/* b6_curriculo_plus.js — Ampliación del banco curricular.
   · Materias nuevas: Biología, Anatomía y fisiología, Física, Química y Geografía.
   · Unidades nuevas en todas las materias existentes, con más bandas de edad cubiertas.
   Cada unidad declara figura (mapa, ciclo, flujo, línea) y vocabulario que los motores
   transversales (EU_SVG, EU_GEO) convierten en páginas visuales. Se registra con EU_EDITORIAL.registrar. */
(function () {
  var ED = window.EU_EDITORIAL;
  if (!ED || ED._curPlus) return;
  ED._curPlus = true;
  var L = [];
  function fig(a) {
    if (!a) return undefined;
    var t = a[0], r = a.slice(1);
    if (t === 'mapa') return { t: 'mapa', c: r[0], r: r.slice(1) };
    if (t === 'linea') return { t: 'linea', h: r.map(function (x) { var p = x.split(':'); return [p[0], p.slice(1).join(':')]; }) };
    return { t: t, p: r };
  }
  function u(m, id, b, t, i, k, vf, q, f, h) {
    L.push({ m: m, id: id, b: b.split(' '), t: t, i: i, k: k, vf: (vf || '').split('|').filter(Boolean).map(function (s) { return [s.slice(2), s.charAt(0) === 'V']; }), q: q || [], f: fig(f), h: h, plus: true });
  }

  /* ─────────── Biología ─────────── */
  u('bio', 'bio_seres', 'pri1 pri2', 'Los seres vivos', ['Los seres vivos nacen, se alimentan, crecen, se reproducen y mueren.', 'Las plantas fabrican su alimento con la luz del sol.', 'Los animales se alimentan de plantas o de otros animales.', 'Los hongos y las bacterias también son seres vivos.'], ['seres vivos', 'plantas', 'animales', 'hongos', 'bacterias'], 'V:Las plantas fabrican su alimento.|F:Una piedra es un ser vivo.|V:Los hongos son seres vivos.', ['Nombra tres seres vivos que veas camino de la escuela.', '¿Qué necesita una planta para crecer?'], ['mapa', 'Seres vivos', 'plantas', 'animales', 'hongos', 'bacterias']);
  u('bio', 'bio_celula', 'pri3 sec', 'La célula', ['La célula es la unidad más pequeña de un ser vivo.', 'Toda célula tiene membrana, citoplasma y material genético.', 'La célula vegetal tiene pared celular y cloroplastos.', 'Las células son tan pequeñas que se observan con el microscopio.'], ['célula', 'membrana', 'citoplasma', 'núcleo', 'microscopio'], 'V:La célula vegetal tiene cloroplastos.|F:Las células se ven siempre a simple vista.|V:Todas las células tienen membrana.', ['¿En qué se diferencia una célula animal de una vegetal?', '¿Por qué necesitamos el microscopio para estudiar las células?'], ['mapa', 'Célula', 'membrana', 'citoplasma', 'núcleo', 'orgánulos'], 'La escala del dibujo te dice cuántas veces está aumentada la célula.');
  u('bio', 'bio_foto', 'pri3 sec', 'La fotosíntesis', ['La fotosíntesis es el proceso con el que las plantas fabrican su alimento.', 'La planta toma agua por la raíz y dióxido de carbono del aire.', 'La clorofila de las hojas capta la energía de la luz.', 'Como resultado la planta produce glucosa y libera oxígeno.'], ['fotosíntesis', 'clorofila', 'glucosa', 'oxígeno', 'dióxido de carbono'], 'V:La fotosíntesis libera oxígeno.|F:La clorofila está en la raíz.|V:La planta usa dióxido de carbono.', ['¿Por qué decimos que los bosques son los pulmones del planeta?', 'Explica qué pasaría con una planta guardada en un armario oscuro.'], ['flujo', 'luz solar', 'agua y dióxido de carbono', 'clorofila', 'glucosa', 'oxígeno']);
  u('bio', 'bio_genetica', 'sec bach', 'Herencia y genética', ['Los genes son fragmentos de ADN que llevan la información de los caracteres.', 'Cada persona recibe la mitad de sus genes del padre y la otra mitad de la madre.', 'Un alelo dominante se expresa aunque solo haya una copia.', 'Mendel estudió la herencia cruzando plantas de guisante.'], ['gen', 'ADN', 'alelo', 'dominante', 'recesivo'], 'V:Mendel trabajó con guisantes.|F:Un alelo recesivo se expresa siempre.|V:El ADN guarda la información genética.', ['¿Por qué dos hermanos no son idénticos si tienen los mismos padres?', 'Explica qué es un carácter recesivo con un ejemplo.'], ['flujo', 'ADN', 'gen', 'alelo', 'carácter'], null);
  u('bio', 'bio_ecosis', 'pri2 pri3 sec', 'Ecosistemas y cadenas tróficas', ['Un ecosistema está formado por los seres vivos y el lugar donde viven.', 'Los productores fabrican su alimento; los consumidores comen a otros seres.', 'Los descomponedores transforman los restos en nutrientes del suelo.', 'Una cadena trófica muestra quién se come a quién.'], ['ecosistema', 'productores', 'consumidores', 'descomponedores', 'cadena trófica'], 'V:Las plantas son productores.|F:Los descomponedores fabrican su alimento con luz.|V:El conejo es un consumidor.', ['Dibuja una cadena trófica con cuatro seres vivos de tu región.', '¿Qué pasaría si desaparecieran los descomponedores?'], ['flujo', 'sol', 'hierba', 'conejo', 'zorro', 'descomponedores']);
  u('bio', 'bio_evol', 'bach adu', 'Evolución y biodiversidad', ['Las especies cambian a lo largo de muchas generaciones.', 'La selección natural favorece a los individuos mejor adaptados.', 'Los fósiles son pruebas de seres vivos que existieron hace millones de años.', 'La biodiversidad es la variedad de especies de un lugar.'], ['evolución', 'selección natural', 'fósiles', 'adaptación', 'biodiversidad'], 'V:Los fósiles son pruebas de la evolución.|F:Las especies nunca cambian.|V:La selección natural favorece a los mejor adaptados.', ['Pon un ejemplo de adaptación de un animal a su medio.', '¿Por qué es importante proteger la biodiversidad?'], ['linea', '3500 M:primeras bacterias', '540 M:explosión del Cámbrico', '230 M:primeros dinosaurios', '66 M:extinción de los dinosaurios', '0,3 M:Homo sapiens']);
  u('bio', 'bio_simetria', 'pri2 pri3 sec', 'Formas y simetrías en la naturaleza', ['Muchos animales tienen simetría bilateral: un eje los divide en dos mitades iguales.', 'La estrella de mar y muchas flores tienen simetría radial.', 'Las celdas hexagonales del panal aprovechan al máximo el espacio.', 'La concha del caracol crece siguiendo una espiral.'], ['simetría bilateral', 'simetría radial', 'eje', 'hexágono', 'espiral'], 'V:La mariposa tiene simetría bilateral.|F:La estrella de mar tiene simetría bilateral.|V:El panal está formado por hexágonos.', ['Busca tres objetos naturales con simetría y dibuja su eje.', '¿Por qué crees que las abejas construyen celdas hexagonales?'], ['mapa', 'Simetría', 'bilateral', 'radial', 'espiral', 'teselas']);

  /* ─────────── Anatomía y fisiología ─────────── */
  u('anat', 'ana_cuerpo', 'pri1 pri2', 'Las partes del cuerpo', ['El cuerpo tiene cabeza, tronco y extremidades.', 'Las extremidades superiores son los brazos y las inferiores, las piernas.', 'Los sentidos nos ayudan a conocer lo que nos rodea.', 'El cuerpo es casi igual por la derecha que por la izquierda.'], ['cabeza', 'tronco', 'extremidades', 'sentidos'], 'V:Las piernas son extremidades inferiores.|F:El tronco es una extremidad.|V:Tenemos cinco sentidos.', ['Nombra los cinco sentidos y el órgano de cada uno.', '¿Qué parte del cuerpo usas para correr?'], ['mapa', 'Cuerpo', 'cabeza', 'tronco', 'brazos', 'piernas']);
  u('anat', 'ana_proporcion', 'pri3 sec bach', 'Proporciones del cuerpo humano', ['Los artistas miden el cuerpo tomando la cabeza como unidad.', 'Un adulto mide unas ocho cabezas de alto.', 'Con los brazos extendidos, la envergadura es casi igual a la altura.', 'El ombligo divide el cuerpo cerca de la proporción áurea.'], ['proporción', 'canon', 'envergadura', 'unidad de medida', 'proporción áurea'], 'V:La envergadura es parecida a la altura.|F:Un adulto mide unas tres cabezas.|V:La cabeza sirve como unidad de medida.', ['Mide tu envergadura y tu altura. ¿Se parecen?', '¿Por qué un bebé tiene la cabeza más grande en proporción?'], ['mapa', 'Canon humano', 'cabeza', 'tronco', 'brazos', 'piernas'], 'Usa la altura de la cabeza como regla.');
  u('anat', 'ana_huesos', 'pri2 pri3 sec', 'El esqueleto y las articulaciones', ['El esqueleto adulto tiene 206 huesos.', 'Los huesos sostienen el cuerpo y protegen los órganos.', 'Las articulaciones unen los huesos y permiten el movimiento.', 'La rodilla funciona como una bisagra: se dobla en un solo sentido.'], ['esqueleto', 'huesos', 'articulaciones', 'cráneo', 'columna vertebral'], 'V:El cráneo protege el cerebro.|F:El esqueleto adulto tiene 50 huesos.|V:La rodilla es una articulación.', ['¿Qué articulaciones usas al escribir?', 'Mide el ángulo que forma tu codo al doblarlo.'], ['mapa', 'Esqueleto', 'cráneo', 'columna vertebral', 'costillas', 'fémur']);
  u('anat', 'ana_circ', 'pri3 sec bach', 'El aparato circulatorio', ['El corazón es un músculo que bombea la sangre.', 'Las arterias llevan la sangre desde el corazón y las venas la devuelven.', 'Los capilares son vasos finísimos que llegan a todas las células.', 'La sangre reparte oxígeno y nutrientes y recoge los desechos.'], ['corazón', 'arterias', 'venas', 'capilares', 'sangre'], 'V:Las arterias salen del corazón.|F:Las venas llevan la sangre desde el corazón.|V:El corazón es un músculo.', ['Toma tu pulso durante un minuto en reposo y después de saltar.', '¿Por qué el corazón late más rápido al hacer ejercicio?'], ['ciclo', 'corazón', 'arterias', 'capilares', 'venas']);
  u('anat', 'ana_resp', 'pri3 sec', 'El aparato respiratorio', ['Al inspirar entra aire por la nariz y llega a los pulmones.', 'En los alvéolos el oxígeno pasa a la sangre.', 'Al espirar expulsamos dióxido de carbono.', 'El diafragma es el músculo principal de la respiración.'], ['pulmones', 'alvéolos', 'diafragma', 'tráquea', 'oxígeno'], 'V:El oxígeno pasa a la sangre en los alvéolos.|F:El diafragma está en la cabeza.|V:Espiramos dióxido de carbono.', ['Cuenta cuántas veces respiras en un minuto.', '¿Por qué el aire contaminado daña los pulmones?'], ['flujo', 'nariz', 'tráquea', 'bronquios', 'pulmones', 'alvéolos']);
  u('anat', 'ana_nervioso', 'sec bach adu', 'El sistema nervioso', ['El sistema nervioso coordina todo lo que hace el cuerpo.', 'Las neuronas transmiten impulsos eléctricos.', 'El encéfalo y la médula espinal forman el sistema nervioso central.', 'Un acto reflejo es una respuesta rápida que no pasa por la conciencia.'], ['neuronas', 'encéfalo', 'médula espinal', 'impulso nervioso', 'acto reflejo'], 'V:Las neuronas transmiten impulsos.|F:La médula espinal está en el pie.|V:Retirar la mano del fuego es un acto reflejo.', ['Describe un acto reflejo que hayas tenido.', '¿Qué hábitos cuidan el sistema nervioso?'], ['flujo', 'estímulo', 'receptor', 'neurona sensitiva', 'médula', 'respuesta']);

  /* ─────────── Física ─────────── */
  u('fisica', 'fis_fuerzas', 'pri3 sec', 'Las fuerzas', ['Una fuerza puede mover un cuerpo, pararlo o deformarlo.', 'Las fuerzas se representan con flechas llamadas vectores.', 'Si dos fuerzas son perpendiculares, la resultante se calcula con el teorema de Pitágoras.', 'La fuerza se mide en newtons (N) con un dinamómetro.'], ['fuerza', 'vector', 'resultante', 'newton', 'dinamómetro'], 'V:La fuerza se mide en newtons.|F:Una fuerza nunca deforma un cuerpo.|V:Las fuerzas se dibujan con flechas.', ['Nombra tres fuerzas que actúan sobre ti ahora mismo.', '¿Qué ocurre si dos personas empujan una caja con la misma fuerza en sentidos contrarios?'], ['mapa', 'Fuerza', 'intensidad', 'dirección', 'sentido', 'punto de aplicación']);
  u('fisica', 'fis_mov', 'sec bach', 'El movimiento', ['La velocidad es la distancia recorrida dividida entre el tiempo.', 'En el movimiento uniforme la velocidad no cambia.', 'La aceleración indica cuánto cambia la velocidad cada segundo.', 'La gráfica posición–tiempo de un movimiento uniforme es una recta.'], ['velocidad', 'aceleración', 'trayectoria', 'movimiento uniforme', 'gráfica'], 'V:v = d ÷ t.|F:En el movimiento uniforme la velocidad cambia.|V:La aceleración mide cambios de velocidad.', ['Calcula tu velocidad caminando 100 m.', '¿Por qué un coche frena antes en seco que en mojado?'], ['flujo', 'reposo', 'aceleración', 'velocidad constante', 'frenado']);
  u('fisica', 'fis_densidad', 'pri3 sec', 'Masa, volumen y densidad', ['La masa es la cantidad de materia de un cuerpo.', 'El volumen es el espacio que ocupa; en un cubo se calcula lado × lado × lado.', 'La densidad es la masa dividida entre el volumen.', 'Un cuerpo flota en agua si su densidad es menor de 1 g/cm³.'], ['masa', 'volumen', 'densidad', 'flotación', 'cubo'], 'V:La madera flota porque es menos densa que el agua.|F:El hierro flota en el agua.|V:d = m ÷ V.', ['¿Por qué un barco de hierro flota?', 'Busca en casa dos objetos del mismo tamaño y distinta masa.'], ['mapa', 'Materia', 'masa', 'volumen', 'densidad', 'flotación']);
  u('fisica', 'fis_energia', 'pri2 pri3 sec', 'La energía y sus formas', ['La energía es la capacidad de producir cambios.', 'Existen energía cinética, potencial, térmica, eléctrica y luminosa.', 'La energía no se crea ni se destruye: se transforma.', 'Las energías renovables vienen del sol, el viento y el agua.'], ['energía', 'cinética', 'potencial', 'renovable', 'transformación'], 'V:La energía se transforma.|F:El petróleo es una energía renovable.|V:Un objeto en movimiento tiene energía cinética.', ['Describe las transformaciones de energía en una bombilla.', '¿Qué energía renovable se podría usar en tu región?'], ['ciclo', 'sol', 'viento', 'agua', 'electricidad']);
  u('fisica', 'fis_optica', 'sec bach', 'Luz y óptica', ['La luz viaja en línea recta a unos 300 000 km/s.', 'En la reflexión el ángulo de incidencia es igual al de reflexión.', 'La refracción es el cambio de dirección de la luz al cambiar de medio.', 'Las lentes convergentes concentran los rayos en un foco.'], ['luz', 'reflexión', 'refracción', 'lente', 'ángulo de incidencia'], 'V:El ángulo de incidencia es igual al de reflexión.|F:La luz viaja en curva por el aire.|V:Una lupa es una lente convergente.', ['¿Por qué un lápiz parece partido dentro de un vaso de agua?', 'Dibuja cómo se refleja un rayo en un espejo.'], ['flujo', 'fuente de luz', 'rayo incidente', 'espejo', 'rayo reflejado']);
  u('fisica', 'fis_palanca', 'pri3 sec', 'Máquinas simples y palancas', ['Una palanca es una barra que gira sobre un punto de apoyo.', 'La ley de la palanca dice: fuerza × brazo = resistencia × brazo.', 'Cuanto más largo es el brazo de la fuerza, menos esfuerzo hace falta.', 'El plano inclinado y la polea también son máquinas simples.'], ['palanca', 'punto de apoyo', 'brazo', 'polea', 'plano inclinado'], 'V:Un balancín es una palanca.|F:Con un brazo más corto se hace menos fuerza.|V:La polea es una máquina simple.', ['Nombra tres palancas que uses cada día.', '¿Por qué es más fácil abrir una puerta empujando lejos de las bisagras?'], ['mapa', 'Máquinas simples', 'palanca', 'polea', 'rueda', 'plano inclinado']);

  /* ─────────── Química ─────────── */
  u('quimica', 'qui_materia', 'pri2 pri3 sec', 'Estados de la materia', ['La materia puede estar en estado sólido, líquido o gaseoso.', 'Los sólidos tienen forma fija; los líquidos toman la forma del recipiente.', 'Al calentar el hielo se funde; al calentar el agua se evapora.', 'Las partículas de un gas se mueven libres y ocupan todo el espacio.'], ['sólido', 'líquido', 'gaseoso', 'fusión', 'evaporación'], 'V:El agua líquida toma la forma del vaso.|F:Un gas tiene forma fija.|V:El hielo se funde con el calor.', ['Describe el ciclo del agua usando los estados de la materia.', '¿Por qué se empaña el espejo del baño?'], ['ciclo', 'sólido', 'fusión', 'líquido', 'evaporación', 'gas', 'condensación']);
  u('quimica', 'qui_atomo', 'sec bach', 'El átomo y la tabla periódica', ['El átomo tiene un núcleo con protones y neutrones, rodeado de electrones.', 'El número atómico es el número de protones.', 'La tabla periódica ordena los elementos por su número atómico.', 'Los elementos de una misma columna tienen propiedades parecidas.'], ['átomo', 'protones', 'electrones', 'número atómico', 'tabla periódica'], 'V:El número atómico indica los protones.|F:Los electrones están en el núcleo.|V:La tabla periódica ordena los elementos.', ['¿Qué elemento químico está presente en todos los seres vivos?', 'Busca tres metales de la tabla periódica y di para qué se usan.'], ['mapa', 'Átomo', 'protones', 'neutrones', 'electrones', 'núcleo']);
  u('quimica', 'qui_molecula', 'sec bach', 'Moléculas y geometría molecular', ['Una molécula es un grupo de átomos unidos por enlaces.', 'La molécula de agua es angular: sus enlaces forman unos 104,5°.', 'El metano es tetraédrico, con ángulos de 109,5°.', 'La forma de una molécula explica muchas de sus propiedades.'], ['molécula', 'enlace', 'ángulo de enlace', 'tetraédrica', 'angular'], 'V:El agua es una molécula angular.|F:El dióxido de carbono es angular.|V:El metano tiene forma tetraédrica.', ['¿Por qué el hielo flota sobre el agua líquida?', 'Construye con plastilina y palillos una molécula de metano.'], ['mapa', 'Geometría molecular', 'lineal', 'angular', 'piramidal', 'tetraédrica']);
  u('quimica', 'qui_mezclas', 'pri3 sec', 'Mezclas y disoluciones', ['Una mezcla une dos o más sustancias sin que cambien.', 'En una disolución el soluto se disuelve en el disolvente.', 'La concentración indica cuánto soluto hay en cada litro de disolución.', 'Las mezclas se separan por filtración, decantación o evaporación.'], ['mezcla', 'disolución', 'soluto', 'disolvente', 'concentración'], 'V:En agua con sal, el agua es el disolvente.|F:La filtración separa la sal del agua.|V:La concentración se mide en g/L.', ['Prepara agua con azúcar y explica cuál es el soluto.', '¿Cómo separarías arena mezclada con agua?'], ['flujo', 'mezcla', 'filtración', 'decantación', 'evaporación']);
  u('quimica', 'qui_reaccion', 'sec bach adu', 'Reacciones químicas', ['En una reacción química unas sustancias se transforman en otras.', 'Los reactivos son las sustancias iniciales y los productos, las finales.', 'En toda reacción la masa total se conserva.', 'La combustión y la oxidación son reacciones cotidianas.'], ['reacción química', 'reactivos', 'productos', 'combustión', 'oxidación'], 'V:La masa se conserva en una reacción.|F:Fundir hielo es una reacción química.|V:La oxidación del hierro es una reacción.', ['Nombra dos reacciones químicas que ocurran en la cocina.', '¿Por qué se oxida una manzana cortada?'], ['flujo', 'reactivos', 'energía', 'reacción', 'productos']);

  /* ─────────── Geografía ─────────── */
  u('geografia', 'geo_plano', 'pri1 pri2', 'Planos y croquis', ['Un plano es un dibujo de un lugar visto desde arriba.', 'La leyenda explica qué significa cada símbolo.', 'La cuadrícula nos ayuda a localizar lugares.', 'Los planos se dibujan más pequeños que la realidad.'], ['plano', 'leyenda', 'símbolo', 'cuadrícula'], 'V:Un plano se dibuja visto desde arriba.|F:La leyenda es el título del mapa.|V:La cuadrícula sirve para localizar.', ['Dibuja el plano de tu habitación.', '¿Qué símbolo usarías para un parque?'], ['mapa', 'Plano', 'leyenda', 'símbolos', 'cuadrícula', 'orientación']);
  u('geografia', 'geo_escala', 'pri3 sec', 'La escala de los mapas', ['La escala indica cuántas veces se ha reducido la realidad.', 'Una escala 1:100 000 significa que 1 cm del mapa son 1 km reales.', 'La escala gráfica es una barra dividida en tramos.', 'Con la escala calculamos distancias reales entre ciudades.'], ['escala', 'escala numérica', 'escala gráfica', 'distancia real', 'kilómetro'], 'V:Con la escala se calculan distancias reales.|F:La escala 1:100 000 significa 1 cm = 1 m.|V:La escala gráfica es una barra.', ['Mide en un mapa la distancia entre dos ciudades de tu país.', '¿Qué mapa tiene más detalle: 1:10 000 o 1:1 000 000?'], ['mapa', 'Escala', 'numérica', 'gráfica', 'distancia real']);
  u('geografia', 'geo_coord', 'pri3 sec bach', 'Latitud, longitud y husos horarios', ['Los paralelos son líneas horizontales; el principal es el ecuador.', 'Los meridianos van de polo a polo; el principal es el de Greenwich.', 'La latitud y la longitud forman las coordenadas geográficas.', 'Cada 15° de longitud la hora cambia una hora.'], ['latitud', 'longitud', 'ecuador', 'meridiano', 'huso horario'], 'V:El ecuador es un paralelo.|F:Greenwich es un paralelo.|V:Cada 15° la hora cambia una hora.', ['¿En qué hemisferio está tu país?', 'Si en Madrid son las 12:00, ¿qué hora es en {ciudad}?'], ['mapa', 'Coordenadas', 'latitud', 'longitud', 'paralelos', 'meridianos']);
  u('geografia', 'geo_relieve', 'pri2 pri3 sec', 'El relieve y las aguas', ['El relieve son las formas de la superficie terrestre.', 'Las montañas, las mesetas y las llanuras son formas del relieve interior.', 'Los ríos nacen en las montañas y desembocan en el mar o en un lago.', 'Las curvas de nivel unen puntos de igual altitud.'], ['relieve', 'montaña', 'llanura', 'río', 'curvas de nivel'], 'V:Los ríos desembocan en el mar o en lagos.|F:Una llanura es muy montañosa.|V:Las curvas de nivel unen puntos de igual altura.', ['Nombra el río más largo de tu país.', '¿Por qué muchas ciudades están junto a un río?'], ['flujo', 'nacimiento', 'curso alto', 'curso medio', 'curso bajo', 'desembocadura']);
  u('geografia', 'geo_poblacion', 'sec bach adu', 'Población y ciudades', ['La densidad de población es habitantes divididos entre kilómetros cuadrados.', 'La pirámide de población muestra habitantes por edad y sexo.', 'Hoy la mayoría de la población mundial vive en ciudades.', 'Las migraciones cambian la población de los territorios.'], ['densidad de población', 'pirámide de población', 'urbanización', 'migración', 'censo'], 'V:Densidad = habitantes ÷ km².|F:La mayoría de la población vive en el campo.|V:El censo cuenta a los habitantes.', ['Calcula la densidad de tu municipio.', '¿Por qué la gente migra del campo a la ciudad?'], ['mapa', 'Población', 'densidad', 'natalidad', 'mortalidad', 'migración']);
  u('geografia', 'geo_clima', 'pri3 sec', 'Tiempo atmosférico y clima', ['El tiempo es el estado de la atmósfera en un momento.', 'El clima es el tiempo habitual de un lugar durante muchos años.', 'La temperatura se mide con el termómetro y la lluvia con el pluviómetro.', 'Un climograma muestra temperaturas y lluvias de cada mes.'], ['tiempo atmosférico', 'clima', 'temperatura', 'precipitación', 'climograma'], 'V:El pluviómetro mide la lluvia.|F:Tiempo y clima son lo mismo.|V:Un climograma combina barras y línea.', ['Anota la temperatura durante una semana.', '¿Qué clima tiene tu región?'], ['mapa', 'Clima', 'temperatura', 'precipitación', 'viento', 'humedad']);

  /* ─────────── Materias existentes ─────────── */
  u('mate', 'mat_geo_plana', 'pri2 pri3', 'Polígonos, perímetro y área', ['Un polígono es una figura plana cerrada con lados rectos.', 'El perímetro es la suma de los lados.', 'El área del rectángulo es base por altura.', 'Un polígono regular tiene todos sus lados y ángulos iguales.'], ['polígono', 'perímetro', 'área', 'lado', 'polígono regular'], 'V:El área del rectángulo es base × altura.|F:El perímetro se mide en m².|V:El cuadrado es un polígono regular.', ['Calcula el perímetro de tu mesa.', '¿Cuántos cuadrados de 1 m² caben en tu aula?'], ['mapa', 'Polígonos', 'triángulo', 'cuadrilátero', 'pentágono', 'hexágono']);
  u('mate', 'mat_simetria', 'pri1 pri2 pri3', 'Simetría y giros', ['Una figura es simétrica si un eje la divide en dos mitades iguales.', 'Al doblar por el eje de simetría, las dos mitades coinciden.', 'En un giro la figura da vueltas alrededor de un punto.', 'Los mosaicos repiten una figura sin dejar huecos.'], ['simetría', 'eje de simetría', 'giro', 'traslación', 'mosaico'], 'V:El cuadrado tiene cuatro ejes de simetría.|F:Todas las figuras tienen simetría.|V:Un mosaico no deja huecos.', ['Busca en tu casa un objeto con simetría.', 'Diseña un mosaico con una sola figura.'], ['mapa', 'Movimientos', 'simetría', 'giro', 'traslación', 'mosaico']);
  u('mate', 'mat_pitagoras', 'sec bach', 'El teorema de Pitágoras', ['En un triángulo rectángulo, el lado mayor se llama hipotenusa.', 'Los otros dos lados son los catetos.', 'El cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos.', 'Los albañiles usan el triángulo 3-4-5 para trazar ángulos rectos.'], ['hipotenusa', 'catetos', 'triángulo rectángulo', 'ángulo recto', 'cuadrado'], 'V:3² + 4² = 5².|F:La hipotenusa es el lado más corto.|V:El teorema vale solo en triángulos rectángulos.', ['¿Cómo comprobarías si la esquina de una habitación es recta?', 'Calcula la diagonal de la pantalla de un televisor.'], ['mapa', 'Pitágoras', 'hipotenusa', 'cateto', 'ángulo recto']);
  u('mate', 'mat_estad', 'pri3 sec bach adu', 'Estadística y probabilidad', ['La media es la suma de los datos dividida entre cuántos hay.', 'La moda es el dato que más se repite.', 'La mediana es el valor central al ordenar los datos.', 'La probabilidad se calcula como casos favorables entre casos posibles.'], ['media', 'moda', 'mediana', 'probabilidad', 'frecuencia'], 'V:La moda es el dato más repetido.|F:La probabilidad puede ser mayor que 1.|V:La mediana es el valor central.', ['Haz una encuesta en clase y calcula la moda.', '¿Qué probabilidad hay de sacar un 6 con un dado?'], ['mapa', 'Estadística', 'media', 'moda', 'mediana', 'gráficos']);

  u('arte', 'art_color', 'inf pri1 pri2', 'El color', ['Los colores primarios son el amarillo, el cian y el magenta.', 'Al mezclar dos primarios obtenemos un secundario.', 'Los colores cálidos recuerdan al fuego; los fríos, al agua.', 'Los colores complementarios están enfrentados en el círculo cromático.'], ['colores primarios', 'colores secundarios', 'cálidos', 'fríos', 'círculo cromático'], 'V:Amarillo y cian dan verde.|F:El azul es un color cálido.|V:El círculo cromático ordena los colores.', ['Pinta un paisaje solo con colores fríos.', '¿Qué colores usarías para un cartel de verano?'], ['ciclo', 'amarillo', 'verde', 'cian', 'violeta', 'magenta', 'naranja']);
  u('arte', 'art_geometria', 'pri3 sec bach', 'Geometría en el arte y el diseño', ['Los rosetones de las catedrales se construyen con polígonos regulares.', 'Los mosaicos islámicos repiten estrellas y polígonos sin dejar huecos.', 'El rectángulo áureo tiene sus lados en proporción 1 : 1,618.', 'Muchos logotipos se basan en círculos y cuadrados.'], ['rosetón', 'polígono regular', 'mosaico', 'rectángulo áureo', 'proporción'], 'V:El rectángulo áureo usa la proporción 1,618.|F:Los mosaicos dejan huecos entre piezas.|V:Los rosetones usan polígonos regulares.', ['Diseña un logotipo solo con círculos y rectas.', 'Busca un edificio de tu ciudad con formas geométricas.'], ['mapa', 'Geometría y arte', 'rosetón', 'mosaico', 'proporción áurea', 'logotipo']);
  u('arte', 'art_perspectiva', 'sec bach fp', 'La perspectiva', ['La perspectiva representa el volumen sobre un papel plano.', 'En la perspectiva cónica las líneas se juntan en un punto de fuga.', 'La perspectiva isométrica usa ejes a 120° y no deforma las medidas.', 'La línea del horizonte está a la altura de los ojos del observador.'], ['perspectiva', 'punto de fuga', 'isométrica', 'línea del horizonte', 'volumen'], 'V:La isométrica usa ejes a 120°.|F:En la cónica las líneas nunca se juntan.|V:El horizonte está a la altura de los ojos.', ['Dibuja una calle con un punto de fuga.', 'Dibuja tu estuche en perspectiva isométrica.'], ['mapa', 'Perspectiva', 'cónica', 'isométrica', 'caballera', 'punto de fuga']);
  u('arte', 'art_figura', 'pri3 sec bach', 'La figura humana', ['Para dibujar la figura humana se usa la cabeza como medida.', 'El canon clásico mide ocho cabezas.', 'Un maniquí de líneas y óvalos ayuda a encajar la postura.', 'Las articulaciones marcan dónde se dobla la figura.'], ['canon', 'proporción', 'encaje', 'maniquí', 'articulaciones'], 'V:El canon clásico mide ocho cabezas.|F:La figura se dibuja empezando por los detalles.|V:Los óvalos ayudan a encajar la figura.', ['Dibuja a un compañero sentado usando óvalos.', 'Compara un dibujo de un niño y de un adulto: ¿qué proporciones cambian?'], ['flujo', 'encaje', 'proporción', 'volumen', 'detalle']);
  u('arte', 'art_textura', 'inf pri1 pri2', 'Líneas, formas y texturas', ['Con líneas rectas, curvas y quebradas creamos dibujos.', 'Las formas pueden ser geométricas u orgánicas.', 'La textura es cómo se siente o se ve una superficie.', 'Con puntos y rayas podemos imitar texturas.'], ['línea', 'forma', 'textura', 'geométrica', 'orgánica'], 'V:Un círculo es una forma geométrica.|F:Una hoja es una forma geométrica.|V:Con puntos imitamos texturas.', ['Haz un dibujo solo con líneas curvas.', 'Frota un lápiz sobre una hoja de árbol y describe la textura.'], ['mapa', 'Lenguaje visual', 'punto', 'línea', 'forma', 'textura']);

  u('lengua', 'len_poesia', 'pri2 pri3 sec', 'La poesía', ['Un poema se escribe en versos agrupados en estrofas.', 'La rima es la repetición de sonidos al final de los versos.', 'Contamos las sílabas métricas para medir un verso.', 'Las figuras literarias, como la comparación, embellecen el lenguaje.'], ['verso', 'estrofa', 'rima', 'sílabas métricas', 'comparación'], 'V:Los versos se agrupan en estrofas.|F:Todos los poemas riman.|V:La comparación es una figura literaria.', ['Escribe cuatro versos que rimen sobre {comida}.', 'Busca una comparación en una canción que te guste.'], ['mapa', 'Poesía', 'verso', 'estrofa', 'rima', 'metáfora']);
  u('lengua', 'len_argumento', 'sec bach adu', 'El texto argumentativo', ['Un texto argumentativo defiende una opinión llamada tesis.', 'Los argumentos son las razones que apoyan la tesis.', 'Los conectores como «por tanto» o «sin embargo» enlazan las ideas.', 'La conclusión resume y refuerza la postura.'], ['tesis', 'argumentos', 'contraargumento', 'conectores', 'conclusión'], 'V:La tesis es la opinión que se defiende.|F:Un texto argumentativo no necesita razones.|V:«Sin embargo» es un conector.', ['Escribe una tesis sobre el uso del móvil en clase.', 'Busca un argumento en un anuncio publicitario.'], ['flujo', 'introducción', 'tesis', 'argumentos', 'contraargumento', 'conclusión']);
  u('lengua', 'len_medios', 'pri3 sec adu', 'La noticia y los medios', ['La noticia informa de un hecho reciente y verdadero.', 'Responde a qué, quién, cuándo, dónde, cómo y por qué.', 'Tiene titular, entradilla y cuerpo.', 'Contrastar fuentes ayuda a detectar noticias falsas.'], ['noticia', 'titular', 'entradilla', 'cuerpo', 'fuentes'], 'V:El titular resume la noticia.|F:Las noticias cuentan hechos inventados.|V:Contrastar fuentes evita bulos.', ['Escribe un titular sobre algo que pasó hoy en tu escuela.', '¿Cómo sabes si una noticia es falsa?'], ['flujo', 'titular', 'entradilla', 'cuerpo', 'cierre']);

  u('natu', 'nat_universo', 'pri2 pri3 sec', 'El universo y el sistema solar', ['El sistema solar está formado por el Sol y los cuerpos que giran a su alrededor.', 'Hay ocho planetas; la Tierra es el tercero.', 'La Tierra gira sobre sí misma en un día y alrededor del Sol en un año.', 'La Luna es el satélite natural de la Tierra.'], ['sistema solar', 'planeta', 'rotación', 'traslación', 'satélite'], 'V:La Tierra es el tercer planeta.|F:La Luna es un planeta.|V:La traslación dura un año.', ['¿Por qué hay día y noche?', 'Dibuja las fases de la Luna durante una semana.'], ['ciclo', 'luna nueva', 'cuarto creciente', 'luna llena', 'cuarto menguante']);
  u('natu', 'nat_agua', 'pri1 pri2 pri3', 'El agua y su ciclo', ['El agua cubre casi tres cuartas partes de la Tierra.', 'El sol calienta el agua y la evapora.', 'El vapor se condensa en nubes y cae como lluvia.', 'El agua dulce es escasa y hay que cuidarla.'], ['evaporación', 'condensación', 'precipitación', 'agua dulce', 'nubes'], 'V:La mayor parte del agua es salada.|F:Las nubes están hechas de humo.|V:La lluvia es una precipitación.', ['Escribe tres maneras de ahorrar agua en casa.', '¿De dónde viene el agua del grifo de tu casa?'], ['ciclo', 'evaporación', 'condensación', 'precipitación', 'escorrentía']);
  u('natu', 'nat_medir', 'pri2 pri3 sec', 'Medir en el laboratorio', ['El volumen de un líquido se mide con probetas y vasos graduados.', 'Hay que leer el nivel a la altura de los ojos.', 'La masa se mide con la balanza y la temperatura con el termómetro.', 'Un litro equivale a mil mililitros.'], ['probeta', 'volumen', 'mililitro', 'balanza', 'termómetro'], 'V:1 L = 1000 mL.|F:La probeta mide la masa.|V:El nivel se lee a la altura de los ojos.', ['Mide con una jarra cuánta agua cabe en un vaso.', '¿Por qué es importante medir con precisión?'], ['flujo', 'observar', 'medir', 'anotar', 'concluir']);
  u('natu', 'nat_salud', 'pri1 pri2 pri3', 'Hábitos saludables', ['Una dieta equilibrada incluye frutas, verduras, cereales y proteínas.', 'Dormir bien ayuda al cuerpo a crecer y a recuperarse.', 'El ejercicio fortalece el corazón y los músculos.', 'Lavarse las manos evita muchas enfermedades.'], ['dieta equilibrada', 'descanso', 'ejercicio', 'higiene', 'proteínas'], 'V:Lavarse las manos evita enfermedades.|F:Dormir poco ayuda a crecer.|V:El ejercicio fortalece el corazón.', ['Diseña el menú de un día equilibrado con {comida}.', '¿Cuántas horas duermes cada noche?'], ['mapa', 'Salud', 'alimentación', 'descanso', 'ejercicio', 'higiene']);

  u('soci', 'soc_paisaje', 'pri1 pri2', 'El paisaje de mi entorno', ['El paisaje es todo lo que vemos a nuestro alrededor.', 'Hay paisajes naturales y paisajes transformados por las personas.', 'En el paisaje de montaña hay cumbres, laderas y valles.', 'En la costa encontramos playas, acantilados y puertos.'], ['paisaje', 'montaña', 'costa', 'valle', 'ciudad'], 'V:Un puerto transforma el paisaje.|F:Una ciudad es un paisaje natural.|V:El valle está entre montañas.', ['Describe el paisaje que ves desde tu ventana.', '¿Qué cambiarías del paisaje de tu barrio?'], ['mapa', 'Paisaje', 'montaña', 'llanura', 'costa', 'ciudad']);
  u('soci', 'soc_america', 'pri3 sec', 'América: territorio y países', ['América es un continente que va del polo norte casi hasta la Antártida.', 'Se divide en América del Norte, Central y del Sur.', 'La cordillera de los Andes recorre el oeste de América del Sur.', 'El Amazonas es el río más caudaloso del mundo.'], ['continente', 'cordillera', 'Andes', 'Amazonas', 'Caribe'], 'V:Los Andes están en América del Sur.|F:El Amazonas está en Europa.|V:El Caribe está en América Central.', ['Localiza tu país en el mapa de América.', '¿Qué países limitan con el tuyo?'], ['mapa', 'América', 'Norte', 'Central', 'Caribe', 'Sur']);
  u('soci', 'soc_economia', 'sec bach adu', 'Sectores económicos', ['El sector primario obtiene recursos de la naturaleza.', 'El sector secundario transforma las materias primas en productos.', 'El sector terciario ofrece servicios como el comercio o la educación.', 'En los países desarrollados predomina el sector terciario.'], ['sector primario', 'sector secundario', 'sector terciario', 'materia prima', 'servicios'], 'V:La pesca es del sector primario.|F:Una escuela es del sector secundario.|V:Una fábrica es del sector secundario.', ['¿En qué sector trabaja tu familia?', 'Sigue el camino del pan: ¿qué sectores participan?'], ['flujo', 'primario', 'secundario', 'terciario', 'consumidor']);
  u('soci', 'soc_ciudadania', 'pri2 pri3 sec', 'Normas y ciudadanía', ['La constitución es la ley más importante de un país.', 'Los ciudadanos tienen derechos y también deberes.', 'Votar es una forma de participar en la vida pública.', 'Los ayuntamientos o alcaldías gestionan los servicios del municipio.'], ['constitución', 'derechos', 'deberes', 'votar', 'municipio'], 'V:La constitución es la ley principal.|F:Los ciudadanos solo tienen derechos.|V:Votar es participar.', ['Escribe tres normas para una buena convivencia en clase.', '¿Qué servicio de tu municipio mejorarías?'], ['mapa', 'Ciudadanía', 'derechos', 'deberes', 'participación', 'normas']);

  u('conta', 'con_nomina', 'fp adu', 'La nómina', ['La nómina es el documento que recoge el salario de un trabajador.', 'El salario bruto es lo que se gana antes de descuentos.', 'Las retenciones y cotizaciones se restan del bruto.', 'El salario neto es lo que se cobra al final.'], ['nómina', 'salario bruto', 'retenciones', 'cotizaciones', 'salario neto'], 'V:Neto = bruto − descuentos.|F:El neto siempre es mayor que el bruto.|V:La nómina es un documento del salario.', ['Calcula el neto de un salario bruto con un 15 % de descuentos.', '¿Para qué sirven las cotizaciones sociales?'], ['flujo', 'salario bruto', 'cotizaciones', 'retenciones', 'salario neto']);
  u('conta', 'con_inventario', 'sec fp adu', 'Inventario y superficie del negocio', ['El inventario es la lista valorada de existencias de un negocio.', 'El coste del local depende de sus metros cuadrados.', 'El rendimiento por metro cuadrado es la venta dividida entre la superficie.', 'Un buen plano del almacén ahorra tiempo y dinero.'], ['inventario', 'existencias', 'metro cuadrado', 'rendimiento', 'almacén'], 'V:El alquiler suele calcularse por m².|F:El inventario es la lista de clientes.|V:Rendimiento = ventas ÷ m².', ['Dibuja el plano de un pequeño almacén y calcula su área.', '¿Qué productos pondrías cerca de la puerta y por qué?'], ['flujo', 'compra', 'almacén', 'venta', 'recuento']);
  u('conta', 'con_ahorro', 'pri3 sec adu', 'Ahorro e interés', ['Ahorrar es guardar una parte del dinero para el futuro.', 'El interés es lo que paga el banco por el dinero depositado.', 'El interés simple se calcula: capital × tipo × tiempo.', 'Un presupuesto ayuda a decidir cuánto ahorrar cada mes.'], ['ahorro', 'interés', 'capital', 'tipo de interés', 'presupuesto'], 'V:El interés simple es capital × tipo × tiempo.|F:Ahorrar es gastarlo todo.|V:El presupuesto ayuda a ahorrar.', ['Calcula cuánto ahorrarías en un año guardando {precio} cada semana.', '¿Para qué te gustaría ahorrar?'], ['flujo', 'ingresos', 'gastos', 'ahorro', 'inversión']);

  u('ingles', 'ing_shapes', 'inf pri1 pri2', 'Shapes and colours', ['A circle is round: the sun is a circle.', 'A square has four equal sides.', 'A triangle has three sides.', 'We say «a red square» with the colour first.'], ['circle', 'square', 'triangle', 'rectangle', 'colour'], 'V:A square has four sides.|F:A triangle has five sides.|V:The sun looks like a circle.', ['Draw three shapes and write their names in English.', 'What shape is your window?'], ['mapa', 'Shapes', 'circle', 'square', 'triangle', 'rectangle']);
  u('ingles', 'ing_body', 'pri1 pri2 pri3', 'My body', ['My head is on top of my body.', 'I have two arms, two hands and ten fingers.', 'I have two legs and two feet.', 'We use «I have got» to talk about our body.'], ['head', 'arms', 'hands', 'legs', 'feet'], 'V:I have two hands.|F:I have three legs.|V:My head is on top.', ['Write five parts of the body in English.', 'Play «Simon says» with your partner.'], ['mapa', 'Body', 'head', 'arms', 'legs', 'feet']);
  u('ingles', 'ing_travel', 'sec bach adu', 'Travel and directions', ['We use «turn left» and «turn right» to give directions.', '«Go straight on» means keep walking in the same direction.', 'A map shows streets, squares and landmarks.', 'We ask «How far is it?» to know the distance.'], ['turn left', 'turn right', 'straight on', 'map', 'distance'], 'V:«Turn left» means girar a la izquierda.|F:«Straight on» means turn back.|V:«How far» asks about distance.', ['Write directions from your school to your home.', 'Plan a trip to another country in English.'], ['flujo', 'start', 'go straight on', 'turn left', 'arrive']);

  u('musica', 'mus_figuras', 'pri1 pri2 pri3', 'Las figuras musicales', ['Las figuras indican cuánto dura cada sonido.', 'Una redonda dura lo mismo que dos blancas.', 'Una blanca dura lo mismo que dos negras.', 'En un compás de 4/4 caben cuatro negras.'], ['redonda', 'blanca', 'negra', 'corchea', 'compás'], 'V:Una blanca vale dos negras.|F:Una negra vale dos blancas.|V:En 4/4 caben cuatro negras.', ['Palmea un ritmo de cuatro negras y una blanca.', '¿Cuántas corcheas caben en una redonda?'], ['flujo', 'redonda', 'blanca', 'negra', 'corchea']);
  u('musica', 'mus_instr', 'pri2 pri3 sec', 'Los instrumentos y el sonido', ['El sonido es una vibración que viaja por el aire.', 'Los instrumentos se agrupan en cuerda, viento y percusión.', 'Una cuerda más corta suena más aguda.', 'El tubo de una flauta más largo da notas más graves.'], ['vibración', 'cuerda', 'viento', 'percusión', 'agudo'], 'V:Una cuerda corta suena más aguda.|F:El tambor es de viento.|V:El sonido es vibración.', ['Llena vasos con distinta agua y golpéalos: ¿cuál suena más agudo?', '¿Qué instrumento típico tiene tu país?'], ['mapa', 'Instrumentos', 'cuerda', 'viento', 'percusión', 'electrónicos']);
  u('musica', 'mus_historia', 'sec bach adu', 'Historia de la música', ['En la Edad Media se cantaba el canto gregoriano.', 'El Barroco trajo la ópera y compositores como Bach.', 'El Clasicismo buscó el equilibrio con Mozart y Haydn.', 'En el siglo XX nacieron el jazz, el rock y la música electrónica.'], ['canto gregoriano', 'Barroco', 'Clasicismo', 'Romanticismo', 'jazz'], 'V:Bach es del Barroco.|F:Mozart es del siglo XX.|V:El jazz nació en el siglo XX.', ['Escucha una obra de Bach y otra de rock: ¿qué cambia?', '¿Qué estilo musical representa a tu país?'], ['linea', '800:canto gregoriano', '1600:Barroco', '1750:Clasicismo', '1820:Romanticismo', '1920:jazz']);

  u('efisica', 'ef_cancha', 'pri2 pri3 sec', 'El terreno de juego', ['Cada deporte tiene una cancha con medidas oficiales.', 'La cancha de voleibol mide 18 m de largo y 9 m de ancho.', 'Las líneas marcan zonas: saque, área y centro.', 'Conocer el espacio ayuda a colocarse bien en el juego.'], ['cancha', 'líneas', 'área', 'perímetro', 'medidas oficiales'], 'V:La cancha de voleibol mide 18 × 9 m.|F:Todas las canchas miden igual.|V:Las líneas marcan zonas del juego.', ['Mide el patio de tu escuela con pasos.', '¿Cuántas vueltas al patio harías para correr 1 km?'], ['mapa', 'Cancha', 'líneas', 'área', 'centro', 'portería']);
  u('efisica', 'ef_movimiento', 'sec bach', 'Biomecánica del movimiento', ['El ángulo de salida influye en la distancia de un lanzamiento.', 'Un ángulo cercano a 45° da el mayor alcance sin rozamiento.', 'Las articulaciones actúan como palancas.', 'Una buena postura reparte el peso y evita lesiones.'], ['ángulo de salida', 'alcance', 'palanca', 'postura', 'articulación'], 'V:45° da el mayor alcance ideal.|F:La postura no influye en las lesiones.|V:Las articulaciones funcionan como palancas.', ['Lanza una pelota con distintos ángulos y mide el alcance.', '¿Qué articulaciones intervienen en un salto?'], ['flujo', 'preparación', 'impulso', 'vuelo', 'caída']);
  u('efisica', 'ef_salud', 'pri3 sec adu', 'Actividad física y salud', ['La frecuencia cardiaca se mide en pulsaciones por minuto.', 'El calentamiento prepara el cuerpo para el esfuerzo.', 'Los estiramientos mejoran la flexibilidad.', 'Se recomienda una hora de actividad física al día.'], ['frecuencia cardiaca', 'calentamiento', 'flexibilidad', 'resistencia', 'estiramientos'], 'V:El calentamiento previene lesiones.|F:Estirar empeora la flexibilidad.|V:El pulso se mide en pulsaciones por minuto.', ['Mide tu pulso antes y después de correr.', 'Diseña un calentamiento de cinco ejercicios.'], ['ciclo', 'calentamiento', 'parte principal', 'vuelta a la calma', 'descanso']);

  u('tecno', 'tec_estruct', 'pri3 sec', 'Estructuras', ['Una estructura soporta pesos sin romperse ni deformarse.', 'El triángulo es la figura más estable porque no se deforma.', 'Las vigas, los pilares y los tirantes son elementos estructurales.', 'Los puentes y las grúas usan triángulos para ser más resistentes.'], ['estructura', 'triangulación', 'viga', 'pilar', 'tirante'], 'V:El triángulo no se deforma.|F:Un cuadrado de barras es más estable que un triángulo.|V:Los puentes usan triángulos.', ['Construye una torre con palillos y plastilina.', '¿Qué estructuras triangulares ves en tu ciudad?'], ['mapa', 'Estructura', 'viga', 'pilar', 'tirante', 'cimiento']);
  u('tecno', 'tec_imp3d', 'sec bach fp adu', 'Diseño 3D e impresión', ['El diseño 3D crea objetos con tres dimensiones: largo, ancho y alto.', 'Las piezas se modelan con prismas, cilindros y esferas.', 'La impresora 3D fabrica la pieza capa a capa.', 'Antes de imprimir se calculan el volumen y el material.'], ['diseño 3D', 'modelado', 'impresora 3D', 'capa', 'volumen'], 'V:La impresora 3D fabrica capa a capa.|F:Un objeto 3D solo tiene largo y ancho.|V:El volumen indica el material.', ['Diseña un llavero con formas geométricas.', '¿Qué objeto útil imprimirías en 3D?'], ['flujo', 'idea', 'boceto', 'modelo 3D', 'impresión', 'prueba']);
  u('tecno', 'tec_programa', 'pri2 pri3 sec', 'Programación por bloques', ['Un programa es una lista de instrucciones en orden.', 'Un bucle repite instrucciones varias veces.', 'Una condición decide qué hacer según lo que pasa.', 'Con bucles y giros de 90° se dibuja un cuadrado.'], ['programa', 'instrucción', 'bucle', 'condición', 'algoritmo'], 'V:Un bucle repite instrucciones.|F:El orden de las instrucciones no importa.|V:Cuatro giros de 90° cierran un cuadrado.', ['Escribe el algoritmo para lavarte los dientes.', '¿Cuántos grados debe girar para dibujar un triángulo equilátero?'], ['flujo', 'inicio', 'repetir 4 veces', 'avanzar', 'girar 90°', 'fin']);

  u('valores', 'val_emociones', 'inf pri1 pri2', 'Mis emociones', ['Las emociones básicas son alegría, tristeza, miedo, enfado y sorpresa.', 'Todas las emociones son válidas.', 'Respirar despacio ayuda a calmar el enfado.', 'Hablar de lo que sentimos nos hace sentir mejor.'], ['alegría', 'tristeza', 'miedo', 'enfado', 'calma'], 'V:Respirar despacio ayuda a calmarse.|F:Está mal sentir tristeza.|V:Hablar de emociones ayuda.', ['Dibuja tu cara cuando estás alegre.', '¿Qué haces cuando sientes miedo?'], ['mapa', 'Emociones', 'alegría', 'tristeza', 'miedo', 'enfado']);
  u('valores', 'val_convivencia', 'pri2 pri3 sec', 'Convivencia y resolución de conflictos', ['Un conflicto es un desacuerdo entre personas.', 'Escuchar a la otra persona es el primer paso para resolverlo.', 'La mediación busca una solución en la que todos ganen.', 'El respeto no significa pensar igual.'], ['conflicto', 'escucha activa', 'mediación', 'respeto', 'acuerdo'], 'V:La mediación busca que todos ganen.|F:Respetar es pensar igual.|V:Escuchar ayuda a resolver conflictos.', ['Describe un conflicto y cómo lo resolviste.', '¿Qué frase usarías para pedir perdón?'], ['flujo', 'conflicto', 'escuchar', 'proponer', 'acuerdo']);
  u('valores', 'val_digital', 'pri3 sec bach adu', 'Ciudadanía digital', ['Lo que publicamos en internet deja una huella digital.', 'Las contraseñas seguras mezclan letras, números y símbolos.', 'El ciberacoso es una forma de violencia que hay que denunciar.', 'Antes de compartir algo, comprueba si es verdad.'], ['huella digital', 'contraseña', 'ciberacoso', 'privacidad', 'desinformación'], 'V:Internet deja huella digital.|F:«1234» es una contraseña segura.|V:El ciberacoso se denuncia.', ['Escribe tres normas para usar bien las redes.', '¿Qué harías si un amigo sufre ciberacoso?'], ['mapa', 'Ciudadanía digital', 'privacidad', 'seguridad', 'respeto', 'veracidad']);

  u('religion', 'rel_simbolos', 'pri1 pri2 pri3', 'Símbolos y espacios sagrados', ['Las religiones usan símbolos para expresar lo que creen.', 'Los templos se construyen con formas que invitan al recogimiento.', 'El rosetón es una ventana circular dividida en partes iguales.', 'La luz y el color de las vidrieras cuentan historias.'], ['símbolo', 'templo', 'rosetón', 'vidriera', 'celebración'], 'V:El rosetón es una ventana circular.|F:Las vidrieras son de madera.|V:Los símbolos expresan creencias.', ['Dibuja un rosetón con ocho partes iguales.', '¿Qué símbolo representa algo importante para tu familia?'], ['mapa', 'Espacios sagrados', 'templo', 'altar', 'rosetón', 'vidriera']);
  u('religion', 'rel_grandes', 'sec bach adu', 'Las grandes religiones del mundo', ['El cristianismo, el islam y el judaísmo son religiones monoteístas.', 'El hinduismo y el budismo nacieron en la India.', 'Cada religión tiene libros sagrados, fiestas y lugares de culto.', 'El diálogo entre religiones favorece la paz.'], ['monoteísmo', 'libros sagrados', 'fiestas', 'lugares de culto', 'diálogo'], 'V:El islam es monoteísta.|F:El budismo nació en América.|V:El diálogo favorece la paz.', ['Compara dos fiestas religiosas de tu país.', '¿Por qué es importante respetar otras creencias?'], ['mapa', 'Religiones', 'cristianismo', 'islam', 'judaísmo', 'budismo', 'hinduismo']);
  u('religion', 'rel_arte', 'sec bach', 'Arte religioso y geometría', ['Las catedrales góticas usan arcos apuntados y bóvedas.', 'Los mosaicos de las mezquitas repiten estrellas geométricas.', 'Los mandalas son círculos con simetría radial.', 'La geometría expresa orden y armonía en el arte sagrado.'], ['arco apuntado', 'bóveda', 'mosaico', 'mandala', 'simetría radial'], 'V:Los mandalas tienen simetría radial.|F:El gótico usa arcos de herradura.|V:Los mosaicos repiten estrellas.', ['Diseña un mandala con simetría de seis partes.', 'Busca un edificio religioso de tu ciudad y describe sus formas.'], ['mapa', 'Arte sagrado', 'gótico', 'mosaico', 'mandala', 'vidriera']);
  u('religion', 'rel_fiestas', 'pri1 pri2 pri3', 'Fiestas y tradiciones', ['Muchas fiestas marcan momentos importantes del año.', 'En las fiestas compartimos comidas, cantos y encuentros.', 'Las tradiciones pasan de padres a hijos.', 'Cada país celebra a su manera.'], ['fiesta', 'tradición', 'celebración', 'comunidad', 'calendario'], 'V:Las tradiciones pasan de padres a hijos.|F:Todos los países celebran igual.|V:En las fiestas compartimos.', ['¿Cuál es tu fiesta favorita y por qué?', 'Pregunta a tus abuelos cómo celebraban de pequeños.'], ['ciclo', 'preparación', 'celebración', 'encuentro', 'recuerdo']);

  ED.registrar({
    materias: [
      { id: 'bio', n: 'Biología', ico: '🧬', al: { es: 'Biología y Geología', cl: 'Biología', co: 'Ciencias Naturales · Biología', mx: 'Biología', ar: 'Biología', us: 'Biología (Life Science)' } },
      { id: 'anat', n: 'Anatomía y fisiología', ico: '🫀', al: { es: 'Anatomía Aplicada' } },
      { id: 'fisica', n: 'Física', ico: '⚙️', al: { es: 'Física y Química · Física', cl: 'Física', us: 'Física (Physical Science)' } },
      { id: 'quimica', n: 'Química', ico: '⚗️', al: { es: 'Física y Química · Química', cl: 'Química' } },
      { id: 'geografia', n: 'Geografía', ico: '🗺', al: { es: 'Geografía e Historia · Geografía', cl: 'Historia, Geografía y Ciencias Sociales', mx: 'Geografía' } }
    ],
    unidades: L
  });
  window.EU_CURRICULO_PLUS = { n: L.length };
})();
