/* b6_color_cerebro_3.js — cerebro con voz de la calculadora cromática de Fátima (calc_cromatica_v8.html) y preguntas
   de colorimetría (juegos_fatima.html), repo «aprendizaje», commit e3c1996. Solo los TEXTOS y las TABLAS, copiados tal cual:
   respuestas del asistente por estado del cabello, textos de audio, niveles 1–10, carta de tonos, 10 errores de corrección con su
   corrector y regla, estrella de neutralización (Howard) y banco de preguntas. Nada de la calculadora, Firebase, créditos ni WhatsApp. */
(function () {
  'use strict';
  var B = window.EU_COLOR_CEREBRO = window.EU_COLOR_CEREBRO || { clases: [] };
  B.calc = {"chat":{"muyMaltratado":"Con cabello muy maltratado, los procesos químicos como decoloración están totalmente contraindicados. El cabello necesita recuperarse primero. Te recomiendo: primero, hidratación profunda con productos naturales como clara de huevo con aceite de oliva durante 30 minutos, retirando siempre con agua fría. Segundo, cortes de puntas cada 15 días para que el cabello respire y crezca fuerte. Tercero, evitar completamente el calor. Este proceso de recuperación puede tomar varios meses. ¿Quieres que te explique el protocolo de hidratación natural completo?","maltratado":"Con cabello maltratado, puedes aplicar tinte con oxidante de máximo 20 volúmenes, pero la decoloración no está recomendada. Es importante hacer prueba de mechón antes de cualquier proceso. Hidrata profundamente antes y después del servicio.","mechon":"La prueba de mechón es fundamental antes de cualquier proceso químico. Toma un mechón pequeño en zona poco visible, aplica 30 gramos de polvo decolorante con agua oxigenada de 30 volúmenes durante 20 minutos. Si la fibra se pone chiclosa, elástica o se rompe, no procedas con la decoloración. Si el mechón aclaró correctamente y la fibra quedó íntegra, puedes proceder con precaución.","hidratacion":"Para hidratar cabello maltratado con productos naturales: mezcla una clara de huevo con una cucharada de aceite de oliva. Aplica en todo el cabello durante 30 minutos. Retira siempre con agua fría, nunca tibia ni caliente, ya que el agua tibia abre la fibra capilar y causa más daño. Repite cada semana para mejores resultados. Recuerda que el cabello respira por las puntas, así que los cortes mensuales son esenciales.","decoloracion":"Para la decoloración correcta, primero verifica el estado estructural de tu cabello. Con cabello virgen o sano, puedes usar hasta 30 o 40 volúmenes. Con color previo, máximo 20 volúmenes. Con cabello maltratado, solo tinte, sin decoloración. Con cabello muy maltratado, ningún proceso químico. Siempre realiza prueba de mechón previa.","canas":"Para la cobertura de canas, usa tinte oxidativo de 20 volúmenes con base de cobertura. El tiempo de exposición debe ser de 45 minutos. Si tienes más del 50 por ciento de canas, usa el módulo A con el selector de porcentaje de canas que aparece en la sección de raíces. La calculadora ajusta la fórmula automáticamente."},"textos":{"TEXTO_MECHON":"Antes de realizarte un proceso químico, es fundamental que realices una prueba de mechón para verificar si tu cabello lo soporta. Toma un mechón pequeño en una zona poco visible, aplica 30 gramos de polvo decolorante con agua oxigenada de 30 volúmenes durante 20 minutos. Observa el resultado: si el mechón aclaró correctamente y la fibra capilar se mantiene íntegra y resistente, puedes proceder con precaución. Si la fibra capilar se puso chiclosa, elástica, blanda o se rompió con facilidad, te recomiendo no proceder con procesos químicos de decoloración. La salud de tu cabello siempre es lo primero.","TEXTO_HIDRATACION":"Se recomienda hidratación profunda con productos naturales que tienes en casa. Prepara una mascarilla con una clara de huevo y una cucharada de aceite de oliva, aplícala en todo el cabello durante 30 minutos y retira con abundante agua fría. Nunca uses agua tibia ni caliente, ya que el agua tibia abre la fibra capilar y puede causar más daño. Se recomienda también realizarse un corte de puntas para mejorar la salud del cabello, ya que el cabello respira por las puntas. En cabellos maltratados con altos procesos químicos, se recomienda realizar cortes mensuales para que el cabello respire, y aplicar hidrataciones profundas con productos naturales de forma regular. Recuerda, el cuidado constante es la clave de un cabello sano y hermoso. Atentamente, Fátima Caldea.","TEXTO_MUY_MALTRATADO_INTRO":"Cabello muy maltratado detectado. Atención: no se recomienda ningún proceso químico en este momento. El cabello necesita recuperación completa antes de cualquier coloración o decoloración. Sigue el protocolo de recuperación que te presento a continuación.","TEXTO_CORTE_PUNTAS":"El corte de puntas cada 15 días es fundamental para el crecimiento saludable del cabello muy maltratado. El cabello respira y crece desde las puntas. Eliminando las puntas dañadas, el cabello puede absorber mejor los nutrientes, ganar fuerza y crecer con más vitalidad. Este proceso, combinado con hidrataciones naturales, puede transformar tu cabello en pocos meses. Recuerda: paciencia y constancia son la clave. Atentamente, Fátima Caldea, tu colorimetrista profesional."},"niveles":[{"l":1,"h":"#0d0400"},
    {"l":2,"h":"#1e0a00"},
    {"l":3,"h":"#3d1800"},
    {"l":4,"h":"#5c2800"},
    {"l":5,"h":"#7a3c10"},
    {"l":6,"h":"#9a5a28"},
    {"l":7,"h":"#b87840"},
    {"l":8,"h":"#d09858"},
    {"l":9,"h":"#e8ba70"},
    {"l":10,"h":"#f8d888"}],
    "colores":{"Natural":[{"n":"Negro 1.0","c":"1.0","h":"#0d0400","l":1},
    {"n":"Castaño Muy Oscuro 2.0","c":"2.0","h":"#1e0a00","l":2},
    {"n":"Castaño Oscuro 3.0","c":"3.0","h":"#3d1800","l":3},
    {"n":"Castaño 4.0","c":"4.0","h":"#5c2800","l":4},
    {"n":"Castaño Claro 5.0","c":"5.0","h":"#7a3c10","l":5},
    {"n":"Rubio Oscuro 6.0","c":"6.0","h":"#9a5a28","l":6},
    {"n":"Rubio 7.0","c":"7.0","h":"#b87840","l":7},
    {"n":"Rubio Claro 8.0","c":"8.0","h":"#d09858","l":8},
    {"n":"Rubio Muy Claro 9.0","c":"9.0","h":"#e8ba70","l":9},
    {"n":"Extra Claro 10.0","c":"10.0","h":"#f8d888","l":10},
    {"n":"Castaño Ceniza 4.01","c":"4.01","h":"#5a3020","l":4},
    {"n":"Castaño Dorado 4.3","c":"4.3","h":"#6a3810","l":4},
    {"n":"Castaño Cobre 5.4","c":"5.4","h":"#8a3818","l":5},
    {"n":"Castaño Caoba 5.5","c":"5.5","h":"#7a2010","l":5},
    {"n":"Rubio Ceniza 7.01","c":"7.01","h":"#a87848","l":7},
    {"n":"Rubio Dorado 7.3","c":"7.3","h":"#c08030","l":7},
    {"n":"Rubio Beige 8.13","c":"8.13","h":"#d4a868","l":8},
    {"n":"Rubio Claro Nat 8.00","c":"8.00","h":"#d4a060","l":8},
    {"n":"Extra Claro Nat 10.00","c":"10.00","h":"#f8d880","l":10},
    {"n":"Rubio Irisado 9.2","c":"9.2","h":"#ddc8d8","l":9}],
    "Rubios":[{"n":"Rubio Dorado 7.3","c":"7.3","h":"#c08030","l":7},
    {"n":"Rubio Dorado Claro 8.3","c":"8.3","h":"#d49040","l":8},
    {"n":"Rubio Miel 7.34","c":"7.34","h":"#c07828","l":7},
    {"n":"Rubio Miel 8.34","c":"8.34","h":"#d48838","l":8},
    {"n":"Rubio Ceniza 7.1","c":"7.1","h":"#b08858","l":7},
    {"n":"Rubio Ceniza 8.1","c":"8.1","h":"#c89868","l":8},
    {"n":"Rubio Ceniza 9.1","c":"9.1","h":"#dca878","l":9},
    {"n":"Rubio Platino 10.1","c":"10.1","h":"#f0d090","l":10},
    {"n":"Rubio Perla 10.01","c":"10.01","h":"#f4dca8","l":10},
    {"n":"Rubio Irisado 8.2","c":"8.2","h":"#c8a0b8","l":8},
    {"n":"Rubio Avellana 7.35","c":"7.35","h":"#b86828","l":7},
    {"n":"Rubio Caramelo 6.34","c":"6.34","h":"#a86020","l":6},
    {"n":"Superclaro 12.0","c":"12.0","h":"#fce8a8","l":10},
    {"n":"Superclaro Ceniza 12.1","c":"12.1","h":"#fce8c0","l":10},
    {"n":"Superclaro Dorado 12.3","c":"12.3","h":"#fce0a0","l":10},
    {"n":"Platino Irisado 10.12","c":"10.12","h":"#f0d8c8","l":10},
    {"n":"Rubio Extra Claro 10.3","c":"10.3","h":"#f8c060","l":10},
    {"n":"Rubio Cobre Dorado 8.43","c":"8.43","h":"#d49040","l":8}],
    "Frios":[{"n":"Ceniza 3.1","c":"3.1","h":"#302820","l":3},
    {"n":"Ceniza 4.1","c":"4.1","h":"#5a4030","l":4},
    {"n":"Ceniza 5.1","c":"5.1","h":"#785050","l":5},
    {"n":"Ceniza 6.1","c":"6.1","h":"#987060","l":6},
    {"n":"Ceniza 7.1","c":"7.1","h":"#b09070","l":7},
    {"n":"Ceniza 8.1","c":"8.1","h":"#c8a880","l":8},
    {"n":"Ceniza 9.1","c":"9.1","h":"#dcc090","l":9},
    {"n":"Platino 10.1","c":"10.1","h":"#f0d8a0","l":10},
    {"n":"Irisado 5.2","c":"5.2","h":"#686080","l":5},
    {"n":"Irisado 6.2","c":"6.2","h":"#8878a0","l":6},
    {"n":"Irisado 7.2","c":"7.2","h":"#a898b8","l":7},
    {"n":"Irisado 8.2","c":"8.2","h":"#c8b0d0","l":8},
    {"n":"Irisado 9.2","c":"9.2","h":"#dcc8e0","l":9},
    {"n":"Mat 5.81","c":"5.81","h":"#705850","l":5},
    {"n":"Mat 6.81","c":"6.81","h":"#907060","l":6},
    {"n":"Mat 7.81","c":"7.81","h":"#b09070","l":7},
    {"n":"Gris Perla 9.11","c":"9.11","h":"#dcd0c8","l":9},
    {"n":"Lila 8.21","c":"8.21","h":"#c0a8c0","l":8},
    {"n":"Platino Irisado 10.2","c":"10.2","h":"#e8d8e8","l":10},
    {"n":"Ceniza Irisado 7.12","c":"7.12","h":"#a898a8","l":7},
    {"n":"Lila Claro 9.21","c":"9.21","h":"#d8c0d8","l":9},
    {"n":"Beige Irisado 8.12","c":"8.12","h":"#c0a8b0","l":8},
    {"n":"Platino Beige 10.13","c":"10.13","h":"#f4e0b0","l":10},
    {"n":"Rubio Gris 8.11","c":"8.11","h":"#c8b890","l":8}],
    "Calidos":[{"n":"Cobre 4.4","c":"4.4","h":"#8a3010","l":4},
    {"n":"Cobre 5.4","c":"5.4","h":"#a84020","l":5},
    {"n":"Cobre 6.4","c":"6.4","h":"#c05030","l":6},
    {"n":"Cobre 7.4","c":"7.4","h":"#d06040","l":7},
    {"n":"Cobre 8.4","c":"8.4","h":"#e07050","l":8},
    {"n":"Dorado 5.3","c":"5.3","h":"#985020","l":5},
    {"n":"Dorado 6.3","c":"6.3","h":"#b06828","l":6},
    {"n":"Dorado 7.3","c":"7.3","h":"#c07828","l":7},
    {"n":"Dorado 8.3","c":"8.3","h":"#d48838","l":8},
    {"n":"Dorado 9.3","c":"9.3","h":"#e49848","l":9},
    {"n":"Avellana 5.35","c":"5.35","h":"#904818","l":5},
    {"n":"Avellana 7.35","c":"7.35","h":"#b86828","l":7},
    {"n":"Caramelo 6.34","c":"6.34","h":"#aa5e22","l":6},
    {"n":"Caramelo 7.34","c":"7.34","h":"#be6e2a","l":7},
    {"n":"Miel 8.34","c":"8.34","h":"#d07e30","l":8},
    {"n":"Miel 9.34","c":"9.34","h":"#e09040","l":9},
    {"n":"Naranja 6.46","c":"6.46","h":"#b04820","l":6},
    {"n":"Canela 7.44","c":"7.44","h":"#c06828","l":7},
    {"n":"Toffee 8.44","c":"8.44","h":"#d07830","l":8},
    {"n":"Cobre Intenso 5.45","c":"5.45","h":"#a03818","l":5},
    {"n":"Bronce 6.0","c":"T6.0","h":"#a87040","l":6},
    {"n":"Miel Claro 10.34","c":"10.34","h":"#f0a858","l":10}],
    "Rojos":[{"n":"Rojo 4.6","c":"4.6","h":"#780808","l":4},
    {"n":"Rojo 5.6","c":"5.6","h":"#901010","l":5},
    {"n":"Rojo 6.6","c":"6.6","h":"#a81818","l":6},
    {"n":"Rojo 7.6","c":"7.6","h":"#c02020","l":7},
    {"n":"Rojo 8.6","c":"8.6","h":"#d83030","l":8},
    {"n":"Rojo Intenso 4.66","c":"4.66","h":"#700000","l":4},
    {"n":"Caoba 4.5","c":"4.5","h":"#6a1818","l":4},
    {"n":"Caoba 5.5","c":"5.5","h":"#882020","l":5},
    {"n":"Caoba 6.5","c":"6.5","h":"#a02828","l":6},
    {"n":"Caoba 7.5","c":"7.5","h":"#b83030","l":7},
    {"n":"Frambuesa 5.26","c":"5.26","h":"#802050","l":5},
    {"n":"Frambuesa 6.26","c":"6.26","h":"#982858","l":6},
    {"n":"Borgoña 4.65","c":"4.65","h":"#681018","l":4},
    {"n":"Cereza 5.62","c":"5.62","h":"#880020","l":5},
    {"n":"Rojo Cobrizo 6.45","c":"6.45","h":"#a02810","l":6},
    {"n":"Rojo Vino 4.52","c":"4.52","h":"#680830","l":4},
    {"n":"Rojo Fuego 7.66","c":"7.66","h":"#c01010","l":7},
    {"n":"Caoba Nat 5.56","c":"5.56","h":"#8a1818","l":5},
    {"n":"Rojo Violeta 5.52","c":"5.52","h":"#802040","l":5},
    {"n":"Castaño Rojo 4.45","c":"4.45","h":"#6a1808","l":4}],
    "Irisados":[{"n":"Irisado 5.2","c":"5.2","h":"#686080","l":5},
    {"n":"Irisado 6.2","c":"6.2","h":"#8878a0","l":6},
    {"n":"Irisado 7.2","c":"7.2","h":"#a898b8","l":7},
    {"n":"Irisado 8.2","c":"8.2","h":"#c0b0d0","l":8},
    {"n":"Irisado 9.2","c":"9.2","h":"#d8c8e0","l":9},
    {"n":"Violeta 5.22","c":"5.22","h":"#684878","l":5},
    {"n":"Violeta 6.22","c":"6.22","h":"#806090","l":6},
    {"n":"Violeta 7.22","c":"7.22","h":"#9878a8","l":7},
    {"n":"Violeta 8.22","c":"8.22","h":"#b098c0","l":8},
    {"n":"Malva 6.20","c":"6.20","h":"#907088","l":6},
    {"n":"Malva 7.20","c":"7.20","h":"#a888a0","l":7},
    {"n":"Lila 8.21","c":"8.21","h":"#c0a8c0","l":8},
    {"n":"Lila 9.21","c":"9.21","h":"#d8c0d8","l":9},
    {"n":"Platino Violeta 10.22","c":"10.22","h":"#e8d0e0","l":10},
    {"n":"Platino Irisado 10.2","c":"10.2","h":"#e8d8e8","l":10},
    {"n":"Beige Irisado 8.12","c":"8.12","h":"#c0a8b0","l":8}],
    "Fantasia":[{"n":"Rosa Bebé","c":"F.RBe","h":"#FFE4EC","l":10},
    {"n":"Rosa Pastel","c":"F.RPa","h":"#FFB3C6","l":10},
    {"n":"Rosa Intenso","c":"F.RI","h":"#E91E63","l":9},
    {"n":"Fucsia","c":"F.Fu","h":"#FF0090","l":9},
    {"n":"Magenta","c":"F.Mg","h":"#FF00FF","l":9},
    {"n":"Coral","c":"F.Co","h":"#FF8A65","l":9},
    {"n":"Lila Pastel","c":"F.LP","h":"#D7B8E8","l":10},
    {"n":"Lila","c":"F.Li","h":"#C880E0","l":9},
    {"n":"Violeta","c":"F.Vi","h":"#9B59B6","l":9},
    {"n":"Lavanda","c":"F.La","h":"#E6CCFF","l":10},
    {"n":"Azul Pastel","c":"F.AP","h":"#B3D4F0","l":10},
    {"n":"Azul Cielo","c":"F.AC","h":"#87CEEB","l":10},
    {"n":"Azul","c":"F.Az","h":"#2196F3","l":9},
    {"n":"Azul Eléctrico","c":"F.AE","h":"#00B0FF","l":9},
    {"n":"Turquesa","c":"F.Tu","h":"#00BCD4","l":9},
    {"n":"Verde Menta","c":"F.VM","h":"#69F0AE","l":10},
    {"n":"Verde Esmeralda","c":"F.VE","h":"#00C853","l":9},
    {"n":"Naranja","c":"F.Na","h":"#FF9800","l":10},
    {"n":"Rose Gold","c":"F.RG","h":"#E8B4B8","l":10},
    {"n":"Champagne","c":"F.Cha","h":"#FAE0C0","l":10},
    {"n":"Granate","c":"F.Gr","h":"#880E4F","l":9},
    {"n":"Rojo Brillante","c":"F.RBr","h":"#FF1744","l":9},
    {"n":"Plata","c":"F.Pl","h":"#A8A9AD","l":10},
    {"n":"Dorado Metal","c":"F.DM","h":"#D4AF37","l":9},
    {"n":"Galaxy","c":"F.Ga","h":"#2E0057","l":9},
    {"n":"Unicornio","c":"F.Un","h":"#E040FB","l":10},
    {"n":"Cotton Candy","c":"F.CC","h":"#FFB3DE","l":10},
    {"n":"Mermaid","c":"F.Mr","h":"#00ACC1","l":10},
    {"n":"Fresa","c":"F.Fr","h":"#FC5A8D","l":10},
    {"n":"Zafiro","c":"F.Za","h":"#0F52BA","l":9},
    {"n":"Amarillo Dorado","c":"F.AD","h":"#FFD700","l":10},
    {"n":"Neon Mix","c":"F.NM","h":"#CCFF00","l":9}],
    "Grises":[{"n":"Gris Claro","c":"G.1","h":"#d0d0d0","l":9},
    {"n":"Gris Medio","c":"G.2","h":"#a8a8a8","l":7},
    {"n":"Gris Oscuro","c":"G.3","h":"#707070","l":5},
    {"n":"Gris Perla","c":"G.4","h":"#dcd0c8","l":9},
    {"n":"Gris Azulado","c":"G.5","h":"#9098a8","l":7},
    {"n":"Gris Plateado","c":"G.6","h":"#c0c8d0","l":9},
    {"n":"Gris Cálido","c":"G.7","h":"#b8a898","l":7},
    {"n":"Blanco Perla","c":"G.8","h":"#f0ece8","l":10},
    {"n":"Platino Blanco","c":"G.9","h":"#f8f4f0","l":10},
    {"n":"Blanco Hielo","c":"G.10","h":"#f4f8ff","l":10}],
    "Canas":[{"n":"Cana Natural","c":"C.1","h":"#e8e0d8","l":9},
    {"n":"Cana Perla","c":"C.2","h":"#f0e8e0","l":10},
    {"n":"Cana Gris","c":"C.3","h":"#c8c0b8","l":8},
    {"n":"Cana Plateada","c":"C.4","h":"#d8d4d0","l":9},
    {"n":"Cobertura Total","c":"C.T","h":"#f4f0ec","l":10},
    {"n":"Cobertura Parcial","c":"C.P","h":"#e0d8d0","l":9},
    {"n":"Neutralizador Cana","c":"C.N","h":"#b8c0c8","l":8},
    {"n":"Tónico Plata Cana","c":"C.TP","h":"#c8d0d8","l":9}],
    "Cobrizos":[{"n":"Cobrizo Intenso 4","c":"Co.4","h":"#8a2808","l":4},
    {"n":"Cobrizo 5","c":"Co.5","h":"#a03010","l":5},
    {"n":"Cobrizo 6","c":"Co.6","h":"#b83818","l":6},
    {"n":"Cobrizo 7","c":"Co.7","h":"#c84020","l":7},
    {"n":"Cobrizo Dorado 6","c":"CoD.6","h":"#c05020","l":6},
    {"n":"Cobrizo Dorado 7","c":"CoD.7","h":"#d06028","l":7},
    {"n":"Cobrizo Oscuro 3","c":"Co.3","h":"#6a1808","l":3},
    {"n":"Anaranjado 6","c":"An.6","h":"#d04010","l":6},
    {"n":"Anaranjado 7","c":"An.7","h":"#e05018","l":7},
    {"n":"Anaranjado Intenso","c":"An.I","h":"#e83000","l":6}],
    "Correctores":[{"n":"Verde 0.07","c":"0.07","h":"#3CB371","l":0},
    {"n":"Rojo 0.06","c":"0.06","h":"#DC143C","l":0},
    {"n":"Violeta 0.02","c":"0.02","h":"#8B00FF","l":0},
    {"n":"Azul 0.08","c":"0.08","h":"#1565C0","l":0},
    {"n":"Naranja 0.04","c":"0.04","h":"#FF6D00","l":0},
    {"n":"Amarillo 0.03","c":"0.03","h":"#FFD600","l":0},
    {"n":"Ceniza 0.01","c":"0.01","h":"#9E9E9E","l":0},
    {"n":"Rosado 0.05","c":"0.05","h":"#F48FB1","l":0},
    {"n":"Dorado 0.33","c":"0.33","h":"#FFA000","l":0},
    {"n":"Cobre 0.44","c":"0.44","h":"#E64A19","l":0},
    {"n":"Irisado 0.22","c":"0.22","h":"#7B1FA2","l":0},
    {"n":"Caoba 0.55","c":"0.55","h":"#880E4F","l":0},
    {"n":"Neutraliz. Morado","c":"N.Mo","h":"#6A1B9A","l":0},
    {"n":"Neutraliz. Azul","c":"N.Az","h":"#0D47A1","l":0},
    {"n":"Neutraliz. Verde","c":"N.Ve","h":"#1B5E20","l":0},
    {"n":"Tónico Plata","c":"T.Pl","h":"#B0BEC5","l":0},
    {"n":"Tónico Violeta","c":"T.Vi","h":"#7B1FA2","l":0},
    {"n":"Tónico Rosa","c":"T.Ro","h":"#F06292","l":0}]},"errores":[{"l":"Demasiado Cálido","s":"Tonos anaranjados no deseados","cor":"0.1 Ceniza","regla":"Ceniza neutraliza calidez. Aplicar sobre nivel objetivo."},
    {"l":"Bandas de Color","s":"Coloración irregular, manchas","cor":"Tinte del nivel objetivo","regla":"Igualar con tinte del nivel base + corrector neutro."},
    {"l":"Sub-proceso","s":"Color no tomó suficientemente","cor":"Repetir proceso + Vol correcto","regla":"Verificar oxidante. Repetir con 20 Vol. Tiempo completo."},
    {"l":"Efecto Verde","s":"Reflejos verdosos post-ceniza","cor":"0.6 Corrector Rojo","regla":"Verde + Rojo = Neutro. Usar con precisión."},
    {"l":"Demasiado Frío","s":"Tonos ceniza/verdosos excesivos","cor":"0.3 Dorado o 0.4 Cobre","regla":"Añadir calor al tono. Mezcla 1:3 con color base."},
    {"l":"Sobre-proceso","s":"Cabello muy aclarado / dañado","cor":"Tinte nivel objetivo + 10 Vol","regla":"Usar oxidante suave. Hidratación previa. Tiempo reducido."},
    {"l":"Oxidación Prematura","s":"Color se oxidó/cambió de tono","cor":"Corrector + tinte sellador","regla":"Sellar con tónico. Evaluar calidad del producto."},
    {"l":"Efecto Morado","s":"Violeta excesivo post-tónico","cor":"0.3 Dorado","regla":"Dorado neutraliza violeta. Aplicar con 10 Vol."},
    {"l":"Cobertura de Canas","s":"Canas sin cobertura total","cor":"Cobertura Cana + 20 Vol","regla":"Usar tinte oxidativo 20 Vol con base de cobertura. Tiempo 45 min."},
    {"l":"Color Fantasía Residual","s":"Fantasía previo no eliminado","cor":"Decolorar + neutralizar","regla":"Decolorar con 20 Vol hasta base limpia. Aplicar corrector."}],
    "estrella":[{"r":"NIV 9-10","p":"Amarillo intenso","ph":"#FFD700","c":"0.22 Irisado Intenso","ch":"#9B59B6"},
    {"r":"NIV 8-9","p":"Amarillo dorado","ph":"#DAA520","c":"0.2 Violeta","ch":"#7D3C98"},
    {"r":"NIV 7-8","p":"Naranja dorado","ph":"#E67E22","c":"0.11 Ceniza Intenso","ch":"#7F8C8D"},
    {"r":"NIV 6-7","p":"Naranja","ph":"#D35400","c":"0.1 Ceniza","ch":"#95A5A6"},
    {"r":"NIV 4-6","p":"Rojo anaranjado","ph":"#C0392B","c":"0.7 Verde","ch":"#27AE60"},
    {"r":"NIV 1-4","p":"Rojo profundo","ph":"#922B21","c":"0.3 Dorado","ch":"#F39C12"}],
    "preguntas":[{"p":"¿Cuántos niveles de color existen en colorimetría capilar profesional?","o":["5 niveles","8 niveles","10 niveles","12 niveles"],
    "c":2,"exp":"Existen 10 niveles del 1 al 10. El nivel 1 es negro puro y el nivel 10 es rubio muy claro platino. Cada nivel tiene sus propios tonos base y requiere fórmulas específicas. Conocer los niveles es la base de toda colorimetría."},
    {"p":"¿Qué oxidante se usa para abrir el tono sin aclarar demasiado?","o":["40 volúmenes","10 volúmenes","20 volúmenes","Sin oxidante"],
    "c":2,"exp":"20 volúmenes (6%) es el oxidante estándar para coloración permanente que sube 1-2 tonos. 10 vol es para tonalizar sin cambio de nivel. 40 vol es para decoloración agresiva que puede dañar el cabello."},
    {"p":"Los colores cálidos en colorimetría son:","o":["Azul, verde, violeta","Rojo, naranja, amarillo","Blanco, gris, negro","No existen colores cálidos"],
    "c":1,"exp":"Los colores cálidos (rojo, naranja, amarillo) tienen longitudes de onda largas y se perciben como energizantes. En colorimetría capilar, estos pigmentos son los más resistentes y los primeros en aparecer cuando el cabello se decolora."},
    {"p":"¿Para qué sirve la Teoría de Howard en colorimetría?","o":["Para decorar el salón","Para calcular el precio del servicio","Para entender cómo los pigmentos naturales del cabello interactúan con el color artificial y predecir el resultado exacto","Para lavar el cabello correctamente"],
    "c":2,"exp":"La Teoría de Howard explica la interacción entre los pigmentos melanínicos naturales y los pigmentos artificiales. Con ella puedes predecir exactamente qué resultado obtendrás antes de aplicar el color. Fátima la aplica con 19 años de experiencia real."},
    {"p":"¿Qué pasa si aplicas tinte directamente sobre canas sin fórmula correcta?","o":["Queda perfecto siempre","El cabello se cae","La cobertura puede ser incompleta porque las canas tienen cutícula cerrada y resisten la absorción del pigmento","No pasa nada especial"],
    "c":2,"exp":"Las canas tienen la cutícula más cerrada y compacta que el cabello pigmentado. Necesitan una fórmula específica: generalmente un tono natural más un tono cálido para garantizar la cobertura completa y evitar el efecto \"vidrio\"."},
    {"p":"Para neutralizar un tono naranja no deseado, ¿qué color se usa?","o":["Rojo","Amarillo","Azul","Verde"],
    "c":2,"exp":"El azul es el complementario del naranja en el círculo cromático. Los complementarios se neutralizan mutuamente. Por eso los matizadores azules o violetas se usan para neutralizar los reflejos anaranjados y dorados no deseados."},
    {"p":"¿Qué es el \"fondo de decoloración\"?","o":["El producto decolorante","El color que queda visible en el cabello durante el proceso de decoloración, que va del negro al amarillo pálido pasando por etapas","El resultado final","El tipo de cabellos"],
    "c":1,"exp":"El fondo de decoloración es la escala de colores que el cabello natural revela al decolorar: negro, marrón oscuro, marrón, castaño rojizo, rojo, naranja, amarillo dorado, amarillo, amarillo pálido. Saber en qué fondo está el cabello es clave para predecir el resultado."},
    {"p":"¿Cuánto tiempo máximo se puede dejar un decolorante para no dañar el cabello?","o":["2 horas mínimo","Indefinidamente","Máximo 50-60 minutos dependiendo del producto y la fórmula","Solo 5 minutos"],
    "c":2,"exp":"El tiempo máximo de decoloración es crítico. Después de 50-60 minutos la mayoría de los productos ya cumplieron su acción y continuar solo daña la cutícula sin aclarar más. El cabello puede volverse gomoso, romperse o perder toda su elasticidad."},
    {"p":"Una cliente llega con cabello verde después de teñirse de rubio. ¿Qué ocurrió?","o":["El tinte era de mala calidad","El cabello estaba muy limpio","El cabello tenía tonos cobrizos-dorados que al combinarse con el pigmento azul del rubio ceniza crearon el verde inesperado","El agua del salón es diferente"],
    "c":2,"exp":"Este es un error clásico de colorimetría sin diagnóstico previo. Los fondos cálidos (dorado, cobrizo) del cabello más el pigmento azul-violeta del rubio ceniza o platino crean verde. La Teoría de Howard predice esto. Un diagnóstico correcto lo evita."},
    {"p":"¿Qué es la \"porosidad\" del cabello y por qué importa en colorimetría?","o":["El brillo del cabello","La capacidad del cabello de absorber y retener los pigmentos de color, que varía según el estado de la cutícula","El peso del cabello","La textura visual"],
    "c":1,"exp":"La porosidad determina cuánto color entra y cuánto se retiene. Cabello muy poroso absorbe rápido pero libera el color igual de rápido (el color se va antes). Cabello resistente necesita más tiempo y productos adaptados. Ignorar la porosidad produce resultados impredecibles."},
    {"p":"¿Por qué el cabello gris resistente requiere un tono más cálido en la fórmula?","o":["Por estética únicamente","Para que dure más tiempo","Porque la cutícula cerrada del cabello gris refleja la luz de manera diferente y los tonos fríos quedan planos o metálicos, mientras que el calor da profundidad y naturalidad","Por tradición profesional"],
    "c":2,"exp":"El cabello gris resistente (canas duras) rechaza los tonos fríos y los hace ver artificiales o metálicos. Añadir un tono cálido en la fórmula (1 parte de tono natural + 1 parte de tono cálido) da profundidad, naturalidad y cobertura duradera."},
    {"p":"Técnica balayage: ¿por qué NO se debe tocar la raíz?","o":["Es solo estética","Porque la raíz tiene más calor corporal que acelera la decoloración creando una transición poco natural y sobre-procesada","Por comodidad","No existe esa regla"],
    "c":1,"exp":"La raíz tiene más temperatura por el calor del cuero cabelludo. Si la decoloración llega a la raíz, actúa más rápido y agresivamente, creando una transición abrupta en lugar del efecto degradado natural que caracteriza al balayage perfecto."},
    {"p":"¿Cómo predices el resultado exacto antes de aplicar color usando la Teoría de Howard?","o":["No se puede predecir","Observas el nivel natural, identificas el fondo de decoloración, calculas la interacción entre pigmentos naturales y artificiales y ajustas la fórmula","Solo con experiencia","Con una prueba de mechón siempre"],
    "c":1,"exp":"La Teoría de Howard es predictiva. Con ella puedes calcular matemáticamente el resultado antes de aplicar el color. Es la diferencia entre un colorista profesional y alguien que aplica color sin criterio científico. Fátima lo aplica en cada servicio con 19 años de práctica."},
    {"p":"Cliente: cabello negro natural, nivel 1, quiere llegar a rubio nivel 8 en una sola sesión. ¿Tu respuesta profesional?","o":["Lo haces en una sesión con mucho decolorante","Es imposible, explicas que el cabello pasará por fondos naranja y amarillo que requieren varias sesiones de decoloración progresiva para mantener la integridad","Aplicas tinte rubio directamente","No se puede hacer nunca"],
    "c":1,"exp":"Este es el error más común que arruina el cabello. Del nivel 1 al 8 hay 7 niveles de diferencia. El cabello debe pasar por todos los fondos de decoloración. Hacerlo en una sesión destruye la estructura del cabello. Un profesional explica el proceso y lo divide en sesiones respetando los tiempos de recuperación."},
    {"p":"¿Qué diferencia a un colorista nivel Dios de uno intermedio?","o":["El precio que cobra","La marca de productos que usa","Predice el resultado antes de aplicar usando química, física de la luz y la Teoría de Howard combinadas con el diagnóstico completo del cabello","La velocidad de trabajo"],
    "c":2,"exp":"El nivel Dios es cuando combinas toda la ciencia: química (composición del cabello), física (comportamiento de la luz y el color), Teoría de Howard (interacción pigmentaria) y diagnóstico clínico. El resultado ya está calculado antes de abrir el tubo de color."}]};
  /* panel de diagnóstico, protocolo de recuperación, decoloración y súper aclarante, y la liga de dos tonos (módulo C):
     textos y datos tal cual de calc_cromatica_v8.html (DIAG_LABELS, DiagAlert, MuyMaltratadoPanel, decTecnicas,
     superMetodos/superMetodosDesc, lenNames/lenGramsArr y los tonos con los que arranca el módulo C) */
  B.calc.diag = {"estados": ["Virgen / Natural", "Sano con color", "Procesos Químicos", "Maltratado", "Muy Maltratado"], "avisos": {"0": ["aok", "✓ Cabello virgen / natural — Todos los procesos permitidos."], "1": ["awarn", "⚠ Cabello con color previo — Verificar estado antes de procesos máximos."], "2": ["awarn", "⚠ Procesos químicos detectados — Máximo 20 Vol. Prueba de mechón obligatoria."], "3": ["adanger", "⚠ Cabello MALTRATADO — No se recomienda decoloración ni procesos fuertes."]}, "recupera": ["Con cabello muy maltratado NO se realizan decoloraciones ni tintes con oxidante alto. Hacerlo puede causar caída severa o calvicie. El cabello necesita recuperación completa primero.", "HIDRATACIÓN PROFUNDA NATURAL", "Clara de huevo + aceite de oliva · 30 min · Agua fría. Nunca caliente. Sin cosméticos agresivos. Solo productos naturales por varios meses hasta recuperar la estructura capilar.", "CORTES DE PUNTAS CADA 15 DÍAS", "El cabello respira y crece por las puntas. Cortes frecuentes eliminan la fibra dañada, dan fuerza al crecimiento y permiten que el cabello se recupere más rápido.", "PROTOCOLO DE RECUPERACIÓN", "Este proceso requiere varios meses de constancia: hidrataciones semanales + cortes cada 15 días. Solo después de la recuperación estructural completa se pueden considerar procesos químicos suaves.", "El protocolo de recuperación para cabello muy maltratado requiere constancia y paciencia. Semana uno y dos: hidratación con clara de huevo y aceite de oliva, y primer corte de puntas. Semana tres y cuatro: segunda hidratación y segundo corte. Este ciclo se repite durante tres a seis meses dependiendo del daño. Solo cuando la fibra capilar recupere su elasticidad y resistencia normal, se puede considerar un tinte suave con oxidante de diez volúmenes. Fátima Caldea estará disponible para hacer el diagnóstico cuando estés lista.", "⊘ CABELLO MUY MALTRATADO — PROTOCOLO DE RECUPERACIÓN"], "decTecnicas": ["Decoloración Total", "Mechas Clásicas", "Highlights", "Balayaje", "Babylights", "Ombré / Sombré", "Solo Raíces", "Solo Puntas"], "superMetodos": ["Polvo Alto Rendimiento", "Aceite Decolorante", "Doble Proceso", "Babylights Full", "Balayaje", "Mechas Sencillas", "Highlights", "Ombré / Sombré"], "superDesc": ["Hasta 8 tonos de lift", "Aclarado suave continuo", "Decoloración + tinte misma sesión", "Aclarado total secciones finas", "Difuminado natural degradado", "Mechas clásicas tradicionales", "Puntos de luz sutiles", "Degradado oscuro a claro"], "largos": ["Corto", "Medio", "Largo", "Muy Largo"], "gramos": [40, 80, 120, 160], "ligaEj": {"c1": {"n": "Rubio 7.0", "c": "7.0", "h": "#b87840", "l": 7}, "c2": {"n": "Rubio Dorado 7.3", "c": "7.3", "h": "#c08030", "l": 7}, "p": 50}};
})();
