/* b6_cocina_unidades2.js — segunda ampliación de los recetarios: diez unidades propias de «Cocina»
   (cortes, cocción, salsas, texturas, emplatado, maridaje, seguridad, aprovechamiento, sostenibilidad y
   receta con °C/°F) y ocho más para repostería, panadería, pastelería y batidos. «Cocina completa»
   recibe copia de las de recetario (sufijo _t). Generadores nuevos: salmuera, reducción, costo por
   ración, rendimiento en piezas, levadura fresca ↔ seca, huevos por peso y proporción del batido.
   Cargar después de b6_cocina_unidades.js. */
(function () {
  'use strict';
  var ED = window.EU_EDITORIAL; if (!ED || window.EU_COCINA_UNIDADES2) return;
  var H = ED.H, pick = H.pick, it = H.it, num = function (n, C) { return H.num(n, C); };
  function ent(r, a, b) { return a + Math.floor(r() * (b - a + 1)); }
  var FX = (window.EU_EMPRE && EU_EMPRE.FX) || { es: 1 };
  function din(eur, C) { var v = eur * (FX[C.pk] || 1); v = v < 10 ? Math.round(v * 100) / 100 : Math.round(v); return v; }

  var G = {
    coc_salmuera: function (u, C, r) {
      var l = pick(r, [0.5, 1, 1.5, 2, 3]), p = pick(r, [3, 5, 6, 8]), g = Math.round(l * 1000 * p / 100);
      var q = pick(r, ['Una salmuera al ' + p + ' % lleva ' + p + ' g de sal por cada 100 ml de agua. ¿Cuánta sal necesitas para ' + num(l, C) + ' l?', 'Para salmuerar pollo preparas ' + num(l, C) + ' l de agua al ' + p + ' % de sal. ¿Cuántos gramos de sal pones?']);
      return it('corta', q, num(g, C) + ' g', { ac: [g], x: num(l * 1000, C) + ' × ' + p + ' ÷ 100 = ' + num(g, C) + ' g' });
    },
    coc_reduccion: function (u, C, r) {
      var v = pick(r, [500, 750, 1000, 1500]), p = pick(r, [25, 33, 50, 66]), f = Math.round(v * (100 - p) / 100);
      var q = pick(r, ['Reduces ' + num(v, C) + ' ml de fondo hasta perder el ' + p + ' % del volumen. ¿Cuántos ml quedan?', 'Una salsa de ' + num(v, C) + ' ml se deja reducir un ' + p + ' %. ¿Qué volumen final tiene?']);
      return it('corta', q, num(f, C) + ' ml', { ac: [f], x: num(v, C) + ' × ' + (100 - p) + ' ÷ 100 = ' + num(f, C) + ' ml' });
    },
    coc_racion: function (u, C, r) {
      var t = din(pick(r, [6, 9, 12, 18, 24]), C), k = pick(r, [4, 6, 8, 10, 12]), c = Math.round(t / k * 100) / 100;
      var q = pick(r, ['Los ingredientes de una receta cuestan ' + H.din(t, C) + ' y salen ' + k + ' raciones. ¿Cuánto cuesta cada ración?', 'Gastas ' + H.din(t, C) + ' en la compra para un plato de ' + k + ' raciones. ¿Costo por ración?']);
      return it('corta', q, H.din(c, C), { ac: [c], x: H.din(t, C) + ' ÷ ' + k + ' = ' + H.din(c, C) });
    },
    coc_piezas: function (u, C, r) {
      var m = pick(r, [800, 1200, 1500, 1800, 2400]), p = pick(r, [50, 60, 80, 100, 120]), k = Math.floor(m / p);
      var q = pick(r, ['Tienes ' + num(m, C) + ' g de masa y cada pieza pesa ' + p + ' g. ¿Cuántas piezas enteras salen?', 'Divides ' + num(m, C) + ' g de masa en bolas de ' + p + ' g. ¿Cuántas bolas completas obtienes?']);
      return it('corta', q, String(k), { ac: [k], x: num(m, C) + ' ÷ ' + p + ' = ' + num(Math.round(m / p * 10) / 10, C) + ' → ' + k + ' piezas' });
    },
    coc_levadura: function (u, C, r) {
      var f = pick(r, [9, 12, 15, 21, 30]), s = f / 3;
      var q = pick(r, ['La receta pide ' + f + ' g de levadura fresca y solo tienes seca de panadero. Si se usa un tercio del peso, ¿cuántos gramos pones?', 'Cambias ' + f + ' g de levadura fresca por levadura seca instantánea (1/3 del peso). ¿Cuánta usas?']);
      return it('corta', q, num(s, C) + ' g', { ac: [s, num(s, C)], x: f + ' ÷ 3 = ' + num(s, C) + ' g' });
    },
    coc_huevos: function (u, C, r) {
      var h = pick(r, [2, 3, 4, 5, 6]), g = h * 50;
      var q = pick(r, ['Una receta profesional pide ' + g + ' g de huevo sin cáscara. Si cada huevo mediano da unos 50 g, ¿cuántos huevos usas?', 'La fórmula indica ' + g + ' g de huevo batido. ¿Cuántos huevos medianos (50 g) son?']);
      return it('corta', q, String(h), { ac: [h], x: g + ' ÷ 50 = ' + h });
    },
    coc_proporcion: function (u, C, r) {
      var fr = pick(r, [150, 200, 250, 300]), p = pick(r, [[1, 1], [2, 3], [1, 2]]), l = Math.round(fr * p[1] / p[0]);
      var q = pick(r, ['Un batido se prepara con fruta y líquido en proporción ' + p[0] + ' : ' + p[1] + '. Si pones ' + fr + ' g de fruta, ¿cuántos ml de líquido añades?', 'Para la textura buscada usas ' + p[0] + ' parte de fruta por ' + p[1] + ' de líquido. Con ' + fr + ' g de fruta, ¿cuánto líquido?']);
      return it('corta', q, l + ' ml', { ac: [l], x: fr + ' × ' + p[1] + ' ÷ ' + p[0] + ' = ' + l + ' ml' });
    }
  };

  /* Versiones con producto y varias redacciones de los generadores de recetario: con un solo enunciado
     por generador, un libro de 300 páginas repetía la misma pregunta cientos de veces. */
  var PROD = {
    panaderia: ['chapata', 'baguette', 'pan de molde', 'hogaza', 'focaccia', 'masa de pizza', 'pan integral', 'pan de centeno', 'bollos de leche', 'pan de hamburguesa', 'masa de empanada', 'pan de pueblo'],
    reposteria: ['bizcocho', 'galletas', 'magdalenas', 'brownie', 'bizcocho de yogur', 'rosquillas', 'muffins', 'cookies', 'tarta de queso', 'bizcocho de zanahoria', 'palmeritas', 'polvorones'],
    pasteleria: ['hojaldre', 'profiteroles', 'tarta de frutas', 'mousse de chocolate', 'entremet', 'macarons', 'éclairs', 'milhojas', 'tarta Sacher', 'crema catalana', 'lionesas', 'tarta de limón'],
    batidos: ['batido verde', 'batido de fresa', 'smoothie de mango', 'batido de plátano y avena', 'bowl de açaí', 'batido de frutos rojos', 'batido tropical', 'licuado de papaya', 'batido de cacao y dátil', 'batido de piña y espinaca'],
    cocina: ['guiso de lentejas', 'crema de calabaza', 'arroz con verduras', 'pollo al horno', 'tortilla de patatas', 'sopa de fideos', 'salsa de tomate', 'pescado al vapor', 'ensalada templada', 'puré de patata', 'estofado', 'pasta fresca']
  };
  function prod(u, r) { var L = PROD[(u && (u.cat || u.m)) || 'cocina'] || PROD.cocina; return L[Math.floor(r() * L.length)]; }
  var FEM = /^(chapata|baguette|hogaza|focaccia|masa|tarta|mousse|crema|sopa|salsa|ensalada|tortilla|pasta)/, FPL = /^(magdalenas|galletas|rosquillas|palmeritas|cookies|lionesas)/, MPL = /^(macarons|éclairs|profiteroles|muffins|polvorones|bollos)/;
  function A(p) { return (FPL.test(p) ? 'las ' : MPL.test(p) ? 'los ' : FEM.test(p) ? 'la ' : 'el ') + p; }
  function D(p) { return ('de ' + A(p)).replace(/^de el /, 'del '); }
  function cap(s) { return s.charAt(0).toUpperCase() + s.slice(1); }
  var G2 = {
    coc_hidrata: function (u, C, r) {
      var p = prod(u, r), h = pick(r, [400, 500, 800, 1000, 1200]), pc = pick(r, [58, 60, 65, 70, 75, 80]), a = h * pc / 100;
      var q = pick(r, ['Para ' + A(p) + ' mezclas ' + num(h, C) + ' g de harina con ' + num(a, C) + ' ml de agua; ¿qué hidratación tiene la masa?', 'La fórmula de ' + p + ' lleva ' + num(a, C) + ' ml de agua por ' + num(h, C) + ' g de harina. Calcula el porcentaje de hidratación.', '¿Qué hidratación tiene ' + A(p) + ' si usas ' + num(h, C) + ' g de harina y ' + num(a, C) + ' g de agua?', 'Anotas en tu cuaderno: ' + p + ', harina ' + num(h, C) + ' g, agua ' + num(a, C) + ' g. ¿Qué porcentaje de hidratación escribes?', 'Quieres comparar ' + A(p) + ' con la de otro obrador: tú usas ' + num(a, C) + ' ml de agua para ' + num(h, C) + ' g de harina. ¿Cuál es tu hidratación?']);
      return it('corta', q, pc + ' %', { ac: [pc, pc + '%', pc + ' %'], x: num(a, C) + ' ÷ ' + num(h, C) + ' × 100 = ' + pc + ' %' });
    },
    coc_panadero: function (u, C, r) {
      var p = prod(u, r), h = pick(r, [500, 750, 1000, 1500, 2000, 2500]), ing = pick(r, [['agua', [60, 62, 65, 68, 70, 75]], ['sal', [1.8, 2, 2.2]], ['levadura fresca', [1, 1.5, 2, 3]], ['aceite', [3, 5, 8]], ['azúcar', [2, 4, 6]], ['mantequilla', [5, 8, 10]]]), pc = pick(r, ing[1]), g = Math.round(h * pc / 100 * 10) / 10;
      var q = pick(r, ['La fórmula de ' + p + ' pide ' + num(pc, C) + ' % de ' + ing[0] + ' sobre la harina; con ' + num(h, C) + ' g de harina, ¿cuántos gramos de ' + ing[0] + ' pesas?', cap(A(p)) + ' lleva ' + num(h, C) + ' g de harina (100 %). ¿Cuánto es el ' + num(pc, C) + ' % de ' + ing[0] + '?', 'En la ficha de ' + p + ' aparece: harina 100 %, ' + ing[0] + ' ' + num(pc, C) + ' %. Si amasas ' + num(h, C) + ' g de harina, ¿cuántos gramos de ' + ing[0] + ' pones?', 'Para una tanda de ' + p + ' con ' + num(h, C) + ' g de harina necesitas el ' + num(pc, C) + ' % de ' + ing[0] + '; calcula los gramos.']);
      return it('corta', q, num(g, C) + ' g', { ac: [g, num(g, C)], x: num(h, C) + ' × ' + num(pc, C) + ' ÷ 100 = ' + num(g, C) + ' g' });
    },
    coc_tiempo: function (u, C, r) {
      var p = prod(u, r), ini = ent(r, 6, 11), mi = pick(r, [0, 15, 30]), a = pick(r, [20, 30, 45, 60, 90, 120]), b = pick(r, [10, 15, 20, 25, 30, 40]), t = ini * 60 + mi + a + b, hh = Math.floor(t / 60), mm = t % 60, h0 = ini + ':' + (mi < 10 ? '0' : '') + mi, sol = hh + ':' + (mm < 10 ? '0' : '') + mm;
      var fase = pick(r, [['de reposo', 'de horno'], ['de fermentación', 'de cocción'], ['de preparación', 'de enfriado'], ['de amasado y reposo', 'de horneado']]);
      var q = pick(r, ['Empiezas ' + A(p) + ' a las ' + h0 + ': ' + a + ' min ' + fase[0] + ' y ' + b + ' min ' + fase[1] + '; ¿a qué hora termina?', 'Si ' + A(p) + ' necesita ' + a + ' min ' + fase[0] + ' y ' + b + ' min ' + fase[1] + ', y arrancas a las ' + h0 + ', ¿a qué hora estará lista?', 'Un cliente recoge ' + A(p) + ' en cuanto esté: la empiezas a las ' + h0 + ' con ' + a + ' min ' + fase[0] + ' y ' + b + ' min ' + fase[1] + '. ¿A qué hora avisas?', 'Planifica ' + A(p) + ': inicio ' + h0 + ', ' + a + ' min ' + fase[0] + ', ' + b + ' min ' + fase[1] + '. ¿Hora de fin?', '¿A qué hora terminas ' + A(p) + ' si empiezas a las ' + h0 + ' y el proceso suma ' + a + ' min ' + fase[0] + ' más ' + b + ' min ' + fase[1] + '?']);
      return it('corta', q, sol, { ac: [sol], x: h0 + ' + ' + (a + b) + ' min = ' + sol });
    },
    coc_temp: function (u, C, r) {
      var p = prod(u, r), c = pick(r, [140, 150, 160, 170, 175, 180, 190, 200, 210, 220, 230, 250]), f = Math.round(c * 9 / 5 + 32), sol = Math.round((f - 32) * 5 / 9 / 5) * 5;
      var q = pick(r, ['Una receta estadounidense de ' + p + ' pide el horno a ' + f + ' °F; ¿a cuántos °C lo pones? (redondea a 5)', 'El libro inglés indica ' + f + ' °F para ' + A(p) + '. Conviértelo a grados Celsius.', 'Tu horno solo marca °C y ' + A(p) + ' pide ' + f + ' °F. ¿Qué temperatura eliges?', 'Traduce a °C la temperatura de horno ' + D(p) + ': ' + f + ' °F.']);
      return it('corta', q, sol + ' °C', { ac: [sol], x: '(' + f + ' − 32) × 5 ÷ 9 ≈ ' + Math.round((f - 32) * 5 / 9) + ' °C' });
    },
    coc_piezas: function (u, C, r) {
      var p = prod(u, r), m = pick(r, [800, 1000, 1200, 1500, 1800, 2400, 3000]), g = pick(r, [40, 50, 60, 80, 100, 120, 250]), k = Math.floor(m / g);
      var q = pick(r, ['Con ' + num(m, C) + ' g de masa de ' + p + ' haces piezas de ' + g + ' g; ¿cuántas enteras salen?', '¿Cuántas porciones de ' + g + ' g obtienes de ' + num(m, C) + ' g de ' + p + '?', 'Divides ' + num(m, C) + ' g de ' + p + ' en piezas iguales de ' + g + ' g. ¿Cuántas completas?', 'El pedido es de ' + p + ' en unidades de ' + g + ' g y tienes ' + num(m, C) + ' g preparados; ¿para cuántas unidades llega?']);
      return it('corta', q, String(k), { ac: [k], x: num(m, C) + ' ÷ ' + g + ' → ' + k });
    },
    coc_racion: function (u, C, r) {
      var p = prod(u, r), t = din(pick(r, [5, 6, 8, 9, 12, 15, 18, 24, 30]), C), k = pick(r, [4, 6, 8, 10, 12, 16, 20]), c = Math.round(t / k * 100) / 100;
      var q = pick(r, ['Los ingredientes ' + D(p) + ' cuestan ' + H.din(t, C) + ' y salen ' + k + ' raciones; ¿cuánto cuesta cada una?', '¿Cuál es el costo por ración ' + D(p) + ' de ' + k + ' raciones si la compra fue de ' + H.din(t, C) + '?', 'Gastas ' + H.din(t, C) + ' para preparar ' + k + ' raciones de ' + p + '. Calcula el costo de una.', 'Para poner precio a ' + A(p) + ' necesitas el costo unitario: ' + H.din(t, C) + ' en total, ' + k + ' raciones.']);
      return it('corta', q, H.din(c, C), { ac: [c], x: H.din(t, C) + ' ÷ ' + k + ' = ' + H.din(c, C) });
    },
    coc_huevos: function (u, C, r) {
      var p = prod(u, r), h = pick(r, [2, 3, 4, 5, 6, 8, 10]), g = h * 50;
      var q = pick(r, [cap(A(p)) + ' pide ' + g + ' g de huevo sin cáscara; con huevos medianos de unos 50 g, ¿cuántos usas?', '¿Cuántos huevos medianos (50 g) son los ' + g + ' g de huevo ' + D(p) + '?', 'Tu ficha de ' + p + ' dice ' + g + ' g de huevo batido. ¿Cuántos huevos cascas?']);
      return it('corta', q, String(h), { ac: [h], x: g + ' ÷ 50 = ' + h });
    },
    coc_levadura: function (u, C, r) {
      var p = prod(u, r), f = pick(r, [6, 9, 12, 15, 18, 21, 24, 30]), s = f / 3;
      var q = pick(r, [cap(A(p)) + ' lleva ' + f + ' g de levadura fresca y solo tienes seca (un tercio del peso); ¿cuántos gramos pones?', 'Cambia a levadura seca instantánea los ' + f + ' g de fresca ' + D(p) + '.', '¿Cuánta levadura seca equivale a ' + f + ' g de fresca en ' + A(p) + '? (usa 1/3)']);
      return it('corta', q, num(s, C) + ' g', { ac: [s, num(s, C)], x: f + ' ÷ 3 = ' + num(s, C) + ' g' });
    },
    coc_vasos: function (u, C, r) {
      var p = prod(u, r), v = pick(r, [200, 250, 300, 350, 400]), n = ent(r, 2, 12), t = v * n;
      var q = pick(r, ['Sirves ' + p + ' en vasos de ' + v + ' ml; ¿cuánto preparas para ' + n + ' personas?', '¿Qué volumen total de ' + p + ' necesitas para ' + n + ' vasos de ' + v + ' ml?', 'Un pedido de ' + n + ' raciones de ' + p + ' de ' + v + ' ml: ¿cuántos ml en total?']);
      return it('corta', q, num(t, C) + ' ml', { ac: [t, num(t, C)], x: v + ' × ' + n + ' = ' + num(t, C) + ' ml' });
    },
    coc_proporcion: function (u, C, r) {
      var p = prod(u, r), fr = pick(r, [100, 150, 200, 250, 300, 400]), pr = pick(r, [[1, 1], [2, 3], [1, 2], [3, 2]]), l = Math.round(fr * pr[1] / pr[0]);
      var q = pick(r, ['Para ' + A(p) + ' usas fruta y líquido en proporción ' + pr[0] + ' : ' + pr[1] + '; con ' + fr + ' g de fruta, ¿cuántos ml de líquido?', 'La textura ' + D(p) + ' pide ' + pr[0] + ' parte sólida por ' + pr[1] + ' líquida. Si pones ' + fr + ' g de sólido, ¿cuánto líquido añades?', '¿Cuánto líquido lleva ' + A(p) + ' con ' + fr + ' g de base, si la razón es ' + pr[0] + ' : ' + pr[1] + '?']);
      return it('corta', q, l + ' ml', { ac: [l], x: fr + ' × ' + pr[1] + ' ÷ ' + pr[0] + ' = ' + l + ' ml' });
    }
  };
  Object.keys(G2).forEach(function (k) { G[k] = G2[k]; });

  var BANDAS = ['inf', 'pri1', 'pri2', 'pri3', 'sec', 'bach', 'fp', 'adu'];
  function vf(s) { return s.split('|').map(function (x) { return [x.slice(2), x.charAt(0) === 'V']; }); }
  var U = [
    /* Cocina (propias) */
    ['cocina', 'coc2_cortes', 'Cortes de cuchillo', ['La juliana son tiras finas de unos 3 mm; la brunoise, dados de 2–3 mm.', 'Cortar todo del mismo tamaño hace que se cocine a la vez.', 'El cuchillo se sujeta por la base de la hoja y la otra mano hace «garra».', 'Un cuchillo afilado es más seguro que uno sin filo.'], ['juliana', 'brunoise', 'garra', 'afilar'], 'coc_merma', 'V:Cortar igual ayuda a cocinar parejo.|F:Un cuchillo sin filo es más seguro.|V:La brunoise son dados pequeños.', ['Describe cómo sujetas el cuchillo y el alimento.', '¿Qué corte usarías para una sopa y por qué?'], { t: 'flujo', p: ['bastón', 'juliana', 'dado', 'brunoise'] }],
    ['cocina', 'coc2_coccion', 'Técnicas de cocción', ['Hervir cocina en agua a 100 °C; escalfar, en líquido justo por debajo del hervor.', 'Saltear es cocinar rápido con poca grasa y fuego fuerte.', 'Asar al horno dora por fuera gracias al aire caliente.', 'Al vapor se conservan mejor el color y parte de las vitaminas.'], ['hervir', 'escalfar', 'saltear', 'vapor'], 'coc_tiempo', 'V:Escalfar es cocinar por debajo del hervor.|F:Saltear se hace a fuego bajo.|V:El vapor conserva mejor el color.', ['Elige una técnica para cada alimento: huevo, brócoli, pollo.', '¿Por qué se dora la carne al asarla?'], { t: 'mapa', c: 'Cocción', r: ['en agua', 'en grasa', 'en seco', 'al vapor'] }],
    ['cocina', 'coc2_salsas', 'Salsas madre', ['La cocina clásica francesa parte de cinco salsas madre: bechamel, velouté, española, tomate y holandesa.', 'Un roux —harina y grasa a partes iguales— espesa la bechamel.', 'La holandesa es una emulsión de yema y mantequilla.', 'Reducir un líquido concentra sabor y espesa.'], ['roux', 'bechamel', 'emulsión', 'reducción'], 'coc_reduccion', 'V:El roux lleva harina y grasa.|F:La holandesa se espesa con harina.|V:Reducir concentra el sabor.', ['Explica cómo se hace un roux.', '¿Qué salsa derivarías de una bechamel?'], { t: 'mapa', c: 'Salsas madre', r: ['bechamel', 'velouté', 'española', 'tomate', 'holandesa'] }],
    ['cocina', 'coc2_texturas', 'Texturas en el plato', ['Un plato interesante combina texturas: crujiente, cremoso, tierno.', 'El almidón espesa al calentarse: harina, maicena o patata.', 'Las proteínas cuajan con el calor; si se pasan, se endurecen.', 'Un toque crujiente al final da contraste.'], ['crujiente', 'cremoso', 'almidón', 'cuajar'], 'coc_temp', 'V:El almidón espesa con calor.|F:Las proteínas se ablandan al pasarse de cocción.|V:El contraste de texturas mejora el plato.', ['Añade un elemento crujiente a una crema de verduras.', '¿Por qué se endurece un huevo muy cocido?'], { t: 'flujo', p: ['base', 'cremoso', 'tierno', 'crujiente'] }],
    ['cocina', 'coc2_emplatado', 'El emplatado', ['Se come primero con los ojos: color, altura y orden.', 'Los números impares de elementos suelen verse más equilibrados.', 'El borde del plato se deja limpio.', 'La salsa se pone debajo o al lado para no tapar lo principal.'], ['emplatado', 'color', 'altura', 'equilibrio'], 'coc_racion', 'V:El borde del plato va limpio.|F:La salsa siempre tapa el alimento principal.|V:El color hace el plato apetecible.', ['Dibuja cómo emplatarías un plato de tu país.', '¿Qué color añadirías a un plato beige?'], { t: 'flujo', p: ['base', 'principal', 'guarnición', 'salsa', 'detalle'] }],
    ['cocina', 'coc2_maridaje', 'Combinar sabores', ['Los cinco sabores básicos son dulce, salado, ácido, amargo y umami.', 'Un ácido (limón, vinagre) aligera platos grasos.', 'El umami está en el tomate maduro, el queso curado y las setas.', 'Las bebidas también se combinan: agua con gas, infusiones o zumos sin azúcar.'], ['dulce', 'ácido', 'amargo', 'umami'], 'coc_proporcion', 'V:El ácido aligera los platos grasos.|F:Solo existen cuatro sabores básicos.|V:El tomate maduro tiene umami.', ['Clasifica diez alimentos por su sabor principal.', 'Propón una bebida sin alcohol para un plato graso.'], { t: 'mapa', c: 'Sabores', r: ['dulce', 'salado', 'ácido', 'amargo', 'umami'] }],
    ['cocina', 'coc2_seguridad', 'Seguridad alimentaria', ['Las bacterias crecen deprisa entre 5 °C y 60 °C.', 'Los alimentos cocinados se enfrían rápido y se guardan en la nevera antes de dos horas.', 'El pollo debe alcanzar 74 °C en el centro.', 'Tablas de colores separan carne cruda, pescado y verdura.'], ['zona de peligro', 'temperatura interna', 'contaminación cruzada', 'refrigerar'], 'coc_temp', 'V:El pollo debe llegar a 74 °C por dentro.|F:La comida cocinada puede quedarse fuera toda la noche.|V:Las tablas de colores evitan contaminación.', ['Haz un cartel con cuatro normas de higiene.', '¿Cómo compruebas que el pollo está hecho?'], { t: 'flujo', p: ['comprar', 'guardar', 'preparar', 'cocinar', 'enfriar'] }],
    ['cocina', 'coc2_aprovecha', 'Cocina de aprovechamiento', ['Con pan duro se hacen torrijas, migas o pan rallado.', 'Las pieles y recortes de verdura sirven para un caldo.', 'Planificar el menú semanal evita comprar de más.', 'Congelar en raciones alarga la vida de lo que sobra.'], ['aprovechar', 'caldo', 'menú semanal', 'congelar'], 'coc_merma', 'V:Con recortes se hace caldo.|F:El pan duro no sirve para nada.|V:Planificar evita desperdicio.', ['Escribe tres recetas con restos de tu nevera.', 'Planifica un menú de cinco días.'], { t: 'ciclo', p: ['planificar', 'comprar', 'cocinar', 'guardar', 'reutilizar'] }],
    ['cocina', 'coc2_sostenible', 'Cocina sostenible', ['Los productos de temporada son más baratos y viajan menos.', 'Las legumbres dan proteína con menos agua y tierra que la carne.', 'Cocinar con tapa y aprovechar el calor residual ahorra energía.', 'Comprar a granel reduce envases.'], ['temporada', 'legumbres', 'energía', 'granel'], 'coc_racion', 'V:Lo de temporada suele ser más barato.|F:Cocinar sin tapa ahorra energía.|V:Las legumbres aportan proteína.', ['Haz un calendario de frutas de temporada de tu país.', 'Propón un plato con legumbres.'], { t: 'mapa', c: 'Sostenible', r: ['temporada', 'cercanía', 'legumbres', 'energía', 'envases'] }],
    ['cocina', 'coc2_receta', 'Leer y adaptar una receta', ['Antes de empezar se lee la receta entera y se prepara todo (mise en place).', 'Las recetas de otros países pueden venir en °F, tazas u onzas.', 'Para escalar se multiplica cada ingrediente por el mismo factor.', 'Los tiempos de horno cambian con el tamaño del molde.'], ['mise en place', 'grados Fahrenheit', 'escalar', 'factor'], 'coc_temp', 'V:Se lee la receta completa antes de empezar.|F:Al escalar solo se cambia la harina.|V:Algunas recetas vienen en °F.', ['Convierte a °C tres temperaturas en °F.', 'Escala una receta de 4 a 10 raciones.'], { t: 'flujo', p: ['leer', 'preparar', 'medir', 'cocinar', 'probar'] }],
    /* Repostería */
    ['reposteria', 'rep2_masas', 'Masas quebradas', ['La masa quebrada mezcla harina con grasa fría antes de añadir el líquido.', 'La grasa recubre la harina y limita el gluten: la masa queda arenosa.', 'Se trabaja poco y se enfría antes de estirar.', 'Se hornea en blanco con peso para que no suba.'], ['quebrada', 'sablée', 'hornear en blanco', 'arenoso'], 'coc_huevos', 'V:La grasa fría limita el gluten.|F:La quebrada se amasa mucho.|V:Hornear en blanco evita que suba.', ['Explica por qué se enfría la masa.', '¿Qué pondrías para hornear en blanco?'], { t: 'flujo', p: ['arenar', 'ligar', 'enfriar', 'estirar', 'hornear'] }],
    ['reposteria', 'rep2_cremas', 'Cremas básicas', ['La crema pastelera se espesa con almidón y yema, y debe hervir un minuto.', 'La inglesa solo lleva yema y se cuece hasta 82–84 °C, sin hervir.', 'La crema de mantequilla se monta con azúcar hasta blanquear.', 'Todas se tapan a piel para que no hagan costra.'], ['pastelera', 'inglesa', 'crema de mantequilla', 'napar'], 'coc_temp', 'V:La inglesa no debe hervir.|F:La pastelera no lleva almidón.|V:Se tapa a piel para evitar costra.', ['Compara la crema pastelera y la inglesa.', '¿Qué significa «napar la cuchara»?'], { t: 'mapa', c: 'Cremas', r: ['pastelera', 'inglesa', 'mantequilla', 'chantilly'] }],
    ['reposteria', 'rep2_merengue', 'Merengues', ['El francés se bate en frío con azúcar poco a poco.', 'El suizo calienta clara y azúcar al baño maría hasta unos 60 °C.', 'El italiano añade un almíbar a 118–121 °C: es el más estable.', 'Una gota de grasa en el bol impide que la clara monte.'], ['merengue francés', 'suizo', 'italiano', 'pico'], 'coc_temp', 'V:El italiano lleva almíbar caliente.|F:La grasa ayuda a montar las claras.|V:El suizo se calienta al baño maría.', ['Ordena los merengues de menos a más estable.', '¿Para qué usarías cada uno?'], { t: 'flujo', p: ['francés', 'suizo', 'italiano'] }],
    ['reposteria', 'rep2_molde', 'Moldes y horneado', ['Un molde oscuro absorbe más calor y dora más.', 'El molde se engrasa y enharina, o se forra con papel.', 'Un palillo que sale limpio indica que el bizcocho está hecho.', 'Se desmolda tras unos minutos de reposo.'], ['molde', 'engrasar', 'prueba del palillo', 'desmoldar'], 'coc_piezas', 'V:El molde oscuro dora más.|F:Se desmolda recién salido del horno siempre.|V:El palillo limpio indica cocción.', ['¿Cómo preparas un molde para bizcocho?', 'Explica la prueba del palillo.'], { t: 'flujo', p: ['engrasar', 'llenar', 'hornear', 'probar', 'desmoldar'] }],
    ['reposteria', 'rep2_leche', 'Lácteos en repostería', ['La nata con más de un 30 % de grasa se puede montar.', 'La mantequilla aporta sabor y hojaldra las masas.', 'El yogur y el suero dan acidez que activa el bicarbonato.', 'Los lácteos fríos montan mejor; los templados se integran mejor en masas.'], ['nata para montar', 'mantequilla', 'suero', 'materia grasa'], 'coc_proporcion', 'V:La nata para montar tiene más del 30 % de grasa.|F:El yogur no reacciona con el bicarbonato.|V:La nata fría monta mejor.', ['¿Por qué no monta la nata ligera?', 'Sustituye la leche por yogur en una receta y explica el cambio.'], { t: 'mapa', c: 'Lácteos', r: ['leche', 'nata', 'mantequilla', 'yogur', 'queso crema'] }],
    ['reposteria', 'rep2_decorar', 'Decorar con sencillez', ['Un tamizado de azúcar glas o cacao decora sin esfuerzo.', 'La fruta fresca aporta color y frescor.', 'La manga con boquilla lisa basta para puntos y líneas.', 'Menos elementos bien colocados lucen más.'], ['tamizar', 'boquilla', 'fruta fresca', 'plantilla'], 'coc_ganache', 'V:Menos elementos pueden lucir más.|F:Decorar exige herramientas caras.|V:Tamizar azúcar glas es una decoración.', ['Diseña la decoración de una tarta con tres elementos.', 'Haz una plantilla de papel para tamizar.'], { t: 'flujo', p: ['base', 'color', 'altura', 'detalle'] }],
    ['reposteria', 'rep2_sin', 'Repostería sin gluten y sin huevo', ['Sin gluten se usan mezclas de harina de arroz, maíz o almendra con un ligante como la goma xantana.', 'El huevo puede sustituirse por plátano, compota o semillas de lino hidratadas.', 'Hay que evitar la contaminación con harina de trigo en la cocina.', 'Las recetas adaptadas suelen necesitar más líquido.'], ['sin gluten', 'goma xantana', 'sustituto del huevo', 'contaminación cruzada'], 'coc_huevos', 'V:El lino hidratado sustituye al huevo.|F:La harina de arroz tiene gluten.|V:Hay que evitar trazas de trigo.', ['Adapta una receta de galletas para una persona celíaca.', '¿Qué sustituto del huevo usarías en un bizcocho?'], { t: 'mapa', c: 'Sustituir', r: ['trigo → arroz y maíz', 'huevo → lino', 'leche → bebida vegetal', 'mantequilla → aceite'] }],
    ['reposteria', 'rep2_costos', 'Poner precio a un dulce', ['El precio parte del costo de ingredientes por unidad.', 'Se suman embalaje, energía y una parte del tiempo de trabajo.', 'Un margen razonable cubre imprevistos y ganancia.', 'Comparar con precios de la zona ayuda a no quedarse corto.'], ['costo por unidad', 'embalaje', 'margen', 'precio de venta'], 'coc_racion', 'V:El precio incluye el tiempo de trabajo.|F:Basta con cobrar los ingredientes.|V:Conviene comparar precios de la zona.', ['Calcula el costo de una docena de galletas.', 'Pon precio a una tarta de 8 raciones.'], { t: 'flujo', p: ['ingredientes', 'embalaje', 'tiempo', 'margen', 'precio'] }],
    /* Panadería */
    ['panaderia', 'pan2_levadura', 'Tipos de levadura', ['La levadura fresca es un bloque húmedo que dura unas semanas en frío.', 'La seca instantánea se usa en un tercio del peso de la fresca.', 'La masa madre aporta levaduras y bacterias lácticas.', 'Demasiada levadura acelera la fermentación y quita sabor.'], ['levadura fresca', 'seca instantánea', 'masa madre', 'dosis'], 'coc_levadura', 'V:La seca se usa en un tercio del peso de la fresca.|F:Más levadura siempre da mejor pan.|V:La fresca se guarda en frío.', ['Convierte una receta de levadura fresca a seca.', '¿Qué aporta la masa madre que no aporta la levadura comercial?'], { t: 'mapa', c: 'Levaduras', r: ['fresca', 'seca', 'instantánea', 'masa madre'] }],
    ['panaderia', 'pan2_amasado', 'Amasar y desarrollar el gluten', ['Amasar alinea las proteínas y forma la red de gluten.', 'La prueba de la ventana: una porción se estira fina sin romperse.', 'La autólisis deja reposar harina y agua antes de amasar.', 'Los pliegues sustituyen parte del amasado en masas húmedas.'], ['gluten', 'prueba de la ventana', 'autólisis', 'pliegues'], 'coc_hidrata', 'V:La autólisis es un reposo de harina y agua.|F:La prueba de la ventana mide la sal.|V:Los pliegues fortalecen masas húmedas.', ['Describe la prueba de la ventana.', '¿Por qué se hacen pliegues en una chapata?'], { t: 'flujo', p: ['mezclar', 'autólisis', 'amasar', 'pliegues', 'ventana'] }],
    ['panaderia', 'pan2_piezas', 'Dividir y pesar', ['En panadería se pesa cada pieza para que todas horneen igual.', 'Una barra suele pesar 250–300 g de masa; un panecillo, 50–80 g.', 'Se divide con rasqueta, sin desgarrar la masa.', 'El pan pierde un 10–20 % de peso al hornearse.'], ['dividir', 'rasqueta', 'peso de pieza', 'merma de horno'], 'coc_piezas', 'V:El pan pierde peso en el horno.|F:Las piezas no necesitan pesarse.|V:Se divide con rasqueta.', ['¿Cuántos panecillos salen de 1 kg de masa?', '¿Por qué pierde peso el pan?'], { t: 'flujo', p: ['pesar', 'dividir', 'bolear', 'reposar', 'formar'] }],
    ['panaderia', 'pan2_integral', 'Panes integrales y de semillas', ['La harina integral lleva salvado y germen: más fibra y más sabor.', 'El salvado corta la red de gluten: la miga queda más densa.', 'Pide más agua y un reposo más largo.', 'Las semillas se remojan antes para que no roben agua a la masa.'], ['integral', 'salvado', 'germen', 'escaldado'], 'coc_hidrata', 'V:La integral absorbe más agua.|F:El salvado refuerza el gluten.|V:Las semillas se remojan antes.', ['Adapta una receta blanca a integral.', '¿Por qué se remojan las semillas?'], { t: 'mapa', c: 'Integral', r: ['salvado', 'germen', 'fibra', 'agua', 'reposo'] }],
    ['panaderia', 'pan2_molde', 'Pan de molde y bollería', ['El pan de molde lleva grasa y a veces leche: miga fina y tierna.', 'La grasa se añade cuando el gluten ya está formado.', 'La bollería enriquecida lleva huevo, azúcar y mantequilla.', 'Masas ricas fermentan más despacio.'], ['masa enriquecida', 'brioche', 'miga fina', 'grasa'], 'coc_huevos', 'V:La grasa se añade con el gluten formado.|F:Las masas ricas fermentan más rápido.|V:El brioche lleva huevo y mantequilla.', ['Compara una baguette y un brioche.', '¿Por qué se añade la mantequilla al final?'], { t: 'flujo', p: ['amasar', 'añadir grasa', 'fermentar', 'formar', 'hornear'] }],
    ['panaderia', 'pan2_horno', 'El horno de casa', ['Un horno doméstico necesita unos 30–45 minutos para calentarse de verdad.', 'Una piedra o bandeja de hierro acumula calor y ayuda al crecimiento.', 'El pan está hecho cuando suena hueco al golpear la base.', 'Por dentro, la miga alcanza unos 96–98 °C.'], ['precalentar', 'piedra', 'sonido hueco', 'temperatura interna'], 'coc_temp', 'V:El pan hecho suena hueco.|F:El horno está listo en cinco minutos.|V:La piedra acumula calor.', ['Planifica un horneado desde el precalentado.', '¿Cómo sabes que el pan está hecho?'], { t: 'flujo', p: ['precalentar', 'vapor', 'hornear', 'quitar vapor', 'enfriar'] }],
    ['panaderia', 'pan2_mundo', 'Panes del mundo', ['La baguette francesa lleva solo harina, agua, sal y levadura.', 'La pita se hincha por el vapor y queda hueca.', 'La tortilla de maíz nixtamalizado es base de la cocina mexicana.', 'La arepa se hace con harina de maíz precocida.'], ['baguette', 'pita', 'tortilla', 'arepa'], 'coc_panadero', 'V:La arepa se hace con maíz precocido.|F:La baguette lleva huevo.|V:La pita queda hueca por el vapor.', ['Investiga el pan típico de tu país.', 'Compara dos panes sin levadura.'], { t: 'mapa', c: 'Panes', r: ['baguette', 'pita', 'tortilla', 'arepa', 'chapata'] }],
    ['panaderia', 'pan2_costos', 'Costos de una panadería', ['El costo de un pan suma harina, agua, sal, levadura y energía.', 'La energía del horno pesa mucho en el costo.', 'Hornear varias piezas a la vez reparte ese gasto.', 'El pan del día anterior puede venderse más barato o transformarse.'], ['costo', 'energía', 'lote', 'pan del día anterior'], 'coc_racion', 'V:Hornear en lote reparte la energía.|F:La energía no influye en el costo.|V:El pan de ayer puede transformarse.', ['Calcula el costo de una barra.', '¿Qué harías con el pan que sobra?'], { t: 'flujo', p: ['ingredientes', 'energía', 'mano de obra', 'lote', 'precio'] }],
    /* Pastelería */
    ['pasteleria', 'pas2_bizcochos', 'Bizcochos de pastelería', ['El bizcocho joconde lleva almendra y se hornea en placa fina.', 'El dacquoise es un merengue con fruto seco molido.', 'El bizcocho de aceite queda tierno varios días.', 'Cada uno se elige según la textura que pide la tarta.'], ['joconde', 'dacquoise', 'placa', 'fruto seco'], 'coc_huevos', 'V:El dacquoise lleva fruto seco molido.|F:El joconde se hornea en molde alto.|V:El bizcocho de aceite dura tierno.', ['¿Qué bizcocho usarías en una tarta con mousse?', 'Compara joconde y genovesa.'], { t: 'mapa', c: 'Bizcochos', r: ['genovesa', 'joconde', 'dacquoise', 'aceite'] }],
    ['pasteleria', 'pas2_inserto', 'Insertos y cremosos', ['Un inserto es una capa interior de sabor intenso, congelada en un aro menor.', 'Los cremosos se hacen con crema inglesa y chocolate o fruta.', 'Se congela para poder montarlo dentro de la mousse.', 'Su sabor debe contrastar con el de la mousse.'], ['inserto', 'cremoso', 'aro', 'contraste'], 'coc_gelatina', 'V:El inserto se congela antes de montar.|F:El inserto debe saber igual que la mousse.|V:El cremoso parte de una inglesa.', ['Diseña una tarta con un inserto de fruta.', '¿Por qué se congela el inserto?'], { t: 'flujo', p: ['bizcocho', 'mousse', 'inserto', 'mousse', 'glaseado'] }],
    ['pasteleria', 'pas2_macaron', 'Macarons', ['Se hacen con almendra molida, azúcar glas y merengue.', 'El macaronage mezcla hasta que la masa cae en cinta.', 'Se dejan secar para que formen piel y salga el «pie».', 'Pesar con precisión es imprescindible.'], ['macaronage', 'pie', 'almendra molida', 'secado'], 'coc_temp', 'V:Se dejan secar antes de hornear.|F:La masa se mezcla lo menos posible.|V:La precisión en el peso es clave.', ['Explica qué es el «pie» del macaron.', '¿Qué pasa si mezclas de más?'], { t: 'flujo', p: ['tamizar', 'merengue', 'macaronage', 'secar', 'hornear'] }],
    ['pasteleria', 'pas2_helados', 'Helados y sorbetes', ['El helado lleva lácteos; el sorbete, fruta, agua y azúcar.', 'El azúcar baja el punto de congelación y evita que quede duro como piedra.', 'Batir mientras se congela rompe los cristales de hielo.', 'Se sirve entre −12 y −14 °C.'], ['helado', 'sorbete', 'punto de congelación', 'cristales'], 'coc_proporcion', 'V:El azúcar evita que el helado quede muy duro.|F:El sorbete lleva nata.|V:Batir rompe los cristales.', ['Diseña un sorbete con una fruta de temporada.', '¿Por qué se bate el helado?'], { t: 'flujo', p: ['base', 'madurar', 'mantecar', 'congelar', 'servir'] }],
    ['pasteleria', 'pas2_tartas', 'Tartas de fruta', ['La base suele ser masa sablée horneada en blanco.', 'Una capa de crema pastelera o de almendra sostiene la fruta.', 'La fruta se coloca en círculos o filas ordenadas.', 'Un brillo de gelatina o mermelada la protege y la hace brillar.'], ['sablée', 'frangipane', 'brillo', 'fruta fresca'], 'coc_merma', 'V:El brillo protege la fruta.|F:La fruta se coloca sin orden.|V:La base se hornea en blanco.', ['Dibuja cómo colocarías la fruta en una tarta.', '¿Qué fruta no usarías con gelatina cruda?'], { t: 'flujo', p: ['base', 'crema', 'fruta', 'brillo'] }],
    ['pasteleria', 'pas2_chocolate', 'Bombones y chocolate', ['Los bombones se hacen con chocolate templado en moldes.', 'El relleno puede ser ganache, praliné o caramelo.', 'Se cierran con una capa de chocolate y se desmoldan en frío.', 'Guardados a 15–18 °C conservan el brillo.'], ['bombón', 'praliné', 'molde', 'templado'], 'coc_ganache', 'V:Los bombones se hacen con chocolate templado.|F:Se guardan en la nevera muy húmeda.|V:El praliné es un relleno.', ['Diseña una caja de seis bombones.', '¿Por qué pierde brillo un chocolate mal guardado?'], { t: 'flujo', p: ['templar', 'encamisar', 'rellenar', 'cerrar', 'desmoldar'] }],
    ['pasteleria', 'pas2_escala', 'Adaptar moldes y aros', ['Para pasar de un aro a otro se comparan las superficies.', 'La superficie de un círculo es π por el radio al cuadrado.', 'Un aro de 24 cm tiene casi el doble de superficie que uno de 18 cm.', 'Se multiplica toda la receta por la razón de superficies.'], ['superficie', 'radio', 'razón', 'aro'], 'coc_piezas', 'V:Se comparan superficies para cambiar de molde.|F:Un aro de 24 cm tiene la misma superficie que uno de 18 cm.|V:La superficie depende del radio al cuadrado.', ['Calcula la razón entre un aro de 20 y uno de 26 cm.', 'Adapta una receta de un aro de 18 a uno de 22 cm.'], { t: 'flujo', p: ['medir', 'superficie', 'razón', 'multiplicar'] }],
    ['pasteleria', 'pas2_produccion', 'Organizar la producción', ['Una tarta de varias capas se prepara en varios días.', 'El primer día se hacen bases e insertos; el segundo, mousses y montaje.', 'Una hoja de producción indica tareas, cantidades y horas.', 'Etiquetar cada elaboración con fecha evita errores.'], ['hoja de producción', 'planificación', 'etiqueta', 'mise en place'], 'coc_tiempo', 'V:Una tarta compleja se hace en varios días.|F:Todo se prepara el mismo minuto.|V:La etiqueta lleva fecha.', ['Haz la hoja de producción de una tarta.', '¿Qué elaboraciones pueden congelarse?'], { t: 'flujo', p: ['día 1: bases', 'día 2: montaje', 'día 3: glaseado', 'entrega'] }],
    /* Batidos */
    ['batidos', 'bat2_proporcion', 'La proporción justa', ['Un batido equilibrado suele llevar partes parecidas de fruta y líquido.', 'Más fruta da un batido espeso; más líquido, uno ligero.', 'Una verdura de hoja por vaso basta para empezar.', 'Anotar las cantidades permite repetir el batido igual.'], ['proporción', 'textura', 'medir', 'repetir'], 'coc_proporcion', 'V:Más fruta espesa el batido.|F:Las proporciones no importan.|V:Anotar permite repetir.', ['Escribe tu batido favorito con cantidades.', 'Adapta la proporción para un batido de cuchara.'], { t: 'flujo', p: ['líquido', 'fruta', 'verdura', 'extra', 'triturar'] }],
    ['batidos', 'bat2_temporada', 'Fruta de temporada', ['La fruta de temporada está más madura, más sabrosa y más barata.', 'En invierno abundan cítricos; en verano, frutos rojos y melón.', 'La fruta congelada fuera de temporada es una buena alternativa.', 'Cada país tiene su calendario de frutas.'], ['temporada', 'madurez', 'cítricos', 'calendario'], 'coc_merma', 'V:La fruta de temporada suele ser más barata.|F:Todas las frutas tienen la misma temporada.|V:La congelada es una alternativa.', ['Haz el calendario de frutas de tu país.', 'Propón un batido para cada estación.'], { t: 'ciclo', p: ['primavera', 'verano', 'otoño', 'invierno'] }],
    ['batidos', 'bat2_color', 'Color y sabor', ['El color anticipa el sabor: rojo a frutos rojos, verde a hojas.', 'Mezclar fruta roja con verde da un color marrón poco apetecible.', 'El limón evita que la manzana y el plátano se oscurezcan.', 'Servir en vaso transparente luce las capas.'], ['color', 'oxidación', 'capas', 'presentación'], 'coc_vasos', 'V:El limón frena la oxidación.|F:Rojo y verde juntos dan un color vivo.|V:Un vaso transparente luce las capas.', ['Diseña un batido en dos capas de color.', '¿Qué fruta añadirías para un color amarillo?'], { t: 'mapa', c: 'Colores', r: ['rojo', 'verde', 'amarillo', 'morado', 'naranja'] }],
    ['batidos', 'bat2_deporte', 'Batidos para el deporte', ['Antes del ejercicio conviene algo ligero con hidratos: plátano y avena.', 'Después, hidratos y proteína ayudan a recuperar: leche o yogur con fruta.', 'El agua sigue siendo la mejor bebida durante el ejercicio corto.', 'Los batidos no sustituyen a una comida completa cada día.'], ['hidratos', 'proteína', 'recuperación', 'hidratación'], 'coc_vasos', 'V:Después del ejercicio ayudan hidratos y proteína.|F:El batido debe sustituir todas las comidas.|V:El agua hidrata en ejercicio corto.', ['Propón un batido para antes y otro para después de entrenar.', '¿Cuándo basta con agua?'], { t: 'flujo', p: ['antes', 'durante', 'después'] }],
    ['batidos', 'bat2_infantil', 'Batidos para niños', ['Para niños basta medio vaso y sin azúcar añadido.', 'La fruta madura endulza de forma natural.', 'Se evitan frutos secos enteros en menores de cinco años por riesgo de atragantamiento.', 'Prepararlos juntos ayuda a probar frutas nuevas.'], ['ración infantil', 'sin azúcar', 'atragantamiento', 'probar'], 'coc_azucarlibre', 'V:La fruta madura endulza.|F:A los niños conviene añadirles azúcar.|V:Frutos secos enteros son un riesgo en menores.', ['Diseña un batido para una merienda escolar.', '¿Qué fruta nueva probarías con un niño?'], { t: 'flujo', p: ['elegir fruta', 'lavar', 'cortar', 'triturar', 'servir'] }],
    ['batidos', 'bat2_costos', 'Batidos en un negocio', ['El costo de un batido suma fruta, líquido, vaso, tapa y pajita.', 'Comprar fruta de temporada y congelar la madura reduce el costo.', 'Un menú corto facilita la preparación y reduce mermas.', 'El precio debe cubrir costo, tiempo y margen.'], ['costo por vaso', 'menú', 'merma', 'margen'], 'coc_racion', 'V:El vaso y la tapa forman parte del costo.|F:Un menú largo reduce mermas.|V:Congelar la fruta madura ahorra.', ['Calcula el costo de un vaso de batido.', 'Diseña un menú de cinco batidos.'], { t: 'flujo', p: ['ingredientes', 'envase', 'tiempo', 'margen', 'precio'] }],
    ['batidos', 'bat2_equipo', 'La batidora', ['Una batidora de vaso tritura mejor el hielo y la fruta congelada.', 'La de mano sirve para pocas cantidades.', 'Se pone primero el líquido y después lo sólido.', 'Nunca se llena por encima de la marca máxima.'], ['batidora de vaso', 'batidora de mano', 'orden de carga', 'seguridad'], 'coc_tiempo', 'V:Primero va el líquido.|F:Se puede llenar por encima del máximo.|V:La de vaso tritura mejor el hielo.', ['Explica el orden de carga de la batidora.', '¿Qué batidora usarías para diez vasos?'], { t: 'flujo', p: ['líquido', 'blando', 'duro', 'congelado', 'triturar'] }],
    ['batidos', 'bat2_bowls', 'Bowls y batidos de cuchara', ['Un bowl es un batido espeso servido en cuenco con toppings.', 'Se hace con fruta congelada y muy poco líquido.', 'Los toppings aportan textura: avena, semillas, fruta en rodajas.', 'Conviene no pasarse con miel o chocolate por encima.'], ['bowl', 'topping', 'textura', 'fruta congelada'], 'coc_proporcion', 'V:El bowl lleva poco líquido.|F:Cuanto más sirope, más saludable.|V:Los toppings aportan textura.', ['Diseña un bowl con tres toppings.', '¿Por qué se usa fruta congelada?'], { t: 'flujo', p: ['base espesa', 'cuenco', 'toppings', 'servir'] }]
  ];
  var UNI = U.map(function (a) { return { cat: a[0], m: a[0], id: a[1], t: a[2], i: a[3], k: a[4], g: a[5], vf: vf(a[6]), q: a[7], f: a[8], b: BANDAS, plus: true }; });
  UNI = UNI.concat(UNI.filter(function (u) { return u.m !== 'cocina'; }).map(function (u) { return Object.assign({}, u, { m: 'cocina', id: u.id + '_t' }); }));
  var CTX = ['En el obrador', 'Para la merienda del colegio', 'En un catering de bodas', 'Para la feria del barrio', 'En la cocina de casa', 'En un restaurante de menú del día', 'Para un pedido de cumpleaños', 'En una cafetería', 'En la clase de cocina', 'Para una comida familiar', 'En un puesto de mercado', 'Para la cena de fin de curso'];
  /* Une las frases del enunciado con «;» para que el contexto forme parte de toda la oración. */
  function unir(e) { return e.replace(/\. (¿?)(Si|Un|Una|El|La|Los|Las|Cada|Tu|Tus|Con|Para|De|Hay|Tienes|Usas|Vendes|Compras|Cuántos|Cuánto|Cuántas|Qué|Cuál|Calcula|Empiezas|Metes|Necesitas|Quieres|Sin|En|Al|Por|Después|Luego|Cuesta|Cobras|Todo|Todos|Así|Ahora|Y|A|Con)\b/g, function (m0, q, w) { return '; ' + q + w.toLowerCase(); }); }
  function conCtx(fn) {
    if (!fn || fn.__ctx) return fn;
    var w = function (u, C, r) {
      var x = fn.apply(this, arguments);
      if (!x || typeof x.e !== 'string' || !x.tipo || typeof r !== 'function' || x.__c) return x;
      x.__c = 1;
      var c = CTX[Math.floor(r() * CTX.length)], e = unir(x.e);
      x.e = c + ', ' + (e.charAt(0) === '¿' ? '¿' + e.charAt(1).toLowerCase() + e.slice(2) : e.charAt(0).toLowerCase() + e.slice(1));
      return x;
    };
    w.__ctx = 1; return w;
  }
  var G1 = (window.EU_COCINA_UNIDADES && EU_COCINA_UNIDADES.GEN) || {}, W = {};
  Object.keys(G2).forEach(function (k) { if (G1[k]) G1[k] = G2[k]; });
  Object.keys(G1).forEach(function (k) { G1[k] = conCtx(G1[k]); W[k] = G1[k]; });
  Object.keys(G).forEach(function (k) { G[k] = conCtx(G[k]); W[k] = G[k]; });
  ED.registrar({ unidades: UNI, generadores: W });
  window.EU_COCINA_UNIDADES2 = { U: UNI, GEN: G };
})();
