/* b6_comercio_electronico.js — materia «Comercio electrónico» (ecom): vender por internet desde cero.
   · 13 unidades: qué es, modelos, qué vender, proveedores y costos, montar la tienda, fichas, pagos,
     envíos, inventario, atención y devoluciones, atraer clientes, legal e impuestos, medir y escalar.
   · Datos por país con fuente (CNMC, AMVO, CCCE, CACE, CCS, Census…), medios de pago, comisión de
     pasarela, operadores y rango orientativo de envío, derecho de retracto, impuesto y autoridad.
   · Generadores con respuesta y proceso: margen, precio con comisiones, peso volumétrico, conversión,
     punto de equilibrio, precio sin impuesto, devoluciones, punto de pedido, comisión de pasarela, CAC máximo.
   · Páginas propias: ec_pais, ec_plataformas, ec_producto, ec_costeo (cascada), ec_pasos (capturas
     esquemáticas), ec_envios, ec_flujo (logística en 3D), ec_atencion, ec_legal, ec_escala.
   · Relleno de página ≥ 85 % para empre, mkt, ia, redes y ecom: mide cada página impresa y completa el
     hueco con un caso con dato real, un cálculo resuelto y líneas de notas (EU_ECOM.llenar; cfg.acab.relleno='no' lo apaga).
   Cargar después de b6_redes_sociales.js. */
(function () {
  'use strict';
  var ED = window.EU_EDITORIAL, LB = window.EU_LIBRO, SV = window.EU_SVG, EM = window.EU_EMPRE, RS = window.EU_REDES;
  if (!ED || !RS || window.EU_ECOM) return;
  var H = ED.H, it = H.it, esc = H.esc, K = RS.K, m = RS.m, bon = RS.bon, P = H.pick;
  function $(v, C) { return H.din(v, C); }
  function n(x, C) { return H.num(x, C); }
  function pc(a, b) { return Math.round(a / b * 1000) / 10; }
  function r2(x) { return Math.round(x * 100) / 100; }

  /* ─────────── datos por país ─────────── */
  var PAIS = {
    es: { dato: ['El comercio electrónico en España facturó más de 95.000 millones de euros en 2024, un 13,1 % más que en 2023; en el tercer trimestre de 2025 creció un 19,3 %.', 'CNMC, CNMCData 2025–2026'], pagos: ['Tarjeta', 'Bizum', 'PayPal', 'Transferencia'], fee: [1.5, .25, 'Stripe, tarjetas estándar del Espacio Económico Europeo'], env: ['Correos', 'SEUR', 'MRW', 'GLS'], envR: [4, 8], ret: '14 días naturales para desistir sin dar explicaciones', ley: 'Ley General para la Defensa de los Consumidores y Usuarios; LSSI (aviso legal) y RGPD', imp: [21, 'IVA'], aut: 'Consumo y oficinas de consumo de cada comunidad autónoma' },
    mx: { dato: ['Las ventas en línea en México llegaron a 941 mil millones de pesos en 2025 (19,2 % más) y ya son el 17,7 % de las ventas minoristas; en 2024 fueron 789.700 millones.', 'AMVO, Estudio de Venta Online 2025 y 2026'], pagos: ['Tarjeta de débito (75 %)', 'Tarjeta de crédito (49 %)', 'Efectivo en tiendas (26 %)', 'Transferencia (20 %)'], fee: [3.6, 3, 'Stripe México, tarjetas nacionales'], env: ['Estafeta', 'DHL', 'FedEx', '99minutos', 'Correos de México'], envR: [120, 250], ret: '5 días hábiles para revocar la compra (art. 56 de la Ley Federal de Protección al Consumidor)', ley: 'Ley Federal de Protección al Consumidor; las plataformas pueden retener ISR e IVA a quien vende', imp: [16, 'IVA'], aut: 'Profeco' },
    co: { dato: ['En Colombia las compras en línea crecieron un 19,9 % en 2025 mientras el ticket medio bajaba a 212.373 pesos: se compra más a menudo y por menos.', 'Cámara Colombiana de Comercio Electrónico (CCCE)'], pagos: ['PSE', 'Nequi y Daviplata', 'Tarjeta', 'Contraentrega'], fee: [3.5, 900, 'pasarela local (orientativo: consulta tu pasarela)'], env: ['Servientrega', 'Coordinadora', 'Interrapidísimo', '4-72'], envR: [12000, 25000], ret: '5 días hábiles de derecho de retracto (art. 47 de la Ley 1480 de 2011)', ley: 'Estatuto del Consumidor (Ley 1480 de 2011) y protección de datos (Ley 1581 de 2012)', imp: [19, 'IVA'], aut: 'Superintendencia de Industria y Comercio (SIC)' },
    ar: { dato: ['El comercio electrónico argentino facturó 34,03 billones de pesos en 2025 (55 % más), con 253 millones de órdenes y 25,1 millones de compradores; la tarjeta de crédito es el medio del 67 %.', 'CACE, Estudio Anual de Comercio Electrónico 2025'], pagos: ['Tarjeta de crédito (67 %)', 'Débito', 'Mercado Pago', 'Transferencia'], fee: [4, null, 'pasarela local (orientativo: varía según plazo de cobro y cuotas)'], env: ['Correo Argentino', 'Andreani', 'OCA', 'Mercado Envíos'], envR: null, ret: '10 días corridos para revocar (art. 34 de la Ley 24.240) y «botón de arrepentimiento» visible en la tienda', ley: 'Ley 24.240 de Defensa del Consumidor y Resolución 424/2020 (botón de arrepentimiento)', imp: [21, 'IVA'], aut: 'Defensa del Consumidor' },
    cl: { dato: ['En Chile, alimentos y bebidas ya es el segundo rubro del comercio electrónico, con el 18 % de las ventas en línea.', 'Cámara de Comercio de Santiago, 2026'], pagos: ['Webpay (débito y crédito)', 'Transferencia', 'Mercado Pago', 'Billeteras digitales'], fee: [3, 150, 'pasarela local (orientativo: consulta tu contrato)'], env: ['Chilexpress', 'Starken', 'Blue Express', 'Correos de Chile'], envR: [3500, 7000], ret: '10 días de derecho a retracto en compras a distancia (Ley 19.496)', ley: 'Ley 19.496 del consumidor y boleta electrónica del SII', imp: [19, 'IVA'], aut: 'SERNAC' },
    ve: { dato: ['En América Latina el comercio electrónico equivalía al 15,9 % de las ventas minoristas en 2025, casi el doble que la media mundial (8,4 %).', 'AMVO, Estudio de Venta Online 2026'], pagos: ['Pago móvil', 'Transferencia', 'Divisas en efectivo', 'Plataformas de pago internacionales'], fee: [3, null, 'orientativo: cada banco y plataforma fija su comisión'], env: ['MRW', 'Zoom', 'Tealca', 'Domesa'], envR: null, ret: 'Consulta la normativa vigente de la SUNDDE sobre cambios y devoluciones', ley: 'Normativa de precios y protección de las personas en el acceso a bienes (SUNDDE)', imp: [16, 'IVA'], aut: 'SUNDDE' },
    do: { dato: ['En República Dominicana las mipymes generan el 61,6 % del empleo; vender en línea es una de las vías de crecimiento que promueve el MICM.', 'Enmipymes, Banco Central y MICM'], pagos: ['Tarjeta (Azul, CardNet)', 'Transferencia', 'Pago contra entrega', 'Billeteras digitales'], fee: [3.5, 10, 'adquirente local (orientativo: consulta tu banco)'], env: ['Vimenpaq', 'Caribe Pack', 'Metro Pac', 'Inposdom'], envR: [250, 450], ret: 'Consulta los plazos de devolución de Pro Consumidor para ventas a distancia', ley: 'Ley 358-05 de Protección al Consumidor y factura electrónica (Ley 32-23)', imp: [18, 'ITBIS'], aut: 'Pro Consumidor' },
    us: { dato: ['En 2024 el comercio electrónico minorista de Estados Unidos sumó 1,19 billones de dólares, el 16,1 % de las ventas minoristas.', 'U.S. Census Bureau, 2025'], pagos: ['Tarjeta', 'PayPal', 'Billeteras del móvil', 'Pago a plazos'], fee: [2.9, .3, 'Stripe, tarjetas nacionales'], env: ['USPS', 'UPS', 'FedEx'], envR: [8, 15], ret: 'No hay un plazo federal general de devolución: publica tu política; la FTC exige enviar en el plazo prometido (o 30 días)', ley: 'Regla de la FTC sobre ventas por correo, internet o teléfono; impuesto de ventas de cada estado', imp: [7, 'impuesto de ventas (ejemplo: varía por estado)'], aut: 'FTC y fiscalías de cada estado' }
  };
  function PA(C) { return PAIS[C.pk] || PAIS.es; }
  function envR(C) { var A = PA(C); return A.envR || [m(5, C), m(9, C)]; }
  function fee(C) { var A = PA(C), f = A.fee; return [f[0], f[1] == null ? m(.2, C) : f[1], f[2]]; }

  /* ─────────── unidades ─────────── */
  var U = [];
  function un(id, t, g, i, k, vf, q, f, h, pz) { U.push({ m: 'ecom', id: id, b: 'sec bach fp adu'.split(' '), t: t, g: g, i: i, k: k, vf: vf.split('|').map(function (s) { return [s.slice(2), s.charAt(0) === 'V']; }), q: q, f: f, h: h, pz: pz, plus: true }); }
  un('ec_que', 'Qué es el comercio electrónico', 'ecom_ticket', ['El comercio electrónico es comprar y vender por internet: la tienda abre las 24 horas y llega a clientes lejos de tu barrio.', 'Puede ser de empresa a consumidor (B2C), entre empresas (B2B) o entre particulares (C2C).', 'En América Latina ya equivale al 15,9 % de las ventas minoristas, casi el doble que la media mundial (AMVO 2026).', 'Vender en línea no es solo abrir una web: incluye producto, pago, envío, atención y devoluciones.', 'El ticket medio (lo que gasta de media cada pedido) y la frecuencia de compra marcan cuánto factura una tienda.'], ['comercio electrónico', 'B2C', 'B2B', 'ticket medio', 'pedido'], 'V:La tienda en línea abre las 24 horas.|F:Vender en línea es solo tener una web.|V:El ticket medio es el gasto medio por pedido.', ['¿Qué compraste por internet el último mes y por qué?', 'Calcula el ticket medio de una tienda.'], { t: 'flujo', p: ['visita', 'carrito', 'pago', 'envío', 'postventa'] }, '¿Qué es lo último que compraste sin salir de casa?', ['ec_pais']);
  un('ec_modelos', 'Modelos: tienda propia, marketplace, redes y dropshipping', 'ecom_pago', ['En un marketplace (un gran mercado en línea) hay clientes desde el primer día, pero cobra comisión por venta y manda en las reglas.', 'La tienda propia da control de la marca y de los datos de clientes, pero hay que atraer las visitas.', 'Vender por redes y mensajería es la forma más barata de empezar: catálogo, conversación y pago con enlace.', 'En el dropshipping el proveedor envía el producto: no hay inventario, pero el margen es menor y el plazo de entrega lo controla otro.', 'Muchas tiendas combinan: empiezan en redes o marketplace y abren la tienda propia al tener clientes.'], ['marketplace', 'tienda propia', 'dropshipping', 'comisión', 'omnicanal'], 'V:El marketplace ya tiene clientes.|F:En el dropshipping controlas el plazo de entrega.|V:Se pueden combinar varios canales.', ['Compara tienda propia y marketplace para tu producto.', '¿Qué modelo elegirías para empezar y por qué?'], { t: 'mapa', c: 'Dónde vender', r: ['marketplace', 'tienda propia', 'redes y mensajería', 'dropshipping', 'tienda física + web'] }, '¿Dónde busca primero tu cliente cuando quiere comprar?', ['ec_plataformas']);
  un('ec_producto', 'Elegir qué vender', 'ecom_margen', ['Un buen producto para vender en línea resuelve un problema claro, pesa poco, no se rompe y deja margen.', 'Se valida antes de comprar stock: búsquedas, preguntas en redes, preventa o una prueba con pocas unidades.', 'Un nicho pequeño con clientes apasionados vende más que un catálogo enorme sin identidad.', 'Hay productos que exigen permisos: alimentos, cosméticos, juguetes o aparatos eléctricos.', 'La matriz de selección puntúa demanda, margen, tamaño, competencia y riesgo de devolución.'], ['nicho', 'validación', 'margen', 'matriz de selección', 'preventa'], 'V:Conviene validar antes de comprar stock.|F:Todos los productos se pueden vender sin permisos.|V:El peso influye en el envío.', ['Puntúa tres productos con la matriz de selección.', '¿Cómo validarías tu producto con poco dinero?'], { t: 'flujo', p: ['idea', 'búsquedas', 'margen', 'prueba', 'decisión'] }, '¿Qué producto comprarías tres veces al año?', ['ec_producto']);
  un('ec_proveedores', 'Proveedores y costos reales', 'ecom_precio', ['El costo real de un producto incluye compra, transporte hasta tu casa, aranceles si es importado, empaque y mermas.', 'Se piden muestras a tres proveedores y se comparan calidad, plazo, pedido mínimo y condiciones de pago.', 'Al precio final se le restan impuestos, comisión de pago, comisión del marketplace, envío no cobrado y publicidad.', 'El margen de contribución es lo que queda de cada venta para pagar los gastos fijos y ganar.', 'Una cascada de costos muestra en un gráfico dónde se va el dinero de cada venta.'], ['proveedor', 'costo total', 'pedido mínimo', 'margen de contribución', 'cascada de costos'], 'V:El costo incluye transporte y empaque.|F:El margen es el precio menos el costo del proveedor, sin más.|V:Conviene comparar tres proveedores.', ['Haz la cascada de costos de un producto.', 'Escribe el correo para pedir muestras a un proveedor.'], { t: 'flujo', p: ['precio final', 'impuesto', 'comisiones', 'envío', 'margen'] }, '¿Cuánto te queda de verdad de cada venta?', ['ec_costeo']);
  un('ec_tienda', 'Montar la tienda paso a paso', 'ecom_conv', ['Las plataformas de tienda en línea se alquilan por meses e incluyen plantilla, carrito y pagos.', 'Se necesita un dominio propio, un logotipo sencillo, las páginas legales y al menos diez productos bien presentados.', 'La tienda debe funcionar bien en el móvil: ahí se hace la mayoría de visitas.', 'Antes de abrir se hace una compra de prueba completa, del carrito a la entrega.', 'Las páginas imprescindibles: inicio, catálogo, ficha, carrito, contacto, envíos y devoluciones, y aviso legal.'], ['plataforma de tienda', 'dominio', 'plantilla', 'compra de prueba', 'páginas legales'], 'V:Hay que hacer una compra de prueba.|F:La tienda no necesita página de devoluciones.|V:El móvil es clave.', ['Lista las páginas de tu tienda.', 'Diseña la compra de prueba paso a paso.'], { t: 'flujo', p: ['plataforma', 'dominio', 'diseño', 'productos', 'prueba'] }, '¿Qué te hace desconfiar de una tienda en línea?', ['ec_pasos:tienda']);
  un('ec_ficha', 'Fichas de producto y fotos que venden', 'ecom_conv', ['La ficha responde todo lo que preguntaría el cliente: qué es, medidas, materiales, uso, envío y devolución.', 'Las fotos se hacen con luz natural, fondo limpio, varios ángulos y una foto en uso.', 'El título lleva las palabras que la gente escribe al buscar.', 'Las opiniones con foto de otros clientes aumentan la confianza.', 'Una ficha clara reduce preguntas y devoluciones.'], ['ficha de producto', 'fotografía', 'título', 'opiniones', 'confianza'], 'V:Las opiniones con foto dan confianza.|F:Basta con una foto del producto.|V:El título debe llevar palabras de búsqueda.', ['Escribe la ficha completa de un producto.', 'Planifica cinco fotos para ese producto.'], { t: 'mapa', c: 'Ficha de producto', r: ['título', 'fotos', 'precio y envío', 'descripción', 'opiniones'] }, '¿Qué necesitas ver antes de comprar algo que no puedes tocar?', ['ec_pasos:ficha']);
  un('ec_pagos', 'Medios de pago y comisiones', 'ecom_pago', ['Cada país tiene sus medios favoritos: tarjeta, transferencia inmediata, billeteras del móvil, efectivo en tiendas o contra entrega.', 'La pasarela de pago cobra un porcentaje y a veces una tarifa fija por cada cobro.', 'Ofrecer el medio que prefiere tu cliente reduce los carritos abandonados.', 'El contra entrega da confianza al comprador pero aumenta devoluciones y riesgo.', 'Nunca se guardan datos de tarjetas en tu propio ordenador: lo hace la pasarela certificada.'], ['pasarela de pago', 'comisión', 'transferencia', 'contra entrega', 'seguridad'], 'V:La pasarela cobra por cada cobro.|F:Conviene guardar los datos de las tarjetas.|V:Cada país prefiere medios distintos.', ['Calcula la comisión de pago de un pedido.', '¿Qué medios de pago ofrecerías en tu país?'], { t: 'flujo', p: ['carrito', 'medio de pago', 'pasarela', 'banco', 'confirmación'] }, '¿Cómo prefieres pagar cuando compras por internet?', ['ec_pasos:pago']);
  un('ec_logistica', 'Envíos y logística', 'ecom_envio', ['El transportista cobra por el mayor entre el peso real y el peso volumétrico: largo × ancho × alto ÷ un divisor (a menudo 5.000 con medidas en cm).', 'Un empaque ajustado baja el peso volumétrico y el costo.', 'Se puede cobrar el envío, incluirlo en el precio u ofrecer envío gratis a partir de un importe.', 'El plazo y el seguimiento del pedido influyen tanto como el precio.', 'La logística inversa es recoger devoluciones: también cuesta y hay que preverla.'], ['peso volumétrico', 'transportista', 'envío gratis', 'seguimiento', 'logística inversa'], 'V:Se cobra el mayor entre peso real y volumétrico.|F:El tamaño de la caja no importa.|V:Las devoluciones también cuestan.', ['Calcula el peso volumétrico de tu caja.', 'Decide tu política de envío.'], { t: 'flujo', p: ['pedido', 'preparar', 'empacar', 'enviar', 'entregar'] }, '¿Por qué una caja grande y ligera puede costar más que una pequeña y pesada?', ['ec_envios', 'ec_flujo']);
  un('ec_inventario', 'Inventario y punto de pedido', 'ecom_stock', ['El inventario es dinero parado: conviene tener lo necesario, no más.', 'El punto de pedido indica cuándo volver a comprar: demanda diaria × días de entrega del proveedor + stock de seguridad.', 'Los productos que más venden (a menudo pocos) merecen más atención.', 'Se cuenta el inventario físico cada mes y se compara con el del sistema.', 'Sin stock se pierden ventas; con demasiado, se inmoviliza dinero y aparecen mermas.'], ['inventario', 'punto de pedido', 'stock de seguridad', 'rotación', 'merma'], 'V:El inventario es dinero parado.|F:Cuanto más stock, mejor.|V:El punto de pedido avisa de cuándo comprar.', ['Calcula el punto de pedido de un producto.', 'Diseña tu hoja de inventario.'], { t: 'ciclo', p: ['vender', 'contar', 'punto de pedido', 'comprar', 'recibir'] }, '¿Qué pasa si se agota tu producto estrella en plena campaña?', []);
  un('ec_atencion', 'Atención al cliente, devoluciones y reseñas', 'ecom_devol', ['Responder rápido y con nombre propio convierte dudas en ventas.', 'Las plantillas de respuesta ahorran tiempo en las preguntas frecuentes.', 'La política de devoluciones se escribe clara y visible, respetando el plazo legal del país.', 'Tras la entrega se pide una reseña: las opiniones son la prueba social de la tienda.', 'Una queja bien resuelta puede crear un cliente fiel.'], ['atención al cliente', 'plantilla', 'devolución', 'reseña', 'fidelización'], 'V:Responder rápido ayuda a vender.|F:La política de devoluciones puede esconderse.|V:Una queja bien resuelta fideliza.', ['Escribe tres plantillas de respuesta.', 'Calcula el costo de las devoluciones de un mes.'], { t: 'ciclo', p: ['pregunta', 'respuesta', 'compra', 'reseña', 'repetición'] }, '¿Qué te hizo volver a comprar en una tienda?', ['ec_atencion']);
  un('ec_marketing', 'Atraer clientes a la tienda', 'ecom_cac', ['Las visitas llegan por buscadores, redes, anuncios, correo y recomendaciones.', 'El costo de adquisición (CAC) no debe superar el margen del primer pedido, salvo que el cliente repita.', 'La tasa de conversión de una tienda pequeña suele ser baja: de cada cien visitas, compran pocas.', 'El correo recupera carritos abandonados y trae de vuelta a quien ya compró.', 'Las fechas comerciales del país (rebajas, Buen Fin, Cyber, Hot Sale, Black Friday) concentran ventas.'], ['CAC', 'tráfico', 'carrito abandonado', 'fecha comercial', 'recompra'], 'V:El CAC debe compararse con el margen.|F:Todas las visitas compran.|V:El correo recupera carritos.', ['Calcula el CAC máximo que puedes pagar.', 'Elige las tres fechas comerciales de tu año.'], { t: 'flujo', p: ['atraer', 'visitar', 'carrito', 'comprar', 'repetir'] }, '¿Cuánto pagarías por conseguir un cliente nuevo?', ['ec_pasos:campana']);
  un('ec_legal', 'Aspectos legales e impuestos', 'ecom_iva', ['Toda tienda en línea publica quién vende, cómo contactar, precios con impuestos, gastos de envío y plazo de entrega.', 'El derecho de retracto o desistimiento permite devolver en un plazo que fija la ley de cada país.', 'Los datos de clientes se protegen: se pide consentimiento y se explica para qué se usan.', 'Hay que facturar y declarar las ventas; el impuesto sobre el consumo va incluido en el precio al cliente final.', 'Algunas categorías necesitan registro sanitario, etiquetado o certificados.'], ['aviso legal', 'derecho de retracto', 'protección de datos', 'factura', 'impuesto al consumo'], 'V:El precio debe mostrarse con impuestos.|F:La tienda puede ocultar quién vende.|V:El retracto lo fija la ley.', ['Revisa las páginas legales de una tienda que conozcas.', 'Calcula el precio sin impuesto de un producto.'], { t: 'mapa', c: 'Tienda legal', r: ['quién vende', 'precio con impuestos', 'envío y plazo', 'devoluciones', 'datos personales'] }, '¿Cuántos días tienes para devolver una compra en línea en tu país?', ['ec_legal']);
  un('ec_escalar', 'Medir y escalar', 'ecom_pe', ['Los números clave cada semana: visitas, conversión, ticket medio, margen, CAC y recompra.', 'El punto de equilibrio dice cuántos pedidos al mes cubren los gastos fijos.', 'Escalar es crecer sin que los costos crezcan igual: automatizar, externalizar envíos, comprar más barato por volumen.', 'Se crece primero en lo que ya funciona antes de abrir nuevos canales o países.', 'Un plan a 12 meses con metas mensuales permite ver si vas por buen camino.'], ['indicador', 'punto de equilibrio', 'escalar', 'automatizar', 'plan a 12 meses'], 'V:El punto de equilibrio cubre los gastos fijos.|F:Escalar es abrir diez canales a la vez.|V:Se crece primero en lo que funciona.', ['Calcula tu punto de equilibrio.', 'Escribe tus metas de los próximos 12 meses.'], { t: 'ciclo', p: ['medir', 'mejorar', 'automatizar', 'crecer', 'medir'] }, '¿Cuántos pedidos al mes necesitas para vivir de tu tienda?', ['ec_escala']);

  /* ─────────── generadores ─────────── */
  var PROD = [['una funda de móvil', 3, 12], ['una vela aromática', 4, 15], ['una camiseta estampada', 6, 20], ['un set de pinceles', 5, 18], ['una lámpara pequeña', 9, 32], ['una mochila', 12, 40], ['un juego de mesa', 10, 30], ['un cuaderno artesanal', 3, 11]];
  var GEN = {
    ecom_margen: function (u, C, r) { var p = P(r, PROD), c = m(p[1], C), v = m(p[2], C), g = v - c; return it('corta', 'Compras ' + p[0] + ' a ' + $(c, C) + ' y la vendes a ' + $(v, C) + ' (sin impuestos). ¿Qué porcentaje de margen bruto tienes sobre el precio?', n(pc(g, v), C) + ' %', { ac: [pc(g, v)], x: 'Margen = (' + $(v, C) + ' − ' + $(c, C) + ') ÷ ' + $(v, C) + ' × 100 = ' + n(pc(g, v), C) + ' %.' }); },
    ecom_precio: function (u, C, r) { var p = P(r, PROD), c = m(p[1], C), e = m(P(r, [1, 2]), C), k = P(r, [10, 12, 15]), mg = P(r, [30, 35, 40]), pv = bon((c + e) / (1 - (k + mg) / 100)); return it('corta', 'Tu costo por ' + p[0] + ' es ' + $(c, C) + ' más ' + $(e, C) + ' de empaque. El marketplace cobra el ' + k + ' % del precio y quieres que te quede un ' + mg + ' % del precio. ¿A qué precio (sin impuestos) debes venderla?', $(pv, C), { ac: [pv, n(pv, C)], x: 'Precio = costo ÷ (1 − comisión − margen) = ' + $(c + e, C) + ' ÷ (1 − ' + n((k + mg) / 100, C) + ') ≈ ' + $(pv, C) + '.' }); },
    ecom_envio: function (u, C, r) { var l = P(r, [20, 25, 30, 40]), a = P(r, [15, 20, 25]), h = P(r, [10, 12, 15, 20]), pr = P(r, [.8, 1.2, 1.5, 2]), vol = Math.round(l * a * h / 5000 * 10) / 10, co = Math.max(vol, pr); return it('corta', 'Una caja mide ' + l + ' × ' + a + ' × ' + h + ' cm y pesa ' + n(pr, C) + ' kg. Con un divisor de 5.000, ¿qué peso cobra el transportista?', n(co, C) + ' kg', { ac: [co], x: 'Volumétrico = ' + l + ' × ' + a + ' × ' + h + ' ÷ 5000 = ' + n(vol, C) + ' kg. Se cobra el mayor entre ' + n(vol, C) + ' y ' + n(pr, C) + ': ' + n(co, C) + ' kg.' }); },
    ecom_conv: function (u, C, r) { var v = P(r, [800, 1500, 2400, 4000]), p = Math.max(1, Math.round(v * P(r, [.8, 1.2, 1.6, 2.2]) / 100)); return it('corta', 'Tu tienda recibió ' + n(v, C) + ' visitas y ' + p + ' pedidos este mes. ¿Cuál es la tasa de conversión?', n(pc(p, v), C) + ' %', { ac: [pc(p, v)], x: 'Conversión = pedidos ÷ visitas × 100 = ' + p + ' ÷ ' + n(v, C) + ' × 100 = ' + n(pc(p, v), C) + ' %.' }); },
    ecom_pe: function (u, C, r) { var f = m(P(r, [300, 450, 600, 900]), C), mc = m(P(r, [6, 8, 10, 12]), C), q = Math.ceil(f / mc); return it('corta', 'Tus gastos fijos (plataforma, publicidad, internet) son ' + $(f, C) + ' al mes y cada pedido deja ' + $(mc, C) + ' de margen de contribución. ¿Cuántos pedidos necesitas para no perder dinero?', q, { ac: [q], x: 'Punto de equilibrio = fijos ÷ margen por pedido = ' + $(f, C) + ' ÷ ' + $(mc, C) + ' = ' + n(r2(f / mc), C) + ' → ' + q + ' pedidos.' }); },
    ecom_iva: function (u, C, r) { var A = PA(C), t = A.imp[0], pf = m(P(r, [12, 18, 24, 36, 48]), C), sin = r2(pf / (1 + t / 100)); return it('corta', 'Un producto se vende a ' + $(pf, C) + ' con ' + A.imp[1] + ' del ' + t + ' % incluido. ¿Cuál es el precio sin impuesto? ¿Cuánto es el impuesto?', $(sin, C) + '; ' + $(r2(pf - sin), C), { ac: [sin, n(sin, C)], x: 'Sin impuesto = ' + $(pf, C) + ' ÷ ' + n(1 + t / 100, C) + ' = ' + $(sin, C) + '. Impuesto = ' + $(pf, C) + ' − ' + $(sin, C) + ' = ' + $(r2(pf - sin), C) + '.' }); },
    ecom_devol: function (u, C, r) { var p = P(r, [80, 120, 200, 300]), d = P(r, [3, 5, 8, 10]), e = m(P(r, [4, 5, 6]), C), nd = Math.round(p * d / 100), g = nd * e * 2; return it('corta', 'De ' + p + ' pedidos, se devuelve el ' + d + ' %. Cada devolución cuesta ' + $(e, C) + ' de envío de ida y otro tanto de vuelta, que asumes tú. ¿Cuánto te cuestan las devoluciones del mes?', $(g, C), { ac: [g, n(g, C)], x: 'Devoluciones = ' + p + ' × ' + d + ' % = ' + nd + '. Costo = ' + nd + ' × ' + $(e, C) + ' × 2 = ' + $(g, C) + '.' }); },
    ecom_stock: function (u, C, r) { var dd = P(r, [3, 4, 5, 8]), pl = P(r, [5, 7, 10, 14]), se = P(r, [10, 15, 20]), pp = dd * pl + se; return it('corta', 'Vendes ' + dd + ' unidades al día, el proveedor tarda ' + pl + ' días y quieres ' + se + ' unidades de seguridad. ¿Con cuántas unidades en stock debes hacer el pedido?', pp, { ac: [pp], x: 'Punto de pedido = demanda diaria × plazo + seguridad = ' + dd + ' × ' + pl + ' + ' + se + ' = ' + pp + ' unidades.' }); },
    ecom_ticket: function (u, C, r) { var p = P(r, [120, 250, 400]), f = m(P(r, [2400, 5000, 9000]), C), t = r2(f / p); return it('corta', 'Una tienda facturó ' + $(f, C) + ' con ' + p + ' pedidos. ¿Cuál es su ticket medio?', $(t, C), { ac: [t, n(t, C)], x: 'Ticket medio = facturación ÷ pedidos = ' + $(f, C) + ' ÷ ' + p + ' = ' + $(t, C) + '.' }); },
    ecom_pago: function (u, C, r) { var F = fee(C), v = m(P(r, [15, 25, 40, 60, 90]), C), c = r2(v * F[0] / 100 + F[1]); return it('corta', 'Un cliente paga ' + $(v, C) + ' con tarjeta. La pasarela cobra ' + n(F[0], C) + ' % + ' + $(F[1], C) + ' (' + F[2] + '). ¿Cuánto te cobra y cuánto recibes?', $(c, C) + '; ' + $(r2(v - c), C), { ac: [c, n(c, C)], x: 'Comisión = ' + $(v, C) + ' × ' + n(F[0], C) + ' % + ' + $(F[1], C) + ' = ' + $(c, C) + '. Recibes ' + $(v, C) + ' − ' + $(c, C) + ' = ' + $(r2(v - c), C) + '.' }); },
    ecom_cac: function (u, C, r) { var t = m(P(r, [25, 35, 50]), C), mg = P(r, [30, 40, 50]), rp = P(r, [1, 2, 3]), mx = r2(t * mg / 100 * rp); return it('corta', 'El ticket medio es ' + $(t, C) + ', el margen de contribución es el ' + mg + ' % y cada cliente compra ' + rp + ' ' + (rp === 1 ? 'vez' : 'veces') + ' al año. ¿Cuánto puedes pagar como máximo por conseguir un cliente sin perder dinero?', $(mx, C), { ac: [mx, n(mx, C)], x: 'CAC máximo = ticket × margen × compras = ' + $(t, C) + ' × ' + mg + ' % × ' + rp + ' = ' + $(mx, C) + '.' }); }
  };

  /* ─────────── flujos paso a paso ─────────── */
  var FL = {
    tienda: { t: 'Paso a paso: montar la tienda en una plataforma', intro: 'Pantallas esquemáticas de un panel de tienda cualquiera (no reproducen una marca concreta).', pant: [{ tit: 'Alta', filas: [['campo', 'Correo y contraseña', 1], ['campo', 'Nombre de la tienda', 1], ['campo', 'País y moneda', 2], ['btn', 'Crear tienda']] }, { tit: 'Diseño', filas: [['img', 'plantilla', 3], ['campo', 'Logotipo y colores', 3], ['btn', 'Aplicar']] }, { tit: 'Productos', filas: [['lista', '10 productos', 4], ['btn', '+ Añadir producto']] }, { tit: 'Ajustes', filas: [['campo', 'Pagos', 5], ['campo', 'Envíos', 5], ['campo', 'Páginas legales', 6], ['btn', 'Abrir tienda', 7]] }], pasos: ['Crea la cuenta con el nombre de la tienda.', 'Elige país y moneda: fijan impuestos y formato de precios.', 'Elige una plantilla sencilla y añade logotipo y colores.', 'Carga al menos diez productos con ficha completa.', 'Configura pagos y zonas de envío con sus tarifas.', 'Publica las páginas legales: aviso legal, privacidad, envíos y devoluciones.', 'Haz una compra de prueba completa y solo entonces abre la tienda.'], ojo: 'Conecta un dominio propio desde el principio: cambiar de dirección más tarde hace perder posiciones en los buscadores y confunde a los clientes.' },
    ficha: { t: 'Paso a paso: una ficha de producto completa', intro: 'Pantalla del cliente (izquierda) y del editor (derecha). Cada número es un elemento que el cliente busca.', pant: [{ tit: 'Ficha (cliente)', filas: [['img', 'foto principal', 1], ['lin', 'Título con palabras de búsqueda', 2], ['dato', 'precio', 3, 'impuestos incluidos'], ['btn', 'Añadir al carrito'], ['lin', 'Envío en 48 h · Devolución', 4]] }, { tit: 'Fotos', filas: [['img', 'uso real', 1], ['lista', 'ángulos y detalle']] }, { tit: 'Editor', filas: [['campo', 'Título', 2], ['campo', 'Precio y stock', 3], ['campo', 'Descripción', 5], ['campo', 'Peso y medidas', 6]] }, { tit: 'Opiniones', filas: [['lista', '★★★★★', 7], ['img', 'foto de cliente']] }], pasos: ['Foto principal sobre fondo limpio, y otras en uso y de detalle.', 'Título con lo que la gente escribe al buscar: tipo, material, uso.', 'Precio con impuestos y stock actualizado.', 'Plazo de envío y política de devolución a la vista.', 'Descripción: para qué sirve, medidas, materiales, cuidados.', 'Peso y medidas del paquete: calculan el envío.', 'Opiniones de clientes, mejor con foto.'], ojo: 'Si recibes la misma pregunta dos veces, la respuesta falta en la ficha: añádela.' },
    pago: { t: 'Paso a paso: activar los cobros', intro: 'Pantallas esquemáticas de una pasarela de pago. Los datos exactos los pide cada proveedor.', pant: [{ tit: 'Pasarela', filas: [['campo', 'Tipo: persona o empresa', 1], ['campo', 'Documento fiscal', 1], ['campo', 'Cuenta bancaria', 2], ['btn', 'Verificar']] }, { tit: 'Medios', filas: [['lista', 'tarjeta · transferencia · billetera', 3]] }, { tit: 'Pago (cliente)', filas: [['dato', 'total', 0, 'con envío e impuestos'], ['campo', 'Medio de pago', 4], ['btn', 'Pagar', 4]] }, { tit: 'Panel', filas: [['dato', 'cobrado', 5, 'menos comisiones'], ['lista', 'liquidaciones', 6]] }], pasos: ['Da de alta la cuenta con tu documento fiscal.', 'Vincula la cuenta bancaria donde recibirás el dinero.', 'Activa los medios de pago que más usa tu país.', 'Haz un pago de prueba y comprueba el correo de confirmación.', 'Revisa en el panel la comisión de cada cobro.', 'Comprueba cuándo se liquida el dinero en tu banco.'], ojo: 'La tienda nunca debe guardar números de tarjeta: lo hace la pasarela. Si alguien te pide los datos de su tarjeta por mensaje, no los aceptes.' },
    campana: { t: 'Paso a paso: recuperar carritos abandonados', intro: 'Pantallas esquemáticas. Alrededor del 70 % de los carritos se abandonan antes de pagar (Baymard Institute).', pant: [{ tit: 'Carrito', filas: [['lista', '2 productos'], ['dato', 'total', 1, 'con envío'], ['btn', 'Pagar']] }, { tit: 'Correo 1 (1 h)', filas: [['lin', '«¿Se te olvidó algo?»', 2], ['img', 'productos'], ['btn', 'Volver al carrito']] }, { tit: 'Correo 2 (24 h)', filas: [['lin', 'Opiniones y dudas', 3], ['btn', 'Terminar compra']] }, { tit: 'Panel', filas: [['dato', '12 %', 4, 'carritos recuperados'], ['lista', 'ventas']] }], pasos: ['Muestra el envío y los impuestos antes del último paso: los costos inesperados son la gran causa de abandono.', 'Envía un primer recordatorio una hora después, solo a quien dio permiso.', 'Envía un segundo al día siguiente con opiniones y respuestas a dudas.', 'Mide qué parte de los carritos recuperas y cuánto facturan.'], ojo: 'Solo se escribe a quien aceptó recibir correos: la ley de protección de datos lo exige.' }
  };

  /* ─────────── páginas ─────────── */
  var PAG = {
    ec_pais: function (pg, C, modo) {
      var A = PA(C), F = fee(C), R = envR(C);
      return H.cabecera(C, pg) + H.h1(C, 'Vender en línea en ' + C.P.n) + K.caja(C, 'El mercado', esc(A.dato[0])) + K.fuente(C, A.dato[1]) +
        K.tabla(C, ['Tema', 'En ' + C.P.n], [['Medios de pago', A.pagos.join(' · ')], ['Comisión de pago de referencia', n(F[0], C) + ' % + ' + $(F[1], C) + ' (' + F[2] + ')'], ['Transportistas', A.env.join(' · ')], ['Envío nacional de 1 kg', $(R[0], C) + ' – ' + $(R[1], C) + ' (rango orientativo 2025–2026; consulta la tarifa vigente)'], ['Devoluciones', A.ret], ['Impuesto al consumo', A.imp[1] + ' ' + A.imp[0] + ' %'], ['Autoridad', A.aut]], { fs: '.84em' }) +
        (SV && SV.barras ? '<div style="max-width:115mm;margin:0 auto 3mm">' + SV.barras(C, { cats: ['Pago', 'Envío', 'Impuesto'], vals: [r2(F[0] + F[1] / m(30, C) * 100), r2(R[0] / m(30, C) * 100), A.imp[0]], unidad: '% de un pedido de ' + $(m(30, C), C), valores: true }) + '</div>' : '') +
        K.caja(C, 'Cómo se lee el gráfico', 'En un pedido de ' + esc($(m(30, C), C)) + ', el pago, el envío más barato y el impuesto se llevan esos porcentajes antes de pagar el producto. Por eso el precio se calcula siempre con todo incluido.', true) + H.folio(C, pg);
    },
    ec_plataformas: function (pg, C, modo) {
      return H.cabecera(C, pg) + H.h1(C, 'Dónde vender: cuatro caminos') + K.p('No hay un canal mejor que otro: depende del producto, del dinero para empezar y de cuánto control quieres.') +
        K.tabla(C, ['Canal', 'Ventaja', 'Costo típico', 'Riesgo'], [['Marketplace', 'Clientes desde el primer día', 'Comisión por venta (a menudo entre el 10 % y el 20 % según categoría) + envío', 'Guerra de precios; las reglas las pone otro'], ['Tienda propia', 'Marca y datos de clientes propios', 'Cuota mensual de la plataforma + comisión de pago', 'Hay que atraer cada visita'], ['Redes y mensajería', 'Empezar hoy casi sin costo', 'Comisión de pago; tu tiempo', 'Depende del alcance de la red'], ['Dropshipping', 'Sin inventario', 'Margen menor', 'Plazos y calidad en manos del proveedor']], { fs: '.82em' }) +
        H.h2(C, 'Qué te queda de un pedido de ' + $(m(30, C), C) + ' en cada canal') + K.barrasH(C, [['Marketplace (15 %)', r2(m(30, C) * .85)], ['Tienda propia (pago 3 %)', r2(m(30, C) * .97)], ['Redes (pago 3 %)', r2(m(30, C) * .97)], ['Dropshipping (margen 25 %)', r2(m(30, C) * .25)]].map(function (x) { return [x[0], x[1], $(x[1], C)]; })) +
        K.caja(C, 'Ojo con el gráfico', 'En dropshipping lo que queda ya es margen: el proveedor cobra el producto y el envío. En los demás canales falta restar el costo del producto, el envío y la publicidad.', true) + K.items(pg, C, modo) + H.folio(C, pg);
    },
    ec_producto: function (pg, C, modo) {
      var ej = [['Velas aromáticas', 4, 5, 4, 3, 4], ['Muebles de palé', 3, 4, 1, 4, 3], ['Fundas de móvil', 5, 3, 5, 1, 4], ['Café de especialidad', 4, 4, 4, 3, 5]];
      return H.cabecera(C, pg) + H.h1(C, 'La matriz para elegir qué vender') + K.p('Puntúa del 1 al 5 cada criterio. Gana el producto con más puntos, siempre que ninguno tenga un 1 en margen.') +
        K.tabla(C, ['Producto', 'Demanda', 'Margen', 'Tamaño y peso', 'Poca competencia', 'Pocas devoluciones', 'Total'], ej.map(function (e) { return e.concat([e.slice(1).reduce(function (a, b) { return a + b; }, 0)]); }).concat([['Mi producto 1', '', '', '', '', '', ''], ['Mi producto 2', '', '', '', '', '', ''], ['Mi producto 3', '', '', '', '', '', '']]), { fs: '.8em', num: true }) +
        H.h2(C, 'Cómo validar con poco dinero') + K.pasos(C, ['Busca el producto en el buscador y en los marketplaces: ¿cuántos lo venden y a qué precio?', 'Pregunta a 20 personas de tu público si lo comprarían y a qué precio.', 'Publica una preventa o un formulario de interés antes de comprar stock.', 'Compra una tanda pequeña y mide cuánto tarda en venderse.']) + K.items(pg, C, modo) + H.folio(C, pg);
    },
    ec_costeo: function (pg, C, modo) {
      var T = C.T, A = PA(C), F = fee(C), pv = m(30, C), iv = r2(pv - pv / (1 + A.imp[0] / 100)), pr = m(9, C), em = m(1, C), en = envR(C)[0], pa = r2(pv * F[0] / 100 + F[1]), mk = r2((pv - iv) * .12), pu = m(4, C), mg = r2(pv - iv - pr - em - en - pa - mk - pu);
      var L = [['Precio con impuesto', pv], [A.imp[1], -iv], ['Producto', -pr], ['Empaque', -em], ['Envío no cobrado', -en], ['Comisión de pago', -pa], ['Comisión marketplace 12 %', -mk], ['Publicidad por pedido', -pu], ['Margen que queda', mg]];
      var W = 620, Hh = 250, x0 = 40, bw = 58, esc2 = 180 / pv, acc = pv, out = '', d3 = K.d3(C);
      L.forEach(function (l, i) { var x = x0 + i * 64, v = l[1], top, h; if (i === 0) { top = 210 - pv * esc2; h = pv * esc2; } else if (i === L.length - 1) { top = 210 - Math.max(0, mg) * esc2; h = Math.abs(mg) * esc2; } else { top = 210 - acc * esc2; h = -v * esc2; acc += v; } var col = i === 0 ? T.acc : i === L.length - 1 ? (mg >= 0 ? T.acc : '#C0392B') : T.acc2; if (d3) out += '<polygon points="' + (x + bw) + ',' + top + ' ' + (x + bw + 7) + ',' + (top - 5) + ' ' + (x + bw + 7) + ',' + (top + h - 5) + ' ' + (x + bw) + ',' + (top + h) + '" fill="' + (SV && SV.osc ? SV.osc(col, .3) : col) + '"/>'; out += '<rect x="' + x + '" y="' + top + '" width="' + bw + '" height="' + Math.max(1, h) + '" fill="' + col + '"/>' + K.tx(x + bw / 2, top - 8, H.num(Math.abs(v), C), { f: T.cuerpo, s: 10, w: 700, c: T.ink }) + '<foreignObject x="' + (x - 3) + '" y="214" width="' + (bw + 6) + '" height="36"><div xmlns="http://www.w3.org/1999/xhtml" style="font:9px/1.15 ' + esc(T.cuerpo) + ';text-align:center;color:' + T.ink + '">' + esc(l[0]) + '</div></foreignObject>'; });
      return H.cabecera(C, pg) + H.h1(C, 'Dónde se va el dinero de una venta') + K.p('Cascada de costos de un pedido de ' + $(pv, C) + ' vendido en marketplace en ' + C.P.n + '. Producto de ' + $(pr, C) + ' (precio de proveedor de ejemplo: compara con tres proveedores reales), envío al precio más bajo del rango del país y comisión de pago de referencia.') +
        K.svg(W, Hh, out, 620) + K.tabla(C, ['Concepto', 'Importe'], L.map(function (l) { return [l[0], $(l[1], C)]; }), { fs: '.82em', num: true }) +
        K.caja(C, 'Por qué funciona', 'Ver la cascada evita el error más común: calcular el margen restando solo el costo del proveedor. Si el margen final queda por debajo del 10 % del precio, sube el precio, negocia el envío o vende por la tienda propia.', true) + K.items(pg, C, modo, 1) + H.folio(C, pg);
    },
    ec_pasos: function (pg, C, modo) { return K.paginaPasos(pg, C, modo, FL[pg.fl] || FL.tienda); },
    ec_envios: function (pg, C, modo) {
      var A = PA(C), R = envR(C), cajas = [['Sobre acolchado', 30, 22, 3, .3], ['Caja pequeña', 20, 15, 10, .8], ['Caja mediana', 30, 25, 15, 1.5], ['Caja grande', 40, 30, 30, 3]];
      return H.cabecera(C, pg) + H.h1(C, 'Envíos en ' + C.P.n + ': peso real y peso volumétrico') + K.p('Transportistas habituales: ' + A.env.join(', ') + '. Un envío nacional de 1 kg cuesta, de forma orientativa, entre ' + $(R[0], C) + ' y ' + $(R[1], C) + ' según operador, zona y plazo: pide cotización antes de fijar precios.') +
        K.tabla(C, ['Empaque', 'Medidas (cm)', 'Peso real', 'Volumétrico (÷ 5.000)', 'Se cobra'], cajas.map(function (c) { var v = Math.round(c[1] * c[2] * c[3] / 5000 * 10) / 10; return [c[0], c[1] + ' × ' + c[2] + ' × ' + c[3], n(c[4], C) + ' kg', n(v, C) + ' kg', n(Math.max(v, c[4]), C) + ' kg']; }), { fs: '.84em', num: true }) +
        K.barrasH(C, cajas.map(function (c) { var v = Math.max(Math.round(c[1] * c[2] * c[3] / 5000 * 10) / 10, c[4]); return [c[0], v, n(v, C) + ' kg']; })) +
        H.h2(C, 'Tres políticas de envío') + K.tabla(C, ['Política', 'Cuándo conviene'], [['Envío cobrado aparte', 'Productos pesados o clientes lejanos'], ['Envío incluido en el precio', 'Productos ligeros y precio alto'], ['Gratis desde un importe', 'Subir el ticket medio: fija el umbral un poco por encima del ticket actual']], { fs: '.84em' }) + K.items(pg, C, modo) + H.folio(C, pg);
    },
    ec_flujo: function (pg, C, modo) {
      var T = C.T, d3 = K.d3(C), E = ['Pedido', 'Pago', 'Preparar', 'Empacar', 'Enviar', 'Entregar', 'Reseña'], out = '', pal = SV && SV.paleta ? SV.paleta(C) : [T.acc, T.acc2];
      E.forEach(function (e, i) { var x = 20 + i * 86, y = 40 + (i % 2) * 70, col = pal[i % pal.length]; if (d3) out += '<polygon points="' + x + ',' + y + ' ' + (x + 12) + ',' + (y - 10) + ' ' + (x + 72) + ',' + (y - 10) + ' ' + (x + 60) + ',' + y + '" fill="' + (SV && SV.clr ? SV.clr(col, .5) : col) + '"/><polygon points="' + (x + 60) + ',' + y + ' ' + (x + 72) + ',' + (y - 10) + ' ' + (x + 72) + ',' + (y + 36) + ' ' + (x + 60) + ',' + (y + 46) + '" fill="' + (SV && SV.osc ? SV.osc(col, .3) : col) + '"/>'; out += '<rect x="' + x + '" y="' + y + '" width="60" height="46" rx="' + (d3 ? 0 : 6) + '" fill="' + col + '"/>' + K.tx(x + 30, y + 28, e, { f: T.cuerpo, s: 11, w: 700, c: '#fff' }) + K.tx(x + 30, y + 64, String(i + 1), { f: T.cuerpo, s: 11, c: T.ink }); if (i < E.length - 1) out += '<path d="M' + (x + 62) + ' ' + (y + 23) + ' L' + (x + 84) + ' ' + (y + 23 + (i % 2 ? -70 : 70)) + '" stroke="' + T.ink + '" stroke-width="1.5" fill="none" marker-end="url(#fl' + pg.num + ')"/>'; });
      out = '<defs><marker id="fl' + pg.num + '" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="' + T.ink + '"/></marker></defs>' + out;
      return H.cabecera(C, pg) + H.h1(C, 'El viaje de un pedido') + K.p('Siete pasos desde que el cliente pulsa «comprar» hasta que deja su opinión. Cada paso tiene un responsable y un tiempo máximo.') + K.svg(630, 190, out, 630) +
        K.tabla(C, ['Paso', 'Qué se hace', 'Tiempo meta'], [['1 · Pedido', 'Correo automático de confirmación', 'inmediato'], ['2 · Pago', 'Comprobar que el cobro está aprobado', 'minutos'], ['3 · Preparar', 'Sacar del stock y revisar el producto', '24 h'], ['4 · Empacar', 'Caja ajustada, protección, factura o ticket', '24 h'], ['5 · Enviar', 'Etiqueta del transportista y número de seguimiento al cliente', '24–48 h'], ['6 · Entregar', 'Vigilar incidencias y avisar si hay retrasos', 'según plazo prometido'], ['7 · Reseña', 'Pedir opinión 2–3 días después de la entrega', 'una semana']], { fs: '.84em' }) +
        K.caja(C, 'Por qué funciona', 'Escribir el proceso permite delegarlo: cuando crezca la tienda, otra persona podrá hacerlo igual de bien siguiendo esta hoja.', true) + K.items(pg, C, modo) + H.folio(C, pg);
    },
    ec_atencion: function (pg, C, modo) {
      var A = PA(C);
      return H.cabecera(C, pg) + H.h1(C, 'Plantillas de atención al cliente') + K.p('Adapta estas respuestas a tu tono y guárdalas en el móvil. Contesta siempre con tu nombre y en menos de un día.') +
        K.caja(C, '¿Cuándo llega mi pedido?', '«Hola, [nombre]. Tu pedido salió ayer con ' + esc(A.env[0]) + '. Este es tu número de seguimiento: [número]. Si mañana no lo ves en movimiento, escríbeme y lo reviso contigo.»') +
        K.caja(C, 'Quiero devolverlo', '«Claro, [nombre]. Tienes derecho a devolverlo: ' + esc(A.ret) + '. Te envío la etiqueta y, cuando lo recibamos, te devolvemos el dinero en [días].»') +
        K.caja(C, 'Llegó dañado', '«Lo siento mucho, [nombre]. ¿Me envías una foto del paquete y del producto? Te mando otro hoy mismo, sin costo, y no hace falta que devuelvas el dañado.»') +
        K.caja(C, 'Pedir una reseña', '«Hola, [nombre], ¿qué tal con tu [producto]? Si te gustó, una opinión con foto nos ayuda mucho: [enlace]. ¡Gracias por confiar en nosotros!»', true) +
        H.h2(C, 'Mis tiempos de respuesta') + K.tabla(C, ['Semana', 'Mensajes', 'Tiempo medio', 'Reseñas nuevas'], [['1', '', '', ''], ['2', '', '', ''], ['3', '', '', ''], ['4', '', '', '']]) + K.items(pg, C, modo) + H.folio(C, pg);
    },
    ec_legal: function (pg, C, modo) {
      var A = PA(C);
      return H.cabecera(C, pg) + H.h1(C, 'Lo legal en ' + C.P.n) + K.tabla(C, ['Tema', 'Qué dice la norma'], [['Ley principal', A.ley], ['Devoluciones', A.ret], ['Impuesto al consumo', A.imp[1] + ' ' + A.imp[0] + ' %, incluido en el precio al consumidor'], ['Autoridad de consumo', A.aut]], { fs: '.86em' }) +
        H.h2(C, 'Lista de comprobación de la tienda') + K.pasos(C, ['Datos de quien vende: nombre o razón social, documento fiscal, dirección y contacto.', 'Precios finales con impuestos y gastos de envío antes de pagar.', 'Plazo de entrega y política de devoluciones visibles.', 'Aviso de privacidad y casilla de consentimiento para correos.', 'Factura o comprobante de cada venta.', 'Permisos especiales si vendes alimentos, cosméticos, juguetes o aparatos eléctricos.']) +
        K.caja(C, 'Fuentes oficiales', 'Antes de abrir, lee la web de ' + esc(A.aut) + ' y la de tu administración tributaria: las normas cambian y esta página es un resumen.', true) + K.items(pg, C, modo) + H.folio(C, pg);
    },
    ec_escala: function (pg, C, modo) {
      var T = C.T, f = m(400, C), mc = m(9, C), pe = Math.ceil(f / mc), pedidos = [8, 14, 20, 28, 35, 42, 48, 55, 62, 70, 76, 82], gan = pedidos.map(function (p) { return Math.round(p * mc - f); });
      return H.cabecera(C, pg) + H.h1(C, 'Plan a 12 meses: cuándo empieza a ganar la tienda') + K.p('Ejemplo con gastos fijos de ' + $(f, C) + ' al mes y ' + $(mc, C) + ' de margen por pedido. El punto de equilibrio está en ' + pe + ' pedidos al mes.') +
        (SV && SV.barras ? SV.barras(C, { cats: pedidos.map(function (x, i) { return 'M' + (i + 1); }), vals: pedidos, unidad: 'pedidos', valores: true }) : '') +
        K.tabla(C, ['Mes', 'Pedidos', 'Resultado'], pedidos.filter(function (x, i) { return i % 2 === 1; }).map(function (p, k) { var i = k * 2 + 1; return ['Mes ' + (i + 1), p, $(gan[i], C)]; }), { fs: '.84em', num: true }) +
        K.caja(C, 'Cómo escalar sin perder margen', 'Automatiza correos y facturas, negocia tarifas de envío por volumen, compra más cantidad al proveedor cuando la rotación lo justifique y crece primero en el canal que ya vende.', true) + K.items(pg, C, modo) + H.folio(C, pg);
    }
  };
  var ITEMS = { ec_pais: 'ecom_pago', ec_plataformas: 'ecom_precio', ec_producto: 'ecom_margen', ec_costeo: 'ecom_precio', ec_envios: 'ecom_envio', ec_flujo: 'ecom_stock', ec_atencion: 'ecom_devol', ec_legal: 'ecom_iva', ec_escala: 'ecom_pe' };

  /* ─────────── visuales para páginas «vis» ─────────── */
  function visCaja(u, C, r) {
    var T = C.T, l = P(r, [30, 35, 40]), a = P(r, [20, 25, 30]), h = P(r, [15, 20, 25]), pr = P(r, [1, 1.5, 2, 3]), v = Math.round(l * a * h / 5000 * 10) / 10, s = 4, d3 = K.d3(C);
    var A = [60, 170], dx = l * s * .9, dy = h * s, pz = a * s * .5, out = '';
    out += '<polygon points="' + A[0] + ',' + A[1] + ' ' + (A[0] + dx) + ',' + A[1] + ' ' + (A[0] + dx) + ',' + (A[1] - dy) + ' ' + A[0] + ',' + (A[1] - dy) + '" fill="' + (d3 ? '#D9B382' : '#fff') + '" stroke="' + T.ink + '" stroke-width="1.5"/>';
    out += '<polygon points="' + A[0] + ',' + (A[1] - dy) + ' ' + (A[0] + pz) + ',' + (A[1] - dy - pz * .6) + ' ' + (A[0] + dx + pz) + ',' + (A[1] - dy - pz * .6) + ' ' + (A[0] + dx) + ',' + (A[1] - dy) + '" fill="' + (d3 ? '#E8C9A0' : '#fff') + '" stroke="' + T.ink + '" stroke-width="1.5"/>';
    out += '<polygon points="' + (A[0] + dx) + ',' + A[1] + ' ' + (A[0] + dx + pz) + ',' + (A[1] - pz * .6) + ' ' + (A[0] + dx + pz) + ',' + (A[1] - dy - pz * .6) + ' ' + (A[0] + dx) + ',' + (A[1] - dy) + '" fill="' + (d3 ? '#B88E5E' : '#fff') + '" stroke="' + T.ink + '" stroke-width="1.5"/>';
    out += K.tx(A[0] + dx / 2, A[1] + 16, l + ' cm', { f: T.cuerpo, s: 12, w: 700, c: T.acc }) + K.tx(A[0] - 8, A[1] - dy / 2, h + ' cm', { f: T.cuerpo, s: 12, w: 700, c: T.acc, a: 'end' }) + K.tx(A[0] + dx + pz / 2 + 14, A[1] - pz * .3 + 4, a + ' cm', { f: T.cuerpo, s: 12, w: 700, c: T.acc, a: 'start' }) + K.tx(A[0] + dx / 2, A[1] - dy / 2 + 4, n(pr, C) + ' kg', { f: T.cuerpo, s: 14, w: 700, c: T.ink });
    return { t: 'Peso volumétrico de una caja', intro: 'El transportista cobra el mayor entre el peso real y el volumétrico (largo × ancho × alto ÷ 5.000).', fig: K.svg(360, 200, out, 380), items: [it('corta', '¿Cuál es el peso volumétrico?', n(v, C) + ' kg', { ac: [v] }), it('corta', '¿Qué peso se cobra?', n(Math.max(v, pr), C) + ' kg', { ac: [Math.max(v, pr)] }), it('abierta', '¿Cómo reducirías el costo del envío de este paquete?', '', { lin: 2 })] };
  }
  function visEmbudo(u, C, r) {
    var v = P(r, [2000, 4000, 6000]), c = Math.round(v * P(r, [8, 10, 12]) / 100), k = Math.round(c * P(r, [35, 40, 50]) / 100), p = Math.max(2, Math.round(k * P(r, [30, 40, 50]) / 100)), E = [['Visitas', v], ['Añaden al carrito', c], ['Empiezan el pago', k], ['Compran', p]];
    return { t: 'El embudo de una tienda en línea', intro: 'Datos de un mes de una tienda pequeña en ' + C.P.ciudades[0] + '.', fig: K.embudo(C, E), items: [it('corta', '¿Cuál es la tasa de conversión (compras ÷ visitas)?', n(pc(p, v), C) + ' %', { ac: [pc(p, v)] }), it('corta', '¿Qué porcentaje de los carritos terminó en compra?', n(pc(p, c), C) + ' %', { ac: [pc(p, c)] }), it('abierta', '¿Qué harías para que menos gente abandone el carrito?', '', { lin: 2 })] };
  }
  function visCascada(u, C, r) {
    var pv = m(P(r, [20, 30, 40]), C), pr = r2(pv * P(r, [.3, .35, .4])), en = r2(pv * P(r, [.12, .15])), co = r2(pv * P(r, [.1, .12, .15])), pu = r2(pv * P(r, [.08, .1])), mg = r2(pv - pr - en - co - pu);
    return { t: 'Reparto de un pedido', intro: 'Pedido de ' + $(pv, C) + ' sin impuestos. Cada sector es una parte del precio.', fig: SV.sectores(C, { vals: [pr, en, co, pu, Math.max(0, mg)], cats: ['Producto', 'Envío', 'Comisiones', 'Publicidad', 'Margen'] }), items: [it('corta', '¿Cuánto queda de margen?', $(mg, C), { ac: [mg, n(mg, C)] }), it('corta', '¿Qué porcentaje del precio es margen?', n(pc(mg, pv), C) + ' %', { ac: [pc(mg, pv)] }), it('abierta', '¿Qué parte intentarías reducir primero y cómo?', '', { lin: 2 })] };
  }
  function visPantalla(u, C, r) {
    var F = FL[P(r, Object.keys(FL))], k = H.ent(r, 0, F.pant.length - 1);
    return { t: 'Lee la pantalla', intro: F.t.replace(/^Paso a paso: /, '') + '. Observa la pantalla ' + (k + 1) + '.', fig: '<div style="display:grid;grid-template-columns:52mm 1fr;gap:6mm;align-items:start"><div>' + K.movil(C, F.pant[k]) + '</div><div>' + K.pasos(C, F.pasos) + '</div></div>', items: [it('abierta', '¿Qué paso corresponde a cada número marcado?', '', { lin: 2 }), it('abierta', '¿Qué error evita el consejo «' + F.ojo.split(':')[0] + '»?', '', { lin: 2 })] };
  }
  if (SV && SV.visual) { var ME = /^ecom$/; SV.visual('ec_caja', visCaja, { materias: ME, max: 2 }); SV.visual('ec_embudo', visEmbudo, { materias: ME, max: 1 }); SV.visual('ec_cascada', visCascada, { materias: ME, max: 2 }); SV.visual('ec_pantalla', visPantalla, { materias: ME, max: 2 }); }

  /* ─────────── Para saber más ─────────── */
  var SABER = [['Récord en España', 'El comercio electrónico en España superó los 95.000 millones de euros en 2024, un 13,1 % más que el año anterior (CNMC).'], ['México acelera', 'Las ventas en línea en México llegaron a 941 mil millones de pesos en 2025 y ya son el 17,7 % de las ventas minoristas (AMVO 2026).'], ['Cómo pagan en México', 'El 75 % de los compradores en línea mexicanos usó tarjeta de débito, el 49 % de crédito y el 26 % efectivo en tiendas (AMVO 2025).'], ['Argentina en cuotas', 'La tarjeta de crédito es el medio de pago del 67 % de las compras en línea en Argentina; en 2025 hubo 25,1 millones de compradores (CACE).'], ['Estados Unidos', 'El comercio electrónico minorista de EE. UU. sumó 1,19 billones de dólares en 2024, el 16,1 % de las ventas minoristas (U.S. Census Bureau).'], ['América Latina', 'En 2025 el comercio electrónico equivalía al 15,9 % de las ventas minoristas en América Latina, frente al 8,4 % mundial (AMVO 2026).'], ['El carrito abandonado', 'El Baymard Institute calcula que alrededor del 70 % de los carritos de compra se abandonan antes de pagar.'], ['La primera compra segura', 'En 1994 la tienda NetMarket vendió un CD de Sting con pago cifrado: se considera la primera compra en línea segura.'], ['Nace Mercado Libre', 'Marcos Galperin fundó Mercado Libre en 1999 en Buenos Aires, cuando estudiaba en Stanford.'], ['De una tienda de tablas', 'Shopify nació en 2006 en Ottawa: sus fundadores crearon el programa para vender tablas de snowboard en línea.'], ['Impuestos por estado', 'En 2018 el Tribunal Supremo de EE. UU. (caso Wayfair) permitió a los estados cobrar impuesto de ventas a tiendas en línea de fuera.'], ['eBay y las subastas', 'Pierre Omidyar lanzó en 1995 AuctionWeb, la web de subastas que se convertiría en eBay.']];
  if (LB && LB.SABER) LB.SABER.ecom = SABER;

  /* ─────────── ideas para «Mi plan de negocio» ─────────── */
  var T26 = 'Importes de ejemplo: compáralos con cotizaciones reales de proveedores y transportistas. ';
  var IDEAS = [
    { id: 'marketplace_revende', g: 'ecom', n: 'Tienda de nicho en un marketplace', u: 'pedido', ico: 'bolsa', d: T26 + 'Vender en un gran mercado en línea da clientes desde el primer día a cambio de una comisión por venta.', inv: [['Primer inventario (50 unidades)', 450], ['Fotos y empaques', 120], ['Cuenta y verificación', 20]], mat: [['Producto', 9], ['Empaque', 1], ['Comisión del marketplace', 4], ['Comisión de pago', 1]], p: 30, h: .2, q: 80, fijos: [['Publicidad en el marketplace', 120], ['Herramientas', 20]], pasos: ['Elige un nicho con 10 productos que se complementen', 'Calcula el precio con la cascada de costos', 'Publica fichas con fotos propias', 'Responde preguntas en menos de 2 horas', 'Revisa cada semana conversión y reputación'], vender: ['Marketplace', 'Redes sociales', 'Clientes recurrentes'], riesgo: 'Guerra de precios: diferénciate con fotos, atención y paquetes.' },
    { id: 'bajo_demanda', g: 'ecom', n: 'Impresión bajo demanda (camisetas, tazas, láminas)', u: 'pedido', ico: 'bolsa', d: T26 + 'Diseñas y el taller imprime y envía cada pedido: no hay inventario, pero el margen depende del precio del taller.', inv: [['Tienda y dominio (año)', 250], ['Muestras de producto', 120], ['Diseños', 100]], mat: [['Producto impreso y envío del taller', 14], ['Comisión de pago', 1]], p: 25, h: .3, q: 70, fijos: [['Plataforma', 30], ['Publicidad', 150]], pasos: ['Pide muestras antes de vender', 'Crea 20 diseños para un público concreto', 'Fotografía las muestras en uso', 'Lanza con tu lista de contactos', 'Deja solo los diseños que se venden'], vender: ['Tienda propia', 'Redes sociales', 'Ferias y eventos'], riesgo: 'Plazos y calidad del taller: pide muestras y revisa opiniones de otros vendedores.' },
    { id: 'kits_regalo', g: 'ecom', n: 'Cajas de regalo con productos locales', u: 'caja', ico: 'bolsa', d: T26 + 'Cajas temáticas (cumpleaños, empresa, bienestar) con productos de artesanos de tu ciudad; se venden mucho en fechas comerciales.', inv: [['Primer stock de productos', 400], ['Cajas, papel y etiquetas', 150], ['Fotos y tienda', 150]], mat: [['Productos', 17], ['Caja y relleno', 3], ['Envío local', 4]], p: 42, h: .5, q: 50, fijos: [['Plataforma', 25], ['Publicidad', 100]], pasos: ['Acuerda precio mayorista con 5 artesanos', 'Diseña 3 cajas a distintos precios', 'Ofrece versión para empresas', 'Prepara stock antes de cada fecha fuerte', 'Pide reseñas con foto'], vender: ['Tienda propia y mensajería', 'Empresas', 'Mercados de temporada'], riesgo: 'Ventas muy concentradas en fechas: planifica el stock y la caja del resto del año.' }
  ];
  if (EM && EM.IDEAS) IDEAS.forEach(function (I) { if (!EM.IDEAS.some(function (x) { return x.id === I.id; })) EM.IDEAS.push(I); });

  ED.registrar({ materias: [{ id: 'ecom', n: 'Comercio electrónico', ico: '🛒', prodDef: 'libro' }], unidades: U, generadores: GEN, paginas: PAG });

  /* ═════════ relleno ≥ 85 % para materias de adultos ═════════ */
  var MM = 96 / 25.4, ADU = /^(empre|mkt|ia|redes|ecom)$/, NO_TIPO = /^(portada|creditos|indice|contra|bibliografia|emp_slide|s_.*)$/, MEMO = {}, memoK = [];
  function gens(mat) { var src = mat === 'empre' ? (EM && EM.GEN) : mat === 'redes' ? RS.GEN : mat === 'ecom' ? GEN : (window.EU_MKT_IA && EU_MKT_IA.GEN); var o = {}; Object.keys(src || {}).forEach(function (k) { if (mat === 'empre' || k.indexOf(mat === 'redes' ? 'redes_' : mat + '_') === 0) o[k] = src[k]; }); var X2 = window.EU_UNIDADES_ADULTOS && EU_UNIDADES_ADULTOS.GEN, p2 = { empre: 'emp2_', mkt: 'mkt2_', ia: 'ia2_', redes: 'rs2_', ecom: 'ec2_' }[mat]; if (X2 && p2) Object.keys(X2).forEach(function (k) { if (k.indexOf(p2) === 0) o[k] = X2[k]; }); return o; }
  function bloque(pg, C, modo) {
    var X = pg.fill; if (!X) return '';
    var T = C.T, out = '', G = gens(C.mat), r = H.rng(X.sem);
    if (X.dato) out += K.caja(C, 'Para saber más · ' + X.dato[0], esc(X.dato[1]), true);
    if (X.gen && G[X.gen]) { var x = null; try { x = G[X.gen](pg.u, C, r); } catch (e) { } if (x) out += '<div style="break-inside:avoid;margin:0 0 3mm"><div style="font-weight:700;color:' + T.acc + ';margin:0 0 1mm">Calcula</div><div style="line-height:1.45">' + x.e + '</div>' + H.lineas(2, C) + (x.x || x.s ? '<div style="font-size:.68em;opacity:.6;transform:rotate(180deg);text-align:right;margin-top:1.5mm">Solución: ' + esc(x.x || x.s) + '</div>' : '') + '</div>'; }
    if (X.lin) out += '<div style="font-weight:700;color:' + T.acc + ';margin:1mm 0 0">' + esc(X.titL || 'Mis notas') + '</div>' + H.lineas(X.lin, C);
    return '<div data-fill="1" style="margin-top:3mm">' + out + '</div>';
  }
  ED.registrar({ post: function (h, pg, C, modo) { if (!pg.fill) return h; try { var b = bloque(pg, C, modo), i = h.lastIndexOf('<div style="position:absolute;bottom:8mm'); return i > 0 ? h.slice(0, i) + b + h.slice(i) : h + b; } catch (e) { return h; } } });
  function medidor(C) {
    var W = C.papel.w * MM, Hp = C.papel.h * MM, host = document.createElement('div'), caja = document.createElement('div');
    host.style.cssText = 'position:fixed;left:-30000px;top:0;width:' + W + 'px;visibility:hidden;pointer-events:none;contain:layout style paint';
    caja.style.cssText = 'position:fixed;left:-30000px;top:0;visibility:hidden;contain:layout style paint;width:' + (W - 34 * MM) + 'px;font-family:' + C.T.cuerpo + ';font-size:' + C.fs + 'px;line-height:1.5';
    document.body.appendChild(host); document.body.appendChild(caja);
    return {
      hueco: function (p, res) {
        host.innerHTML = ED.paginaHTML(p, C, 'print', res); var el = host.firstChild; if (!el || !el.getBoundingClientRect) return null;
        var top = el.getBoundingClientRect().top, fondo = 0, tope = Hp - 20 * MM, pad = 16 * MM, hijos = [];
        var mete = function (nn) { for (var i = 0; i < nn.children.length; i++) { var c = nn.children[i], cs = getComputedStyle(c); if (cs.display === 'contents') mete(c); else if (cs.position !== 'absolute' && cs.position !== 'fixed') hijos.push(c); } };
        mete(el); hijos.forEach(function (c) { var b = c.getBoundingClientRect(); if (b.height) fondo = Math.max(fondo, b.bottom - top); });
        return { libre: (tope - fondo) / MM, lleno: Math.max(0, (fondo - pad) / (tope - pad)), alto: (tope - pad) / MM };
      },
      alto: function (html) { caja.innerHTML = html; return caja.getBoundingClientRect().height / MM; },
      fin: function () { host.remove(); caja.remove(); }
    };
  }
  function llenar(res, o) {
    o = o || {}; var C = res.C; if (!document.body || !C || !C.papel) return null;
    var Md = medidor(C), G = gens(C.mat), keys = Object.keys(G), sab = H.mezcla(H.rng(H.hash(C.mat + ':fill') + (C.semilla || 1)), ((LB && LB.SABER && LB.SABER[C.mat]) || []).slice()), si = o.st ? (o.st.si || 0) : 0, t0 = performance.now(), lin = C.fs * 1.5 / MM, stats = [];
    try {
      res.pages.forEach(function (p) {
        if (o.lista && !o.lista[p.num]) return;
        if (NO_TIPO.test(p.tipo) || p.fill) return;
        if (!o.medirTodo && performance.now() - t0 > (o.presup || 60000)) return;
        var h = Md.hueco(p, res); if (!h) return;
        if (h.lleno >= .85 || h.libre < 8) { stats.push(h.lleno); return; }
        var f = h.libre - 4, X = { sem: H.hash(C.mat + ':' + p.num) + (C.semilla || 1) }, u = p.u;
        if (f > 45 && si < sab.length) X.dato = sab[si++];
        if (f > 75 && keys.length) X.gen = u && G[u.g] ? u.g : keys[X.sem % keys.length];
        p.fill = X; var usado = X.dato || X.gen ? Md.alto(bloque(p, C, 'print')) : 0;
        if (usado > f) { delete X.gen; usado = X.dato ? Md.alto(bloque(p, C, 'print')) : 0; if (usado > f) { delete X.dato; usado = 0; } }
        var k = Math.floor((f - usado - 7) / lin); if (k >= 2) { X.lin = Math.min(k, 40); X.titL = p.items && p.items.length ? 'Mis respuestas y notas' : 'Mis notas'; }
        if (!X.dato && !X.gen && !X.lin) delete p.fill;
      });
    } finally { if (o.st) o.st.si = si; Md.fin(); }
    return stats;
  }

  /* Páginas visuales «esquema» que desbordan: quita huecos del final y, si no basta, reduce la figura. */
  function ajustarVis(res) {
    var C = res.C, Md = null;
    try {
      res.pages.forEach(function (p) {
        if (p.tipo !== 'vis' || p.gen !== 'esquema' || !p.v) return;
        Md = Md || medidor(C); var h = Md.hueco(p, res); if (!h || h.lleno <= 1.0) return;
        var its = p.v.items || p.items || [], tope = 130;
        var achica = function (min) {
          while (h && h.lleno > 1.0 && tope >= min && typeof p.v.fig === 'string') {
            p.v.fig0 = p.v.fig0 || p.v.fig;
            p.v.fig = p.v.fig0.replace(/<svg\b[^>]*>/, function (m) { return m.replace(/\sstyle="[^"]*"/g, '').replace('<svg', '<svg style="display:block;margin:0 auto;height:' + tope + 'mm;width:auto;max-width:100%"'); });
            h = Md.hueco(p, res); tope -= 10;
          }
        };
        achica(90);
        while (h && h.lleno > 1.0 && its.length > 3) { its.pop(); h = Md.hueco(p, res); }
        achica(55);
        while (h && h.lleno > 1.0 && its.length > 1) { its.pop(); h = Md.hueco(p, res); }
        if (p.items && p.items !== its) p.items = its;
      });
    } finally { if (Md) Md.fin(); }
  }

  /* ─────────── ensamblado ─────────── */
  var ens = ED.ensamblar;
  ED.ensamblar = function (cfg) {
    var res = ens(cfg);
    try {
      if (cfg && cfg.materia === 'ecom' && res && res.pages) { RS.insertar(res, PAG, ITEMS, GEN); RS.sinRepetir(res, GEN, 'ecom_'); }
      if (cfg && ADU.test(cfg.materia) && res && res.C && res.C.papel && res.C.papel.id !== 'slide' && document.body) ajustarVis(res);
      if (cfg && ADU.test(cfg.materia) && res && res.C && res.C.papel && res.C.papel.id !== 'slide' && ((cfg.acab || {}).relleno !== 'no') && ((cfg.acab || {}).relleno !== 'tandas') && !/^(pitch)$/.test(cfg.prod)) {
        var key = JSON.stringify(cfg);
        if (MEMO[key]) { var M = MEMO[key]; res.pages.forEach(function (p) { if (M[p.num]) p.fill = Object.assign({}, M[p.num]); }); }
        else { llenar(res); var g = {}; res.pages.forEach(function (p) { if (p.fill) g[p.num] = p.fill; }); MEMO[key] = g; memoK.push(key); if (memoK.length > 6) delete MEMO[memoK.shift()]; }
      }
    } catch (e) { console.warn('EU_ECOM', e); }
    return res;
  };
  window.EU_ECOM = { U: U, GEN: GEN, SABER: SABER, PAIS: PAIS, IDEAS: IDEAS, FL: FL, llenar: llenar, medidor: medidor, MEMO: MEMO };
})();
