/* b6_ideas_2026.js — ideas de negocio 2026 apoyadas en datos con fuente, más datos para «Para saber más»
   y cabecera correcta en libros de adultos de materias no escolares. Cargar después de b6_marketing_ia.js.
   Los importes de las fichas son de ejemplo (base EUR convertida con EU_EMPRE.FX): la ficha lo indica. */
(function () {
  'use strict';
  var ED = window.EU_EDITORIAL, EM = window.EU_EMPRE, LB = window.EU_LIBRO;
  if (!ED || !EM || window.EU_IDEAS_2026) return;
  var T26 = 'Importes de ejemplo: compáralos con precios reales de tu zona. ';
  var NUEVAS = [
    { id: 'tienda_online', g: 'tendencia', n: 'Tienda en línea de cuidado personal', u: 'pedido', ico: 'bolsa', d: T26 + 'Moda, belleza y cuidado personal están entre lo más comprado por internet en México (AMVO 2026); en América Latina el comercio electrónico ya es el 15,9 % de las ventas minoristas.',
      inv: [['Tienda en línea y dominio (primer año)', 250], ['Primer inventario', 900], ['Fotos de producto', 150], ['Empaques', 120]], mat: [['Costo del producto', 11], ['Empaque', 1], ['Comisión de pago', 1]], p: 24, h: .15, q: 60, fijos: [['Plataforma', 30], ['Publicidad', 200], ['Envíos no cobrados', 60]],
      pasos: ['Elige 10 productos de un solo nicho', 'Fotografía cada producto con fondo limpio', 'Calcula el precio con envío y comisión incluidos', 'Lanza con una lista de contactos propia', 'Mide conversión y costo por cliente cada semana'], vender: ['Tienda propia', 'Mercados en línea', 'Redes sociales'], riesgo: 'La publicidad puede comerse el margen: vigila el costo por cliente frente al valor de cada pedido.' },
    { id: 'redes_comercios', g: 'tendencia', n: 'Gestión de redes para comercios locales', u: 'cliente', ico: 'movil', d: T26 + 'En España el 46 % de quienes emprenden en fase inicial usa comercio electrónico y el 29 % ya integra la IA (Informe GEM 2025-2026): muchos comercios necesitan ayuda digital.',
      inv: [['Portátil (si no tienes)', 600], ['Programas de diseño y edición (año)', 150], ['Formación y certificados', 80]], mat: [['Herramientas por cliente', 15]], p: 300, h: 12, q: 5, fijos: [['Internet y teléfono', 40], ['Publicidad propia', 40]],
      pasos: ['Haz tres casos gratis o baratos para el portafolio', 'Ofrece un paquete cerrado: 12 publicaciones al mes', 'Mide alcance y mensajes recibidos de cada cliente', 'Cobra por adelantado cada mes', 'Sube la tarifa al tener resultados medidos'], vender: ['Comercios del barrio', 'Asociaciones de comerciantes', 'Recomendaciones'], riesgo: 'Depender de pocos clientes: si uno se va pierdes una parte grande del ingreso.' },
    { id: 'contenido_ia', g: 'tendencia', n: 'Contenido y atención con IA para pymes', u: 'proyecto', ico: 'libro', d: T26 + 'Las empresas latinas de EE. UU. duplicaron su uso de IA desde 2024 (Stanford SLEI 2026). Servicio: textos, fichas de producto, respuestas frecuentes y automatizaciones.',
      inv: [['Suscripciones de IA (primer mes)', 60], ['Formación', 100], ['Web sencilla', 120]], mat: [['Uso de herramientas por proyecto', 20]], p: 250, h: 8, q: 6, fijos: [['Suscripciones', 60], ['Internet', 30]],
      pasos: ['Domina una tarea concreta: fichas de producto o respuestas frecuentes', 'Mide el tiempo que ahorras al cliente', 'Vende por el ahorro, no por la herramienta', 'Revisa siempre lo que genera la IA', 'Explica al cliente qué datos no deben subirse'], vender: ['Tiendas en línea', 'Academias y clínicas', 'Hoteles y restaurantes'], riesgo: 'Errores de la IA: revisa cada entrega y no uses datos personales de clientes sin permiso.' },
    { id: 'comida_online', g: 'tendencia', n: 'Alimentos artesanales con venta en línea', u: 'caja', ico: 'pan', d: T26 + 'Alimentos y bebidas es ya el segundo rubro del comercio electrónico en Chile, con el 18 % (Cámara de Comercio de Santiago, 2026).',
      inv: [['Registro sanitario y curso', 250], ['Utensilios y horno', 500], ['Empaques y etiquetas', 200], ['Fotos', 100]], mat: [['Ingredientes', 6], ['Caja y etiqueta', 1.5], ['Reparto', 3]], p: 22, h: .6, q: 60, fijos: [['Luz y gas', 60], ['Publicidad', 80], ['Plataforma de pedidos', 20]],
      pasos: ['Confirma el registro sanitario que exige tu país', 'Elige un producto estrella que aguante el viaje', 'Vende por encargo con día fijo de entrega', 'Crea una suscripción mensual', 'Pide reseñas con foto'], vender: ['Pedidos por mensajería', 'Aplicaciones de reparto', 'Tiendas de barrio'], riesgo: 'Sin registro sanitario no se pueden vender alimentos: es lo primero.' },
    { id: 'formaliza', g: 'tendencia', n: 'Asesoría para formalizar microempresas', u: 'cliente', ico: 'libro', d: T26 + 'En República Dominicana se formalizaron 4.264 mipymes en 2025 y la meta es superar 350.000 formales antes de 2028 (MICM): hay demanda de ayuda con trámites y facturación.',
      inv: [['Formación en trámites y facturación electrónica', 150], ['Portátil e impresora', 500], ['Publicidad inicial', 80]], mat: [['Trámites y copias por cliente', 5]], p: 90, h: 4, q: 12, fijos: [['Internet', 30], ['Programa de facturación', 25]],
      pasos: ['Aprende los trámites oficiales de tu país paso a paso', 'Ofrece un paquete: registro, facturación y primer mes', 'Crea una guía gratuita como gancho', 'Colabora con asociaciones y ferias', 'Cobra una cuota mensual por la contabilidad básica'], vender: ['Mercados y ferias', 'Asociaciones de comerciantes', 'Redes sociales'], riesgo: 'Las normas cambian: consulta siempre la web oficial antes de asesorar.' }
  ];
  NUEVAS.forEach(function (I) { if (!EM.IDEAS.some(function (x) { return x.id === I.id; })) EM.IDEAS.push(I); });

  var MAS = {
    empre: [['Nace una tienda en un garaje', 'Jeff Bezos fundó Amazon en 1994 como librería en línea, desde un garaje de Bellevue (Washington).'], ['Zara empezó con batas', 'Amancio Ortega y Rosalía Mera abrieron en 1975 la primera tienda Zara en A Coruña; antes fabricaban batas en un pequeño taller.'], ['El Nobel del microcrédito', 'Muhammad Yunus y el Grameen Bank recibieron el Nobel de la Paz en 2006 por prestar pequeñas cantidades a personas sin acceso a la banca.'], ['Las pymes sostienen el empleo', 'En República Dominicana las mipymes generan el 61,6 % del empleo (Enmipymes, Banco Central y MICM).']],
    mkt: [['El primer anuncio de televisión', 'En 1941 un reloj Bulova protagonizó en Nueva York el primer anuncio de televisión emitido legalmente; costó 9 dólares.'], ['Google Maps y los comercios', 'Google Maps se lanzó en 2005; hoy las fichas de negocio son una forma gratuita de que los clientes locales te encuentren.'], ['Nace Facebook', 'Facebook se creó en 2004 en la Universidad de Harvard; Instagram llegó en 2010 y TikTok salió fuera de China en 2017.'], ['El carrito abandonado', 'El Baymard Institute calcula, con decenas de estudios, que alrededor del 70 % de los carritos de compra en línea se abandonan antes de pagar.'], ['Compras frecuentes', 'En Colombia el ticket medio en línea bajó a 212.373 pesos en 2025 mientras las compras subían un 19,9 %: se compra más a menudo y por menos (CCCE).']],
    ia: [['El primer coche sin conductor', 'En 2005 el vehículo Stanley, de la Universidad de Stanford, ganó el DARPA Grand Challenge recorriendo 212 km de desierto sin conductor.'], ['Watson en la tele', 'En 2011 el sistema Watson de IBM ganó el concurso de preguntas Jeopardy! a dos campeones humanos.'], ['Asistentes de voz', 'Siri llegó al iPhone en 2011 y Alexa se presentó en 2014: la IA entró en casa por la voz.'], ['Proteínas plegadas', 'AlphaFold predijo en 2020 la forma de las proteínas con una precisión cercana a la de laboratorio; en 2024 sus creadores recibieron el Nobel de Química.'], ['IA y emprendimiento latino', 'Las empresas latinas de EE. UU. duplicaron su adopción de IA desde 2024 (Stanford Latino Entrepreneurship Initiative, 2026).']]
  };
  if (LB && LB.SABER) Object.keys(MAS).forEach(function (k) { LB.SABER[k] = (LB.SABER[k] || []).concat(MAS[k]); });
  var E26 = window.EU_EMPRE_2026; if (E26 && E26.GENERAL) Array.prototype.push.apply(E26.GENERAL, MAS.empre);

  /* Cabecera: en libros de adultos de materias no escolares, «Personas adultas» en vez del nombre del ciclo */
  var NOESC = /^(empre|mkt|ia)$/, ens = ED.ensamblar;
  ED.ensamblar = function (cfg) { var res = ens(cfg); if (cfg && cfg.nivel === 'adu' && NOESC.test(cfg.materia) && res && res.C) res.C.cursoN = 'Personas adultas'; return res; };
  window.EU_IDEAS_2026 = { NUEVAS: NUEVAS, MAS: MAS };
})();
