/* b6_lib_musica2.js — Música (2/2): instrumentos, historia/formas/estilos, tecnología musical. 25 modelos.
   Materia `musica`. Prefijo `mu_`. Cargar después de b6_lib_musica.js. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('mu_guitarra')) return;
  var P = { papel: '#FBF7EE', azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', madera: '#C89A62', maderaO: '#8A5A30', metal: '#C8CED4', oro: '#E8C04A' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { len: 'Lenguaje musical', son: 'El sonido', voz: 'La voz y el cuerpo', ins: 'Instrumentos', his: 'Historia, formas y estilos', tec: 'Tecnología musical' };
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + f1 * .35, q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + (o && o.tit ? K.t(100, 14, o.tit, { s: 7, b: 1 }) : '') + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  function rot(K, x, y, tx, lx, ly, o) { return K.l('M' + x + ' ' + y + ' L' + lx + ' ' + ly, P.grisO, { w: .5 }) + K.c(x, y, 1.2, P.tinta, { negro: 1, w: .3 }) + K.t(lx + (lx < x ? -2 : 2), ly + 2, tx, { s: (o && o.s) || 5.4, b: 1, a: lx < x ? 'end' : 'start' }); }
  function persona(K, x, y, col) { return K.c(x, y, 6, P.piel, { w: .8 }) + K.p('M' + (x - 9) + ' ' + (y + 26) + ' Q' + (x - 9) + ' ' + (y + 8) + ' ' + x + ' ' + (y + 8) + ' Q' + (x + 9) + ' ' + (y + 8) + ' ' + (x + 9) + ' ' + (y + 26) + ' Z', col, { w: .8 }); }
  function penta(K, x, y, w) { var s = ''; for (var i = 0; i < 5; i++) s += K.l('M' + x + ' ' + (y + i * 5) + ' L' + (x + w) + ' ' + (y + i * 5), P.tinta, { w: .6 }); return s; }
  function caja(K, x, y, w, h, col, txt, fs) { return K.r(x, y, w, h, 3, col, { w: .9 }) + (txt ? K.t(x + w / 2, y + h / 2 + 2.3, txt, { s: fs || 6.2, b: 1 }) : ''); }

  var L = [
    /* ─────────── INSTRUMENTOS ─────────── */
    { id: 'mu_guitarra', fam: 'ins', n: 'Las partes de la guitarra',
      d: function (K) { var s = K.suelo(70, 138, 50) + K.c(70, 104, 30, P.madera, { w: 1 }) + K.c(70, 64, 22, P.madera, { w: 1 }) + K.e(70, 84, 18, 14, P.madera, { sin: 1 }) + K.c(70, 80, 9, P.maderaO, { w: .8 }) + K.r(58, 112, 24, 5, 1, P.maderaO, { w: .6 }) + K.r(66, 8, 8, 50, 1, P.maderaO, { w: .8 }) + K.r(64, 2, 12, 12, 2, P.maderaO, { w: .8 }); for (var i = 0; i < 6; i++) s += K.l('M' + (67 + i * 1.2) + ' 10 L' + (66 + i * 1.6) + ' 114', P.grisO, { w: .35 }); for (var j = 1; j < 6; j++) s += K.l('M66 ' + (12 + j * 8) + ' L74 ' + (12 + j * 8), P.metal, { w: .7 }); return s + rot(K, 70, 6, 'clavijero', 120, 8) + rot(K, 70, 30, 'mástil con trastes', 120, 30) + rot(K, 74, 80, 'boca', 120, 62) + rot(K, 82, 114, 'puente', 120, 98) + rot(K, 96, 104, 'caja de resonancia', 120, 120) + rot(K, 66, 46, 'cuerdas (6)', 22, 40); },
      intro: 'La guitarra es un cordófono: las cuerdas vibran y la caja de madera amplifica el sonido.',
      q: [['¿Para qué sirven las clavijas?', 'Para tensar o aflojar cada cuerda y afinarla.'], ['¿Qué hace un traste?', 'Acorta la cuerda al pisarla y sube la nota medio tono.'], ['¿Cómo se llaman las cuerdas al aire, de grave a agudo?', 'Mi, la, re, sol, si, mi.']],
      porque: 'Sin caja de resonancia la cuerda sonaría muy débil: la madera y el aire de dentro vibran con ella.' },
    { id: 'mu_violin', fam: 'ins', n: 'El violín y el arco',
      d: function (K) { var s = K.suelo(60, 140, 44) + K.p('M60 52 C40 52 38 70 46 78 C38 86 38 112 60 116 C82 112 82 86 74 78 C82 70 80 52 60 52 Z', P.madera, { w: 1 }) + K.l('M53 84 q-3 4 0 8 M67 84 q3 4 0 8', P.maderaO, { w: 1.2 }) + K.r(57, 14, 6, 44, 1, P.tinta, { w: .6 }) + K.c(60, 10, 5, P.maderaO, { w: .8 }) + K.r(54, 96, 12, 3, 1, P.maderaO, { w: .5 }) + K.r(55, 102, 10, 12, 3, P.tinta, { w: .5 }); for (var i = 0; i < 4; i++) s += K.l('M' + (58.5 + i) + ' 14 L' + (57 + i * 2) + ' 104', P.grisO, { w: .35 }); s += K.l('M104 24 L176 120', P.maderaO, { w: 1.6 }) + K.l('M108 22 L180 118', P.blanco, { w: 1 }) + K.r(172, 114, 10, 8, 1, P.tinta, { w: .5 }); return s + K.t(60, 132, 'violín', { s: 6.4, b: 1 }) + K.t(150, 132, 'arco (crin de caballo)', { s: 6, b: 1 }) + rot(K, 52, 88, 'efes', 24, 70) + rot(K, 60, 97, 'puente', 24, 100) + rot(K, 60, 10, 'voluta', 24, 14) + K.t(164, 44, 'cuerdas: sol, re, la, mi', { s: 5.2, b: 1 }) + K.t(164, 54, 'se frotan con el arco', { s: 4.8 }) + K.t(164, 62, 'o se pellizcan (pizzicato)', { s: 4.8 }); },
      intro: 'El violín es el cordófono más agudo de la familia de cuerda frotada; el arco hace vibrar las cuerdas.',
      q: [['¿De qué está hecho el arco?', 'De una vara de madera con crines de caballo tensadas.'], ['¿Qué significa pizzicato?', 'Pellizcar las cuerdas con los dedos en lugar de usar el arco.'], ['¿Para qué se usa resina en el arco?', 'Para que la crin agarre la cuerda y la haga vibrar.']],
      porque: 'La resina da fricción a la crin: sin ella el arco resbalaría sin sonar.' },
    { id: 'mu_flauta', fam: 'ins', n: 'Digitación de la flauta dulce',
      d: function (K) { var N = [['do', 7], ['re', 6], ['mi', 5], ['fa', 4], ['sol', 3], ['la', 2], ['si', 1]], s = K.suelo(100, 140, 96); N.forEach(function (q, k) { var x = 22 + k * 26; s += K.r(x - 5, 16, 10, 92, 4, P.amarillo, { w: .7 }) + K.r(x - 4, 12, 8, 8, 2, P.blanco, { w: .6 }) + K.c(x - 7, 30, 2.4, k < 7 ? P.tinta : P.blanco, { w: .5, negro: 1 }); for (var h = 0; h < 7; h++) { var on = h < q[1], y = 30 + h * 10; s += K.c(x, y, 2.6, on ? P.tinta : P.blanco, { w: .6, negro: on }); } s += K.t(x, 120, q[0], { s: 6.4, b: 1 }); }); return s + K.t(100, 134, 'negro = tapado · el agujero de atrás se tapa con el pulgar', { s: 5.4, b: 1 }); },
      intro: 'En la flauta dulce, cuantos más agujeros se tapan, más larga es la columna de aire y más grave la nota.',
      q: [['¿Qué nota se toca tapando solo el pulgar y el primer agujero?', 'Si.'], ['¿Por qué el do es la nota más grave de la tabla?', 'Porque tiene todos los agujeros tapados: la columna de aire es la más larga.'], ['¿Qué mano va arriba?', 'La izquierda.']],
      porque: 'Destapar un agujero acorta el tubo que vibra: es la misma idea que acortar una cuerda.' },
    { id: 'mu_piano', fam: 'ins', n: 'El piano por dentro',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(14, 92, 70, 14, 1, P.blanco, { w: .9 }) + K.l('M40 98 L112 72', P.maderaO, { w: 2.4 }) + K.c(76, 85, 2, P.grisO, { w: .5 }) + K.r(110, 60, 10, 12, 3, P.rojo, { w: .8 }) + K.l('M115 60 L115 46', P.maderaO, { w: 1.4 }) + K.l('M20 44 L188 44', P.grisO, { w: 1.4 }) + K.r(124, 36, 10, 8, 1, P.gris, { w: .6 }) + K.flecha(30, 82, 30, 96, P.azulO, { w: 1.3 }); return s + K.t(30, 78, '1 tecla', { s: 5.6, b: 1 }) + K.t(84, 68, '2 palanca', { s: 5.6, b: 1 }) + K.t(124, 70, '3 martillo', { s: 5.6, b: 1, a: 'start' }) + K.t(150, 38, 'apagador', { s: 5.2, b: 1, a: 'start' }) + K.t(170, 54, '4 cuerda', { s: 5.6, b: 1 }) + K.t(100, 118, 'El martillo golpea la cuerda y rebota', { s: 6.2, b: 1 }) + K.t(100, 130, 'Es cordófono y percusión a la vez', { s: 5.6 }); },
      intro: 'Al bajar una tecla, una palanca lanza un martillo de fieltro que golpea la cuerda y se aparta.',
      q: [['¿Por qué el piano se considera también de percusión?', 'Porque las cuerdas suenan por un golpe de martillo.'], ['¿Qué hace el apagador?', 'Detiene la vibración al soltar la tecla.'], ['¿Qué hace el pedal derecho?', 'Levanta todos los apagadores para que las notas sigan sonando.']],
      porque: 'Por eso se puede tocar fuerte o suave: la fuerza del dedo pasa al martillo.' },
    { id: 'mu_bateria', fam: 'ins', n: 'La batería',
      d: function (K) { var s = K.suelo(100, 136, 90); s += K.e(100, 104, 26, 26, P.rojo, { w: 1 }) + K.e(100, 104, 18, 18, P.blanco, { w: .7 }) + K.cil(58, 88, 14, 22, P.rojo, { w: .8 }) + K.cil(84, 62, 11, 12, P.rojo, { w: .8 }) + K.cil(118, 62, 11, 12, P.rojo, { w: .8 }) + K.cil(150, 92, 16, 26, P.rojo, { w: .8 }) + K.l('M32 40 L32 124 M172 30 L172 124', P.metal, { w: 1.2 }) + K.e(32, 40, 16, 3, P.oro, { w: .8 }) + K.e(32, 44, 16, 3, P.oro, { w: .8 }) + K.e(172, 30, 20, 4, P.oro, { w: .8 }); return s + K.t(100, 108, 'bombo', { s: 6, b: 1 }) + K.t(58, 120, 'caja', { s: 6, b: 1 }) + K.t(100, 52, 'toms', { s: 6, b: 1 }) + K.t(150, 130, 'tom de piso', { s: 5.6, b: 1 }) + K.t(32, 32, 'charles', { s: 5.6, b: 1 }) + K.t(172, 20, 'platillo', { s: 5.6, b: 1 }) + K.t(100, 146, 'Bombo con el pie · charles con el pie y los palillos', { s: 5.2 }); },
      intro: 'La batería reúne membranófonos (tambores) e idiófonos (platillos) para que una sola persona lleve el ritmo.',
      q: [['¿Qué parte se toca con el pie derecho?', 'El bombo, con un pedal.'], ['¿Cuál suele marcar los tiempos 2 y 4 en el rock?', 'La caja.'], ['¿A qué familia pertenecen los platillos?', 'A los idiófonos: suena el propio metal.']],
      porque: 'Repartir el ritmo entre pies y manos permite a una persona sonar como varios percusionistas.' },
    { id: 'mu_trompeta', fam: 'ins', n: 'La trompeta y sus pistones',
      d: function (K) { var s = K.suelo(100, 132, 90) + K.l('M20 70 L60 70 Q66 70 66 64 L66 56 Q66 50 72 50 L140 50', P.oro, { w: 4 }) + K.l('M60 86 L150 86 Q160 86 160 76 L160 68', P.oro, { w: 4 }) + K.p('M140 40 L184 26 L184 74 L140 60 Z', P.oro, { w: 1 }) + K.r(14, 66, 8, 8, 2, P.metal, { w: .7 }); [84, 100, 116].forEach(function (x, i) { s += K.r(x - 4, 44, 8, 50, 2, P.metal, { w: .8 }) + K.c(x, 40, 5, P.blanco, { w: .8 }) + K.t(x, 42, String(i + 1), { s: 5, b: 1 }); }); return s + K.t(18, 60, 'boquilla', { s: 5.4, b: 1 }) + K.t(100, 30, 'pistones', { s: 5.8, b: 1 }) + K.t(170, 86, 'campana', { s: 5.6, b: 1 }) + K.t(100, 108, 'Los labios vibran en la boquilla', { s: 6, b: 1 }) + K.t(100, 120, 'Cada pistón añade un tramo de tubo: la nota baja', { s: 5.6 }); },
      intro: 'En la trompeta, la vibración de los labios suena dentro del tubo; los pistones cambian su longitud.',
      q: [['¿Qué vibra en un instrumento de metal?', 'Los labios del intérprete, en la boquilla.'], ['¿Qué pasa al bajar un pistón?', 'El aire recorre más tubo y la nota baja.'], ['¿Cómo se consiguen notas distintas sin pistones?', 'Cambiando la tensión de los labios y la presión del aire.']],
      porque: 'Con solo tres pistones y los labios se consiguen todas las notas del registro.' },
    { id: 'mu_laminas', fam: 'ins', n: 'Xilófono y metalófono',
      d: function (K) { var s = K.suelo(100, 136, 96), nom = ['do', 're', 'mi', 'fa', 'sol', 'la', 'si', 'do']; for (var i = 0; i < 8; i++) { var h = 56 - i * 4.4, x = 22 + i * 20; s += K.caja(x, 40 + (56 - h) / 2, 16, h, 3, i % 2 ? P.madera : P.naranja, { w: .8 }) + K.t(x + 8, 108, nom[i], { s: 6, b: 1 }); } return s + K.l('M18 50 L184 60 M18 90 L184 82', P.maderaO, { w: 1.6 }) + K.l('M60 18 L80 34', P.maderaO, { w: 1.2 }) + K.c(82, 36, 4, P.rojo, { w: .7 }) + K.t(100, 124, 'Lámina más corta = nota más aguda', { s: 6.4, b: 1 }) + K.t(100, 136, 'Xilófono: madera · metalófono: metal', { s: 5.6 }); },
      intro: 'Los instrumentos de láminas suenan al golpear barras afinadas: cuanto más corta, más aguda.',
      q: [['¿Qué lámina da la nota más grave?', 'La más larga, el do de la izquierda.'], ['¿A qué familia pertenecen?', 'A los idiófonos: vibra la propia lámina.'], ['¿Por qué se usan baquetas blandas o duras?', 'Para cambiar el timbre: las duras dan un sonido más brillante.']],
      porque: 'Es la misma regla de la cuerda y la flauta: lo que vibra más corto suena más agudo.' },
    G('mu_clasif', 'ins', 'Clasificación de los instrumentos', [['Idiófonos', 'vibra el propio cuerpo: maracas, xilófono'], ['Membranófonos', 'vibra una piel tensa: tambor, bongó'], ['Cordófonos', 'vibran cuerdas: guitarra, violín, arpa'], ['Aerófonos', 'vibra el aire: flauta, trompeta, quena'], ['Electrófonos', 'el sonido es eléctrico: sintetizador']], 1, 16, 19, 'Se clasifican por lo que vibra para producir el sonido', 'Los instrumentos se agrupan según el material que vibra al tocarlos.', [['¿A qué grupo pertenece el cajón peruano?', 'Al de los idiófonos: suena la madera de la caja.'], ['¿Y el bombo?', 'Al de los membranófonos.'], ['¿Por qué la guitarra eléctrica es un caso especial?', 'Sus cuerdas vibran, pero el sonido se amplifica por electricidad.']], 'Esta clasificación sirve para instrumentos de cualquier cultura, no solo de la orquesta.', { s: 7, s2: 5.4, gy: 4 }),
    G('mu_latinos', 'ins', 'Instrumentos de América Latina', [['Cuatro', 'Venezuela · 4 cuerdas'], ['Charango', 'Andes · 10 cuerdas'], ['Quena', 'Andes · flauta de caña'], ['Marimba', 'Guatemala y Colombia'], ['Cajón', 'Perú · se toca sentado'], ['Maracas', 'Caribe · semillas'], ['Bandoneón', 'Argentina · tango'], ['Güiro', 'Caribe · se raspa']], 2, 16, 23, 'Cada uno nació de la mezcla de culturas', 'Muchos instrumentos latinoamericanos mezclan tradiciones indígenas, africanas y europeas.', [['¿Qué instrumento acompaña el joropo venezolano?', 'El cuatro, junto al arpa y las maracas.'], ['¿A qué familia pertenece la quena?', 'A los aerófonos.'], ['¿De dónde llegó el bandoneón a Argentina?', 'De Alemania, con inmigrantes del siglo XIX.']], 'Los instrumentos cuentan la historia de los pueblos que los tocan.', { s: 7.4, s2: 5.4 }),
    G('mu_escolar', 'ins', 'Pequeña percusión del aula', [['Pandereta', 'piel + sonajas'], ['Triángulo', 'metal, suena largo'], ['Claves', 'dos palos de madera'], ['Caja china', 'madera hueca'], ['Cascabeles', 'metal, agitados'], ['Crótalos', 'platillos pequeños']], 3, 22, 32, 'Sonido largo: triángulo · sonido corto: claves', 'La pequeña percusión permite acompañar canciones con sonidos de distinto timbre y duración.', [['¿Qué instrumento suena más tiempo después del golpe?', 'El triángulo.'], ['¿Cuál combina membrana e idiófono?', 'La pandereta.'], ['¿Cómo se apaga el sonido del triángulo?', 'Tocándolo con la mano.']], 'Elegir un instrumento de sonido corto o largo cambia el carácter del acompañamiento.', { s: 8, s2: 5.6 }),
    { id: 'mu_acorde_gtr', fam: 'ins', n: 'Leer un diagrama de acorde',
      d: function (K) { var s = K.suelo(100, 140, 96), x0 = 30, y0 = 28, dx = 12, dy = 18; s += K.r(x0, y0 - 3, dx * 5, 3, 0, P.tinta, { negro: 1, w: .2 }); for (var c = 0; c < 6; c++) s += K.l('M' + (x0 + c * dx) + ' ' + y0 + ' L' + (x0 + c * dx) + ' ' + (y0 + dy * 4), P.tinta, { w: .6 }); for (var f = 1; f <= 4; f++) s += K.l('M' + x0 + ' ' + (y0 + f * dy) + ' L' + (x0 + dx * 5) + ' ' + (y0 + f * dy), P.grisO, { w: .6 }); [[1, 3, '3'], [2, 2, '2'], [4, 1, '1']].forEach(function (p) { s += K.c(x0 + p[0] * dx, y0 + p[1] * dy - dy / 2, 4.6, P.rojo, { w: .7 }) + K.t(x0 + p[0] * dx, y0 + p[1] * dy - dy / 2 + 2, p[2], { s: 5, b: 1 }); }); s += K.t(x0, y0 - 7, '×', { s: 7, b: 1 }) + K.t(x0 + dx * 3, y0 - 7, 'o', { s: 6, b: 1 }) + K.t(x0 + dx * 5, y0 - 7, 'o', { s: 6, b: 1 }); [0, 1, 2, 3, 4, 5].forEach(function (n, i) { s += K.t(x0 + i * dx, y0 + dy * 4 + 9, ['mi', 'la', 're', 'sol', 'si', 'mi'][i], { s: 4.6 }); }); return s + K.t(60, 120, 'Do mayor (C)', { s: 7, b: 1 }) + K.t(140, 34, 'Líneas verticales: cuerdas', { s: 5.6 }) + K.t(140, 46, 'Horizontales: trastes', { s: 5.6 }) + K.t(140, 58, 'Número: dedo que pisa', { s: 5.6 }) + K.t(140, 70, 'o: cuerda al aire', { s: 5.6 }) + K.t(140, 82, '×: no se toca', { s: 5.6 }) + K.t(140, 104, '1 índice · 2 medio · 3 anular', { s: 5.2, b: 1 }); },
      intro: 'El diagrama de acorde muestra el mástil de frente: dónde poner cada dedo y qué cuerdas sonar.',
      q: [['¿Qué cuerda no se toca en el do mayor?', 'La 6.ª, el mi grave.'], ['¿En qué traste pisa el dedo 3?', 'En el 3.º traste de la cuerda la.'], ['¿Qué notas suenan en este acorde?', 'Do, mi y sol, repetidas en varias cuerdas.']],
      porque: 'Con el diagrama se aprende un acorde sin saber leer partitura.' },
    { id: 'mu_afinar', fam: 'ins', n: 'Afinar con diapasón o afinador',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.l('M30 30 L30 80 M46 30 L46 80', P.metal, { w: 4 }) + K.p('M30 80 Q38 92 46 80', 'none', { w: 4 }) + K.l('M38 88 L38 118', P.metal, { w: 3 }); for (var j = 1; j <= 3; j++) s += K.l('M' + (52 + j * 6) + ' 44 q4 10 0 20', P.azulO, { w: .9 }); s += K.t(38, 132, 'diapasón: la 440 Hz', { s: 5.6, b: 1 }) + K.r(100, 30, 84, 70, 6, P.tinta, { w: 1 }) + K.r(106, 36, 72, 46, 3, '#1E3A2A', { w: .4 }); for (var i = -4; i <= 4; i++) { var a = i * .22, x = 142 + Math.sin(a) * 30, y = 80 - Math.cos(a) * 30; s += K.l('M' + x.toFixed(1) + ' ' + y.toFixed(1) + ' L' + (142 + Math.sin(a) * 26).toFixed(1) + ' ' + (80 - Math.cos(a) * 26).toFixed(1), i ? P.blanco : P.verde, { w: i ? .6 : 1.4 }); } s += K.l('M142 80 L150 54', P.rojo, { w: 1.2 }) + K.t(118, 46, 'A', { s: 9, b: 1, c: P.verde }) + K.t(142, 94, '♭ bajo   ·   ♯ alto', { s: 5, c: P.blanco }); return s + K.t(142, 112, 'aguja a la derecha:', { s: 5.4 }) + K.t(142, 120, 'demasiado agudo, aflojar', { s: 5.4, b: 1 }); },
      intro: 'Afinar es ajustar un instrumento para que sus notas coincidan con una referencia: normalmente el la de 440 Hz.',
      q: [['¿Qué nota da el diapasón habitual?', 'La, a 440 Hz.'], ['El afinador marca que la cuerda está alta. ¿Qué haces?', 'Aflojar un poco la clavija.'], ['¿Por qué hay que afinar antes de tocar en grupo?', 'Para que todos los instrumentos den las mismas notas.']],
      porque: 'Los cambios de temperatura y el uso desafinan las cuerdas: se afina cada vez que se toca.' },
    /* ─────────── HISTORIA, FORMAS Y ESTILOS ─────────── */
    { id: 'mu_periodos', fam: 'his', n: 'Los periodos de la música occidental',
      d: function (K) { var E = [['Edad Media', '500–1400', 'canto gregoriano', P.gris], ['Renacimiento', '1400–1600', 'polifonía', P.verde], ['Barroco', '1600–1750', 'Bach, Vivaldi', P.amarillo], ['Clasicismo', '1750–1820', 'Mozart, Haydn', P.azul], ['Romanticismo', '1820–1900', 'Chopin, Verdi', P.rosa], ['Siglo XX y XXI', '1900–hoy', 'jazz, cine, electrónica', P.morado]], s = K.suelo(100, 140, 96) + K.flecha(10, 76, 192, 76, P.tinta, { w: 1 }); E.forEach(function (q, i) { var x = 12 + i * 30, arr = i % 2 === 0; s += K.r(x, arr ? 30 : 84, 28, 38, 3, q[3], { w: .8 }) + K.t(x + 14, (arr ? 30 : 84) + 10, q[0], { s: Math.min(4.8, 26 / (q[0].length * .55)), b: 1 }) + K.t(x + 14, (arr ? 30 : 84) + 20, q[1], { s: 4.4 }) + K.t(x + 14, (arr ? 30 : 84) + 30, q[2], { s: Math.min(4, 26 / (q[2].length * .52)) }) + K.l('M' + (x + 14) + ' ' + (arr ? 68 : 84) + ' L' + (x + 14) + ' 76', P.grisO, { w: .6 }) + K.c(x + 14, 76, 1.8, P.tinta, { negro: 1, w: .3 }); }); return s + K.t(100, 136, 'Las fechas son aproximadas: los estilos se solapan', { s: 5.6 }); },
      intro: 'La historia de la música occidental se divide en periodos con rasgos y compositores propios.',
      q: [['¿En qué periodo vivió Mozart?', 'En el Clasicismo.'], ['¿Qué es la polifonía?', 'Varias melodías independientes que suenan a la vez.'], ['¿Qué periodo dura más tiempo?', 'La Edad Media.']],
      porque: 'Los periodos ayudan a situar una obra, pero la música de cada país también tiene su propia historia.' },
    G('mu_compositores', 'his', 'Compositores y una obra de cada uno', [['J. S. Bach', 'Conciertos de Brandeburgo'], ['A. Vivaldi', 'Las cuatro estaciones'], ['W. A. Mozart', 'La flauta mágica'], ['L. van Beethoven', 'Novena sinfonía'], ['F. Chopin', 'Nocturnos para piano'], ['H. Villa-Lobos', 'Bachianas brasileiras'], ['A. Piazzolla', 'Libertango'], ['A. Ginastera', 'Danzas argentinas']], 2, 16, 23, 'Europa y América Latina', 'Cada compositor dejó obras que todavía se escuchan en conciertos y en el cine.', [['¿Qué obra de Vivaldi describe el año?', 'Las cuatro estaciones.'], ['¿De qué país era Villa-Lobos?', 'De Brasil.'], ['¿Qué tenía de especial Beethoven al componer la Novena?', 'Estaba casi completamente sordo.']], 'Escuchar a compositores de distintas épocas y países amplía el oído.', { s: 7.2, s2: 5.2 }),
    G('mu_generos', 'his', 'Géneros de América Latina', [['Salsa', 'Caribe y Nueva York'], ['Cumbia', 'Colombia'], ['Tango', 'Argentina y Uruguay'], ['Joropo', 'Venezuela y Colombia'], ['Son', 'Cuba'], ['Merengue', 'República Dominicana'], ['Mariachi', 'México'], ['Bossa nova', 'Brasil']], 2, 16, 23, 'Muchos mezclan raíces indígenas, africanas y europeas', 'Cada país tiene géneros que nacen de su historia y se bailan de forma distinta.', [['¿De dónde es el tango?', 'Del Río de la Plata: Argentina y Uruguay.'], ['¿Qué instrumentos suelen acompañar el mariachi?', 'Violines, trompetas, guitarra, vihuela y guitarrón.'], ['¿Qué género nació de la mezcla de son cubano y jazz en Nueva York?', 'La salsa.']], 'Los géneros viajan y se mezclan: así nacen estilos nuevos.', { s: 7.4, s2: 5.4 }),
    { id: 'mu_formas', fam: 'his', n: 'Las formas musicales: AB, ABA, rondó',
      d: function (K) { var F = [['Binaria', 'AB', [['A', P.azul], ['B', P.verde]]], ['Ternaria', 'ABA', [['A', P.azul], ['B', P.verde], ['A', P.azul]]], ['Rondó', 'ABACA', [['A', P.azul], ['B', P.verde], ['A', P.azul], ['C', P.amarillo], ['A', P.azul]]]], s = K.suelo(100, 140, 96); F.forEach(function (q, i) { var y = 20 + i * 36; s += K.t(14, y + 12, q[0], { s: 6.4, b: 1, a: 'start' }); q[2].forEach(function (b, j) { s += K.caja(60 + j * 25, y, 22, 18, 4, b[1], { w: .8 }) + K.t(71 + j * 25, y + 12.5, b[0], { s: 7.4, b: 1 }); }); }); return s + K.t(100, 132, 'Las letras iguales son la misma música; las distintas, música nueva', { s: 5.4, b: 1 }); },
      intro: 'La forma es el plan de una obra: qué partes tiene y en qué orden se repiten.',
      q: [['¿Qué forma tiene una canción con estrofa y estribillo alternados?', 'Una forma de rondó: el estribillo (A) vuelve entre estrofas.'], ['¿Qué tienen en común la forma ternaria y el rondó?', 'Que la parte A vuelve al final.'], ['¿Por qué la repetición ayuda al oyente?', 'Le da algo conocido a lo que volver.']],
      porque: 'Repetir y contrastar es la base de casi toda la música, de una nana a una sinfonía.' },
    { id: 'mu_canon', fam: 'his', n: 'El canon',
      d: function (K) { var s = K.suelo(100, 140, 96), C = [P.azul, P.verde, P.amarillo]; for (var v = 0; v < 3; v++) { var y = 24 + v * 30; s += K.t(14, y + 12, 'voz ' + (v + 1), { s: 6, b: 1, a: 'start' }); for (var f = 0; f < 4 - v; f++) s += K.caja(48 + (v + f) * 34, y, 32, 18, 4, C[f % 3], { w: .8 }) + K.t(64 + (v + f) * 34, y + 12, 'frase ' + (f + 1), { s: 5.2, b: 1 }); } return s + K.t(100, 122, 'Todas cantan la misma melodía, entrando una tras otra', { s: 5.8, b: 1 }) + K.t(100, 134, 'Ejemplo conocido: «Frère Jacques» («Martinillo»)', { s: 5.4 }); },
      intro: 'En un canon, todas las voces cantan la misma melodía pero empiezan en momentos distintos.',
      q: [['¿Cuándo entra la voz 2?', 'Cuando la voz 1 empieza la frase 2.'], ['¿Por qué no suena desordenado?', 'Porque las frases están escritas para encajar al sonar juntas.'], ['¿Cuántas voces pueden cantar un canon?', 'Dos o más; muchos se cantan a 3 o 4.']],
      porque: 'Con una sola melodía, el canon crea armonía: es la forma más sencilla de polifonía.' },
    { id: 'mu_partitura', fam: 'his', n: 'Las partes de una partitura',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(14, 10, 172, 120, 2, P.blanco, { w: .9 }) + K.t(100, 22, 'Canción de cuna', { s: 7, b: 1 }) + K.t(180, 30, 'J. Brahms', { s: 5, a: 'end' }) + K.t(22, 34, 'Andante', { s: 5, b: 1, a: 'start' }) + penta(K, 22, 44, 156); s += K.l('M28 41 C24 42 24 37 27 37 L28 32 C31 34 31 38 25 45 C22 49 26 52 30 49', P.tinta, { w: .9 }) + K.t(40, 52, '3', { s: 7, b: 1 }) + K.t(40, 62, '4', { s: 7, b: 1 }); [60, 72, 84, 104, 116, 128, 148, 160].forEach(function (x, i) { var y = 64 - [2, 2, 4, 3, 2, 3, 4, 5][i] * 2.5; s += K.e(x, y, 3, 2.2, P.tinta, { negro: 1, w: .6 }) + K.l('M' + (x + 3) + ' ' + y + ' L' + (x + 3) + ' ' + (y - 13), P.tinta, { w: .7 }); }); s += K.l('M96 44 L96 64 M140 44 L140 64 M176 44 L176 64', P.tinta, { w: .7 }) + K.t(70, 80, 'A la ro - ro, ni - ño', { s: 5, a: 'start' }); var B = [[60, 18, '1'], [18, 31, '2'], [22, 48, '3'], [48, 46, '4'], [100, 42, '5'], [62, 78, '6']]; B.forEach(function (q) { s += K.c(q[0], q[1], 3.6, P.amarillo, { w: .5 }) + K.t(q[0], q[1] + 1.8, q[2], { s: 4.6, b: 1 }); }); return s + K.t(100, 102, '1 título · 2 tempo · 3 clave · 4 compás', { s: 5.6, b: 1 }) + K.t(100, 112, '5 barra de compás · 6 letra', { s: 5.6, b: 1 }) + K.t(100, 124, 'Arriba a la derecha va el autor', { s: 5 }); },
      intro: 'Una partitura reúne todo lo necesario para tocar una obra: título, autor, tempo, clave, compás, notas y letra.',
      q: [['¿Qué indica el 3/4 del principio?', 'Que cada compás tiene tres tiempos de negra.'], ['¿Dónde se escribe el tempo?', 'Arriba a la izquierda, sobre el primer pentagrama.'], ['¿Para qué sirve la barra de compás?', 'Para separar los compases y ayudar a contar.']],
      porque: 'Con la partitura, una persona puede tocar una obra sin haberla oído nunca.' },
    G('mu_estilos', 'his', 'Estilos de música popular', [['Blues', 'EE. UU. · años 1900'], ['Jazz', 'improvisación'], ['Rock', 'guitarra eléctrica · 1950'], ['Pop', 'canciones breves y pegadizas'], ['Hip hop', 'rap y ritmo'], ['Reguetón', 'Puerto Rico y Panamá'], ['Electrónica', 'sintetizadores'], ['Bolero', 'Cuba y México']], 2, 16, 23, 'Muchos estilos nacen de la música afroamericana', 'La música popular cambia con cada generación y con la tecnología de cada época.', [['¿Qué estilo se basa en la improvisación?', 'El jazz.'], ['¿Qué instrumento define al rock?', 'La guitarra eléctrica.'], ['¿Qué tienen en común blues, jazz y rock?', 'Sus raíces en la música afroamericana.']], 'Conocer de dónde viene un estilo ayuda a entender por qué suena así.', { s: 7.4, s2: 5.4 }),
    G('mu_opera', 'his', 'Las partes de una ópera', [['Obertura', 'la orquesta sola, al empezar'], ['Recitativo', 'canto casi hablado: avanza la historia'], ['Aria', 'canto lucido de un personaje'], ['Dúo y conjunto', 'varios personajes a la vez'], ['Coro', 'el pueblo o un grupo'], ['Libreto', 'el texto de la obra']], 2, 22, 28, 'Ópera = teatro + canto + orquesta', 'La ópera cuenta una historia cantada de principio a fin, con orquesta, escenario y vestuario.', [['¿Qué parte cuenta la acción rápidamente?', 'El recitativo.'], ['¿Qué es el libreto?', 'El texto que cantan los personajes.'], ['¿Qué parte suena antes de que se abra el telón?', 'La obertura.']], 'En la ópera la música expresa lo que sienten los personajes, no solo lo que dicen.', { s: 7.4, s2: 5.2 }),
    /* ─────────── TECNOLOGÍA MUSICAL ─────────── */
    { id: 'mu_cadena', fam: 'tec', n: 'Del micrófono al altavoz',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.c(24, 50, 9, P.metal, { w: .9 }) + K.r(21, 58, 6, 22, 2, P.tinta, { w: .5 }) + K.r(56, 44, 36, 26, 3, P.gris, { w: .9 }) + K.c(66, 57, 4, P.blanco, { w: .6 }) + K.c(80, 57, 4, P.blanco, { w: .6 }) + K.r(116, 40, 30, 34, 3, P.tinta, { w: .9 }) + K.c(131, 57, 10, P.grisO, { w: .6 }) + K.c(131, 57, 4, P.tinta, { w: .4 }) + K.l('M27 80 C40 90 44 66 56 60 M92 57 L116 57', P.tinta, { w: 1 }); for (var j = 1; j <= 3; j++) s += K.l('M' + (150 + j * 7) + ' 44 q5 13 0 26', P.azulO, { w: 1 }) + K.l('M' + (12 - j * 3) + ' 42 q-4 8 0 16', P.azulO, { w: .7 }); return s + K.t(24, 96, '1 micrófono', { s: 5.6, b: 1 }) + K.t(24, 104, 'sonido → señal eléctrica', { s: 4.6 }) + K.t(74, 86, '2 amplificador', { s: 5.6, b: 1 }) + K.t(74, 94, 'hace la señal más fuerte', { s: 4.6 }) + K.t(131, 86, '3 altavoz', { s: 5.6, b: 1 }) + K.t(131, 94, 'señal → vibración del cono', { s: 4.6 }) + K.t(100, 122, 'El sonido se convierte en electricidad y vuelve a ser sonido', { s: 5.6, b: 1 }) + K.t(100, 134, 'Acoplamiento (pitido): el micrófono capta su propio altavoz', { s: 5 }); },
      intro: 'El micrófono convierte el sonido en señal eléctrica, el amplificador la refuerza y el altavoz la vuelve sonido.',
      q: [['¿Qué parte del altavoz vibra?', 'El cono, movido por un imán y una bobina.'], ['¿Por qué se produce el pitido de acoplamiento?', 'Porque el micrófono recoge el sonido del altavoz y lo amplifica una y otra vez.'], ['¿Cómo se evita?', 'Colocando el micrófono detrás o lejos de los altavoces.']],
      porque: 'Micrófono y altavoz hacen lo mismo en sentidos opuestos: uno convierte vibración en electricidad y el otro al revés.' },
    { id: 'mu_mezcla', fam: 'tec', n: 'La mesa de mezclas',
      d: function (K) { var s = K.suelo(100, 136, 96) + K.p('M14 40 L186 40 L190 112 L10 112 Z', P.gris, { w: 1 }), C = ['voz', 'guitarra', 'bajo', 'batería', 'teclado'], V = [.8, .55, .45, .6, .35]; C.forEach(function (c, i) { var x = 30 + i * 30; s += K.c(x, 52, 4, P.tinta, { w: .5 }) + K.l('M' + x + ' 52 L' + (x + 2) + ' 49', P.blanco, { w: .7 }) + K.r(x - 1, 62, 2, 38, 1, P.tinta, { w: .3 }) + K.r(x - 6, 62 + (1 - V[i]) * 34, 12, 6, 1, P.metal, { w: .7 }) + K.t(x, 122, c, { s: 5.4, b: 1 }); }); return s + K.t(172, 50, 'panorámica', { s: 4.6 }) + K.t(100, 30, 'Un canal por instrumento', { s: 6.4, b: 1 }) + K.t(100, 134, 'Subir o bajar cada fader equilibra el conjunto', { s: 5.6 }); },
      intro: 'La mesa de mezclas recibe cada instrumento por un canal y permite ajustar su volumen y su posición.',
      q: [['¿Qué controla el fader?', 'El volumen de ese canal.'], ['¿Qué hace la perilla de panorámica?', 'Envía el sonido más a la izquierda o a la derecha.'], ['¿Por qué la voz suele estar más alta?', 'Para que se entienda la letra por encima de los instrumentos.']],
      porque: 'Una buena mezcla deja oír cada instrumento sin que ninguno tape a los demás.' },
    { id: 'mu_pistas', fam: 'tec', n: 'Grabar por pistas',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(10, 14, 180, 112, 3, P.tinta, { w: 1 }), T = [['voz', P.rosa, 60, 120], ['guitarra', P.verde, 40, 170], ['bajo', P.azul, 40, 170], ['batería', P.amarillo, 40, 170]]; T.forEach(function (q, i) { var y = 30 + i * 22; s += K.r(14, y, 32, 18, 2, P.grisO, { w: .4 }) + K.t(30, y + 11.5, q[0], { s: 5, b: 1, c: P.blanco }) + K.r(q[2] + 10, y + 2, q[3] - q[2], 14, 2, q[1], { w: .5 }); for (var k = 0; k < 18; k++) { var x = q[2] + 14 + k * ((q[3] - q[2] - 8) / 18), h = 2 + ((k * 7 + i * 3) % 9); s += K.l('M' + x.toFixed(1) + ' ' + (y + 9 - h / 2) + ' L' + x.toFixed(1) + ' ' + (y + 9 + h / 2), P.tinta, { w: .6 }); } }); s += K.l('M100 22 L100 120', P.rojo, { w: 1 }) + K.p('M96 18 L104 18 L100 24 Z', P.rojo, { w: .5 }); for (var b = 0; b < 8; b++) s += K.t(54 + b * 18, 22, String(b + 1), { s: 4.6, c: P.blanco }); return s + K.t(100, 138, 'Cada instrumento se graba en su pista y se corrige por separado', { s: 5.4, b: 1 }); },
      intro: 'En la grabación por pistas cada instrumento queda en una línea propia que se puede editar sin tocar las demás.',
      q: [['¿Qué ventaja tiene grabar por separado?', 'Se puede repetir solo la parte que salió mal.'], ['¿Qué indica la línea roja?', 'El punto de reproducción: lo que suena en ese momento.'], ['¿Qué significan los números de arriba?', 'Los compases.']],
      porque: 'Así se graban hoy casi todas las canciones, desde un estudio profesional hasta un teléfono.' },
    { id: 'mu_metronomo', fam: 'tec', n: 'El metrónomo',
      d: function (K) { var s = K.suelo(60, 128, 40) + K.p('M40 126 L52 20 L68 20 L80 126 Z', P.madera, { w: 1 }) + K.r(50, 40, 20, 70, 1, P.blanco, { w: .6 }); for (var i = 0; i < 8; i++) s += K.l('M52 ' + (44 + i * 8) + ' L58 ' + (44 + i * 8), P.tinta, { w: .5 }); s += K.l('M60 110 L72 34', P.metal, { w: 1.6 }) + K.r(65, 52, 10, 8, 1, P.oro, { w: .7 }) + K.l('M60 110 L48 34', P.grisO, { w: .5 }); return s + K.t(140, 40, '60 ppm = 1 pulso por segundo', { s: 5.6, b: 1 }) + K.t(140, 54, '120 ppm = 2 por segundo', { s: 5.6 }) + K.t(140, 74, 'Pesa abajo: más rápido', { s: 5.6, b: 1 }) + K.t(140, 84, 'pesa arriba: más lento', { s: 5.6 }) + K.t(140, 106, 'Para practicar, empezar lento', { s: 5.4 }) + K.t(140, 114, 'y subir el tempo poco a poco', { s: 5.4 }); },
      intro: 'El metrónomo marca un pulso regular a la velocidad elegida para practicar a tempo.',
      q: [['¿Cuántos golpes da en un minuto a 90 ppm?', '90.'], ['¿Qué pasa al subir la pesa del péndulo?', 'Oscila más despacio y el tempo baja.'], ['¿Para qué sirve practicar con metrónomo?', 'Para no correr ni frenar sin darse cuenta.']],
      porque: 'Un péndulo más largo tarda más en ir y volver: esa es la física del metrónomo mecánico.' },
    G('mu_derechos', 'tec', 'Los derechos de una canción', [['Autor de la letra', 'derecho de autor'], ['Compositor de la música', 'derecho de autor'], ['Intérprete', 'quien la canta o toca'], ['Productor de la grabación', 'quien pagó el máster'], ['Sociedad de gestión', 'cobra y reparte'], ['Plataformas y radios', 'pagan por usarla']], 2, 22, 28, 'Usar música ajena en un vídeo puede necesitar permiso', 'Cada vez que una canción suena en público o en internet, generan derechos quienes la crearon y grabaron.', [['¿Quién cobra cuando una canción suena en la radio?', 'Autores, intérpretes y productores, a través de sus sociedades de gestión.'], ['¿Se puede usar cualquier canción en un vídeo publicado?', 'No siempre: muchas necesitan licencia o permiso.'], ['¿Qué es la música libre de derechos?', 'Música con licencia que permite usarla en ciertas condiciones.']], 'Respetar los derechos permite que los músicos vivan de su trabajo.', { s: 6.8, s2: 5.4 })
  ];
  MO.agregar('musica', L, { nombre: 'Música', familias: FAM, materias: /^(musica)$/ });
})();
