/* b6_lib_contabilidad3.js — Contabilidad (3/3): caja, bancos y dinero; nómina e impuestos; gestión, control y ética. 33 modelos.
   Materia `conta`. Prefijo `ct_`. Cargar después de b6_lib_contabilidad2.js.
   Las tasas y porcentajes son de ejemplo: cada país tiene los suyos. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('ct_conciliacion')) return;
  var P = { papel: '#FBF7EE', azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', madera: '#B8946A', metal: '#C8CED4', billete: '#BFE0B0', oro: '#E8C04A' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { doc: 'Documentos comerciales', cue: 'Las cuentas', reg: 'El registro contable', est: 'Estados financieros', inv: 'Inventarios', cos: 'Costos y precios', ban: 'Caja, bancos y dinero', nom: 'Nómina e impuestos', ges: 'Gestión, control y ética' };
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + f1 * .35, q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + (o && o.tit ? K.t(100, 14, o.tit, { s: 7, b: 1 }) : '') + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  function tabla(K, x, y, ws, filas, o) {
    o = o || {}; var h = o.h || 10, fs = o.s || 5.2, s = '', W = 0; ws.forEach(function (w) { W += w; });
    filas.forEach(function (f, i) {
      var yy = y + i * h, cab = i === 0 && !o.sinCab, tot = String(f[0]).charAt(0) === '=', cx = x;
      s += K.r(x, yy, W, h, 0, cab ? (o.cab || P.azul) : tot ? P.amarillo : P.blanco, { w: .6 });
      ws.forEach(function (w, j) {
        var tx = String(f[j] == null ? '' : f[j]); if (j === 0 && tot) tx = tx.slice(1);
        var num = j > 0 && !cab && /^[−\-+$\d(]/.test(tx);
        s += K.t(num ? cx + w - 2 : cx + 2, yy + h / 2 + fs * .36, tx, { s: fs, b: cab || tot ? 1 : 0, a: num ? 'end' : 'start' });
        if (j > 0) s += K.l('M' + cx + ' ' + yy + ' L' + cx + ' ' + (yy + h), P.grisO, { w: .4 });
        cx += w;
      });
    });
    return s;
  }
  function formula(K, piezas, y, o) { o = o || {}; var k = o.k || 4.3, fs = o.s || 7, g = 3, n = piezas.length, fijo = n * 12 + g * (n - 1), tot = piezas.reduce(function (a, q) { return a + q[0].length * k; }, 0) + fijo; if (tot > 178) { var f = (178 - fijo) / (tot - fijo); k *= f; fs *= f; tot = 178; } var x = 100 - tot / 2, s = ''; piezas.forEach(function (q) { var w = q[0].length * k + 12; s += K.r(x, y, w, 18, 3, q[1], { w: .8 }) + K.t(x + w / 2, y + 12.5, q[0], { s: +fs.toFixed(2), b: 1 }); x += w + g; }); return s; }
  function caja(K, x, y, w, h, col, txt, fs) { return K.r(x, y, w, h, 3, col, { w: .9 }) + (txt ? K.t(x + w / 2, y + h / 2 + 2.3, txt, { s: fs || 6.2, b: 1 }) : ''); }
  function persona(K, x, y, col) { return K.c(x, y, 6, P.piel, { w: .8 }) + K.p('M' + (x - 9) + ' ' + (y + 26) + ' Q' + (x - 9) + ' ' + (y + 8) + ' ' + x + ' ' + (y + 8) + ' Q' + (x + 9) + ' ' + (y + 8) + ' ' + (x + 9) + ' ' + (y + 26) + ' Z', col, { w: .8 }); }
  function billete(K, x, y, v) { return K.r(x, y, 30, 15, 2, P.billete, { w: .7 }) + K.c(x + 15, y + 7.5, 4.4, P.blanco, { w: .5 }) + K.t(x + 15, y + 9.6, String(v), { s: 5.4, b: 1 }); }
  function moneda(K, x, y, r, v) { return K.c(x, y, r, P.oro, { w: .7 }) + K.t(x, y + r * .36, String(v), { s: r * .9, b: 1 }); }
  function barras(K, x0, base, w, g, vals, esc, cols, et) { var s = ''; vals.forEach(function (v, i) { var x = x0 + i * (w + g), h = v * esc; s += K.caja(x, base - h, w, h, 4, cols[i % cols.length], { w: .7 }) + (et ? K.t(x + w / 2, base - h - 3, et[i], { s: 5, b: 1 }) : ''); }); return s; }

  var L = [
    /* ─────────── CAJA, BANCOS Y DINERO ─────────── */
    { id: 'ct_conciliacion', fam: 'ban', n: 'La conciliación bancaria',
      d: function (K) { return K.suelo(100, 140, 96) + tabla(K, 6, 14, [62, 26], [['Según el banco', ''], ['Saldo del extracto', '4 380'], ['(−) Cheques sin cobrar', '(400)'], ['(+) Depósito en tránsito', '120'], ['=Saldo conciliado', '4 100']], { h: 13, s: 5.4, cab: P.azul }) + tabla(K, 106, 14, [62, 26], [['Según la empresa', ''], ['Saldo del libro', '4 150'], ['(−) Comisión del banco', '(50)'], ['', ''], ['=Saldo conciliado', '4 100']], { h: 13, s: 5.4, cab: P.verde }) + K.t(100, 92, '4 100 = 4 100', { s: 9, b: 1 }) + K.t(100, 108, 'Cada lado se corrige con lo que el otro ya sabe', { s: 6, b: 1 }) + K.t(100, 120, 'Solo la comisión se registra en el libro', { s: 5.6 }) + K.t(100, 132, '(los cheques y el depósito se arreglan solos)', { s: 5.2 }); },
      intro: 'La conciliación explica por qué el saldo del banco y el de la empresa no coinciden en una misma fecha.',
      q: [['¿Por qué el banco no descontó los 400?', 'Porque el beneficiario aún no ha cobrado esos cheques.'], ['¿Qué asiento hace la empresa?', 'Gastos bancarios al Debe 50; Bancos al Haber 50.'], ['¿Qué indica una diferencia que no se explica?', 'Un error o un movimiento no registrado que hay que investigar.']],
      porque: 'Cada mes se cruzan los dos registros: así aparecen los errores y los cobros que no se reconocen.' },
    { id: 'ct_caja_chica', fam: 'ban', n: 'La caja chica',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.caja(20, 36, 60, 46, 10, P.rojo, { w: 1 }) + K.r(42, 30, 16, 8, 2, P.metal, { w: .8 }) + K.t(50, 64, 'fondo fijo', { s: 6, b: 1 }) + K.t(50, 74, '200', { s: 8, b: 1 }); ['taxi 25', 'café 40', 'copias 30', 'cinta 50'].forEach(function (v, i) { s += K.r(98 + (i % 2) * 46, 26 + Math.floor(i / 2) * 26, 42, 22, 2, P.blanco, { w: .7 }) + K.t(119 + (i % 2) * 46, 35 + Math.floor(i / 2) * 26, 'VALE', { s: 4.6, b: 1 }) + K.t(119 + (i % 2) * 46, 43 + Math.floor(i / 2) * 26, v, { s: 5.2 }); }); return s + K.t(144, 90, 'vales: 145', { s: 6, b: 1 }) + K.t(50, 96, 'efectivo: 55', { s: 6, b: 1 }) + K.t(100, 114, '145 + 55 = 200 · se repone 145', { s: 6.6, b: 1 }) + K.t(100, 128, 'El gasto se registra al reponer, con los vales', { s: 5.6 }); },
      intro: 'La caja chica es un fondo pequeño y fijo para gastos menores, que se repone presentando los vales.',
      q: [['¿Cuánto hay que reponer?', '145, lo gastado según los vales.'], ['¿Qué debe sumar siempre vales + efectivo?', 'El fondo fijo: 200.'], ['¿Se puede pagar un sueldo con caja chica?', 'No: es solo para gastos menores y urgentes.']],
      porque: 'Con un fondo fijo, cualquier faltante se descubre al sumar vales y billetes.' },
    { id: 'ct_arqueo', fam: 'ban', n: 'El arqueo de caja',
      d: function (K) { var s = K.suelo(100, 140, 96) + billete(K, 8, 20, 20) + billete(K, 8, 40, 10) + billete(K, 8, 60, 5) + moneda(K, 22, 88, 7, 1); return s + tabla(K, 46, 18, [56, 22, 36], [['Denominación', 'Cant.', 'Total'], ['Billetes de 20', '5', '100,00'], ['Billetes de 10', '8', '80,00'], ['Billetes de 5', '6', '30,00'], ['Monedas', '', '7,50'], ['=Contado', '', '217,50'], ['Según sistema', '', '220,00'], ['=Faltante', '', '2,50']], { h: 11.5, s: 5.4 }) + K.t(100, 116, 'Se cuenta por sorpresa, delante del cajero', { s: 6, b: 1 }) + K.t(100, 128, 'y ambos firman el acta', { s: 5.6 }); },
      intro: 'El arqueo es contar el dinero de una caja y compararlo con lo que dicen los registros.',
      q: [['Comprueba el total contado.', '100 + 80 + 30 + 7,50 = 217,50.'], ['¿Qué diferencia hay?', 'Faltan 2,50.'], ['¿Por qué se hace sin avisar?', 'Para que nadie pueda tapar un faltante a última hora.']],
      porque: 'Contar por denominación facilita encontrar el error, por ejemplo un billete confundido.' },
    { id: 'ct_interes_simple', fam: 'ban', n: 'El interés simple',
      d: function (K) { return K.suelo(100, 140, 96) + K.l('M20 114 L186 114', P.tinta, { w: .9 }) + barras(K, 30, 114, 30, 14, [10, 11, 12, 13], 5.4, [P.azul], ['1 000', '1 100', '1 200', '1 300']) + K.t(45, 124, 'hoy', { s: 5.4 }) + K.t(89, 124, 'año 1', { s: 5.4 }) + K.t(133, 124, 'año 2', { s: 5.4 }) + K.t(177, 124, 'año 3', { s: 5.4 }) + formula(K, [['I', P.amarillo], ['=', P.blanco], ['C · i · t', P.verde], ['= 1 000 × 0,10 × 3 = 300', P.gris]], 4, { s: 6.4 }) + K.t(100, 136, 'Cada año gana lo mismo: 100', { s: 6, b: 1 }); },
      intro: 'En el interés simple, el interés se calcula siempre sobre el capital inicial.',
      q: [['¿Cuánto interés da 2 000 al 5 % durante 4 años?', '2 000 × 0,05 × 4 = 400.'], ['¿Cuánto se recibe en total?', '2 400.'], ['¿Por qué las barras suben lo mismo?', 'Porque el interés no se suma al capital para el año siguiente.']],
      porque: 'El interés simple crece en línea recta: es fácil de calcular y de comparar.' },
    { id: 'ct_interes_compuesto', fam: 'ban', n: 'El interés compuesto',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.l('M16 114 L188 114', P.tinta, { w: .9 }), S = [1000, 1100, 1200, 1300], C = [1000, 1100, 1210, 1331]; for (var i = 0; i < 4; i++) { var x = 24 + i * 42; s += K.caja(x, 114 - S[i] * .06, 14, S[i] * .06, 3, P.azul, { w: .6 }) + K.caja(x + 16, 114 - C[i] * .06, 14, C[i] * .06, 3, P.verde, { w: .6 }) + K.t(x + 23, 124, i ? 'año ' + i : 'hoy', { s: 5.2 }) + K.t(x + 23, 114 - C[i] * .06 - 3, String(C[i]).replace(/(\d)(\d{3})$/, '$1 $2'), { s: 4.8, b: 1, c: P.verdeO }); } return s + K.r(30, 14, 8, 8, 1, P.azul, { w: .5 }) + K.t(42, 20, 'simple', { s: 5.4, a: 'start' }) + K.r(80, 14, 8, 8, 1, P.verde, { w: .5 }) + K.t(92, 20, 'compuesto', { s: 5.4, a: 'start' }) + K.t(100, 134, 'Monto = C × (1 + i)ⁿ = 1 000 × 1,1³ = 1 331', { s: 5.8, b: 1 }); },
      intro: 'En el interés compuesto, cada año el interés se suma al capital y genera más interés.',
      q: [['¿Por qué el año 3 da 1 331 y no 1 300?', 'Porque el interés del año 2 y 3 se calcula sobre un capital mayor.'], ['¿Cuánto será al año 4?', '1 331 × 1,1 = 1 464,10.'], ['¿Conviene en un ahorro o en una deuda?', 'Juega a favor en el ahorro y en contra en una deuda.']],
      porque: 'Con el tiempo la diferencia se agranda: el interés compuesto crece cada vez más rápido.' },
    { id: 'ct_tarjeta', fam: 'ban', n: 'Pagar solo el mínimo de la tarjeta',
      d: function (K) { return K.suelo(100, 140, 96) + K.r(14, 22, 72, 44, 5, P.azul, { w: 1 }) + K.r(22, 32, 14, 10, 2, P.oro, { w: .6 }) + K.t(22, 56, '•••• 4821', { s: 6, b: 1, a: 'start' }) + K.t(50, 80, 'Deuda: 1 000', { s: 6.4, b: 1 }) + K.t(50, 90, 'interés: 3 % al mes', { s: 5.4 }) + tabla(K, 96, 22, [58, 34], [['Pago mínimo', '40'], ['− interés del mes', '30'], ['=Baja la deuda', '10']], { h: 14, s: 5.8, sinCab: 1 }) + K.t(144, 80, 'De 40 pagados,', { s: 5.6 }) + K.t(144, 88, 'solo 10 reducen la deuda', { s: 5.6, b: 1 }) + K.t(100, 116, 'Con pagos mínimos, la deuda tarda años en bajar', { s: 6, b: 1, c: P.rojoO }) + K.t(100, 128, '3 % al mes es más del 42 % al año', { s: 5.6 }); },
      intro: 'El pago mínimo de la tarjeta cubre sobre todo los intereses; la deuda casi no baja.',
      q: [['¿Cuánto interés se paga el primer mes?', '1 000 × 3 % = 30.'], ['¿Cuánto queda debiendo?', '1 000 − 10 = 990.'], ['¿Qué conviene hacer?', 'Pagar el total del mes o lo máximo posible.']],
      porque: 'El interés de la tarjeta es de los más altos: pagar poco es pagar mucho más al final.' },
    { id: 'ct_tasa_efectiva', fam: 'ban', n: 'Tasa nominal y tasa efectiva',
      d: function (K) { var s = K.suelo(100, 140, 96); for (var i = 0; i < 12; i++) s += K.c(20 + i * 14, 52, 5.5, P.verde, { w: .6 }) + K.t(20 + i * 14, 54, '1 %', { s: 3.6, b: 1 }) + (i < 11 ? K.flecha(25.5 + i * 14, 52, 28.5 + i * 14, 52, P.grisO, { w: .6, p: 2 }) : ''); return s + K.t(100, 24, 'Nominal: 12 % anual, con capitalización mensual', { s: 6.2, b: 1 }) + K.t(100, 36, '= 1 % cada mes, sobre el saldo que ya creció', { s: 5.6 }) + formula(K, [['(1 + 0,01)¹² − 1', P.gris], ['= 12,68 %', P.amarillo]], 74, { s: 7 }) + K.t(100, 110, 'La tasa efectiva es lo que realmente se paga o gana', { s: 6, b: 1 }) + K.t(100, 122, 'Para comparar préstamos, compara siempre la efectiva', { s: 5.6 }); },
      intro: 'La tasa nominal es la anunciada; la efectiva tiene en cuenta cada cuántas veces se capitaliza.',
      q: [['¿Por qué la efectiva es mayor que 12 %?', 'Porque cada mes el interés se suma y genera más interés.'], ['¿Cuándo coinciden nominal y efectiva?', 'Cuando se capitaliza una sola vez al año.'], ['¿Qué tasa aparece en la letra pequeña de un préstamo?', 'La tasa efectiva anual (o costo total), que es la que conviene comparar.']],
      porque: 'Dos préstamos con la misma tasa nominal pueden costar distinto si capitalizan con distinta frecuencia.' },
    { id: 'ct_ahorro', fam: 'ban', n: 'Ahorrar un poco cada mes',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.l('M16 116 L188 116', P.tinta, { w: .9 }); for (var i = 0; i < 12; i++) { var v = 50 * (Math.pow(1.01, i + 1) - 1) / .01; s += K.caja(20 + i * 14, 116 - v * .13, 10, v * .13, 3, i === 11 ? P.amarillo : P.verde, { w: .6 }); } return s + K.t(100, 16, '50 al mes durante 12 meses, al 1 % mensual', { s: 6.2, b: 1 }) + K.t(30, 34, 'aportado: 600', { s: 5.8, b: 1, a: 'start' }) + K.t(30, 44, 'con intereses: 634,13', { s: 5.8, b: 1, a: 'start', c: P.verdeO }) + K.t(100, 128, 'Valor futuro = cuota × ((1 + i)ⁿ − 1) / i', { s: 6, b: 1 }) + K.t(100, 138, '50 × (1,01¹² − 1) / 0,01 = 634,13', { s: 5.4 }); },
      intro: 'Pequeños depósitos regulares, sumados a sus intereses, forman un capital al final del plazo.',
      q: [['¿Cuánto interés ganó en el año?', '634,13 − 600 = 34,13.'], ['¿Qué pasa si se ahorra durante 24 meses?', 'El interés pesa más: unos 1 349 con 1 200 aportados.'], ['¿Qué importa más al principio, la tasa o la constancia?', 'La constancia: los aportes son la mayor parte.']],
      porque: 'Empezar pronto da más meses al interés compuesto para trabajar.' },
    { id: 'ct_inflacion', fam: 'ban', n: 'La inflación y el poder de compra',
      d: function (K) { var s = K.suelo(100, 140, 96) + billete(K, 14, 26, 100) + billete(K, 14, 72, 100); for (var i = 0; i < 10; i++) s += K.c(64 + i * 12, 34, 5, P.rojo, { w: .6 }); for (var j = 0; j < 9; j++) s += K.c(64 + j * 12, 80, 5, P.rojo, { w: .6 }); return s + K.c(172, 80, 5, P.gris, { w: .4 }) + K.t(29, 20, 'hoy', { s: 6, b: 1 }) + K.t(29, 66, 'en un año', { s: 6, b: 1 }) + K.t(124, 48, '10 manzanas', { s: 5.6, b: 1 }) + K.t(124, 94, '9 manzanas (y algo)', { s: 5.6, b: 1 }) + K.t(100, 114, 'Con 10 % de inflación: 100 / 1,10 = 90,91', { s: 6.2, b: 1 }) + K.t(100, 126, 'El billete es el mismo; compra menos', { s: 5.8 }); },
      intro: 'La inflación es la subida general de los precios: el mismo dinero compra menos cosas.',
      q: [['¿Cuánto vale hoy, en compras, 100 del año próximo con 10 % de inflación?', '100 / 1,10 = 90,91.'], ['Si el sueldo sube 5 % y la inflación es 10 %, ¿gana o pierde?', 'Pierde poder de compra.'], ['¿Qué tasa de ahorro protege del 10 % de inflación?', 'Una mayor del 10 % anual.']],
      porque: 'Por eso se distingue el interés nominal del real: el real descuenta la inflación.' },
    { id: 'ct_cambio', fam: 'ban', n: 'El tipo de cambio',
      d: function (K) { return K.suelo(100, 140, 96) + K.r(54, 18, 92, 40, 4, P.tinta, { w: 1 }) + K.t(100, 28, 'CASA DE CAMBIO · 1 USD', { s: 5.2, b: 1, c: P.amarillo }) + K.t(78, 42, 'COMPRA', { s: 5, c: P.blanco }) + K.t(78, 52, '18,00', { s: 7, b: 1, c: P.verde }) + K.t(122, 42, 'VENTA', { s: 5, c: P.blanco }) + K.t(122, 52, '18,50', { s: 7, b: 1, c: P.rojo }) + caja(K, 10, 70, 86, 42, P.verde) + K.t(53, 82, 'Vendo 500 USD', { s: 5.8, b: 1 }) + K.t(53, 92, 'la casa me compra a 18,00', { s: 4.8 }) + K.t(53, 104, '= 9 000 ML', { s: 7, b: 1 }) + caja(K, 104, 70, 86, 42, P.rojo) + K.t(147, 82, 'Compro 500 USD', { s: 5.8, b: 1 }) + K.t(147, 92, 'la casa me vende a 18,50', { s: 4.8 }) + K.t(147, 104, '= 9 250 ML', { s: 7, b: 1 }) + K.t(100, 128, 'La diferencia (250) es la ganancia de la casa de cambio', { s: 5.6, b: 1 }) + K.t(100, 138, 'ML = moneda local · cifras de ejemplo', { s: 5 }); },
      intro: 'El tipo de cambio es el precio de una moneda en otra; la casa de cambio compra más barato de lo que vende.',
      q: [['¿Cuántos USD da con 3 700 ML?', '3 700 / 18,50 = 200 USD.'], ['¿Por qué hay dos precios?', 'Porque la casa gana con la diferencia entre compra y venta.'], ['¿Cómo se registra una deuda en USD?', 'En moneda local al tipo de cambio del día, y se ajusta si el cambio varía.']],
      porque: 'Siempre se mira desde la casa de cambio: «compra» es lo que te paga, «venta» lo que te cobra.' },
    G('ct_medios_pago', 'ban', 'Medios de pago', [['Efectivo', 'inmediato · riesgo de robo'], ['Transferencia', 'de cuenta a cuenta'], ['Tarjeta de débito', 'descuenta de la cuenta'], ['Tarjeta de crédito', 'paga el banco; tú pagas después'], ['Billetera digital', 'pago con el teléfono'], ['Código QR', 'escanear y pagar'], ['Cheque', 'orden de pago al banco'], ['Pago contra entrega', 'se paga al recibir']], 2, 18, 22, 'El comercio paga comisión por casi todos los medios electrónicos', 'Cada medio de pago tiene su rapidez, su costo y su riesgo.', [['¿Qué medio no deja rastro bancario?', 'El efectivo.'], ['¿Quién paga la comisión de la tarjeta en una venta?', 'Normalmente el comercio, que recibe un poco menos.'], ['Venta de 100 con 3 % de comisión. ¿Cuánto recibe la tienda?', '97.']], 'La comisión es un gasto de venta: conviene incluirla al fijar precios.', { s: 6.6, s2: 5 }),
    { id: 'ct_plazo_fijo', fam: 'ban', n: 'El depósito a plazo',
      d: function (K) { return K.suelo(100, 140, 96) + K.caja(20, 40, 52, 56, 10, P.metal, { w: 1 }) + K.c(46, 68, 12, P.gris, { w: .9 }) + K.l('M46 68 L46 60 M46 68 L52 72', P.tinta, { w: 1 }) + K.t(46, 108, '5 000 bloqueados', { s: 5.6, b: 1 }) + K.t(46, 116, '180 días', { s: 5.4 }) + formula(K, [['5 000 × 0,06 × 180 / 360', P.gris], ['= 150', P.amarillo]], 26, { s: 6 }) + K.t(136, 64, 'Tasa: 6 % anual', { s: 6, b: 1 }) + K.t(136, 76, 'Al vencer recibe 5 150', { s: 6, b: 1 }) + K.t(136, 88, 'Si retira antes,', { s: 5.4 }) + K.t(136, 96, 'pierde parte del interés', { s: 5.4 }) + K.t(100, 130, 'Más plazo y más monto suelen dar mejor tasa', { s: 5.8, b: 1 }); },
      intro: 'En un depósito a plazo el dinero queda fijo un tiempo pactado a cambio de un interés conocido.',
      q: [['¿Cuánto interés da en 180 días?', '150.'], ['¿Y si fuera a 360 días con la misma tasa?', '300.'], ['¿Por qué paga más que una cuenta de ahorros?', 'Porque el banco sabe que puede usar ese dinero durante todo el plazo.']],
      porque: 'Renunciar a usar el dinero un tiempo es lo que el banco paga con el interés.' },
    /* ─────────── NÓMINA E IMPUESTOS ─────────── */
    { id: 'ct_rol', fam: 'nom', n: 'El rol de pagos',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 12, 'Laura Gómez · marzo 2026', { s: 6.2, b: 1 }) + tabla(K, 8, 16, [62, 28], [['Ingresos', ''], ['Sueldo base', '800,00'], ['Horas extra', '60,00'], ['=Total ingresos', '860,00']], { h: 13, s: 5.4, cab: P.verde }) + tabla(K, 104, 16, [62, 28], [['Descuentos', ''], ['Seguridad social 10 %', '86,00'], ['Anticipo', '100,00'], ['=Total descuentos', '186,00']], { h: 13, s: 5.4, cab: P.rojo }) + K.r(46, 78, 108, 22, 3, P.amarillo, { w: 1 }) + K.t(100, 92, 'Líquido a recibir: 674,00', { s: 7.4, b: 1 }) + K.t(100, 116, '860 − 186 = 674', { s: 6.4, b: 1 }) + K.t(100, 128, 'El porcentaje de aporte varía según el país', { s: 5.4 }); },
      intro: 'El rol (o recibo) de pagos detalla lo que gana cada trabajador, lo que se le descuenta y lo que recibe.',
      q: [['¿Sobre qué se calcula el aporte a la seguridad social?', 'Sobre el total de ingresos: 860 × 10 % = 86.'], ['¿Qué es el anticipo?', 'Dinero adelantado del mismo sueldo; se descuenta al pagar.'], ['¿Quién firma el rol?', 'El trabajador, como prueba de que recibió el pago.']],
      porque: 'El rol deja claro cada concepto: así el trabajador puede comprobar su pago.' },
    { id: 'ct_horas_extra', fam: 'nom', n: 'Calcular horas extra',
      d: function (K) { var s = K.suelo(100, 140, 96); for (var i = 0; i < 5; i++) { var x = 14 + i * 36; s += K.caja(x, 70, 28, 40, 5, P.azul, { w: .7 }) + K.caja(x, 70 - (i % 2 ? 16 : 8), 28, i % 2 ? 16 : 8, 5, P.naranja, { w: .7 }) + K.t(x + 14, 122, 'LMXJV'.charAt(i), { s: 6, b: 1 }); } return s + K.t(100, 14, 'Semana con 8 horas extra (naranja)', { s: 6.2, b: 1 }) + K.t(100, 28, 'Valor hora: 800 / 160 h = 5,00', { s: 5.8 }) + K.t(100, 38, 'Hora extra con recargo del 50 %: 7,50', { s: 5.8 }) + K.t(100, 48, '8 h × 7,50 = 60,00', { s: 6.6, b: 1 }) + K.t(100, 136, 'Las horas y el recargo los fija la ley de cada país', { s: 5.4 }); },
      intro: 'Las horas trabajadas fuera de la jornada se pagan con un recargo sobre el valor de la hora normal.',
      q: [['¿Cómo se obtiene el valor de la hora normal?', 'Sueldo mensual ÷ horas de la jornada mensual.'], ['¿Cuánto se paga por 12 horas extra?', '12 × 7,50 = 90.'], ['¿Qué pasa si el recargo es del 100 %?', 'La hora extra vale 10,00.']],
      porque: 'El recargo compensa el tiempo libre que el trabajador entrega.' },
    { id: 'ct_aportes', fam: 'nom', n: 'Quién aporta a la seguridad social',
      d: function (K) { return K.suelo(100, 140, 96) + persona(K, 36, 24, P.azul) + K.t(36, 62, 'Trabajador', { s: 6, b: 1 }) + K.t(36, 70, 'aporte personal', { s: 5 }) + K.t(36, 78, 'se descuenta del sueldo', { s: 4.8 }) + K.r(140, 22, 32, 34, 2, P.gris, { w: .8 }) + K.r(146, 28, 8, 8, 1, P.azul) + K.r(158, 28, 8, 8, 1, P.azul) + K.r(146, 40, 8, 8, 1, P.azul) + K.r(158, 40, 8, 8, 1, P.azul) + K.t(156, 66, 'Empleador', { s: 6, b: 1 }) + K.t(156, 74, 'aporte patronal', { s: 5 }) + K.t(156, 82, 'es un gasto de la empresa', { s: 4.8 }) + K.flecha(40, 86, 90, 108, P.azulO, { w: 1.4 }) + K.flecha(156, 88, 110, 108, P.verdeO, { w: 1.4 }) + K.r(66, 106, 68, 22, 4, P.amarillo, { w: 1 }) + K.t(100, 116, 'Instituto de', { s: 5.6, b: 1 }) + K.t(100, 124, 'seguridad social', { s: 5.6, b: 1 }) + K.t(100, 140, 'Paga salud, pensión y riesgos de trabajo', { s: 5.4 }); },
      intro: 'A la seguridad social aportan el trabajador (de su sueldo) y el empleador (además del sueldo).',
      q: [['¿Quién entrega los dos aportes al instituto?', 'El empleador: retiene el personal y suma el patronal.'], ['¿Es el aporte patronal un descuento al trabajador?', 'No: es un costo adicional de la empresa.'], ['¿Qué cubre la seguridad social?', 'Atención de salud, jubilación y accidentes de trabajo, entre otros.']],
      porque: 'Por eso el costo de un trabajador para la empresa es mayor que su sueldo.' },
    G('ct_provisiones', 'nom', 'Provisiones laborales', [['Vacaciones', 'días pagados de descanso'], ['Aguinaldo o sueldo extra', 'pago adicional anual'], ['Bonos por ley', 'según cada país'], ['Indemnización', 'por fin de contrato'], ['Fondo de reserva o cesantía', 'ahorro obligatorio'], ['Participación de utilidades', 'donde la ley la exige']], 2, 22, 24, 'Se reserva 1/12 cada mes para no pagar todo de golpe', 'Las provisiones laborales son gastos del mes que se pagarán más adelante.', [['¿Por qué se provisiona cada mes?', 'Porque el trabajador lo gana mes a mes, aunque se pague después.'], ['Un sueldo extra anual de 800: ¿provisión mensual?', '800 / 12 = 66,67.'], ['¿En qué grupo va la provisión?', 'Es un pasivo: una deuda con el trabajador.']], 'Provisionar evita que un mes cargue con el gasto de todo el año.', { s: 6.6, s2: 5.2 }),
    { id: 'ct_iva_mes', fam: 'nom', n: 'La declaración mensual del impuesto al consumo',
      d: function (K) { return K.suelo(100, 140, 96) + caja(K, 10, 22, 80, 46, P.verde) + K.t(50, 36, 'Cobrado en ventas', { s: 5.8, b: 1 }) + K.t(50, 46, '(débito fiscal)', { s: 5 }) + K.t(50, 60, '1 500', { s: 9, b: 1 }) + K.t(100, 48, '−', { s: 12, b: 1 }) + caja(K, 110, 22, 80, 46, P.azul) + K.t(150, 36, 'Pagado en compras', { s: 5.8, b: 1 }) + K.t(150, 46, '(crédito fiscal)', { s: 5 }) + K.t(150, 60, '900', { s: 9, b: 1 }) + K.r(50, 78, 100, 22, 3, P.amarillo, { w: 1 }) + K.t(100, 92, 'A pagar este mes: 600', { s: 7, b: 1 }) + K.t(100, 114, 'Si las compras superan a las ventas,', { s: 5.8 }) + K.t(100, 124, 'queda un saldo a favor para el mes siguiente', { s: 5.8, b: 1 }); },
      intro: 'Cada mes se resta el impuesto pagado en las compras del impuesto cobrado en las ventas.',
      q: [['¿Cuánto se paga si se cobró 2 000 y se pagó 2 300?', 'Nada: queda un saldo a favor de 300.'], ['¿El impuesto cobrado es un ingreso de la empresa?', 'No: es dinero del fisco que la empresa solo recauda.'], ['¿Qué documento respalda el crédito fiscal?', 'Las facturas de compra válidas.']],
      porque: 'Cada empresa paga solo el impuesto sobre el valor que añade; el resto ya lo pagaron otros.' },
    { id: 'ct_retencion', fam: 'nom', n: 'La retención en la fuente',
      d: function (K) { return K.suelo(100, 140, 96) + persona(K, 30, 30, P.verde) + K.t(30, 70, 'cliente', { s: 6, b: 1 }) + persona(K, 170, 30, P.azul) + K.t(170, 70, 'proveedor', { s: 6, b: 1 }) + K.r(80, 96, 40, 30, 3, P.amarillo, { w: 1 }) + K.t(100, 108, 'fisco', { s: 6.4, b: 1 }) + K.t(100, 118, 'recibe 20', { s: 5.4 }) + K.flecha(44, 42, 156, 42, P.verdeO, { w: 1.6 }) + K.t(100, 36, 'paga 980', { s: 6.4, b: 1, c: P.verdeO }) + K.flecha(40, 64, 82, 98, P.rojoO, { w: 1.4 }) + K.t(48, 92, 'retiene 2 %: 20', { s: 5.6, b: 1, c: P.rojoO }) + K.t(100, 14, 'Factura de servicios por 1 000', { s: 6.4, b: 1 }) + K.t(150, 92, 'El proveedor resta los 20', { s: 5.2 }) + K.t(150, 100, 'de su impuesto anual', { s: 5.2 }); },
      intro: 'En la retención, quien paga descuenta una parte del impuesto del proveedor y la entrega directamente al fisco.',
      q: [['¿Cuánto recibe el proveedor?', '1 000 − 20 = 980.'], ['¿Pierde el proveedor esos 20?', 'No: es un anticipo de su impuesto, que descuenta después.'], ['¿Qué documento entrega el cliente?', 'Un comprobante de retención.']],
      porque: 'La retención asegura que el impuesto se cobre poco a poco, en el momento del pago.' },
    { id: 'ct_renta_tramos', fam: 'nom', n: 'Impuesto progresivo por tramos',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 12, 'Ingreso anual: 26 000 (tabla de ejemplo)', { s: 6, b: 1 }) + K.caja(14, 34, 64, 30, 5, P.verde, { w: .8 }) + K.t(46, 46, '0 – 10 000', { s: 5.6, b: 1 }) + K.t(46, 56, '0 % → 0', { s: 5.6 }) + K.caja(80, 34, 64, 30, 5, P.amarillo, { w: .8 }) + K.t(112, 46, '10 000 – 20 000', { s: 5.6, b: 1 }) + K.t(112, 56, '10 % → 1 000', { s: 5.6 }) + K.caja(146, 34, 40, 30, 5, P.rojo, { w: .8 }) + K.t(166, 46, '20 000 – 26 000', { s: 4.6, b: 1 }) + K.t(166, 56, '20 % → 1 200', { s: 5 }) + K.t(100, 86, 'Impuesto total: 0 + 1 000 + 1 200 = 2 200', { s: 6.6, b: 1 }) + K.t(100, 100, 'Tasa efectiva: 2 200 / 26 000 = 8,5 %', { s: 6, b: 1 }) + K.t(100, 120, 'Cada tasa se aplica solo a su tramo,', { s: 5.8 }) + K.t(100, 130, 'no a todo el ingreso', { s: 5.8, b: 1 }); },
      intro: 'En un impuesto progresivo, cada parte del ingreso paga la tasa de su tramo.',
      q: [['¿Es cierto que paga el 20 % de todo su ingreso?', 'No: solo los 6 000 del último tramo pagan 20 %.'], ['¿Cuánto paga con 15 000?', '0 + 500 = 500.'], ['¿Puede un aumento de sueldo hacer que gane menos?', 'No: solo el dinero extra paga la tasa más alta.']],
      porque: 'Entender los tramos evita un miedo común: subir de tramo nunca reduce el ingreso neto.' },
    { id: 'ct_calendario', fam: 'nom', n: 'El calendario tributario',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(20, 14, 160, 14, 2, P.azul, { w: .8 }) + K.t(100, 24, 'MES DE ABRIL', { s: 6.6, b: 1 }); 'LMXJVSD'.split('').forEach(function (d, i) { s += K.t(31 + i * 23, 37, d, { s: 5.4, b: 1 }); }); for (var n = 1; n <= 30; n++) { var c = (n + 1) % 7, f = Math.floor((n + 1) / 7), x = 20 + c * 23, y = 40 + f * 18, mk = n === 10 ? P.rojo : n === 15 ? P.amarillo : n === 28 ? P.verde : P.blanco; s += K.r(x, y, 22, 17, 1, mk, { w: .4 }) + K.t(x + 3, y + 7, String(n), { s: 4.8, a: 'start' }); } return s + K.t(54, 140, '10: impuesto al consumo', { s: 5, b: 1, c: P.rojoO }) + K.t(110, 140, '15: retenciones', { s: 5, b: 1 }) + K.t(160, 140, '28: seguridad social', { s: 5, b: 1, c: P.verdeO }); },
      intro: 'El calendario tributario marca las fechas límite de cada declaración y pago.',
      q: [['¿Qué pasa si se paga después de la fecha?', 'Se cobran multas e intereses.'], ['¿De qué suele depender el día de vencimiento?', 'Del último dígito del número de identificación tributaria, según el país.'], ['¿Por qué conviene preparar la declaración antes?', 'Para revisar errores sin la presión del último día.']],
      porque: 'Las fechas cambian según el país y el contribuyente: siempre se consulta el calendario oficial.' },
    G('ct_deducible', 'nom', '¿Gasto deducible o no?', [['Sueldos con aportes', 'deducible', P.verde], ['Alquiler del local', 'deducible', P.verde], ['Luz y agua del negocio', 'deducible', P.verde], ['Gastos sin factura', 'no deducible', P.rojo], ['Multas e intereses tributarios', 'no deducible', P.rojo], ['Gastos personales del dueño', 'no deducible', P.rojo]], 2, 22, 24, 'Deducible = necesario para el negocio y con comprobante válido', 'Un gasto deducible reduce la base sobre la que se calcula el impuesto a la renta.', [['¿Por qué un gasto sin factura no se acepta?', 'Porque no se puede probar ni que existió ni su importe.'], ['Ingresos 20 000, gastos deducibles 12 000. ¿Base imponible?', '8 000.'], ['¿Es deducible la cena familiar del dueño?', 'No: es un gasto personal, no del negocio.']], 'Las reglas exactas las fija la ley de cada país; el principio común es: necesario y comprobado.', { s: 6.4, s2: 5.6 }),
    { id: 'ct_bruto_neto', fam: 'nom', n: 'Sueldo bruto, neto y costo total',
      d: function (K) { return K.suelo(100, 140, 96) + K.caja(22, 30, 156, 18, 5, P.morado, { w: .8 }) + K.t(100, 42, 'costo para la empresa: 1 000', { s: 6, b: 1 }) + K.caja(22, 58, 128, 18, 5, P.azul, { w: .8 }) + K.t(86, 70, 'sueldo bruto: 820', { s: 6, b: 1 }) + K.t(164, 70, '+180 aportes', { s: 4.8 }) + K.caja(22, 86, 104, 18, 5, P.verde, { w: .8 }) + K.t(74, 98, 'sueldo neto: 670', { s: 6, b: 1 }) + K.t(150, 98, '−150 descuentos', { s: 4.8 }) + K.t(100, 122, 'Bruto: lo pactado · Neto: lo que llega a la cuenta', { s: 5.8, b: 1 }) + K.t(100, 134, 'Costo total: bruto + aportes y provisiones', { s: 5.6 }); },
      intro: 'El mismo empleo tiene tres cifras: lo que cuesta a la empresa, el sueldo bruto y el neto que se cobra.',
      q: [['¿Qué cifra aparece en el contrato?', 'Normalmente el sueldo bruto.'], ['¿Cuánto se descuenta al trabajador?', '820 − 670 = 150.'], ['¿Qué cifra usa la empresa para su presupuesto?', 'El costo total: 1 000.']],
      porque: 'Comparar ofertas de trabajo por el neto, y presupuestar personal por el costo total, evita sorpresas.' },
    G('ct_liquidacion', 'nom', 'La liquidación al terminar un contrato', [['Días trabajados', 'del último mes'], ['Vacaciones no gozadas', 'proporcionales'], ['Sueldos extra proporcionales', 'lo ganado del año'], ['Indemnización', 'si la ley la exige'], ['(−) Deudas o anticipos', 'pendientes con la empresa'], ['=Total a pagar', 'firma de ambas partes', P.amarillo]], 2, 22, 24, 'Cada país define plazos y montos mínimos', 'Al terminar la relación laboral se pagan todos los valores que el trabajador ganó y aún no cobró.', [['¿Por qué se pagan vacaciones no gozadas?', 'Porque el trabajador ya las ganó con su tiempo.'], ['Sueldo extra anual de 800 y trabajó 9 meses: ¿proporcional?', '800 × 9 / 12 = 600.'], ['¿Por qué se firma?', 'Para dejar constancia de que se pagó lo acordado.']], 'Las provisiones mensuales existen para que este pago no tome a la empresa por sorpresa.', { s: 6.4, s2: 5.2 }),
    /* ─────────── GESTIÓN, CONTROL Y ÉTICA ─────────── */
    G('ct_principios', 'ges', 'Principios básicos de la contabilidad', [['Entidad', 'la empresa no es el dueño'], ['Empresa en marcha', 'se supone que seguirá'], ['Devengo', 'cuando ocurre, no cuando se cobra'], ['Prudencia', 'no inflar activos ni ganancias'], ['Uniformidad', 'mismos criterios cada año'], ['Importancia relativa', 'detallar lo que importa'], ['Medición en dinero', 'todo en una moneda'], ['Periodo', 'informar por años o meses']], 2, 18, 22, 'Las bases que comparten las normas contables', 'Los principios contables son las reglas generales que hacen comparables y fiables los registros.', [['¿Qué principio se rompe si el dueño paga su casa con la caja de la empresa?', 'El de entidad.'], ['¿Por qué no se cambia de método de inventario cada año?', 'Por uniformidad: se perdería la comparación.'], ['¿Qué hace la prudencia ante una pérdida probable?', 'La reconoce; una ganancia probable, en cambio, se espera a que ocurra.']], 'Con reglas comunes, dos contadores llegan a cifras parecidas con los mismos documentos.', { s: 6.6, s2: 5.2 }),
    G('ct_normas', 'ges', 'Las normas contables', [['NIIF completas', 'grandes empresas y bolsa'], ['NIIF para PYMES', 'empresas medianas y pequeñas'], ['Normas locales', 'microempresas y casos especiales'], ['Normas tributarias', 'para calcular impuestos']], 2, 26, 34, 'Cada país decide qué norma aplica a cada empresa', 'Las Normas Internacionales de Información Financiera (NIIF) se usan en gran parte del mundo; muchos países tienen además normas propias.', [['¿Para qué sirven normas internacionales?', 'Para que un inversionista de otro país entienda los estados.'], ['¿Qué norma suele usar una pequeña empresa?', 'La NIIF para PYMES u otra norma simplificada local.'], ['¿Son iguales la utilidad contable y la tributaria?', 'No siempre: la ley tributaria tiene sus propias reglas.']], 'Llevar la contabilidad con norma y declarar con ley tributaria obliga a conciliar las dos cifras.', { s: 7, s2: 5.4 }),
    { id: 'ct_control', fam: 'ges', n: 'Separar funciones',
      d: function (K) { var V = [[100, 26, 'AUTORIZA', 'aprueba la compra', P.amarillo], [40, 104, 'CUSTODIA', 'guarda dinero y bienes', P.azul], [160, 104, 'REGISTRA', 'anota en contabilidad', P.verde]]; var s = K.suelo(100, 140, 96) + K.pl([[100, 34], [44, 100], [156, 100]], P.blanco, { w: .8 }); V.forEach(function (q) { s += K.c(q[0], q[1], 18, q[4], { w: .9 }) + K.t(q[0], q[1] + 2, q[2], { s: 5.4, b: 1 }) + K.t(q[0], q[1] + (q[1] < 50 ? -22 : 28), q[3], { s: 5.4 }); }); return s + K.t(100, 78, 'tres personas', { s: 6, b: 1 }) + K.t(100, 86, 'distintas', { s: 6, b: 1 }); },
      intro: 'El control interno pide que autorizar, custodiar y registrar estén en manos de personas diferentes.',
      q: [['¿Qué riesgo hay si el cajero también registra la caja?', 'Podría sacar dinero y ocultarlo en los registros.'], ['¿Qué hacer en una empresa muy pequeña?', 'Que el dueño revise y firme las conciliaciones y los pagos.'], ['¿Es desconfiar de las personas?', 'No: protege también al empleado de sospechas.']],
      porque: 'Para cometer un fraude harían falta dos o tres personas de acuerdo, y eso es mucho menos probable.' },
    { id: 'ct_auditoria', fam: 'ges', n: 'La auditoría',
      d: function (K) { var s = K.suelo(100, 140, 96); for (var i = 0; i < 6; i++) s += K.r(20 + i * 10, 34 + i * 6, 52, 62, 2, P.blanco, { w: .7 }); s += K.l('M74 76 L108 76 M74 84 L104 84 M74 92 L100 92', P.grisO, { w: .5 }); return s + K.c(136, 66, 22, P.azul, { w: 1.4, op: .5 }) + K.c(136, 66, 22, 'none', { w: 2.4 }) + K.l('M152 82 L176 108', P.madera, { w: 6 }) + K.t(136, 64, '✓', { s: 14, b: 1, c: P.verdeO }) + K.t(100, 18, 'Revisión independiente de los registros', { s: 6.4, b: 1 }) + K.t(100, 128, 'Se revisa una muestra y se opina si los estados son fiables', { s: 5.6, b: 1 }); },
      intro: 'El auditor revisa los registros y documentos para opinar si los estados financieros son razonables.',
      q: [['¿Por qué el auditor revisa una muestra y no todo?', 'Porque revisar cada documento sería muy lento y costoso.'], ['¿Qué diferencia hay entre auditoría interna y externa?', 'La interna la hace personal de la empresa; la externa, profesionales independientes.'], ['¿Qué entrega el auditor al final?', 'Un informe con su opinión.']],
      porque: 'Una mirada independiente da confianza a quienes no pueden revisar los libros por sí mismos.' },
    G('ct_etica', 'ges', 'La ética del contador', [['Integridad', 'ser honesto en todo'], ['Objetividad', 'sin favorecer intereses'], ['Competencia', 'saber y actualizarse'], ['Confidencialidad', 'no divulgar datos del cliente'], ['Comportamiento profesional', 'cumplir la ley siempre']], 1, 18, 18, 'Firmar un estado falso es responsabilidad del contador', 'Los códigos de ética profesional resumen los deberes de quien lleva las cuentas de otros.', [['Un cliente pide ocultar ventas para pagar menos impuesto. ¿Qué hace el contador?', 'Negarse y explicar que es evasión, un delito.'], ['¿Puede contar a un amigo cuánto gana un cliente?', 'No: rompería la confidencialidad.'], ['¿Por qué debe actualizarse?', 'Porque las normas y leyes cambian.']], 'La contabilidad solo sirve si se puede confiar en quien la hace.', { s: 7, s2: 5.4, gy: 4 }),
    { id: 'ct_area', fam: 'ges', n: 'El área de contabilidad',
      d: function (K) { var s = K.suelo(100, 140, 96) + caja(K, 66, 14, 68, 22, P.amarillo, 'Contador general', 6) + K.l('M100 36 L100 50 M30 50 L170 50', P.grisO, { w: .9 }); [['Auxiliar contable', 'registra', P.azul], ['Tesorería', 'cobra y paga', P.verde], ['Nómina', 'sueldos y aportes', P.rosa], ['Costos', 'calcula costos', P.naranja]].forEach(function (q, i) { var x = 8 + i * 47; s += K.l('M' + (x + 22) + ' 50 L' + (x + 22) + ' 62', P.grisO, { w: .9 }) + K.r(x, 62, 44, 34, 3, q[2], { w: .8 }) + K.t(x + 22, 76, q[0], { s: Math.min(5.4, 40 / (q[0].length * .55)), b: 1 }) + K.t(x + 22, 86, q[1], { s: 4.8 }); }); return s + K.t(100, 116, 'En una pyme, una sola persona puede hacer varias tareas', { s: 5.6, b: 1 }) + K.t(100, 128, 'pero conviene separar cobrar y registrar', { s: 5.6 }); },
      intro: 'En una empresa mediana, el área contable reparte las tareas entre varias personas.',
      q: [['¿Quién firma los estados financieros?', 'El contador general, junto con el representante legal.'], ['¿Qué hace tesorería?', 'Maneja cobros, pagos y cuentas bancarias.'], ['¿Por qué separar tesorería y registro?', 'Por control interno: quien maneja dinero no lo registra.']],
      porque: 'Dividir el trabajo acelera el cierre de mes y mejora el control.' },
    { id: 'ct_software', fam: 'ges', n: 'Del libro de papel al programa contable',
      d: function (K) { return K.suelo(100, 140, 96) + K.p('M14 40 L54 34 L94 40 L94 104 L54 98 L14 104 Z', P.blanco, { w: .9 }) + K.l('M54 34 L54 98', P.grisO, { w: .8 }) + K.l('M20 52 L50 50 M20 60 L50 58 M20 68 L50 66 M58 50 L88 52 M58 58 L88 60 M58 66 L88 68', P.grisO, { w: .5 }) + K.t(54, 118, 'a mano: sumar y pasar', { s: 5.6, b: 1 }) + K.r(108, 34, 80, 54, 3, P.tinta, { w: 1 }) + K.r(112, 38, 72, 46, 1, P.azul, { w: .5 }) + K.r(116, 42, 64, 7, 1, P.blanco, { w: .3 }) + K.r(116, 52, 30, 28, 1, P.verde, { w: .3 }) + K.r(150, 52, 30, 28, 1, P.amarillo, { w: .3 }) + K.p('M136 88 L160 88 L166 96 L130 96 Z', P.metal, { w: .8 }) + K.t(148, 118, 'el programa pasa y suma solo', { s: 5.6, b: 1 }) + K.t(100, 136, 'El programa calcula; el criterio sigue siendo del contador', { s: 5.6 }); },
      intro: 'El programa contable hace los pases al mayor, las sumas y los informes automáticamente.',
      q: [['¿Qué errores elimina el programa?', 'Los de suma y los de pasar mal un importe al mayor.'], ['¿Qué errores no elimina?', 'Elegir la cuenta equivocada o registrar un documento falso.'], ['¿Por qué hacer copias de seguridad?', 'Para no perder la información si falla el equipo.']],
      porque: 'Automatizar quita trabajo mecánico, no la responsabilidad de decidir qué registrar.' },
    { id: 'ct_factura_e', fam: 'ges', n: 'El recorrido de la factura electrónica',
      d: function (K) { return K.suelo(100, 140, 96) + K.r(10, 50, 44, 34, 3, P.azul, { w: .9 }) + K.t(32, 64, 'empresa', { s: 6, b: 1 }) + K.t(32, 74, 'emite', { s: 5 }) + K.r(78, 18, 44, 34, 3, P.amarillo, { w: .9 }) + K.t(100, 32, 'autoridad', { s: 5.8, b: 1 }) + K.t(100, 42, 'tributaria valida', { s: 4.6 }) + K.r(146, 50, 44, 34, 3, P.verde, { w: .9 }) + K.t(168, 64, 'cliente', { s: 6, b: 1 }) + K.t(168, 74, 'recibe', { s: 5 }) + K.flecha(54, 56, 78, 42, P.tinta, { w: 1.2 }) + K.t(56, 44, '1 envía', { s: 5 }) + K.flecha(122, 42, 146, 56, P.tinta, { w: 1.2 }) + K.t(146, 44, '2 autoriza', { s: 5 }) + K.flecha(54, 76, 146, 76, P.grisO, { w: 1 }) + K.t(100, 90, '3 correo o portal con el archivo y su código', { s: 5 }) + K.r(76, 98, 48, 24, 2, P.blanco, { w: .7 }) + K.t(100, 108, 'XML + firma', { s: 5.4, b: 1 }) + K.t(100, 117, 'clave única', { s: 4.8 }) + K.t(100, 136, 'Sin autorización, la factura no es válida', { s: 5.8, b: 1 }); },
      intro: 'La factura electrónica viaja como archivo firmado y la autoridad tributaria la valida antes de que sea válida.',
      q: [['¿Qué gana el fisco con este sistema?', 'Conoce cada venta al instante y reduce la evasión.'], ['¿Y la empresa?', 'Ahorra papel y archiva sin ocupar espacio.'], ['¿Qué pasa si la autoridad la rechaza?', 'Se corrige y se vuelve a enviar; mientras, no vale como comprobante.']],
      porque: 'El código único permite a cualquiera comprobar que una factura existe y no fue alterada.' },
    { id: 'ct_separar', fam: 'ges', n: 'Separar el dinero del negocio y el personal',
      d: function (K) { return K.suelo(100, 140, 96) + K.r(12, 34, 76, 54, 6, P.azul, { w: 1 }) + K.r(64, 50, 24, 20, 4, P.metal, { w: .7 }) + K.t(42, 50, 'NEGOCIO', { s: 6.4, b: 1 }) + K.t(42, 62, 'ventas, compras,', { s: 4.8 }) + K.t(42, 70, 'sueldos', { s: 4.8 }) + K.r(112, 34, 76, 54, 6, P.rosa, { w: 1 }) + K.r(164, 50, 24, 20, 4, P.metal, { w: .7 }) + K.t(142, 50, 'PERSONAL', { s: 6.4, b: 1 }) + K.t(142, 62, 'casa, comida,', { s: 4.8 }) + K.t(142, 70, 'ocio', { s: 4.8 }) + K.flecha(90, 104, 112, 104, P.verdeO, { w: 1.6 }) + K.t(100, 98, 'un sueldo fijo al dueño', { s: 5.2, b: 1 }) + K.t(100, 124, 'Dos cuentas bancarias distintas', { s: 6.4, b: 1 }) + K.t(100, 136, 'Si se mezclan, nadie sabe si el negocio gana', { s: 5.6 }); },
      intro: 'El dinero del negocio y el del dueño se manejan en cuentas separadas, aunque el dueño sea una sola persona.',
      q: [['¿Cómo recibe dinero el dueño sin mezclar?', 'Con un sueldo o un retiro registrado.'], ['¿Qué principio contable se aplica?', 'El de entidad.'], ['¿Qué problema da pagar el mercado de casa con la caja del negocio?', 'Los gastos del negocio parecen mayores y la utilidad real se pierde.']],
      porque: 'Separar el dinero es la primera condición para saber si un negocio realmente funciona.' },
    { id: 'ct_fraude', fam: 'ges', n: 'El triángulo del fraude',
      d: function (K) { var V = [[100, 26, 'PRESIÓN', 'deudas, metas imposibles', P.rojo], [36, 108, 'OPORTUNIDAD', 'controles débiles', P.amarillo], [164, 108, 'JUSTIFICACIÓN', '«lo devolveré»', P.morado]]; var s = K.suelo(100, 140, 96) + K.pl([[100, 34], [42, 102], [158, 102]], P.blanco, { w: 1.2 }); V.forEach(function (q) { s += K.c(q[0], q[1], 17, q[4], { w: .9 }) + K.t(q[0], q[1] + 2, q[2], { s: Math.min(5.2, 30 / (q[2].length * .55)), b: 1 }) + K.t(q[0], q[1] + (q[1] < 50 ? -21 : 27), q[3], { s: 5.2 }); }); return s + K.t(100, 80, 'La empresa solo controla', { s: 5.4 }) + K.t(100, 88, 'la oportunidad', { s: 6, b: 1 }); },
      intro: 'El fraude suele aparecer cuando coinciden presión, oportunidad y una justificación.',
      q: [['¿Cuál de los tres puede reducir la empresa?', 'La oportunidad, con buenos controles.'], ['Da un ejemplo de oportunidad.', 'Una sola persona que cobra, registra y concilia la caja.'], ['¿Qué señales de alerta hay?', 'Faltantes repetidos, documentos perdidos o alguien que nunca toma vacaciones.']],
      porque: 'Quitar la oportunidad es más eficaz que confiar en que no haya presión ni excusas.' }
  ];
  MO.agregar('conta', L, { nombre: 'Contabilidad', familias: FAM, materias: /^(conta)$/ });
})();
