/* b6_lib_efisica.js — Educación física (1/2): calentamiento, capacidades físicas, salud, entrenamiento. 25 modelos.
   Materia `efisica`. Prefijo `ef_`. Cargar después de b6_modelos.js.
   No repite anat_* (sistemas, edades, palanca, postura, pulso), pulso, palanca, plato, fis_mru ni geo_cancha/geo_canon. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('ef_calentar')) return;
  var P = { azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', cesped: '#9CCB7A', pista: '#D9866A', agua: '#9CCBE6' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { cal: 'Calentamiento y estiramiento', cap: 'Capacidades físicas', sal: 'Salud y hábitos', ent: 'Entrenamiento', atl: 'Atletismo', gim: 'Gimnasia y expresión', dep: 'Deportes colectivos', jue: 'Juegos y recreación', seg: 'Seguridad y primeros auxilios' };
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + f1 * .35, q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  function caja(K, x, y, w, h, col, txt, fs) { return K.r(x, y, w, h, 3, col, { w: .9 }) + (txt ? K.t(x + w / 2, y + h / 2 + 2.3, txt, { s: fs || 6.2, b: 1 }) : ''); }
  /* figura articulada: ángulos en grados desde la vertical hacia abajo (0 = colgando); positivo hacia la derecha */
  function fig(K, x, y, o) {
    o = o || {}; var e = o.e || 1, col = o.col || P.azul, rad = Math.PI / 180, tor = (o.tronco || 0) * rad, L1 = 13 * e, L2 = 12 * e, T = 18 * e;
    var hx = x + Math.sin(tor) * T, hy = y - Math.cos(tor) * T, s = '';
    function seg(x0, y0, a1, a2, l1, l2, c) { var x1 = x0 + Math.sin(a1 * rad) * l1, y1 = y0 + Math.cos(a1 * rad) * l1, x2 = x1 + Math.sin(a2 * rad) * l2, y2 = y1 + Math.cos(a2 * rad) * l2; return K.l('M' + x0.toFixed(1) + ' ' + y0.toFixed(1) + ' L' + x1.toFixed(1) + ' ' + y1.toFixed(1) + ' L' + x2.toFixed(1) + ' ' + y2.toFixed(1), c, { w: 3.4 * e }); }
    var b = o.b || [20, 20, -20, -20], p = o.p || [8, 8, -8, -8];
    s += seg(x, y, p[0], p[1], L1, L2, K.oscuro(col, .35)) + seg(x, y, p[2], p[3], L1, L2, K.oscuro(col, .35));
    s += K.l('M' + x + ' ' + y + ' L' + hx.toFixed(1) + ' ' + hy.toFixed(1), col, { w: 5 * e });
    var sx = x + Math.sin(tor) * T * .85, sy = y - Math.cos(tor) * T * .85;
    s += seg(sx, sy, b[0], b[1], 10 * e, 9 * e, col) + seg(sx, sy, b[2], b[3], 10 * e, 9 * e, col);
    return s + K.c(hx + Math.sin(tor) * 5 * e, hy - Math.cos(tor) * 5 * e, 4.6 * e, P.piel, { w: .7 });
  }
  function ejes(K, x, y, w, h, ex, ey) { return K.flecha(x, y + h, x + w, y + h, P.tinta, { w: 1 }) + K.flecha(x, y + h, x, y, P.tinta, { w: 1 }) + K.t(x + w, y + h + 9, ex, { s: 5.4, a: 'end' }) + K.t(x + 4, y + 3, ey, { s: 5.4, a: 'start' }); }
  function linea(K, pts, col, w) { return K.l('M' + pts.map(function (p) { return p[0].toFixed(1) + ' ' + p[1].toFixed(1); }).join(' L'), col, { w: w || 1.6 }); }

  var L = [
    /* ─────────── CALENTAMIENTO Y ESTIRAMIENTO ─────────── */
    { id: 'ef_calentar', fam: 'cal', n: 'Las fases del calentamiento',
      d: function (K) { var s = K.suelo(100, 140, 96); [['1 Activar', 'trote suave 5 min', { b: [30, 60, -30, -60], p: [30, 10, -20, -40] }, P.verde], ['2 Movilidad', 'círculos de brazos y cadera', { b: [150, 170, -150, -170] }, P.amarillo], ['3 Estirar', 'estiramientos breves', { tronco: 30, b: [10, 0, 40, 30], p: [20, 0, -12, -12] }, P.azul], ['4 Específico', 'gestos del deporte', { b: [-40, -100, 60, 120], p: [40, -10, -30, -50] }, P.naranja]].forEach(function (q, i) { var x = 26 + i * 50; s += K.r(x - 22, 20, 44, 92, 4, q[3], { w: .7, op: .6 }) + fig(K, x, 70, q[2]) + K.t(x, 98, q[0], { s: 5.8, b: 1 }) + K.t(x, 106, q[1], { s: Math.min(4.6, 40 / (q[1].length * .52)) }); }); return s + K.t(100, 128, 'De lo suave a lo intenso · unos 10–15 minutos', { s: 6, b: 1 }); },
      intro: 'El calentamiento prepara el cuerpo poco a poco: sube el pulso, moviliza articulaciones y repite los gestos del deporte.',
      q: [['¿Por qué empezar con un trote suave?', 'Para subir la temperatura del cuerpo y el pulso sin esfuerzo brusco.'], ['¿Cuánto debe durar?', 'Entre 10 y 15 minutos, según la actividad.'], ['¿Qué es el calentamiento específico?', 'Repetir de forma suave los movimientos del deporte que se va a practicar.']],
      porque: 'Un músculo caliente es más elástico: se lesiona menos y rinde más.' },
    { id: 'ef_estira_pierna', fam: 'cal', n: 'Estirar las piernas',
      d: function (K) { var s = K.suelo(100, 140, 96); [['isquiotibiales', 'sentado, alcanzar el pie', { tronco: 60, b: [100, 100, 110, 100], p: [90, 90, 85, 85] }, 40, 92], ['cuádriceps', 'talón al glúteo', { b: [30, 30, 150, 170], p: [0, 0, -20, -170] }, 100, 80], ['gemelos', 'apoyo en pared', { tronco: 25, b: [130, 140, 125, 140], p: [-15, -15, 20, 20] }, 160, 80]].forEach(function (q) { s += fig(K, q[3], q[4], q[2]) + K.t(q[3], 112, q[0], { s: 6, b: 1 }) + K.t(q[3], 120, q[1], { s: 4.8 }); }); s += K.r(180, 40, 6, 70, 0, P.gris, { w: .7 }); return s + K.t(100, 136, 'Mantener 20–30 s sin rebotes ni dolor', { s: 6, b: 1 }); },
      intro: 'Los estiramientos devuelven a los músculos su longitud después del esfuerzo y mejoran la flexibilidad.',
      q: [['¿Cuánto tiempo se mantiene cada estiramiento?', 'Entre 20 y 30 segundos.'], ['¿Por qué no hay que dar rebotes?', 'Porque el músculo se contrae para protegerse y puede lesionarse.'], ['¿Qué se debe sentir?', 'Tensión suave, nunca dolor.']],
      porque: 'Estirar despacio y respirando relaja el músculo; forzarlo produce el efecto contrario.' },
    { id: 'ef_estira_tronco', fam: 'cal', n: 'Estirar brazos, hombros y espalda',
      d: function (K) { var s = K.suelo(100, 140, 96); [['hombro', 'brazo cruzado', { b: [-80, -80, -60, -100] }], ['tríceps', 'codo detrás de la cabeza', { b: [170, 20, 160, -160] }], ['espalda', 'manos arriba, estirarse', { b: [175, 180, -175, -180] }], ['costado', 'inclinarse al lado', { tronco: -20, b: [160, 175, -20, -10] }]].forEach(function (q, i) { var x = 28 + i * 48; s += fig(K, x, 80, q[2]) + K.t(x, 112, q[0], { s: 6, b: 1 }) + K.t(x, 120, q[1], { s: Math.min(4.8, 44 / (q[1].length * .52)) }); }); return s + K.t(100, 136, 'Hacer los dos lados por igual', { s: 6, b: 1 }); },
      intro: 'El tren superior también se estira: hombros, brazos, espalda y costados.',
      q: [['¿Por qué estirar los dos lados?', 'Para mantener el cuerpo equilibrado.'], ['¿Qué estiramiento ayuda tras muchas horas sentado?', 'El de espalda, estirándose hacia arriba.'], ['¿Se debe aguantar la respiración?', 'No: se respira lento y profundo.']],
      porque: 'La postura sentada acorta pecho y hombros; estirarlos ayuda a mantener la espalda recta.' },
    { id: 'ef_vuelta_calma', fam: 'cal', n: 'La vuelta a la calma',
      d: function (K) { var s = K.suelo(100, 140, 96) + ejes(K, 22, 14, 166, 94, 'minutos', 'pulso'), y = function (v) { return 108 - (v - 60) * .68; }; s += K.r(23, y(190), 30, y(70) - y(190), 0, P.verde, { w: .2, op: .4 }) + K.r(53, y(190), 90, y(70) - y(190), 0, P.rojo, { w: .2, op: .4 }) + K.r(143, y(190), 44, y(70) - y(190), 0, P.azul, { w: .2, op: .4 }); s += linea(K, [[24, y(75)], [52, y(115)], [70, y(160)], [140, y(165)], [160, y(120)], [186, y(85)]], P.rojoO, 1.8); return s + K.t(38, 24, 'calentar', { s: 5.4, b: 1 }) + K.t(98, 24, 'parte principal', { s: 5.4, b: 1 }) + K.t(165, 24, 'vuelta a la calma', { s: 5.2, b: 1 }) + K.t(100, 134, 'Bajar poco a poco: caminar, estirar, respirar', { s: 5.8, b: 1 }); },
      intro: 'Tras el esfuerzo, la vuelta a la calma baja el pulso poco a poco antes de terminar la sesión.',
      q: [['¿Por qué no parar en seco después de correr?', 'Porque la sangre se acumula en las piernas y puede dar mareo.'], ['¿Qué se hace en la vuelta a la calma?', 'Caminar, estirar y respirar despacio.'], ['¿Cuánto dura?', 'Unos 5 a 10 minutos.']],
      porque: 'El corazón necesita tiempo para volver a su ritmo de reposo.' },
    /* ─────────── CAPACIDADES FÍSICAS ─────────── */
    G('ef_capacidades', 'cap', 'Las capacidades físicas básicas', [['Resistencia', 'aguantar un esfuerzo largo'], ['Fuerza', 'vencer una resistencia'], ['Velocidad', 'moverse en el menor tiempo'], ['Flexibilidad', 'amplitud de movimiento']], 2, 24, 40, 'Se mejoran con entrenamiento a cualquier edad', 'Las capacidades físicas básicas son las cualidades que permiten moverse y hacer ejercicio.', [['¿Qué capacidad se usa más en una maratón?', 'La resistencia.'], ['¿Y en un salto de longitud?', 'La velocidad y la fuerza.'], ['¿Qué capacidad se pierde antes si no se trabaja?', 'La flexibilidad.']], 'Todos los deportes combinan las cuatro, en proporciones distintas.', { s: 9, s2: 5.8 }),
    G('ef_coordinativas', 'cap', 'Capacidades coordinativas', [['Equilibrio', 'mantener la postura'], ['Coordinación', 'movimientos combinados'], ['Agilidad', 'cambiar de dirección rápido'], ['Ritmo', 'moverse a un compás'], ['Orientación', 'saber dónde se está'], ['Reacción', 'responder a una señal']], 2, 22, 28, 'Se aprenden mejor en la infancia', 'Las capacidades coordinativas dependen del sistema nervioso: cómo se controla el movimiento.', [['¿Qué capacidad trabaja la cuerda de saltar?', 'Coordinación y ritmo.'], ['¿Y caminar por una línea con los ojos cerrados?', 'El equilibrio.'], ['¿Qué capacidad usa un portero ante un penalti?', 'La reacción.']], 'Practicar juegos variados en la infancia deja un repertorio de movimiento para toda la vida.', { s: 8, s2: 5.6 }),
    { id: 'ef_aerobico', fam: 'cap', n: 'Resistencia aeróbica y anaeróbica',
      d: function (K) { var s = K.suelo(100, 140, 96) + caja(K, 10, 18, 86, 92, P.azul) + fig(K, 54, 62, { b: [30, 70, -30, -70], p: [25, 5, -15, -35], col: P.verde }) + K.t(53, 84, 'AERÓBICA', { s: 7, b: 1 }) + K.t(53, 94, 'larga y moderada', { s: 5.2 }) + K.t(53, 102, 'usa oxígeno', { s: 5.2 }) + caja(K, 104, 18, 86, 92, P.rojo) + fig(K, 148, 62, { tronco: 20, b: [-50, -100, 70, 120], p: [55, -20, -40, -60], col: P.naranja }) + K.t(147, 84, 'ANAERÓBICA', { s: 7, b: 1 }) + K.t(147, 94, 'corta e intensa', { s: 5.2 }) + K.t(147, 102, 'sin oxígeno suficiente', { s: 5.2 }); return s + K.t(53, 122, 'trote 30 min, natación suave', { s: 5, b: 1 }) + K.t(147, 122, 'sprint 100 m, subir escaleras', { s: 5, b: 1 }) + K.t(100, 136, 'El esfuerzo intenso fatiga antes: aparece el ácido láctico', { s: 5.2 }); },
      intro: 'La resistencia aeróbica sostiene esfuerzos largos con oxígeno; la anaeróbica, esfuerzos cortos y muy intensos.',
      q: [['¿Qué tipo de resistencia usa un partido de fútbol?', 'Las dos: la aeróbica en todo el partido y la anaeróbica en los sprints.'], ['¿Por qué no se puede esprintar diez minutos?', 'Porque el esfuerzo anaeróbico solo dura segundos.'], ['¿Cuál mejora más la salud del corazón?', 'La aeróbica.']],
      porque: 'Si se puede hablar mientras se corre, el esfuerzo es aeróbico.' },
    { id: 'ef_fuerza', fam: 'cap', n: 'Ejercicios de fuerza con el propio cuerpo',
      d: function (K) { var s = K.suelo(100, 140, 96); [['sentadilla', { tronco: 15, b: [-90, -90, -80, -80], p: [-90, 0, -70, 0] }, 30, 84], ['plancha', { tronco: 80, b: [0, 0, 5, 5], p: [-95, -95, -90, -90] }, 100, 92], ['flexión', { tronco: 75, b: [10, 0, 15, 0], p: [-100, -100, -95, -95] }, 164, 92]].forEach(function (q) { s += fig(K, q[2], q[3], q[1]) + K.t(q[2], 112, q[0], { s: 6.2, b: 1 }); }); return s + K.t(30, 120, 'piernas', { s: 5 }) + K.t(100, 120, 'abdomen', { s: 5 }) + K.t(164, 120, 'brazos y pecho', { s: 5 }) + K.t(100, 136, '3 series de 10 repeticiones, espalda recta', { s: 5.8, b: 1 }); },
      intro: 'La fuerza se puede entrenar sin aparatos, usando el peso del propio cuerpo.',
      q: [['¿Qué músculos trabaja la sentadilla?', 'Sobre todo cuádriceps y glúteos.'], ['¿Por qué la espalda debe estar recta?', 'Para no cargar la zona lumbar.'], ['¿Qué es una serie?', 'Un grupo de repeticiones seguidas, con descanso entre grupos.']],
      porque: 'Con buena técnica, el propio cuerpo es suficiente para fortalecer los músculos principales.' },
    { id: 'ef_flexibilidad', fam: 'cap', n: 'Medir la flexibilidad: test de sentarse y alcanzar',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.caja(110, 80, 50, 26, 8, P.madera || '#C89A62', { w: .9 }) + K.r(100, 76, 80, 4, 1, P.amarillo, { w: .7 }); for (var i = 0; i <= 16; i++) s += K.l('M' + (100 + i * 5) + ' 76 L' + (100 + i * 5) + ' ' + (i % 2 ? 78 : 80), P.tinta, { w: .4 }); s += fig(K, 60, 104, { tronco: 65, b: [95, 95, 100, 95], p: [90, 90, 88, 88] }) + K.t(118, 70, '0', { s: 5.4, b: 1 }) + K.t(138, 70, '+10', { s: 5.4, b: 1 }) + K.t(100, 70, '−5', { s: 5.4, b: 1 }); return s + K.t(100, 22, 'Piernas estiradas, se empuja la regla despacio', { s: 5.8, b: 1 }) + K.t(100, 32, 'Se anota la mejor de dos marcas, en cm', { s: 5.4 }) + K.t(100, 126, 'El 0 está a la altura de los pies', { s: 5.8, b: 1 }) + K.t(100, 136, 'Comparar con uno mismo, no con los demás', { s: 5.2 }); },
      intro: 'El test de sentarse y alcanzar mide la flexibilidad de la espalda y la parte de atrás de las piernas.',
      q: [['¿Qué significa una marca negativa?', 'Que no se llega a los pies.'], ['¿Por qué no se deben doblar las rodillas?', 'Porque el test mide el estiramiento con las piernas rectas.'], ['¿Cómo mejorar la marca?', 'Estirando a diario unos minutos.']],
      porque: 'Repetir el test cada trimestre muestra el progreso de cada estudiante.' },
    { id: 'ef_velocidad', fam: 'cap', n: 'Los tipos de velocidad',
      d: function (K) { var s = K.suelo(100, 140, 96); [['de reacción', 'salir al oír la señal', { tronco: 45, b: [60, 60, -10, -10], p: [-40, 0, 40, 60] }], ['gestual', 'un golpe o lanzamiento rápido', { b: [-150, -170, 40, 30] }], ['de desplazamiento', 'recorrer una distancia', { tronco: 15, b: [-50, -100, 70, 120], p: [55, -20, -40, -60] }]].forEach(function (q, i) { var x = 36 + i * 64; s += fig(K, x, 80, q[2]) + K.t(x, 108, q[0], { s: 6, b: 1 }) + K.t(x, 116, q[1], { s: Math.min(4.8, 58 / (q[1].length * .52)) }); }); s += K.l('M18 40 q4 -6 8 0 M14 36 q8 -12 16 0', P.grisO, { w: .7 }); return s + K.t(100, 136, 'Se entrena con esfuerzos cortos y descansos completos', { s: 5.6, b: 1 }); },
      intro: 'La velocidad no es solo correr rápido: también reaccionar rápido y hacer un gesto rápido.',
      q: [['¿Qué velocidad necesita un corredor en la salida?', 'La de reacción.'], ['¿Y un tenista al golpear?', 'La gestual.'], ['¿Por qué se descansa mucho entre sprints?', 'Para hacer cada uno al máximo, no cansado.']],
      porque: 'Entrenar velocidad cansado se convierte en entrenar resistencia.' },
    /* ─────────── SALUD Y HÁBITOS ─────────── */
    { id: 'ef_oms', fam: 'sal', n: 'Cuánta actividad física al día',
      d: function (K) { var s = K.suelo(100, 140, 96), cx = 60, cy = 70, r = 40; s += K.c(cx, cy, r, P.gris, { w: .9 }); var a = 2 * Math.PI * 60 / 1440, x = cx + Math.sin(a) * r, y = cy - Math.cos(a) * r; s += K.p('M' + cx + ' ' + cy + ' L' + cx + ' ' + (cy - r) + ' A' + r + ' ' + r + ' 0 0 1 ' + x.toFixed(1) + ' ' + y.toFixed(1) + ' Z', P.verde, { w: .9 }); return s + K.t(cx, cy + 3, '24 h', { s: 8, b: 1 }) + K.t(76, 22, '60 min', { s: 6, b: 1, c: P.verdeO }) + K.t(146, 36, 'Niños y adolescentes:', { s: 6, b: 1 }) + K.t(146, 46, 'al menos 60 minutos', { s: 6, b: 1 }) + K.t(146, 56, 'al día, moderados a intensos', { s: 5.4 }) + K.t(146, 74, '3 días por semana:', { s: 5.6, b: 1 }) + K.t(146, 84, 'fortalecer músculos y huesos', { s: 5.4 }) + K.t(146, 102, 'Menos tiempo sentado', { s: 5.6, b: 1 }) + K.t(146, 112, 'y frente a pantallas', { s: 5.4 }) + K.t(100, 132, 'Recomendación de la Organización Mundial de la Salud', { s: 5.2 }); },
      intro: 'La Organización Mundial de la Salud recomienda al menos una hora diaria de actividad física para niños y adolescentes.',
      q: [['¿Cuenta ir caminando al colegio?', 'Sí: suma minutos de actividad moderada.'], ['¿Cuánta actividad se recomienda a los adultos?', 'Al menos 150 minutos semanales de actividad moderada.'], ['¿Qué es una actividad intensa?', 'Una en la que cuesta hablar: correr, nadar rápido, saltar.']],
      porque: 'El cuerpo humano está hecho para moverse: la inactividad es un riesgo para la salud.' },
    { id: 'ef_fc_zonas', fam: 'sal', n: 'Las zonas de frecuencia cardiaca',
      d: function (K) { var Z = [['reposo', 60, 100, P.gris], ['ligera 50–60 %', 103, 124, P.azul], ['aeróbica 60–80 %', 124, 165, P.verde], ['intensa 80–90 %', 165, 186, P.naranja], ['máxima 90–100 %', 186, 206, P.rojo]], s = K.suelo(100, 140, 96); Z.forEach(function (q, i) { var y = 18 + i * 20; s += K.r(70, y, (q[2] - 60) * .74, 16, 3, q[3], { w: .7 }) + K.t(66, y + 10.5, q[0], { s: 5.4, b: 1, a: 'end' }) + K.t(72 + (q[2] - 60) * .74, y + 10.5, q[1] + '–' + q[2], { s: 4.8, a: 'start' }); }); return s + K.t(100, 124, 'FC máxima aproximada = 220 − edad', { s: 6.4, b: 1 }) + K.t(100, 136, 'Ejemplo a los 14 años: 206 pulsaciones por minuto', { s: 5.4 }); },
      intro: 'La frecuencia cardiaca indica cuán intenso es un esfuerzo; se divide en zonas según el porcentaje del máximo.',
      q: [['¿Cuál es la FC máxima aproximada a los 16 años?', '220 − 16 = 204.'], ['¿En qué zona se mejora la resistencia aeróbica?', 'Entre el 60 y el 80 % de la máxima.'], ['¿Cómo se toma el pulso?', 'Contando los latidos en la muñeca o el cuello durante 15 s y multiplicando por 4.']],
      porque: 'Entrenar en la zona adecuada mejora el corazón sin agotarse antes de tiempo.' },
    G('ef_habitos', 'sal', 'Hábitos de vida saludable', [['Moverse a diario', '60 minutos'], ['Dormir', '9–11 h niños · 8–10 h adolescentes'], ['Beber agua', 'antes, durante y después'], ['Comer variado', 'frutas, verduras, legumbres'], ['Higiene', 'ducha y ropa limpia tras el ejercicio'], ['Pantallas', 'limitar el tiempo sentado']], 2, 22, 28, 'Los hábitos se refuerzan entre sí', 'La actividad física rinde más cuando va acompañada de descanso, buena alimentación e higiene.', [['¿Cuántas horas debe dormir un adolescente?', 'Entre 8 y 10 horas.'], ['¿Por qué ducharse después del ejercicio?', 'Para quitar el sudor y evitar hongos e irritaciones.'], ['¿Qué beber al hacer deporte?', 'Agua, en pequeños sorbos.']], 'Dormir es cuando el cuerpo repara lo que se entrenó.', { s: 7.4, s2: 5 }),
    { id: 'ef_hidratar', fam: 'sal', n: 'Hidratarse al hacer ejercicio',
      d: function (K) { var s = K.suelo(100, 140, 96); [['antes', '1 vaso', 1], ['durante', 'sorbos cada 15–20 min', 2], ['después', 'reponer lo sudado', 3]].forEach(function (q, i) { var x = 36 + i * 64; s += K.p('M' + (x - 10) + ' 40 L' + (x + 10) + ' 40 L' + (x + 8) + ' 92 L' + (x - 8) + ' 92 Z', P.blanco, { w: .9 }) + K.p('M' + (x - 9.6) + ' ' + (92 - q[2] * 14) + ' L' + (x + 9.6) + ' ' + (92 - q[2] * 14) + ' L' + (x + 8) + ' 92 L' + (x - 8) + ' 92 Z', P.agua, { w: .4 }) + K.t(x, 106, q[0], { s: 6.4, b: 1 }) + K.t(x, 115, q[1], { s: 4.8 }); }); return s + K.t(100, 24, 'Con sed ya hay algo de deshidratación', { s: 6, b: 1 }) + K.t(100, 134, 'Orina clara = bien hidratado', { s: 6, b: 1 }); },
      intro: 'Al sudar se pierde agua y sales; hay que beber antes, durante y después del ejercicio.',
      q: [['¿Por qué no esperar a tener sed?', 'Porque la sed aparece cuando ya falta agua.'], ['¿Qué señales indican deshidratación?', 'Sed, cansancio, dolor de cabeza y orina oscura.'], ['¿Hace falta bebida deportiva en una clase?', 'No: para una hora de ejercicio basta el agua.']],
      porque: 'Perder solo un 2 % del peso en agua ya reduce el rendimiento.' },
    { id: 'ef_mochila', fam: 'sal', n: 'Llevar bien la mochila',
      d: function (K) { var s = K.suelo(100, 140, 96) + fig(K, 52, 92, { b: [15, 10, -15, -10] }) + K.r(36, 64, 14, 22, 4, P.verde, { w: .8 }) + K.l('M50 66 L56 72 M50 80 L56 76', P.verdeO, { w: 1 }) + K.t(52, 118, 'bien', { s: 6.4, b: 1, c: P.verdeO }) + K.t(52, 126, 'dos asas, pegada a la espalda', { s: 4.8 }) + fig(K, 148, 92, { tronco: -12, b: [10, 10, -15, -10] }) + K.r(156, 72, 14, 22, 4, P.rojo, { w: .8 }) + K.l('M146 70 L156 76', P.rojoO, { w: 1 }) + K.t(148, 118, 'mal', { s: 6.4, b: 1, c: P.rojoO }) + K.t(148, 126, 'un hombro, colgando baja', { s: 4.8 }); return s + K.t(100, 22, 'Peso máximo: 10 % del peso corporal', { s: 6.2, b: 1 }) + K.t(100, 32, '40 kg de peso → mochila de 4 kg como mucho', { s: 5.4 }); },
      intro: 'Una mochila pesada o mal colocada obliga a la espalda a compensar con malas posturas.',
      q: [['¿Cuánto puede pesar la mochila de alguien de 50 kg?', 'Como mucho 5 kg.'], ['¿Por qué usar las dos asas?', 'Para repartir el peso entre los dos hombros.'], ['¿Dónde se ponen los libros más pesados?', 'Pegados a la espalda.']],
      porque: 'Cuanto más lejos de la espalda cuelga el peso, más esfuerzo hace la columna.' },
    { id: 'ef_sedentario', fam: 'sal', n: 'Cortar el tiempo sentado',
      d: function (K) { var s = K.suelo(100, 140, 96); for (var h = 0; h < 8; h++) { var x = 18 + h * 21; s += K.r(x, 50, 18, 30, 2, h % 2 ? P.gris : P.gris, { w: .6 }) + K.r(x + 6, 46, 6, 8, 2, P.verde, { w: .6 }) + K.t(x + 9, 92, (8 + h) + ' h', { s: 5 }); } s += K.t(100, 30, 'Cada hora sentado: 2–3 minutos de pausa activa', { s: 5.8, b: 1 }) + K.t(100, 40, 'levantarse, estirarse, caminar', { s: 5.2 }); return s + K.r(18, 50, 168, 30, 2, 'none', { w: .3 }) + K.t(100, 70, 'sentado', { s: 6, b: 1 }) + K.t(100, 110, 'verde = pausa activa', { s: 5.4, b: 1, c: P.verdeO }) + K.t(100, 128, 'Sentarse mucho tiempo seguido daña aunque se haga deporte', { s: 5.2 }); },
      intro: 'Pasar muchas horas sentado sin pausas perjudica la salud, aunque después se haga ejercicio.',
      q: [['¿Cada cuánto conviene hacer una pausa activa?', 'Cada 30 a 60 minutos.'], ['Propón una pausa activa en el aula.', 'Ponerse de pie, estirar brazos y espalda y caminar unos pasos.'], ['¿Por qué no basta con el deporte de la tarde?', 'Porque estar quieto muchas horas seguidas tiene efectos propios.']],
      porque: 'Interrumpir el tiempo sentado reactiva la circulación de las piernas.' },
    /* ─────────── ENTRENAMIENTO ─────────── */
    { id: 'ef_supercomp', fam: 'ent', n: 'Entrenar y descansar: la supercompensación',
      d: function (K) { var s = K.suelo(100, 140, 96) + ejes(K, 18, 16, 170, 92, 'tiempo', 'forma física'), base = 78; s += K.l('M18 ' + base + ' L188 ' + base, P.grisO, { w: .6 }); var pts = []; for (var i = 0; i <= 60; i++) { var t = i / 60, x = 22 + t * 160, y = base + Math.sin(t * Math.PI * 2.4) * -10 + 18 * Math.sin(Math.min(t, .4) / .4 * Math.PI) * (t < .4 ? 1 : 0) - (t > .4 ? (t - .4) * 30 : 0); pts.push([x, y]); } s += linea(K, [[22, base], [44, base + 22], [74, base - 12], [96, base + 8], [124, base - 22], [146, base - 4], [176, base - 32]], P.verdeO, 1.8); return s + K.t(40, base + 32, 'esfuerzo', { s: 5, b: 1, c: P.rojoO }) + K.t(74, base - 18, 'recuperación', { s: 5, b: 1, c: P.verdeO }) + K.t(150, 30, 'cada sesión arranca', { s: 5.2 }) + K.t(150, 38, 'un poco más arriba', { s: 5.2, b: 1 }) + K.t(100, 134, 'Sin descanso no hay mejora; sin carga, tampoco', { s: 5.8, b: 1 }); },
      intro: 'Tras un entrenamiento el cuerpo se cansa, se recupera y queda un poco mejor que antes: es la supercompensación.',
      q: [['¿Qué pasa si se entrena sin descansar?', 'El cansancio se acumula y el rendimiento baja.'], ['¿Y si se descansa demasiado?', 'Se pierde la mejora conseguida.'], ['¿Cuándo se mejora: al entrenar o al descansar?', 'Al descansar, tras el estímulo del entrenamiento.']],
      porque: 'El entrenamiento es el estímulo; el descanso es cuando el cuerpo se adapta.' },
    G('ef_principios', 'ent', 'Principios del entrenamiento', [['Progresión', 'aumentar poco a poco'], ['Continuidad', 'entrenar con regularidad'], ['Individualidad', 'cada persona es distinta'], ['Alternancia', 'esfuerzo y descanso'], ['Variedad', 'ejercicios diferentes'], ['Especificidad', 'entrenar lo que se necesita']], 2, 22, 28, 'Correr 20 % más cada semana, no el doble', 'Los principios del entrenamiento indican cómo organizar el ejercicio para mejorar sin lesionarse.', [['¿Qué principio se rompe al correr 10 km sin haber entrenado?', 'La progresión.'], ['¿Por qué dos amigos no deben seguir el mismo plan?', 'Por la individualidad: tienen niveles distintos.'], ['¿Qué pasa si se entrena una semana y se para un mes?', 'Se pierde casi todo: falta continuidad.']], 'Mejorar es cuestión de constancia más que de esfuerzos heroicos.', { s: 7.4, s2: 5.6 }),
    { id: 'ef_circuito', fam: 'ent', n: 'Un circuito de entrenamiento',
      d: function (K) { var E = [['saltos', { b: [160, 170, -160, -170], p: [15, 15, -15, -15] }], ['sentadillas', { tronco: 15, b: [-90, -90, -80, -80], p: [-90, 0, -70, 0] }], ['abdominales', { tronco: 50, b: [140, 160, -140, -160], p: [-80, 0, -80, 0] }], ['comba', { b: [60, 20, -60, -20], p: [5, 5, -5, -5] }], ['flexiones', { tronco: 75, b: [10, 0, 15, 0], p: [-100, -100, -95, -95] }], ['skipping', { b: [-40, -100, 40, 100], p: [-70, 10, 0, 0] }]], s = K.suelo(100, 140, 96); E.forEach(function (q, i) { var a = -Math.PI / 2 + i * Math.PI / 3, x = 100 + Math.cos(a) * 62, y = 74 + Math.sin(a) * 46; s += K.c(x, y, 17, CO[i], { w: .7, op: .7 }) + fig(K, x, y + 6, Object.assign({ e: .55 }, q[1])) + K.t(x, y + 22, (i + 1) + ' ' + q[0], { s: 5, b: 1 }); }); return s + K.t(100, 70, '30 s de trabajo', { s: 5.6, b: 1 }) + K.t(100, 79, '30 s para cambiar', { s: 5.4 }) + K.t(100, 88, '× 2 vueltas', { s: 5.4, b: 1 }); },
      intro: 'En un circuito se pasa por varias estaciones con ejercicios distintos, alternando grupos musculares.',
      q: [['¿Cuánto dura el circuito completo?', '6 estaciones × 1 min × 2 vueltas = 12 minutos.'], ['¿Por qué alternar piernas, brazos y abdomen?', 'Para que unos músculos descansen mientras trabajan otros.'], ['¿Qué capacidades trabaja?', 'Fuerza y resistencia.']],
      porque: 'Variar los ejercicios mantiene el esfuerzo alto sin agotar un solo músculo.' },
    { id: 'ef_cooper', fam: 'ent', n: 'El test de Cooper',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.e(100, 66, 82, 40, P.pista, { w: 1 }) + K.e(100, 66, 64, 26, P.cesped, { w: .8 }); for (var i = 1; i < 4; i++) s += K.e(100, 66, 64 + i * 5, 26 + i * 4.5, 'none', { w: .3 }); s += fig(K, 100, 108, { e: .6, b: [-50, -100, 70, 120], p: [55, -20, -40, -60], col: P.amarillo }) + K.c(170, 24, 10, P.blanco, { w: .8 }) + K.l('M170 24 L170 17 M170 24 L175 26', P.tinta, { w: .8 }) + K.t(170, 42, '12 min', { s: 5.8, b: 1 }); return s + K.t(100, 64, 'correr 12 minutos', { s: 6, b: 1 }) + K.t(100, 72, 'y medir los metros', { s: 5.4 }) + K.t(100, 126, '7 vueltas de 400 m + 200 m = 3 000 m', { s: 6, b: 1 }) + K.t(100, 136, 'Se compara con la propia marca anterior', { s: 5.4 }); },
      intro: 'El test de Cooper mide la resistencia aeróbica por la distancia recorrida en 12 minutos.',
      q: [['¿Cuántos metros son 6,5 vueltas a una pista de 400 m?', '2 600 m.'], ['¿Qué capacidad mide?', 'La resistencia aeróbica.'], ['¿Cómo conviene correrlo?', 'A ritmo constante, sin salir demasiado rápido.']],
      porque: 'Salir a tope y pararse da peor marca que mantener un ritmo parejo.' },
    { id: 'ef_registro', fam: 'ent', n: 'Mi registro de progreso',
      d: function (K) { var s = K.suelo(100, 140, 96) + ejes(K, 26, 16, 160, 86, '', 'metros'), V = [1800, 1950, 2000, 2150, 2250, 2400], y = function (v) { return 102 - (v - 1600) * .09; }; V.forEach(function (v, i) { var x = 40 + i * 26; s += K.caja(x - 7, y(v), 14, 102 - y(v), 3, P.azul, { w: .6 }) + K.t(x, y(v) - 3, String(v).replace(/(\d)(\d{3})$/, '$1 $2'), { s: 4.6, b: 1 }) + K.t(x, 112, 'sem ' + (i + 1), { s: 4.6 }); }); return s + K.t(100, 128, 'Test de Cooper cada semana: +600 m en 6 semanas', { s: 5.8, b: 1 }) + K.t(100, 138, 'Anotar fecha, prueba, marca y cómo te sentiste', { s: 5.2 }); },
      intro: 'Anotar los resultados de cada prueba muestra el progreso y ayuda a fijar metas realistas.',
      q: [['¿Cuánto mejoró entre la semana 1 y la 6?', '2 400 − 1 800 = 600 m.'], ['¿Cuál fue la mayor mejora semanal?', 'De la 5 a la 6 o de la 3 a la 4: 150 m.'], ['¿Por qué anotar cómo te sentiste?', 'Porque el cansancio o el sueño explican algunas marcas.']],
      porque: 'Lo que se mide se puede mejorar.' }
  ];
  MO.agregar('efisica', L, { nombre: 'Educación física', familias: FAM, materias: /^(efisica)$/ });
})();
