/* b6_lib_panaderia3.js — Panadería (3/3): proceso, ciencia del pan, medida y costes. 30 modelos para EU_MODELOS.
   Cargar después de b6_lib_panaderia2.js. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('pn_p_mezcla')) return;
  var M = MO.M;
  function domo(K, cx, cy, rx, ry, c) { return K.p('M' + (cx - rx) + ' ' + cy + ' C' + (cx - rx) + ' ' + (cy - ry * 1.36) + ' ' + (cx + rx) + ' ' + (cy - ry * 1.36) + ' ' + (cx + rx) + ' ' + cy + ' Q' + cx + ' ' + (cy + ry * .22) + ' ' + (cx - rx) + ' ' + cy + ' Z', c); }
  function cuenco(K, cx, cy, rx, c) { return K.p('M' + (cx - rx) + ' ' + cy + ' Q' + (cx - rx + 3) + ' ' + (cy + rx * .8) + ' ' + cx + ' ' + (cy + rx * .8) + ' Q' + (cx + rx - 3) + ' ' + (cy + rx * .8) + ' ' + (cx + rx) + ' ' + cy + ' Z', c || M.ceramica) + K.e(cx, cy, rx, rx * .2, c || M.ceramica); }
  function num(K, n, x, y) { return K.c(x, y, 6.5, K.linea ? 'none' : M.rojo, { w: 1 }) + K.t(x, y + 2.8, n, { s: 7.6, b: 1, c: K.linea ? '#1B1B1B' : '#fff' }); }
  function ejes(K, x0, y0, w, h) { return K.l('M' + x0 + ' ' + (y0 - h) + ' V' + y0 + ' H' + (x0 + w), M.tinta, { w: 1.1 }); }

  var L = [
    /* ─────────── PROCESO ─────────── */
    { id: 'pn_p_mezcla', fam: 'pro', n: 'Los cuatro ingredientes',
      d: function (K) { var s = cuenco(K, 100, 104, 40) + K.suelo(100, 138, 40); s += K.p('M14 22 L42 22 L40 50 L16 50 Z', M.lino) + K.t(28, 60, 'Harina', { s: 7 }) + K.p('M64 20 L82 20 L84 50 L62 50 Z', M.vidrio, { op: .7 }) + K.r(64, 32, 20, 18, 0, M.agua, { op: .8 }) + K.t(73, 60, 'Agua', { s: 7 }) + K.cil(128, 30, 10, 18, M.blanco) + K.t(128, 60, 'Sal', { s: 7 }) + K.caja(160, 30, 22, 18, 5, M.amarillo) + K.t(171, 60, 'Levadura', { s: 7 }); [[28, 64], [73, 64], [128, 64], [171, 64]].forEach(function (p) { s += K.flecha(p[0], p[1] + 2, 100 + (p[0] - 100) * .25, 94, M.tinta, { w: 1 }); }); return s; },
      intro: 'El pan básico se hace con harina, agua, sal y levadura. Todo lo demás es opcional.',
      q: [['¿Qué función cumple el agua?', 'Hidrata la harina para que se forme el gluten y activa la levadura.'], ['¿Qué hace la sal además de dar sabor?', 'Fortalece el gluten y frena un poco la levadura.'], ['¿Por qué no se pone la sal en contacto directo con la levadura?', 'Porque puede deshidratarla y debilitarla.']],
      porque: 'Con solo cuatro ingredientes, cada uno cumple una función que ningún otro puede suplir.' },
    { id: 'pn_p_autolisis', fam: 'pro', n: 'Autólisis',
      d: function (K) { var s = cuenco(K, 76, 86, 50) + K.p('M30 86 Q76 60 122 86 Z', M.masa) + K.p('M24 84 Q76 78 128 84', 'none', { w: 1 }) + K.suelo(76, 128, 50) + K.c(160, 60, 26, M.blanco) + K.l('M160 60 V42 M160 60 L172 68', M.tinta, { w: 1.8 }) + K.p('M160 60 L160 34 A26 26 0 0 1 186 60 Z', M.agua, { op: .6 }); return s + K.t(160, 100, '30 min', { s: 10, b: 1 }) + K.t(76, 36, 'Harina + agua', { s: 8 }); },
      intro: 'Reposo de harina y agua, sin sal ni levadura, antes de amasar.',
      q: [['¿Cuánto dura la autólisis?', 'Entre 20 y 60 minutos.'], ['¿Qué se ahorra con ella?', 'Tiempo de amasado.'], ['¿Por qué no se añade sal todavía?', 'La sal aprieta el gluten y frena la hidratación.']],
      porque: 'En reposo, la harina se hidrata sola y las enzimas empiezan a formar gluten sin esfuerzo.' },
    { id: 'pn_p_amasado', fam: 'pro', n: 'Amasar',
      d: function (K) { return K.caja(10, 104, 180, 20, 10, M.madera) + domo(K, 100, 104, 56, 26, M.masa) + K.flecha(62, 84, 130, 70, M.rojo, { curva: [90, 58] }) + K.flecha(140, 90, 76, 96, M.rojo, { curva: [110, 112] }) + num(K, '1', 58, 78) + num(K, '2', 144, 96) + K.t(100, 30, 'Estirar y plegar', { s: 9, b: 1 }); },
      rot: [['Masa', 70, 100, 20, 60]],
      intro: 'Se estira la masa con el talón de la mano y se vuelve a plegar sobre sí misma.',
      q: [['¿Cuánto se amasa a mano una masa básica?', 'Unos 10–15 minutos.'], ['¿Cómo cambia la masa al amasarla?', 'Pasa de pegajosa y rota a lisa y elástica.'], ['¿Qué se forma al amasar?', 'La red de gluten.']],
      porque: 'Cada estirón alinea las proteínas y cada pliegue las cruza: así se teje la red.' },
    { id: 'pn_p_ventana', fam: 'pro', n: 'Prueba de la ventana',
      d: function (K) { return K.c(100, 70, 46, K.linea ? 'none' : '#FFF4C8', { w: .6, op: .9 }) + K.p('M50 70 Q52 36 100 30 Q148 36 150 70 Q148 104 100 110 Q52 104 50 70 Z', M.masa) + K.p('M68 70 Q70 48 100 44 Q130 48 132 70 Q130 92 100 96 Q70 92 68 70 Z', K.linea ? 'none' : '#FBF3DE', { op: .7 }) + K.l('M78 60 Q100 54 122 62 M76 78 Q100 84 124 76', M.corteza, { w: .6, op: .6 }) + K.t(100, 132, 'Membrana fina sin romperse', { s: 8 }); },
      rot: [['Membrana', 100, 70, 170, 40], ['Borde grueso', 52, 78, 14, 110]],
      intro: 'Se estira un trozo de masa: si se ve la luz sin que se rompa, el gluten está listo.',
      q: [['¿Qué indica que la masa se rompa enseguida?', 'Que falta amasado.'], ['¿Sirve la prueba para el pan de centeno?', 'No, el centeno no forma una red de gluten.'], ['¿Por qué la masa debe estar reposada unos segundos?', 'Para que el gluten se relaje y se estire sin romper.']],
      porque: 'Una red de gluten desarrollada es tan continua que se estira en lámina casi transparente.' },
    { id: 'pn_p_pliegues', fam: 'pro', n: 'Pliegues en el cuenco',
      d: function (K) { var s = ''; for (var i = 0; i < 4; i++) { var x = 26 + i * 50; s += K.r(x - 18, 60, 36, 36, 6, M.masa) + num(K, String(i + 1), x, 48); } s += K.flecha(26, 70, 26, 84, M.rojo, { w: 1 }) + K.p('M58 60 L94 60 L94 76 L58 76 Z', K.oscuro(M.masa, .08)) + K.flecha(76, 94, 76, 78, M.rojo, { w: 1 }) + K.p('M108 70 L144 70 L144 86 L108 86 Z', K.oscuro(M.masa, .08)) + K.flecha(158, 78, 190, 78, M.rojo, { w: 1, curva: [174, 60] }); return s + K.t(100, 124, 'Cada 30 min · 4 veces', { s: 8.5, b: 1 }); },
      intro: 'Se estira un borde de la masa hacia arriba y se dobla sobre el centro, girando el cuenco.',
      q: [['¿Qué masas se trabajan con pliegues en lugar de amasado?', 'Las muy hidratadas, como la chapata o la hogaza de masa madre.'], ['¿Cuántos pliegues se hacen cada vez?', 'Cuatro, uno por cada lado.'], ['¿Cada cuánto se repite?', 'Cada 30 minutos, durante las primeras 2 horas.']],
      porque: 'El tiempo entre pliegues deja que el gluten se forme solo; el pliegue lo ordena y le da fuerza.' },
    { id: 'pn_p_boleado', fam: 'pro', n: 'Bolear',
      d: function (K) { return K.caja(10, 108, 180, 18, 10, M.madera) + domo(K, 100, 108, 44, 32, M.masa) + K.flecha(48, 104, 150, 104, M.rojo, { curva: [100, 130] }) + K.l('M76 70 Q100 62 124 70 M70 84 Q100 74 130 84', M.corteza, { w: .7, op: .6 }) + K.t(100, 30, 'La superficie se tensa', { s: 9, b: 1 }); },
      rot: [['Piel tensa', 124, 70, 176, 50]],
      intro: 'Se gira la pieza sobre la mesa arrastrándola para tensar su superficie.',
      q: [['¿Por qué la mesa no debe tener harina al bolear?', 'La masa necesita agarre para tensarse.'], ['¿Qué pasa si se tensa demasiado?', 'La piel se rasga.'], ['¿Qué se hace después de bolear?', 'Dejar reposar 15–20 minutos antes de formar.']],
      porque: 'La piel tensa actúa como un globo: retiene el gas y da una forma redonda y alta.' },
    { id: 'pn_p_formado_barra', fam: 'pro', n: 'Formar una barra',
      d: function (K) { return K.r(10, 58, 46, 30, 6, M.masa) + num(K, '1', 33, 46) + K.flecha(60, 74, 74, 74, M.tinta) + K.r(80, 64, 44, 20, 10, M.masa) + K.l('M86 74 Q102 66 118 74', M.corteza, { w: .8 }) + num(K, '2', 102, 46) + K.flecha(128, 74, 140, 74, M.tinta) + K.r(144, 68, 52, 12, 6, M.masa) + num(K, '3', 170, 46) + K.t(33, 104, 'Aplanar', { s: 7.6 }) + K.t(102, 104, 'Enrollar', { s: 7.6 }) + K.t(170, 104, 'Estirar', { s: 7.6 }); },
      intro: 'La barra se forma en tres gestos: aplanar, enrollar sellando y estirar rodando.',
      q: [['¿Por qué se sella con el talón de la mano?', 'Para cerrar la costura y que no se abra en el horno.'], ['¿Desde dónde se estira?', 'Desde el centro hacia las puntas.'], ['¿Hacia dónde queda la costura al fermentar?', 'Hacia arriba en el lienzo; al hornear, abajo.']],
      porque: 'Enrollar crea tensión en la superficie y el sellado la conserva.' },
    { id: 'pn_p_fermentacion', fam: 'pro', n: 'La masa dobla su volumen',
      d: function (K) { var s = '', D = [[34, 14, '0 h'], [100, 26, '1 h'], [166, 38, '2 h']]; D.forEach(function (x) { s += K.p('M' + (x[0] - 24) + ' 50 L' + (x[0] - 20) + ' 118 L' + (x[0] + 20) + ' 118 L' + (x[0] + 24) + ' 50 Z', M.vidrio, { op: .5 }) + K.p('M' + (x[0] - 22) + ' ' + (118 - x[1] - 8) + ' Q' + x[0] + ' ' + (118 - x[1] - 18) + ' ' + (x[0] + 22) + ' ' + (118 - x[1] - 8) + ' L' + (x[0] + 20) + ' 118 L' + (x[0] - 20) + ' 118 Z', M.masa) + K.t(x[0], 134, x[2], { s: 9, b: 1 }); }); return s + K.l('M10 104 H190', M.rojo, { d: '3 3', w: .8 }) + K.l('M10 72 H190', M.rojo, { d: '3 3', w: .8 }) + K.t(192, 70, '×2', { a: 'end', s: 7.6, c: K.linea ? '#1B1B1B' : M.rojo }); },
      intro: 'Con levadura y a 25 °C, la masa tarda de 1 a 2 horas en doblar su volumen.',
      q: [['¿Por qué se usa un recipiente de lados rectos?', 'Para medir el crecimiento con facilidad.'], ['¿Qué pasa a 30 °C?', 'La fermentación va más rápido.'], ['¿Qué pasa si fermenta demasiado?', 'El gluten se debilita y el pan se hunde.']],
      porque: 'La levadura produce CO₂; la red de gluten lo retiene y la masa se infla.' },
    { id: 'pn_p_dedo', fam: 'pro', n: 'Prueba del dedo',
      d: function (K) { var s = '', D = [[34, 'Le falta', 'vuelve rápido', 2], [100, 'Lista', 'vuelve despacio', 6], [166, 'Pasada', 'no vuelve', 11]]; D.forEach(function (x) { s += domo(K, x[0], 96, 28, 22, M.masa) + K.e(x[0], 72 + x[3] * .6, 5, 2 + x[3] * .25, K.oscuro(M.masa, .18)) + K.t(x[0], 114, x[1], { s: 8.6, b: 1 }) + K.t(x[0], 124, x[2], { s: 6.8 }); }); return s; },
      intro: 'Se hunde un dedo enharinado en la masa y se mira cómo recupera el hueco.',
      q: [['¿Qué significa que el hueco vuelva rápido?', 'Que le falta fermentar.'], ['¿Y si no vuelve?', 'Que está pasada de fermentación.'], ['¿Qué se hace con una masa lista?', 'Hornearla enseguida.']],
      porque: 'Una red de gluten con la cantidad justa de gas cede y se recupera despacio.' },
    { id: 'pn_p_grenados', fam: 'pro', n: 'Dibujos de greñado',
      d: function (K) { var s = '', X = [28, 76, 124, 172]; X.forEach(function (x) { s += K.c(x, 70, 22, M.corteza); }); s += K.l('M16 60 L40 80 M40 60 L16 80', M.cortezaC, { w: 2 }) + K.l('M66 58 L86 82 M60 66 L72 60 M60 76 L78 66 M74 84 L92 74', M.cortezaC, { w: 2 }) + K.l('M110 62 H138 M110 70 H138 M110 78 H138 M116 56 V84 M124 56 V84 M132 56 V84', M.cortezaC, { w: 1.5 }) + K.l('M156 70 Q172 58 188 70', M.cortezaC, { w: 2 }); return s + K.t(28, 106, 'Cruz', { s: 7.6 }) + K.t(76, 106, 'Espiga', { s: 7.6 }) + K.t(124, 106, 'Cuadrícula', { s: 7.6 }) + K.t(172, 106, 'Uno curvo', { s: 7.6 }); },
      intro: 'Cuatro dibujos de corte habituales sobre una pieza redonda.',
      q: [['¿Cuál se abre en cuatro lóbulos?', 'El corte en cruz.'], ['¿Qué dibujo necesita cortes muy poco profundos?', 'La cuadrícula.'], ['¿Qué profundidad tiene un corte normal?', 'Entre 5 y 10 mm.']],
      porque: 'Cada corte es un punto débil; su número y dirección deciden por dónde se expande el pan.' },
    { id: 'pn_p_vapor', fam: 'pro', n: 'Vapor en el horno',
      d: function (K) { var s = K.caja(14, 20, 172, 112, 12, M.acero) + K.r(22, 28, 156, 96, 2, K.linea ? 'none' : '#2E2A28') + K.r(28, 96, 144, 6, 1, '#8A8F96') + K.r(40, 112, 44, 8, 1, M.metal) + K.r(42, 114, 40, 5, 1, M.agua); s += domo(K, 124, 96, 36, 20, M.masa); [[52, 90], [66, 76], [58, 60], [92, 54], [150, 50]].forEach(function (p, i) { s += K.p('M' + p[0] + ' ' + p[1] + ' q6 -8 0 -14 q-6 -6 0 -12', 'none', { w: 1.4 }); }); return s; },
      rot: [['Bandeja con agua', 62, 116, 30, 144], ['Vapor', 92, 48, 92, 12]],
      intro: 'En los primeros minutos de horno, el vapor mantiene la superficie húmeda.',
      q: [['¿Cuándo se retira el vapor?', 'A los 10–15 minutos, abriendo la puerta o quitando la bandeja.'], ['¿Qué pasa si no hay vapor?', 'La corteza se seca antes y el pan crece menos.'], ['¿Qué aporta el vapor al color?', 'Una corteza brillante y más dorada.']],
      porque: 'La superficie húmeda sigue elástica y deja crecer al pan antes de endurecerse.' },
    { id: 'pn_p_conservar', fam: 'pro', n: 'Conservar el pan',
      d: function (K) { return K.p('M14 40 L58 40 L62 118 L10 118 Z', M.lino) + K.r(22, 50, 32, 60, 12, M.corteza) + K.t(36, 132, 'Bolsa de papel', { s: 7, b: 1 }) + K.t(36, 141, '1–2 días', { s: 6.6 }) + K.p('M78 40 L122 40 L126 118 L74 118 Z', M.vidrio, { op: .5 }) + K.r(86, 50, 32, 60, 12, M.cortezaC) + K.t(100, 132, 'Bolsa de plástico', { s: 7, b: 1 }) + K.t(100, 141, 'corteza blanda', { s: 6.6 }) + K.caja(142, 40, 44, 78, 10, '#DDEEF7') + K.r(150, 56, 28, 44, 10, M.corteza) + K.t(164, 132, 'Congelador', { s: 7, b: 1 }) + K.t(164, 141, 'hasta 3 meses', { s: 6.6 }); },
      intro: 'Tres formas de guardar el pan y lo que le pasa a su corteza.',
      q: [['¿Por qué el pan duro no se recupera en la nevera?', 'El frío de la nevera acelera el endurecimiento del almidón.'], ['¿Cómo se descongela mejor?', 'A temperatura ambiente y 5 minutos de horno.'], ['¿Por qué la bolsa de plástico ablanda la corteza?', 'Encierra la humedad que sale de la miga.']],
      porque: 'El pan se endurece porque el almidón se recristaliza; el frío de nevera lo acelera y la congelación lo detiene.' },
    { id: 'pn_p_carga', fam: 'pro', n: 'Cargar el horno',
      d: function (K) { return K.caja(80, 28, 110, 96, 12, M.acero) + K.r(88, 84, 94, 30, 2, K.linea ? 'none' : '#2E2A28') + K.r(90, 108, 90, 6, 1, '#B5563A') + K.r(4, 100, 70, 5, 2.5, M.madera) + K.p('M70 96 L130 96 Q136 96 136 102 L136 104 L70 104 Z', M.madera) + K.e(110, 94, 20, 7, M.masa) + K.flecha(40, 88, 104, 88, M.rojo, { w: 1.4 }) + K.t(136, 46, '240 °C', { s: 10, b: 1, c: K.linea ? '#1B1B1B' : '#fff' }); },
      rot: [['Solera caliente', 160, 111, 186, 140], ['Pala', 30, 102, 20, 128]],
      intro: 'El pan entra en la solera con la pala en un solo movimiento seco.',
      q: [['¿Por qué se da un tirón rápido a la pala?', 'Para que el pan caiga sin deformarse.'], ['¿Qué se hace justo después de cargar?', 'Dar vapor y cerrar la puerta.'], ['¿Por qué se precalienta la solera 45 minutos?', 'Para que la piedra acumule todo el calor.']],
      porque: 'El choque térmico de la piedra hace que el pan crezca de golpe en los primeros minutos.' },

    /* ─────────── CIENCIA DEL PAN ─────────── */
    { id: 'pn_c_gluten', fam: 'cie', n: 'La red de gluten',
      d: function (K) { var s = ''; for (var i = 0; i < 5; i++) s += K.l('M10 ' + (30 + i * 22) + ' Q50 ' + (20 + i * 22) + ' 100 ' + (34 + i * 22) + ' T190 ' + (30 + i * 22), M.corteza, { w: 2.2 }); for (var j = 0; j < 6; j++) s += K.l('M' + (24 + j * 30) + ' 24 Q' + (34 + j * 30) + ' 76 ' + (20 + j * 30) + ' 128', M.cortezaO, { w: 1.2, op: .8 }); [[40, 44], [76, 64], [120, 40], [150, 90], [64, 108], [110, 100], [170, 56]].forEach(function (p) { s += K.c(p[0], p[1], 4, M.amarillo); }); return s; },
      rot: [['Glutenina (cadenas)', 100, 34, 150, 12], ['Gliadina (bolitas)', 150, 90, 176, 140]],
      intro: 'Al mojar y amasar la harina, dos proteínas se unen y forman el gluten.',
      q: [['¿Qué proteína da elasticidad?', 'La glutenina.'], ['¿Qué proteína da extensibilidad?', 'La gliadina.'], ['¿Qué retiene la red de gluten?', 'El gas que produce la levadura.']],
      porque: 'Las cadenas de glutenina hacen de muelle y la gliadina de lubricante: juntas forman una malla elástica.' },
    { id: 'pn_c_levadura', fam: 'cie', n: 'La levadura trabaja',
      d: function (K) { var s = K.e(56, 70, 26, 20, M.amarillo) + K.e(84, 56, 12, 9, M.amarillo) + K.c(52, 70, 6, K.oscuro(M.amarillo, .25)); [[124, 40, 6], [140, 58, 9], [160, 36, 5], [132, 84, 7], [170, 74, 10], [150, 104, 6]].forEach(function (b) { s += K.c(b[0], b[1], b[2], M.vidrio, { op: .7 }) + K.brillo(b[0] - b[2] * .3, b[1] - b[2] * .3, b[2] * .3, b[2] * .2); }); return s + K.t(100, 132, 'azúcar → CO₂ + alcohol', { s: 9, b: 1 }); },
      rot: [['Célula', 40, 80, 16, 110], ['Yema (brote)', 84, 56, 92, 24], ['Burbujas de CO₂', 170, 74, 186, 130]],
      intro: 'La levadura es un hongo microscópico que se come los azúcares de la harina.',
      q: [['¿Qué gas produce?', 'Dióxido de carbono (CO₂).'], ['¿Qué pasa con el alcohol?', 'Se evapora en el horno y deja aroma.'], ['¿A qué temperatura muere la levadura?', 'Hacia 55–60 °C.']],
      porque: 'Sin oxígeno, la levadura fermenta: transforma azúcar en gas, que infla la masa, y en aromas.' },
    { id: 'pn_c_alveolos', fam: 'cie', n: 'Cómo nace un alveolo',
      d: function (K) { var s = '', R = [4, 9, 16]; R.forEach(function (r, i) { var x = 36 + i * 64; s += K.r(x - 26, 44, 52, 52, 6, M.masa) + K.c(x, 70, r, K.linea ? 'none' : '#FBF6EC') + K.l('M' + (x - r) + ' 70 A' + r + ' ' + r + ' 0 1 0 ' + (x + r) + ' 70 A' + r + ' ' + r + ' 0 1 0 ' + (x - r) + ' 70', M.corteza, { w: 1.6 }) + (i < 2 ? K.flecha(x + 30, 70, x + 36, 70, M.tinta) : ''); }); return s + K.t(36, 112, 'Mezcla', { s: 7.6 }) + K.t(100, 112, 'Fermentación', { s: 7.6 }) + K.t(164, 112, 'Horno', { s: 7.6 }); },
      rot: [['Pared de gluten', 180, 70, 188, 36]],
      intro: 'Las burbujas se forman al mezclar, crecen al fermentar y se fijan en el horno.',
      q: [['¿De dónde salen las primeras burbujas?', 'Del aire que entra al mezclar y amasar.'], ['¿Qué las hace crecer?', 'El CO₂ de la levadura.'], ['¿Qué las fija para siempre?', 'El calor, que cuaja el gluten y el almidón.']],
      porque: 'La levadura no crea burbujas nuevas: infla las que ya había; por eso el amasado decide la miga.' },
    { id: 'pn_c_almidon', fam: 'cie', n: 'El almidón se gelatiniza',
      d: function (K) { var s = ''; [[36, 5, '20 °C'], [100, 9, '60 °C'], [164, 14, '85 °C']].forEach(function (x, i) { for (var k = 0; k < 5; k++) { var a = k * 1.26; s += K.e(x[0] + Math.cos(a) * 16, 70 + Math.sin(a) * 16, x[1], x[1] * .8, i === 2 ? K.claro(M.miga, .3) : M.miga, { op: i === 2 ? .8 : 1 }); } s += K.t(x[0], 110, x[2], { s: 9, b: 1 }); }); return s + K.flecha(60, 70, 72, 70, M.tinta) + K.flecha(124, 70, 136, 70, M.tinta); },
      intro: 'Con agua y calor, los gránulos de almidón se hinchan y forman un gel.',
      q: [['¿A qué temperatura empieza el almidón de trigo a gelatinizarse?', 'Hacia 58–64 °C.'], ['¿Qué parte del pan forma el almidón gelatinizado?', 'La miga.'], ['¿Qué ocurre cuando el pan se enfría días después?', 'El almidón se recristaliza y el pan se endurece.']],
      porque: 'El calor abre el gránulo, entra agua y el almidón pasa de cristal duro a gel blando.' },
    { id: 'pn_c_maillard', fam: 'cie', n: 'Color de la corteza',
      d: function (K) { var s = '', C = [['#E8D2A6', '150 °C'], ['#DDB27A', '170 °C'], ['#C67B35', '190 °C'], ['#9A5424', '210 °C'], ['#5C3418', '230 °C']]; C.forEach(function (c, i) { s += K.caja(16 + i * 36, 50, 28, 40, 6, c[0]) + K.t(30 + i * 36, 106, c[1], { s: 7.6, b: 1 }); }); return s + K.flecha(20, 124, 184, 124, M.rojo, { w: 1.2 }) + K.t(100, 140, 'Más calor y tiempo = más aroma y color', { s: 7.4 }); },
      intro: 'Los azúcares y las proteínas de la superficie reaccionan con el calor y dan color y aroma.',
      q: [['¿Cómo se llama esta reacción?', 'Reacción de Maillard.'], ['¿Por qué la miga no se dora?', 'Dentro no pasa de unos 98 °C por el agua que contiene.'], ['¿Qué ingrediente de la masa oscurece antes la corteza?', 'El azúcar o la leche.']],
      porque: 'La reacción necesita más de 140 °C, y solo la superficie seca llega a esa temperatura.' },
    { id: 'pn_c_grano', fam: 'cie', n: 'El grano de trigo',
      d: function (K) { return K.e(100, 72, 70, 42, '#B77A3A') + K.e(100, 72, 64, 36, M.miga) + K.e(160, 84, 10, 12, M.amarillo) + K.l('M34 72 Q100 60 166 72', '#B77A3A', { w: .8, op: .6 }) + K.t(100, 132, 'Salvado 14 % · Endospermo 83 % · Germen 3 %', { s: 7.2, b: 1 }); },
      rot: [['Salvado', 40, 48, 14, 24], ['Endospermo', 90, 80, 60, 118], ['Germen', 160, 84, 186, 112]],
      intro: 'Un grano de trigo tiene tres partes; la harina blanca usa solo el endospermo.',
      q: [['¿Qué parte da la harina blanca?', 'El endospermo.'], ['¿Qué aporta el salvado?', 'Fibra.'], ['¿Por qué la harina integral se enrancia antes?', 'El germen contiene grasa que se oxida.']],
      porque: 'El endospermo es la reserva de almidón y proteína que la semilla usaría para crecer.' },
    { id: 'pn_c_harinas', fam: 'cie', n: 'Tipos de harina',
      d: function (K) { var s = '', D = [['Floja', 'W 100', '9 %'], ['Media', 'W 200', '11 %'], ['Fuerza', 'W 300', '13 %'], ['Integral', 'W 250', '12 %']]; D.forEach(function (x, i) { var X = 12 + i * 47; s += K.p('M' + X + ' 44 Q' + (X + 20) + ' 36 ' + (X + 40) + ' 44 L' + (X + 42) + ' 120 L' + (X - 2) + ' 120 Z', i === 3 ? '#D8B98A' : M.lino) + K.t(X + 20, 66, x[0], { s: 8.4, b: 1 }) + K.t(X + 20, 82, x[1], { s: 7.4 }) + K.t(X + 20, 96, 'Prot. ' + x[2], { s: 6.6 }); }); return s + K.t(100, 140, 'Más W → más fuerza para fermentaciones largas', { s: 7.2 }); },
      intro: 'Las harinas se clasifican por su fuerza (W) y su proteína.',
      q: [['¿Qué harina se usa para bizcochos?', 'La floja, de poca fuerza.'], ['¿Y para brioche o panettone?', 'La de fuerza.'], ['¿Qué mide el valor W?', 'La fuerza de la masa: cuánto resiste al estirarse.']],
      porque: 'Más proteína da más gluten, y más gluten soporta más grasa, azúcar y tiempo de fermentación.' },
    { id: 'pn_c_masa_madre', fam: 'cie', n: 'Masa madre',
      d: function (K) { var s = K.p('M60 30 L140 30 L144 126 L56 126 Z', M.vidrio, { op: .5 }) + K.r(62, 58, 78, 66, 4, M.masa) + K.r(56, 22, 88, 10, 3, M.acero) + K.l('M56 96 H144', M.rojo, { w: 2.2 }) + K.t(150, 99, 'inicio', { a: 'start', s: 7 }) + K.l('M56 60 H144', M.tinta, { d: '3 3' }) + K.t(150, 63, '×2 en 6 h', { a: 'start', s: 7 }); [[76, 80], [96, 100], [118, 76], [128, 108], [88, 70], [110, 92]].forEach(function (p) { s += K.c(p[0], p[1], 2.4, K.linea ? 'none' : '#FBF6EC'); }); return s; },
      rot: [['Banda de referencia', 60, 96, 20, 120]],
      intro: 'Cultivo de levaduras salvajes y bacterias lácticas que se alimenta con harina y agua.',
      q: [['¿Cada cuánto se alimenta a temperatura ambiente?', 'Una vez al día.'], ['¿Qué dan las bacterias lácticas?', 'Acidez y sabor.'], ['¿Cómo se sabe que está activa?', 'Dobla su volumen en unas horas tras alimentarla.']],
      porque: 'Levaduras y bacterias conviven: unas producen gas y las otras, ácidos que dan sabor y conservación.' },
    { id: 'pn_c_temp_masa', fam: 'cie', n: 'Temperatura de la masa',
      d: function (K) { var s = K.r(20, 60, 160, 20, 10, M.blanco) + K.r(20, 60, 60, 20, 10, M.agua) + K.r(80, 60, 40, 20, 0, M.verde) + K.r(120, 60, 60, 20, 10, M.fuego); [['20', 20], ['24', 80], ['26', 120], ['30 °C', 180]].forEach(function (x) { s += K.l('M' + x[1] + ' 56 V84', M.tinta, { w: .8 }) + K.t(x[1], 52, x[0], { s: 7.6, b: 1 }); }); return s + K.t(50, 100, 'Lenta', { s: 8 }) + K.t(100, 100, 'Ideal', { s: 8, b: 1 }) + K.t(150, 100, 'Rápida', { s: 8 }) + K.l('M100 118 V106', M.rojo, { w: 1.6 }) + K.t(100, 128, 'Masa a 25 °C', { s: 8 }); },
      intro: 'La masa debe salir del amasado entre 24 y 26 °C.',
      q: [['¿Qué pasa si sale a 20 °C?', 'La fermentación va muy lenta.'], ['¿Qué pasa si sale a 30 °C?', 'Fermenta demasiado rápido y pierde sabor.'], ['¿Qué ingrediente se usa para corregir la temperatura?', 'El agua: más fría o más tibia.']],
      porque: 'La levadura trabaja a un ritmo que depende de la temperatura: controlarla es controlar el tiempo.' },
    { id: 'pn_c_curva', fam: 'cie', n: 'Temperatura dentro del pan',
      d: function (K) { var s = ejes(K, 26, 118, 164, 96) + K.l('M26 110 C60 104 80 60 110 40 S160 30 186 30', M.rojo, { w: 2 }); [['98 °C', 30], ['60 °C', 70], ['20 °C', 110]].forEach(function (x) { s += K.l('M22 ' + x[1] + ' H190', M.gris, { d: '2 3', w: .6 }) + K.t(20, x[1] + 2.5, x[0], { a: 'end', s: 6.6 }); }); return s + K.t(108, 136, 'Minutos de horno', { s: 7.4 }) + K.t(104, 74, 'muere la levadura', { a: 'start', s: 6.6 }) + K.t(186, 24, 'pan hecho', { a: 'end', s: 6.6, b: 1 }); },
      intro: 'Así sube la temperatura en el centro de una hogaza durante el horneado.',
      q: [['¿A qué temperatura deja de crecer el pan?', 'Hacia 60 °C, cuando muere la levadura.'], ['¿Por qué el centro no pasa de 98–99 °C?', 'El agua que contiene hierve y se lleva el calor.'], ['¿Qué ocurre entre 60 y 80 °C?', 'El almidón se gelatiniza y el gluten cuaja.']],
      porque: 'La curva se aplana cerca de 100 °C porque el calor se gasta en evaporar agua, no en calentar.' },

    /* ─────────── MEDIDA Y COSTES ─────────── */
    { id: 'pn_m_panadero', fam: 'med', n: 'Porcentaje panadero',
      d: function (K) { var s = ejes(K, 30, 120, 160, 100), D = [['Harina', 100, M.lino], ['Agua', 65, M.agua], ['Sal', 2, M.blanco], ['Levadura', 1, M.amarillo]]; D.forEach(function (x, i) { var h = x[1] * .92, X = 44 + i * 38; s += K.caja(X, 120 - h, 24, h, 6, x[2]) + K.t(X + 12, 116 - h - 4, x[1] + ' %', { s: 8, b: 1 }) + K.t(X + 12, 132, x[0], { s: 7 }); }); return s; },
      intro: 'Cada ingrediente se expresa como porcentaje del peso de la harina, que vale 100 %.',
      q: [['Con 2 kg de harina, ¿cuánta agua es el 65 %?', '1 300 g.'], ['¿Y cuánta sal al 2 %?', '40 g.'], ['¿Por qué los porcentajes suman más de 100 %?', 'Porque la harina es la base y el resto se suma encima.']],
      porque: 'Tomar la harina como base permite escalar la receta a cualquier tamaño sin recalcular proporciones.' },
    { id: 'pn_m_hidratacion', fam: 'med', n: 'Hidratación de la masa',
      d: function (K) { var s = '', D = [['60 %', 26, 24, 'firme'], ['70 %', 34, 17, 'suave'], ['80 %', 42, 11, 'muy blanda']]; D.forEach(function (x, i) { var X = 36 + i * 64; s += domo(K, X, 100, x[1], x[2], M.masa) + K.t(X, 120, x[0], { s: 10, b: 1 }) + K.t(X, 132, x[3], { s: 7.4 }); }); return s + K.caja(10, 100, 180, 4, 4, M.madera); },
      intro: 'La hidratación es el agua sobre la harina. Cuanta más agua, más se extiende la masa.',
      q: [['500 g de harina y 350 g de agua: ¿qué hidratación es?', '70 %.'], ['¿Qué pan se hace con 80 %?', 'Chapata o hogaza de miga abierta.'], ['¿Qué pan se hace con 55–60 %?', 'Pan de molde o bagels.']],
      porque: 'El agua suelta la red de gluten: más agua da masas extensibles y alveolos grandes.' },
    { id: 'pn_m_escandallo', fam: 'med', n: 'Escandallo de una barra',
      d: function (K) { var s = K.r(14, 18, 172, 116, 3, M.blanco), F = [['Ingrediente', 'g', 'Coste'], ['Harina', '150', '0,11'], ['Agua', '98', '0,00'], ['Sal', '3', '0,00'], ['Levadura', '2', '0,01'], ['Energía y mano de obra', '', '0,18'], ['Coste por barra', '', '0,30']]; F.forEach(function (f, i) { var y = 34 + i * 15; if (i) s += K.l('M20 ' + (y - 10) + ' H180', M.gris, { w: .5 }); s += K.t(22, y, f[0], { a: 'start', s: 7.2, b: i === 0 || i === 6 }) + K.t(122, y, f[1], { a: 'end', s: 7.2, b: i === 0 }) + K.t(176, y, f[2], { a: 'end', s: 7.2, b: i === 0 || i === 6 }); }); return s; },
      intro: 'El escandallo suma lo que cuesta cada ingrediente y cada gasto para una pieza.',
      q: [['Si la barra cuesta 0,30 y se vende a 1,00, ¿cuál es el margen?', '0,70 por barra, un 70 % del precio.'], ['¿Qué gasto pesa más que los ingredientes?', 'La energía y la mano de obra.'], ['¿Por qué el agua cuesta casi cero?', 'Su precio por litro es muy bajo frente a la harina.']],
      porque: 'Conocer el coste real por pieza permite fijar un precio que cubra todos los gastos.' },
    { id: 'pn_m_division', fam: 'med', n: 'Dividir y pesar',
      d: function (K) { var s = K.caja(14, 90, 72, 30, 10, M.blanco) + K.e(50, 86, 32, 6, M.metal) + domo(K, 50, 84, 26, 22, M.masa) + K.r(34, 100, 32, 12, 2, M.negro) + K.t(50, 109, '3 000 g', { s: 6.6, c: K.linea ? '#1B1B1B' : '#8CE08C' }) + K.flecha(92, 90, 108, 90, M.tinta); for (var i = 0; i < 10; i++) s += K.e(122 + (i % 5) * 16, 76 + Math.floor(i / 5) * 24, 7, 5, M.masa); return s + K.t(154, 124, '10 × 300 g', { s: 9, b: 1 }); },
      intro: 'Una masa de 3 kg se divide en diez piezas de 300 g.',
      q: [['¿Cuántas piezas de 250 g salen de 3 kg?', '12 piezas.'], ['¿Qué margen de error se admite al pesar?', 'Unos 5 g por pieza.'], ['¿Por qué la pieza cruda pesa más que el pan cocido?', 'En el horno pierde un 10–20 % de agua.']],
      porque: 'Pesar cada pieza garantiza el mismo tiempo de horno y el mismo peso para el cliente.' },
    { id: 'pn_m_temp_agua', fam: 'med', n: 'Calcular el agua',
      d: function (K) { return K.r(12, 26, 176, 98, 4, M.blanco) + K.t(100, 46, 'T agua = 3 × T masa − (T harina + T ambiente + fricción)', { s: 7.2, b: 1 }) + K.t(100, 70, '= 3 × 25 − (20 + 22 + 8)', { s: 9 }) + K.t(100, 94, '= 75 − 50 = 25 °C', { s: 11, b: 1 }) + K.t(100, 114, 'Fricción de amasadora ≈ 8 °C', { s: 6.8 }); },
      intro: 'Fórmula para saber a qué temperatura echar el agua y que la masa salga a 25 °C.',
      q: [['Si la harina está a 16 °C y el ambiente a 18 °C, ¿qué temperatura tendrá el agua?', '3 × 25 − (16 + 18 + 8) = 33 °C.'], ['¿Por qué se multiplica por 3?', 'Porque se suman tres factores: harina, ambiente y fricción.'], ['¿Qué se hace en verano si sale muy baja?', 'Usar agua fría o hielo.']],
      porque: 'La temperatura final de la masa es la media de lo que aporta cada elemento.' },
    { id: 'pn_m_cronograma', fam: 'med', n: 'Plan de producción',
      d: function (K) { var s = K.l('M12 80 H188', M.tinta, { w: 1.4 }), P = [['Amasar', 0, 20], ['Fermentar', 20, 90], ['Dividir', 110, 15], ['Reposo', 125, 20], ['Formar y levar', 145, 60], ['Hornear', 205, 25]], tot = 230; P.forEach(function (p, i) { var x = 12 + p[1] / tot * 176, w = p[2] / tot * 176; s += K.r(x, 66, w, 14, 1, [M.lino, M.masa, M.miga, M.masa, M.cortezaC, M.corteza][i]) + K.t(x + w / 2, i % 2 ? 100 : 56, p[0], { s: 6.6, b: 1 }); }); return s + K.t(12, 124, '0 h', { a: 'start', s: 7 }) + K.t(188, 124, '3 h 50 min', { a: 'end', s: 7 }); },
      intro: 'Orden y duración de cada paso para una hornada de barras.',
      q: [['¿Qué paso ocupa más tiempo?', 'La fermentación en bloque.'], ['Si se empieza a las 4:00, ¿a qué hora sale el pan?', 'Hacia las 7:50.'], ['¿Qué paso no admite retrasos?', 'El horneado: la masa lista no puede esperar.']],
      porque: 'Planificar hacia atrás desde la hora de venta dice a qué hora hay que empezar.' },
    { id: 'pn_m_rendimiento', fam: 'med', n: 'Piezas por bandeja',
      d: function (K) { var s = K.caja(20, 30, 160, 96, 6, M.acero); for (var i = 0; i < 6; i++) for (var j = 0; j < 4; j++) s += K.e(36 + i * 26, 46 + j * 22, 9, 7, M.corteza); return s + K.l('M20 134 H180', M.tinta, { w: .8 }) + K.t(100, 144, '60 cm', { s: 7.6, b: 1 }) + K.l('M190 30 V126', M.tinta, { w: .8 }) + K.t(192, 80, '40', { a: 'start', s: 7.6, b: 1 }); },
      intro: 'Una bandeja de 60 × 40 cm con panecillos de 60 g separados 3 cm.',
      q: [['¿Cuántos panecillos caben?', '24: 6 a lo largo y 4 a lo ancho.'], ['Si el horno tiene 5 bandejas, ¿cuántos salen por hornada?', '120 panecillos.'], ['¿Por qué se dejan 3 cm entre piezas?', 'Para que crezcan sin pegarse y el calor circule.']],
      porque: 'Conocer las piezas por bandeja permite calcular cuántas hornadas se necesitan para un pedido.' }
  ];
  MO.agregar('panaderia', L);
})();
