/* b6_lib_pasteleria3.js — Pastelería (3/3): masas y cremas base, técnicas, ciencia, medida y costes. 40 modelos.
   Cargar después de b6_lib_pasteleria2.js. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('ps_b_choux')) return;
  var M = MO.M;
  var C = { crema: '#F6E7C8', pastelera: '#F4D57A', merengue: '#FBF7EE', choco: '#5A3521', chocoC: '#8A5A3A', caramelo: '#C8832E', frambuesa: '#C7334F', pistacho: '#9DBF6A', limon: '#F2D14B', bizcocho: '#E8C27A', galleta: '#D9A45F', mantequilla: '#F5DD8A', nata: '#FFFDF7', huevo: '#F2B632', almendra: '#D9B98A' };
  function cuenco(K, cx, cy, rx, c) { return K.p('M' + (cx - rx) + ' ' + cy + ' Q' + (cx - rx + 3) + ' ' + (cy + rx * .8) + ' ' + cx + ' ' + (cy + rx * .8) + ' Q' + (cx + rx - 3) + ' ' + (cy + rx * .8) + ' ' + (cx + rx) + ' ' + cy + ' Z', c || M.ceramica) + K.e(cx, cy, rx, rx * .2, c || M.ceramica); }
  function num(K, n, x, y) { return K.c(x, y, 6.5, K.linea ? 'none' : M.rojo, { w: 1 }) + K.t(x, y + 2.8, n, { s: 7.6, b: 1, c: K.linea ? '#1B1B1B' : '#fff' }); }
  function ejes(K, x0, y0, w, h) { return K.l('M' + x0 + ' ' + (y0 - h) + ' V' + y0 + ' H' + (x0 + w), M.tinta, { w: 1.1 }); }
  function tabla(K, x, y, w, filas, anchos) { var s = K.r(x, y, w, filas.length * 14 + 8, 3, M.blanco); filas.forEach(function (f, i) { var yy = y + 16 + i * 14, xx = x + 6; if (i) s += K.l('M' + (x + 4) + ' ' + (yy - 10) + ' H' + (x + w - 4), M.gris, { w: .5 }); f.forEach(function (c, j) { var a = j ? 'end' : 'start', px = j ? xx + anchos.slice(0, j + 1).reduce(function (p, q) { return p + q; }, 0) - 6 : xx; s += K.t(px, yy, c, { a: a, s: 7, b: i === 0 || i === filas.length - 1 }); }); }); return s; }

  var L = [
    /* ─────────── MASAS Y CREMAS BASE ─────────── */
    { id: 'ps_b_choux', fam: 'bas', n: 'Pasta choux',
      d: function (K) { return K.suelo(70, 124, 54) + K.cil(70, 64, 50, 50, M.acero) + K.e(70, 65, 45, 11, C.crema) + K.l('M56 60 Q70 54 88 62', K.oscuro(C.crema, .2), { w: 1 }) + K.p('M96 30 L110 62 L104 64 L90 32 Z', M.madera) + K.flecha(128, 84, 146, 84, M.tinta) + K.c(170, 80, 14, C.galleta) + K.p('M158 78 Q170 70 182 78 Q170 76 158 78 Z', K.oscuro(C.galleta, .2)) + K.t(70, 138, 'Masa en el cazo', { s: 7 }) + K.t(170, 110, 'Hueca por dentro', { s: 7 }); },
      rot: [['Película en el fondo', 50, 90, 14, 110]],
      intro: 'Masa de agua, mantequilla, harina y huevo que se cuece primero en el cazo.',
      q: [['¿Por qué se seca la masa en el cazo antes del huevo?', 'Para quitarle agua y que absorba más huevo.'], ['¿Cuándo está lista?', 'Cuando forma una película fina en el fondo del cazo.'], ['¿Cómo se sabe que lleva suficiente huevo?', 'Cae de la espátula formando un pico en «V».']],
      porque: 'El almidón cocido retiene el huevo y el agua; en el horno ese agua infla la pieza.' },
    { id: 'ps_b_sablee', fam: 'bas', n: 'Masa sablée',
      d: function (K) { return K.caja(20, 96, 160, 22, 10, M.madera) + K.p('M40 96 Q42 70 70 66 Q100 60 130 66 Q158 70 160 96 Z', C.galleta) + K.puntos([[60, 84], [80, 78], [100, 74], [120, 80], [140, 86], [90, 88], [110, 90]], 1.6, K.claro(C.galleta, .4)) + K.r(128, 40, 50, 20, 3, C.mantequilla) + K.t(153, 54, 'Mantequilla fría', { s: 6.4 }); },
      rot: [['Textura arenosa', 100, 74, 60, 36]],
      intro: 'Masa de mantequilla, azúcar y harina que se mezcla poco: queda arenosa y quebradiza.',
      q: [['¿Qué significa «sablée»?', 'Arenosa, en francés.'], ['¿Por qué se trabaja poco?', 'Para no desarrollar gluten y que no encoja al hornear.'], ['¿Por qué reposa en frío?', 'Para que la mantequilla se endurezca y se pueda estirar.']],
      porque: 'La grasa recubre la harina y corta el gluten: la masa se deshace en migas.' },
    { id: 'ps_b_hojaldre', fam: 'bas', n: 'Hojaldre: las capas',
      d: function (K) { var s = ''; for (var i = 0; i < 9; i++) s += K.r(30, 40 + i * 8, 140, 4.4, 0, i % 2 ? C.mantequilla : C.bizcocho, { w: .6 }); return s + K.t(100, 130, 'Masa · mantequilla · masa · mantequilla…', { s: 7.6 }) + K.t(178, 44, 'masa', { a: 'start', s: 6.6 }) + K.t(178, 52, 'grasa', { a: 'start', s: 6.6 }); },
      intro: 'El hojaldre alterna láminas de masa y de mantequilla gracias a los pliegues.',
      q: [['¿Cuántas capas da un hojaldre de 6 pliegues sencillos?', 'Unas 729 capas de mantequilla (3 elevado a 6).'], ['¿Por qué se reposa en frío entre pliegues?', 'Para que la mantequilla no se funda y la masa se relaje.'], ['¿Qué hace subir el hojaldre sin levadura?', 'El vapor del agua de la masa y de la mantequilla.']],
      porque: 'Cada pliegue multiplica las capas; en el horno el vapor las separa como páginas.' },
    { id: 'ps_b_genoves', fam: 'bas', n: 'Bizcocho genovés',
      d: function (K) { var s = K.suelo(100, 126, 70) + K.cil(100, 62, 64, 52, C.bizcocho); [[70, 80], [96, 92], [126, 86], [84, 104], [116, 106], [140, 100], [60, 98]].forEach(function (p) { s += K.e(p[0], p[1], 3, 2, K.oscuro(C.bizcocho, .15)); }); return s + K.e(100, 62, 58, 13, K.oscuro(C.bizcocho, .15)); },
      rot: [['Miga fina', 96, 92, 30, 132], ['Corteza', 100, 56, 150, 30]],
      intro: 'Bizcocho de huevos batidos con azúcar, sin levadura: sube solo por el aire.',
      q: [['¿Qué le da volumen?', 'El aire batido en los huevos con azúcar.'], ['¿Cómo se añade la harina?', 'Tamizada y envuelta, sin batir.'], ['¿Qué pasa si se abre el horno pronto?', 'La espuma se enfría y el bizcocho se hunde.']],
      porque: 'El calor dilata las burbujas del huevo y luego cuaja sus paredes antes de que escape el aire.' },
    { id: 'ps_b_merengues', fam: 'bas', n: 'Tres merengues',
      d: function (K) { var s = '', D = [['Francés', 'clara + azúcar', 'crudo'], ['Suizo', 'al baño María', '50–60 °C'], ['Italiano', 'almíbar a 118 °C', 'el más estable']]; D.forEach(function (x, i) { var X = 36 + i * 64; s += cuenco(K, X, 86, 26) + K.p('M' + (X - 22) + ' 86 Q' + (X - 10) + ' ' + (58 - i * 4) + ' ' + X + ' ' + (52 - i * 4) + ' Q' + (X + 10) + ' ' + (58 - i * 4) + ' ' + (X + 22) + ' 86 Z', C.merengue) + K.t(X, 122, x[0], { s: 8.6, b: 1 }) + K.t(X, 132, x[1], { s: 6.4 }) + K.t(X, 141, x[2], { s: 6.4 }); }); return s; },
      intro: 'Tres formas de hacer merengue: sin calor, con calor suave o con almíbar caliente.',
      q: [['¿Qué merengue se usa para macarons y mousses?', 'El italiano.'], ['¿Cuál es el más sencillo?', 'El francés.'], ['¿Por qué el italiano es más estable?', 'El almíbar caliente cuece la clara.']],
      porque: 'Cuanto más cocida está la proteína de la clara, más firme y duradera es la espuma.' },
    { id: 'ps_b_pastelera', fam: 'bas', n: 'Crema pastelera',
      d: function (K) { return K.suelo(80, 124, 54) + K.cil(80, 70, 50, 44, M.acero) + K.e(80, 71, 45, 11, C.pastelera) + K.l('M60 68 Q80 60 100 70 Q84 76 64 72', K.oscuro(C.pastelera, .2), { w: 1 }) + K.p('M112 20 L100 70 L106 72 L118 22 Z', M.acero) + K.t(160, 50, 'Leche', { s: 7.4 }) + K.t(160, 62, 'Yemas', { s: 7.4 }) + K.t(160, 74, 'Azúcar', { s: 7.4 }) + K.t(160, 86, 'Maicena', { s: 7.4 }) + K.t(160, 104, 'Hervir 1 min', { s: 8, b: 1 }); },
      rot: [['Crema espesa', 60, 72, 20, 40]],
      intro: 'Crema de leche, yemas, azúcar y maicena que se cuece hasta espesar.',
      q: [['¿Por qué esta crema sí debe hervir?', 'La maicena necesita hervir para espesar y protege a las yemas.'], ['¿Cómo se evita la costra al enfriar?', 'Con film pegado a la superficie.'], ['¿A qué temperatura se guarda?', 'En nevera, por debajo de 4 °C, y se usa en 2 días.']],
      porque: 'El almidón rodea las proteínas del huevo y no deja que se unan en grumos al hervir.' },
    { id: 'ps_b_ganache', fam: 'bas', n: 'Ganache',
      d: function (K) { return cuenco(K, 70, 84, 46) + K.e(70, 84, 40, 7, C.choco) + K.l('M44 84 Q70 76 96 86', C.chocoC, { w: 1.6 }) + K.t(150, 50, 'Chocolate', { s: 8, b: 1 }) + K.t(150, 62, '+ nata caliente', { s: 7.4 }) + K.t(150, 84, 'Firme  2 : 1', { s: 7.4 }) + K.t(150, 96, 'Para cubrir  1 : 1', { s: 7.4 }) + K.t(150, 108, 'Blanda  1 : 2', { s: 7.4 }); },
      rot: [['Emulsión brillante', 70, 84, 30, 30]],
      intro: 'Emulsión de chocolate y nata; su proporción decide si es firme, cubriente o blanda.',
      q: [['¿Qué proporción se usa para trufas?', 'Dos de chocolate por una de nata.'], ['¿Qué pasa si se corta?', 'Se separa la grasa; se recupera con un poco de nata tibia y batiendo.'], ['¿A qué temperatura se añade la nata?', 'Recién hervida, a unos 80–90 °C.']],
      porque: 'La nata aporta agua y grasa; el chocolate las une como una mayonesa dulce.' },
    { id: 'ps_b_inglesa', fam: 'bas', n: 'Crema inglesa',
      d: function (K) { return K.suelo(70, 124, 54) + K.cil(70, 70, 50, 44, M.acero) + K.e(70, 71, 45, 11, C.crema) + K.p('M110 22 L100 70 L106 72 L116 24 Z', M.madera) + K.p('M130 40 L186 40 L186 90 L130 90 Z', C.crema) + K.l('M136 50 Q158 42 180 52', 'none') + K.l('M134 66 H182', M.tinta, { w: 1.2 }) + K.t(158, 104, 'Punto nappe', { s: 7, b: 1 }) + K.t(158, 114, 'la raya no se cierra', { s: 6.4 }) + K.t(70, 138, '82–84 °C', { s: 9, b: 1 }); },
      rot: [['Cuchara napada', 158, 66, 158, 20]],
      intro: 'Crema de leche, yemas y azúcar cocida sin hervir hasta que napa la cuchara.',
      q: [['¿A qué temperatura se retira del fuego?', 'Entre 82 y 84 °C.'], ['¿Qué pasa si hierve?', 'La yema cuaja en grumos y la crema se corta.'], ['¿Cómo se comprueba el punto nappe?', 'Pasando el dedo por la cuchara: la raya no se cierra.']],
      porque: 'Sin almidón, nada protege a la yema: pasados los 85 °C sus proteínas se aprietan.' },
    { id: 'ps_b_caramelo', fam: 'bas', n: 'Caramelo en seco',
      d: function (K) { var s = '', D = [['#F7F2E6', 'Azúcar'], ['#F0D79B', '150 °C'], ['#D9A04A', '165 °C'], ['#A8621F', '175 °C'], ['#5A2E10', 'Quemado']]; D.forEach(function (d, i) { var x = 24 + i * 38; s += K.cil(x, 58, 16, 22, M.acero) + K.e(x, 59, 13, 3.6, d[0]) + K.t(x, 102, d[1], { s: 7, b: 1 }); }); return s + K.flecha(20, 118, 184, 118, M.rojo, { w: 1.2 }) + K.t(100, 134, 'Del rubio al oscuro en menos de un minuto', { s: 7 }); },
      intro: 'El azúcar solo, al calentarse, se funde y cambia de color y de sabor.',
      q: [['¿A qué temperatura empieza a colorear?', 'Hacia 150–160 °C.'], ['¿Cómo se detiene la cocción?', 'Sumergiendo la base del cazo en agua fría.'], ['¿Qué sabor tiene el caramelo pasado?', 'Amargo.']],
      porque: 'Con calor, la sacarosa se rompe en cientos de moléculas nuevas que dan color y aroma.' },
    { id: 'ps_b_pralin', fam: 'bas', n: 'Praliné',
      d: function (K) { var s = K.caja(14, 92, 70, 8, 8, M.acero); [[26, 86], [40, 82], [56, 86], [70, 82], [34, 90], [62, 90]].forEach(function (p) { s += K.e(p[0], p[1], 6, 4, C.almendra); }); s += K.l('M20 88 Q50 76 80 88', C.caramelo, { w: 3, op: .8 }) + K.flecha(92, 90, 110, 90, M.tinta) + K.caja(116, 60, 50, 50, 12, M.blanco).replace('', '') + K.p('M122 104 L160 104 L160 84 Q141 78 122 84 Z', '#B8793B'); return s + K.t(50, 122, 'Frutos secos + caramelo', { s: 7 }) + K.t(141, 122, 'Molido: pasta', { s: 7 }); },
      intro: 'Frutos secos cubiertos de caramelo y molidos hasta formar una pasta.',
      q: [['¿Qué frutos secos lleva el praliné clásico?', 'Almendras y avellanas.'], ['¿Por qué se vuelve líquido al molerlo tanto?', 'Suelta el aceite de los frutos secos.'], ['¿En qué postres se usa?', 'París-Brest, bombones, cremas y mousses.']],
      porque: 'Al moler, se rompen las células del fruto seco y su aceite convierte el polvo en pasta.' },

    /* ─────────── TÉCNICAS ─────────── */
    { id: 'ps_p_picos', fam: 'pro', n: 'Punto de las claras',
      d: function (K) { var s = '', D = [['Espuma', 10, 1], ['Pico blando', 22, 2], ['Pico firme', 32, 3]]; D.forEach(function (x, i) { var X = 36 + i * 64; s += K.r(X - 4, 30, 8, 30, 4, M.acero) + K.p('M' + (X - 12) + ' 60 Q' + X + ' ' + (60 + x[1]) + ' ' + (X + 12) + ' 60 Z', C.merengue) + (i === 1 ? K.p('M' + (X + 2) + ' ' + (60 + x[1]) + ' q6 -4 8 -12', 'none', { w: 1 }) : '') + cuenco(K, X, 100, 26) + K.e(X, 100, 22, 4, C.merengue) + K.t(X, 136, x[0], { s: 8, b: 1 }); }); return s; },
      intro: 'Tres puntos al montar claras, mirando el pico que queda en las varillas.',
      q: [['¿Qué punto se busca para el merengue de macarons?', 'Pico firme.'], ['¿Por qué el bol debe estar sin grasa?', 'La grasa impide que la espuma se forme.'], ['¿Cuándo se añade el azúcar?', 'Poco a poco, cuando la clara ya espuma.']],
      porque: 'Al batir, las proteínas de la clara se estiran y forman paredes alrededor del aire.' },
    { id: 'ps_p_cinta', fam: 'pro', n: 'Punto de cinta',
      d: function (K) { return cuenco(K, 100, 96, 56) + K.e(100, 96, 50, 9, C.huevo) + K.r(96, 18, 8, 34, 4, M.acero) + K.p('M92 52 Q100 56 108 52 L104 94 Q100 98 96 94 Z', C.huevo, { op: .9 }) + K.l('M70 94 Q84 90 96 96 Q110 102 124 96 Q138 90 146 96', K.oscuro(C.huevo, .25), { w: 2 }) + K.t(100, 150, 'La mezcla cae y dibuja una cinta', { s: 7.4 }); },
      rot: [['Cinta que se mantiene', 130, 96, 176, 70]],
      intro: 'Huevos y azúcar batidos hasta que al caer forman una cinta que tarda en borrarse.',
      q: [['¿Cuánto tiempo se bate hasta el punto de cinta?', 'Unos 8–10 minutos a velocidad alta.'], ['¿Qué color toma la mezcla?', 'Pasa de amarilla a casi blanca.'], ['¿Para qué masa es clave?', 'Para el bizcocho genovés.']],
      porque: 'El azúcar disuelto espesa la espuma de huevo y la hace estable.' },
    { id: 'ps_p_templado', fam: 'pro', n: 'Curva de templado',
      d: function (K) { var s = ejes(K, 26, 120, 164, 100) + K.l('M26 34 L80 34 L110 84 L140 64 L186 64', C.chocoC, { w: 2.4 }); [['50 °C', 34], ['31 °C', 64], ['27 °C', 84]].forEach(function (x) { s += K.l('M22 ' + x[1] + ' H190', M.gris, { d: '2 3', w: .6 }) + K.t(20, x[1] + 2.5, x[0], { a: 'end', s: 6.6 }); }); return s + K.t(52, 28, 'Fundir', { s: 7, b: 1 }) + K.t(110, 96, 'Enfriar', { s: 7, b: 1 }) + K.t(160, 58, 'Trabajar', { s: 7, b: 1 }) + K.t(108, 136, 'Chocolate negro', { s: 7.4 }); },
      intro: 'El chocolate negro se funde a 50 °C, se enfría a 27 °C y se trabaja a 31 °C.',
      q: [['¿Por qué se enfría por debajo de la temperatura de trabajo?', 'Para formar cristales estables que guíen al resto.'], ['¿Qué pasa si se supera 32 °C al volver a calentar?', 'Se funden los cristales buenos y hay que repetir.'], ['¿Cómo se comprueba el templado?', 'Una tira sobre papel debe endurecer brillante en 5 minutos.']],
      porque: 'Solo el cristal tipo V de la manteca de cacao da brillo y chasquido; la curva lo selecciona.' },
    { id: 'ps_p_bano_maria', fam: 'pro', n: 'Baño María',
      d: function (K) { var s = K.suelo(100, 132, 80) + K.cil(100, 70, 72, 54, M.acero) + K.e(100, 71, 66, 14, M.agua) + cuenco(K, 100, 56, 50, M.vidrio) + K.e(100, 56, 44, 9, C.choco); for (var i = 0; i < 4; i++) s += K.p('M' + (52 + i * 30) + ' 90 q4 -6 0 -10', 'none', { w: 1 }); return s; },
      rot: [['Agua caliente', 160, 80, 186, 104], ['Chocolate', 100, 56, 150, 26]],
      intro: 'Un recipiente sobre agua caliente: el calor llega suave y nunca pasa de 100 °C.',
      q: [['¿Por qué no debe tocar el agua el bol de arriba?', 'Se calentaría demasiado y quemaría el chocolate.'], ['¿Qué pasa si cae vapor en el chocolate?', 'Se espesa y se vuelve granuloso.'], ['¿Qué postres se hornean al baño María?', 'Flanes, tartas de queso y cremas.']],
      porque: 'El agua no supera los 100 °C: es un límite de temperatura natural.' },
    { id: 'ps_p_encamisar', fam: 'pro', n: 'Encamisar un molde',
      d: function (K) { var s = ''; [['Engrasar', M.mantequilla], ['Enharinar', M.harina], ['Sacudir', 'none']].forEach(function (x, i) { var X = 36 + i * 64; s += K.cil(X, 60, 26, 32, M.metal, { abierto: 1 }) + (x[1] !== 'none' ? K.e(X, 62, 22, 5, x[1], { op: .9 }) : '') + num(K, String(i + 1), X, 40) + K.t(X, 118, x[0], { s: 8, b: 1 }); }); return s + K.flecha(150, 70, 186, 76, M.tinta, { curva: [170, 56] }); },
      intro: 'Tres pasos para que el bizcocho no se pegue: grasa, harina y sacudir el exceso.',
      q: [['¿Con qué se engrasa?', 'Con mantequilla pomada, con pincel.'], ['¿Qué se usa en lugar de harina en un bizcocho de chocolate?', 'Cacao, para que no queden manchas blancas.'], ['¿Por qué se sacude el molde?', 'Para dejar solo una capa fina.']],
      porque: 'La capa de grasa y harina separa la masa del metal y se despega al enfriar.' },
    { id: 'ps_p_forrar', fam: 'pro', n: 'Forrar una tartaleta',
      d: function (K) { return K.e(46, 80, 34, 10, C.galleta) + K.t(46, 108, 'Estirar 3 mm', { s: 7.4 }) + K.flecha(84, 80, 100, 80, M.tinta) + K.cil(136, 70, 34, 20, M.metal, { abierto: 1 }) + K.e(136, 70, 30, 7, C.galleta) + K.p('M106 70 Q108 60 118 58 L118 70 Z', C.galleta) + K.p('M166 70 Q164 60 154 58 L154 70 Z', C.galleta) + K.r(160, 40, 30, 6, 3, M.acero) + K.t(136, 108, 'Cortar el exceso', { s: 7.4 }); },
      rot: [['Masa sobrante', 112, 60, 86, 36]],
      intro: 'La masa se estira fina, se ajusta al molde por dentro y se corta el borde sobrante.',
      q: [['¿Qué grosor tiene la masa?', 'Unos 3 mm.'], ['¿Por qué se pincha el fondo?', 'Para que el aire salga y no se levante.'], ['¿Por qué se enfría antes de hornear?', 'Para que no encoja en el horno.']],
      porque: 'Una masa fría y relajada mantiene la forma del molde al hornearse.' },
    { id: 'ps_p_glasear', fam: 'pro', n: 'Verter un glaseado',
      d: function (K) { return K.suelo(100, 136, 70) + K.cil(100, 120, 60, 8, M.acero) + K.cil(100, 70, 46, 44, '#8C3A62') + K.p('M100 20 Q106 30 102 50 L98 50 Q94 30 100 20 Z', '#8C3A62') + K.cil(100, 14, 20, 8, M.metal, { abierto: 1 }) + K.l('M58 94 Q60 108 62 116 M142 94 Q140 108 138 116', '#8C3A62', { w: 2 }) + K.t(170, 70, '32 °C', { s: 10, b: 1 }); },
      rot: [['Tarta congelada', 60, 80, 20, 60], ['Rejilla', 150, 122, 184, 144]],
      intro: 'El glaseado se vierte de una vez sobre la tarta congelada colocada en una rejilla.',
      q: [['¿Por qué se vierte desde el centro?', 'Para que cubra por igual hacia todos los lados.'], ['¿Qué se hace con el exceso?', 'Se recoge debajo, se cuela y se reutiliza.'], ['¿Se puede retocar con la espátula?', 'Solo una pasada rápida; si no, pierde el brillo.']],
      porque: 'Al tocar la superficie congelada, la gelatina cuaja al instante en una capa fina.' },
    { id: 'ps_p_manga', fam: 'pro', n: 'Rellenar la manga',
      d: function (K) { return K.cil(60, 40, 30, 80, M.vidrio, { abierto: 1 }).replace(/opacity="[^"]*"/g, '') + K.p('M44 30 L76 30 L66 110 L54 110 Z', '#F1ECE3') + K.p('M36 30 Q60 20 84 30 L84 36 Q60 28 36 36 Z', '#E4DCCD') + K.p('M50 50 L70 50 L66 104 L54 104 Z', C.crema) + K.flecha(98, 80, 118, 80, M.tinta) + K.p('M124 60 Q120 80 124 100 L180 84 L180 76 Z', '#F1ECE3') + K.p('M128 66 Q126 80 128 94 L160 84 L160 76 Z', C.crema) + K.t(60, 142, 'Doblar sobre un vaso', { s: 7 }) + K.t(152, 118, 'Girar y apretar', { s: 7 }); },
      intro: 'La manga se dobla sobre un vaso alto para llenarla sin mancharse.',
      q: [['¿Por qué se dobla el borde hacia fuera?', 'Para que la crema no manche la parte que se sujeta.'], ['¿Cómo se quita el aire?', 'Empujando la crema hacia la punta antes de cerrar.'], ['¿Qué pasa si se llena demasiado?', 'Sale crema por arriba y cuesta controlarla.']],
      porque: 'Sin aire dentro, la presión de la mano llega entera a la boquilla.' },
    { id: 'ps_p_rosetas', fam: 'pro', n: 'Hacer rosetas',
      d: function (K) { var s = ''; [['1', 'Vertical', 40], ['2', 'Apretar y girar', 100], ['3', 'Soltar y subir', 160]].forEach(function (x, i) { s += num(K, x[0], x[2], 30) + K.t(x[2], 128, x[1], { s: 7.4, b: 1 }); }); s += K.pl([[34, 48], [46, 48], [42, 84], [38, 84]], M.metal) + K.e(40, 98, 12, 4, C.nata); s += K.c(100, 92, 16, C.nata) + K.l('M100 92 m-12 0 a12 5 0 1 0 24 0 a9 4 0 1 0 -18 0', K.oscuro(C.nata, .2), { w: 1 }); s += K.p('M146 104 Q146 82 160 80 Q174 82 174 104 Z', C.nata) + K.l('M152 100 Q156 86 160 80 M168 100 Q164 86 160 80', K.oscuro(C.nata, .2), { w: 1 }) + K.flecha(160, 76, 160, 58, M.rojo, { w: 1 }); return s; },
      intro: 'Una roseta se hace con la manga vertical, apretando mientras se gira y soltando al subir.',
      q: [['¿A qué altura se sujeta la boquilla?', 'A 1 cm de la superficie.'], ['¿Qué deja la punta limpia al terminar?', 'Dejar de apretar antes de levantar.'], ['¿Qué boquilla se usa?', 'Una rizada o de estrella.']],
      porque: 'Cortar la presión antes de subir corta la crema y deja un pico limpio.' },
    { id: 'ps_p_cremar', fam: 'pro', n: 'Cremar mantequilla',
      d: function (K) { return cuenco(K, 70, 90, 50) + K.p('M26 90 Q40 70 70 72 Q100 70 114 90 Z', C.mantequilla) + K.l('M40 84 Q70 74 100 86', K.oscuro(C.mantequilla, .2), { w: 1 }) + K.t(150, 50, 'Mantequilla a 18–20 °C', { s: 7.4, b: 1 }) + K.t(150, 64, '+ azúcar', { s: 7.4 }) + K.t(150, 84, 'Batir hasta blanquear', { s: 7.4 }) + K.t(150, 98, '3–5 minutos', { s: 7.4 }); },
      rot: [['Mezcla pálida y esponjosa', 70, 76, 30, 40]],
      intro: 'Batir mantequilla blanda con azúcar para meterle aire antes de añadir huevos y harina.',
      q: [['¿Qué temperatura debe tener la mantequilla?', 'Entre 18 y 20 °C: blanda pero no derretida.'], ['¿Por qué se blanquea?', 'Los cristales de azúcar abren burbujas de aire en la grasa.'], ['¿Qué pasa si los huevos están fríos?', 'La mezcla se corta.']],
      porque: 'Los cantos de los cristales de azúcar hacen agujeros en la grasa donde queda el aire.' },
    { id: 'ps_p_cortar_capas', fam: 'pro', n: 'Cortar el bizcocho en capas',
      d: function (K) { return K.suelo(100, 128, 76) + K.cil(100, 64, 64, 54, C.bizcocho) + K.l('M36 82 Q100 96 164 82 M36 100 Q100 114 164 100', K.oscuro(C.bizcocho, .3), { w: 1, d: '4 3' }) + K.p('M10 80 L150 80 L150 86 L10 86 Z', M.metal) + K.r(150, 78, 40, 10, 5, M.negro) + K.flecha(30, 72, 60, 72, M.rojo, { w: 1 }); },
      rot: [['Marca de corte', 100, 104, 150, 136]],
      intro: 'El bizcocho frío se corta en discos iguales girándolo contra un cuchillo largo.',
      q: [['¿Por qué se marca primero todo el contorno?', 'Para que el corte sea recto y a la misma altura.'], ['¿Qué cuchillo se usa?', 'Uno largo de sierra.'], ['¿Por qué el bizcocho debe estar frío?', 'Caliente se desmiga y se aplasta.']],
      porque: 'Girando el bizcocho, el cuchillo avanza poco a poco y no se desvía.' },
    { id: 'ps_p_emulsionar', fam: 'pro', n: 'Emulsionar con túrmix',
      d: function (K) { return K.suelo(80, 134, 44) + K.p('M50 50 L110 50 L106 128 L54 128 Z', M.vidrio, { op: .5 }) + K.r(54, 74, 52, 52, 2, C.choco) + K.r(74, 10, 12, 86, 4, M.metal) + K.r(64, 4, 32, 26, 6, M.blanco) + K.p('M68 96 L92 96 L88 108 L72 108 Z', M.acero) + K.t(150, 70, 'Cuchilla sumergida', { s: 7.4, b: 1 }) + K.t(150, 84, 'Sin hacer burbujas', { s: 7.4 }); },
      rot: [['Ganache', 64, 110, 24, 138]],
      intro: 'Con la túrmix sumergida, la ganache queda lisa, brillante y sin grumos.',
      q: [['¿Por qué la cuchilla no debe salir a la superficie?', 'Metería aire y burbujas.'], ['¿Qué se consigue frente a mezclar con espátula?', 'Una emulsión más fina y estable.'], ['¿Qué recipiente conviene?', 'Uno alto y estrecho.']],
      porque: 'La cuchilla divide la grasa en gotas diminutas que el agua de la nata mantiene separadas.' },

    /* ─────────── CIENCIA ─────────── */
    { id: 'ps_c_puntos_azucar', fam: 'cie', n: 'Puntos del azúcar',
      d: function (K) { var s = '', D = [['Hebra', '105'], ['Bola blanda', '116'], ['Bola dura', '124'], ['Lámina', '145'], ['Caramelo', '160+']]; D.forEach(function (d, i) { var y = 24 + i * 22; s += K.r(20, y, 12, 14, 3, [C.merengue, '#F7EFD8', '#F2E2B8', '#E9C98A', C.caramelo][i]) + K.t(40, y + 10, d[0], { a: 'start', s: 8, b: 1 }) + K.t(180, y + 10, d[1] + ' °C', { a: 'end', s: 8 }); }); return s + K.l('M110 24 V132', M.gris, { d: '2 3', w: .6 }); },
      intro: 'La temperatura del almíbar dice qué textura tendrá al enfriarse.',
      q: [['¿Qué punto se usa para el merengue italiano?', 'Bola blanda, a unos 118 °C.'], ['¿Qué pasa con el agua al subir la temperatura?', 'Se evapora: cada grado más, menos agua.'], ['¿Cómo se comprobaba sin termómetro?', 'Dejando caer una gota en agua fría y tocándola.']],
      porque: 'El punto de ebullición sube cuanto más concentrado está el azúcar.' },
    { id: 'ps_c_cristales', fam: 'cie', n: 'Cristales del chocolate',
      d: function (K) { var s = ''; [['Mal templado', 44, false], ['Templado', 150, true]].forEach(function (x) { s += K.r(x[1] - 38, 30, 76, 60, 4, C.choco); for (var i = 0; i < 12; i++) { var cx = x[1] - 30 + (i % 4) * 20, cy = 40 + Math.floor(i / 4) * 18; s += x[2] ? K.pl([[cx, cy], [cx + 10, cy], [cx + 10, cy + 8], [cx, cy + 8]], C.chocoC, { w: .6 }) : K.pl([[cx, cy + (i % 3) * 2], [cx + 6 + (i % 2) * 6, cy], [cx + 12, cy + 8], [cx + 2, cy + 10]], C.chocoC, { w: .6 }); } s += K.t(x[1], 108, x[0], { s: 8, b: 1 }); }); return s + K.t(44, 120, 'Mate, se funde', { s: 7 }) + K.t(150, 120, 'Brilla y cruje', { s: 7 }); },
      intro: 'La manteca de cacao puede cristalizar de seis formas; solo una da buen chocolate.',
      q: [['¿Qué forma cristalina se busca?', 'La forma V.'], ['¿Qué son las vetas blancas en un chocolate viejo?', 'Grasa o azúcar que salieron a la superficie.'], ['¿Por qué cruje el chocolate templado?', 'Sus cristales son ordenados y compactos.']],
      porque: 'Cristales iguales y ordenados reflejan la luz y se rompen en seco.' },
    { id: 'ps_c_espuma', fam: 'cie', n: 'Por qué sube la clara',
      d: function (K) { var s = ''; [[50, 60, 22], [110, 50, 18], [150, 90, 20], [80, 100, 16], [130, 30, 12]].forEach(function (b) { s += K.c(b[0], b[1], b[2], M.vidrio, { op: .5 }); for (var i = 0; i < 10; i++) { var a = i * Math.PI / 5; s += K.l('M' + (b[0] + Math.cos(a) * b[2]).toFixed(1) + ' ' + (b[1] + Math.sin(a) * b[2]).toFixed(1) + ' l' + (Math.cos(a) * 4).toFixed(1) + ' ' + (Math.sin(a) * 4).toFixed(1), C.huevo, { w: 1.4 }); } }); return s + K.t(100, 140, 'Proteínas desplegadas rodean el aire', { s: 7.4 }); },
      rot: [['Burbuja', 50, 60, 16, 20], ['Proteína', 72, 60, 30, 130]],
      intro: 'Al batir, las proteínas de la clara se despliegan y rodean cada burbuja de aire.',
      q: [['¿Por qué una gota de yema impide montar la clara?', 'Su grasa se coloca donde deberían ir las proteínas.'], ['¿Qué ayuda a estabilizar la espuma?', 'El azúcar, unas gotas de limón o crémor tártaro.'], ['¿Qué pasa si se bate de más?', 'Las proteínas se aprietan, la espuma se granula y suelta agua.']],
      porque: 'Una parte de la proteína busca el agua y otra el aire: se colocan justo en la pared de la burbuja.' },
    { id: 'ps_c_huevo', fam: 'cie', n: 'El huevo cuaja por partes',
      d: function (K) { var s = ejes(K, 26, 118, 164, 96); [['Clara empieza', 62, 60], ['Yema cuaja', 70, 88], ['Clara firme', 80, 116], ['Crema cortada', 85, 150]].forEach(function (x) { var X = 26 + (x[1] - 50) * 4.4; s += K.l('M' + X + ' 118 V' + (118 - (x[1] - 50) * 2.4), C.huevo, { w: 6 }) + K.t(X, 124 + 10, x[1] + ' °C', { s: 6.8, b: 1 }) + K.t(X, 112 - (x[1] - 50) * 2.4, x[0], { s: 6.4 }); }); return s; },
      intro: 'Cada proteína del huevo cuaja a una temperatura distinta.',
      q: [['¿Por qué la crema inglesa se retira a 84 °C?', 'Poco más arriba la yema se aprieta y se corta.'], ['¿Qué cuaja primero, la clara o la yema?', 'La clara empieza antes, hacia 62 °C.'], ['¿Qué hace el azúcar con esas temperaturas?', 'Las sube: protege al huevo.']],
      porque: 'El azúcar se interpone entre las proteínas y retrasa que se unan.' },
    { id: 'ps_c_gelificantes', fam: 'cie', n: 'Gelatina, agar y pectina',
      d: function (K) { var s = '', D = [['Gelatina', 'Animal', 'se funde a 35 °C', '#F2D3A0'], ['Agar-agar', 'Alga', 'aguanta 80 °C', '#DDEBC9'], ['Pectina', 'Fruta', 'necesita azúcar y ácido', '#F2B7B7']]; D.forEach(function (d, i) { var X = 36 + i * 64; s += K.caja(X - 22, 50, 40, 36, 12, d[3]) + K.t(X, 104, d[0], { s: 8.4, b: 1 }) + K.t(X, 115, d[1], { s: 7 }) + K.t(X, 126, d[2], { s: 6.2 }); }); return s; },
      intro: 'Tres gelificantes comunes y lo que los distingue.',
      q: [['¿Cuál sirve para postres veganos?', 'El agar-agar, que viene de algas.'], ['¿Qué gelificante lleva la mermelada?', 'La pectina.'], ['¿Por qué la gelatina se deshace en la boca?', 'Se funde a menos de la temperatura del cuerpo.']],
      porque: 'Sus cadenas largas atrapan el agua en una red; cada una se forma y se funde a su temperatura.' },
    { id: 'ps_c_caramel_maillard', fam: 'cie', n: 'Caramelización y Maillard',
      d: function (K) { return K.r(14, 30, 80, 70, 4, M.blanco) + K.cil(54, 50, 20, 20, M.acero) + K.e(54, 51, 17, 4, C.caramelo) + K.t(54, 88, 'Solo azúcar', { s: 7.4 }) + K.t(54, 118, 'Caramelización', { s: 8, b: 1 }) + K.t(54, 128, 'desde 160 °C', { s: 7 }) + K.r(106, 30, 80, 70, 4, M.blanco) + K.e(146, 62, 26, 12, C.galleta) + K.t(146, 88, 'Azúcar + proteína', { s: 7.4 }) + K.t(146, 118, 'Reacción de Maillard', { s: 8, b: 1 }) + K.t(146, 128, 'desde 140 °C', { s: 7 }); },
      intro: 'Dos reacciones que dan color: una solo con azúcar y otra con azúcar y proteína.',
      q: [['¿Qué reacción dora una galleta?', 'La de Maillard, porque hay proteínas de la harina y la mantequilla.'], ['¿Qué reacción ocurre en un caramelo de solo azúcar?', 'La caramelización.'], ['¿Qué acelera la reacción de Maillard?', 'Un medio poco ácido y más temperatura.']],
      porque: 'Las dos reacciones crean cientos de moléculas nuevas: por eso el tostado sabe distinto al crudo.' },
    { id: 'ps_c_emulsion', fam: 'cie', n: 'Emulsión',
      d: function (K) { var s = K.r(14, 30, 80, 80, 4, M.agua, { op: .6 }) + K.r(14, 30, 80, 24, 4, C.mantequilla) + K.t(54, 126, 'Separada', { s: 8, b: 1 }) + K.r(106, 30, 80, 80, 4, M.agua, { op: .6 }); [[118, 44], [130, 60], [150, 50], [170, 66], [124, 80], [146, 90], [166, 96], [140, 70], [176, 44], [116, 100]].forEach(function (p) { s += K.c(p[0], p[1], 4, C.mantequilla); }); return s + K.t(146, 126, 'Emulsionada', { s: 8, b: 1 }); },
      rot: [['Gota de grasa', 150, 50, 150, 16]],
      intro: 'Grasa y agua no se mezclan; batiendo con un emulsionante quedan en gotas muy finas.',
      q: [['¿Qué emulsionante natural tiene la yema?', 'La lecitina.'], ['¿Qué emulsiones hay en pastelería?', 'Ganache, buttercream y crema inglesa, entre otras.'], ['¿Qué pasa si una emulsión se corta?', 'La grasa se separa y la textura queda grasienta.']],
      porque: 'El emulsionante tiene una parte que busca el agua y otra la grasa: une las dos fases.' },
    { id: 'ps_c_vapor_hojaldre', fam: 'cie', n: 'El vapor levanta el hojaldre',
      d: function (K) { var s = ''; for (var i = 0; i < 6; i++) { s += K.r(20, 40 + i * 12, 60, 3, 0, C.bizcocho, { w: .5 }) + K.r(20, 43 + i * 12, 60, 2, 0, C.mantequilla, { w: .4 }); s += K.r(120, 24 + i * 20, 60, 3, 0, C.galleta, { w: .5 }); if (i < 5) s += K.p('M' + (140 + (i % 2) * 14) + ' ' + (38 + i * 20) + ' q3 -4 0 -8', 'none', { w: .9 }); } return s + K.flecha(88, 72, 110, 72, M.tinta) + K.t(50, 128, 'Crudo', { s: 8, b: 1 }) + K.t(150, 142, 'Horneado', { s: 8, b: 1 }); },
      intro: 'En el horno, el agua de cada capa se vuelve vapor y separa las láminas.',
      q: [['¿Qué pasa si la mantequilla se funde antes de hornear?', 'Las capas se unen y el hojaldre no sube.'], ['¿Por qué se hornea a más de 200 °C?', 'El vapor debe formarse de golpe.'], ['¿Qué parte se dora?', 'La masa, por la reacción de Maillard.']],
      porque: 'El agua al convertirse en vapor ocupa unas 1 600 veces más volumen.' },
    { id: 'ps_c_azucares', fam: 'cie', n: 'Tipos de azúcar',
      d: function (K) { var s = '', D = [['Blanco', '#FFFFFF'], ['Glas', '#FBFBFB'], ['Moreno', '#B77A3A'], ['Invertido', '#F2DE9C'], ['Glucosa', '#F4F1E6']]; D.forEach(function (d, i) { var X = 24 + i * 38; s += cuenco(K, X, 84, 16) + K.e(X, 84, 13, 3, d[1]) + K.t(X, 118, d[0], { s: 7.4, b: 1 }); }); return s + K.t(100, 138, 'Cambian el dulzor, la humedad y el color', { s: 7.2 }); },
      intro: 'Cinco azúcares de obrador: cada uno cambia el dulzor, la humedad y el color.',
      q: [['¿Qué azúcar mantiene tierno un bizcocho más días?', 'El invertido, que retiene humedad.'], ['¿Por qué se usa glucosa en glaseados?', 'Evita que el azúcar cristalice y da brillo.'], ['¿Qué lleva el azúcar moreno?', 'Restos de melaza.']],
      porque: 'Los azúcares que atraen agua del aire mantienen las masas húmedas más tiempo.' },
    { id: 'ps_c_gluten_bizcocho', fam: 'cie', n: 'Poco gluten, bizcocho tierno',
      d: function (K) { var s = K.r(14, 30, 80, 70, 4, C.bizcocho); for (var i = 0; i < 4; i++) s += K.l('M20 ' + (42 + i * 16) + ' Q54 ' + (34 + i * 16) + ' 88 ' + (44 + i * 16), '#8E4F1E', { w: 2 }); s += K.r(106, 30, 80, 70, 4, C.bizcocho); for (var j = 0; j < 4; j++) s += K.l('M' + (114 + j * 16) + ' ' + (44 + j * 10) + ' l10 4', '#8E4F1E', { w: 1.4 }); return s + K.t(54, 118, 'Mucho amasado', { s: 7.6, b: 1 }) + K.t(54, 128, 'duro y con túneles', { s: 7 }) + K.t(146, 118, 'Mezclado justo', { s: 7.6, b: 1 }) + K.t(146, 128, 'tierno', { s: 7 }); },
      intro: 'En pastelería se busca poco gluten: la harina se mezcla lo justo.',
      q: [['¿Qué harina se usa para bizcochos?', 'Harina floja, de poca proteína.'], ['¿Qué causa túneles en una magdalena?', 'Mezclar demasiado la masa.'], ['¿Por qué se añade la harina al final?', 'Para mezclarla el menor tiempo posible.']],
      porque: 'Cuanto menos se trabaja la harina, menos red de gluten y más tierna la miga.' },

    /* ─────────── MEDIDA Y COSTES ─────────── */
    { id: 'ps_m_escandallo', fam: 'med', n: 'Escandallo de una tarta',
      d: function (K) { return tabla(K, 14, 16, 172, [['Ingrediente', 'Cant.', 'Coste'], ['Harina', '200 g', '0,20'], ['Huevos', '6 u', '1,50'], ['Azúcar', '250 g', '0,30'], ['Nata', '500 ml', '2,20'], ['Fresas', '400 g', '2,40'], ['Caja y base', '', '0,90'], ['Total', '', '7,50']], [92, 40, 34]); },
      intro: 'Coste de los ingredientes y del envase de una tarta de fresas de 8 raciones.',
      q: [['¿Cuánto cuesta cada ración?', '7,50 ÷ 8 ≈ 0,94.'], ['Si se aplica un factor de 3 sobre el coste, ¿cuál es el precio?', '22,50.'], ['¿Qué ingrediente pesa más en el coste?', 'Las fresas.']],
      porque: 'Sumar cada gramo permite fijar un precio que cubra ingredientes, trabajo y local.' },
    { id: 'ps_m_porciones', fam: 'med', n: 'Porciones de una tarta',
      d: function (K) { var s = K.e(64, 76, 52, 40, C.crema); for (var i = 0; i < 8; i++) { var a = i * Math.PI / 4; s += K.l('M64 76 L' + (64 + Math.cos(a) * 52).toFixed(1) + ' ' + (76 + Math.sin(a) * 40).toFixed(1), C.chocoC, { w: 1 }); } s += K.e(148, 76, 36, 28, C.crema); for (var j = 0; j < 12; j++) { var b = j * Math.PI / 6; s += K.l('M148 76 L' + (148 + Math.cos(b) * 36).toFixed(1) + ' ' + (76 + Math.sin(b) * 28).toFixed(1), C.chocoC, { w: 1 }); } return s + K.t(64, 134, '24 cm · 8 raciones', { s: 7.6, b: 1 }) + K.t(148, 134, '18 cm · 12 mini', { s: 7.6, b: 1 }); },
      intro: 'Cuántas raciones salen según el diámetro y el tamaño de cada porción.',
      q: [['¿Qué ángulo tiene cada porción si se corta en 8?', '45°.'], ['¿Y si se corta en 12?', '30°.'], ['¿Por qué se limpia el cuchillo entre cortes?', 'Para que cada corte salga limpio.']],
      porque: 'Dividir 360° entre las raciones da el ángulo de cada una.' },
    { id: 'ps_m_molde', fam: 'med', n: 'Cambiar de molde',
      d: function (K) { return K.suelo(60, 118, 44) + K.cil(60, 76, 40, 36, C.bizcocho) + K.t(60, 136, '20 cm', { s: 8, b: 1 }) + K.suelo(150, 118, 48) + K.cil(150, 70, 48, 42, C.bizcocho) + K.t(150, 136, '24 cm', { s: 8, b: 1 }) + K.t(100, 22, '(24 ÷ 20)² = 1,44', { s: 10, b: 1 }) + K.t(100, 36, 'Multiplicar la receta por 1,44', { s: 7.4 }); },
      intro: 'Para pasar una receta a un molde más grande se compara el área, no el diámetro.',
      q: [['Si la receta lleva 300 g de harina en 20 cm, ¿cuánta en 24 cm?', '300 × 1,44 = 432 g.'], ['¿Por qué no basta con multiplicar por 24 ÷ 20?', 'Porque el área crece con el cuadrado del radio.'], ['¿Cambia el tiempo de horno?', 'Sí: suele necesitar algo más de tiempo.']],
      porque: 'El área del círculo es π × r²: al doblar el radio, la superficie se multiplica por 4.' },
    { id: 'ps_m_gelatina', fam: 'med', n: 'Calcular la gelatina',
      d: function (K) { var s = ''; for (var i = 0; i < 6; i++) s += K.r(14 + i * 7, 40 + i * 2, 44, 28, 3, '#F2E3BF', { op: .9 }); return s + K.t(56, 100, '6 hojas × 2 g = 12 g', { s: 8, b: 1 }) + K.t(156, 50, '1 litro de mousse', { s: 7.4 }) + K.t(156, 64, '8–12 g de gelatina', { s: 7.4, b: 1 }) + K.t(156, 84, 'Hidratar en agua fría', { s: 7 }) + K.t(156, 96, '5–10 minutos', { s: 7 }); },
      intro: 'La gelatina en hojas se pesa y se hidrata en agua fría antes de usarla.',
      q: [['¿Cuánto pesa una hoja de gelatina?', 'Unos 2 g.'], ['¿Cuántas hojas para 500 ml de mousse?', 'Entre 2 y 3 hojas (4–6 g).'], ['¿Por qué no se hierve?', 'El calor fuerte le quita fuerza de gelificación.']],
      porque: 'Hidratada en frío, la gelatina se disuelve luego del todo a unos 50–60 °C.' },
    { id: 'ps_m_tazas', fam: 'med', n: 'De tazas a gramos',
      d: function (K) { return tabla(K, 20, 22, 160, [['1 taza de…', 'Gramos'], ['Harina', '125 g'], ['Azúcar', '200 g'], ['Azúcar glas', '120 g'], ['Mantequilla', '225 g'], ['Leche', '240 g'], ['Cacao', '90 g']], [110, 40]); },
      intro: 'Una misma taza pesa distinto según el ingrediente.',
      q: [['¿Pesa lo mismo una taza de harina que de azúcar?', 'No: la de azúcar pesa unos 200 g y la de harina unos 125 g.'], ['¿Por qué la pastelería prefiere pesar?', 'Porque es más exacto y repetible.'], ['¿Cuántas tazas son 500 g de harina?', 'Unas 4 tazas.']],
      porque: 'Cada ingrediente tiene su densidad: el mismo volumen tiene distinto peso.' },
    { id: 'ps_m_rendimiento', fam: 'med', n: 'Rendimiento de una masa',
      d: function (K) { var s = K.cil(40, 60, 26, 36, M.acero, { abierto: 1 }) + K.e(40, 62, 22, 5, C.crema) + K.t(40, 114, '900 g de choux', { s: 7.4, b: 1 }) + K.flecha(72, 78, 92, 78, M.tinta); for (var i = 0; i < 6; i++) for (var j = 0; j < 5; j++) s += K.c(104 + i * 14, 50 + j * 14, 5, C.galleta); return s + K.t(140, 132, '30 piezas de 30 g', { s: 8, b: 1 }); },
      intro: 'Cuántas piezas salen de una masa según el peso de cada una.',
      q: [['Con 900 g de choux y piezas de 20 g, ¿cuántas salen?', '45 piezas.'], ['¿Qué margen se deja por merma?', 'Un 5–10 % de masa que queda en el bol y la manga.'], ['¿Cómo se consigue que todas pesen igual?', 'Pesando las primeras y usando la misma boquilla.']],
      porque: 'Dividir el peso total entre el peso por pieza da el número máximo de piezas.' },
    { id: 'ps_m_plan', fam: 'med', n: 'Plan de producción de dos días',
      d: function (K) { var s = K.l('M12 50 H188 M12 104 H188', M.tinta, { w: 1 }), D1 = [['Bizcochos', 0, 50], ['Cremas', 50, 40], ['Congelar', 90, 80]], D2 = [['Glasear', 0, 40], ['Decorar', 40, 60], ['Vitrina', 100, 70]]; D1.forEach(function (p, i) { s += K.r(12 + p[1], 36, p[2], 14, 1, [C.bizcocho, C.pastelera, '#CFE6EE'][i]) + K.t(12 + p[1] + p[2] / 2, 30, p[0], { s: 6.8, b: 1 }); }); D2.forEach(function (p, i) { s += K.r(12 + p[1], 90, p[2], 14, 1, ['#8C3A62', C.frambuesa, C.pistacho][i]) + K.t(12 + p[1] + p[2] / 2, 84, p[0], { s: 6.8, b: 1 }); }); return s + K.t(12, 64, 'Día 1', { a: 'start', s: 7.4 }) + K.t(12, 118, 'Día 2', { a: 'start', s: 7.4 }); },
      intro: 'Una tarta de mousse se reparte en dos días: preparar y congelar, luego terminar.',
      q: [['¿Por qué se congela la tarta la víspera?', 'Para poder glasearla y cortarla limpia.'], ['¿Qué se hace primero el día 1?', 'Los bizcochos, que tienen que enfriar.'], ['¿Cuándo se decora?', 'El día de la venta, para que la fruta esté fresca.']],
      porque: 'Separar tareas por tiempos de frío aprovecha las esperas y reparte el trabajo.' },
    { id: 'ps_m_alergenos', fam: 'med', n: 'Etiqueta de alérgenos',
      d: function (K) { var s = K.r(20, 16, 160, 120, 4, M.blanco) + K.t(28, 32, 'Tarta de fresas · 8 raciones', { a: 'start', s: 8, b: 1 }), A = [['Gluten', 1], ['Huevo', 1], ['Leche', 1], ['Frutos de cáscara', 0], ['Soja', 0], ['Cacahuete', 0]]; A.forEach(function (a, i) { var y = 50 + i * 14; s += K.r(28, y - 7, 8, 8, 1, a[1] ? M.rojo : 'none', { w: .8 }) + K.t(42, y, a[0], { a: 'start', s: 7.4, b: a[1] }); }); return s + K.t(28, 136 - 6, 'Consumir antes de: 2 días', { a: 'start', s: 7 }); },
      intro: 'Toda pieza vendida debe indicar los alérgenos que contiene.',
      q: [['¿Qué tres alérgenos tiene esta tarta?', 'Gluten, huevo y leche.'], ['¿Cuántos alérgenos de declaración obligatoria hay en la Unión Europea?', 'Catorce.'], ['¿Qué pasa si hay trazas de frutos secos en el obrador?', 'Se indica «puede contener trazas de…».']],
      porque: 'Una etiqueta clara protege a las personas alérgicas y cumple la ley.' }
  ];
  MO.agregar('pasteleria', L);
})();
