/* b6_lib_ecommerce.js — Comercio electrónico: modelos 1–17 de 50 (primera entrega; 18–32 en el archivo 2, 33–50 en el 3). Materia `ecom`. Prefijo `ce_`.
   Usa EU_EMPRE_K y EU_DIGI_K: cargar después de b6_lib_marketing.js. Importes de ejemplo sin moneda.
   No repite ec_ficha, ec_zonas, ec_devolucion, la cascada de costos, el peso volumétrico ni el flujo logístico de b6_comercio_electronico.js. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS, E = window.EU_EMPRE_K, D = window.EU_DIGI_K; if (!MO || !E || !D || MO.modelo('ce_modelos')) return;
  var P = E.P, CO = E.CO, nf = E.nf, ajusta = E.ajusta, G = E.G, caja = E.caja, per = E.per, barras = E.barras;
  var pant = D.pant, movil = D.movil, renglones = D.renglones, sector = D.sector, curva = D.curva, check = D.check;
  function carrito(K, x, y, e, col) { e = e || 1; return K.l('M' + (x - 14 * e) + ' ' + (y - 10 * e) + ' L' + (x - 10 * e) + ' ' + (y - 10 * e) + ' L' + (x - 6 * e) + ' ' + (y + 4 * e) + ' L' + (x + 12 * e) + ' ' + (y + 4 * e) + ' L' + (x + 14 * e) + ' ' + (y - 6 * e) + ' L' + (x - 8 * e) + ' ' + (y - 6 * e), P.tinta, { w: 1 }) + K.p('M' + (x - 7.5 * e) + ' ' + (y - 5 * e) + ' L' + (x + 13 * e) + ' ' + (y - 5 * e) + ' L' + (x + 11.5 * e) + ' ' + (y + 3 * e) + ' L' + (x - 5.5 * e) + ' ' + (y + 3 * e) + ' Z', col || P.azul, { w: .4 }) + K.c(x - 4 * e, y + 8 * e, 2 * e, P.tinta, { negro: 1, w: .3 }) + K.c(x + 10 * e, y + 8 * e, 2 * e, P.tinta, { negro: 1, w: .3 }); }
  function cajaCarton(K, x, y, w, h, col) { var d = w * .3; return K.p('M' + x + ' ' + y + ' L' + (x + w) + ' ' + y + ' L' + (x + w) + ' ' + (y + h) + ' L' + x + ' ' + (y + h) + ' Z', col || P.madera, { w: .8 }) + K.p('M' + x + ' ' + y + ' L' + (x + d) + ' ' + (y - d * .6) + ' L' + (x + w + d) + ' ' + (y - d * .6) + ' L' + (x + w) + ' ' + y + ' Z', P.oro, { w: .8 }) + K.p('M' + (x + w) + ' ' + y + ' L' + (x + w + d) + ' ' + (y - d * .6) + ' L' + (x + w + d) + ' ' + (y + h - d * .6) + ' L' + (x + w) + ' ' + (y + h) + ' Z', P.naranjaO, { w: .8, op: .7 }) + K.l('M' + (x + w / 2) + ' ' + y + ' L' + (x + w / 2) + ' ' + (y + h * .35), P.tinta, { w: 1.6 }); }
  window.EU_DIGI_K.carrito = carrito; window.EU_DIGI_K.cajaCarton = cajaCarton;
  var FAM = { tie: 'La tienda online', cat: 'Catálogo y producto', pag: 'Pagos', log: 'Envíos y almacén', cli: 'Experiencia del cliente', mkp: 'Canales y marketplaces', num: 'Los números', leg: 'Seguridad y ley' };
  window.EU_DIGI_K.FAM_ECOM = FAM;
  var L = [
    /* ─────────── LA TIENDA ONLINE ─────────── */
    G('ce_modelos', 'tie', 'Quién vende a quién', [['B2C', 'empresa → consumidor'], ['B2B', 'empresa → empresa'], ['C2C', 'persona → persona'], ['D2C', 'fabricante → consumidor'], ['Suscripción', 'pago fijo cada mes'], ['Bajo pedido', 'se fabrica al comprar']], 2, 20, 28, 'Una misma tienda puede combinar varios modelos', 'El comercio electrónico se clasifica según quién vende y quién compra, y según cómo se paga.', [['¿Qué modelo es una web de segunda mano entre vecinos?', 'C2C: de persona a persona.'], ['¿Y un mayorista que vende a restaurantes?', 'B2B.'], ['¿Qué ventaja tiene el D2C?', 'El fabricante se queda el margen del intermediario y conoce al cliente.']], 'Saber el modelo ayuda a elegir precios, canales y plataforma.', { s: 8, s2: 5.4 }),
    { id: 'ce_mapa_tienda', fam: 'tie', n: 'Recorrido por una tienda online',
      d: function (K) { var Pg = [['inicio', P.amarillo], ['categoría', P.azul], ['producto', P.verde], ['carrito', P.rosa], ['pago', P.naranja], ['gracias', P.morado]], s = K.suelo(100, 140, 96); Pg.forEach(function (p, i) { var x = 12 + (i % 3) * 62, y = 18 + Math.floor(i / 3) * 56; s += pant(K, x, y, 52, 40, { f: p[1] }) + K.t(x + 26, y + 26, p[0], { s: 6, b: 1 }); if (i % 3 < 2) s += K.flecha(x + 53, y + 20, x + 61, y + 20, P.tinta, { w: .8, p: 2.2 }); }); s += K.l('M168 60 L168 66 L38 66 L38 72', P.tinta, { w: .8 }) + K.p('M35 70 L41 70 L38 74 Z', P.tinta, { w: .3 }); return s + K.t(100, 128, 'Cada paso de más hace que alguien abandone', { s: 5.6, b: 1 }) + K.t(100, 138, 'Llegar a pagar en pocos clics', { s: 5 }); },
      intro: 'Una tienda online lleva al visitante de la página de inicio al pago a través de unas pocas páginas.',
      q: [['¿Cuántas páginas hay hasta la confirmación?', 'Seis.'], ['¿Qué página se puede saltar con un botón «comprar ya»?', 'El carrito.'], ['¿Para qué sirve la página de gracias?', 'Confirma el pedido y puede ofrecer seguir comprando.']],
      porque: 'Un camino corto y claro vende más que uno largo.' },
    { id: 'ce_filtros', fam: 'tie', n: 'Buscador y filtros de la tienda',
      d: function (K) { var s = K.suelo(100, 144, 96) + pant(K, 10, 8, 180, 128) + K.r(16, 20, 168, 12, 6, P.blanco, { w: .7 }) + K.c(26, 26, 3, 'none', { w: .1 }) + K.l('M24 24 m-3 0 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0 M26.5 28.5 L29 31', P.tinta, { w: .8 }) + K.t(34, 28, 'zapatillas', { s: 5.6, a: 'start' }); [['talla', ['38', '39', '40']], ['color', ['negro', 'blanco']], ['precio', ['hasta 50']], ['envío', ['gratis']]].forEach(function (f, i) { var y = 46 + i * 22; s += K.t(18, y, f[0], { s: 5.4, b: 1, a: 'start' }); f[1].forEach(function (o, j) { s += K.r(18 + j * 20, y + 3, 18, 9, 4.5, j === 0 ? P.azul : P.gris, { w: .4 }) + K.t(27 + j * 20, y + 9.5, o, { s: ajusta(o, 16, 4.4) }); }); }); for (var i = 0; i < 6; i++) { var x = 88 + (i % 3) * 32, y = 40 + Math.floor(i / 3) * 46; s += K.r(x, y, 28, 40, 2, P.blanco, { w: .5 }) + K.r(x + 3, y + 3, 22, 20, 1.5, CO[i], { w: .3 }) + renglones(K, x + 4, y + 28, 20, 2, 5); } return s + K.t(132, 132, '486 resultados → 6 con los filtros', { s: 5.2, b: 1 }); },
      intro: 'El buscador y los filtros ayudan a encontrar rápido un producto entre cientos.',
      q: [['¿Qué filtros se han marcado?', 'Talla 38, color negro, hasta 50 y envío gratis.'], ['¿Por qué importan los filtros en una tienda grande?', 'Porque sin ellos el cliente se cansa de buscar.'], ['¿Qué filtros pondrías en una tienda de plantas?', 'Tamaño, luz que necesita, interior o exterior y precio.']],
      porque: 'Quien encuentra rápido lo que busca compra más y vuelve.' },
    { id: 'ce_categorias', fam: 'tie', n: 'Organizar el catálogo en categorías',
      d: function (K) { var s = K.suelo(100, 140, 96) + caja(K, 76, 12, 48, 16, P.amarillo, 'TIENDA'), C = [[34, 'Mujer', ['vestidos', 'calzado']], [100, 'Hombre', ['camisas', 'calzado']], [166, 'Niños', ['bebé', 'colegio']]]; C.forEach(function (c, i) { s += K.l('M100 28 L100 36 L' + c[0] + ' 36 L' + c[0] + ' 44', P.grisO, { w: .8 }) + caja(K, c[0] - 22, 44, 44, 14, CO[i + 1], c[1]); c[2].forEach(function (t, j) { var x = c[0] - 14 + j * 28; s += K.l('M' + c[0] + ' 58 L' + c[0] + ' 64 L' + x + ' 64 L' + x + ' 70', P.grisO, { w: .6 }) + K.r(x - 13, 70, 26, 12, 2, P.blanco, { w: .6 }) + K.t(x, 78, t, { s: ajusta(t, 24, 5) }); }); }); return s + K.t(100, 102, 'Máximo tres niveles: tienda → categoría → subcategoría', { s: 5.2, b: 1 }) + K.t(100, 114, 'Nombres que usa el cliente, no los del almacén', { s: 5 }) + K.t(100, 126, 'Un producto puede estar en dos categorías', { s: 5 }); },
      intro: 'Las categorías ordenan los productos como las secciones de una tienda física, de lo general a lo concreto.',
      q: [['¿Cuántas subcategorías hay en total?', '6.'], ['¿Dónde pondrías «zapatillas de niño»?', 'En Niños, por ejemplo en «colegio» o una nueva «calzado».'], ['¿Por qué no más de tres niveles?', 'Porque el cliente se pierde y abandona.']],
      porque: 'Un catálogo bien ordenado se recorre sin pensar.' },
    { id: 'ce_dominio', fam: 'tie', n: 'Partes de una dirección web',
      d: function (K) { var Pz = [['https://', 'conexión segura', P.verde], ['www.', 'subdominio', P.gris], ['dulcehogar', 'nombre elegido', P.amarillo], ['.com', 'extensión', P.azul], ['/tazas', 'página', P.rosa]], s = K.suelo(100, 140, 96), x = 10; Pz.forEach(function (p, i) { var w = p[0].length * 3.9 + 6; s += K.r(x, 36, w, 18, 2, p[2], { w: .7 }) + K.t(x + w / 2, 48, p[0], { s: 7, b: 1 }) + K.l('M' + (x + w / 2) + ' 56 L' + (x + w / 2) + ' ' + (i % 2 ? 76 : 64), P.grisO, { w: .5 }) + K.t(x + w / 2, i % 2 ? 82 : 70, p[1], { s: ajusta(p[1], 44, 5) }); x += w + 1; }); return s + K.t(100, 22, 'dirección = dominio + página', { s: 6, b: 1 }) + K.t(100, 104, 'Nombre corto, fácil de escribir y sin guiones raros', { s: 5.2, b: 1 }) + K.t(100, 114, 'Extensión del país (.es, .mx, .co…) o .com', { s: 5 }) + K.t(100, 124, 'El dominio se renueva cada año', { s: 5 }); },
      intro: 'La dirección web tiene partes: el protocolo, el nombre del dominio, la extensión y la página concreta.',
      q: [['¿Qué parte indica que la conexión es segura?', 'https://'], ['¿Qué extensión usaría una tienda solo para México?', '.mx'], ['¿Por qué un nombre corto?', 'Se recuerda y se escribe sin errores.']],
      porque: 'Un buen dominio es la dirección de la tienda: debe ser fácil de encontrar.' },
    { id: 'ce_plataforma', fam: 'tie', n: 'Plataforma alquilada o tienda propia',
      d: function (K) { var F = [['Empezar en un día', 1, 0], ['Pago mensual fijo', 1, 0], ['Sin saber programar', 1, 0], ['Diseño a medida', 0, 1], ['Sin cuota mensual', 0, 1], ['Control total', 0, 1]], s = K.suelo(100, 140, 96) + K.t(124, 16, 'alquilada', { s: 5.6, b: 1 }) + K.t(170, 16, 'propia', { s: 5.6, b: 1 }); F.forEach(function (f, i) { var y = 30 + i * 15; s += K.r(10, y - 8, 180, 13, 2, i % 2 ? P.blanco : P.gris, { w: .3 }) + K.t(14, y + 1, f[0], { s: 5.6, a: 'start' }) + check(K, 124, y - 1, f[1]) + check(K, 170, y - 1, f[2]); }); return s + K.t(100, 128, 'Para empezar suele bastar una plataforma alquilada', { s: 5.4, b: 1 }) + K.t(100, 138, 'La propia exige más dinero, tiempo o un programador', { s: 5 }); },
      intro: 'Una tienda online se puede montar en una plataforma que se alquila por meses o desarrollar a medida.',
      q: [['¿Qué opción elegirías para empezar con poco dinero?', 'La plataforma alquilada.'], ['¿Qué ventaja tiene la propia?', 'Diseño a medida y control total.'], ['Si la cuota es 30 al mes, ¿cuánto se paga al año?', '360.']],
      porque: 'Elegir bien la plataforma ahorra cambios caros más adelante.' },
    /* ─────────── CATÁLOGO Y PRODUCTO ─────────── */
    { id: 'ce_estudio_foto', fam: 'cat', n: 'Un estudio de fotos casero',
      d: function (K) { var s = K.suelo(100, 128, 92) + K.p('M50 30 L150 30 L150 96 Q150 112 134 112 L66 112 Q50 112 50 96 Z', P.blanco, { w: .9 }) + K.r(86, 82, 28, 26, 3, P.rosa, { w: .8 }) + K.r(92, 74, 16, 8, 2, P.rosa, { w: .6 }) + K.p('M14 34 L34 26 L34 70 L14 62 Z', P.amarillo, { w: .8 }) + K.l('M24 66 L24 120', P.grisO, { w: 1.2 }) + K.r(170, 40, 8, 60, 1, P.gris, { w: .7 }) + K.r(116, 116, 30, 14, 2, P.tinta, { w: .6 }) + K.c(122, 123, 4, P.azul, { w: .4 }); for (var i = 0; i < 4; i++) s += K.l('M36 ' + (36 + i * 8) + ' L60 ' + (56 + i * 6), P.oro, { w: .5 }); return s + K.t(24, 20, 'luz lateral', { s: 5.4, b: 1 }) + K.t(24, 128, 'ventana o lámpara', { s: 4.6 }) + K.t(100, 24, 'fondo blanco curvo', { s: 5.4, b: 1 }) + K.t(174, 34, 'rebote', { s: 5.4, b: 1 }) + K.t(174, 108, 'cartulina', { s: 4.6 }) + K.t(131, 140, 'móvil fijo', { s: 5 }) + K.t(66, 140, 'producto', { s: 5 }); },
      intro: 'Con una ventana, una cartulina blanca y el móvil se pueden hacer fotos de producto limpias y uniformes.',
      q: [['¿Para qué sirve la cartulina de rebote?', 'Para aclarar la sombra del lado opuesto a la luz.'], ['¿Por qué un fondo curvo?', 'Para que no se vea la línea entre mesa y pared.'], ['¿Por qué fijar el móvil?', 'Para que todas las fotos tengan el mismo encuadre y salgan nítidas.']],
      porque: 'Las fotos sustituyen al tacto: en internet, el cliente compra lo que ve.' },
    { id: 'ce_tomas', fam: 'cat', n: 'Las fotos que necesita un producto',
      d: function (K) { var T = [['frente', 0], ['perfil', 1], ['detalle', 2], ['en uso', 3], ['tamaño', 4], ['envase', 5]], s = K.suelo(100, 140, 96); T.forEach(function (t, i) { var x = 12 + (i % 3) * 62, y = 14 + Math.floor(i / 3) * 56, cx = x + 26, cy = y + 22; s += K.r(x, y, 52, 44, 3, P.blanco, { w: .8 }); if (i === 0) s += K.r(cx - 8, cy - 12, 16, 24, 3, P.azul, { w: .7 }); if (i === 1) s += K.r(cx - 3, cy - 12, 6, 24, 2, P.azul, { w: .7 }); if (i === 2) s += K.c(cx, cy, 14, P.azul, { w: .7 }) + K.c(cx, cy, 5, P.amarillo, { w: .5 }); if (i === 3) s += per(K, cx - 10, cy - 10, P.verde, .6) + K.r(cx + 2, cy - 4, 8, 14, 2, P.azul, { w: .6 }); if (i === 4) s += K.r(cx - 18, cy - 8, 8, 14, 2, P.azul, { w: .6 }) + K.r(cx - 4, cy - 2, 20, 6, 1, P.amarillo, { w: .5 }) + K.t(cx + 6, cy + 14, '15 cm', { s: 4.4 }); if (i === 5) s += K.r(cx - 12, cy - 10, 24, 20, 2, P.madera, { w: .7 }); s += K.t(cx, y + 52, t[0], { s: 5.6, b: 1 }); }); return s + K.t(100, 136, 'Todas con la misma luz y el mismo fondo', { s: 5.4, b: 1 }); },
      intro: 'Una ficha completa muestra el producto desde varios ángulos, en detalle, en uso y con una referencia de tamaño.',
      q: [['¿Qué foto evita la pregunta «¿cuánto mide?»?', 'La de tamaño, con una referencia.'], ['¿Para qué sirve la foto en uso?', 'Para que el cliente se imagine usándolo.'], ['¿Cuántas fotos hay en el ejemplo?', 'Seis.']],
      porque: 'Cada foto responde a una duda que, si no, frenaría la compra.' },
    { id: 'ce_variantes', fam: 'cat', n: 'Variantes y existencias',
      d: function (K) { var T = ['S', 'M', 'L', 'XL'], C = [['rojo', P.rojo], ['azul', P.azul], ['verde', P.verde]], St = [[4, 0, 6, 2], [8, 5, 3, 0], [1, 7, 2, 4]], s = K.suelo(100, 140, 96); T.forEach(function (t, j) { s += K.t(72 + j * 30, 24, t, { s: 6.4, b: 1 }); }); C.forEach(function (c, i) { var y = 38 + i * 22; s += K.c(26, y, 6, c[1], { w: .7 }) + K.t(36, y + 2, c[0], { s: 5.6, a: 'start' }); St[i].forEach(function (v, j) { s += K.r(60 + j * 30, y - 8, 24, 16, 2, v === 0 ? P.rojo : v < 3 ? P.amarillo : P.verde, { w: .5, op: .7 }) + K.t(72 + j * 30, y + 2, String(v), { s: 6.4, b: 1 }); }); }); return s + K.t(100, 116, '3 colores × 4 tallas = 12 variantes de una camiseta', { s: 5.4, b: 1 }) + K.t(100, 126, 'Agotado en rojo · pocas en amarillo', { s: 5 }) + K.t(100, 136, 'La tienda oculta o avisa de las agotadas', { s: 5 }); },
      intro: 'Un producto con tallas y colores tiene varias variantes, y cada una lleva su propio número de unidades.',
      q: [['¿Cuántas camisetas hay en total?', '4+0+6+2 + 8+5+3+0 + 1+7+2+4 = 42.'], ['¿Qué variantes están agotadas?', 'Roja M y azul XL.'], ['¿Cuántas variantes tendría con 5 colores y 4 tallas?', '20.']],
      porque: 'Controlar cada variante evita vender algo que no hay.' },
    { id: 'ce_descuento', fam: 'cat', n: 'Precio anterior y descuento',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(20, 18, 72, 92, 4, P.blanco, { w: .9 }) + K.r(26, 24, 60, 44, 2, P.azul, { w: .5 }) + K.r(64, 26, 20, 10, 5, P.rojo, { w: .5 }) + K.t(74, 33, '−25 %', { s: 4.8, b: 1, c: P.blanco }) + K.t(30, 80, '40', { s: 7, a: 'start', c: P.grisO }) + K.l('M29 77.5 L42 77.5', P.rojoO, { w: .8 }) + K.t(48, 80, '30', { s: 9, b: 1, a: 'start' }) + renglones(K, 30, 92, 50, 2, 6) + K.t(140, 34, 'Descuento = 40 − 30 = 10', { s: 5.6, b: 1 }) + K.t(140, 46, '10 / 40 × 100 = 25 %', { s: 5.6 }) + K.t(140, 66, 'El precio anterior debe', { s: 5.2 }) + K.t(140, 74, 'ser real, no inventado', { s: 5.2 }) + K.t(140, 90, 'muchos países lo exigen:', { s: 5 }) + K.t(140, 98, 'el más bajo de los últimos', { s: 5 }) + K.t(140, 106, 'días antes de rebajar', { s: 5 }); return s + K.t(100, 128, 'Mostrar el ahorro en dinero o en porcentaje, el que sea mayor a la vista', { s: 4.6, b: 1 }); },
      intro: 'Un precio rebajado muestra el anterior tachado y el porcentaje de descuento.',
      q: [['¿Qué descuento hay de 60 a 45?', '15 / 60 = 25 %.'], ['¿Cuál es el precio con 20 % menos sobre 35?', '28.'], ['¿Por qué el precio anterior debe ser real?', 'Inventarlo es engañar al cliente y está sancionado.']],
      porque: 'Un descuento claro y honesto genera confianza y ventas.' },
    { id: 'ce_pack', fam: 'cat', n: 'Vender en paquete',
      d: function (K) { var s = K.suelo(100, 140, 96), I = [['café', 8, P.madera], ['taza', 10, P.azul], ['galletas', 4, P.amarillo]]; I.forEach(function (it, i) { var x = 18 + i * 30; s += K.r(x, 30, 24, 30, 3, it[2], { w: .7 }) + K.t(x + 12, 70, it[0], { s: 5.2 }) + K.t(x + 12, 78, nf(it[1]), { s: 6, b: 1 }); if (i < 2) s += K.t(x + 27, 48, '+', { s: 7, b: 1 }); }); s += K.t(54, 94, 'por separado: 22', { s: 5.8, b: 1 }) + K.flecha(110, 50, 124, 50, P.tinta, { w: 1, p: 3 }) + cajaCarton(K, 132, 34, 36, 30, P.rosa) + K.t(156, 78, 'paquete regalo', { s: 5.2, b: 1 }) + K.t(156, 90, '19', { s: 9, b: 1 }); return s + K.t(100, 112, 'El cliente ahorra 3 y la tienda vende 3 productos de una vez', { s: 5, b: 1 }) + K.t(100, 124, 'Un solo envío para tres productos: menos coste por unidad', { s: 4.8 }) + K.t(100, 134, 'Sirve para dar salida a lo que se vende menos', { s: 4.8 }); },
      intro: 'Un paquete agrupa varios productos a un precio menor que la suma, lo que sube el valor de cada pedido.',
      q: [['¿Qué porcentaje ahorra el cliente?', '3 / 22 ≈ 14 %.'], ['¿Por qué le conviene a la tienda?', 'Vende más por pedido y ahorra en envíos.'], ['Diseña un paquete para una tienda de plantas.', 'Planta + maceta + abono, por ejemplo.']],
      porque: 'Los paquetes suben el pedido medio sin buscar clientes nuevos.' },
    { id: 'ce_texto_producto', fam: 'cat', n: 'Texto de producto fácil de leer',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.t(52, 16, 'difícil', { s: 6, b: 1, c: P.rojoO }) + K.t(148, 16, 'fácil', { s: 6, b: 1, c: P.verdeO }) + K.r(10, 22, 84, 96, 3, P.blanco, { w: .7 }) + renglones(K, 16, 30, 72, 16, 5.4) + K.r(106, 22, 84, 96, 3, P.blanco, { w: .7 }) + K.t(112, 32, 'Mochila urbana 20 L', { s: 5.6, b: 1, a: 'start' }), V = ['impermeable', 'bolsillo para portátil', 'pesa 600 g', 'garantía 2 años']; V.forEach(function (v, i) { var y = 46 + i * 12; s += K.c(115, y - 1.8, 1.6, P.verdeO, { w: .2 }) + K.t(120, y, v, { s: 5.4, a: 'start' }); }); return s + renglones(K, 112, 100, 72, 3, 5) + K.t(100, 132, 'Título, ventajas en viñetas y detalle al final', { s: 5.6, b: 1 }); },
      intro: 'En una pantalla la gente no lee: recorre con la vista. Un buen texto de producto se entiende en pocos segundos.',
      q: [['¿Qué va en las viñetas?', 'Las ventajas y datos clave.'], ['¿Dónde se ponen los detalles técnicos?', 'Al final, para quien quiera más información.'], ['Escribe tres viñetas para un termo.', 'Mantiene frío 24 h, 500 ml, sin plástico, por ejemplo.']],
      porque: 'Si el dato que busca el cliente está escondido, se va sin comprar.' },
    /* ─────────── PAGOS ─────────── */
    G('ce_metodos', 'pag', 'Formas de pago online', [['Tarjeta', 'débito o crédito'], ['Transferencia', 'del banco a la tienda'], ['Billetera digital', 'cuenta en el móvil'], ['Pago al recibir', 'en efectivo o tarjeta'], ['Código en tienda', 'se paga en un comercio'], ['Pago por QR', 'escaneando con el móvil']], 2, 20, 28, 'Ofrecer las formas que más se usan en el país', 'Ofrecer varias formas de pago evita que el cliente abandone por no encontrar la suya.', [['¿Qué forma prefiere quien no tiene tarjeta?', 'Pago al recibir, código en tienda o transferencia.'], ['¿Qué riesgo tiene el pago al recibir para la tienda?', 'Que el cliente rechace el paquete y haya que pagar el envío de vuelta.'], ['¿Cuántas formas conviene ofrecer?', 'Las más usadas en el país, normalmente tres o cuatro.']], 'Sin la forma de pago que espera, el cliente no compra.', { s: 7.4, s2: 5.2 }),
    { id: 'ce_pasarela', fam: 'pag', n: 'Qué pasa al pagar con tarjeta',
      d: function (K) { var N = [[24, 'cliente', P.azul], [72, 'pasarela', P.amarillo], [128, 'banco', P.verde], [176, 'tienda', P.rosa]], s = K.suelo(100, 140, 96); N.forEach(function (n, i) { s += K.c(n[0], 40, 15, n[2], { w: .9 }) + K.t(n[0], 42, n[1], { s: ajusta(n[1], 26, 5.6), b: 1 }); }); s += K.flecha(40, 34, 56, 34, P.tinta, { w: .9, p: 2.4 }) + K.flecha(88, 34, 112, 34, P.tinta, { w: .9, p: 2.4 }) + K.flecha(112, 48, 88, 48, P.verdeO, { w: .9, p: 2.4 }) + K.flecha(88, 56, 160, 56, P.verdeO, { w: .9, p: 2.4 }); s += K.t(48, 28, 'datos', { s: 4.6 }) + K.t(100, 28, '¿hay saldo?', { s: 4.6 }) + K.t(100, 46, 'sí', { s: 4.6, b: 1 }) + K.t(124, 64, 'aprobado', { s: 4.6, b: 1, c: P.verdeO }); [['1', 'el cliente escribe la tarjeta'], ['2', 'la pasarela la cifra y consulta'], ['3', 'el banco aprueba o rechaza'], ['4', 'la tienda recibe el aviso y envía'], ['5', 'el dinero llega en unos días, menos comisión']].forEach(function (f, i) { var y = 80 + i * 11; s += K.t(28, y, f[0], { s: 5.6, b: 1 }) + K.t(36, y, f[1], { s: 5.4, a: 'start' }); }); return s; },
      intro: 'Al pagar con tarjeta, una pasarela de pago conecta la tienda con el banco de forma segura en pocos segundos.',
      q: [['¿Quién aprueba el pago?', 'El banco del cliente.'], ['¿Ve la tienda el número completo de la tarjeta?', 'No: lo gestiona la pasarela de forma cifrada.'], ['¿Cuándo llega el dinero a la tienda?', 'En unos días, descontada la comisión.']],
      porque: 'La pasarela protege los datos y da confianza al cliente.' },
    { id: 'ce_comision', fam: 'pag', n: 'La comisión por cada pago',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(20, 24, 70, 44, 5, P.azul, { w: .9 }) + K.t(55, 38, 'venta', { s: 5.6 }) + K.t(55, 54, '50', { s: 11, b: 1 }) + K.flecha(94, 46, 108, 46, P.tinta, { w: 1, p: 3 }) + K.r(112, 18, 70, 20, 4, P.rojo, { w: .8 }) + K.t(147, 27, 'comisión', { s: 5, b: 1 }) + K.t(147, 34, '3 % + 0,30 = 1,80', { s: 5 }) + K.r(112, 42, 70, 30, 4, P.verde, { w: .8 }) + K.t(147, 54, 'recibe la tienda', { s: 5 }) + K.t(147, 66, '48,20', { s: 8, b: 1 }); return s + K.t(100, 92, 'Comisión = 50 × 3 % + 0,30 = 1,50 + 0,30 = 1,80', { s: 5.4, b: 1 }) + K.t(100, 106, 'En una venta de 5: 0,15 + 0,30 = 0,45 → ¡9 %!', { s: 5.4 }) + K.t(100, 120, 'La parte fija pesa mucho en compras pequeñas', { s: 5.4, b: 1 }) + K.t(100, 130, 'Tarifa de ejemplo: cada pasarela tiene la suya', { s: 4.8 }); },
      intro: 'Las pasarelas cobran por cada pago un porcentaje más una cantidad fija.',
      q: [['¿Qué comisión tiene una venta de 100?', '3 + 0,30 = 3,30.'], ['¿Qué porcentaje real paga una venta de 10?', '0,60 / 10 = 6 %.'], ['¿Cómo reducir su efecto?', 'Fijando un pedido mínimo o subiendo el pedido medio.']],
      porque: 'Olvidar la comisión hace que el margen real sea menor del previsto.' },
    { id: 'ce_pasos_pago', fam: 'pag', n: 'Los pasos para finalizar la compra',
      d: function (K) { var Pz = ['carrito', 'datos', 'envío', 'pago', 'listo'], s = K.suelo(100, 140, 96) + K.l('M24 30 L176 30', P.gris, { w: 3 }) + K.l('M24 30 L100 30', P.verdeO, { w: 3 }); Pz.forEach(function (p, i) { var x = 24 + i * 38; s += K.c(x, 30, 7, i <= 2 ? P.verde : P.blanco, { w: .8 }) + K.t(x, 32.5, String(i + 1), { s: 6, b: 1 }) + K.t(x, 46, p, { s: 5.4 }); }); s += K.r(40, 56, 120, 60, 4, P.blanco, { w: .8 }) + K.t(48, 68, 'Envío a domicilio', { s: 5.6, b: 1, a: 'start' }) + K.r(48, 74, 104, 10, 2, P.gris, { w: .3 }) + K.t(52, 81, 'Calle, número, ciudad', { s: 4.6, a: 'start', c: P.grisO }) + K.r(48, 88, 104, 10, 2, P.gris, { w: .3 }) + K.t(52, 95, 'Teléfono', { s: 4.6, a: 'start', c: P.grisO }) + K.r(96, 102, 56, 10, 5, P.naranja, { w: .5 }) + K.t(124, 109, 'Continuar', { s: 5, b: 1 }); return s + K.t(100, 128, 'Pedir solo los datos necesarios y permitir comprar sin registrarse', { s: 4.8, b: 1 }) + K.t(100, 138, 'Mostrar en qué paso está y cuántos faltan', { s: 4.8 }); },
      intro: 'El proceso de pago guía al cliente por unos pocos pasos y muestra en cada momento cuánto falta.',
      q: [['¿En qué paso está el cliente?', 'En el 3, envío.'], ['¿Por qué permitir comprar sin registrarse?', 'Porque obligar a crear cuenta hace abandonar a muchos.'], ['¿Qué dato no hace falta pedir para enviar?', 'La fecha de nacimiento, por ejemplo.']],
      porque: 'Cada campo de más en el formulario es una razón para abandonar.' },
    { id: 'ce_cuotas', fam: 'pag', n: 'Pagar a plazos',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(14, 22, 54, 40, 4, P.azul, { w: .9 }) + K.t(41, 36, 'precio', { s: 5.6 }) + K.t(41, 52, '300', { s: 10, b: 1 }); for (var i = 0; i < 6; i++) { var x = 82 + (i % 3) * 36, y = 18 + Math.floor(i / 3) * 30; s += K.r(x, y, 32, 24, 3, i < 2 ? P.verde : P.blanco, { w: .7 }) + K.t(x + 16, y + 9, 'mes ' + (i + 1), { s: 4.8 }) + K.t(x + 16, y + 19, '52,50', { s: 5.6, b: 1 }); } return s + K.t(100, 88, 'Sin interés: 300 / 6 = 50 al mes', { s: 5.6 }) + K.t(100, 100, 'Con 5 % de recargo: 315 / 6 = 52,50 al mes', { s: 5.6, b: 1 }) + K.t(100, 114, 'Total pagado: 315 → 15 más que al contado', { s: 5.4 }) + K.t(100, 128, 'Comprobar siempre el total, no solo la cuota', { s: 5.4, b: 1 }); },
      intro: 'Pagar a plazos reparte el precio en varias cuotas; a veces se añade un recargo o interés.',
      q: [['¿Cuánto es la cuota sin interés en 4 plazos?', '300 / 4 = 75.'], ['¿Cuánto se paga de más con el 5 %?', '15.'], ['¿Por qué ofrecer plazos sube las ventas?', 'Porque el cliente puede comprar algo caro sin pagar todo de una vez.']],
      porque: 'Las cuotas facilitan la compra, pero el cliente debe conocer el coste total.' }
  ];
  MO.agregar('ecom', L, { nombre: 'Comercio electrónico', familias: FAM, materias: /^(ecom)$/ });
})();
