/* b6_lib_tecnologia.js — Tecnología e informática (1/2): el computador, software, internet y redes, programación. 25 modelos.
   Materia `tecno`. Prefijo `te_`. Cargar después de b6_modelos.js.
   No repite fis_circuito, fis_plano, tec_iso, bloques, palanca, ia_red, ia_arbol ni los geo_/gm_ de geometría. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('te_partes_pc')) return;
  var P = { azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', metal: '#C8CED4', pantalla: '#1E3A4A', oro: '#E8C04A' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { pc: 'El computador', sw: 'Software y archivos', red: 'Internet y redes', prg: 'Programación', seg: 'Seguridad y ciudadanía digital', ele: 'Electricidad y electrónica', mec: 'Máquinas y mecanismos', mat: 'Materiales y fabricación', pro: 'El proyecto tecnológico' };
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + f1 * .35, q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  function caja(K, x, y, w, h, col, txt, fs) { return K.r(x, y, w, h, 3, col, { w: .9 }) + (txt ? K.t(x + w / 2, y + h / 2 + 2.3, txt, { s: fs || 6.2, b: 1 }) : ''); }
  function rot(K, x, y, tx, lx, ly) { return K.l('M' + x + ' ' + y + ' L' + lx + ' ' + ly, P.grisO, { w: .5 }) + K.c(x, y, 1.2, P.tinta, { negro: 1, w: .3 }) + K.t(lx + (lx < x ? -2 : 2), ly + 2, tx, { s: 5.4, b: 1, a: lx < x ? 'end' : 'start' }); }
  function monitor(K, x, y, w, h) { return K.r(x, y, w, h, 3, P.tinta, { w: 1 }) + K.r(x + 3, y + 3, w - 6, h - 6, 1, P.pantalla, { w: .3 }) + K.r(x + w / 2 - 4, y + h, 8, 8, 0, P.metal, { w: .6 }) + K.r(x + w / 2 - 14, y + h + 8, 28, 3, 1, P.metal, { w: .6 }); }
  function bloque(K, x, y, w, txt, col, fs) { return K.p('M' + x + ' ' + y + ' L' + (x + 6) + ' ' + y + ' L' + (x + 8) + ' ' + (y + 2) + ' L' + (x + 12) + ' ' + (y + 2) + ' L' + (x + 14) + ' ' + y + ' L' + (x + w) + ' ' + y + ' L' + (x + w) + ' ' + (y + 12) + ' L' + (x + 14) + ' ' + (y + 12) + ' L' + (x + 12) + ' ' + (y + 14) + ' L' + (x + 8) + ' ' + (y + 14) + ' L' + (x + 6) + ' ' + (y + 12) + ' L' + x + ' ' + (y + 12) + ' Z', col, { w: .7 }) + K.t(x + 4, y + 8.4, txt, { s: fs || 5.4, b: 1, a: 'start' }); }
  function nodo(K, x, y, r, col, txt, fs) { return K.c(x, y, r, col, { w: .8 }) + (txt ? K.t(x, y + 2, txt, { s: fs || 5.2, b: 1 }) : ''); }
  function persona(K, x, y, col) { return K.c(x, y, 6, P.piel, { w: .8 }) + K.p('M' + (x - 9) + ' ' + (y + 26) + ' Q' + (x - 9) + ' ' + (y + 8) + ' ' + x + ' ' + (y + 8) + ' Q' + (x + 9) + ' ' + (y + 8) + ' ' + (x + 9) + ' ' + (y + 26) + ' Z', col, { w: .8 }); }

  var L = [
    /* ─────────── EL COMPUTADOR ─────────── */
    { id: 'te_partes_pc', fam: 'pc', n: 'Las partes del computador',
      d: function (K) { return K.suelo(100, 136, 92) + monitor(K, 60, 18, 80, 54) + K.caja(150, 30, 26, 70, 8, P.gris, { w: .9 }) + K.c(163, 42, 3, P.verde, { w: .5 }) + K.r(156, 54, 14, 3, 1, P.tinta) + K.r(40, 96, 90, 14, 2, P.gris, { w: .8 }) + K.e(146, 104, 7, 9, P.gris, { w: .8 }) + K.l('M146 95 L146 102', P.grisO, { w: .5 }) + K.r(66, 24, 68, 42, 1, P.azul, { w: .2, op: .3 }) + rot(K, 70, 40, 'monitor (salida)', 58, 10) + rot(K, 170, 80, 'torre: CPU, memoria, disco', 128, 124) + rot(K, 60, 103, 'teclado (entrada)', 64, 124) + rot(K, 150, 112, 'ratón', 182, 112); },
      intro: 'Un computador tiene una unidad central que procesa y periféricos para dar órdenes y mostrar resultados.',
      q: [['¿Es el monitor un dispositivo de entrada o de salida?', 'De salida: muestra información.'], ['¿Dónde está el procesador?', 'En la torre, sobre la placa base.'], ['¿Qué dispositivo es a la vez de entrada y salida?', 'Una pantalla táctil, por ejemplo.']],
      porque: 'Todo computador sigue el mismo esquema: entrar datos, procesarlos, guardarlos y mostrar el resultado.' },
    { id: 'te_placa', fam: 'pc', n: 'Dentro de la torre: la placa base',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(14, 14, 172, 112, 3, '#7FB89A', { w: 1 }); for (var i = 0; i < 9; i++) s += K.l('M' + (20 + i * 18) + ' 20 L' + (20 + i * 18) + ' 120', '#5E9A7C', { w: .3 }); s += K.r(30, 30, 40, 40, 2, P.metal, { w: 1 }) + K.r(38, 38, 24, 24, 1, P.gris, { w: .6 }) + K.r(86, 26, 6, 56, 1, P.tinta, { w: .5 }) + K.r(96, 26, 6, 56, 1, P.tinta, { w: .5 }) + K.r(30, 92, 96, 10, 1, P.tinta, { w: .5 }) + K.r(140, 28, 36, 50, 2, P.gris, { w: .8 }) + K.c(158, 53, 14, P.metal, { w: .6 }) + K.r(140, 92, 36, 22, 2, P.azul, { w: .8 }); return s + K.t(50, 80, 'CPU', { s: 6.4, b: 1 }) + K.t(94, 90, 'RAM', { s: 6, b: 1 }) + K.t(78, 112, 'ranura gráfica', { s: 5.4, b: 1 }) + K.t(158, 84, 'disco', { s: 5.6, b: 1 }) + K.t(158, 106, 'fuente', { s: 5.6, b: 1 }); },
      intro: 'La placa base une todas las piezas: procesador, memoria, tarjeta gráfica, almacenamiento y alimentación.',
      q: [['¿Qué pieza ejecuta las instrucciones?', 'El procesador (CPU).'], ['¿Qué hace la fuente de alimentación?', 'Convierte la corriente del enchufe en la que necesitan las piezas.'], ['¿Por qué la CPU lleva un disipador o ventilador?', 'Porque se calienta al trabajar.']],
      porque: 'La placa base es como las calles de una ciudad: conecta cada pieza con las demás.' },
    { id: 'te_ram_disco', fam: 'pc', n: 'Memoria RAM y almacenamiento',
      d: function (K) { return K.suelo(100, 140, 96) + caja(K, 12, 22, 84, 76, P.amarillo) + K.r(22, 34, 64, 14, 1, P.verdeO, { w: .6 }) + K.r(28, 37, 8, 8, 0, P.tinta) + K.r(40, 37, 8, 8, 0, P.tinta) + K.r(52, 37, 8, 8, 0, P.tinta) + K.r(64, 37, 8, 8, 0, P.tinta) + K.t(54, 62, 'RAM', { s: 8, b: 1 }) + K.t(54, 74, 'rápida y temporal', { s: 5.4 }) + K.t(54, 84, 'se borra al apagar', { s: 5.4, b: 1, c: P.rojoO }) + caja(K, 104, 22, 84, 76, P.azul) + K.r(124, 32, 44, 22, 3, P.tinta, { w: .6 }) + K.t(146, 46, 'SSD', { s: 6, b: 1, c: P.blanco }) + K.t(146, 66, 'Almacenamiento', { s: 6.4, b: 1 }) + K.t(146, 76, 'disco o memoria SSD', { s: 5.4 }) + K.t(146, 86, 'guarda al apagar', { s: 5.4, b: 1, c: P.verdeO }) + K.t(100, 116, 'La RAM es la mesa de trabajo; el disco, el archivador', { s: 5.8, b: 1 }); },
      intro: 'La RAM guarda lo que se usa en este momento; el disco guarda los archivos aunque el equipo se apague.',
      q: [['¿Qué se pierde si se corta la luz sin guardar?', 'Lo que estaba solo en la RAM.'], ['¿Para qué sirve más RAM?', 'Para tener más programas abiertos sin que el equipo se vuelva lento.'], ['¿Qué ventaja tiene un SSD frente a un disco duro?', 'Es mucho más rápido y no tiene piezas móviles.']],
      porque: 'Guardar con frecuencia pasa el trabajo de la mesa (RAM) al archivador (disco).' },
    { id: 'te_bits', fam: 'pc', n: 'Bits y bytes',
      d: function (K) { var s = K.suelo(100, 140, 96), b = [0, 1, 0, 0, 0, 0, 0, 1]; b.forEach(function (v, i) { s += K.caja(28 + i * 18, 26, 16, 22, 3, v ? P.amarillo : P.gris, { w: .7 }) + K.t(36 + i * 18, 41, String(v), { s: 9, b: 1 }) + K.t(36 + i * 18, 58, String(Math.pow(2, 7 - i)), { s: 5 }); }); return s + K.t(100, 18, '8 bits = 1 byte', { s: 7, b: 1 }) + K.t(100, 72, '64 + 1 = 65 → letra «A»', { s: 6.6, b: 1 }) + K.t(100, 92, '1 KB ≈ 1 000 bytes · 1 MB ≈ 1 000 KB', { s: 5.8 }) + K.t(100, 102, '1 GB ≈ 1 000 MB · 1 TB ≈ 1 000 GB', { s: 5.8 }) + K.t(100, 124, 'Todo en el computador se guarda con ceros y unos', { s: 6, b: 1 }); },
      intro: 'El computador guarda todo como bits (0 o 1); ocho bits forman un byte, que puede representar una letra.',
      q: [['¿Cuántos valores distintos caben en un byte?', '2⁸ = 256.'], ['¿Qué número es 00000011?', '2 + 1 = 3.'], ['¿Cuántos MB tiene un archivo de 2,5 GB?', 'Unos 2 500 MB.']],
      porque: 'Un circuito solo distingue dos estados, encendido y apagado: por eso el sistema binario.' },
    { id: 'te_binario', fam: 'pc', n: 'Contar en binario',
      d: function (K) { var s = K.suelo(100, 140, 96); for (var n = 0; n < 8; n++) { var x = 14 + (n % 4) * 44, y = 18 + Math.floor(n / 4) * 52, bits = ('00' + n.toString(2)).slice(-3); s += K.r(x, y, 40, 44, 3, CO[n], { w: .7 }) + K.t(x + 20, y + 16, String(n), { s: 10, b: 1 }) + K.t(x + 20, y + 34, bits, { s: 8, b: 1 }); } return s + K.t(100, 132, 'Cada posición vale el doble que la de su derecha: 4 · 2 · 1', { s: 5.8, b: 1 }); },
      intro: 'En binario solo hay dos cifras; al llegar a 1 se pasa a la siguiente posición, que vale el doble.',
      q: [['¿Cómo se escribe 5 en binario?', '101 (4 + 1).'], ['¿Qué número es 111?', '7.'], ['¿Cuál sería el siguiente después de 111?', '1000, que vale 8.']],
      porque: 'Es el mismo sistema que el decimal, pero con base 2 en lugar de base 10.' },
    G('te_perifericos', 'pc', 'Periféricos de entrada, salida y almacenamiento', [['Teclado', 'entrada', P.verde], ['Micrófono', 'entrada', P.verde], ['Escáner', 'entrada', P.verde], ['Impresora', 'salida', P.azul], ['Altavoces', 'salida', P.azul], ['Proyector', 'salida', P.azul], ['Memoria USB', 'almacenamiento', P.amarillo], ['Pantalla táctil', 'entrada y salida', P.rosa]], 2, 16, 23, 'Entrada: lleva datos al equipo · Salida: los saca', 'Los periféricos se clasifican según el sentido en que viaja la información.', [['¿Qué tipo de periférico es una cámara web?', 'De entrada.'], ['¿Y unos auriculares con micrófono?', 'De entrada y salida.'], ['¿Para qué sirve una memoria USB?', 'Para guardar y llevar archivos de un equipo a otro.']], 'Pensar en hacia dónde viajan los datos resuelve cualquier clasificación.', { s: 7, s2: 5.4 }),
    { id: 'te_ciclo', fam: 'pc', n: 'Entrada, proceso, salida',
      d: function (K) { var s = K.suelo(100, 140, 96) + caja(K, 8, 48, 50, 34, P.verde, 'ENTRADA', 6.6) + caja(K, 75, 48, 50, 34, P.amarillo, 'PROCESO', 6.6) + caja(K, 142, 48, 50, 34, P.azul, 'SALIDA', 6.6) + caja(K, 75, 98, 50, 24, P.morado, 'MEMORIA', 6) + K.flecha(58, 65, 74, 65, P.tinta, { w: 1.4 }) + K.flecha(125, 65, 141, 65, P.tinta, { w: 1.4 }) + K.flecha(96, 82, 96, 97, P.tinta, { w: 1.2 }) + K.flecha(104, 97, 104, 82, P.tinta, { w: 1.2 }); return s + K.t(33, 38, 'teclear 2 + 3', { s: 5.4 }) + K.t(100, 38, 'la CPU suma', { s: 5.4 }) + K.t(167, 38, 'pantalla: 5', { s: 5.4 }) + K.t(100, 22, 'Así funciona cualquier sistema informático', { s: 6.2, b: 1 }); },
      intro: 'Todo sistema informático recibe datos, los procesa con ayuda de la memoria y entrega un resultado.',
      q: [['¿Qué es la entrada en un cajero automático?', 'La tarjeta, la clave y el monto que se teclea.'], ['¿Y la salida?', 'Los billetes y el recibo.'], ['¿Para qué se usa la memoria en el proceso?', 'Para guardar datos e instrucciones mientras se trabaja.']],
      porque: 'Identificar entrada, proceso y salida es el primer paso para diseñar cualquier programa.' },
    /* ─────────── SOFTWARE Y ARCHIVOS ─────────── */
    { id: 'te_capas', fam: 'sw', n: 'Hardware, sistema operativo y aplicaciones',
      d: function (K) { var C = [['Usuario', P.rosa, 36], ['Aplicaciones', P.amarillo, 62], ['Sistema operativo', P.azul, 88], ['Hardware', P.gris, 114]], s = K.suelo(100, 140, 96); C.forEach(function (q, i) { var w = 80 + i * 26; s += K.caja(100 - w / 2, q[2] - 16, w, 20, 6, q[1], { w: .8 }) + K.t(100, q[2] - 3, q[0], { s: 6.6, b: 1 }); }); return s + K.t(100, 12, 'navegador, procesador de texto, juegos', { s: 5.2 }) + K.t(178, 76, 'Windows,', { s: 5, a: 'end' }) + K.t(178, 83, 'Android, Linux', { s: 5, a: 'end' }) + K.t(100, 132, 'El sistema operativo es el intermediario', { s: 6, b: 1 }); },
      intro: 'El sistema operativo administra el hardware y permite que las aplicaciones lo usen sin conocer sus detalles.',
      q: [['¿Qué sistema operativo usa la mayoría de los teléfonos?', 'Android; muchos otros usan iOS.'], ['¿Es el navegador un sistema operativo?', 'No: es una aplicación.'], ['¿Qué pasa si se quita el sistema operativo?', 'El equipo enciende pero no puede ejecutar aplicaciones.']],
      porque: 'Gracias al sistema operativo, el mismo programa funciona en equipos con piezas distintas.' },
    { id: 'te_carpetas', fam: 'sw', n: 'Organizar archivos en carpetas',
      d: function (K) { var s = K.suelo(100, 140, 96), F = function (x, y, t, c) { return K.p('M' + x + ' ' + (y + 2) + ' L' + (x + 10) + ' ' + (y + 2) + ' L' + (x + 13) + ' ' + y + ' L' + (x + 26) + ' ' + y + ' L' + (x + 26) + ' ' + (y + 16) + ' L' + x + ' ' + (y + 16) + ' Z', c || P.amarillo, { w: .7 }) + K.t(x + 30, y + 11, t, { s: 5.6, b: 1, a: 'start' }); }; s += F(16, 14, 'Colegio') + K.l('M24 30 L24 108', P.grisO, { w: .6 }) + K.l('M24 42 L34 42 M24 70 L34 70 M24 104 L34 104', P.grisO, { w: .6 }) + F(34, 34, 'Matemáticas') + F(34, 62, 'Lengua') + F(34, 96, 'Fotos', P.azul); s += K.l('M42 50 L42 56 L54 56 M42 78 L42 88 L54 88', P.grisO, { w: .5 }) + K.r(54, 51, 10, 10, 1, P.blanco, { w: .6 }) + K.t(68, 58, 'tarea_fracciones_2026-03-10.docx', { s: 5, a: 'start' }) + K.r(54, 83, 10, 10, 1, P.blanco, { w: .6 }) + K.t(68, 90, 'resumen_cuento.pdf', { s: 5, a: 'start' }); return s + K.t(100, 128, 'nombre claro + fecha + extensión', { s: 6.4, b: 1 }) + K.t(100, 138, 'La extensión indica el tipo: .docx, .pdf, .jpg', { s: 5.4 }); },
      intro: 'Las carpetas agrupan archivos como un árbol; un buen nombre de archivo dice qué es y de cuándo.',
      q: [['¿Qué indica la extensión .jpg?', 'Que es una imagen.'], ['¿Por qué poner la fecha como año-mes-día?', 'Para que los archivos se ordenen solos por fecha.'], ['¿Dónde guardarías una foto del paseo escolar?', 'En Colegio/Fotos.']],
      porque: 'Un archivo bien guardado se encuentra en segundos; uno mal guardado puede perderse.' },
    G('te_extensiones', 'sw', 'Tipos de archivo', [['.docx · .odt', 'documento de texto'], ['.pdf', 'documento para leer o imprimir'], ['.xlsx · .ods', 'hoja de cálculo'], ['.pptx', 'presentación'], ['.jpg · .png', 'imagen'], ['.mp3', 'audio'], ['.mp4', 'vídeo'], ['.zip', 'carpeta comprimida']], 2, 16, 23, 'Nunca abras un .exe que llegó por correo sin saber qué es', 'La extensión, después del punto, dice qué programa abre el archivo.', [['¿Qué formato conviene para enviar un trabajo que no se debe modificar?', 'PDF.'], ['¿Qué hace un .zip?', 'Reúne y comprime varios archivos en uno.'], ['¿Por qué es peligroso un .exe desconocido?', 'Porque es un programa que puede contener virus.']], 'Conocer la extensión evita abrir archivos peligrosos y elegir el formato correcto para compartir.', { s: 7.4, s2: 5.4 }),
    { id: 'te_hoja_calculo', fam: 'sw', n: 'La hoja de cálculo',
      d: function (K) { var s = K.suelo(100, 140, 96), cols = ['', 'A', 'B', 'C', 'D'], F = [['1', 'Producto', 'Cant.', 'Precio', 'Total'], ['2', 'Lápiz', '10', '0,50', '5,00'], ['3', 'Cuaderno', '4', '2,00', '8,00'], ['4', 'Regla', '2', '1,25', '2,50'], ['5', '', '', 'Suma', '15,50']], W = [12, 46, 30, 34, 38]; var x = 18; cols.forEach(function (c, j) { s += K.r(x, 22, W[j], 10, 0, P.gris, { w: .5 }) + K.t(x + W[j] / 2, 29, c, { s: 5.2, b: 1 }); x += W[j]; }); F.forEach(function (f, i) { var x2 = 18, y = 32 + i * 12; f.forEach(function (v, j) { var sel = i === 4 && j === 4; s += K.r(x2, y, W[j], 12, 0, j === 0 ? P.gris : sel ? P.amarillo : i === 0 ? P.azul : P.blanco, { w: sel ? 1.2 : .4 }) + K.t(j > 1 ? x2 + W[j] - 2 : x2 + 2, y + 8, v, { s: 5.2, b: i === 0 || j === 0 ? 1 : 0, a: j > 1 ? 'end' : 'start' }); x2 += W[j]; }); }); return s + K.r(18, 8, 160, 10, 1, P.blanco, { w: .6 }) + K.t(20, 15, 'E5   =SUMA(E2:E4)', { s: 5.6, b: 1, a: 'start' }) + K.t(100, 104, 'En E2: =C2*D2 (cantidad × precio)', { s: 6, b: 1 }) + K.t(100, 118, 'Al cambiar un dato, el total se recalcula solo', { s: 5.8 }); },
      intro: 'La hoja de cálculo organiza datos en celdas y usa fórmulas que se recalculan al cambiar un valor.',
      q: [['¿Qué fórmula calcula el total del cuaderno?', '=C3*D3.'], ['¿Qué pasa si se compran 20 lápices?', 'E2 pasa a 10,00 y la suma a 20,50 automáticamente.'], ['¿Cómo se nombra una celda?', 'Con la letra de la columna y el número de la fila: E5.']],
      porque: 'Escribir fórmulas en vez de resultados hace que la tabla se corrija sola.' },
    { id: 'te_nube', fam: 'sw', n: 'Guardar en la nube',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.p('M64 46 C56 46 52 38 58 32 C58 22 72 18 78 26 C84 14 104 14 108 28 C120 24 132 32 128 42 C134 46 130 54 122 54 L68 54 C60 54 58 48 64 46 Z', P.azul, { w: 1 }) + K.t(94, 42, 'servidores', { s: 5.8, b: 1 }) + monitor(K, 12, 80, 40, 28) + K.r(84, 82, 22, 36, 4, P.tinta, { w: .8 }) + K.r(86, 86, 18, 26, 1, P.pantalla, { w: .3 }) + K.r(140, 86, 46, 28, 2, P.tinta, { w: .8 }) + K.r(143, 89, 40, 20, 1, P.pantalla, { w: .3 }) + K.p('M136 114 L190 114 L186 120 L140 120 Z', P.metal, { w: .6 }) + K.flecha(40, 78, 70, 58, P.verdeO, { w: 1.2 }) + K.flecha(95, 80, 95, 58, P.verdeO, { w: 1.2 }) + K.flecha(160, 84, 120, 58, P.verdeO, { w: 1.2 }); return s + K.t(100, 136, 'El mismo archivo, desde cualquier equipo con internet', { s: 5.8, b: 1 }); },
      intro: 'Guardar en la nube es guardar los archivos en servidores de internet en lugar de solo en el propio equipo.',
      q: [['¿Qué ventaja tiene la nube si se pierde el teléfono?', 'Los archivos siguen a salvo en el servidor.'], ['¿Qué se necesita para acceder?', 'Conexión a internet y una cuenta con contraseña.'], ['¿Qué riesgo hay?', 'Si alguien roba la contraseña, puede ver los archivos.']],
      porque: 'La nube es una copia de seguridad automática, pero depende de proteger bien la cuenta.' },
    /* ─────────── INTERNET Y REDES ─────────── */
    { id: 'te_internet', fam: 'red', n: 'Cómo viaja una página web',
      d: function (K) { var s = K.suelo(100, 140, 96) + monitor(K, 8, 50, 36, 26) + K.caja(54, 56, 22, 14, 4, P.gris, { w: .8 }) + K.l('M60 56 L58 46 M70 56 L72 46', P.tinta, { w: .8 }) + K.p('M88 52 C82 52 80 44 86 40 C88 32 98 30 102 36 C108 28 122 30 122 40 C128 42 128 52 120 52 Z', P.azul, { w: .8 }) + K.caja(152, 36, 30, 52, 6, P.gris, { w: .9 }); for (var i = 0; i < 4; i++) s += K.r(156, 42 + i * 11, 22, 7, 1, P.tinta, { w: .3 }) + K.c(174, 45.5 + i * 11, 1, P.verde); s += K.flecha(44, 64, 54, 64, P.verdeO, { w: 1 }) + K.flecha(76, 62, 86, 52, P.verdeO, { w: 1 }) + K.flecha(122, 46, 150, 58, P.verdeO, { w: 1 }) + K.flecha(150, 72, 76, 72, P.rojoO, { w: 1, curva: [112, 98] }); return s + K.t(26, 96, 'tu equipo', { s: 5.4, b: 1 }) + K.t(65, 82, 'router', { s: 5.4, b: 1 }) + K.t(104, 26, 'internet', { s: 5.6, b: 1 }) + K.t(167, 98, 'servidor', { s: 5.4, b: 1 }) + K.t(100, 104, '1 pides la página · 2 el servidor la envía en paquetes', { s: 5.4 }) + K.t(100, 122, 'Cada equipo tiene una dirección (IP), como una casa', { s: 5.8, b: 1 }); },
      intro: 'Al abrir una web, el equipo pide la página a un servidor lejano, que la envía troceada en paquetes.',
      q: [['¿Qué es un servidor?', 'Un computador que guarda páginas o archivos y los envía cuando se piden.'], ['¿Qué hace el router?', 'Conecta la red de casa con internet y dirige los paquetes.'], ['¿Por qué se envía en paquetes?', 'Para que viajen por caminos distintos y se reenvíe solo lo que se pierde.']],
      porque: 'Internet no es un lugar: es una red de redes que se pasan paquetes de equipo en equipo.' },
    { id: 'te_url', fam: 'red', n: 'Las partes de una dirección web',
      d: function (K) { var P1 = [['https://', P.verde], ['www.', P.gris], ['ejemplo', P.amarillo], ['.edu.co', P.azul], ['/cursos/mate', P.rosa]], s = K.suelo(100, 140, 96), x = 12; P1.forEach(function (q) { var w = q[0].length * 3.5 + 6; s += K.r(x, 34, w, 18, 2, q[1], { w: .7 }) + K.t(x + w / 2, 46, q[0], { s: 5.6, b: 1 }); x += w + 2; }); return s + K.c(18, 26, 3.4, P.verdeO, { w: .5 }) + K.t(30, 72, 'protocolo seguro', { s: 5.2, b: 1 }) + K.t(30, 80, '(el candado)', { s: 4.8 }) + K.t(88, 72, 'nombre del sitio', { s: 5.2, b: 1 }) + K.t(126, 80, 'dominio: tipo y país', { s: 5.2, b: 1 }) + K.t(168, 72, 'ruta: la página', { s: 5.2, b: 1 }) + K.t(100, 104, 'Antes de escribir una contraseña, revisa que diga https', { s: 5.8, b: 1 }) + K.t(100, 116, 'y que el nombre del sitio sea exactamente el correcto', { s: 5.6 }); },
      intro: 'Una dirección web (URL) dice cómo se conecta, a qué sitio y a qué página dentro de él.',
      q: [['¿Qué indica la «s» de https?', 'Que la conexión va cifrada.'], ['¿Qué dice el dominio .edu.co?', 'Que es un sitio educativo de Colombia.'], ['¿Qué tiene de raro «ejemp1o.com»?', 'Un 1 en lugar de la l: puede ser un sitio falso.']],
      porque: 'Muchos engaños usan direcciones casi iguales a las reales: leerla con calma es la primera defensa.' },
    { id: 'te_wifi', fam: 'red', n: 'Wifi, cable y datos móviles',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.caja(80, 70, 40, 16, 4, P.gris, { w: .9 }) + K.l('M90 70 L86 54 M110 70 L114 54', P.tinta, { w: .9 }); for (var r = 1; r <= 3; r++) s += K.l('M' + (100 - r * 10) + ' ' + (60 - r * 4) + ' Q100 ' + (50 - r * 10) + ' ' + (100 + r * 10) + ' ' + (60 - r * 4), P.azulO, { w: 1 }); s += K.r(22, 96, 30, 20, 2, P.tinta, { w: .7 }) + K.l('M52 108 C64 108 70 84 80 80', P.amarillo, { w: 2 }) + K.r(154, 92, 14, 26, 3, P.tinta, { w: .6 }) + K.l('M176 20 L176 60 M170 26 L182 26 M168 34 L184 34', P.grisO, { w: 1 }); return s + K.t(37, 126, 'cable: estable', { s: 5.4, b: 1 }) + K.t(100, 98, 'router wifi', { s: 5.6, b: 1 }) + K.t(100, 20, 'ondas de radio', { s: 5.4 }) + K.t(161, 126, 'datos móviles', { s: 5.4, b: 1 }) + K.t(176, 14, 'antena', { s: 5 }) + K.t(100, 140, 'Las paredes y la distancia debilitan el wifi', { s: 5.6, b: 1 }); },
      intro: 'Un equipo se conecta por cable, por wifi (ondas del router) o por datos móviles (ondas de una antena).',
      q: [['¿Qué conexión suele ser más estable?', 'El cable.'], ['¿Por qué el wifi va peor en la habitación del fondo?', 'Porque las paredes y la distancia debilitan la señal.'], ['¿Conviene usar un wifi público para entrar al banco?', 'No: otros pueden espiar la conexión.']],
      porque: 'Wifi y datos móviles son ondas de radio: viajan sin cable, pero se debilitan con obstáculos.' },
    { id: 'te_buscar', fam: 'red', n: 'Buscar bien en internet',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(20, 16, 160, 16, 8, P.blanco, { w: 1 }) + K.c(32, 24, 4, 'none', { w: 1 }) + K.l('M35 27 L39 31', P.tinta, { w: 1.2 }) + K.t(44, 27, '"ciclo del agua" filetype:pdf site:.edu', { s: 5.8, a: 'start' }); [['"…"', 'frase exacta'], ['site:', 'solo en ese tipo de sitio'], ['filetype:', 'solo ese tipo de archivo'], ['−palabra', 'excluye resultados']].forEach(function (q, i) { s += K.r(20 + (i % 2) * 82, 42 + Math.floor(i / 2) * 26, 78, 22, 3, CO[i], { w: .7 }) + K.t(59 + (i % 2) * 82, 52 + Math.floor(i / 2) * 26, q[0], { s: 6.4, b: 1 }) + K.t(59 + (i % 2) * 82, 60 + Math.floor(i / 2) * 26, q[1], { s: 4.8 }); }); return s + K.t(100, 106, 'Comprueba: ¿quién lo escribe? ¿cuándo? ¿lo dicen otras fuentes?', { s: 5.4, b: 1 }) + K.t(100, 124, 'Copia la fuente para citarla en tu trabajo', { s: 5.8 }); },
      intro: 'Con unos pocos operadores el buscador devuelve resultados más precisos; luego hay que comprobar la fuente.',
      q: [['¿Qué hacen las comillas?', 'Buscan la frase exacta, con las palabras en ese orden.'], ['¿Cómo buscar solo en sitios del gobierno?', 'Añadiendo site:.gov o el dominio oficial del país.'], ['¿Por qué comparar varias fuentes?', 'Porque una sola puede estar equivocada o desactualizada.']],
      porque: 'Encontrar es fácil; saber si es cierto es la parte importante.' },
    G('te_redes_tipos', 'red', 'Tipos de red por su tamaño', [['PAN', 'personal: auriculares bluetooth'], ['LAN', 'local: casa, aula, oficina'], ['MAN', 'ciudad: red de un municipio'], ['WAN', 'amplia: países, internet']], 2, 24, 40, 'Internet es la WAN más grande: une millones de redes', 'Las redes se nombran según el área que cubren.', [['¿Qué tipo de red es el wifi de casa?', 'Una LAN.'], ['¿Qué es internet?', 'Una WAN mundial que une muchas redes.'], ['¿Qué red usas al conectar el reloj al teléfono?', 'Una PAN.']], 'Las redes pequeñas se conectan entre sí hasta formar internet.', { s: 10, s2: 5.8 }),
    /* ─────────── PROGRAMACIÓN ─────────── */
    { id: 'te_algoritmo', fam: 'prg', n: 'Un algoritmo de la vida diaria',
      d: function (K) { var Pa = ['1 Echa agua en la tetera', '2 Enciende el fuego', '3 ¿Hierve el agua?', '4 Pon la bolsa de té en la taza', '5 Sirve el agua', '6 Espera 3 minutos'], s = K.suelo(100, 140, 96); Pa.forEach(function (t, i) { var y = 12 + i * 20, dec = i === 2; s += dec ? K.pl([[100, y], [150, y + 8], [100, y + 16], [50, y + 8]], P.amarillo, { w: .8 }) : K.r(50, y, 100, 16, 4, CO[i], { w: .7 }); s += K.t(100, y + 10.5, t, { s: 5.6, b: 1 }); if (i < 5) s += K.flecha(100, y + 16, 100, y + 20, P.tinta, { w: .9, p: 3 }); }); return s + K.l('M150 60 L170 60 L170 52 L150 52', P.rojoO, { w: .9 }) + K.t(172, 48, 'no: espera', { s: 5, b: 1, c: P.rojoO, a: 'start' }) + K.t(110, 74, 'sí', { s: 5, b: 1, c: P.verdeO, a: 'start' }); },
      intro: 'Un algoritmo es una lista ordenada y precisa de pasos para resolver un problema.',
      q: [['¿Qué pasa si se cambia el orden de los pasos 2 y 1?', 'Se calienta la tetera vacía: el orden importa.'], ['¿Qué tiene de especial el paso 3?', 'Es una decisión: según la respuesta se sigue o se espera.'], ['Escribe un algoritmo para lavarte las manos.', 'Abrir el grifo, mojar, enjabonar 20 s, enjuagar, cerrar y secar.']],
      porque: 'Un computador solo hace lo que se le dice, paso a paso: por eso el algoritmo debe ser exacto.' },
    { id: 'te_diagrama', fam: 'prg', n: 'Símbolos del diagrama de flujo',
      d: function (K) { var s = K.suelo(100, 140, 96); s += K.r(14, 18, 50, 18, 9, P.verde, { w: .8 }) + K.t(39, 30, 'inicio / fin', { s: 5.6, b: 1 }) + K.r(76, 18, 50, 18, 1, P.azul, { w: .8 }) + K.t(101, 30, 'proceso', { s: 5.6, b: 1 }) + K.pl([[138, 36], [146, 18], [190, 18], [182, 36]], P.rosa, { w: .8 }) + K.t(164, 30, 'entrada / salida', { s: 5, b: 1 }) + K.pl([[39, 50], [64, 62], [39, 74], [14, 62]], P.amarillo, { w: .8 }) + K.t(39, 64, 'decisión', { s: 5.4, b: 1 }) + K.flecha(80, 62, 120, 62, P.tinta, { w: 1.2 }) + K.t(100, 56, 'flujo', { s: 5.4, b: 1 }) + K.c(160, 62, 9, P.morado, { w: .8 }) + K.t(160, 64, 'A', { s: 6, b: 1 }) + K.t(160, 80, 'conector', { s: 5.2, b: 1 }); return s + K.t(100, 100, 'Ejemplo: leer la edad → ¿edad ≥ 18?', { s: 6, b: 1 }) + K.t(100, 110, 'sí → «puede votar» · no → «aún no»', { s: 5.6 }) + K.t(100, 128, 'Cada forma tiene un significado fijo', { s: 5.8 }); },
      intro: 'El diagrama de flujo dibuja un algoritmo con formas que tienen un significado acordado.',
      q: [['¿Qué forma se usa para una pregunta de sí o no?', 'El rombo de decisión.'], ['¿Cuántas salidas tiene un rombo?', 'Dos: sí y no.'], ['¿Qué forma tiene el principio y el final?', 'Un óvalo o rectángulo redondeado.']],
      porque: 'Dibujar el algoritmo antes de programar ayuda a ver errores de lógica.' },
    { id: 'te_secuencia', fam: 'prg', n: 'Programar con bloques: secuencia',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(14, 14, 96, 112, 3, P.blanco, { w: .7 }); s += K.p('M20 22 Q20 16 30 16 L84 16 Q94 16 94 22 L94 30 L20 30 Z', P.amarillo, { w: .7 }) + K.t(24, 26, 'al hacer clic', { s: 5.4, b: 1, a: 'start' }); [['mover 50 pasos', P.azul], ['girar 90°', P.azul], ['mover 50 pasos', P.azul], ['girar 90°', P.azul], ['decir «¡Hola!»', P.morado]].forEach(function (q, i) { s += bloque(K, 20, 32 + i * 16, 78, q[0], q[1]); }); s += K.l('M130 110 L130 70 L170 70', P.rojoO, { w: 1.4 }) + K.p('M166 64 L178 70 L166 76 Z', P.verde, { w: .8 }) + K.c(130, 110, 2, P.rojoO); return s + K.t(152, 122, 'recorrido del personaje', { s: 5.2, b: 1 }) + K.t(152, 40, 'Se ejecutan', { s: 5.6, b: 1 }) + K.t(152, 48, 'de arriba abajo', { s: 5.6 }); },
      intro: 'En la programación por bloques, las instrucciones encajan como piezas y se ejecutan en orden.',
      q: [['¿En qué orden se ejecutan los bloques?', 'De arriba abajo, uno tras otro.'], ['¿Qué forma dibuja el personaje si se repite «mover 50, girar 90°» cuatro veces?', 'Un cuadrado.'], ['¿Qué bloque inicia el programa?', 'El evento «al hacer clic».']],
      porque: 'La secuencia es la estructura más simple: el orden de las órdenes cambia el resultado.' },
    { id: 'te_bucle', fam: 'prg', n: 'Repetir: el bucle',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(12, 20, 92, 90, 3, P.blanco, { w: .7 }) + K.p('M18 26 L94 26 L94 40 L30 40 L30 82 L94 82 L94 92 L18 92 Z', P.naranja, { w: .8 }) + K.t(22, 36, 'repetir 4 veces', { s: 5.6, b: 1, a: 'start' }) + bloque(K, 32, 46, 60, 'mover 40 pasos', P.azul) + bloque(K, 32, 62, 60, 'girar 90°', P.azul); s += K.r(128, 40, 44, 44, 0, 'none', { w: 1.6 }) + K.l('M128 84 L128 40 L172 40 L172 84 L128 84', P.rojoO, { w: 1.6 }); return s + K.t(150, 98, 'resultado: un cuadrado', { s: 5.6, b: 1 }) + K.t(100, 124, 'Con el bucle: 3 bloques en lugar de 8', { s: 6.2, b: 1 }) + K.t(100, 134, 'Para un hexágono: repetir 6 veces, girar 60°', { s: 5.4 }); },
      intro: 'Un bucle repite un grupo de instrucciones un número de veces o mientras se cumpla una condición.',
      q: [['¿Cuántas veces se mueve el personaje?', 'Cuatro.'], ['¿Qué giro hace falta para un triángulo equilátero?', '120°, repitiendo 3 veces.'], ['¿Qué ventaja tiene el bucle?', 'El programa es más corto y fácil de cambiar.']],
      porque: 'El giro total de un polígono es 360°: por eso se divide 360 entre el número de lados.' },
    { id: 'te_condicional', fam: 'prg', n: 'Decidir: el condicional',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(12, 14, 112, 112, 3, P.blanco, { w: .7 }) + K.p('M18 20 L118 20 L118 34 L30 34 L30 58 L118 58 L118 70 L30 70 L30 96 L118 96 L118 106 L18 106 Z', P.amarillo, { w: .8 }) + K.t(22, 30, 'si ¿toca el borde?', { s: 5.6, b: 1, a: 'start' }) + bloque(K, 32, 40, 82, 'girar 180°', P.azul) + K.t(22, 66, 'si no', { s: 5.6, b: 1, a: 'start' }) + bloque(K, 32, 76, 82, 'mover 10 pasos', P.azul); return s + K.r(138, 30, 50, 70, 0, P.gris, { w: 1.2 }) + K.c(178, 64, 5, P.verde, { w: .7 }) + K.flecha(172, 64, 150, 64, P.rojoO, { w: 1.2 }) + K.t(163, 112, 'rebota en la pared', { s: 5.4, b: 1 }) + K.t(100, 136, 'Si se cumple la condición hace una cosa; si no, otra', { s: 5.6, b: 1 }); },
      intro: 'El condicional hace que el programa elija qué hacer según si una condición es verdadera o falsa.',
      q: [['¿Qué hace el personaje si no toca el borde?', 'Avanza 10 pasos.'], ['Escribe un condicional para la nota de un examen.', 'Si nota ≥ 6, decir «aprobado»; si no, «a repasar».'], ['¿Qué pasaría sin el condicional?', 'El personaje saldría de la pantalla.']],
      porque: 'Con condicionales el programa reacciona a lo que pasa, en lugar de seguir siempre igual.' },
    { id: 'te_variable', fam: 'prg', n: 'Las variables',
      d: function (K) { var s = K.suelo(100, 140, 96); [['puntos', '0 → 10 → 20', P.amarillo], ['vidas', '3 → 2', P.rosa], ['nombre', '«Ana»', P.azul]].forEach(function (q, i) { var x = 14 + i * 60; s += K.caja(x, 36, 52, 40, 6, q[2], { w: .9 }) + K.r(x + 8, 30, 36, 10, 2, P.blanco, { w: .6 }) + K.t(x + 26, 37.5, q[0], { s: 5.6, b: 1 }) + K.t(x + 26, 60, q[1], { s: 6, b: 1 }); }); return s + K.t(100, 18, 'Una variable es una caja con nombre que guarda un dato', { s: 5.8, b: 1 }) + bloque(K, 30, 90, 140, 'al tocar la moneda: sumar 10 a puntos', P.naranja, 5.6) + K.t(100, 124, 'El nombre no cambia; el valor sí', { s: 6.2, b: 1 }); },
      intro: 'Una variable guarda un dato con un nombre, para usarlo y cambiarlo mientras el programa funciona.',
      q: [['¿Cuánto vale «puntos» tras tocar 3 monedas?', '30.'], ['¿Qué tipo de dato guarda «nombre»?', 'Un texto.'], ['¿Por qué no escribir el número directamente?', 'Porque cambia durante el juego; la variable lo recuerda.']],
      porque: 'Las variables son la memoria del programa: sin ellas no se podría llevar la cuenta de nada.' },
    { id: 'te_depurar', fam: 'prg', n: 'Encontrar el error: depurar',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(12, 16, 104, 98, 3, P.blanco, { w: .7 }), B = [['repetir 4 veces', P.naranja], ['mover 40 pasos', P.azul], ['girar 80°', P.rojo], ['fin', P.naranja]]; B.forEach(function (q, i) { s += bloque(K, 18 + (i === 1 || i === 2 ? 8 : 0), 22 + i * 18, 84, q[0], q[1]); }); s += K.c(104, 63, 7, 'none', { w: 1.6 }) + K.l('M128 96 L128 56 L166 50 L172 88 Z', P.rojoO, { w: 1.4 }); return s + K.t(150, 108, 'no cierra el cuadrado', { s: 5.4, b: 1, c: P.rojoO }) + K.t(64, 104, 'error: debe girar 90°', { s: 5.4, b: 1, c: P.rojoO }) + K.t(100, 128, 'Probar, observar, corregir y volver a probar', { s: 6, b: 1 }); },
      intro: 'Depurar es buscar y corregir los errores de un programa probándolo paso a paso.',
      q: [['¿Qué error tiene el programa?', 'Gira 80° en lugar de 90°.'], ['¿Cómo se encuentra un error?', 'Ejecutando paso a paso y comparando con lo esperado.'], ['¿Es malo equivocarse al programar?', 'No: todos los programas tienen errores que se corrigen probando.']],
      porque: 'En inglés al error se le llama «bug» (bicho); depurar es quitar los bichos.' }
  ];
  MO.agregar('tecno', L, { nombre: 'Tecnología e informática', familias: FAM, materias: /^(tecno)$/ });
})();
