/* b6_lib_contabilidad2.js — Contabilidad (2/3): estados financieros, inventarios, costos y precios. 33 modelos.
   Materia `conta`. Prefijo `ct_`. Cargar después de b6_lib_contabilidad.js. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('ct_resultados')) return;
  var P = { papel: '#FBF7EE', azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', madera: '#B8946A', metal: '#C8CED4' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { doc: 'Documentos comerciales', cue: 'Las cuentas', reg: 'El registro contable', est: 'Estados financieros', inv: 'Inventarios', cos: 'Costos y precios', ban: 'Caja, bancos y dinero', nom: 'Nómina e impuestos', ges: 'Gestión, control y ética' };
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + f1 * .35, q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + (o && o.tit ? K.t(100, 14, o.tit, { s: 7, b: 1 }) : '') + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  function tabla(K, x, y, ws, filas, o) {
    o = o || {}; var h = o.h || 10, fs = o.s || 5.2, s = '', W = 0; ws.forEach(function (w) { W += w; });
    filas.forEach(function (f, i) {
      var yy = y + i * h, cab = i === 0 && !o.sinCab, tot = String(f[0]).charAt(0) === '=', cx = x;
      s += K.r(x, yy, W, h, 0, cab ? (o.cab || P.azul) : tot ? P.amarillo : P.blanco, { w: .6 });
      ws.forEach(function (w, j) {
        var tx = String(f[j] == null ? '' : f[j]); if (j === 0 && tot) tx = tx.slice(1);
        var num = j > 0 && !cab && /^[−\-+$\d(]/.test(tx);
        s += K.t(num ? cx + w - 2 : cx + 2, yy + h / 2 + fs * .36, tx, { s: fs, b: cab || tot ? 1 : 0, a: num ? 'end' : 'start' });
        if (j > 0) s += K.l('M' + cx + ' ' + yy + ' L' + cx + ' ' + (yy + h), P.grisO, { w: .4 });
        cx += w;
      });
    });
    return s;
  }
  function formula(K, piezas, y, o) { o = o || {}; var k = o.k || 4.3, fs = o.s || 7, g = 3, n = piezas.length, fijo = n * 12 + g * (n - 1), tot = piezas.reduce(function (a, q) { return a + q[0].length * k; }, 0) + fijo; if (tot > 178) { var f = (178 - fijo) / (tot - fijo); k *= f; fs *= f; tot = 178; } var x = 100 - tot / 2, s = ''; piezas.forEach(function (q) { var w = q[0].length * k + 12; s += K.r(x, y, w, 18, 3, q[1], { w: .8 }) + K.t(x + w / 2, y + 12.5, q[0], { s: +fs.toFixed(2), b: 1 }); x += w + g; }); return s; }
  function ejes(K, x, y, w, h, ex, ey) { return K.flecha(x, y + h, x + w, y + h, P.tinta, { w: 1 }) + K.flecha(x, y + h, x, y, P.tinta, { w: 1 }) + K.t(x + w, y + h + 9, ex, { s: 5.4, a: 'end' }) + K.t(x + 4, y + 3, ey, { s: 5.4, a: 'start' }); }
  function linea(K, pts, col, w) { return K.l('M' + pts.map(function (p) { return p[0] + ' ' + p[1]; }).join(' L'), col, { w: w || 1.6 }); }
  function caja(K, x, y, w, h, col, txt, fs) { return K.r(x, y, w, h, 3, col, { w: .9 }) + (txt ? K.t(x + w / 2, y + h / 2 + 2.3, txt, { s: fs || 6.2, b: 1 }) : ''); }
  function persona(K, x, y, col) { return K.c(x, y, 6, P.piel, { w: .8 }) + K.p('M' + (x - 9) + ' ' + (y + 26) + ' Q' + (x - 9) + ' ' + (y + 8) + ' ' + x + ' ' + (y + 8) + ' Q' + (x + 9) + ' ' + (y + 8) + ' ' + (x + 9) + ' ' + (y + 26) + ' Z', col, { w: .8 }); }
  function pila(K, x, base, w, partes) { var s = '', y = base; partes.forEach(function (q) { y -= q[0]; s += K.caja(x, y, w, q[0], 5, q[1], { w: .8 }) + (q[2] ? K.t(x + w / 2, y + q[0] / 2 + 2.2, q[2], { s: 5.4, b: 1 }) : ''); }); return s; }

  var L = [
    /* ─────────── ESTADOS FINANCIEROS ─────────── */
    { id: 'ct_resultados', fam: 'est', n: 'El estado de resultados',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 12, 'Comercial Río · del 1 de enero al 31 de diciembre', { s: 5.6, b: 1 }) + tabla(K, 26, 16, [104, 44], [['Concepto', 'Importe'], ['Ventas netas', '50 000'], ['(−) Costo de ventas', '(30 000)'], ['=Utilidad bruta', '20 000'], ['(−) Gastos de operación', '(12 000)'], ['=Utilidad operativa', '8 000'], ['(−) Gastos financieros', '(1 000)'], ['=Utilidad antes de impuestos', '7 000'], ['(−) Impuesto (25 % del ejemplo)', '(1 750)'], ['=Utilidad neta', '5 250']], { h: 11.4, s: 5.6 }) + K.t(100, 140, 'Mide lo ganado en un periodo, de arriba abajo', { s: 5.6 }); },
      intro: 'El estado de resultados resta a las ventas cada costo y gasto hasta llegar a la utilidad neta del periodo.',
      q: [['¿Cuál es la utilidad bruta?', '50 000 − 30 000 = 20 000.'], ['¿Qué parte de las ventas es utilidad neta?', '5 250 ÷ 50 000 = 10,5 %.'], ['¿Por qué se indica el periodo?', 'Porque mide un tiempo (un año), no un día como el balance.']],
      porque: 'Ordenar los gastos por escalones muestra en qué paso se va la ganancia.' },
    { id: 'ct_cascada', fam: 'est', n: 'De las ventas a la utilidad neta',
      d: function (K) { var B = [['Ventas', 0, 50, P.verde], ['Costo', 20, 30, P.rojo], ['Gastos', 8, 12, P.rojo], ['Interés', 7, 1, P.rojo], ['Impuesto', 5.25, 1.75, P.rojo], ['Neta', 0, 5.25, P.amarillo]], s = K.suelo(100, 140, 96) + K.l('M20 118 L186 118', P.tinta, { w: .9 }); B.forEach(function (q, i) { var x = 24 + i * 27, y = 118 - (q[1] + q[2]) * 1.9, h = q[2] * 1.9; s += K.caja(x, y, 20, Math.max(h, 1.6), 4, q[3], { w: .8 }) + K.t(x + 10, 128, q[0], { s: 5.2, b: 1 }) + K.t(x + 10, y - 3, (i && i < 5 ? '−' : '') + String(q[2]).replace('.', ',') + ' mil', { s: 4.8 }); if (i < 5) s += K.l('M' + (x + 20) + ' ' + (118 - (i ? q[1] : 50) * 1.9) + ' L' + (x + 27) + ' ' + (118 - (i ? q[1] : 50) * 1.9), P.grisO, { w: .5 }); }); return s + K.t(100, 140, 'Cada barra roja baja el escalón', { s: 5.8, b: 1 }); },
      intro: 'Una gráfica en cascada muestra cómo cada costo y gasto va restando a las ventas.',
      q: [['¿Qué barra roja es la mayor?', 'El costo de ventas: 30 000.'], ['¿Cuánto queda tras costo y gastos de operación?', '8 000.'], ['¿Qué pasa si el costo sube a 40 000?', 'La utilidad neta baja a 0 o queda en pérdida, según los impuestos.']],
      porque: 'La cascada deja ver de un golpe qué partida se lleva la mayor parte de lo vendido.' },
    { id: 'ct_cambios_pat', fam: 'est', n: 'Estado de cambios en el patrimonio',
      d: function (K) { return K.suelo(100, 140, 96) + tabla(K, 26, 18, [104, 44], [['Movimiento del año', 'Importe'], ['Patrimonio al 1 de enero', '40 000'], ['(+) Utilidad neta del año', '5 250'], ['(+) Nuevos aportes de socios', '2 000'], ['(−) Dividendos repartidos', '(1 500)'], ['=Patrimonio al 31 de diciembre', '45 750']], { h: 14, s: 6 }) + K.t(100, 116, '40 000 + 5 250 + 2 000 − 1 500 = 45 750', { s: 6.6, b: 1 }) + K.t(100, 128, 'Explica por qué cambió lo que es de los dueños', { s: 5.8 }); },
      intro: 'Este estado explica cómo pasó el patrimonio de su valor inicial a su valor final en el año.',
      q: [['¿Qué aumenta el patrimonio?', 'La utilidad y los nuevos aportes.'], ['¿Qué lo disminuye?', 'Las pérdidas y los dividendos o retiros.'], ['¿Con qué estado se conecta la utilidad neta?', 'Con el estado de resultados.']],
      porque: 'Los estados se encadenan: la utilidad del estado de resultados entra al patrimonio del balance.' },
    G('ct_estados', 'est', 'Los estados financieros', [['Situación financiera', 'qué tiene y qué debe, a una fecha'], ['Resultados', 'cuánto ganó en el periodo'], ['Cambios en el patrimonio', 'cómo variaron los fondos propios'], ['Flujos de efectivo', 'de dónde vino y a dónde fue el dinero'], ['Notas', 'explicaciones y criterios usados']], 1, 18, 18, 'Juntos cuentan la historia financiera del año', 'Las normas contables piden un juego completo de estados que se leen juntos.', [['¿Cuál de ellos tiene una fecha y no un periodo?', 'El estado de situación financiera.'], ['¿Para qué sirven las notas?', 'Para explicar cifras y métodos que el número solo no dice.'], ['¿Puede una empresa con utilidad quedarse sin efectivo?', 'Sí: lo muestra el estado de flujos de efectivo.']], 'Cada estado responde una pregunta distinta; ninguno basta por sí solo.', { s: 7, s2: 5.4, gy: 4 }),
    { id: 'ct_liquidez', fam: 'est', n: 'La razón corriente',
      d: function (K) { return K.suelo(100, 140, 96) + pila(K, 36, 112, 40, [[24, P.verde, 'caja'], [28, P.azul, 'clientes'], [32, P.amarillo, 'inventario']]) + K.t(56, 124, 'Activo corriente', { s: 5.8, b: 1 }) + K.t(56, 132, '30 000', { s: 6, b: 1 }) + pila(K, 124, 112, 40, [[22, P.rojo, 'proveedores'], [20, P.rosa, 'sueldos e imp.']]) + K.t(144, 124, 'Pasivo corriente', { s: 5.8, b: 1 }) + K.t(144, 132, '15 000', { s: 6, b: 1 }) + formula(K, [['30 000 / 15 000', P.gris], ['= 2,0', P.amarillo]], 4, { s: 7 }) + K.t(144, 50, 'Por cada $ 1 de deuda', { s: 5.4 }) + K.t(144, 58, 'corta hay $ 2', { s: 5.4, b: 1 }); },
      intro: 'La razón corriente compara el activo corriente con el pasivo corriente.',
      q: [['¿Qué indica una razón de 2,0?', 'Que hay 2 de activo corto por cada 1 de deuda corta.'], ['¿Y una razón de 0,8?', 'Que el activo corriente no alcanza para las deudas de corto plazo.'], ['¿Es siempre mejor una razón muy alta?', 'No: puede indicar dinero ocioso o inventario acumulado.']],
      porque: 'Con esta razón, un banco ve rápido si la empresa podrá pagar lo que vence este año.' },
    { id: 'ct_acida', fam: 'est', n: 'La prueba ácida',
      d: function (K) { return K.suelo(100, 140, 96) + pila(K, 30, 112, 40, [[24, P.verde, 'caja'], [28, P.azul, 'clientes']]) + K.caja(30, 28, 40, 32, 5, P.amarillo, { w: .8, op: .35 }) + K.l('M28 30 L72 58 M72 30 L28 58', P.rojoO, { w: 1.2 }) + K.t(50, 46, 'inventario', { s: 5.4, b: 1 }) + K.t(50, 124, 'sin inventario', { s: 5.6, b: 1 }) + K.t(50, 132, '18 000', { s: 6, b: 1 }) + pila(K, 120, 112, 40, [[22, P.rojo], [20, P.rosa]]) + K.t(140, 124, 'Pasivo corriente', { s: 5.6, b: 1 }) + K.t(140, 132, '15 000', { s: 6, b: 1 }) + formula(K, [['(30 000 − 12 000) / 15 000', P.gris], ['= 1,2', P.amarillo]], 8, { s: 6.4 }); },
      intro: 'La prueba ácida es como la razón corriente pero sin el inventario, que tarda más en convertirse en dinero.',
      q: [['¿Por qué se quita el inventario?', 'Porque hay que venderlo antes de tener el dinero.'], ['¿Qué significa 1,2?', 'Que sin vender nada se cubre la deuda corta y sobra un 20 %.'], ['¿En qué negocio importa más esta prueba?', 'En los que tienen mucho inventario de venta lenta.']],
      porque: 'Es una prueba «ácida» porque supone el peor caso: que no se venda nada.' },
    { id: 'ct_endeuda', fam: 'est', n: 'El nivel de endeudamiento',
      d: function (K) { var cx = 70, cy = 72, r = 44, a = 2 * Math.PI * .4, x = cx + Math.sin(a) * r, y = cy - Math.cos(a) * r; return K.suelo(70, 122, 50) + K.c(cx, cy, r, P.verde, { w: 1 }) + K.p('M' + cx + ' ' + cy + ' L' + cx + ' ' + (cy - r) + ' A' + r + ' ' + r + ' 0 0 1 ' + x.toFixed(1) + ' ' + y.toFixed(1) + ' Z', P.rojo, { w: 1 }) + K.t(90, 58, '40 %', { s: 8, b: 1 }) + K.t(54, 90, '60 %', { s: 8, b: 1 }) + K.r(128, 34, 10, 10, 1, P.rojo, { w: .6 }) + K.t(142, 42, 'Pasivo 40 000', { s: 5.8, a: 'start' }) + K.r(128, 52, 10, 10, 1, P.verde, { w: .6 }) + K.t(142, 60, 'Patrimonio 60 000', { s: 5.8, a: 'start' }) + K.t(158, 84, 'Pasivo / Activo', { s: 6.2, b: 1 }) + K.t(158, 94, '40 000 / 100 000', { s: 5.6 }) + K.t(158, 104, '= 40 %', { s: 7, b: 1 }) + K.t(100, 136, 'De cada $ 100 de activo, 40 se deben', { s: 6, b: 1 }); },
      intro: 'El endeudamiento indica qué parte del activo se financió con deudas.',
      q: [['¿Qué porcentaje pertenece a los dueños?', '60 %.'], ['¿Qué riesgo tiene un 85 % de endeudamiento?', 'Si bajan las ventas, puede no alcanzar para pagar las cuotas.'], ['Activo 50 000 y pasivo 10 000. ¿Endeudamiento?', '20 %.']],
      porque: 'Deber no es malo; deber más de lo que el negocio puede pagar sí lo es.' },
    { id: 'ct_rentabilidad', fam: 'est', n: 'Medir la rentabilidad',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 14, 'Utilidad neta: 5 250', { s: 7, b: 1 }) + caja(K, 12, 26, 56, 70, P.azul) + K.t(40, 40, 'Margen neto', { s: 6, b: 1 }) + K.t(40, 56, '5 250 / 50 000', { s: 5 }) + K.t(40, 64, 'ventas', { s: 4.6 }) + K.t(40, 84, '10,5 %', { s: 9, b: 1 }) + caja(K, 72, 26, 56, 70, P.verde) + K.t(100, 40, 'ROA', { s: 6, b: 1 }) + K.t(100, 56, '5 250 / 100 000', { s: 5 }) + K.t(100, 64, 'activo', { s: 4.6 }) + K.t(100, 84, '5,3 %', { s: 9, b: 1 }) + caja(K, 132, 26, 56, 70, P.amarillo) + K.t(160, 40, 'ROE', { s: 6, b: 1 }) + K.t(160, 56, '5 250 / 45 750', { s: 5 }) + K.t(160, 64, 'patrimonio', { s: 4.6 }) + K.t(160, 84, '11,5 %', { s: 9, b: 1 }) + K.t(100, 112, 'La misma utilidad, comparada con tres bases', { s: 6, b: 1 }) + K.t(100, 124, 'ROE: lo que rinde el dinero de los dueños', { s: 5.6 }); },
      intro: 'La rentabilidad compara la utilidad con lo vendido, con los activos o con lo invertido por los dueños.',
      q: [['¿Qué mide el ROE?', 'Lo que gana cada unidad de dinero aportada por los dueños.'], ['¿Qué conviene comparar con el ROE?', 'Lo que daría ese dinero en un depósito a plazo u otra inversión.'], ['Margen 10,5 %: ¿cuánto queda de una venta de 200?', '21.']],
      porque: 'Una utilidad grande puede ser pobre si se necesitó una inversión enorme para lograrla.' },
    { id: 'ct_capital_trabajo', fam: 'est', n: 'El capital de trabajo',
      d: function (K) { return K.suelo(100, 140, 96) + K.caja(30, 30, 50, 84, 6, P.verde, { w: .9 }) + K.t(55, 70, 'Activo', { s: 6, b: 1 }) + K.t(55, 78, 'corriente', { s: 6, b: 1 }) + K.t(55, 90, '30 000', { s: 6.4, b: 1 }) + K.caja(118, 72, 50, 42, 6, P.rojo, { w: .9 }) + K.t(143, 90, 'Pasivo', { s: 6, b: 1 }) + K.t(143, 98, 'corriente', { s: 6, b: 1 }) + K.t(143, 108, '15 000', { s: 6.4, b: 1 }) + K.caja(118, 30, 50, 42, 6, P.amarillo, { w: .9, op: .8 }) + K.t(143, 48, 'capital de', { s: 5.8, b: 1 }) + K.t(143, 56, 'trabajo', { s: 5.8, b: 1 }) + K.t(143, 66, '15 000', { s: 6.4, b: 1 }) + K.t(100, 20, 'Capital de trabajo = AC − PC', { s: 7, b: 1 }) + K.t(100, 132, 'El margen con que opera el día a día', { s: 6, b: 1 }); },
      intro: 'El capital de trabajo es lo que sobra del activo corriente después de cubrir el pasivo corriente.',
      q: [['Calcula el capital de trabajo.', '30 000 − 15 000 = 15 000.'], ['¿Qué significa un capital de trabajo negativo?', 'Que las deudas cortas superan a los recursos cortos.'], ['¿Cómo aumenta?', 'Con utilidades retenidas, aportes o préstamos a largo plazo.']],
      porque: 'Con capital de trabajo, la empresa paga sueldos y proveedores sin esperar cada cobro.' },
    { id: 'ct_horizontal', fam: 'est', n: 'Análisis horizontal',
      d: function (K) { return K.suelo(100, 140, 96) + tabla(K, 12, 16, [62, 34, 34, 46], [['Partida', '2025', '2026', 'Variación'], ['Ventas', '42 000', '50 000', '+19,0 %'], ['Costo de ventas', '26 000', '30 000', '+15,4 %'], ['Gastos de operación', '10 000', '12 000', '+20,0 %'], ['=Utilidad neta', '4 200', '5 250', '+25,0 %']], { h: 14, s: 5.6 }) + K.t(100, 98, 'Variación % = (nuevo − anterior) / anterior × 100', { s: 5.8, b: 1 }) + K.t(100, 112, 'Ventas: (50 000 − 42 000) / 42 000 = 19 %', { s: 5.6 }) + K.t(100, 128, 'Compara la misma partida de un año a otro', { s: 6, b: 1 }); },
      intro: 'El análisis horizontal compara cada partida con la del año anterior para ver cuánto creció o bajó.',
      q: [['Comprueba la variación de la utilidad neta.', '(5 250 − 4 200) / 4 200 = 25 %.'], ['¿Qué creció más que las ventas?', 'Los gastos de operación (20 %) y la utilidad (25 %).'], ['¿Es buena señal que el costo suba menos que las ventas?', 'Sí: mejora el margen bruto.']],
      porque: 'Un número aislado dice poco; su cambio de un año a otro muestra la tendencia.' },
    { id: 'ct_vertical', fam: 'est', n: 'Análisis vertical',
      d: function (K) { var B = [[60, P.rojo, 'costo de ventas 60 %'], [24, P.naranja, 'gastos 24 %'], [2, P.morado, ''], [3.5, P.rosa, ''], [10.5, P.verde, '10,5 %']], x = 14, s = K.suelo(100, 140, 96) + K.t(100, 18, 'Ventas = 100 %', { s: 7, b: 1 }); B.forEach(function (q) { var w = q[0] * 1.72; s += K.caja(x, 34, w, 30, 6, q[1], { w: .8 }) + (q[2] ? K.t(x + w / 2, 52, q[2], { s: 5.2, b: 1 }) : ''); x += w; }); return s + K.t(132, 80, 'interés 2 % · impuesto 3,5 % · neta 10,5 %', { s: 5.2 }) + K.l('M126 72 L126 66 M136 72 L136 66', P.grisO, { w: .6 }) + K.t(100, 104, 'Cada partida ÷ ventas × 100', { s: 6.4, b: 1 }) + K.t(100, 116, '30 000 / 50 000 = 60 %', { s: 5.8 }) + K.t(100, 130, 'Sirve para comparar empresas de distinto tamaño', { s: 5.6 }); },
      intro: 'El análisis vertical expresa cada partida como porcentaje de las ventas del mismo año.',
      q: [['¿Qué porcentaje de las ventas son gastos de operación?', '12 000 / 50 000 = 24 %.'], ['¿Cuánto queda de cada 100 vendidos?', '10,50.'], ['¿Por qué permite comparar con una empresa más grande?', 'Porque compara proporciones, no montos.']],
      porque: 'Los porcentajes ponen a una tienda pequeña y a una cadena en la misma escala.' },
    { id: 'ct_usuarios', fam: 'est', n: '¿Quién lee los estados financieros?',
      d: function (K) { var U = [['dueños', '¿gano?', P.amarillo], ['banco', '¿me pagará?', P.azul], ['fisco', '¿cuánto tributa?', P.rojo], ['proveedores', '¿le doy crédito?', P.verde], ['trabajadores', '¿es estable?', P.naranja], ['inversionistas', '¿compro parte?', P.morado]], s = K.suelo(100, 140, 96); U.forEach(function (q, i) { var x = 34 + (i % 3) * 66, y = 14 + Math.floor(i / 3) * 62; s += persona(K, x, y, q[2]) + K.t(x, y + 35, q[0], { s: 6, b: 1 }) + K.r(x - 25, y + 39, 50, 13, 6, P.blanco, { w: .6 }) + K.t(x, y + 47.5, q[1], { s: 5 }); }); return s; },
      intro: 'Muchas personas distintas usan la misma información contable para tomar sus propias decisiones.',
      q: [['¿Qué le interesa al banco?', 'Que la empresa genere dinero suficiente para pagar el préstamo.'], ['¿Y a la autoridad tributaria?', 'Que los impuestos estén bien calculados.'], ['¿Por qué deben ser fiables los estados?', 'Porque muchos deciden con ellos sin poder revisar cada documento.']],
      porque: 'Por eso la contabilidad sigue normas comunes: la leen personas que no estuvieron dentro.' },
    /* ─────────── INVENTARIOS ─────────── */
    { id: 'ct_kardex', fam: 'inv', n: 'La tarjeta kárdex',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 12, 'Artículo: cuaderno A4 · método promedio ponderado', { s: 5.6, b: 1 }) + tabla(K, 4, 16, [22, 26, 40, 40, 64], [['Fecha', 'Detalle', 'Entrada', 'Salida', 'Saldo'], ['02/06', 'Compra', '100 × 10', '', '100 u · 1 000'], ['10/06', 'Compra', '100 × 12', '', '200 u · 2 200'], ['', '', '', '', 'promedio: 11'], ['15/06', 'Venta', '', '120 × 11', '80 u · 880'], ['25/06', 'Compra', '50 × 12', '', '130 u · 1 480']], { h: 14, s: 5.2 }) + K.t(100, 116, 'Promedio = valor del saldo ÷ unidades', { s: 6.2, b: 1 }) + K.t(100, 128, 'Nuevo promedio: 1 480 / 130 = 11,38', { s: 5.6 }); },
      intro: 'El kárdex registra cada entrada y salida de un artículo, con cantidades y valores, y su saldo.',
      q: [['¿Por qué la venta sale a 11?', 'Porque es el costo promedio de las 200 unidades.'], ['¿Cuánto vale el saldo tras la venta?', '80 × 11 = 880.'], ['¿El kárdex registra el precio de venta?', 'No: registra el costo.']],
      porque: 'El kárdex dice en todo momento cuántas unidades hay y cuánto costaron.' },
    { id: 'ct_promedio', fam: 'inv', n: 'El costo promedio ponderado',
      d: function (K) { var s = K.suelo(100, 140, 96); for (var i = 0; i < 10; i++) { s += K.caja(14 + (i % 5) * 14, 34 + Math.floor(i / 5) * 16, 12, 12, 3, P.azul, { w: .6 }); s += K.caja(114 + (i % 5) * 14, 34 + Math.floor(i / 5) * 16, 12, 12, 3, P.naranja, { w: .6 }); } return s + K.t(48, 24, '100 u a $ 10', { s: 6, b: 1 }) + K.t(148, 24, '100 u a $ 12', { s: 6, b: 1 }) + K.t(100, 50, '+', { s: 12, b: 1 }) + formula(K, [['(100 × 10 + 100 × 12)', P.gris], ['/ 200', P.azul], ['= 11', P.amarillo]], 82, { s: 6.6 }) + K.t(100, 116, 'Si las cantidades son distintas, pesa más la mayor', { s: 5.8, b: 1 }) + K.t(100, 128, '300 a 10 y 100 a 14 → 4 400 / 400 = 11', { s: 5.6 }); },
      intro: 'El promedio ponderado reparte el costo total entre todas las unidades, según cuántas se compraron a cada precio.',
      q: [['¿Por qué no se hace (10 + 12) / 2 siempre?', 'Porque solo vale si se compró la misma cantidad a cada precio.'], ['200 u a 5 y 50 u a 10: ¿promedio?', '(1 000 + 500) / 250 = 6.'], ['¿Cuándo se recalcula el promedio?', 'Después de cada compra.']],
      porque: 'Ponderar da a cada precio el peso de las unidades que realmente se compraron.' },
    { id: 'ct_costo_ventas', fam: 'inv', n: 'El costo de lo vendido',
      d: function (K) { return K.suelo(100, 140, 96) + caja(K, 8, 30, 40, 34, P.azul) + K.t(28, 44, 'Inventario', { s: 5.4, b: 1 }) + K.t(28, 52, 'inicial', { s: 5.4, b: 1 }) + K.t(28, 60, '5 000', { s: 5.6 }) + K.t(53, 50, '+', { s: 11, b: 1 }) + caja(K, 58, 30, 40, 34, P.verde) + K.t(78, 44, 'Compras', { s: 5.4, b: 1 }) + K.t(78, 52, 'netas', { s: 5.4, b: 1 }) + K.t(78, 60, '20 000', { s: 5.6 }) + K.t(103, 50, '−', { s: 11, b: 1 }) + caja(K, 108, 30, 40, 34, P.naranja) + K.t(128, 44, 'Inventario', { s: 5.4, b: 1 }) + K.t(128, 52, 'final', { s: 5.4, b: 1 }) + K.t(128, 60, '6 000', { s: 5.6 }) + K.t(153, 50, '=', { s: 11, b: 1 }) + caja(K, 158, 30, 36, 34, P.rojo) + K.t(176, 44, 'Costo de', { s: 5, b: 1 }) + K.t(176, 52, 'ventas', { s: 5, b: 1 }) + K.t(176, 60, '19 000', { s: 5.6, b: 1 }) + K.t(100, 92, 'Lo que había + lo que entró − lo que quedó', { s: 6.4, b: 1 }) + K.t(100, 104, '= lo que salió (vendido)', { s: 6, b: 1 }) + K.t(100, 126, 'Se usa cuando el inventario se cuenta solo al final', { s: 5.6 }); },
      intro: 'En el sistema periódico, el costo de ventas se calcula al final con el inventario contado.',
      q: [['Inicial 3 000, compras 9 000, final 2 500. ¿Costo de ventas?', '9 500.'], ['¿Qué pasa si se cuenta mal el inventario final?', 'El costo de ventas y la utilidad salen mal.'], ['¿Por qué se usan compras netas?', 'Porque se restan devoluciones y descuentos y se suman fletes.']],
      porque: 'Si no se registra cada salida, el costo se deduce de lo que falta en la bodega.' },
    { id: 'ct_toma_fisica', fam: 'inv', n: 'La toma física del inventario',
      d: function (K) { return K.suelo(100, 140, 96) + tabla(K, 10, 16, [56, 34, 34, 56], [['Artículo', 'Sistema', 'Contado', 'Diferencia'], ['Cuaderno A4', '80', '78', '−2 faltante'], ['Lápiz HB', '250', '250', '0'], ['Borrador', '120', '123', '+3 sobrante'], ['Carpeta', '40', '35', '−5 faltante']], { h: 14, s: 5.6 }) + K.r(26, 92, 148, 24, 3, P.amarillo, { w: .8 }) + K.t(100, 102, 'Las diferencias se investigan y luego', { s: 5.8, b: 1 }) + K.t(100, 111, 'se ajustan con un asiento', { s: 5.8, b: 1 }) + K.t(100, 132, 'Dos personas cuentan; una tercera revisa', { s: 5.6 }); },
      intro: 'La toma física es contar uno por uno los artículos de la bodega y compararlos con los registros.',
      q: [['¿Cuántas carpetas faltan?', '5.'], ['¿Qué causas puede tener un faltante?', 'Robo, daño, error al despachar o al registrar.'], ['¿Por qué cuentan dos personas?', 'Para evitar errores y que nadie oculte un faltante.']],
      porque: 'El registro dice lo que debería haber; solo contar dice lo que realmente hay.' },
    { id: 'ct_rotacion', fam: 'inv', n: 'La rotación del inventario',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.c(54, 70, 34, P.blanco, { w: .8 }); for (var i = 0; i < 3; i++) s += K.flecha(54 + Math.cos(i * 2.1) * 34, 70 + Math.sin(i * 2.1) * 34, 54 + Math.cos(i * 2.1 + 1.6) * 34, 70 + Math.sin(i * 2.1 + 1.6) * 34, P.verdeO, { w: 1.4, curva: [54 + Math.cos(i * 2.1 + .8) * 48, 70 + Math.sin(i * 2.1 + .8) * 48] }); return s + K.caja(40, 58, 28, 22, 5, P.amarillo, { w: .8 }) + K.t(54, 72, 'bodega', { s: 5, b: 1 }) + K.t(54, 118, '3,5 vueltas al año', { s: 6.2, b: 1 }) + K.t(146, 30, 'Rotación =', { s: 6.2, b: 1 }) + K.t(146, 40, 'costo de ventas', { s: 5.6 }) + K.l('M118 43 L174 43', P.tinta, { w: .6 }) + K.t(146, 51, 'inventario promedio', { s: 5.6 }) + K.t(146, 66, '19 000 / 5 500 = 3,45', { s: 6, b: 1 }) + K.t(146, 88, 'Días de inventario =', { s: 6, b: 1 }) + K.t(146, 98, '365 / 3,45 ≈ 106 días', { s: 6, b: 1 }) + K.t(146, 116, 'cuánto tarda en venderse', { s: 5.2 }); },
      intro: 'La rotación dice cuántas veces al año se vende y se repone todo el inventario.',
      q: [['¿De dónde sale el inventario promedio 5 500?', '(5 000 inicial + 6 000 final) / 2.'], ['¿Qué es mejor para una frutería, rotar 3 o 50 veces?', '50: la fruta no aguanta 100 días.'], ['¿Qué significa una rotación muy baja?', 'Mercadería parada, que ocupa espacio y dinero.']],
      porque: 'Inventario que no rota es dinero dormido en la bodega.' },
    { id: 'ct_punto_pedido', fam: 'inv', n: 'Stock mínimo y punto de pedido',
      d: function (K) { var s = K.suelo(100, 140, 96) + ejes(K, 22, 14, 166, 100, 'días', 'unidades'), y = function (u) { return 114 - u * .62; }; s += K.r(23, y(20), 160, 20 * .62, 0, P.rojo, { w: .2, op: .5 }) + K.l('M23 ' + y(70) + ' L183 ' + y(70), P.naranja, { w: .9 }); s += linea(K, [[24, y(150)], [104, y(70)], [134, y(20)], [134, y(150)], [183, y(100)]], P.azulO, 1.8); return s + K.t(186, y(70) - 2, 'punto de pedido: 70', { s: 5.2, b: 1, a: 'end', c: P.naranja }) + K.t(186, y(10), 'seguridad: 20', { s: 5.2, b: 1, a: 'end', c: P.rojoO }) + K.flecha(104, y(70) + 8, 104, y(70) + 2, P.tinta, { w: .8 }) + K.t(104, y(40) + 6, 'se pide', { s: 5, b: 1 }) + K.t(134, y(160) - 1, 'llega', { s: 5, b: 1 }) + K.t(100, 136, '10 u/día × 5 días de espera + 20 = 70', { s: 5.8, b: 1 }); },
      intro: 'El punto de pedido es la cantidad a la que hay que volver a comprar para no quedarse sin existencias.',
      q: [['¿Cómo se calcula el punto de pedido?', 'Consumo diario × días que tarda el proveedor + stock de seguridad.'], ['Si se venden 15 al día y el proveedor tarda 4 días, con 30 de seguridad, ¿punto de pedido?', '15 × 4 + 30 = 90.'], ['¿Para qué sirve el stock de seguridad?', 'Para cubrir retrasos o ventas mayores de lo previsto.']],
      porque: 'Pedir a tiempo evita perder ventas sin llenar la bodega de más.' },
    { id: 'ct_abc', fam: 'inv', n: 'Clasificación ABC',
      d: function (K) { var B = [[38, P.rojo], [24, P.rojo], [12, P.rojo], [7, P.amarillo], [6, P.amarillo], [4, P.amarillo], [3, P.verde], [2.5, P.verde], [2, P.verde], [1.5, P.verde]], s = K.suelo(100, 140, 96) + K.l('M18 112 L186 112', P.tinta, { w: .9 }); B.forEach(function (q, i) { s += K.caja(22 + i * 16, 112 - q[0] * 2.2, 11, q[0] * 2.2, 4, q[1], { w: .7 }); }); return s + K.t(46, 122, 'A: 3 artículos', { s: 5.6, b: 1 }) + K.t(46, 130, '74 % del valor', { s: 5.2 }) + K.t(102, 122, 'B: 3', { s: 5.6, b: 1 }) + K.t(102, 130, '17 %', { s: 5.2 }) + K.t(160, 122, 'C: 4', { s: 5.6, b: 1 }) + K.t(160, 130, '9 %', { s: 5.2 }) + K.t(130, 30, 'Pocos artículos', { s: 6, b: 1 }) + K.t(130, 39, 'concentran casi todo el valor', { s: 5.6 }) + K.t(130, 52, 'Controla A cada semana, C cada trimestre', { s: 5.2 }); },
      intro: 'La clasificación ABC ordena los artículos según el valor que representan para controlar más los más importantes.',
      q: [['¿Qué artículos se vigilan más de cerca?', 'Los del grupo A.'], ['¿Qué porcentaje del valor suman los grupos A y B?', '74 + 17 = 91 %.'], ['¿Se pueden descuidar los C?', 'No, pero basta con revisarlos con menos frecuencia.']],
      porque: 'El control cuesta tiempo; conviene gastarlo donde está el dinero.' },
    { id: 'ct_compras_netas', fam: 'inv', n: 'Las compras netas',
      d: function (K) { return K.suelo(100, 140, 96) + tabla(K, 30, 18, [100, 40], [['Concepto', 'Importe'], ['Compras brutas', '20 000'], ['(+) Fletes en compras', '500'], ['(−) Devoluciones en compras', '(800)'], ['(−) Descuentos en compras', '(300)'], ['=Compras netas', '19 400']], { h: 14, s: 6 }) + K.t(100, 114, 'El flete se suma: es parte de traer la mercadería', { s: 5.8, b: 1 }) + K.t(100, 126, 'Lo devuelto y lo descontado no costó', { s: 5.6 }); },
      intro: 'Las compras netas son el costo real de lo comprado, tras sumar fletes y restar devoluciones y descuentos.',
      q: [['Comprueba las compras netas.', '20 000 + 500 − 800 − 300 = 19 400.'], ['¿Por qué el flete forma parte del costo?', 'Porque sin pagarlo la mercadería no estaría en la bodega.'], ['¿Qué documento respalda una devolución en compras?', 'La nota de crédito del proveedor.']],
      porque: 'El costo de un producto es todo lo necesario para tenerlo listo para vender.' },
    { id: 'ct_merma', fam: 'inv', n: 'Merma y costo real',
      d: function (K) { var s = K.suelo(100, 140, 96); for (var i = 0; i < 50; i++) { var x = 14 + (i % 10) * 9, y = 26 + Math.floor(i / 10) * 9, m = i >= 47; s += K.c(x + 4, y + 4, 3.6, m ? P.grisO : P.naranja, { w: .5 }); } return s + K.t(58, 18, '1 000 kg de naranjas · $ 1 500', { s: 5.6, b: 1 }) + K.t(58, 82, 'merma 6 % = 60 kg (gris)', { s: 5.4, b: 1 }) + K.t(150, 34, 'Costo por kg útil', { s: 6, b: 1 }) + K.t(150, 46, '1 500 / 940 kg', { s: 6 }) + K.t(150, 60, '= 1,60 por kg', { s: 7.4, b: 1 }) + K.t(150, 74, 'y no 1,50', { s: 5.6, c: P.rojoO }) + K.t(100, 108, 'La merma es la pérdida natural de peso o de unidades', { s: 5.6, b: 1 }) + K.t(100, 120, 'Se reparte sobre lo que sí se puede vender', { s: 5.6 }); },
      intro: 'La merma reduce lo que se puede vender; su costo se reparte entre las unidades que quedan.',
      q: [['¿Cuántos kilos se pueden vender?', '1 000 − 60 = 940 kg.'], ['¿Qué pasa si se fija el precio con 1,50?', 'Se gana menos de lo calculado, o se pierde.'], ['Da un ejemplo de merma en otro negocio.', 'La evaporación en una panadería o la rotura de huevos.']],
      porque: 'Ignorar la merma es vender por debajo del costo sin darse cuenta.' },
    { id: 'ct_vnr', fam: 'inv', n: 'Costo o valor neto realizable',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 14, 'Un teléfono del año pasado', { s: 6.6, b: 1 }) + caja(K, 16, 26, 52, 40, P.azul) + K.t(42, 40, 'Costo', { s: 6, b: 1 }) + K.t(42, 56, '50', { s: 10, b: 1 }) + caja(K, 74, 26, 52, 40, P.verde) + K.t(100, 38, 'Se venderá en', { s: 5.4, b: 1 }) + K.t(100, 48, '45', { s: 8, b: 1 }) + K.t(100, 58, '− 5 de gastos', { s: 5 }) + caja(K, 132, 26, 52, 40, P.amarillo) + K.t(158, 40, 'VNR', { s: 6, b: 1 }) + K.t(158, 56, '40', { s: 10, b: 1 }) + K.r(40, 80, 120, 22, 3, P.rojo, { w: .9 }) + K.t(100, 89, 'Se valora en el menor: 40', { s: 6.4, b: 1 }) + K.t(100, 97, 'pérdida por deterioro: 10', { s: 5.6 }) + K.t(100, 122, 'El inventario no puede valer más de lo que se recuperará', { s: 5.6, b: 1 }); },
      intro: 'Si un artículo se venderá por menos de lo que costó, se rebaja su valor al importe que realmente se recuperará.',
      q: [['¿Qué es el valor neto realizable?', 'El precio de venta esperado menos los gastos para venderlo.'], ['¿Cuánto se reconoce como pérdida?', '50 − 40 = 10 por unidad.'], ['¿Se sube el valor si el precio aumenta por encima del costo?', 'No: el inventario se lleva al costo como máximo.']],
      porque: 'Reconocer la pérdida cuando se sabe evita que los estados muestren un inventario inflado.' },
    /* ─────────── COSTOS Y PRECIOS ─────────── */
    { id: 'ct_fijo_variable', fam: 'cos', n: 'Costos fijos y variables',
      d: function (K) { var s = K.suelo(100, 140, 96) + ejes(K, 24, 14, 160, 96, 'unidades', '$'), y = function (v) { return 110 - v * 9; }; s += linea(K, [[24, y(4)], [180, y(4)]], P.azulO, 1.8) + linea(K, [[24, y(0)], [180, y(9)]], P.naranja, 1.8) + linea(K, [[24, y(4)], [180, y(13)]], P.rojoO, 2.2); return s + K.t(182, y(4) - 3, 'fijo: alquiler', { s: 5.4, b: 1, a: 'end', c: P.azulO }) + K.t(150, y(7.5) + 8, 'variable: material', { s: 5.4, b: 1, c: P.naranja }) + K.t(150, y(12) - 4, 'total', { s: 5.6, b: 1, c: P.rojoO }) + K.t(100, 136, 'El fijo no cambia con la producción; el variable sí', { s: 5.8, b: 1 }); },
      intro: 'Los costos fijos se pagan aunque no se produzca nada; los variables crecen con cada unidad.',
      q: [['¿Es fijo o variable la harina de una panadería?', 'Variable: más pan, más harina.'], ['¿Y el alquiler del local?', 'Fijo: se paga igual con 10 o con 1 000 panes.'], ['¿Dónde empieza la recta del costo total?', 'En el valor del costo fijo, no en cero.']],
      porque: 'Separar fijos y variables es la base para calcular precios y el punto de equilibrio.' },
    { id: 'ct_elementos', fam: 'cos', n: 'Los tres elementos del costo',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 14, 'Costo de producir una silla de madera', { s: 6.4, b: 1 }) + caja(K, 10, 26, 52, 46, P.madera) + K.t(36, 40, 'Materia prima', { s: 5.6, b: 1 }) + K.t(36, 50, 'madera, clavos', { s: 4.8 }) + K.t(36, 64, '20', { s: 9, b: 1 }) + K.t(67, 52, '+', { s: 10, b: 1 }) + caja(K, 74, 26, 52, 46, P.azul) + K.t(100, 40, 'Mano de obra', { s: 5.6, b: 1 }) + K.t(100, 50, '3 h del carpintero', { s: 4.8 }) + K.t(100, 64, '15', { s: 9, b: 1 }) + K.t(131, 52, '+', { s: 10, b: 1 }) + caja(K, 138, 26, 52, 46, P.morado) + K.t(164, 40, 'Costos indirectos', { s: 5.2, b: 1 }) + K.t(164, 50, 'luz, lija, desgaste', { s: 4.8 }) + K.t(164, 64, '10', { s: 9, b: 1 }) + K.r(50, 86, 100, 22, 3, P.amarillo, { w: 1 }) + K.t(100, 100, 'Costo de producción = 45', { s: 7, b: 1 }) + K.t(100, 128, 'MP + MOD + CIF', { s: 6.4, b: 1 }); },
      intro: 'El costo de un producto fabricado se forma con materia prima, mano de obra directa y costos indirectos.',
      q: [['¿Qué son los costos indirectos de fabricación?', 'Costos necesarios que no se pueden asignar exactos a cada silla: luz, mantenimiento, supervisión.'], ['¿Cuánto cuestan 12 sillas?', '12 × 45 = 540.'], ['¿Entra el sueldo del vendedor en este costo?', 'No: es un gasto de venta, no de producción.']],
      porque: 'Olvidar uno de los tres elementos lleva a vender por debajo del costo.' },
    { id: 'ct_unitario', fam: 'cos', n: 'El costo unitario baja con el volumen',
      d: function (K) { return K.suelo(100, 140, 96) + tabla(K, 12, 16, [44, 40, 46, 46], [['Unidades', 'Fijos', 'Variables (3 c/u)', 'Costo unitario'], ['500', '2 000', '1 500', '7,00'], ['1 000', '2 000', '3 000', '5,00'], ['2 000', '2 000', '6 000', '4,00'], ['4 000', '2 000', '12 000', '3,50']], { h: 14, s: 5.6 }) + K.t(100, 96, '(fijos + variables) ÷ unidades', { s: 6.4, b: 1 }) + K.t(100, 108, '1 000 u: (2 000 + 3 000) / 1 000 = 5', { s: 5.6 }) + K.t(100, 126, 'El costo fijo se reparte entre más unidades', { s: 6, b: 1 }); },
      intro: 'Al producir más, el costo fijo se reparte entre más unidades y el costo de cada una baja.',
      q: [['¿Cuál es el costo unitario con 2 000 unidades?', '(2 000 + 6 000) / 2 000 = 4.'], ['¿Puede bajar de 3?', 'No: 3 es el costo variable de cada unidad; el fijo solo se acerca a cero.'], ['¿Por qué las fábricas grandes pueden vender más barato?', 'Porque reparten sus costos fijos entre muchas más unidades.']],
      porque: 'Esto se llama economía de escala: producir más abarata cada unidad hasta un límite.' },
    { id: 'ct_margen_recargo', fam: 'cos', n: 'Margen y recargo no son lo mismo',
      d: function (K) { return K.suelo(100, 140, 96) + K.caja(30, 40, 140, 22, 6, P.verde, { w: .9 }) + K.caja(30, 40, 84, 22, 6, P.azul, { w: .9 }) + K.t(72, 54, 'costo 60', { s: 6.4, b: 1 }) + K.t(142, 54, 'ganancia 40', { s: 6.4, b: 1 }) + K.t(100, 30, 'precio de venta 100', { s: 6.6, b: 1 }) + caja(K, 14, 82, 82, 34, P.amarillo) + K.t(55, 94, 'Margen', { s: 6.4, b: 1 }) + K.t(55, 103, '40 / 100 (precio)', { s: 5.2 }) + K.t(55, 112, '= 40 %', { s: 6.6, b: 1 }) + caja(K, 104, 82, 82, 34, P.naranja) + K.t(145, 94, 'Recargo', { s: 6.4, b: 1 }) + K.t(145, 103, '40 / 60 (costo)', { s: 5.2 }) + K.t(145, 112, '= 66,7 %', { s: 6.6, b: 1 }) + K.t(100, 132, 'La misma ganancia con dos bases distintas', { s: 5.8, b: 1 }); },
      intro: 'El margen compara la ganancia con el precio; el recargo, con el costo. Confundirlos cambia el precio.',
      q: [['Costo 80 y recargo 25 %. ¿Precio?', '80 × 1,25 = 100.'], ['¿Qué margen tiene ese precio?', '20 / 100 = 20 %.'], ['Para ganar un margen del 40 % con costo 60, ¿qué precio hace falta?', '60 / 0,60 = 100.']],
      porque: 'Un recargo del 40 % solo da un margen del 28,6 %: por eso conviene decir siempre sobre qué base se calcula.' },
    { id: 'ct_precio', fam: 'cos', n: 'Fijar el precio de venta',
      d: function (K) { return K.suelo(100, 140, 96) + pila(K, 70, 120, 60, [[45, P.azul, 'costo 45,00'], [18, P.verde, '+ 40 %: 18,00'], [9.5, P.rojo, '+ imp. 15 %: 9,45']]) + K.t(100, 40, 'Precio al público', { s: 6.4, b: 1 }) + K.t(100, 30, '72,45', { s: 10, b: 1 }) + K.t(166, 64, '1) costo', { s: 5.4, a: 'start' }) + K.t(166, 74, '2) + ganancia', { s: 5.4, a: 'start' }) + K.t(166, 84, '3) + impuesto', { s: 5.4, a: 'start' }) + K.t(30, 64, '45 × 1,40', { s: 5.4 }) + K.t(30, 72, '= 63,00', { s: 5.4, b: 1 }) + K.t(30, 86, '63 × 1,15', { s: 5.4 }) + K.t(30, 94, '= 72,45', { s: 5.4, b: 1 }) + K.t(100, 136, 'El impuesto no es ganancia: se entrega al fisco', { s: 5.6, b: 1 }); },
      intro: 'El precio se construye sumando al costo la ganancia deseada y luego el impuesto que cobra el país.',
      q: [['¿Por qué el impuesto se calcula al final?', 'Porque se aplica sobre el precio de venta, no sobre el costo.'], ['Costo 20, recargo 50 %, impuesto 15 %. ¿Precio?', '20 × 1,5 × 1,15 = 34,50.'], ['¿Qué más conviene mirar antes de fijar el precio?', 'Los precios de la competencia y lo que el cliente está dispuesto a pagar.']],
      porque: 'La tasa del impuesto cambia de un país a otro: el 15 % es solo un ejemplo.' },
    { id: 'ct_orden_trabajo', fam: 'cos', n: 'Hoja de costos por pedido',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 12, 'Orden de trabajo N.º 31 · 10 mesas para un café', { s: 5.8, b: 1 }) + tabla(K, 20, 18, [100, 60], [['Elemento', 'Importe'], ['Materia prima (madera, herrajes)', '900'], ['Mano de obra (40 h × 6)', '240'], ['Costos indirectos (50 % de la MO)', '120'], ['=Costo total del pedido', '1 260'], ['=Costo por mesa', '126']], { h: 14, s: 5.8 }) + K.t(100, 116, 'Cada pedido acumula su propio costo', { s: 6.2, b: 1 }) + K.t(100, 128, 'Útil para trabajos a medida', { s: 5.6 }); },
      intro: 'En la producción por pedidos, cada orden lleva una hoja donde se suman sus propios costos.',
      q: [['¿Cuánto cuesta cada mesa?', '1 260 / 10 = 126.'], ['¿Cómo se asignaron los costos indirectos?', 'Como un 50 % de la mano de obra directa.'], ['¿Qué negocio trabaja así?', 'Una carpintería, una imprenta o un taller de costura a medida.']],
      porque: 'Cuando cada trabajo es distinto, solo el costo de cada orden dice si ese pedido dejó ganancia.' },
    { id: 'ct_procesos', fam: 'cos', n: 'Costos por procesos',
      d: function (K) { var E = [['corte', 2, P.madera], ['ensamble', 3, P.azul], ['pintura', 1.5, P.verde], ['empaque', 0.5, P.amarillo]], s = K.suelo(100, 140, 96), acu = 0; E.forEach(function (q, i) { var x = 8 + i * 48; acu += q[1]; s += K.caja(x, 40, 40, 30, 6, q[2], { w: .8 }) + K.t(x + 20, 52, q[0], { s: 6, b: 1 }) + K.t(x + 20, 62, '+ ' + String(q[1]).replace('.', ','), { s: 5.6 }) + K.t(x + 20, 90, 'acumulado', { s: 4.8 }) + K.t(x + 20, 100, String(acu.toFixed(2)).replace('.', ','), { s: 7, b: 1 }); if (i < 3) s += K.flecha(x + 41, 55, x + 47, 55, P.tinta, { w: 1 }); }); return s + K.t(100, 24, 'Producción en serie de cajas de madera (por unidad)', { s: 5.8, b: 1 }) + K.t(100, 124, 'Cada departamento suma su costo al que recibe', { s: 6, b: 1 }); },
      intro: 'En la producción en serie, el costo se acumula departamento por departamento.',
      q: [['¿Cuánto cuesta cada caja terminada?', '2 + 3 + 1,5 + 0,5 = 7.'], ['¿Qué proceso es el más caro?', 'El ensamble.'], ['¿Qué negocio usa este sistema?', 'Una fábrica de bebidas, de pan industrial o de ladrillos.']],
      porque: 'Cuando todas las unidades son iguales, basta dividir el costo de cada proceso entre las unidades.' },
    G('ct_directo', 'cos', 'Costos directos e indirectos', [['Directo', 'tela de una camisa', P.verde], ['Directo', 'horas de la costurera', P.verde], ['Directo', 'botones y cierres', P.verde], ['Indirecto', 'luz del taller', P.naranja], ['Indirecto', 'sueldo del supervisor', P.naranja], ['Indirecto', 'desgaste de las máquinas', P.naranja], ['Indirecto', 'hilo y agujas', P.naranja], ['Indirecto', 'alquiler del taller', P.naranja]], 2, 18, 22, 'Directo: se mide por unidad · Indirecto: se reparte', 'Un costo es directo si se puede medir exactamente en cada producto; si no, es indirecto y se reparte.', [['¿Por qué el hilo es indirecto si se usa en cada camisa?', 'Porque medir el hilo exacto de cada una cuesta más de lo que vale.'], ['¿Cómo se reparte la luz del taller?', 'Con una base: horas de máquina, de trabajo o unidades.'], ['¿Es directo el sueldo del supervisor?', 'No: supervisa todas las camisas a la vez.']], 'Repartir bien los indirectos evita que un producto parezca rentable a costa de otro.', { s: 6.6, s2: 5.4 }),
    { id: 'ct_contribucion', fam: 'cos', n: 'El margen de contribución',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 14, 'Cada empanada se vende a $ 2,00', { s: 6.4, b: 1 }) + K.caja(24, 30, 152, 24, 6, P.amarillo, { w: .9 }) + K.caja(24, 30, 91, 24, 6, P.naranja, { w: .9 }) + K.t(70, 45, 'variable 1,20', { s: 6.2, b: 1 }) + K.t(146, 45, 'contribuye 0,80', { s: 6.2, b: 1 }) + K.flecha(146, 58, 146, 76, P.tinta, { w: 1.2 }) + K.r(100, 78, 92, 30, 3, P.azul, { w: .9 }) + K.t(146, 90, 'cubre el alquiler', { s: 5.6, b: 1 }) + K.t(146, 100, 'y luego da ganancia', { s: 5.4 }) + K.t(54, 82, 'Margen de contribución', { s: 5.8, b: 1 }) + K.t(54, 92, '= precio − costo variable', { s: 5.4 }) + K.t(54, 102, '= 0,80 por unidad (40 %)', { s: 5.6, b: 1 }) + K.t(100, 128, 'Con fijos de 400 al mes hacen falta 500 empanadas', { s: 5.6 }); },
      intro: 'El margen de contribución es lo que deja cada unidad vendida para pagar los costos fijos.',
      q: [['¿Cuánto aporta cada empanada?', '2,00 − 1,20 = 0,80.'], ['¿Cuántas hay que vender para cubrir 400 de fijos?', '400 / 0,80 = 500.'], ['¿Qué pasa con la empanada 501?', 'Sus 0,80 ya son ganancia.']],
      porque: 'Primero cada venta paga los costos fijos; solo después empieza a dejar utilidad.' },
    { id: 'ct_costo_hora', fam: 'cos', n: 'Lo que cuesta una hora de trabajo',
      d: function (K) { return K.suelo(100, 140, 96) + K.c(40, 60, 26, P.blanco, { w: 1 }) + K.l('M40 60 L40 42 M40 60 L52 66', P.tinta, { w: 1.4 }) + K.c(40, 60, 2, P.tinta) + K.t(40, 96, '160 h al mes', { s: 6, b: 1 }) + tabla(K, 78, 26, [70, 40], [['Sueldo mensual', '600'], ['Cargas sociales (20 %)', '120'], ['=Costo para la empresa', '720'], ['=Costo por hora', '4,50']], { h: 14, s: 5.6, sinCab: 1 }) + K.t(100, 112, '720 / 160 h = 4,50 por hora', { s: 6.6, b: 1 }) + K.t(100, 128, 'Las cargas sociales cambian según el país', { s: 5.6 }); },
      intro: 'El costo real de una hora de trabajo incluye el sueldo y las cargas que paga la empresa.',
      q: [['¿Por qué no se usa solo el sueldo?', 'Porque la empresa también paga aportes, vacaciones y otras cargas.'], ['¿Cuánto cuesta un trabajo de 6 horas?', '6 × 4,50 = 27.'], ['Si el sueldo sube a 700, ¿nuevo costo por hora?', '700 × 1,2 / 160 = 5,25.']],
      porque: 'Presupuestar con el sueldo neto deja fuera un costo que igual habrá que pagar.' },
    { id: 'ct_descuentos', fam: 'cos', n: 'Descuento comercial y por pronto pago',
      d: function (K) { return K.suelo(100, 140, 96) + caja(K, 12, 22, 84, 82, P.azul) + K.t(54, 36, 'Comercial', { s: 6.6, b: 1 }) + K.t(54, 48, 'por volumen o temporada', { s: 4.8 }) + K.t(54, 62, 'Lista: 1 000', { s: 5.8 }) + K.t(54, 72, '− 10 %: 100', { s: 5.8 }) + K.t(54, 88, 'Factura: 900', { s: 7, b: 1 }) + caja(K, 104, 22, 84, 82, P.verde) + K.t(146, 36, 'Pronto pago', { s: 6.6, b: 1 }) + K.t(146, 48, '«2/10, n/30»', { s: 5.6, b: 1 }) + K.t(146, 58, '2 % si paga en 10 días', { s: 4.8 }) + K.t(146, 66, 'si no, total a 30 días', { s: 4.8 }) + K.t(146, 80, '900 − 2 % = 882', { s: 6.2, b: 1 }) + K.t(146, 92, 'ahorra 18', { s: 5.4 }) + K.t(100, 124, 'El primero baja el precio; el segundo premia pagar antes', { s: 5.6, b: 1 }); },
      intro: 'El descuento comercial se aplica en la factura; el de pronto pago, solo si se paga dentro del plazo.',
      q: [['¿Qué significa «2/10, n/30»?', '2 % de descuento si se paga en 10 días; si no, el total en 30.'], ['¿Cuánto se paga a los 25 días?', '900: ya no hay descuento.'], ['¿Conviene pagar antes?', 'Sí, si se tiene el dinero: un 2 % por adelantar 20 días es mucho.']],
      porque: 'Para el vendedor, cobrar antes vale dinero: por eso premia al cliente que paga rápido.' }
  ];
  MO.agregar('conta', L, { nombre: 'Contabilidad', familias: FAM, materias: /^(conta)$/ });
})();
