/* b6_lib_marketing.js — Marketing digital: modelos 1–17 de 50 (primera entrega; 18–33 en el archivo 2, 34–50 en el 3). Materia `mkt`. Prefijo `mk_`.
   Cargar después de b6_lib_emprendimiento.js (usa EU_EMPRE_K). Expone window.EU_DIGI_K: helpers digitales (pantalla, móvil, sectores, curva, estrella) para Marketing, Comercio electrónico, Redes e IA.
   No repite mkt_posicion, mkt_recorrido, emp_lienzo, emp_empatia, rs_*, ec_ficha, con_presupuesto, len_comunica ni los em_* de Emprendimiento. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS, E = window.EU_EMPRE_K; if (!MO || !E || MO.modelo('mk_4p')) return;
  var P = E.P, CO = E.CO, nf = E.nf, ajusta = E.ajusta, G = E.G, caja = E.caja, per = E.per, barras = E.barras, estrella = E.estrella;
  function pant(K, x, y, w, h, o) { o = o || {}; return K.r(x, y, w, h, 2.5, o.f || P.blanco, { w: .9 }) + K.r(x, y, w, 8, 2.5, P.gris, { w: .6 }) + K.c(x + 5, y + 4, 1.4, P.rojo, { w: .3 }) + K.c(x + 9, y + 4, 1.4, P.amarillo, { w: .3 }) + K.c(x + 13, y + 4, 1.4, P.verde, { w: .3 }) + (o.url ? K.r(x + 18, y + 1.8, w - 22, 4.4, 2, P.blanco, { w: .4 }) + K.t(x + 20, y + 5.2, o.url, { s: ajusta(o.url, w - 26, 3.6), a: 'start' }) : ''); }
  function movil(K, x, y, w, h, col) { return K.r(x, y, w, h, 5, P.tinta, { w: .8 }) + K.r(x + 2, y + 6, w - 4, h - 12, 2, col || P.blanco, { w: .3 }) + K.r(x + w / 2 - 5, y + 2.2, 10, 1.6, .8, P.grisO, { w: .2 }) + K.c(x + w / 2, y + h - 3, 1.6, P.grisO, { w: .2 }); }
  function renglones(K, x, y, w, n, g, col) { var s = ''; for (var i = 0; i < n; i++) s += K.l('M' + x + ' ' + (y + i * (g || 5)) + ' L' + (x + w * (i === n - 1 ? .6 : 1)) + ' ' + (y + i * (g || 5)), col || P.gris, { w: 1.4 }); return s; }
  function sector(K, cx, cy, r, D) { var a = -Math.PI / 2, tot = D.reduce(function (t, d) { return t + d[1]; }, 0), s = ''; D.forEach(function (d, i) { var b = a + d[1] / tot * 2 * Math.PI, x1 = cx + r * Math.cos(a), y1 = cy + r * Math.sin(a), x2 = cx + r * Math.cos(b), y2 = cy + r * Math.sin(b); s += K.p('M' + cx + ' ' + cy + ' L' + x1.toFixed(1) + ' ' + y1.toFixed(1) + ' A' + r + ' ' + r + ' 0 ' + (b - a > Math.PI ? 1 : 0) + ' 1 ' + x2.toFixed(1) + ' ' + y2.toFixed(1) + ' Z', d[2] || CO[i % CO.length], { w: .7 }); a = b; }); return s; }
  function curva(K, V, x0, y0, w, h, max, col) { var X = function (i) { return +(x0 + i * w / (V.length - 1)).toFixed(1); }, Y = function (v) { return +(y0 + h - v / max * h).toFixed(1); }; return K.l('M' + x0 + ' ' + y0 + ' L' + x0 + ' ' + (y0 + h) + ' L' + (x0 + w) + ' ' + (y0 + h), P.tinta, { w: .6 }) + K.l('M' + V.map(function (v, i) { return X(i) + ' ' + Y(v); }).join(' L'), col || P.azulO, { w: 1.3 }) + V.map(function (v, i) { return K.c(X(i), Y(v), 1.5, col || P.azulO, { w: .3 }); }).join(''); }
  function check(K, x, y, ok) { return ok ? K.l('M' + (x - 3) + ' ' + y + ' l2.2 2.6 l4 -5', P.verdeO, { w: 1.3 }) : K.l('M' + (x - 2.5) + ' ' + (y - 2.5) + ' l5 5 M' + (x + 2.5) + ' ' + (y - 2.5) + ' l-5 5', P.rojoO, { w: 1.3 }); }
  window.EU_DIGI_K = { pant: pant, movil: movil, renglones: renglones, sector: sector, curva: curva, check: check };
  var FAM = { fun: 'Fundamentos', cli: 'El cliente', mar: 'Marca y contenido', web: 'Web y buscadores', pub: 'Publicidad pagada', ema: 'Correo y automatización', met: 'Métricas', est: 'Estrategia y plan' };
  var L = [
    /* ─────────── FUNDAMENTOS ─────────── */
    { id: 'mk_4p', fam: 'fun', n: 'Las 4 P del marketing',
      d: function (K) { var s = K.suelo(100, 140, 96), C = [[56, 40, 'PRODUCTO', 'qué vendo', P.azul], [144, 40, 'PRECIO', 'cuánto cobro', P.amarillo], [56, 96, 'PLAZA', 'dónde lo vendo', P.verde], [144, 96, 'PROMOCIÓN', 'cómo lo doy a conocer', P.rosa]]; C.forEach(function (c) { s += K.r(c[0] - 40, c[1] - 22, 80, 44, 6, c[4], { w: .9 }) + K.t(c[0], c[1] - 2, c[0 + 2], { s: 7, b: 1 }) + K.t(c[0], c[1] + 9, c[3], { s: ajusta(c[3], 74, 5.4) }); }); return s + K.c(100, 68, 14, P.blanco, { w: 1 }) + K.t(100, 70.5, 'cliente', { s: 5.4, b: 1 }) + K.t(100, 136, 'Las cuatro decisiones deben encajar entre sí', { s: 5.8, b: 1 }); },
      intro: 'El marketing reúne cuatro decisiones básicas: el producto, su precio, el lugar donde se vende y la forma de darlo a conocer.',
      q: [['¿A qué P pertenece una tienda en internet?', 'A la plaza: es el lugar donde se vende.'], ['¿Y un anuncio en redes?', 'A la promoción.'], ['¿Por qué deben encajar?', 'Un producto de lujo con precio de saldo o en un mal lugar confunde al cliente.']],
      porque: 'Pensar en las cuatro P evita fallos como un buen producto que nadie conoce.' },
    { id: 'mk_aida', fam: 'fun', n: 'El modelo AIDA',
      d: function (K) { var A = [['A', 'Atención', 'me fijo en el anuncio'], ['I', 'Interés', 'quiero saber más'], ['D', 'Deseo', 'lo quiero para mí'], ['A', 'Acción', 'compro o escribo']], s = K.suelo(100, 140, 96); A.forEach(function (a, i) { var x = 14 + i * 46, y = 92 - i * 18; s += K.r(x, y, 38, 120 - y, 3, CO[i], { w: .8 }) + K.t(x + 19, y + 14, a[0], { s: 12, b: 1 }) + K.t(x + 19, y + 24, a[1], { s: 6, b: 1 }) + K.t(x + 19, y - 4, a[2], { s: ajusta(a[2], 44, 4.6) }); if (i < 3) s += K.flecha(x + 32, y - 10, x + 44, y - 26, P.tinta, { w: .7, p: 2.2 }); }); return s + K.t(100, 132, 'Cada mensaje lleva al cliente al escalón siguiente', { s: 5.6, b: 1 }); },
      intro: 'AIDA describe los cuatro pasos que recorre una persona desde que ve un mensaje hasta que actúa.',
      q: [['¿Qué paso busca un titular llamativo?', 'La atención.'], ['¿Qué paso consigue un botón «Comprar ahora»?', 'La acción.'], ['¿Qué despierta el deseo?', 'Mostrar el beneficio: cómo mejora la vida del cliente.']],
      porque: 'Un anuncio que solo llama la atención, sin llevar a la acción, gasta dinero sin vender.' },
    { id: 'mk_tradicional', fam: 'fun', n: 'Marketing tradicional y digital',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.t(52, 16, 'TRADICIONAL', { s: 6.4, b: 1 }) + K.t(148, 16, 'DIGITAL', { s: 6.4, b: 1 }) + K.r(22, 24, 60, 40, 2, P.gris, { w: .8 }) + K.r(26, 28, 52, 30, 1, P.amarillo, { w: .5 }) + K.t(52, 46, 'VALLA', { s: 7, b: 1 }) + K.l('M44 64 L44 74 M60 64 L60 74', P.grisO, { w: 1.4 }) + pant(K, 120, 24, 56, 38) + K.r(126, 36, 44, 8, 2, P.azul, { w: .4 }) + K.r(126, 48, 20, 8, 2, P.rosa, { w: .4 }) + K.r(150, 48, 20, 8, 2, P.verde, { w: .4 }); [['lo ve todo el que pasa', 'lo ve quien yo elijo'], ['caro para empezar', 'desde importes pequeños'], ['difícil de medir', 'se mide cada clic'], ['mensaje en un sentido', 'el cliente responde']].forEach(function (f, i) { var y = 88 + i * 11; s += K.t(52, y, f[0], { s: 5, a: 'middle' }) + K.t(148, y, f[1], { s: 5 }); }); return s + K.l('M100 80 L100 130', P.grisO, { w: .5 }); },
      intro: 'El marketing digital usa internet para llegar a las personas; se puede dirigir, medir y ajustar mejor que el tradicional.',
      q: [['¿Qué ventaja tiene el digital para un negocio pequeño?', 'Se puede empezar con poco dinero y medir los resultados.'], ['¿Sigue sirviendo el tradicional?', 'Sí: un cartel o un folleto funcionan bien en el barrio.'], ['¿Qué significa que el cliente responde?', 'Puede comentar, escribir o compartir el mensaje.']],
      porque: 'Lo mejor suele ser combinar los dos según dónde está el cliente.' },
    { id: 'mk_ecosistema', fam: 'fun', n: 'Canales digitales alrededor de la web',
      d: function (K) { var s = K.suelo(100, 140, 96), C = [[100, 18, 'buscadores'], [166, 42, 'redes sociales'], [166, 98, 'correo'], [100, 122, 'mensajería'], [34, 98, 'anuncios'], [34, 42, 'mapas y fichas']]; C.forEach(function (c, i) { s += K.flecha(c[0], c[1], 100 + (c[0] - 100) * .3, 68 + (c[1] - 68) * .3, P.grisO, { w: .8, p: 2.5 }); }); s += pant(K, 78, 52, 44, 32) + K.t(100, 74, 'MI WEB', { s: 6, b: 1 }); C.forEach(function (c, i) { s += K.r(c[0] - 24, c[1] - 7, 48, 13, 6, CO[i], { w: .7 }) + K.t(c[0], c[1] + 1.8, c[2], { s: ajusta(c[2], 44, 5.6), b: 1 }); }); return s + K.t(100, 141, 'Todos los caminos llevan a un lugar propio', { s: 5.2, b: 1 }); },
      intro: 'Los canales digitales atraen a las personas hacia un espacio propio, como la web, donde el negocio controla el mensaje.',
      q: [['¿Por qué es importante tener un espacio propio?', 'Porque las redes cambian sus reglas y la web es del negocio.'], ['¿Qué canal usa quien busca «panadería cerca»?', 'Buscadores y mapas.'], ['Nombra dos canales gratuitos.', 'Redes sociales y ficha en mapas.']],
      porque: 'Depender de un solo canal es arriesgado: si falla, se pierde el contacto con los clientes.' },
    { id: 'mk_beneficio', fam: 'fun', n: 'Característica, ventaja y beneficio',
      d: function (K) { var F = [['CARACTERÍSTICA', 'lo que tiene', 'batería de 5 000 mAh', P.gris], ['VENTAJA', 'lo que hace', 'dura dos días', P.azul], ['BENEFICIO', 'lo que gano yo', 'no me quedo sin móvil de viaje', P.verde]], s = K.suelo(100, 140, 96); F.forEach(function (f, i) { var y = 16 + i * 36; s += K.r(14, y, 70, 28, 4, f[3], { w: .8 }) + K.t(49, y + 12, f[0], { s: ajusta(f[0], 64, 6.4), b: 1 }) + K.t(49, y + 21, f[1], { s: 5 }) + K.r(96, y + 3, 92, 22, 11, P.blanco, { w: .6 }) + K.t(142, y + 16, '«' + f[2] + '»', { s: ajusta(f[2], 84, 5.4) }); if (i < 2) s += K.flecha(49, y + 29, 49, y + 35, P.tinta, { w: .8, p: 2 }); }); return s + K.t(100, 132, 'El cliente compra el beneficio, no la característica', { s: 5.6, b: 1 }); },
      intro: 'Un buen mensaje traduce cada característica del producto en el beneficio que obtiene la persona.',
      q: [['¿Qué beneficio tiene «horno de leña» en una pizzería?', 'Una pizza con sabor ahumado y crujiente.'], ['¿Por qué no basta con dar la característica?', 'Porque el cliente no siempre entiende qué gana con ella.'], ['Convierte «abierto 24 horas» en beneficio.', 'Puedes comprar cuando lo necesites, incluso de noche.']],
      porque: 'Hablar de beneficios conecta el producto con la vida del cliente.' },
    { id: 'mk_propuesta', fam: 'fun', n: 'Propuesta de valor en una frase',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(12, 22, 176, 44, 6, P.amarillo, { w: 1 }), T = [['Ayudo a', 'familias con poco tiempo', P.azul], ['a', 'comer casero cada día', P.verde], ['con', 'menús listos en 10 minutos', P.rosa]]; T.forEach(function (t, i) { var y = 34 + i * 11; s += K.t(20, y, t[0], { s: 6, a: 'start' }) + K.r(48, y - 7, 132, 9, 2, t[2], { w: .4 }) + K.t(52, y, t[1], { s: 6, b: 1, a: 'start' }); }); return s + K.t(54, 84, 'para quién', { s: 5.2, b: 1, c: P.azulO }) + K.t(100, 84, 'qué logra', { s: 5.2, b: 1, c: P.verdeO }) + K.t(148, 84, 'cómo', { s: 5.2, b: 1, c: P.rojoO }) + K.t(100, 106, 'Clara: se entiende en 5 segundos', { s: 5.6 }) + K.t(100, 116, 'Concreta: dice para quién es', { s: 5.6 }) + K.t(100, 126, 'Distinta: dice por qué yo', { s: 5.6 }); },
      intro: 'La propuesta de valor resume en una frase a quién ayuda el negocio, qué consigue y cómo lo hace.',
      q: [['¿Para quién es la propuesta del ejemplo?', 'Para familias con poco tiempo.'], ['¿Qué la hace distinta?', 'Los menús listos en 10 minutos.'], ['Escribe la propuesta de tu negocio con la misma estructura.', 'Respuesta abierta.']],
      porque: 'Si el cliente no entiende rápido qué ofreces, se va a otra página.' },
    /* ─────────── EL CLIENTE ─────────── */
    { id: 'mk_segmentar', fam: 'cli', n: 'Segmentar el mercado',
      d: function (K) { var D = [['jóvenes', 35, P.azul], ['familias', 30, P.verde], ['mayores', 20, P.amarillo], ['empresas', 15, P.rosa]], s = K.suelo(100, 140, 96) + sector(K, 60, 66, 42, D); D.forEach(function (d, i) { var y = 34 + i * 18; s += K.r(118, y - 6, 9, 9, 1.5, d[2], { w: .6 }) + K.t(132, y + 1, d[0] + ' · ' + d[1] + ' %', { s: 6, a: 'start' }); }); s += K.c(60, 66, 44, 'none', { w: .1 }); return s + K.t(100, 126, 'Segmentar: dividir en grupos con necesidades parecidas', { s: 5.2, b: 1 }) + K.t(100, 136, 'Por edad, zona, ingresos, gustos o forma de comprar', { s: 5 }); },
      intro: 'Segmentar es dividir a los posibles clientes en grupos que tienen necesidades y costumbres parecidas.',
      q: [['¿Qué grupo es el mayor?', 'Los jóvenes, con un 35 %.'], ['Si el mercado son 2 000 personas, ¿cuántas son familias?', '30 % de 2 000 = 600.'], ['¿Por qué no dirigirse a todos a la vez?', 'Porque cada grupo necesita un mensaje y un canal distintos.']],
      porque: 'Un mensaje pensado para un grupo concreto convence más que uno para todo el mundo.' },
    { id: 'mk_persona', fam: 'cli', n: 'Ficha del cliente ideal',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(12, 14, 176, 112, 6, P.blanco, { w: 1 }) + K.c(42, 46, 20, P.azul, { w: .8 }) + per(K, 42, 40, P.morado, .9) + K.t(42, 78, 'Lucía, 34', { s: 6.4, b: 1 }) + K.t(42, 86, 'enfermera', { s: 5.2 }); [['Quiere', 'cenar sano sin cocinar mucho'], ['Le preocupa', 'el precio y el tiempo'], ['Usa', 'el móvil en el descanso'], ['Busca en', 'mensajería y vídeos cortos'], ['Le convence', 'opiniones de otras madres']].forEach(function (f, i) { var y = 30 + i * 18; s += K.t(74, y, f[0], { s: 5.4, b: 1, a: 'start', c: P.azulO }) + K.t(74, y + 7, f[1], { s: ajusta(f[1], 108, 5.4), a: 'start' }); }); return s + K.t(42, 104, 'Personaje', { s: 5, b: 1 }) + K.t(42, 111, 'inventado con', { s: 4.8 }) + K.t(42, 117, 'datos reales', { s: 4.8 }); },
      intro: 'La ficha del cliente ideal describe a una persona inventada que representa al cliente típico, con datos reales detrás.',
      q: [['¿Dónde conviene anunciarse para Lucía?', 'En mensajería y vídeos cortos desde el móvil.'], ['¿Qué mensaje le convencería?', 'Uno con opiniones de otras madres y precio claro.'], ['¿De dónde salen los datos?', 'De encuestas, conversaciones y ventas reales.']],
      porque: 'Pensar en una persona concreta ayuda a escribir mensajes que suenan cercanos.' },
    { id: 'mk_encuesta', fam: 'cli', n: 'Encuesta a clientes',
      d: function (K) { var D = [['precio', 42], ['sabor', 78], ['rapidez', 55], ['envase', 18], ['trato', 64]], s = K.suelo(100, 140, 96) + K.t(100, 16, '¿Qué valoras más? (100 respuestas, varias opciones)', { s: 5.2, b: 1 }); D.forEach(function (d, i) { var y = 30 + i * 16; s += K.t(48, y + 4, d[0], { s: 5.8, a: 'end' }) + K.r(52, y - 3, 120, 10, 2, P.gris, { w: .4 }) + K.r(52, y - 3, d[1] * 1.2, 10, 2, CO[i], { w: .5 }) + K.t(176, y + 4, d[1] + ' %', { s: 5.4, b: 1, a: 'start' }); }); return s + K.t(100, 122, 'Lo más valorado: el sabor (78 %)', { s: 5.8, b: 1 }) + K.t(100, 132, 'Preguntas cortas, con opciones y una abierta al final', { s: 5 }); },
      intro: 'Una encuesta sencilla muestra qué valoran los clientes y ayuda a decidir qué destacar en la comunicación.',
      q: [['¿Qué conviene destacar en los anuncios?', 'El sabor y el buen trato.'], ['¿Cuántas personas eligieron el envase?', '18 de 100.'], ['¿Por qué la suma pasa de 100 %?', 'Porque cada persona podía elegir varias opciones.']],
      porque: 'Preguntar es más barato que adivinar lo que quiere el cliente.' },
    { id: 'mk_foda', fam: 'cli', n: 'Análisis FODA',
      d: function (K) { var C = [['FORTALEZAS', 'receta propia, trato cercano', P.verde], ['DEBILIDADES', 'poca presencia en internet', P.rojo], ['OPORTUNIDADES', 'más pedidos a domicilio', P.azul], ['AMENAZAS', 'cadena nueva en la zona', P.amarillo]], s = K.suelo(100, 140, 96) + K.t(54, 14, 'interno', { s: 5, b: 1 }) + K.t(146, 14, 'interno', { s: 5, b: 1 }) ; s = K.suelo(100, 140, 96) + K.t(8, 46, 'dentro', { s: 4.8, b: 1, a: 'start' }) + K.t(8, 98, 'fuera', { s: 4.8, b: 1, a: 'start' }); C.forEach(function (c, i) { var x = 30 + (i % 2) * 84, y = 18 + Math.floor(i / 2) * 52; s += K.r(x, y, 80, 48, 4, c[2], { w: .9 }) + K.t(x + 40, y + 18, c[0], { s: ajusta(c[0], 74, 6.6), b: 1 }) + K.t(x + 40, y + 32, c[1], { s: ajusta(c[1], 74, 5) }); }); return s + K.t(110, 132, 'Usar fortalezas para aprovechar oportunidades', { s: 5.6, b: 1 }); },
      intro: 'El FODA reúne lo bueno y lo malo del propio negocio (fortalezas y debilidades) y del entorno (oportunidades y amenazas).',
      q: [['¿La cadena nueva es debilidad o amenaza?', 'Amenaza: viene de fuera.'], ['¿Cómo convertir la debilidad en acción?', 'Abrir una ficha en mapas y redes.'], ['Une una fortaleza con una oportunidad.', 'Receta propia + pedidos a domicilio: reparto con sabor casero.']],
      porque: 'Ver todo el cuadro ayuda a decidir en qué invertir tiempo y dinero.' },
    { id: 'mk_diana', fam: 'cli', n: 'Público objetivo: de general a concreto',
      d: function (K) { var R = [[58, P.gris, 'todas las personas'], [44, P.azul, 'adultos de mi ciudad'], [30, P.verde, 'que hacen deporte'], [16, P.amarillo, 'y comen sin gluten']], s = K.suelo(100, 140, 96); R.forEach(function (r) { s += K.c(70, 72, r[0], r[1], { w: .8 }); }); s += K.c(70, 72, 5, P.rojo, { w: .7 }) + K.flecha(178, 30, 76, 70, P.rojoO, { w: 1.2, p: 3 }); R.forEach(function (r, i) { s += K.t(134, 92 + i * 10, (i + 1) + '. ' + r[2], { s: ajusta((i + 1) + '. ' + r[2], 64, 5.4), a: 'start' }); }); return s + K.t(150, 24, 'mi mensaje', { s: 5.4, b: 1 }) + K.t(100, 140, 'Cuanto más concreto, más fácil acertar', { s: 5.6, b: 1 }); },
      intro: 'El público objetivo se define estrechando poco a poco el grupo hasta llegar a quien más necesita el producto.',
      q: [['¿Cuál es el público del centro de la diana?', 'Adultos de la ciudad que hacen deporte y comen sin gluten.'], ['¿Por qué no anunciar a todas las personas?', 'Se gasta mucho y la mayoría no está interesada.'], ['Define el público de una tienda de comida para perros.', 'Dueños de perros de la zona, por ejemplo.']],
      porque: 'Un anuncio dirigido a pocas personas adecuadas rinde más que uno para todos.' },
    { id: 'mk_escucha', fam: 'cli', n: 'Escuchar lo que dicen en internet',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.c(100, 70, 16, P.azul, { w: 1 }) + K.c(100, 70, 9, P.blanco, { w: .7 }) + K.c(100, 70, 4, P.tinta, { negro: 1, w: .3 }), B = [[40, 28, '«¡Qué rico el pan!»', P.verde], [160, 28, '«Tardó mucho»', P.rojo], [36, 108, '«¿Abren el domingo?»', P.amarillo], [164, 108, '«Lo recomiendo»', P.verde]]; B.forEach(function (b) { s += K.r(b[0] - 30, b[1] - 9, 60, 16, 7, b[3], { w: .7 }) + K.t(b[0], b[1] + 1.5, b[2], { s: ajusta(b[2], 56, 5.2) }) + K.l('M' + b[0] + ' ' + (b[1] + (b[1] < 70 ? 8 : -9)) + ' L' + (100 + (b[0] - 100) * .3) + ' ' + (70 + (b[1] - 70) * .3), P.grisO, { w: .5 }); }); return s + K.t(100, 136, 'Responder dudas, agradecer y corregir lo que falla', { s: 5.4, b: 1 }); },
      intro: 'Escuchar en internet es leer comentarios, reseñas y menciones para saber qué piensan los clientes.',
      q: [['¿Qué hacer con «Tardó mucho»?', 'Disculparse, explicar y mejorar el tiempo de entrega.'], ['¿Qué revela «¿Abren el domingo?»?', 'Que falta información clara del horario.'], ['¿Dónde se pueden encontrar estos comentarios?', 'En reseñas, redes y mensajes.']],
      porque: 'Los comentarios son una encuesta gratuita y continua.' },
    /* ─────────── MARCA Y CONTENIDO ─────────── */
    { id: 'mk_identidad', fam: 'mar', n: 'Identidad visual de una marca',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.c(46, 50, 26, P.verde, { w: 1 }) + K.t(46, 48, 'VERDE', { s: 7, b: 1 }) + K.t(46, 57, 'HUERTA', { s: 5.6, b: 1 }) + K.t(46, 88, 'logotipo', { s: 5.4, b: 1 }); ['#3E7A3A', '#B8D8A0', '#F4DC90', '#2A2420'].forEach(function (c, i) { s += K.r(92 + i * 24, 28, 20, 20, 2, c, { w: .6 }); }); s += K.t(136, 56, 'colores', { s: 5.4, b: 1 }) + K.t(136, 74, 'Aa Bb Cc', { s: 9, b: 1 }) + K.t(136, 84, 'tipo de letra', { s: 5.4, b: 1 }) + K.r(92, 92, 44, 26, 3, P.blanco, { w: .7 }) + K.c(102, 100, 4, P.verde, { w: .4 }) + renglones(K, 108, 99, 24, 3, 5) + K.r(140, 92, 44, 26, 3, P.verde, { w: .7 }) + K.t(162, 107, 'bolsa', { s: 5.2, b: 1 }); return s + K.t(46, 112, 'siempre igual', { s: 5 }) + K.t(46, 119, 'en todo', { s: 5 }) + K.t(100, 136, 'Repetir la misma imagen hace que te reconozcan', { s: 5.6, b: 1 }); },
      intro: 'La identidad visual es el conjunto de logotipo, colores y letras que hace reconocible a una marca en cualquier lugar.',
      q: [['¿Por qué usar siempre los mismos colores?', 'Para que el cliente reconozca la marca enseguida.'], ['¿Qué transmite el verde en una frutería?', 'Frescura y naturaleza.'], ['Nombra tres lugares donde debe aparecer la identidad.', 'Bolsa, redes y tarjeta, por ejemplo.']],
      porque: 'La repetición coherente crea recuerdo y confianza.' },
    { id: 'mk_color', fam: 'mar', n: 'Lo que suelen transmitir los colores',
      d: function (K) { var C = [['rojo', 'energía, urgencia', P.rojo], ['azul', 'confianza, calma', P.azul], ['verde', 'salud, naturaleza', P.verde], ['amarillo', 'alegría, atención', P.amarillo], ['morado', 'creatividad, lujo', P.morado], ['naranja', 'cercanía, apetito', P.naranja]], s = K.suelo(100, 140, 96); C.forEach(function (c, i) { var x = 34 + (i % 3) * 66, y = 38 + Math.floor(i / 3) * 50; s += K.c(x, y, 16, c[2], { w: .9 }) + K.t(x, y + 2, c[0], { s: 5.8, b: 1 }) + K.t(x, y + 25, c[1], { s: ajusta(c[1], 62, 5.2) }); }); return s + K.t(100, 132, 'Varía según la cultura: es una guía, no una regla', { s: 5.4, b: 1 }); },
      intro: 'Los colores despiertan asociaciones; elegirlos bien refuerza lo que la marca quiere comunicar.',
      q: [['¿Qué color elegirías para una clínica?', 'Azul o verde: confianza y salud.'], ['¿Por qué muchas ofertas usan rojo?', 'Porque transmite urgencia y llama la atención.'], ['¿Significan lo mismo en todos los países?', 'No siempre: depende de la cultura.']],
      porque: 'El color se percibe antes que las palabras.' },
    { id: 'mk_voz', fam: 'mar', n: 'El tono de voz de la marca',
      d: function (K) { var E = [['formal', 'cercano', .75], ['serio', 'divertido', .6], ['técnico', 'sencillo', .8], ['clásico', 'moderno', .55]], s = K.suelo(100, 140, 96) + K.t(100, 16, 'Una marca de helados artesanos', { s: 6, b: 1 }); E.forEach(function (e, i) { var y = 32 + i * 16; s += K.t(42, y + 2, e[0], { s: 5.6, a: 'end' }) + K.l('M48 ' + y + ' L152 ' + y, P.grisO, { w: 1.6 }) + K.c(48 + e[2] * 104, y, 4, P.rosa, { w: .8 }) + K.t(158, y + 2, e[1], { s: 5.6, a: 'start' }); }); return s + K.r(20, 98, 160, 22, 11, P.rosa, { w: .7 }) + K.t(100, 111, '«¡Hoy toca fresa! Recién hecha, como te gusta 🍓»'.replace(' 🍓', ''), { s: 5.4 }) + K.t(100, 134, 'Escribir siempre con la misma personalidad', { s: 5.6, b: 1 }); },
      intro: 'El tono de voz es la personalidad con la que escribe la marca: más formal o cercana, más seria o divertida.',
      q: [['¿El ejemplo es formal o cercano?', 'Cercano: tutea y usa exclamaciones.'], ['¿Qué tono usaría un despacho de abogados?', 'Más formal y técnico.'], ['¿Por qué mantener el mismo tono?', 'Para que la marca suene coherente en todos los canales.']],
      porque: 'Las personas confían en marcas que suenan siempre como la misma persona.' },
    { id: 'mk_historia', fam: 'mar', n: 'Contar una historia de marca',
      d: function (K) { var E = [['cliente', 'tiene un problema'], ['marca', 'aparece como guía'], ['plan', 'pasos sencillos'], ['acción', 'el cliente prueba'], ['final feliz', 'problema resuelto']], s = K.suelo(100, 140, 96) + K.l('M14 104 Q60 100 80 70 Q100 30 130 34 Q160 38 186 70', P.grisO, { w: 1.2 }); E.forEach(function (e, i) { var x = [16, 54, 100, 142, 182][i], y = [104, 88, 40, 36, 72][i]; s += K.c(x, y, 6, CO[i], { w: .8 }) + K.t(x, y + 2.2, String(i + 1), { s: 6, b: 1 }) + K.t(x + (i === 0 ? 6 : i === 4 ? -6 : 0), y + 14, e[0], { s: 5.6, b: 1 }) + K.t(x + (i === 0 ? 6 : i === 4 ? -6 : 0), y + 21, e[1], { s: ajusta(e[1], 40, 4.6) }); }); return s + K.t(100, 136, 'El protagonista es el cliente, no la marca', { s: 5.8, b: 1 }); },
      intro: 'Una historia de marca sitúa al cliente como protagonista que, con ayuda de la marca, resuelve su problema.',
      q: [['¿Quién es el protagonista de la historia?', 'El cliente.'], ['¿Qué papel tiene la marca?', 'El de guía que ofrece un plan.'], ['Cuenta en tres frases la historia de un cliente de tu negocio.', 'Respuesta abierta.']],
      porque: 'Las historias se recuerdan mucho mejor que una lista de datos.' },
    G('mk_contenidos', 'mar', 'Tipos de contenido', [['Enseñar', 'trucos, tutoriales, guías'], ['Inspirar', 'antes y después, ideas'], ['Entretener', 'humor, retos, curiosidades'], ['Mostrar', 'detrás de cámaras, equipo'], ['Demostrar', 'opiniones, casos reales'], ['Vender', 'ofertas, novedades']], 2, 20, 28, 'Vender en uno de cada cinco, aportar valor en los demás', 'El contenido digital puede enseñar, inspirar, entretener o vender; mezclarlos mantiene el interés.', [['¿Qué tipo es «cómo guardar el pan para que dure»?', 'Enseñar.'], ['¿Por qué no publicar solo ofertas?', 'Porque la gente se cansa y deja de seguir la cuenta.'], ['Da un ejemplo de contenido para «mostrar».', 'Un vídeo del horno a las 5 de la mañana.']], 'El contenido útil hace que la gente vuelva aunque hoy no compre.', { s: 7, s2: 5.2 })
  ];
  window.EU_DIGI_K.FAM_MKT = FAM;
  MO.agregar('mkt', L, { nombre: 'Marketing digital', familias: FAM, materias: /^(mkt)$/ });
})();
