/* b6_lib_batidos2.js — Batidos (2/3): semillas y extras, equipo y batidos por objetivo. 33 modelos para EU_MODELOS.
   Cargar después de b6_lib_batidos.js. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('bt_chia')) return;
  var M = MO.M;
  var C = { chia: '#5A5450', lino: '#8A5A2E', avena: '#E8D6A8', cacahuete: '#C8904A', nuez: '#A8743E', datil: '#6A3A1E', cacao: '#5A3521', miel: '#E0A02A', canela: '#A4602F', proteina: '#EFE8DA', hielo: '#DDF1F8', verde: '#7FB548', rosa: '#E86A8A', morado: '#6A3A7A', naranja: '#F29A3A', amarillo: '#F2C94B', choco: '#7A4A2E', rojo: '#D2453E', cafe: '#8A5A3A', blanco: '#F4EFE6' };
  function vaso(K, x, y, w, h, c, o) {
    o = o || {}; var s = K.suelo(x, y + h + 2, w * .7) + K.p('M' + (x - w / 2) + ' ' + y + ' L' + (x - w * .38) + ' ' + (y + h) + ' L' + (x + w * .38) + ' ' + (y + h) + ' L' + (x + w / 2) + ' ' + y + ' Z', M.vidrio, { op: .7 });
    s += K.p('M' + (x - w * .47) + ' ' + (y + h * .1) + ' L' + (x - w * .38) + ' ' + (y + h - 2) + ' L' + (x + w * .38) + ' ' + (y + h - 2) + ' L' + (x + w * .47) + ' ' + (y + h * .1) + ' Z', c) + K.e(x, y + h * .1, w * .47, 3, K.claro(c, .2));
    if (o.pajita !== false) s += K.l('M' + (x + w * .1) + ' ' + (y + h * .5) + ' L' + (x + w * .32) + ' ' + (y - 22), o.pc || '#E8E0D0', { w: 3.4 });
    return s + K.brillo(x - w * .3, y + h * .5, 2, h * .3);
  }
  function tabla(K, x, y, filas, w) { var s = ''; filas.forEach(function (f, i) { s += K.t(x, y + i * 11, f[0], { s: 6.6, a: 'start' }) + K.t(x + w, y + i * 11, f[1], { s: 6.6, b: 1, a: 'end' }); }); return s; }

  var L = [
    /* ─────────── SEMILLAS Y EXTRAS ─────────── */
    { id: 'bt_chia', fam: 'ext', n: 'Semillas de chía',
      d: function (K) { var s = K.suelo(100, 124, 86) + K.cil(52, 70, 28, 50, M.vidrio, { abierto: 1 }); for (var i = 0; i < 40; i++) s += K.e(30 + (i * 17) % 44, 96 + (i * 7) % 22, 1.4, 1, C.chia, { sin: 1 }); s += K.t(52, 136, 'Secas', { s: 7, b: 1 }) + K.flecha(88, 90, 106, 90, '#555') + K.cil(146, 70, 28, 50, M.vidrio, { abierto: 1 }) + K.r(119, 76, 54, 44, 0, '#E6E2D8', { op: .9 }); for (var j = 0; j < 30; j++) s += K.c(126 + (j * 13) % 40, 82 + (j * 11) % 34, 2.6, '#F2EEE6', { w: .5 }) + K.c(126 + (j * 13) % 40, 82 + (j * 11) % 34, 1, C.chia, { sin: 1 }); return s + K.t(146, 136, 'Hidratadas 15 min', { s: 7, b: 1 }); },
      rot: [['Gel de mucílago', 150, 96, 186, 60]],
      intro: 'Semillas diminutas que absorben hasta 10 veces su peso en agua y espesan el batido.',
      q: [['¿Cuánta se pone por batido?', 'Una cucharada, unos 10-12 g.'], ['¿Qué ácido graso aportan?', 'Omega 3 de origen vegetal.'], ['¿Por qué conviene hidratarlas antes?', 'Forman el gel y resultan más fáciles de digerir.']],
      porque: 'Su cubierta suelta mucílago, una fibra soluble que retiene agua y forma un gel.' },
    { id: 'bt_linaza', fam: 'ext', n: 'Linaza molida',
      d: function (K) { var s = K.suelo(100, 118, 86); for (var i = 0; i < 20; i++) s += K.e(34 + (i % 5) * 9, 80 + Math.floor(i / 5) * 7, 3.4, 2, C.lino, { w: .5 }); s += K.t(52, 124, 'Entera', { s: 7, b: 1 }) + K.flecha(80, 90, 104, 90, '#555') + K.p('M118 104 Q120 78 148 76 Q176 78 178 104 Z', '#B88A5A'); for (var j = 0; j < 30; j++) s += K.c(124 + (j * 7) % 50, 86 + (j * 5) % 16, .9, '#6A4A2A', { sin: 1 }); return s + K.t(148, 124, 'Molida', { s: 7, b: 1 }); },
      intro: 'Semillas de lino: hay que molerlas, porque enteras atraviesan el intestino sin digerirse.',
      q: [['¿Por qué se muele?', 'La cáscara dura impide absorber su omega 3.'], ['¿Cómo se guarda molida?', 'En frasco cerrado en la nevera: se oxida rápido.'], ['¿Cuánta se usa?', 'Una cucharada.']],
      porque: 'Al moler se rompe la cubierta y el cuerpo accede al aceite y la fibra del interior.' },
    { id: 'bt_avena_copos', fam: 'ext', n: 'Copos de avena',
      d: function (K) { var s = K.suelo(100, 120, 80) + K.p('M40 90 Q44 120 100 120 Q156 120 160 90 Z', M.ceramica) + K.e(100, 90, 60, 12, K.oscuro(M.ceramica, .2)); for (var i = 0; i < 24; i++) s += K.e(50 + (i * 23) % 100, 82 + (i * 7) % 12, 6, 3.4, C.avena, { w: .6 }); return s + K.t(100, 40, '40 g = 150 kcal, 4 g de fibra', { s: 7, b: 1 }); },
      intro: 'Dan cuerpo y energía de liberación lenta; convierten el batido en un desayuno completo.',
      q: [['¿Crudos o remojados?', 'Se pueden batir crudos; remojados quedan más finos.'], ['¿Qué fibra especial tienen?', 'Betaglucano.'], ['¿Por qué sacian?', 'La fibra forma un gel que retrasa el vaciado del estómago.']],
      porque: 'El almidón de la avena se digiere despacio y la glucosa sube de forma gradual.' },
    { id: 'bt_crema_cacahuete', fam: 'ext', n: 'Crema de cacahuete',
      d: function (K) { var s = K.suelo(100, 124, 70) + K.cil(70, 56, 32, 64, M.vidrio, { abierto: 1 }) + K.r(39, 64, 62, 56, 0, C.cacahuete) + K.cil(70, 46, 32, 10, C.rojo) + K.r(44, 80, 52, 22, 1, M.blanco) + K.t(70, 94, '100 %', { s: 7, b: 1 }); [[140, 90], [160, 96], [150, 108]].forEach(function (q) { s += K.p('M' + (q[0] - 10) + ' ' + q[1] + ' q0 -8 7 -8 q3 3 6 0 q7 0 7 8 q0 8 -7 8 q-3 -3 -6 0 q-7 0 -7 -8 Z', '#D8A868'); }); return s; },
      rot: [['Solo cacahuete', 70, 92, 20, 134]],
      intro: 'Aporta proteína y grasa: una cucharada vuelve el batido saciante.',
      q: [['¿Qué se mira en la etiqueta?', 'Que sea 100 % cacahuete, sin azúcar ni aceite de palma.'], ['¿Cuánta proteína tiene una cucharada?', 'Unos 4 g.'], ['¿Por qué se usa poca?', 'Tiene muchas calorías: unas 95 por cucharada.']],
      porque: 'La grasa y la proteína retrasan la digestión y alargan la saciedad.' },
    { id: 'bt_frutos_secos', fam: 'ext', n: 'Frutos secos',
      d: function (K) { var s = K.suelo(100, 122, 90); [[40, 'Nuez', C.nuez], [80, 'Almendra', '#B8784A'], [120, 'Anacardo', '#E8C890'], [160, 'Avellana', '#9A6A3A']].forEach(function (q, i) { var x = q[0]; if (i === 0) s += K.c(x, 88, 14, q[2]) + K.l('M' + x + ' 74 L' + x + ' 102 M' + (x - 10) + ' 82 q10 6 20 0 M' + (x - 10) + ' 94 q10 -6 20 0', K.oscuro(q[2], .3)); else if (i === 1) s += K.p('M' + x + ' 72 Q' + (x + 12) + ' 88 ' + x + ' 104 Q' + (x - 12) + ' 88 ' + x + ' 72 Z', q[2]); else if (i === 2) s += K.p('M' + (x - 12) + ' 80 Q' + (x - 14) + ' 102 ' + x + ' 102 Q' + (x + 10) + ' 100 ' + (x + 8) + ' 90 Q' + (x - 2) + ' 92 ' + (x - 2) + ' 80 Z', q[2]); else s += K.c(x, 90, 12, q[2]) + K.e(x, 80, 6, 3, '#C8A070'); s += K.t(x, 124, q[1], { s: 7, b: 1 }); }); return s + K.t(100, 40, 'Una porción = un puñado (25-30 g)', { s: 7, b: 1 }); },
      intro: 'Grasas buenas, proteína y vitamina E; se remojan unas horas para que se trituren mejor.',
      q: [['¿Cuál tiene más omega 3?', 'La nuez.'], ['¿Por qué se remojan?', 'Se ablandan y el batido queda más fino.'], ['¿Qué alergia hay que preguntar siempre?', 'La alergia a frutos secos.']],
      porque: 'El remojo hidrata la semilla y la vuelve más blanda para la cuchilla.' },
    { id: 'bt_datiles', fam: 'ext', n: 'Dátiles',
      d: function (K) { var s = K.suelo(100, 118, 80); [[50, 84], [80, 90], [110, 84], [140, 90]].forEach(function (q, i) { s += K.e(q[0], q[1], 13, 22, C.datil) + K.l('M' + (q[0] - 6) + ' ' + (q[1] - 10) + ' q4 8 0 20', K.claro(C.datil, .2)) + K.brillo(q[0] - 4, q[1] - 8, 2, 5); }); return s + K.e(170, 104, 4, 10, '#D8C0A0') + K.t(170, 124, 'Hueso', { s: 7, b: 1 }); },
      intro: 'Endulzan de forma natural y aportan fibra y potasio; uno o dos bastan.',
      q: [['¿Son mejores que el azúcar?', 'Aportan fibra y minerales, pero siguen siendo azúcar: con moderación.'], ['¿Qué se quita antes?', 'El hueso.'], ['¿Qué variedad es más blanda?', 'La Medjool.']],
      porque: 'La fibra del dátil hace que su azúcar pase más despacio a la sangre que el azúcar de mesa.' },
    { id: 'bt_cacao', fam: 'ext', n: 'Cacao puro',
      d: function (K) { var s = K.suelo(100, 118, 86) + K.p('M16 82 Q20 52 54 50 Q90 52 92 82 Q88 110 54 112 Q20 110 16 82 Z', '#8A4A2A'); for (var i = 0; i < 5; i++) s += K.l('M' + (26 + i * 14) + ' 54 q4 28 0 56', '#6A3418'); s += K.p('M112 104 Q114 80 146 78 Q178 80 180 104 Z', M.ceramica) + K.e(146, 92, 30, 7, C.cacao); return s + K.t(54, 128, 'Mazorca', { s: 7, b: 1 }) + K.t(146, 128, 'Cacao en polvo sin azúcar', { s: 6.6, b: 1 }); },
      intro: 'Da sabor a chocolate sin azúcar; aporta magnesio y antioxidantes.',
      q: [['¿En qué se diferencia del cacao soluble?', 'El soluble lleva mucho azúcar; el puro, nada.'], ['¿Cuánto se pone?', 'Una cucharada.'], ['¿Qué fruta combina mejor?', 'El plátano.']],
      porque: 'El sabor amargo del cacao se equilibra con el dulzor natural del plátano maduro.' },
    { id: 'bt_miel', fam: 'ext', n: 'Miel',
      d: function (K) { var s = K.suelo(100, 124, 70) + K.cil(70, 50, 30, 70, M.vidrio, { abierto: 1 }) + K.r(41, 58, 58, 62, 0, C.miel, { op: .9 }) + K.cil(70, 40, 30, 10, M.madera); for (var i = 0; i < 7; i++) { var x = 132 + (i % 3) * 16 + (Math.floor(i / 3) % 2) * 8, y = 64 + Math.floor(i / 3) * 14; s += K.pl([[x, y - 8], [x + 7, y - 4], [x + 7, y + 4], [x, y + 8], [x - 7, y + 4], [x - 7, y - 4]], '#F2C24A'); } return s + K.l('M80 30 Q84 20 92 26 L90 40', M.madera, { w: 2 }); },
      intro: 'Endulzante natural, pero es azúcar: se usa poco y nunca en niños menores de un año.',
      q: [['¿Por qué no en bebés?', 'Puede tener esporas de botulismo que su intestino no controla.'], ['¿Es mejor que el azúcar?', 'Tiene algo más de aroma y minerales, pero cuenta como azúcar libre.'], ['¿Cuánto se pone?', 'Una cucharadita como máximo.']],
      porque: 'La miel es sobre todo fructosa y glucosa: el cuerpo la trata como azúcar añadido.' },
    { id: 'bt_canela', fam: 'ext', n: 'Canela',
      d: function (K) { var s = K.suelo(100, 118, 86); [[30, 64], [40, 78], [34, 92]].forEach(function (q) { s += '<g transform="rotate(-12 ' + q[0] + ' ' + q[1] + ')">' + K.r(q[0], q[1] - 5, 80, 10, 5, C.canela) + K.e(q[0] + 80, q[1], 3, 5, K.oscuro(C.canela, .3)) + K.p('M' + (q[0] + 78) + ' ' + (q[1] - 3) + ' q-3 3 0 6', '#6A3418', { w: .8 }) + '</g>'; }); return s + K.p('M136 104 Q138 82 160 80 Q182 82 184 104 Z', M.ceramica) + K.e(160, 94, 22, 6, K.claro(C.canela, .1)); },
      intro: 'Especia dulce y cálida que da sensación de dulzor sin añadir azúcar.',
      q: [['¿Cuánta se pone?', 'Media cucharadita o una pizca.'], ['¿Qué tipo se recomienda para uso frecuente?', 'La de Ceilán, con menos cumarina.'], ['¿En qué batidos encaja?', 'Con manzana, plátano, avena y cacao.']],
      porque: 'El aroma dulce de la canela hace que el cerebro perciba más dulzor.' },
    { id: 'bt_proteina', fam: 'ext', n: 'Proteína en polvo',
      d: function (K) { return K.suelo(100, 128, 80) + K.cil(66, 38, 34, 86, M.negro) + K.cil(66, 30, 34, 10, '#3A3A3A') + K.r(36, 62, 60, 36, 2, M.blanco) + K.t(66, 76, 'PROTEÍNA', { s: 7.4, b: 1 }) + K.t(66, 88, '20 g / cacito', { s: 6 }) + K.p('M130 90 L170 90 L166 110 L134 110 Z', M.plastico) + K.e(150, 90, 20, 5, C.proteina) + K.l('M166 92 L186 72', M.plastico, { w: 3 }); },
      intro: 'Suplemento de proteína de leche (suero) o vegetal; útil cuando la comida no alcanza.',
      q: [['¿Cuándo tiene sentido?', 'Cuando no se llega a la proteína diaria con alimentos.'], ['¿Qué alternativas naturales hay?', 'Yogur griego, leche, requesón, tofu sedoso.'], ['¿Qué se mira en la etiqueta?', 'Proteína por ración, azúcares y lista corta de ingredientes.']],
      porque: 'La proteína de suero se digiere rápido y llega pronto a los músculos después del ejercicio.' },
    { id: 'bt_hielo', fam: 'ext', n: 'Hielo y fruta congelada',
      d: function (K) { var s = K.suelo(100, 124, 86); [[34, 80], [58, 74], [46, 100], [72, 96]].forEach(function (q) { s += K.caja(q[0] - 10, q[1] - 8, 18, 18, 8, C.hielo); }); s += K.t(52, 130, 'Cubitos', { s: 7, b: 1 }) + K.caja(112, 70, 70, 46, 12, '#E8EEF2'); [[124, 86, '#F2D04B'], [140, 92, '#E0413A'], [156, 84, '#3E4A8A'], [170, 94, '#F2A43A'], [132, 102, '#E0413A'], [160, 104, '#F2D04B']].forEach(function (q) { s += K.c(q[0], q[1], 7, q[2]); }); return s + K.t(146, 130, 'Fruta congelada', { s: 7, b: 1 }); },
      intro: 'Enfrían y espesan; la fruta congelada lo hace sin aguar el sabor.',
      q: [['¿Por qué es mejor la fruta congelada que el hielo?', 'Enfría igual y no diluye el sabor.'], ['¿Cómo se congela el plátano?', 'Pelado y en rodajas, extendido en una bandeja.'], ['¿Qué batidora aguanta el hielo?', 'Una de vaso potente; las de mano sufren.']],
      porque: 'Al triturar algo congelado, los cristales pequeños dan textura de granizado.' },
    { id: 'bt_cafe', fam: 'ext', n: 'Café en el batido',
      d: function (K) { var s = K.suelo(100, 124, 86) + K.cil(56, 76, 24, 38, M.blanco) + K.e(56, 76, 22, 6, C.cafe) + K.p('M80 84 Q96 86 94 98 Q90 108 80 106', 'none', { w: 3 }); [[122, 96], [136, 90], [150, 98], [164, 92], [140, 104], [156, 106]].forEach(function (q) { s += K.e(q[0], q[1], 6, 4, '#4A2A18') + K.l('M' + (q[0] - 4) + ' ' + q[1] + ' q4 -2 8 0', '#8A5A3A'); }); return s + K.t(56, 130, 'Café frío', { s: 7, b: 1 }) + K.t(144, 130, 'Granos', { s: 7, b: 1 }); },
      intro: 'Un poco de café frío convierte un batido de plátano y cacao en un desayuno con energía.',
      q: [['¿Cuánta cafeína es razonable al día para un adulto?', 'Hasta unos 400 mg, unas 3-4 tazas.'], ['¿Por qué frío?', 'El café caliente derrite la fruta congelada y cambia la textura.'], ['¿Quién debe evitarlo?', 'Niños, embarazadas en exceso y personas con hipertensión o ansiedad.']],
      porque: 'La cafeína bloquea la adenosina, la señal química que da sensación de cansancio.' },
    /* ─────────── EQUIPO ─────────── */
    { id: 'bt_batidora_vaso', fam: 'equ', n: 'Batidora de vaso',
      d: function (K) { return K.suelo(100, 136, 50) + K.caja(70, 104, 60, 30, 12, M.negro) + K.c(100, 120, 7, M.gris) + K.p('M70 104 L64 30 L136 30 L130 104 Z', M.vidrio, { op: .8 }) + K.r(62, 22, 76, 10, 3, M.negro) + K.p('M72 100 L68 60 L132 60 L128 100 Z', C.verde, { op: .85 }) + K.p('M86 98 L100 92 L114 98 L100 96 Z', M.acero) + K.p('M136 40 Q156 44 150 80 L132 86', 'none', { w: 3 }) + K.l('M76 50 L92 50 M76 70 L90 70', '#fff', { w: 1 }); },
      rot: [['Tapa con tapón', 130, 26, 170, 16], ['Cuchillas', 104, 95, 170, 104], ['Base motor', 120, 120, 170, 132]],
      intro: 'Motor potente bajo un vaso con cuchillas: la mejor para hielo y fruta congelada.',
      q: [['¿Qué se pone primero en el vaso?', 'El líquido, luego lo blando y al final lo congelado.'], ['¿Por qué ese orden?', 'El líquido cerca de la cuchilla crea el remolino.'], ['¿Cómo se limpia rápido?', 'Agua tibia y una gota de jabón, y se bate 20 segundos.']],
      porque: 'Las cuchillas crean un remolino que baja los trozos una y otra vez hacia el centro.' },
    { id: 'bt_batidora_mano', fam: 'equ', n: 'Batidora de mano',
      d: function (K) { return K.suelo(100, 132, 50) + K.cil(100, 72, 30, 56, M.vidrio, { abierto: 1 }) + K.r(71, 96, 58, 30, 0, C.rosa, { op: .85 }) + K.r(90, 8, 20, 52, 10, M.blanco) + K.r(97, 58, 6, 38, 2, M.metal) + K.p('M86 96 Q100 88 114 96 L110 106 L90 106 Z', M.metal); },
      intro: 'Pequeña y fácil de limpiar; va bien con fruta blanda y líquidos, no con mucho hielo.',
      q: [['¿Dónde se bate?', 'En un vaso alto y estrecho para que no salpique.'], ['¿Qué ingredientes le cuestan?', 'El hielo, los frutos secos enteros y las verduras duras.'], ['¿Cómo se evita que salpique?', 'Se mete hasta el fondo antes de encenderla.']],
      porque: 'La campana protege la cuchilla y crea una succión que atrae los trozos.' },
    { id: 'bt_extractor', fam: 'equ', n: 'Licuadora y extractor',
      d: function (K) { return K.suelo(100, 132, 86) + K.caja(20, 90, 60, 40, 10, M.blanco) + K.cil(50, 50, 22, 40, M.vidrio, { abierto: 1 }) + K.cil(50, 36, 8, 16, M.gris) + K.cil(100, 104, 12, 26, M.vidrio, { abierto: 1 }) + K.r(89, 110, 22, 20, 0, '#F29A3A') + K.p('M80 104 L90 104', '#F29A3A', { w: 3 }) + K.t(50, 144, 'Zumo', { s: 7, b: 1 }) + K.flecha(118, 80, 136, 80, '#555') + K.p('M146 124 L144 60 L184 60 L182 124 Z', M.vidrio, { op: .7 }) + K.r(147, 70, 34, 52, 0, '#F4B85A') + K.t(164, 144, 'Batido: con fibra', { s: 7, b: 1 }); },
      intro: 'La licuadora separa el zumo y desecha la fibra; la batidora la conserva toda.',
      q: [['¿Qué se pierde al licuar?', 'La mayor parte de la fibra.'], ['¿Qué es mejor para la glucosa?', 'El batido, porque la fibra frena el azúcar.'], ['¿Qué se puede hacer con la pulpa del extractor?', 'Añadirla a panes, galletas o caldos.']],
      porque: 'Sin fibra, el azúcar de la fruta pasa muy rápido a la sangre.' },
    { id: 'bt_vaso_medidor', fam: 'equ', n: 'Vaso medidor',
      d: function (K) { var s = K.suelo(100, 128, 60) + K.p('M64 30 L70 124 L130 124 L136 30 Z', M.vidrio, { op: .8 }) + K.r(69, 70, 62, 52, 0, C.blanco, { op: .9 }) + K.p('M136 40 Q156 44 150 80 L132 86', 'none', { w: 3 }); [['500', 40], ['400', 58], ['300', 76], ['200', 94], ['100', 112]].forEach(function (q) { s += K.l('M70 ' + q[1] + ' L84 ' + q[1], '#555', { w: 1 }) + K.t(88, q[1] + 2.4, q[0] + ' ml', { s: 6.5, a: 'start' }); }); return s; },
      intro: 'Medir el líquido evita batidos demasiado aguados o demasiado espesos.',
      q: [['¿Cuánto líquido lleva un batido de un vaso?', 'Entre 200 y 250 ml.'], ['¿Por qué se lee a la altura de los ojos?', 'Visto desde arriba o abajo, la línea engaña.'], ['¿Cuántos ml tiene una taza de medir?', '240 ml en la mayoría de recetas americanas.']],
      porque: 'La superficie del líquido se curva: se lee en la parte baja de esa curva.' },
    { id: 'bt_cucharas_medida', fam: 'equ', n: 'Cucharas medidoras',
      d: function (K) { var t = [['1 cda', 15, 22], ['1 cdta', 5, 16], ['½ cdta', 2.5, 12], ['¼ cdta', 1.25, 9]], s = K.suelo(100, 118, 90); t.forEach(function (q, i) { var x = 34 + i * 44; s += K.e(x, 84, q[2], q[2] * .6, M.metal) + K.e(x, 82, q[2] * .8, q[2] * .45, M.acero) + K.r(x - 2, 84 + q[2] * .5, 4, 22, 2, M.metal) + K.t(x, 124, q[0], { s: 7, b: 1 }) + K.t(x, 134, q[1] + ' ml', { s: 6 }); }); return s; },
      intro: 'Cuatro medidas estándar para semillas, especias y endulzantes.',
      q: [['¿Cuántas cucharaditas tiene una cucharada?', 'Tres.'], ['¿Por qué se enrasa?', 'Una cuchara colmada puede llevar el doble.'], ['¿Cuántos gramos de chía caben en una cucharada?', 'Unos 12 g.']],
      porque: 'Medir por volumen enrasado da siempre la misma cantidad sin báscula.' },
    { id: 'bt_bascula', fam: 'equ', n: 'Báscula de cocina',
      d: function (K) { return K.suelo(100, 128, 76) + K.caja(34, 96, 132, 24, 16, M.blanco) + K.r(76, 102, 48, 14, 2, '#2B3A44') + K.t(100, 112, '150 g', { s: 8, b: 1, c: '#7BD389' }) + K.e(100, 94, 60, 8, M.metal) + K.p('M70 90 Q72 60 100 58 Q128 60 130 90 Z', '#F2D04B') + K.l('M86 64 Q100 90 118 64', '#E0B83A'); },
      intro: 'Pesar la fruta ayuda a repetir el mismo batido y a controlar el azúcar y las calorías.',
      q: [['¿Qué es la función tara?', 'Poner a cero con el recipiente encima.'], ['¿Cuánto pesa una ración de fruta?', 'Entre 120 y 150 g.'], ['¿Por qué pesar si ya se usa taza?', 'La fruta troceada ocupa distinto según el corte.']],
      porque: 'El peso no cambia con la forma de cortar; el volumen sí.' },
    { id: 'bt_colador_fino', fam: 'equ', n: 'Colador fino',
      d: function (K) { var s = K.suelo(100, 124, 70) + K.cil(100, 90, 34, 34, M.vidrio, { abierto: 1 }) + K.r(67, 100, 66, 24, 0, '#C8325A', { op: .8 }) + K.p('M58 74 Q60 104 100 104 Q140 104 142 74 Z', M.metal, { op: .9 }); for (var i = 0; i < 8; i++) s += K.l('M' + (64 + i * 10) + ' 76 L' + (70 + i * 8) + ' 100', M.acero, { w: .5 }); return s + K.e(100, 74, 42, 8, M.acero) + K.r(142, 70, 44, 6, 3, M.negro) + K.puntos([[90, 84], [104, 88], [116, 82]], 1.6, '#3A1A2A'); },
      rot: [['Semillas retenidas', 104, 86, 150, 36]],
      intro: 'Retiene semillas y pieles cuando se quiere una textura muy lisa.',
      q: [['¿Con qué frutas se usa?', 'Frambuesa, mora, maracuyá, guayaba.'], ['¿Se pierde fibra?', 'Sí, un poco.'], ['¿Cómo se acelera el colado?', 'Presionando con el dorso de una cuchara.']],
      porque: 'La malla deja pasar el líquido y la pulpa fina, pero no las semillas.' },
    { id: 'bt_botella', fam: 'equ', n: 'Botella para llevar',
      d: function (K) { return K.suelo(100, 132, 50) + K.cil(100, 30, 24, 100, M.vidrio, { abierto: 1 }) + K.r(77, 46, 46, 84, 0, C.naranja, { op: .85 }) + K.cil(100, 20, 24, 12, M.acero) + K.r(92, 8, 16, 12, 4, M.acero) + K.l('M80 46 L120 46', '#fff', { w: 1, d: '3 3' }) + K.t(146, 60, 'Dejar 2 cm', { s: 6.6, b: 1, a: 'start' }) + K.t(146, 70, 'sin llenar', { s: 6.6, b: 1, a: 'start' }) + K.brillo(84, 90, 3, 26); },
      intro: 'Botella hermética para llevar el batido; se agita antes de beber.',
      q: [['¿Por qué se deja espacio arriba?', 'Para poder agitarlo.'], ['¿Cuánto aguanta sin nevera?', 'Una o dos horas como máximo.'], ['¿Qué material conserva mejor el frío?', 'El acero con doble pared.']],
      porque: 'Al reposar, la pulpa se separa del líquido; al agitar se vuelve a mezclar.' },
    { id: 'bt_cuchillo_tabla', fam: 'equ', n: 'Tabla y cuchillo de fruta',
      d: function (K) { return K.suelo(100, 122, 90) + K.caja(20, 94, 160, 16, 14, M.madera) + K.p('M30 90 Q32 70 52 70 Q72 72 72 90 Z', '#F2A43A') + K.r(80, 80, 12, 12, 2, '#F2A43A') + K.r(96, 82, 12, 12, 2, '#F2A43A') + K.p('M112 82 L172 78 Q186 80 186 86 Q164 92 112 90 Z', '#D5DADF') + K.r(84, 82, 30, 8, 4, M.negro); },
      intro: 'Trocear la fruta del mismo tamaño ayuda a que se triture pareja y rápido.',
      q: [['¿Qué tamaño de trozo es ideal?', 'Unos 2-3 cm.'], ['¿Por qué se lava la fruta antes de pelarla?', 'El cuchillo arrastra suciedad de la piel a la pulpa.'], ['¿Qué tabla se usa para fruta?', 'Una distinta a la de carne cruda.']],
      porque: 'Trozos iguales llegan a la cuchilla al mismo ritmo y el batido no queda con grumos.' },
    /* ─────────── BATIDOS POR OBJETIVO ─────────── */
    { id: 'bt_verde', fam: 'rec', n: 'Batido verde',
      d: function (K) { return vaso(K, 60, 44, 56, 80, C.verde) + tabla(K, 104, 42, [['Espinaca', '30 g'], ['Manzana verde', '1'], ['Pepino', '½'], ['Plátano congelado', '½'], ['Agua o coco', '200 ml'], ['Limón', 'unas gotas']], 84); },
      intro: 'Verdura de hoja con fruta dulce: el primer paso para tomar más verde.',
      q: [['¿Qué proporción de verdura y fruta se recomienda para empezar?', 'Un tercio de verdura y dos tercios de fruta.'], ['¿Para qué el limón?', 'Mantiene el color y ayuda a absorber el hierro.'], ['¿Qué se nota más, la espinaca o la manzana?', 'La manzana; la espinaca casi no sabe.']],
      porque: 'La fruta dulce tapa el sabor amargo de las hojas mientras el paladar se acostumbra.' },
    { id: 'bt_tropical', fam: 'rec', n: 'Batido tropical',
      d: function (K) { return vaso(K, 60, 44, 56, 80, C.naranja, { pc: '#E86A8A' }) + tabla(K, 104, 42, [['Mango', '100 g'], ['Piña', '100 g'], ['Maracuyá', '1'], ['Agua de coco', '200 ml'], ['Jengibre', '1 cm']], 84); },
      intro: 'Fruta tropical con agua de coco: dulce, ácido y refrescante.',
      q: [['¿Por qué se toma enseguida?', 'La piña y el jengibre cambian de sabor al reposar.'], ['¿Qué aporta el agua de coco?', 'Hidratación y potasio con poco azúcar.'], ['¿Cómo se hace más espeso?', 'Con el mango congelado.']],
      porque: 'El ácido del maracuyá realza el aroma dulce del mango.' },
    { id: 'bt_frutos_rojos', fam: 'rec', n: 'Batido de frutos rojos',
      d: function (K) { return vaso(K, 60, 44, 56, 80, '#A8325A') + tabla(K, 104, 42, [['Fresas', '80 g'], ['Arándanos', '60 g'], ['Frambuesas', '40 g'], ['Yogur natural', '125 g'], ['Leche o bebida', '120 ml']], 84); },
      intro: 'Bayas con poco azúcar y mucha fibra, con yogur para la proteína.',
      q: [['¿Por qué es bueno para controlar la glucosa?', 'Las bayas tienen poco azúcar y mucha fibra.'], ['¿Se pueden usar congeladas?', 'Sí, y el batido sale más espeso.'], ['¿Cómo se quitan las semillas?', 'Colándolo.']],
      porque: 'La proteína del yogur y la fibra de las bayas frenan juntas la subida del azúcar.' },
    { id: 'bt_desayuno', fam: 'rec', n: 'Batido desayuno completo',
      d: function (K) { return vaso(K, 60, 44, 56, 80, '#D8B07A') + tabla(K, 104, 42, [['Plátano', '1'], ['Copos de avena', '30 g'], ['Crema de cacahuete', '1 cda'], ['Leche', '250 ml'], ['Canela', 'pizca']], 84) + K.t(146, 110, '≈ 450 kcal · 18 g proteína', { s: 6.4, b: 1 }); },
      intro: 'Carbohidrato lento, proteína y grasa en un vaso: aguanta hasta la comida.',
      q: [['¿Qué aporta la avena?', 'Energía lenta y fibra.'], ['¿Qué aporta el cacahuete?', 'Proteína y grasa, que alargan la saciedad.'], ['¿Cómo se aligera?', 'Con bebida vegetal y medio plátano.']],
      porque: 'Tres nutrientes que se digieren a ritmos distintos dan energía durante varias horas.' },
    { id: 'bt_perder_peso', fam: 'rec', n: 'Objetivo: bajar de peso',
      d: function (K) { return vaso(K, 60, 44, 56, 80, '#9CC46A') + tabla(K, 104, 36, [['Kale o espinaca', '30 g'], ['Pepino', '½'], ['Frutos rojos', '80 g'], ['Chía hidratada', '1 cda'], ['Agua', '200 ml']], 84) + K.r(104, 96, 84, 26, 2, '#EEF6E4') + K.t(146, 107, '≈ 150 kcal', { s: 7.4, b: 1 }) + K.t(146, 117, 'mucha fibra, poco azúcar', { s: 6 }); },
      intro: 'Mucho volumen y fibra con pocas calorías: sacia sin sumar azúcar.',
      q: [['¿Por qué agua y no zumo?', 'El zumo añade azúcar sin fibra.'], ['¿Qué papel cumple la chía?', 'Su gel llena el estómago y sacia.'], ['¿Sustituye una comida?', 'Solo si se añade proteína; si no, es un tentempié.']],
      porque: 'Para bajar de peso se come menos energía de la que se gasta; la fibra ayuda a no pasar hambre.' },
    { id: 'bt_masa_muscular', fam: 'rec', n: 'Objetivo: ganar masa muscular',
      d: function (K) { return vaso(K, 60, 44, 56, 80, C.choco) + tabla(K, 104, 36, [['Leche', '300 ml'], ['Yogur griego', '125 g'], ['Plátano', '1'], ['Avena', '40 g'], ['Cacao puro', '1 cda'], ['Crema de cacahuete', '1 cda']], 84) + K.r(104, 104, 84, 22, 2, '#F4ECE0') + K.t(146, 118, '≈ 35 g de proteína', { s: 7.4, b: 1 }); },
      intro: 'Proteína y carbohidrato después de entrenar ayudan a reparar y construir músculo.',
      q: [['¿Cuándo se toma?', 'En las dos horas después de entrenar.'], ['¿Por qué lleva carbohidrato?', 'Repone el glucógeno gastado.'], ['¿Cuánta proteína se busca por toma?', 'Entre 20 y 40 g.']],
      porque: 'El músculo necesita aminoácidos para repararse y crece si recibe estímulo y proteína.' },
    { id: 'bt_hipertension', fam: 'rec', n: 'Objetivo: tensión arterial',
      d: function (K) { return vaso(K, 60, 44, 56, 80, '#8A1E4A') + tabla(K, 104, 36, [['Remolacha cocida', '¼'], ['Plátano', '1'], ['Espinaca', '30 g'], ['Kéfir o yogur', '150 ml'], ['Sin sal añadida', '']], 84) + K.r(104, 96, 84, 26, 2, '#F6E6EC') + K.t(146, 107, 'Rico en potasio y nitratos', { s: 6.4, b: 1 }) + K.t(146, 117, 'sin sodio añadido', { s: 6 }); },
      intro: 'Potasio, nitratos y calcio: nutrientes que ayudan a controlar la tensión, dentro de una dieta baja en sal.',
      q: [['¿Qué mineral ayuda a eliminar el sodio?', 'El potasio.'], ['¿Sustituye a la medicación?', 'No: complementa el tratamiento indicado por el médico.'], ['¿Qué ingrediente hay que evitar?', 'La sal y los caldos o bebidas con sodio.']],
      porque: 'Más potasio y menos sodio relajan los vasos y ayudan a bajar la tensión.' },
    { id: 'bt_diabetes', fam: 'rec', n: 'Objetivo: controlar la glucosa',
      d: function (K) { return vaso(K, 60, 44, 56, 80, '#B8A0C8') + tabla(K, 104, 36, [['Frutos rojos', '100 g'], ['Yogur griego', '125 g'], ['Linaza molida', '1 cda'], ['Canela', 'pizca'], ['Bebida sin azúcar', '150 ml']], 84) + K.r(104, 96, 84, 26, 2, '#F0EAF4') + K.t(146, 107, 'Fruta de índice glucémico bajo', { s: 6, b: 1 }) + K.t(146, 117, '+ proteína + fibra', { s: 6 }); },
      intro: 'Poca fruta dulce, mucha fibra y proteína: la glucosa sube despacio.',
      q: [['¿Qué frutas se evitan en exceso?', 'Plátano muy maduro, mango y uvas en cantidad.'], ['¿Por qué no se usa zumo?', 'Sube la glucosa muy rápido.'], ['¿A quién se consulta?', 'Al médico o nutricionista, que ajustan la dieta a cada persona.']],
      porque: 'Fibra, proteína y grasa enlentecen el paso del azúcar del intestino a la sangre.' },
    { id: 'bt_energia', fam: 'rec', n: 'Objetivo: antes de entrenar',
      d: function (K) { return vaso(K, 60, 44, 56, 80, C.amarillo) + tabla(K, 104, 36, [['Plátano', '1'], ['Dátil', '1'], ['Avena', '20 g'], ['Agua o bebida', '200 ml'], ['30-60 min antes', '']], 84); },
      intro: 'Carbohidrato fácil de digerir y poca grasa: energía sin pesadez.',
      q: [['¿Por qué poca grasa antes de entrenar?', 'La grasa hace más lenta la digestión.'], ['¿Cuánto antes se toma?', 'Entre 30 y 60 minutos.'], ['¿Qué fruta es la más usada?', 'El plátano.']],
      porque: 'El músculo usa glucosa como combustible rápido; el plátano la aporta de forma escalonada.' },
    { id: 'bt_digestion', fam: 'rec', n: 'Objetivo: buena digestión',
      d: function (K) { return vaso(K, 60, 44, 56, 80, '#F4B878') + tabla(K, 104, 36, [['Papaya', '150 g'], ['Kéfir', '150 ml'], ['Jengibre', '1 cm'], ['Menta', '6 hojas'], ['Avena', '1 cda']], 84); },
      intro: 'Fermentados, enzimas de fruta y fibra suave para cuidar el intestino.',
      q: [['¿Qué aporta el kéfir?', 'Bacterias vivas beneficiosas.'], ['¿Qué enzima tiene la papaya?', 'La papaína.'], ['¿Para qué el jengibre?', 'Ayuda con las náuseas y la pesadez.']],
      porque: 'Las bacterias del kéfir se alimentan de la fibra y mantienen sano el intestino.' },
    { id: 'bt_ninos', fam: 'rec', n: 'Batido para niños',
      d: function (K) { return vaso(K, 60, 44, 56, 80, C.rosa, { pc: '#4F8FC0' }) + tabla(K, 104, 36, [['Fresas', '80 g'], ['Plátano', '½'], ['Leche', '150 ml'], ['Avena', '1 cda'], ['Sin azúcar añadido', '']], 84) + K.t(146, 110, 'Vaso pequeño: 150-200 ml', { s: 6.4, b: 1 }); },
      intro: 'Fruta dulce y leche, sin azúcar añadido y en ración pequeña.',
      q: [['¿Por qué ración pequeña?', 'Los niños necesitan menos cantidad y no debe quitar el apetito.'], ['¿Qué ingredientes se evitan?', 'Azúcar, miel en menores de un año, café y frutos secos enteros.'], ['¿Cómo participan los niños?', 'Eligiendo la fruta y echándola en el vaso.']],
      porque: 'Acostumbrarse al dulzor de la fruta sin azúcar forma buenos hábitos desde pequeños.' }
  ];
  MO.agregar('batidos', L, { materias: /^(batidos|cocina)$/ });
})();
