/* b6_lib_ingles2.js — Inglés (2/3): cuerpo, sentimientos y rutinas, tiempos verbales y estructura de la oración. 33 modelos.
   Cargar después de b6_lib_ingles.js. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('in_body')) return;
  var P = { papel: '#FBF7EE', azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', madera: '#B8946A' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { cue: 'Cuerpo, sentimientos y rutinas', tie: 'Tiempos verbales', est: 'Estructura de la oración' };
  function persona(K, x, y, col) { return K.c(x, y, 7, P.piel, { w: .8 }) + K.p('M' + (x - 11) + ' ' + (y + 30) + ' Q' + (x - 11) + ' ' + (y + 10) + ' ' + x + ' ' + (y + 10) + ' Q' + (x + 11) + ' ' + (y + 10) + ' ' + (x + 11) + ' ' + (y + 30) + ' Z', col, { w: .8 }); }
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .58)) : 0; if (q[1]) { var k = Math.min(1, (h - 3) / (f1 + f2 + 1.6)); f1 *= k; f2 *= k; } var b1 = q[1] ? y + (h - f1 - f2 - 1.6) / 2 + f1 * .8 : y + h / 2 + f1 * .35, b2 = b1 + f1 * .2 + 1.6 + f2 * .8; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, +b1.toFixed(2), q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, +b2.toFixed(2), q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + (o && o.tit ? K.t(100, 14, o.tit, { s: 7, b: 1 }) : '') + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: +Math.min(6, 180 / (pie.length * .58)).toFixed(2), b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  /* línea del tiempo: pasado · ahora · futuro, con marcas */
  function eje(K, y, marcas) { var s = K.flecha(14, y, 188, y, P.tinta, { w: 1.2 }) + K.l('M100 ' + (y - 8) + ' L100 ' + (y + 8), P.rojoO, { w: 1.4 }) + K.t(100, y + 17, 'now', { s: 6, b: 1, c: P.rojoO }) + K.t(30, y + 17, 'past', { s: 5.6 }) + K.t(172, y + 17, 'future', { s: 5.6 }); (marcas || []).forEach(function (m) { s += m.tramo ? K.r(m.x, y - 4, m.w, 8, 3, m.c || P.azul, { w: .6 }) : K.c(m.x, y, 4.4, m.c || P.azulO, { w: .6 }); }); return s; }
  /* fórmula en piezas de color */
  function formula(K, piezas, y, o) { o = o || {}; var k = o.k || 4.3, fs = o.s || 7, g = 3, n = piezas.length, fijo = n * 12 + g * (n - 1), tot = piezas.reduce(function (a, q) { return a + q[0].length * k; }, 0) + fijo; if (tot > 178) { var f = (178 - fijo) / (tot - fijo); k *= f; fs *= f; tot = 178; } var x = 100 - tot / 2, s = ''; piezas.forEach(function (q) { var w = q[0].length * k + 12; s += K.r(x, y, w, 18, 3, q[1], { w: .8 }) + K.t(x + w / 2, y + 12.5, q[0], { s: +fs.toFixed(2), b: 1 }); x += w + g; }); return s; }

  var L = [
    /* ─────────── CUERPO, SENTIMIENTOS Y RUTINAS ─────────── */
    { id: 'in_body', fam: 'cue', n: 'The body · El cuerpo',
      d: function (K) { return K.suelo(100, 140, 60) + K.c(100, 26, 13, P.piel, { w: 1 }) + K.r(96, 38, 8, 6, 1, P.piel, { w: .8 }) + K.p('M80 44 L120 44 L118 92 L82 92 Z', P.azul, { w: 1 }) + K.p('M80 46 L66 84 L72 86 L84 58 Z', P.piel, { w: .8 }) + K.p('M120 46 L134 84 L128 86 L116 58 Z', P.piel, { w: .8 }) + K.p('M84 92 L98 92 L96 134 L86 134 Z', '#5A6A8A', { w: .8 }) + K.p('M102 92 L116 92 L114 134 L104 134 Z', '#5A6A8A', { w: .8 }) + K.e(91, 136, 8, 3, P.tinta) + K.e(109, 136, 8, 3, P.tinta); },
      rot: [['head · cabeza', 100, 20, 30, 16], ['neck · cuello', 100, 41, 30, 36], ['arm · brazo', 70, 70, 26, 62], ['hand · mano', 69, 86, 26, 92], ['chest · pecho', 104, 58, 170, 44], ['leg · pierna', 112, 112, 170, 112], ['foot · pie', 110, 136, 170, 136]],
      intro: 'Las partes principales del cuerpo en inglés.',
      q: [['¿Cuál es el plural de «foot»?', '«Feet».'], ['Touch your head. / ¿Qué tocas?', 'La cabeza.'], ['¿Cómo se dice «rodilla»?', '«Knee», con la k muda.']],
      porque: 'Las órdenes con partes del cuerpo («touch your nose») se aprenden jugando.' },
    { id: 'in_face', fam: 'cue', n: 'The face · La cara',
      d: function (K) { return K.suelo(100, 140, 60) + K.p('M64 40 Q64 14 100 14 Q136 14 136 40 L136 30 Q120 22 100 24 Q80 22 64 30 Z', '#6A4A30', { w: .8 }) + K.e(100, 70, 36, 46, P.piel, { w: 1.2 }) + K.e(62, 70, 5, 9, P.piel, { w: .8 }) + K.e(138, 70, 5, 9, P.piel, { w: .8 }) + K.e(86, 62, 7, 4.4, P.blanco, { w: .8 }) + K.c(86, 62, 2.6, '#4A6A3A') + K.e(114, 62, 7, 4.4, P.blanco, { w: .8 }) + K.c(114, 62, 2.6, '#4A6A3A') + K.l('M78 52 Q86 48 94 52 M106 52 Q114 48 122 52', '#6A4A30', { w: 1.4 }) + K.l('M100 66 L96 84 L104 84', P.tinta, { w: .8 }) + K.p('M86 96 Q100 106 114 96 Q100 100 86 96 Z', '#C8505A', { w: .8 }); },
      rot: [['hair · pelo', 100, 20, 150, 14], ['eye · ojo', 86, 62, 30, 50], ['eyebrow · ceja', 114, 50, 170, 40], ['nose · nariz', 100, 80, 170, 80], ['mouth · boca', 100, 99, 40, 112], ['ear · oreja', 62, 70, 24, 80]],
      intro: 'Las partes de la cara para describir a alguien.',
      q: [['¿Cómo se dice «ojos verdes»?', '«Green eyes».'], ['¿«Hair» tiene plural?', 'No, cuando es el pelo de la cabeza: «long hair».'], ['What colour are your eyes?', 'Respuesta libre: my eyes are brown.']],
      porque: '«Hair» es incontable: se dice «my hair is», no «my hairs are».' },
    G('in_health', 'cue', 'Health problems · Dolencias', [['I’ve got a headache', 'me duele la cabeza', P.rojo], ['a stomachache', 'dolor de estómago', P.naranja], ['a toothache', 'dolor de muelas', P.amarillo], ['a cold', 'un resfriado', P.azul], ['a cough', 'tos', P.verde], ['a temperature', 'fiebre', P.rosa]], 2, 16, 30, 'You should see a doctor = deberías ir al médico', 'Cómo decir qué te duele y dar un consejo con «should».', [['¿Cómo se dice «me duele la garganta»?', '«I’ve got a sore throat».'], ['¿Qué significa «You should rest»?', 'Deberías descansar.'], ['What’s the matter? / ¿Qué pregunta?', '¿Qué te pasa?']], 'Con «-ache» se forma el dolor de casi cualquier parte: back + ache = backache.', { s: 7, s2: 5.4 }),
    { id: 'in_feelings', fam: 'cue', n: 'Feelings · Sentimientos',
      d: function (K) { var F = [['happy', 'feliz', [-7, 4, 0, 12, 7, 4], P.amarillo], ['sad', 'triste', [-7, 9, 0, 1, 7, 9], P.azul], ['angry', 'enfadado', [-6, 7, 0, 5, 6, 7], P.rojo], ['scared', 'asustado', 'o', P.morado], ['tired', 'cansado', [-5, 7, 0, 7, 5, 7], P.gris], ['surprised', 'sorprendido', 'O', P.naranja]], s = K.suelo(100, 140, 96); F.forEach(function (q, i) { var x = 34 + (i % 3) * 66, y = 38 + Math.floor(i / 3) * 52, m = q[2]; s += K.c(x, y, 16, q[3], { w: 1 }) + K.c(x - 6, y - 4, 1.8, P.tinta) + K.c(x + 6, y - 4, 1.8, P.tinta) + (typeof m === 'string' ? K.e(x, y + 7, m === 'O' ? 4 : 3, m === 'O' ? 5 : 2.4, P.tinta) : K.l('M' + (x + m[0]) + ' ' + (y + m[1]) + ' Q' + (x + m[2]) + ' ' + (y + m[3]) + ' ' + (x + m[4]) + ' ' + (y + m[5]), P.tinta, { w: 1.2 })) + (i === 2 ? K.l('M' + (x - 9) + ' ' + (y - 10) + ' l6 3 M' + (x + 9) + ' ' + (y - 10) + ' l-6 3', P.tinta, { w: 1 }) : '') + K.t(x, y + 26, q[0], { s: 7, b: 1 }) + K.t(x, y + 33, q[1], { s: 5 }); }); return s; },
      intro: 'Seis emociones básicas para decir cómo te sientes.',
      q: [['How do you feel? / ¿Qué pregunta?', '¿Cómo te sientes?'], ['¿Cómo se dice «estoy cansado»?', '«I’m tired».'], ['¿«Bored» o «boring» para decir que te aburres?', '«I’m bored»; «boring» describe lo que aburre.']],
      porque: 'Los adjetivos en -ed dicen cómo te sientes; los terminados en -ing, qué lo provoca.' },
    { id: 'in_routine', fam: 'cue', n: 'Daily routine · La rutina diaria',
      d: function (K) { var R = [['7:00', 'get up', 'levantarse'], ['7:30', 'have breakfast', 'desayunar'], ['8:00', 'go to school', 'ir al colegio'], ['14:00', 'have lunch', 'almorzar'], ['17:00', 'do homework', 'hacer deberes'], ['22:00', 'go to bed', 'acostarse']], s = K.suelo(100, 140, 96) + K.l('M30 18 L30 126', P.tinta, { w: 1.2 }); R.forEach(function (q, i) { var y = 22 + i * 19; s += K.c(30, y, 4, CO[i], { w: .8 }) + K.t(24, y + 2.4, q[0], { s: 5.6, b: 1, a: 'end' }) + K.r(40, y - 7, 148, 14, 3, CO[i], { w: .6 }) + K.t(46, y + 2.4, q[1], { s: 6.8, b: 1, a: 'start' }) + K.t(182, y + 2.4, q[2], { s: 5.4, a: 'end' }); }); return s + K.t(100, 140, 'I get up at seven · She gets up at seven', { s: 6, b: 1 }); },
      intro: 'Un día ordenado por horas, con los verbos de rutina más usados.',
      q: [['What time do you get up?', 'Respuesta libre: I get up at seven.'], ['¿Qué preposición va con la hora?', '«At»: at seven o’clock.'], ['Completa: He ___ (go) to bed at ten.', '«Goes».']],
      porque: 'Las rutinas se cuentan en presente simple porque se repiten cada día.' },
    { id: 'in_frequency', fam: 'cue', n: 'Adverbs of frequency · Frecuencia',
      d: function (K) { var A = [['always', 100, 'siempre'], ['usually', 80, 'normalmente'], ['often', 60, 'a menudo'], ['sometimes', 40, 'a veces'], ['rarely', 15, 'rara vez'], ['never', 0, 'nunca']], s = K.suelo(100, 140, 96); A.forEach(function (q, i) { var y = 16 + i * 17; s += K.t(52, y + 9, q[0], { s: 6.6, b: 1, a: 'end' }) + K.r(56, y, 80, 12, 2, P.gris, { w: .4 }) + K.r(56, y, Math.max(q[1] * .8, .1), 12, 2, P.verde, { w: .6 }) + K.t(139, y + 9, q[1] + ' %', { s: 5.6, a: 'start' }) + K.t(190, y + 9, q[2], { s: 4.8, a: 'end' }); }); return s + K.t(100, 124, 'Antes del verbo: I always walk', { s: 6.4, b: 1 }) + K.t(100, 136, 'Después de «be»: She is never late', { s: 6.2 }); },
      intro: 'Los adverbios de frecuencia indican cuántas veces pasa algo; los porcentajes son orientativos.',
      q: [['¿Dónde va «often» en «I go to the cinema»?', '«I often go to the cinema».'], ['Completa: He is ___ late (nunca).', '«Never».'], ['How often do you read?', 'Respuesta libre: I sometimes read at night.']],
      porque: 'Estos adverbios van delante del verbo principal, pero detrás de «be».' },
    G('in_hobbies', 'cue', 'Free time · Tiempo libre', [['play football', 'jugar al fútbol'], ['play the guitar', 'tocar la guitarra'], ['read books', 'leer libros'], ['watch TV', 'ver la tele'], ['go swimming', 'ir a nadar'], ['ride a bike', 'montar en bici'], ['draw', 'dibujar'], ['listen to music', 'escuchar música']], 2, 14, 22, '«play the» con instrumentos · «play» sin artículo con deportes', 'Actividades de ocio con el verbo que las acompaña.', [['¿Se dice «play the football»?', 'No: «play football».'], ['¿Y «play piano»?', 'Lo correcto es «play the piano».'], ['What do you do in your free time?', 'Respuesta libre: I play the guitar.']], 'Cada actividad pide su verbo: play, go o do; no se traduce palabra por palabra.', { s: 7.6, s2: 5.4 }),
    G('in_can', 'cue', 'Can for ability · Saber, poder', [['I can swim.', 'sé nadar', P.verde], ['I can’t drive.', 'no sé conducir', P.rojo], ['Can you cook?', '¿sabes cocinar?', P.azul], ['Yes, I can. / No, I can’t.', 'respuestas cortas', P.amarillo]], 1, 20, 22, '«can» no cambia: he can, she can · sin «to»', '«Can» expresa capacidad y es igual para todas las personas.', [['¿Se dice «he cans»?', 'No: «he can».'], ['¿Se dice «I can to swim»?', 'No: «I can swim», sin «to».'], ['Can you speak English?', 'Respuesta libre: yes, a little.']], '«Can» es un verbo modal: no lleva -s ni «to» y forma la pregunta invirtiendo el orden.', { s: 8, s2: 5.4 }),
    G('in_like_ing', 'cue', 'Like, love, hate + -ing · Gustos', [['I love dancing.', 'me encanta ♥♥', P.rosa], ['I like reading.', 'me gusta ♥', P.verde], ['I don’t mind cooking.', 'no me importa', P.amarillo], ['I don’t like running.', 'no me gusta', P.naranja], ['I hate waiting.', 'odio', P.rojo]], 1, 14, 18, 'Tras estos verbos, el otro verbo va en -ing', 'Cómo expresar gustos del más al menos, con el verbo en -ing.', [['Completa: She likes ___ (swim).', '«Swimming».'], ['¿Qué significa «I don’t mind»?', 'No me importa.'], ['What do you hate doing?', 'Respuesta libre: I hate getting up early.']], 'En inglés «me gusta» se dice con la persona como sujeto: I like.', { s: 8, s2: 5.4 }),
    { id: 'in_weather', fam: 'cue', n: 'The weather · El tiempo',
      d: function (K) { var s = K.suelo(100, 140, 96), W = [['sunny', 'soleado'], ['cloudy', 'nublado'], ['rainy', 'lluvioso'], ['snowy', 'nevado'], ['windy', 'ventoso'], ['stormy', 'tormenta']]; W.forEach(function (q, i) { var x = 34 + (i % 3) * 66, y = 34 + Math.floor(i / 3) * 54; if (i === 0) s += K.c(x, y, 10, '#F4C83C', { w: .8 }) + K.l('M' + (x - 16) + ' ' + y + ' l5 0 M' + (x + 11) + ' ' + y + ' l5 0 M' + x + ' ' + (y - 16) + ' l0 5 M' + x + ' ' + (y + 11) + ' l0 5', '#C89A20', { w: 1.2 }); else { s += K.e(x, y, 16, 9, i === 5 ? '#8A8A9A' : '#D8DCE4', { w: .8 }); if (i === 2) s += K.l('M' + (x - 8) + ' ' + (y + 12) + ' l-3 6 M' + x + ' ' + (y + 12) + ' l-3 6 M' + (x + 8) + ' ' + (y + 12) + ' l-3 6', P.azulO, { w: 1 }); if (i === 3) s += K.c(x - 8, y + 15, 2, P.blanco, { w: .6 }) + K.c(x, y + 17, 2, P.blanco, { w: .6 }) + K.c(x + 8, y + 15, 2, P.blanco, { w: .6 }); if (i === 4) s += K.l('M' + (x - 20) + ' ' + (y + 14) + ' q10 -4 20 0 t20 0', P.azulO, { w: 1 }); if (i === 5) s += K.p('M' + x + ' ' + (y + 6) + ' l-5 9 l4 0 l-3 8 l8 -11 l-4 0 l3 -6 Z', '#F4C83C', { w: .6 }); } s += K.t(x, y + 30, q[0], { s: 7, b: 1 }) + K.t(x, y + 37, q[1], { s: 5 }); }); return s; },
      intro: 'El tiempo atmosférico se describe con «It’s» y un adjetivo terminado en -y.',
      q: [['What’s the weather like today?', 'Respuesta libre: It’s sunny.'], ['¿Cómo se forma «cloudy»?', 'Cloud (nube) + y.'], ['¿Cómo se dice «hace frío»?', '«It’s cold».']],
      porque: 'Muchos adjetivos del tiempo se forman añadiendo -y al nombre: sun → sunny.' },
    G('in_jobs', 'cue', 'Jobs · Profesiones', [['teacher', 'docente'], ['doctor', 'médico/a'], ['nurse', 'enfermero/a'], ['cook', 'cocinero/a'], ['farmer', 'agricultor/a'], ['driver', 'conductor/a'], ['engineer', 'ingeniero/a'], ['hairdresser', 'peluquero/a'], ['police officer', 'policía'], ['shop assistant', 'dependiente'], ['firefighter', 'bombero/a'], ['vet', 'veterinario/a']], 3, 14, 20, 'She is a nurse: «a» delante de la profesión', 'Doce profesiones; en inglés casi todas valen para hombre y mujer.', [['¿Se dice «She is nurse»?', 'No: «She is a nurse».'], ['¿Cómo se dice «cocinero»?', '«Cook»; «cooker» es la cocina, el aparato.'], ['What do you want to be?', 'Respuesta libre: I want to be a vet.']], 'El artículo «a» es obligatorio con las profesiones, aunque en español no se ponga.', { s: 7.6, s2: 5.2, gy: 3 }),
    G('in_personality', 'cue', 'Personality · La personalidad', [['friendly', 'simpático'], ['shy', 'tímido'], ['funny', 'gracioso'], ['kind', 'amable'], ['lazy', 'vago'], ['hard-working', 'trabajador'], ['honest', 'sincero'], ['brave', 'valiente'], ['clever', 'listo'], ['patient', 'paciente'], ['generous', 'generoso'], ['polite', 'educado']], 4, 14, 24, '«sympathetic» no es simpático: es compasivo', 'Adjetivos para describir el carácter.', [['¿Cómo se dice «simpático»?', '«Friendly» o «nice».'], ['What is the opposite of «lazy»?', '«Hard-working».'], ['¿«Educated» es educado?', 'No: significa con estudios. Educado es «polite».']], 'Algunas palabras parecidas al español cambian de significado: son falsos amigos.', { s: 7.6, s2: 5.2 }),
    { id: 'in_describe', fam: 'cue', n: 'Describing people · Describir personas',
      d: function (K) { var s = K.suelo(100, 140, 96); s += K.c(50, 36, 10, P.piel, { w: .8 }) + K.p('M40 34 Q40 22 50 22 Q60 22 60 34 L60 60 L56 60 L56 34 L44 34 L44 60 L40 60 Z', '#C89A40', { w: .8 }) + K.p('M38 48 L62 48 L64 100 L36 100 Z', P.rosa, { w: .8 }) + K.l('M44 100 L44 128 M56 100 L56 128', P.tinta, { w: 2 }); s += K.c(146, 50, 10, '#B88A68', { w: .8 }) + K.p('M136 46 Q136 38 146 38 Q156 38 156 46 Q150 42 146 42 Q142 42 136 46 Z', P.tinta, { w: .6 }) + K.p('M132 62 L160 62 L162 104 L130 104 Z', P.verde, { w: .8 }) + K.l('M140 104 L140 128 M152 104 L152 128', P.tinta, { w: 2 }); return s + K.t(50, 18, 'She is tall.', { s: 6.4, b: 1 }) + K.t(50, 140, 'long blonde hair', { s: 6 }) + K.t(146, 30, 'He is short.', { s: 6.4, b: 1 }) + K.t(146, 140, 'short dark hair', { s: 6 }) + K.t(100, 74, 'Orden:', { s: 5.6, b: 1 }) + K.t(100, 84, 'largo → color', { s: 5.6 }) + K.t(100, 94, '→ hair', { s: 5.6 }); },
      intro: 'Para describir a alguien se usa «be» para la altura y «have got» para el pelo y los ojos.',
      q: [['¿Se dice «blonde long hair»?', 'No: «long blonde hair»; primero la longitud.'], ['What does your best friend look like?', 'Respuesta libre: She is tall and has got curly hair.'], ['¿Qué pregunta «What is he like?»?', 'Cómo es de carácter.']],
      porque: '«What does he look like?» pregunta por el aspecto; «What is he like?», por la personalidad.' },
    { id: 'in_have_got', fam: 'cue', n: 'Have got · Tener',
      d: function (K) { return K.suelo(100, 140, 96) + formula(K, [['I / you / we / they', P.azul], ['have got', P.verde]], 18) + formula(K, [['he / she / it', P.naranja], ['has got', P.verde]], 42) + formula(K, [['I', P.azul], ['haven’t got', P.rojo], ['a car', P.gris]], 70) + formula(K, [['Has', P.verde], ['she', P.naranja], ['got', P.verde], ['a dog?', P.gris]], 96) + K.t(100, 134, 'Más británico; en EE. UU. se dice «I have»', { s: 6, b: 1 }); },
      intro: '«Have got» expresa posesión; la tercera persona usa «has».',
      q: [['Completa: He ___ got two sisters.', '«Has».'], ['¿Cómo se forma la negativa?', 'Con «haven’t got» o «hasn’t got».'], ['Have you got a pet?', 'Yes, I have / No, I haven’t.']],
      porque: 'En la pregunta «have» pasa delante del sujeto y «got» se queda detrás.' },
    G('in_imperatives', 'cue', 'Classroom instructions · Órdenes en clase', [['Open your books.', 'abrid los libros'], ['Close the door.', 'cierra la puerta'], ['Sit down.', 'siéntate'], ['Stand up.', 'levántate'], ['Listen.', 'escucha'], ['Don’t run.', 'no corras'], ['Be quiet.', 'silencio'], ['Work in pairs.', 'en parejas']], 2, 14, 22, 'Imperativo = verbo sin sujeto · negativo: Don’t + verbo', 'El imperativo da órdenes con el verbo sin sujeto.', [['¿Cómo se dice «no hables»?', '«Don’t talk».'], ['¿Cambia el imperativo en plural?', 'No: «Sit down» vale para uno o para todos.'], ['¿Cómo suena más amable?', 'Añadiendo «please»: Open the window, please.']], 'El imperativo es igual para tú y vosotros, por eso se suaviza con «please».', { s: 7.6, s2: 5.4 }),
    /* ─────────── TIEMPOS VERBALES ─────────── */
    G('in_to_be', 'tie', 'Verb «to be» · Ser y estar', [['I am', 'I’m', P.azul], ['you are', 'you’re', P.verde], ['he / she / it is', 'he’s, she’s, it’s', P.naranja], ['we are', 'we’re', P.verde], ['they are', 'they’re', P.verde], ['I’m not · isn’t · aren’t', 'negativa', P.rojo]], 2, 18, 26, 'Pregunta: Are you ready? · Is she here?', '«To be» significa ser y estar a la vez.', [['Completa: They ___ from Mexico.', '«Are».'], ['¿Cómo se forma la pregunta?', 'Poniendo el verbo delante: Is he a teacher?'], ['¿Cómo se dice «tengo 12 años»?', '«I am twelve»: en inglés la edad va con «be».']], 'El inglés usa un solo verbo donde el español distingue entre ser y estar.', { s: 7.6, s2: 5.4 }),
    { id: 'in_present_simple', fam: 'tie', n: 'Present simple · Presente simple',
      d: function (K) { return K.suelo(100, 140, 96) + eje(K, 30, [{ x: 40 }, { x: 70 }, { x: 100 }, { x: 130 }, { x: 160 }]) + K.t(100, 14, 'every day', { s: 6.4, b: 1 }) + formula(K, [['I', P.azul], ['play', P.verde], ['tennis.', P.gris]], 58) + formula(K, [['I', P.azul], ['don’t', P.rojo], ['play', P.verde], ['tennis.', P.gris]], 82) + formula(K, [['Do', P.amarillo], ['you', P.azul], ['play', P.verde], ['tennis?', P.gris]], 106) + K.t(100, 140, 'Hábitos, rutinas y verdades generales', { s: 6, b: 1 }); },
      intro: 'El presente simple habla de lo que se repite o es siempre verdad.',
      q: [['¿Para qué se usa?', 'Para hábitos, rutinas y hechos.'], ['¿Cómo se forma la negativa?', 'Con «don’t» o «doesn’t» delante del verbo.'], ['Completa: Water ___ (boil) at 100 °C.', '«Boils».']],
      porque: 'Los puntos repartidos por todo el eje indican que la acción se repite.' },
    G('in_third_s', 'tie', 'Third person «-s» · La tercera persona', [['play → plays', '+ s', P.verde], ['watch → watches', '+ es tras ch, sh, s, x, o', P.naranja], ['study → studies', 'consonante + y → ies', P.azul], ['have → has', 'irregular', P.rosa], ['go → goes · do → does', '+ es', P.amarillo], ['He doesn’t play.', 'negativa: el verbo pierde la -s', P.rojo]], 1, 14, 16, 'he, she, it: solo aquí cambia el verbo', 'En presente simple, con he, she e it el verbo añade -s.', [['Completa: She ___ (watch) TV.', '«Watches».'], ['¿Por qué «He doesn’t plays» está mal?', 'La -s ya está en «does»; el verbo va sin -s.'], ['Completa: A bird ___ (fly).', '«Flies».']], 'La -s solo aparece una vez: en el verbo o en el auxiliar «does».', { s: 7.4, s2: 5.2, gy: 3 }),
    { id: 'in_present_cont', fam: 'tie', n: 'Present continuous · Presente continuo',
      d: function (K) { return K.suelo(100, 140, 96) + eje(K, 30, [{ tramo: 1, x: 84, w: 32, c: P.verde }]) + K.t(100, 14, 'right now', { s: 6.4, b: 1 }) + formula(K, [['I', P.azul], ['am', P.amarillo], ['reading', P.verde]], 58) + formula(K, [['She', P.naranja], ['is', P.amarillo], ['not', P.rojo], ['sleeping', P.verde]], 82) + formula(K, [['Are', P.amarillo], ['they', P.azul], ['playing?', P.verde]], 106) + K.t(100, 140, 'be + verbo-ing: acción en curso', { s: 6, b: 1 }); },
      intro: 'El presente continuo describe lo que está pasando ahora mismo.',
      q: [['Completa: Look! It ___ (rain).', '«Is raining».'], ['¿Cómo se escribe «run» + ing?', '«Running»: se dobla la n.'], ['What are you doing now?', 'Respuesta libre: I’m studying English.']],
      porque: 'El tramo alrededor de «now» indica una acción que empezó y aún no ha terminado.' },
    G('in_simple_cont', 'tie', 'Simple or continuous? · ¿Simple o continuo?', [['every day · usually · never', 'present simple', P.azul], ['now · at the moment · Look!', 'present continuous', P.verde], ['I work in a bank.', 'trabajo (siempre)', P.azul], ['I’m working from home today.', 'hoy, temporal', P.verde], ['I like coffee.', 'like, know, want: sin -ing', P.amarillo]], 1, 16, 18, 'Las palabras de tiempo ayudan a elegir', 'El simple habla de hábitos; el continuo, de lo que ocurre ahora o es temporal.', [['Completa: I usually ___ (walk), but today I ___ (take) the bus.', '«Walk» / «am taking».'], ['¿Se dice «I am knowing»?', 'No: «know» no se usa en continuo.'], ['¿Qué palabra pide continuo: «now» o «often»?', '«Now».']], 'Los verbos de estado (like, know, want) casi nunca van en -ing.', { s: 7.4, s2: 5.4, gy: 4 }),
    G('in_past_be', 'tie', 'Past of «be» · Was y were', [['I / he / she / it was', 'era, estaba', P.naranja], ['you / we / they were', 'eras, estábamos…', P.azul], ['I wasn’t at home.', 'negativa', P.rojo], ['Were you tired?', 'pregunta', P.verde]], 1, 22, 22, 'yesterday · last week · in 2010', '«Be» en pasado tiene dos formas: was y were.', [['Completa: We ___ at the beach yesterday.', '«Were».'], ['Completa: She ___ happy.', '«Was».'], ['Where were you last night?', 'Respuesta libre: I was at home.']], 'Es el único verbo inglés con dos formas en pasado según la persona.', { s: 7.6, s2: 5.4 }),
    { id: 'in_past_simple', fam: 'tie', n: 'Past simple · Pasado simple',
      d: function (K) { return K.suelo(100, 140, 96) + eje(K, 30, [{ x: 44, c: P.rojoO }]) + K.t(44, 14, 'yesterday', { s: 6.4, b: 1 }) + formula(K, [['I', P.azul], ['played', P.verde], ['football.', P.gris]], 58) + formula(K, [['I', P.azul], ['didn’t', P.rojo], ['play', P.verde], ['football.', P.gris]], 82) + formula(K, [['Did', P.amarillo], ['you', P.azul], ['play', P.verde], ['football?', P.gris]], 106) + K.t(100, 140, 'Con «did» el verbo vuelve a su forma base', { s: 6, b: 1 }); },
      intro: 'El pasado simple cuenta acciones terminadas en un momento concreto del pasado.',
      q: [['Completa: She ___ (watch) a film last night.', '«Watched».'], ['¿Se dice «Did you played?»?', 'No: «Did you play?».'], ['What did you do yesterday?', 'Respuesta libre: I visited my grandmother.']],
      porque: 'El auxiliar «did» ya marca el pasado, así que el verbo no lo repite.' },
    { id: 'in_past_cont', fam: 'tie', n: 'Past continuous · Pasado continuo',
      d: function (K) { return K.suelo(100, 140, 96) + eje(K, 34, [{ tramo: 1, x: 24, w: 52, c: P.azul }, { x: 54, c: P.rojoO }]) + K.t(50, 16, 'I was reading…', { s: 6.4, b: 1, c: P.azulO }) + K.t(78, 26, '…when the phone rang', { s: 5.6, b: 1, c: P.rojoO, a: 'start' }) + formula(K, [['was / were', P.amarillo], ['+ verb-ing', P.verde]], 66) + K.t(100, 100, 'Acción larga interrumpida por otra corta', { s: 6.4, b: 1 }) + K.t(100, 114, 'while = mientras · when = cuando', { s: 6 }); },
      intro: 'El pasado continuo describe una acción en curso en el pasado, a menudo interrumpida.',
      q: [['Completa: They ___ (sleep) when I arrived.', '«Were sleeping».'], ['¿Qué tiempo lleva la acción corta?', 'El pasado simple.'], ['What were you doing at 8 pm yesterday?', 'Respuesta libre: I was having dinner.']],
      porque: 'El tramo azul es la acción de fondo; el punto rojo, el hecho que la corta.' },
    { id: 'in_present_perfect', fam: 'tie', n: 'Present perfect · Pretérito perfecto',
      d: function (K) { return K.suelo(100, 140, 96) + eje(K, 34, [{ tramo: 1, x: 40, w: 60, c: P.morado }]) + K.t(70, 18, 'I have lived here since 2020', { s: 6, b: 1 }) + formula(K, [['have / has', P.amarillo], ['+ participio', P.verde]], 64) + K.t(100, 96, 'ever · never · already · yet · since · for', { s: 6.6, b: 1 }) + K.t(100, 110, 'Have you ever been to London?', { s: 6.4 }) + K.t(100, 122, 'No dice cuándo: con «yesterday» va el pasado simple', { s: 5.6 }); },
      intro: 'El present perfect une el pasado con el presente: experiencias o acciones que siguen.',
      q: [['¿«for» o «since» con «three years»?', '«For»: indica duración.'], ['¿Se dice «I have seen it yesterday»?', 'No: «I saw it yesterday».'], ['Have you ever eaten sushi?', 'Yes, I have / No, I haven’t.']],
      porque: 'El tramo que llega hasta «now» muestra que la acción tiene relación con el presente.' },
    G('in_going_to', 'tie', 'Going to · Planes', [['I’m going to visit Rome.', 'plan decidido', P.verde], ['She isn’t going to come.', 'negativa', P.rojo], ['Are you going to study?', 'pregunta', P.azul], ['Look at the clouds! It’s going to rain.', 'predicción con pruebas', P.gris]], 1, 20, 22, 'be + going to + verbo', '«Going to» expresa planes ya decididos y predicciones con señales visibles.', [['Completa: We ___ (travel) next summer.', '«Are going to travel».'], ['¿Por qué «It’s going to rain»?', 'Porque se ven las nubes: hay una prueba.'], ['What are you going to do this weekend?', 'Respuesta libre.']], 'Se usa cuando la decisión ya está tomada antes de hablar.', { s: 7.4, s2: 5.4 }),
    G('in_will', 'tie', 'Will · Futuro', [['I think it will be sunny.', 'opinión sobre el futuro', P.amarillo], ['I’ll help you!', 'decisión en el momento', P.verde], ['I won’t tell anyone.', 'promesa · won’t = will not', P.rojo], ['Will you marry me?', 'pregunta', P.rosa]], 1, 20, 22, 'will + verbo base, igual para todas las personas', '«Will» se usa para opiniones, promesas y decisiones tomadas al momento.', [['¿Qué significa «won’t»?', '«Will not».'], ['The phone is ringing. — I ___ answer it.', '«’ll»: decisión inmediata.'], ['¿Lleva -s con «he»?', 'No: «he will go».']], '«Will» decide en el instante; «going to» anuncia lo que ya estaba planeado.', { s: 7.4, s2: 5.4 }),
    { id: 'in_tenses_map', fam: 'tie', n: 'Tense map · Mapa de tiempos',
      d: function (K) { var s = K.suelo(100, 140, 96) + eje(K, 72, []); [[30, 'past simple', 'I played', P.azul, 30], [60, 'past cont.', 'I was playing', P.morado, 44], [88, 'present perfect', 'I have played', P.rosa, 30], [112, 'present', 'I play', P.verde, 44], [140, 'going to', 'I’m going to play', P.amarillo, 30], [170, 'will', 'I will play', P.naranja, 44]].forEach(function (q) { var arriba = q[4] === 30, y = arriba ? 18 : 98; s += K.l('M' + q[0] + ' ' + (arriba ? 46 : 80) + ' L' + q[0] + ' ' + (arriba ? 64 : 98), P.tinta, { w: .6 }) + K.c(q[0], 72, 3.6, q[3], { w: .6 }) + K.r(q[0] - 26, y, 52, 28, 3, q[3], { w: .6 }) + K.t(q[0], y + 11, q[1], { s: 5.6, b: 1 }) + K.t(q[0], y + 21, q[2], { s: 5 }); }); return s; },
      intro: 'Los tiempos estudiados, colocados en una sola línea del tiempo.',
      q: [['¿Qué tiempo une pasado y presente?', 'El present perfect.'], ['¿Cuáles hablan del futuro?', '«Going to» y «will».'], ['Ordena: I will play, I played, I play.', 'I played → I play → I will play.']],
      porque: 'Ver todos los tiempos en un mismo eje ayuda a elegir el adecuado.' },
    /* ─────────── ESTRUCTURA DE LA ORACIÓN ─────────── */
    { id: 'in_svo', fam: 'est', n: 'Subject, verb, object · Orden de la oración',
      d: function (K) { return K.suelo(100, 140, 96) + formula(K, [['Subject', P.azul], ['Verb', P.verde], ['Object', P.naranja], ['Place', P.morado], ['Time', P.amarillo]], 20, { s: 6.4, k: 4 }) + formula(K, [['Tom', P.azul], ['plays', P.verde], ['football', P.naranja], ['in the park', P.morado], ['on Sundays.', P.amarillo]], 50, { s: 6.4, k: 4 }) + K.t(100, 92, 'El sujeto es obligatorio: «It is late», no «Is late»', { s: 6, b: 1 }) + K.t(100, 108, 'El orden es fijo: cambiarlo cambia el sentido', { s: 6 }) + K.t(100, 122, 'The dog bit the man ≠ The man bit the dog', { s: 6.2, b: 1, c: P.rojoO }); },
      intro: 'La oración inglesa sigue un orden casi fijo: sujeto, verbo, objeto, lugar y tiempo.',
      q: [['Ordena: every day / I / English / study.', 'I study English every day.'], ['¿Se puede decir «Is raining»?', 'No: «It is raining»; el sujeto no se omite.'], ['¿Qué va antes, lugar o tiempo?', 'El lugar: at school on Monday.']],
      porque: 'Como el verbo inglés casi no cambia, el orden de las palabras indica quién hace qué.' },
    G('in_wh', 'est', 'Question words · Palabras interrogativas', [['What?', '¿qué?'], ['Who?', '¿quién?'], ['Where?', '¿dónde?'], ['When?', '¿cuándo?'], ['Why?', '¿por qué?'], ['How?', '¿cómo?'], ['Which?', '¿cuál?'], ['How many?', '¿cuántos?']], 4, 22, 34, 'Why…? — Because… = ¿Por qué? — Porque…', 'Las palabras para preguntar empiezan casi todas por «wh».', [['¿Cómo se pregunta el lugar?', 'Con «Where»: Where do you live?'], ['¿Qué responde a «Why»?', '«Because».'], ['Completa: ___ is your birthday? — In May.', '«When».']], 'En inglés la palabra interrogativa va siempre al principio de la pregunta.', { s: 9, s2: 6 }),
    { id: 'in_do_questions', fam: 'est', n: 'Making questions · Formar preguntas',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 14, 'QUASM', { s: 8, b: 1 }) + formula(K, [['Question word', P.morado], ['Auxiliary', P.amarillo], ['Subject', P.azul], ['Main verb', P.verde]], 22, { s: 6, k: 3.9 }) + formula(K, [['Where', P.morado], ['do', P.amarillo], ['you', P.azul], ['live?', P.verde]], 52) + formula(K, [['What', P.morado], ['is', P.amarillo], ['she', P.azul], ['eating?', P.verde]], 78) + formula(K, [['', P.blanco], ['Did', P.amarillo], ['they', P.azul], ['win?', P.verde]], 104) + K.t(100, 136, 'Sin auxiliar no hay pregunta: «You live where?» es incorrecto', { s: 5.6, b: 1 }); },
      intro: 'Las preguntas siguen el orden palabra interrogativa, auxiliar, sujeto y verbo.',
      q: [['Ordena: you / like / do / what?', 'What do you like?'], ['¿Qué auxiliar va en pasado?', '«Did».'], ['Corrige: Where you are going?', 'Where are you going?']],
      porque: 'El auxiliar delante del sujeto es la señal de que la frase es una pregunta.' },
    G('in_negatives', 'est', 'Negative sentences · Frases negativas', [['I am not tired.', 'be + not', P.azul], ['She doesn’t eat meat.', 'present simple', P.verde], ['We didn’t go.', 'past simple', P.naranja], ['They can’t swim.', 'can + not', P.morado], ['He hasn’t finished.', 'present perfect', P.rosa], ['I won’t forget.', 'will + not', P.amarillo]], 2, 14, 30, 'Una sola negación: I don’t know anything', 'Cada tiempo forma la negativa con «not» detrás de su auxiliar.', [['¿Está bien «I don’t know nothing»?', 'No: «I don’t know anything».'], ['Negativa de «He works»:', 'He doesn’t work.'], ['¿Qué es «can’t»?', '«Cannot».']], 'En inglés estándar no se acumulan dos negaciones como en español.', { s: 7.6, s2: 5.4 }),
    G('in_adj_order', 'est', 'Adjective order · Orden de los adjetivos', [['opinion', 'beautiful', P.rosa], ['size', 'big', P.naranja], ['age', 'old', P.amarillo], ['colour', 'red', P.rojo], ['origin', 'Italian', P.verde], ['material', 'wooden', P.madera], ['noun', 'table', P.azul]], 7, 30, 40, 'a beautiful big old red Italian wooden table', 'Varios adjetivos delante de un nombre siguen un orden fijo.', [['¿«a red big car» o «a big red car»?', '«A big red car»: el tamaño va antes que el color.'], ['Ordena: cotton / white / a / shirt.', 'A white cotton shirt.'], ['¿Dónde va la opinión?', 'Primero: a lovely small house.']], 'A los hablantes nativos les suena raro cambiar este orden, aunque nadie lo estudie.', { s: 5.6, s2: 5 }),
    G('in_there_is', 'est', 'There is / There are · Hay', [['There is a cat.', 'hay un gato (singular)', P.azul], ['There are two cats.', 'hay dos gatos (plural)', P.verde], ['There isn’t any milk.', 'no hay leche', P.rojo], ['Is there a bank near here?', '¿hay un banco cerca?', P.amarillo], ['There was / There were', 'había, hubo', P.morado]], 1, 14, 18, 'Español: «hay» siempre igual · inglés: cambia con el número', '«There is» y «there are» equivalen a «hay» y concuerdan con lo que sigue.', [['Completa: There ___ three books.', '«Are».'], ['¿Cómo se dice «había mucha gente»?', '«There were a lot of people».'], ['Is there a park in your town?', 'Yes, there is / No, there isn’t.']], 'El verbo concuerda con el nombre que viene después.', { s: 7.6, s2: 5.4, gy: 4 })
  ];
  MO.agregar('ingles', L, { nombre: 'Inglés', familias: FAM, materias: /^(ingles)$/ });
})();
