/* b6_lib_contabilidad.js — Contabilidad (1/3): documentos comerciales, las cuentas, el registro. 34 modelos.
   Materia `conta`. Prefijo `ct_`. Cargar después de b6_modelos.js.
   No repite los dibujos que el Editorial ya tiene para conta (con_factura, con_balance, con_equilibrio, con_flujo,
   con_diario, con_cuentast, con_amortiza, con_peps, con_presupuesto, con_ivacadena). */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('ct_recibo')) return;
  var P = { papel: '#FBF7EE', azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', madera: '#B8946A', metal: '#C8CED4', billete: '#BFE0B0' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { doc: 'Documentos comerciales', cue: 'Las cuentas', reg: 'El registro contable', est: 'Estados financieros', inv: 'Inventarios', cos: 'Costos y precios', ban: 'Caja, bancos y dinero', nom: 'Nómina e impuestos', ges: 'Gestión, control y ética' };
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + f1 * .35, q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + (o && o.tit ? K.t(100, 14, o.tit, { s: 7, b: 1 }) : '') + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  function tabla(K, x, y, ws, filas, o) {
    o = o || {}; var h = o.h || 10, fs = o.s || 5.2, s = '', W = 0; ws.forEach(function (w) { W += w; });
    filas.forEach(function (f, i) {
      var yy = y + i * h, cab = i === 0 && !o.sinCab, tot = String(f[0]).charAt(0) === '=', cx = x;
      s += K.r(x, yy, W, h, 0, cab ? (o.cab || P.azul) : tot ? P.amarillo : P.blanco, { w: .6 });
      ws.forEach(function (w, j) {
        var tx = String(f[j] == null ? '' : f[j]); if (j === 0 && tot) tx = tx.slice(1);
        var num = j > 0 && !cab && /^[−\-+$\d(]/.test(tx);
        s += K.t(num ? cx + w - 2 : cx + 2, yy + h / 2 + fs * .36, tx, { s: fs, b: cab || tot ? 1 : 0, a: num ? 'end' : 'start' });
        if (j > 0) s += K.l('M' + cx + ' ' + yy + ' L' + cx + ' ' + (yy + h), P.grisO, { w: .4 });
        cx += w;
      });
    });
    return s;
  }
  function hoja(K, x, y, w, h, tit, col) { return K.r(x + 2.5, y + 2.5, w, h, 2, P.gris, { w: .4 }) + K.r(x, y, w, h, 2, P.blanco, { w: .9 }) + K.r(x, y, w, 12, 2, col || P.azul, { w: .6 }) + K.t(x + w / 2, y + 8.4, tit, { s: 6, b: 1 }); }
  function renglon(K, x, y, et, val, w) { return K.t(x, y, et, { s: 5.2, a: 'start' }) + (val ? K.t(x + w, y, val, { s: 5.4, b: 1, a: 'end' }) : '') + K.l('M' + x + ' ' + (y + 2.2) + ' L' + (x + w) + ' ' + (y + 2.2), P.grisO, { w: .3 }); }
  function firma(K, x, y, w, txt) { return K.l('M' + x + ' ' + y + ' q' + (w * .15) + ' -6 ' + (w * .3) + ' 0 t' + (w * .3) + ' 0', P.azulO, { w: .9 }) + K.l('M' + (x - 4) + ' ' + (y + 3) + ' L' + (x + w) + ' ' + (y + 3), P.tinta, { w: .5 }) + K.t(x + w / 2 - 2, y + 9, txt, { s: 4.8 }); }
  function persona(K, x, y, col) { return K.c(x, y, 6, P.piel, { w: .8 }) + K.p('M' + (x - 9) + ' ' + (y + 26) + ' Q' + (x - 9) + ' ' + (y + 8) + ' ' + x + ' ' + (y + 8) + ' Q' + (x + 9) + ' ' + (y + 8) + ' ' + (x + 9) + ' ' + (y + 26) + ' Z', col, { w: .8 }); }
  function caja(K, x, y, w, h, col, txt, fs) { return K.r(x, y, w, h, 3, col, { w: .9 }) + (txt ? K.t(x + w / 2, y + h / 2 + 2.3, txt, { s: fs || 6.2, b: 1 }) : ''); }

  var L = [
    /* ─────────── DOCUMENTOS COMERCIALES ─────────── */
    { id: 'ct_recibo', fam: 'doc', n: 'El recibo',
      d: function (K) { return K.suelo(100, 140, 90) + hoja(K, 24, 14, 152, 112, 'RECIBO N.º 0045', P.verde) + K.t(168, 34, 'Por $ 250,00', { s: 6.4, b: 1, a: 'end' }) + renglon(K, 32, 50, 'Recibí de:', 'Ana Pérez', 136) + renglon(K, 32, 64, 'La cantidad de:', 'doscientos cincuenta', 136) + renglon(K, 32, 78, 'Por concepto de:', 'alquiler de marzo', 136) + renglon(K, 32, 92, 'Fecha:', '05/03/2026', 136) + firma(K, 116, 112, 50, 'firma de quien recibe'); },
      intro: 'El recibo prueba que una persona entregó dinero a otra y por qué motivo.',
      q: [['¿Quién firma el recibo?', 'La persona que recibe el dinero.'], ['¿Por qué se escribe la cantidad también en letras?', 'Para que nadie pueda cambiar la cifra.'], ['¿Qué documento usa el contador para registrar este cobro?', 'La copia del recibo, que va al archivo como respaldo.']],
      porque: 'Sin un documento que lo respalde, un movimiento de dinero no se puede registrar ni comprobar.' },
    { id: 'ct_cheque', fam: 'doc', n: 'El cheque',
      d: function (K) { return K.suelo(100, 140, 96) + K.r(10, 34, 180, 78, 3, '#E4EEF4', { w: 1 }) + K.t(18, 46, 'BANCO DEL CENTRO', { s: 6.4, b: 1, a: 'start', c: P.azulO }) + K.t(182, 46, 'N.º 000127', { s: 5.4, a: 'end' }) + K.r(132, 52, 50, 11, 2, P.blanco, { w: .7 }) + K.t(178, 59.6, '$ 1 380,00', { s: 6, b: 1, a: 'end' }) + renglon(K, 18, 60, 'Páguese a la orden de:', 'Ferretería Sol', 108) + renglon(K, 18, 74, 'La suma de:', 'mil trescientos ochenta', 164) + renglon(K, 18, 88, 'Lugar y fecha:', '12/04/2026', 70) + firma(K, 128, 94, 52, 'firma del titular') + K.t(18, 108, '001234  0012 3456 78  000127', { s: 5.2, a: 'start' }) + K.t(100, 128, 'Orden de pago al banco con cargo a la cuenta corriente', { s: 6, b: 1 }); },
      intro: 'El cheque es una orden escrita para que el banco pague una suma con el dinero de la cuenta del titular.',
      q: [['¿Quiénes intervienen en un cheque?', 'El girador (titular), el banco que paga y el beneficiario.'], ['¿Qué pasa si la cuenta no tiene fondos?', 'El cheque es devuelto o protestado y puede tener consecuencias legales.'], ['¿Qué cuenta disminuye al pagar con cheque?', 'Bancos, no Caja.']],
      porque: 'El cheque mueve dinero entre cuentas sin billetes; por eso afecta a Bancos y no a Caja.' },
    { id: 'ct_pagare', fam: 'doc', n: 'El pagaré',
      d: function (K) { return K.suelo(100, 140, 90) + hoja(K, 20, 14, 160, 104, 'PAGARÉ   $ 5 000,00', P.naranja) + K.t(28, 40, 'Debo y pagaré incondicionalmente a', { s: 5.4, a: 'start' }) + renglon(K, 28, 52, 'la orden de:', 'Créditos Andes S.A.', 144) + renglon(K, 28, 64, 'la suma de:', 'cinco mil', 144) + renglon(K, 28, 76, 'con vencimiento el:', '30/09/2026', 144) + renglon(K, 28, 88, 'interés anual:', '12 %', 144) + firma(K, 30, 104, 50, 'deudor') + K.c(150, 102, 10, P.rosa, { w: .7 }) + K.t(150, 104, 'sello', { s: 5 }) + K.t(100, 134, 'Una sola persona promete pagar a otra', { s: 6, b: 1 }); },
      intro: 'El pagaré es una promesa escrita de pagar una cantidad en una fecha, a veces con interés.',
      q: [['¿Quién firma el pagaré?', 'El deudor, que es quien promete pagar.'], ['¿En qué cuenta lo anota quien debe?', 'En el pasivo: Documentos por pagar.'], ['¿Y quien va a cobrar?', 'En el activo: Documentos por cobrar.']],
      porque: 'El mismo pagaré es una deuda para uno y un derecho de cobro para el otro: cada parte lo registra en su lado.' },
    { id: 'ct_letra', fam: 'doc', n: 'La letra de cambio',
      d: function (K) { return K.suelo(100, 140, 96) + persona(K, 30, 30, P.azul) + persona(K, 100, 86, P.verde) + persona(K, 170, 30, P.amarillo) + K.t(30, 72, 'girador', { s: 6.4, b: 1 }) + K.t(30, 80, 'emite la orden', { s: 5 }) + K.t(170, 72, 'beneficiario', { s: 6.4, b: 1 }) + K.t(170, 80, 'cobra', { s: 5 }) + K.t(100, 126, 'girado (aceptante)', { s: 6.4, b: 1 }) + K.t(100, 134, 'paga al vencimiento', { s: 5 }) + K.flecha(44, 46, 88, 88, P.azulO, { w: 1.2 }) + K.t(56, 76, 'ordena pagar', { s: 5, c: P.azulO }) + K.flecha(114, 96, 160, 60, P.verdeO, { w: 1.2 }) + K.t(148, 92, 'paga', { s: 5, c: P.verdeO }) + K.flecha(48, 36, 154, 36, P.grisO, { w: .9 }) + K.t(100, 30, 'entrega la letra', { s: 5 }); },
      intro: 'En la letra de cambio una persona ordena a otra que pague a una tercera en una fecha fijada.',
      q: [['¿En qué se diferencia del pagaré?', 'En el pagaré hay dos partes y una promesa; en la letra hay una orden y puede haber tres partes.'], ['¿Qué hace el girado al «aceptar» la letra?', 'Firma y se compromete a pagarla al vencimiento.'], ['¿Se puede pasar la letra a otra persona?', 'Sí, por endoso, firmando al dorso.']],
      porque: 'La letra permite usar una deuda como medio de pago entre varias personas.' },
    { id: 'ct_cotizacion', fam: 'doc', n: 'La cotización',
      d: function (K) { return K.suelo(100, 140, 96) + hoja(K, 14, 10, 172, 118, 'COTIZACIÓN N.º 218', P.morado) + tabla(K, 20, 28, [76, 22, 32, 30], [['Producto', 'Cant.', 'Precio u.', 'Total'], ['Silla de oficina', '4', '85,00', '340,00'], ['Escritorio', '2', '210,00', '420,00'], ['Lámpara', '4', '18,50', '74,00'], ['=Total sin impuestos', '', '', '834,00']], { h: 11 }) + K.t(20, 96, 'Válida por 15 días · entrega en 5 días hábiles', { s: 5.4, a: 'start' }) + K.t(20, 106, 'Forma de pago: 50 % al pedir, 50 % al entregar', { s: 5.4, a: 'start' }) + K.t(100, 122, 'No se registra en contabilidad: aún no hay venta', { s: 5.6, b: 1, c: P.rojoO }); },
      intro: 'La cotización (o proforma) informa al cliente el precio y las condiciones antes de que decida comprar.',
      q: [['¿Se registra la cotización como venta?', 'No: es solo una oferta; no hay intercambio todavía.'], ['¿Por qué tiene fecha de validez?', 'Porque los precios pueden cambiar.'], ['Si el cliente pide 6 sillas, ¿cuánto suman?', '6 × 85 = 510,00.']],
      porque: 'Solo se contabiliza lo que ya ocurrió; una oferta es un hecho comercial, no un hecho contable.' },
    { id: 'ct_orden_compra', fam: 'doc', n: 'La orden de compra',
      d: function (K) { return K.suelo(100, 140, 96) + hoja(K, 12, 22, 78, 92, 'ORDEN DE COMPRA', P.amarillo) + renglon(K, 18, 46, 'Proveedor:', 'Papelera Luz', 66) + renglon(K, 18, 58, '50 resmas A4', '$ 225', 66) + renglon(K, 18, 70, 'Entrega:', 'lunes', 66) + firma(K, 26, 96, 40, 'autoriza compras') + K.flecha(94, 66, 120, 66, P.tinta, { w: 1.4 }) + K.r(124, 40, 64, 52, 4, P.gris, { w: .9 }) + K.r(132, 30, 48, 14, 2, P.rojo, { w: .8 }) + K.t(156, 40, 'proveedor', { s: 5.6, b: 1 }) + K.t(156, 62, 'prepara', { s: 5.6 }) + K.t(156, 72, 'el pedido', { s: 5.6 }) + K.t(100, 132, 'Lo emite el comprador para pedir y autorizar la compra', { s: 5.8, b: 1 }); },
      intro: 'La orden de compra es el documento con que una empresa pide formalmente mercadería a un proveedor.',
      q: [['¿Quién emite la orden de compra?', 'El comprador.'], ['¿Para qué sirve la firma de autorización?', 'Para controlar que nadie compre sin permiso.'], ['¿Cuándo se registra la compra?', 'Al recibir la mercadería con su factura, no al emitir la orden.']],
      porque: 'Separar quien pide, quien autoriza y quien paga evita compras indebidas.' },
    { id: 'ct_guia', fam: 'doc', n: 'La guía de remisión',
      d: function (K) { return K.suelo(100, 140, 96) + K.r(14, 62, 92, 46, 3, P.azul, { w: 1 }) + K.p('M106 74 L130 74 L144 90 L144 108 L106 108 Z', P.amarillo, { w: 1 }) + K.r(112, 78, 18, 12, 1, P.blanco, { w: .7 }) + K.c(36, 110, 8, P.tinta) + K.c(124, 110, 8, P.tinta) + K.c(36, 110, 3, P.metal) + K.c(124, 110, 3, P.metal) + K.t(60, 88, 'mercadería', { s: 6.4, b: 1 }) + hoja(K, 128, 12, 62, 54, 'GUÍA N.º 77', P.verde) + K.t(134, 36, 'Origen: bodega', { s: 4.8, a: 'start' }) + K.t(134, 44, 'Destino: tienda 2', { s: 4.8, a: 'start' }) + K.t(134, 52, '20 cajas', { s: 4.8, a: 'start' }) + K.t(134, 60, 'Placa: ABC-123', { s: 4.8, a: 'start' }) + K.t(100, 134, 'Acompaña a la mercadería durante el traslado', { s: 6, b: 1 }); },
      intro: 'La guía de remisión (o nota de entrega) justifica el traslado de mercadería de un lugar a otro.',
      q: [['¿Quién lleva la guía?', 'El transportista, junto con la carga.'], ['¿La guía indica precios?', 'No necesariamente: indica qué se traslada, de dónde y a dónde.'], ['¿Qué se compara al recibir la carga?', 'Las cantidades de la guía con lo que llega realmente.']],
      porque: 'Al revisar la guía en la llegada se descubren faltantes antes de firmar la recepción.' },
    { id: 'ct_notas', fam: 'doc', n: 'Nota de crédito y nota de débito',
      d: function (K) { return K.suelo(100, 140, 96) + hoja(K, 12, 18, 82, 84, 'NOTA DE CRÉDITO', P.verde) + K.t(53, 44, 'Devolución de', { s: 5.6 }) + K.t(53, 54, '2 camisas falladas', { s: 5.6 }) + K.t(53, 72, '− $ 60,00', { s: 9, b: 1, c: P.verdeO }) + K.t(53, 88, 'baja lo que debe el cliente', { s: 5 }) + hoja(K, 106, 18, 82, 84, 'NOTA DE DÉBITO', P.rojo) + K.t(147, 44, 'Intereses por', { s: 5.6 }) + K.t(147, 54, 'pago atrasado', { s: 5.6 }) + K.t(147, 72, '+ $ 15,00', { s: 9, b: 1, c: P.rojoO }) + K.t(147, 88, 'sube lo que debe el cliente', { s: 5 }) + K.t(100, 124, 'Las dos corrigen una factura ya emitida', { s: 6.2, b: 1 }); },
      intro: 'La nota de crédito disminuye el valor de una factura; la nota de débito lo aumenta.',
      q: [['El cliente devuelve mercadería. ¿Qué nota se emite?', 'Una nota de crédito.'], ['¿Por qué no se rompe la factura y se hace otra?', 'Porque la factura ya se registró; se corrige con otro documento.'], ['¿Qué nota se usa para cobrar un flete olvidado?', 'Una nota de débito.']],
      porque: 'Los documentos emitidos no se borran: se corrigen con otros, y así queda la historia completa.' },
    { id: 'ct_ingreso_egreso', fam: 'doc', n: 'Comprobantes de ingreso y egreso',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.caja(76, 60, 48, 40, 10, P.metal, { w: 1 }) + K.r(92, 66, 16, 4, 1, P.tinta) + K.t(100, 90, 'CAJA', { s: 7, b: 1 }); return s + hoja(K, 8, 20, 56, 42, 'INGRESO', P.verde) + K.t(36, 42, 'cobro a cliente', { s: 5 }) + K.t(36, 54, '+ 400', { s: 7, b: 1, c: P.verdeO }) + K.flecha(64, 46, 82, 62, P.verdeO, { w: 1.6 }) + hoja(K, 136, 20, 56, 42, 'EGRESO', P.rojo) + K.t(164, 42, 'pago de luz', { s: 5 }) + K.t(164, 54, '− 90', { s: 7, b: 1, c: P.rojoO }) + K.flecha(124, 62, 140, 52, P.rojoO, { w: 1.6 }) + K.t(100, 124, 'Saldo = saldo anterior + ingresos − egresos', { s: 6.2, b: 1 }) + K.t(100, 134, 'Cada comprobante lleva número, fecha, concepto y firma', { s: 5.2 }); },
      intro: 'Cada entrada y salida de dinero se respalda con un comprobante de ingreso o de egreso.',
      q: [['La caja tenía 300. Entran 400 y salen 90. ¿Cuánto queda?', '300 + 400 − 90 = 610.'], ['¿Por qué se numeran los comprobantes?', 'Para notar si falta alguno.'], ['¿Quién debe firmar el egreso?', 'Quien autoriza el pago y quien recibe el dinero.']],
      porque: 'La numeración correlativa hace visible cualquier comprobante perdido o sacado.' },
    { id: 'ct_ticket', fam: 'doc', n: 'El tique de caja',
      d: function (K) { var s = K.suelo(100, 140, 60) + K.p('M68 8 L132 8 L132 126 L127 130 L122 126 L117 130 L112 126 L107 130 L102 126 L97 130 L92 126 L87 130 L82 126 L77 130 L72 126 L68 130 Z', P.blanco, { w: .9 }); s += K.t(100, 20, 'MINIMARKET LA ESQUINA', { s: 5, b: 1 }) + K.t(100, 28, '15/05/2026  18:42', { s: 4.6 }); var it = [['Pan', '1,20'], ['Leche 1 L', '0,95'], ['Arroz 1 kg', '1,40'], ['Huevos x12', '2,60']]; it.forEach(function (q, i) { s += K.t(74, 42 + i * 9, q[0], { s: 5, a: 'start' }) + K.t(126, 42 + i * 9, q[1], { s: 5, a: 'end' }); }); return s + K.l('M74 80 L126 80', P.tinta, { w: .5 }) + K.t(74, 90, 'TOTAL', { s: 6, b: 1, a: 'start' }) + K.t(126, 90, '6,15', { s: 6, b: 1, a: 'end' }) + K.t(74, 100, 'Efectivo', { s: 5, a: 'start' }) + K.t(126, 100, '10,00', { s: 5, a: 'end' }) + K.t(74, 109, 'Cambio', { s: 5, a: 'start' }) + K.t(126, 109, '3,85', { s: 5, a: 'end' }) + K.t(100, 120, '¡Gracias!', { s: 5 }); },
      intro: 'El tique (o boleta) de la caja registradora resume una venta al consumidor final.',
      q: [['Comprueba el total de la compra.', '1,20 + 0,95 + 1,40 + 2,60 = 6,15.'], ['¿Cuánto cambio corresponde si paga con 10?', '10 − 6,15 = 3,85.'], ['¿Qué resumen saca la caja al cerrar el día?', 'El cierre o «corte» con el total de ventas, que se compara con el dinero contado.']],
      porque: 'Al final del día, la suma de los tiques debe coincidir con el dinero de la caja.' },
    { id: 'ct_circuito', fam: 'doc', n: 'El recorrido de una venta',
      d: function (K) { var D = [['cotización', P.morado], ['pedido', P.amarillo], ['guía', P.verde], ['factura', P.azul], ['recibo', P.rosa]], s = K.suelo(100, 140, 96); D.forEach(function (q, i) { var x = 8 + i * 38; s += K.r(x + 2, 44, 30, 40, 2, P.gris, { w: .3 }) + K.r(x, 42, 30, 40, 2, P.blanco, { w: .8 }) + K.r(x, 42, 30, 9, 2, q[1], { w: .5 }) + K.l('M' + (x + 5) + ' 60 L' + (x + 25) + ' 60 M' + (x + 5) + ' 66 L' + (x + 25) + ' 66 M' + (x + 5) + ' 72 L' + (x + 18) + ' 72', P.grisO, { w: .5 }) + K.t(x + 15, 96, q[0], { s: 5.8, b: 1 }) + K.t(x + 15, 32, String(i + 1), { s: 8, b: 1 }); if (i < 4) s += K.flecha(x + 31, 62, x + 37, 62, P.tinta, { w: 1 }); }); return s + K.t(100, 116, 'Se registra en contabilidad a partir de la factura', { s: 6, b: 1 }) + K.t(100, 128, 'y el cobro, a partir del recibo', { s: 6 }); },
      intro: 'Una venta deja varios documentos en orden: cada uno prueba un paso distinto.',
      q: [['¿Qué documento prueba que el cliente recibió la mercadería?', 'La guía o nota de entrega firmada.'], ['¿Cuál origina el registro de la venta?', 'La factura.'], ['¿Qué falta si hay factura pero no recibo?', 'El cobro: la venta fue a crédito y el cliente aún debe.']],
      porque: 'Cada paso tiene su prueba; si un documento falta, se sabe exactamente qué paso no ocurrió.' },
    { id: 'ct_archivo', fam: 'doc', n: 'El archivo de documentos',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.caja(20, 26, 160, 98, 8, P.madera, { w: 1 }); ['2022', '2023', '2024', '2025', '2026'].forEach(function (a, i) { var x = 28 + i * 30; s += K.r(x, 34, 24, 84, 2, CO[i], { w: .9 }) + K.c(x + 12, 104, 4, P.blanco, { w: .7 }) + K.r(x + 4, 44, 16, 30, 1, P.blanco, { w: .5 }) + K.t(x + 12, 58, a, { s: 5.6, b: 1 }) + K.t(x + 12, 66, 'enero–', { s: 3.8 }) + K.t(x + 12, 71, 'dic.', { s: 3.8 }); }); return s + K.t(100, 18, 'Un archivador por año, ordenado por mes y número', { s: 6, b: 1 }) + K.t(100, 136, 'La ley de cada país fija cuántos años guardarlos', { s: 5.8 }); },
      intro: 'Los documentos contables se guardan ordenados por fecha y número, durante los años que exige la ley.',
      q: [['¿Para qué se guardan los documentos antiguos?', 'Para justificar los registros ante una revisión o auditoría.'], ['¿Cómo se ordenan dentro de cada mes?', 'Por fecha y número correlativo.'], ['¿Vale un archivo digital?', 'Sí, si cumple lo que pide la autoridad tributaria del país.']],
      porque: 'Un registro contable vale lo que vale su respaldo: sin el documento, el asiento no se puede probar.' },
    /* ─────────── LAS CUENTAS ─────────── */
    { id: 'ct_ecuacion', fam: 'cue', n: 'La ecuación contable',
      d: function (K) { return K.suelo(100, 140, 80) + K.p('M100 30 L108 120 L92 120 Z', P.metal, { w: 1 }) + K.r(76, 120, 48, 8, 2, P.grisO, { w: 1 }) + K.r(22, 34, 156, 4, 1, P.metal, { w: 1 }) + K.l('M40 38 L26 66 M40 38 L54 66 M160 38 L146 66 M160 38 L174 66', P.grisO, { w: .7 }) + K.e(40, 68, 22, 4, P.metal, { w: 1 }) + K.e(160, 68, 22, 4, P.metal, { w: 1 }) + caja(K, 24, 46, 32, 20, P.azul, 'ACTIVO', 5.6) + caja(K, 140, 54, 20, 12, P.rojo, 'P', 6) + caja(K, 160, 46, 18, 20, P.verde, 'Pt', 6) + K.t(40, 84, '$ 80 000', { s: 7, b: 1 }) + K.t(40, 92, 'lo que tiene', { s: 5 }) + K.t(160, 84, '30 000 + 50 000', { s: 6.4, b: 1 }) + K.t(160, 92, 'lo que debe + lo propio', { s: 5 }) + K.t(100, 22, 'ACTIVO = PASIVO + PATRIMONIO', { s: 7.4, b: 1 }); },
      intro: 'Todo lo que tiene una empresa se financió con deudas (pasivo) o con recursos de sus dueños (patrimonio).',
      q: [['Activo 80 000 y pasivo 30 000. ¿Patrimonio?', '80 000 − 30 000 = 50 000.'], ['¿Puede romperse el equilibrio?', 'No: cada operación cambia los dos lados por igual o se compensa en el mismo lado.'], ['¿Qué pasa si el pasivo es mayor que el activo?', 'El patrimonio es negativo: la empresa debe más de lo que tiene.']],
      porque: 'Cada bien tiene un origen; la ecuación iguala los bienes con quién los pagó.' },
    G('ct_activo', 'cue', 'El activo: lo que tiene la empresa', [['Caja', 'billetes y monedas'], ['Bancos', 'dinero en cuentas'], ['Clientes', 'lo que nos deben'], ['Inventario', 'mercadería para vender'], ['Muebles y enseres', 'escritorios, sillas'], ['Equipo de cómputo', 'computadoras, impresoras'], ['Vehículos', 'camionetas de reparto'], ['Edificios y terrenos', 'local propio']], 2, 18, 22, 'Bienes y derechos que darán beneficios', 'El activo reúne los bienes y los derechos de cobro que controla la empresa.', [['¿Es un activo lo que nos deben los clientes?', 'Sí: es un derecho de cobro (Cuentas por cobrar).'], ['¿Es activo un local alquilado?', 'No: no es de la empresa; el alquiler es un gasto.'], ['Ordena de más a menos líquido: edificio, caja, inventario.', 'Caja, inventario, edificio.']], 'Se ordena por liquidez: primero lo que ya es dinero, al final lo que tardaría en venderse.', { s: 6.8, s2: 5.2 }),
    G('ct_pasivo', 'cue', 'El pasivo: lo que debe la empresa', [['Proveedores', 'compras a crédito'], ['Préstamos bancarios', 'cuotas pendientes'], ['Sueldos por pagar', 'salarios del mes'], ['Impuestos por pagar', 'a la autoridad tributaria'], ['Seguridad social por pagar', 'aportes retenidos'], ['Anticipos de clientes', 'cobrado y no entregado'], ['Hipoteca', 'deuda a largo plazo'], ['Intereses por pagar', 'costo del préstamo']], 2, 18, 22, 'Obligaciones con terceros', 'El pasivo son las deudas que la empresa tendrá que pagar con dinero, bienes o servicios.', [['¿Por qué un anticipo de un cliente es pasivo?', 'Porque la empresa debe entregarle algo que ya cobró.'], ['¿Qué pasivo nace al comprar a crédito?', 'Proveedores (Cuentas por pagar).'], ['¿Es pasivo un sueldo que ya se pagó?', 'No: al pagarlo, la deuda desaparece.']], 'Un pasivo no siempre es un préstamo: cualquier obligación pendiente lo es.', { s: 6.4, s2: 5.2 }),
    G('ct_patrimonio', 'cue', 'El patrimonio: lo que es de los dueños', [['Capital', 'aporte inicial de los socios'], ['Aportes posteriores', 'nuevas inversiones'], ['Reservas', 'utilidades apartadas por ley'], ['Utilidades acumuladas', 'ganancias de años pasados'], ['Resultado del ejercicio', 'ganancia o pérdida del año'], ['Retiros del dueño', 'lo restan']], 2, 22, 24, 'Patrimonio = Activo − Pasivo', 'El patrimonio es la parte del activo que pertenece a los dueños, una vez descontadas las deudas.', [['¿Aumenta el patrimonio con una ganancia?', 'Sí: la utilidad del ejercicio se suma.'], ['¿Qué hace un retiro del dueño?', 'Lo disminuye.'], ['¿Es el patrimonio dinero en efectivo?', 'No: es un derecho sobre todos los activos, no una caja.']], 'El patrimonio crece con aportes y ganancias, y baja con pérdidas y retiros.', { s: 6.6, s2: 5.2 }),
    { id: 'ct_corriente', fam: 'cue', n: 'Corriente y no corriente',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.flecha(14, 70, 190, 70, P.tinta, { w: 1.2 }) + K.r(14, 62, 84, 16, 0, P.verde, { w: .5, op: .8 }) + K.r(98, 62, 88, 16, 0, P.azul, { w: .5, op: .8 }) + K.t(56, 73, 'hasta 12 meses', { s: 6, b: 1 }) + K.t(142, 73, 'más de 12 meses', { s: 6, b: 1 }) + K.l('M98 56 L98 84', P.rojoO, { w: 1.2 }) + K.t(98, 52, 'hoy + 1 año', { s: 5.4, b: 1, c: P.rojoO }); return s + K.t(56, 24, 'CORRIENTE', { s: 7, b: 1 }) + K.t(56, 34, 'caja, clientes, inventario', { s: 5 }) + K.t(56, 42, 'proveedores, sueldos por pagar', { s: 5 }) + K.t(142, 24, 'NO CORRIENTE', { s: 7, b: 1 }) + K.t(142, 34, 'edificios, vehículos, equipos', { s: 5 }) + K.t(142, 42, 'préstamos a 5 años, hipoteca', { s: 5 }) + K.t(100, 100, 'Un préstamo a 3 años: la cuota de este año es corriente', { s: 5.6 }) + K.t(100, 110, 'y el resto, no corriente', { s: 5.6 }); },
      intro: 'Los activos y pasivos se separan según se conviertan en dinero o se paguen antes o después de un año.',
      q: [['¿Es corriente una deuda con un proveedor a 30 días?', 'Sí.'], ['¿En qué grupo va una camioneta de reparto?', 'Activo no corriente.'], ['¿Para qué sirve separar así?', 'Para saber si el dinero de corto plazo alcanza para las deudas de corto plazo.']],
      porque: 'Comparar activo y pasivo corriente dice si la empresa podrá pagar lo que vence pronto.' },
    { id: 'ct_plan', fam: 'cue', n: 'El plan de cuentas',
      d: function (K) { var R = [[0, '1', 'ACTIVO', P.azul], [1, '1.1', 'Activo corriente', P.azul], [2, '1.1.01', 'Caja', P.blanco], [2, '1.1.02', 'Bancos', P.blanco], [2, '1.1.03', 'Clientes', P.blanco], [1, '1.2', 'Activo no corriente', P.azul], [0, '2', 'PASIVO', P.rojo], [0, '3', 'PATRIMONIO', P.verde], [0, '4', 'INGRESOS', P.amarillo], [0, '5', 'GASTOS', P.naranja]], s = K.suelo(100, 140, 96); R.forEach(function (q, i) { var x = 20 + q[0] * 16, y = 12 + i * 12; s += K.r(x, y, 160 - q[0] * 16, 10, 2, q[3], { w: .6 }) + K.t(x + 3, y + 7, q[1], { s: 5.4, b: 1, a: 'start' }) + K.t(x + 34, y + 7, q[2], { s: 5.6, b: q[0] < 2 ? 1 : 0, a: 'start' }); if (q[0]) s += K.l('M' + (x - 8) + ' ' + (y - 2) + ' L' + (x - 8) + ' ' + (y + 5) + ' L' + x + ' ' + (y + 5), P.grisO, { w: .5 }); }); return s + K.t(100, 140, 'El código dice a qué grupo pertenece cada cuenta', { s: 5.6, b: 1 }); },
      intro: 'El plan de cuentas es la lista ordenada y codificada de todas las cuentas que usa una empresa.',
      q: [['¿Qué indica el primer número del código?', 'El grupo: 1 activo, 2 pasivo, 3 patrimonio, 4 ingresos, 5 gastos.'], ['¿Qué código le darías a «Inventario» después de Clientes?', '1.1.04.'], ['¿Por qué se codifica?', 'Para registrar rápido, sin ambigüedad, y ordenar los informes.']],
      porque: 'Con un código, cada movimiento cae siempre en la misma cuenta, aunque lo registre otra persona.' },
    { id: 'ct_naturaleza', fam: 'cue', n: 'Naturaleza de las cuentas',
      d: function (K) { return K.suelo(100, 140, 96) + tabla(K, 18, 20, [64, 50, 50], [['Grupo', 'Saldo normal', 'Lado'], ['Activo', 'deudor', 'DEBE'], ['Gastos y costos', 'deudor', 'DEBE'], ['Pasivo', 'acreedor', 'HABER'], ['Patrimonio', 'acreedor', 'HABER'], ['Ingresos', 'acreedor', 'HABER']], { h: 14, s: 6 }) + K.t(100, 122, 'Una cuenta crece por el lado de su naturaleza', { s: 6.2, b: 1 }) + K.t(100, 132, 'Debe = izquierda · Haber = derecha', { s: 5.6 }); },
      intro: 'Cada grupo de cuentas tiene un saldo «normal»: deudor (en el Debe) o acreedor (en el Haber).',
      q: [['¿Qué saldo normal tiene la cuenta Bancos?', 'Deudor, porque es activo.'], ['¿Y la cuenta Ventas?', 'Acreedor, porque es un ingreso.'], ['Si Caja tiene saldo acreedor, ¿qué indica?', 'Un error: no se puede sacar más dinero del que hay.']],
      porque: 'Conocer la naturaleza de cada cuenta permite detectar saldos imposibles a primera vista.' },
    { id: 'ct_partida', fam: 'cue', n: 'La partida doble',
      d: function (K) { return K.suelo(100, 140, 96) + K.r(20, 24, 160, 14, 2, P.amarillo, { w: .8 }) + K.t(100, 34, 'Compra de un computador al contado: $ 900', { s: 6.4, b: 1 }) + caja(K, 20, 52, 74, 40, P.azul) + K.t(57, 64, 'DEBE', { s: 6.4, b: 1 }) + K.t(57, 76, 'Equipo de cómputo', { s: 5.6 }) + K.t(57, 86, '900', { s: 7, b: 1 }) + caja(K, 106, 52, 74, 40, P.verde) + K.t(143, 64, 'HABER', { s: 6.4, b: 1 }) + K.t(143, 76, 'Bancos', { s: 5.6 }) + K.t(143, 86, '900', { s: 7, b: 1 }) + K.t(100, 76, '=', { s: 12, b: 1 }) + K.t(100, 112, 'No hay deudor sin acreedor', { s: 6.6, b: 1 }) + K.t(100, 124, 'Suma del Debe = suma del Haber en cada asiento', { s: 5.8 }); },
      intro: 'Toda operación afecta al menos a dos cuentas: lo que entra en una sale de otra por el mismo valor.',
      q: [['¿Qué cuenta aumenta y cuál disminuye en esta compra?', 'Aumenta Equipo de cómputo y disminuye Bancos.'], ['¿Cambia el total del activo?', 'No: un activo sube y otro baja 900.'], ['¿Puede un asiento tener tres cuentas?', 'Sí, si las sumas del Debe y del Haber siguen siendo iguales.']],
      porque: 'Como cada valor se anota dos veces, la suma total del Debe y del Haber siempre debe coincidir.' },
    { id: 'ct_debe_haber', fam: 'cue', n: 'Cuándo se carga y cuándo se abona',
      d: function (K) { return K.suelo(100, 140, 96) + tabla(K, 14, 18, [56, 58, 58], [['Cuenta de…', 'Aumenta en', 'Disminuye en'], ['Activo', 'Debe (cargo)', 'Haber (abono)'], ['Pasivo', 'Haber (abono)', 'Debe (cargo)'], ['Patrimonio', 'Haber (abono)', 'Debe (cargo)'], ['Ingresos', 'Haber (abono)', 'Debe (cargo)'], ['Gastos', 'Debe (cargo)', 'Haber (abono)']], { h: 14, s: 5.8 }) + K.t(100, 120, 'Cargar = anotar en el Debe · Abonar = anotar en el Haber', { s: 5.8, b: 1 }) + K.t(100, 132, 'Ejemplo: pagar una deuda = cargo a Pasivo, abono a Bancos', { s: 5.4 }); },
      intro: 'Las reglas del cargo y del abono dicen en qué columna se anota cada aumento o disminución.',
      q: [['Se cobra a un cliente. ¿Qué se carga y qué se abona?', 'Se carga Caja (sube) y se abona Clientes (baja).'], ['Se paga el alquiler. ¿Qué se carga?', 'Gasto de alquiler (sube); se abona Caja o Bancos.'], ['¿Cargar significa siempre aumentar?', 'No: aumenta las cuentas deudoras y disminuye las acreedoras.']],
      porque: 'Debe y Haber son lados, no buenas o malas noticias: el significado depende del tipo de cuenta.' },
    { id: 'ct_resultado', fam: 'cue', n: 'Ingresos, costos y gastos',
      d: function (K) { return K.suelo(100, 140, 96) + caja(K, 14, 20, 54, 28, P.verde, 'INGRESOS', 6.4) + K.t(41, 58, 'ventas, servicios,', { s: 5 }) + K.t(41, 65, 'intereses ganados', { s: 5 }) + caja(K, 73, 20, 54, 28, P.naranja, 'COSTOS', 6.4) + K.t(100, 58, 'lo que costó', { s: 5 }) + K.t(100, 65, 'lo vendido', { s: 5 }) + caja(K, 132, 20, 54, 28, P.rojo, 'GASTOS', 6.4) + K.t(159, 58, 'sueldos, alquiler,', { s: 5 }) + K.t(159, 65, 'luz, publicidad', { s: 5 }) + K.r(30, 82, 140, 22, 3, P.amarillo, { w: .9 }) + K.t(100, 96, 'Utilidad = Ingresos − Costos − Gastos', { s: 7, b: 1 }) + K.t(100, 120, 'Son cuentas de resultado: se cierran al final del año', { s: 5.8, b: 1 }) + K.t(100, 130, 'y su saldo pasa al patrimonio', { s: 5.6 }); },
      intro: 'Las cuentas de resultado miden lo que la empresa ganó y lo que le costó ganarlo en un periodo.',
      q: [['Ventas 12 000, costo 7 000, gastos 3 000. ¿Utilidad?', '12 000 − 7 000 − 3 000 = 2 000.'], ['¿Es un gasto comprar un camión?', 'No: es un activo; el gasto será su depreciación anual.'], ['¿Qué diferencia hay entre costo y gasto?', 'El costo está ligado a lo vendido; el gasto, al funcionamiento general.']],
      porque: 'Las cuentas de resultado vuelven a cero cada año para medir cada periodo por separado.' },
    { id: 'ct_hecho', fam: 'cue', n: '¿Se registra o no se registra?',
      d: function (K) { var S = [['Compra de mercadería', 1], ['Pago de sueldos', 1], ['Firma de un contrato futuro', 0], ['Venta a crédito', 1], ['Contratar a una persona', 0], ['Pedir una cotización', 0]], s = K.suelo(100, 140, 96); S.forEach(function (q, i) { var x = 12 + (i % 2) * 90, y = 18 + Math.floor(i / 2) * 32; s += K.r(x, y, 86, 26, 3, q[1] ? P.verde : P.gris, { w: .8 }) + K.c(x + 12, y + 13, 7, q[1] ? P.verdeO : P.grisO, { w: .6 }) + K.t(x + 12, y + 16, q[1] ? 'Sí' : 'No', { s: 5.4, b: 1, c: P.blanco }) + K.t(x + 52, y + 16, q[0], { s: Math.min(5.6, 62 / (q[0].length * .55)), b: 1 }); }); return s + K.t(100, 128, 'Se registra si cambia el patrimonio o los recursos y se puede medir en dinero', { s: 5.2, b: 1 }); },
      intro: 'Solo se contabilizan los hechos económicos: los que ya cambiaron los recursos o las deudas y tienen un valor.',
      q: [['¿Se registra la contratación de un empleado?', 'No hasta que trabaje y se le deba o se le pague su sueldo.'], ['¿Se registra una venta a crédito?', 'Sí: sale mercadería y nace un derecho de cobro.'], ['¿Se registra un incendio que destruye mercadería?', 'Sí: disminuye un activo y se reconoce una pérdida.']],
      porque: 'Una promesa o una intención no mueve recursos; un hecho sí, aunque no haya dinero de por medio.' },
    { id: 'ct_efecto', fam: 'cue', n: 'Cada operación y su efecto',
      d: function (K) { return K.suelo(100, 140, 96) + tabla(K, 8, 14, [74, 34, 34, 42], [['Operación', 'Activo', 'Pasivo', 'Patrimonio'], ['Aporte de capital 1 000', '+1 000', '', '+1 000'], ['Compra a crédito 500', '+500', '+500', ''], ['Pago al proveedor 200', '−200', '−200', ''], ['Pago de luz 80', '−80', '', '−80'], ['=Totales', '+1 220', '+300', '+920']], { h: 14, s: 5.6 }) + K.t(100, 116, '1 220 = 300 + 920', { s: 8, b: 1 }) + K.t(100, 130, 'Después de cada operación la ecuación sigue igualada', { s: 5.8 }); },
      intro: 'Cada operación cambia la ecuación contable, pero los dos lados siempre quedan iguales.',
      q: [['¿Por qué el pago de luz reduce el patrimonio?', 'Porque es un gasto: sale dinero y no entra otro bien.'], ['¿Qué operación no cambia el total del activo?', 'Una compra al contado: un activo sube y otro baja.'], ['Comprueba la igualdad final.', '300 + 920 = 1 220.']],
      porque: 'Seguir el efecto en la ecuación es la forma más segura de saber qué cuentas tocar.' },
    /* ─────────── EL REGISTRO CONTABLE ─────────── */
    { id: 'ct_ciclo', fam: 'reg', n: 'El ciclo contable',
      d: function (K) { var E = ['documentos', 'diario', 'mayor', 'comprobación', 'ajustes', 'estados', 'cierre', 'nuevo año'], s = K.suelo(100, 140, 96) + K.c(100, 74, 46, P.blanco, { w: .6 }); E.forEach(function (q, i) { var a = -Math.PI / 2 + i * Math.PI / 4, x = 100 + Math.cos(a) * 52, y = 74 + Math.sin(a) * 52, a2 = a + Math.PI / 4 - .32; s += K.c(x, y, 15, CO[i], { w: .9 }) + K.t(x, y - 1, String(i + 1), { s: 6, b: 1 }) + K.t(x, y + 6, q, { s: Math.min(4.6, 26 / (q.length * .55)) }); s += K.flecha(100 + Math.cos(a + .32) * 52, 74 + Math.sin(a + .32) * 52, 100 + Math.cos(a2) * 52, 74 + Math.sin(a2) * 52, P.grisO, { w: .8, p: 3 }); }); return s + K.t(100, 72, 'un año', { s: 7, b: 1 }) + K.t(100, 81, 'contable', { s: 6 }); },
      intro: 'El ciclo contable son los pasos que se repiten cada periodo, desde el documento hasta el cierre.',
      q: [['¿Cuál es el primer paso?', 'Reunir y revisar los documentos de respaldo.'], ['¿Para qué sirve el balance de comprobación?', 'Para comprobar que el Debe y el Haber suman lo mismo antes de los estados.'], ['¿Qué se hace en el cierre?', 'Se cancelan las cuentas de resultado y se traslada la utilidad al patrimonio.']],
      porque: 'Seguir siempre el mismo orden hace que cualquier error se pueda rastrear hasta su documento.' },
    { id: 'ct_asiento', fam: 'reg', n: 'Asiento simple y asiento compuesto',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 14, 'Simple: una cuenta al Debe y una al Haber', { s: 6, b: 1 }) + tabla(K, 20, 20, [92, 34, 34], [['Cuenta', 'Debe', 'Haber'], ['Caja', '600', ''], ['   Ventas', '', '600']], { h: 10, s: 5.6 }) + K.t(100, 64, 'Compuesto: tres o más cuentas', { s: 6, b: 1 }) + tabla(K, 20, 70, [92, 34, 34], [['Cuenta', 'Debe', 'Haber'], ['Mercaderías', '1 000', ''], ['   Bancos', '', '400'], ['   Proveedores', '', '600'], ['=Sumas iguales', '1 000', '1 000']], { h: 10, s: 5.6 }) + K.t(100, 128, 'Compra pagada en parte al contado y en parte a crédito', { s: 5.4 }); },
      intro: 'Un asiento es el registro de una operación; puede tener solo dos cuentas o varias.',
      q: [['¿Por qué el segundo asiento es compuesto?', 'Porque tiene tres cuentas: una al Debe y dos al Haber.'], ['¿Qué se escribe con sangría?', 'Las cuentas del Haber, para distinguirlas.'], ['¿Qué falla si el Debe suma 1 000 y el Haber 900?', 'Falta un importe: el asiento está descuadrado.']],
      porque: 'Por compuesto que sea, un asiento vale solo si el Debe y el Haber suman lo mismo.' },
    { id: 'ct_mayor', fam: 'reg', n: 'El libro mayor con saldo',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 14, 'Cuenta: BANCOS  (código 1.1.02)', { s: 6.6, b: 1 }) + tabla(K, 6, 20, [22, 64, 30, 30, 32], [['Fecha', 'Detalle', 'Debe', 'Haber', 'Saldo'], ['01/03', 'Saldo inicial', '', '', '5 000'], ['05/03', 'Depósito de ventas', '1 200', '', '6 200'], ['10/03', 'Cheque a proveedor', '', '2 000', '4 200'], ['20/03', 'Pago de luz', '', '150', '4 050'], ['=31/03', 'Saldo final', '1 200', '2 150', '4 050']], { h: 14, s: 5.4 }) + K.t(100, 122, 'Saldo = anterior + Debe − Haber', { s: 6.4, b: 1 }) + K.t(100, 132, 'Así se ve el saldo después de cada movimiento', { s: 5.6 }); },
      intro: 'El mayor reúne todos los movimientos de una cuenta y calcula su saldo línea por línea.',
      q: [['Comprueba el saldo final.', '5 000 + 1 200 − 2 150 = 4 050.'], ['¿De dónde salen los datos del mayor?', 'Del libro diario: cada línea del asiento se pasa a su cuenta.'], ['¿Qué saldo tendría tras un depósito de 300?', '4 350.']],
      porque: 'El diario ordena por fecha; el mayor ordena por cuenta. Con los dos se sabe qué pasó y cuánto queda.' },
    { id: 'ct_comprobacion', fam: 'reg', n: 'El balance de comprobación',
      d: function (K) { return K.suelo(100, 140, 96) + tabla(K, 18, 12, [84, 40, 40], [['Cuenta', 'Deudor', 'Acreedor'], ['Caja', '2 000', ''], ['Bancos', '4 050', ''], ['Mercaderías', '3 000', ''], ['Proveedores', '', '2 500'], ['Capital', '', '6 000'], ['Ventas', '', '1 200'], ['Gastos generales', '650', ''], ['=Sumas', '9 700', '9 700']], { h: 11, s: 5.6 }) + K.t(100, 124, 'Si las sumas no coinciden, hay un error en los pases', { s: 5.8, b: 1 }) + K.t(100, 134, 'Si coinciden, aún puede haber errores de cuenta', { s: 5.4 }); },
      intro: 'El balance de comprobación lista los saldos de todas las cuentas del mayor y comprueba que el Debe iguala al Haber.',
      q: [['Suma los saldos deudores.', '2 000 + 4 050 + 3 000 + 650 = 9 700.'], ['¿Qué error no detecta?', 'Anotar el importe correcto en una cuenta equivocada del mismo lado.'], ['¿Cuándo se prepara?', 'Antes de los ajustes y de los estados financieros.']],
      porque: 'Que cuadre no prueba que todo esté bien, pero que no cuadre prueba que algo está mal.' },
    G('ct_ajustes', 'reg', 'Los asientos de ajuste', [['Depreciación', 'desgaste de activos'], ['Gastos anticipados', 'seguro pagado por un año'], ['Ingresos anticipados', 'cobrado sin entregar'], ['Gastos acumulados', 'sueldos devengados sin pagar'], ['Ingresos acumulados', 'servicio hecho sin cobrar'], ['Cuentas incobrables', 'clientes que no pagarán'], ['Diferencias de inventario', 'faltantes y mermas'], ['Intereses devengados', 'del préstamo del mes']], 2, 18, 22, 'Se hacen al final del periodo, antes de los estados', 'Los ajustes corrigen las cuentas para que reflejen lo que realmente corresponde al periodo.', [['¿Por qué se ajusta un seguro pagado por un año?', 'Porque solo una parte corresponde a este mes; el resto sigue siendo activo.'], ['¿Qué ajuste reconoce sueldos trabajados y no pagados?', 'Un gasto acumulado: Sueldos al Debe, Sueldos por pagar al Haber.'], ['¿Mueven dinero los ajustes?', 'No: solo reparten ingresos y gastos en el periodo correcto.']], 'Sin ajustes, un mes parecería ganar de más y el siguiente de menos.', { s: 6.6, s2: 5 }),
    { id: 'ct_devengo', fam: 'reg', n: 'Devengo y caja',
      d: function (K) { var M = ['ene', 'feb', 'mar', 'abr', 'may'], s = K.suelo(100, 140, 96) + K.l('M16 70 L184 70', P.tinta, { w: 1.2 }); M.forEach(function (m, i) { var x = 30 + i * 35; s += K.l('M' + x + ' 66 L' + x + ' 74', P.tinta, { w: .8 }) + K.t(x, 84, m, { s: 6, b: 1 }); }); return s + K.r(84, 30, 52, 22, 3, P.verde, { w: .9 }) + K.t(110, 40, 'Servicio hecho', { s: 5.6, b: 1 }) + K.t(110, 48, 'ingreso de marzo', { s: 5 }) + K.l('M100 52 L100 66', P.verdeO, { w: 1 }) + K.r(116, 92, 56, 22, 3, P.amarillo, { w: .9 }) + K.t(144, 102, 'Cobro: abril', { s: 5.6, b: 1 }) + K.t(144, 110, 'entra el dinero', { s: 5 }) + K.l('M135 74 L135 92', P.naranja, { w: 1 }) + K.t(100, 132, 'El ingreso es de marzo aunque el dinero llegue en abril', { s: 5.8, b: 1 }); },
      intro: 'Por el principio del devengo, ingresos y gastos se registran cuando ocurren, no cuando se cobran o pagan.',
      q: [['¿En qué mes se registra el ingreso?', 'En marzo, cuando se hizo el servicio.'], ['¿Qué cuenta se usa en marzo si no se ha cobrado?', 'Cuentas por cobrar (Clientes).'], ['¿Qué se registra en abril?', 'El cobro: sube Caja y baja Clientes. No es un ingreso nuevo.']],
      porque: 'El devengo une cada ingreso con el periodo en que se ganó, para medir bien cada mes.' },
    { id: 'ct_anticipado', fam: 'reg', n: 'Un gasto pagado por adelantado',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.t(100, 14, 'Seguro anual pagado el 1 de enero: $ 1 200', { s: 6.4, b: 1 }); for (var i = 0; i < 12; i++) { var x = 16 + i * 14, us = i < 3; s += K.r(x, 30, 12, 60, 1, us ? P.rojo : P.azul, { w: .6 }) + K.t(x + 6, 98, 'EFMAMJJASOND'.charAt(i), { s: 5.4, b: 1 }); } return s + K.t(37, 62, 'gasto', { s: 5.4, b: 1 }) + K.t(37, 70, '300', { s: 6, b: 1 }) + K.t(121, 62, 'activo: seguro pagado por anticipado', { s: 5.4, b: 1 }) + K.t(121, 70, '900', { s: 6, b: 1 }) + K.t(100, 114, 'Cada mes se pasa $ 100 del activo al gasto', { s: 6.2, b: 1 }) + K.t(100, 126, 'Al 31 de marzo: 3 meses usados, 9 por usar', { s: 5.6 }); },
      intro: 'Lo que se paga por adelantado es un activo y se convierte en gasto mes a mes a medida que se usa.',
      q: [['¿Cuánto gasto corresponde a cada mes?', '1 200 ÷ 12 = 100.'], ['¿Cuánto queda como activo al 30 de junio?', '6 meses por usar: 600.'], ['¿Qué asiento se hace cada mes?', 'Gasto de seguro al Debe 100; Seguro pagado por anticipado al Haber 100.']],
      porque: 'Cargar los 1 200 en enero haría ver enero muy malo y el resto del año demasiado bueno.' },
    { id: 'ct_cierre', fam: 'reg', n: 'El asiento de cierre',
      d: function (K) { return K.suelo(100, 140, 96) + caja(K, 12, 22, 56, 26, P.verde, 'Ventas 10 000', 6) + caja(K, 12, 66, 56, 26, P.rojo, 'Gastos 7 000', 6) + K.flecha(70, 35, 90, 52, P.verdeO, { w: 1.4 }) + K.flecha(70, 79, 90, 64, P.rojoO, { w: 1.4 }) + K.r(92, 42, 50, 32, 3, P.amarillo, { w: 1 }) + K.t(117, 54, 'Resumen de', { s: 5.6, b: 1 }) + K.t(117, 62, 'resultados', { s: 5.6, b: 1 }) + K.t(117, 70, '+3 000', { s: 6, b: 1 }) + K.flecha(144, 58, 160, 58, P.tinta, { w: 1.4 }) + K.r(162, 40, 30, 36, 3, P.azul, { w: 1 }) + K.t(177, 54, 'Patri-', { s: 5.4, b: 1 }) + K.t(177, 62, 'monio', { s: 5.4, b: 1 }) + K.t(177, 70, '+3 000', { s: 5, b: 1 }) + K.t(100, 108, 'Ventas y Gastos quedan en cero', { s: 6.4, b: 1 }) + K.t(100, 120, 'y empiezan de nuevo el año siguiente', { s: 5.8 }); },
      intro: 'Al cerrar el año, las cuentas de ingresos y gastos se cancelan y la utilidad pasa al patrimonio.',
      q: [['¿Cuál es la utilidad del ejercicio?', '10 000 − 7 000 = 3 000.'], ['¿Se cierran también Caja y Bancos?', 'No: las cuentas de balance continúan con su saldo.'], ['¿Qué pasa si los gastos superan a las ventas?', 'Hay pérdida y el patrimonio disminuye.']],
      porque: 'Cerrar las cuentas de resultado permite medir cada año desde cero.' },
    G('ct_errores', 'reg', 'Errores frecuentes y cómo encontrarlos', [['Transposición', '54 escrito como 45: la diferencia es múltiplo de 9'], ['Omisión', 'un documento sin registrar'], ['Duplicado', 'la misma factura dos veces'], ['Cuenta equivocada', 'Caja en lugar de Bancos'], ['Lado equivocado', 'Debe por Haber: la diferencia es el doble'], ['Cifra mal copiada', '1 250 anotado como 1 520']], 2, 14, 30, 'Nunca se borra: se anula con un asiento de corrección', 'Los errores contables dejan pistas en las diferencias que producen.', [['La diferencia es 27. ¿Qué error puede ser?', 'Una transposición, porque 27 es múltiplo de 9.'], ['La diferencia es 400 y hay un importe de 200. ¿Qué pasó?', 'Probablemente se anotó en el lado equivocado.'], ['¿Cómo se corrige un asiento mal hecho?', 'Con un asiento inverso que lo anula y otro correcto.']], 'Conocer el patrón de cada error ahorra horas de revisión.', { s: 6.4, s2: 4.6, gy: 4 }),
    { id: 'ct_mercaderias', fam: 'reg', n: 'Registrar una venta con su costo',
      d: function (K) { return K.suelo(100, 140, 96) + K.t(100, 14, 'Se vende en $ 800 un producto que costó $ 500', { s: 6.2, b: 1 }) + K.t(18, 26, '1) La venta', { s: 5.8, b: 1, a: 'start' }) + tabla(K, 18, 30, [100, 32, 32], [['Caja', '800', ''], ['   Ventas', '', '800']], { h: 10, sinCab: 1, s: 5.6 }) + K.t(18, 62, '2) El costo de lo vendido', { s: 5.8, b: 1, a: 'start' }) + tabla(K, 18, 66, [100, 32, 32], [['Costo de ventas', '500', ''], ['   Inventario de mercaderías', '', '500']], { h: 10, sinCab: 1, s: 5.6 }) + K.r(40, 98, 120, 18, 3, P.amarillo, { w: .9 }) + K.t(100, 110, 'Utilidad bruta = 800 − 500 = 300', { s: 6.8, b: 1 }) + K.t(100, 130, 'Inventario permanente: se descarga en cada venta', { s: 5.6 }); },
      intro: 'Con inventario permanente, cada venta se registra dos veces: el precio cobrado y el costo de lo que salió.',
      q: [['¿Por qué se acredita el inventario por 500 y no por 800?', 'Porque el inventario se lleva al costo, no al precio de venta.'], ['¿Qué cuenta muestra el margen?', 'Ninguna sola: es la diferencia entre Ventas y Costo de ventas.'], ['Si se vende a crédito, ¿qué cambia?', 'Se carga Clientes en lugar de Caja.']],
      porque: 'Registrar el costo en cada venta deja ver al instante cuánto inventario queda y cuánto se gana.' }
  ];
  MO.agregar('conta', L, { nombre: 'Contabilidad', familias: FAM, materias: /^(conta)$/ });
})();
