/* b6_lib_emprendimiento.js — Emprendimiento: modelos 1–18 de 50 (primera entrega; 19–34 en el archivo 2, 35–50 en el 3). Materia `empre`. Prefijo `em_`.
   Cargar después de b6_modelos.js. No repite emp_lienzo, emp_empatia, emp_escenarios, con_*, ec_*, mkt_posicion, mkt_recorrido, rs_calendario ni ia_arbol.
   Importes de ejemplo, sin moneda: valen para cualquier país. Expone window.EU_EMPRE_K (helpers) para los archivos 2 y 3. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('em_problema')) return;
  var P = { azul: '#A8C8E8', azulO: '#2F5F92', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', oro: '#E8C060', morado: '#D0B8E8', moradoO: '#6A4A96', naranja: '#F4C090', naranjaO: '#B8661E', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', piel2: '#C89670', tinta: '#2A2420', blanco: '#FFFFFF', madera: '#C89A62', cesped: '#9CCB7A' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { idea: 'Ideas y oportunidades', cli: 'Cliente y mercado', per: 'La persona emprendedora', mod: 'Modelo de negocio', num: 'Los números del negocio', leg: 'Formalizar el negocio', ven: 'Vender y fidelizar', cre: 'Financiar y crecer' };
  function nf(v, d) { var s = (+v).toFixed(d || 0).split('.'); s[0] = s[0].replace(/\B(?=(\d{3})+(?!\d))/g, ' '); return s.join(',').replace('-', '−'); }
  function ajusta(t, ancho, max) { return +Math.min(max, ancho / (String(t).length * .54)).toFixed(2); }
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var a1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), a2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + a1 * .35, q[0], { s: +a1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +a2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  function caja(K, x, y, w, h, col, t1, t2, o) { o = o || {}; var s = K.r(x, y, w, h, o.r == null ? 4 : o.r, col, { w: .8 }); if (t1) s += K.t(x + w / 2, y + (t2 ? h * .45 : h / 2) + 2, t1, { s: ajusta(t1, w - 4, o.s || 6), b: 1 }); if (t2) s += K.t(x + w / 2, y + h * .78 + 1, t2, { s: ajusta(t2, w - 4, o.s2 || 4.8) }); return s; }
  function per(K, x, y, col, e, piel) { e = e || 1; return K.p('M' + (x - 11 * e) + ' ' + (y + 34 * e) + ' Q' + (x - 11 * e) + ' ' + (y + 12 * e) + ' ' + x + ' ' + (y + 12 * e) + ' Q' + (x + 11 * e) + ' ' + (y + 12 * e) + ' ' + (x + 11 * e) + ' ' + (y + 34 * e) + ' Z', col, { w: .8 }) + K.c(x, y, 8 * e, piel || P.piel, { w: .8 }) + K.c(x - 2.6 * e, y - 1 * e, .8 * e, P.tinta, { negro: 1, w: .2 }) + K.c(x + 2.6 * e, y - 1 * e, .8 * e, P.tinta, { negro: 1, w: .2 }) + K.l('M' + (x - 2.6 * e) + ' ' + (y + 3 * e) + ' Q' + x + ' ' + (y + 5.5 * e) + ' ' + (x + 2.6 * e) + ' ' + (y + 3 * e), P.tinta, { w: .6 }); }
  function barras(K, D, x0, y0, w, h, max, o) { o = o || {}; var n = D.length, bw = w / n * .62, s = K.l('M' + x0 + ' ' + (y0 + h) + ' L' + (x0 + w) + ' ' + (y0 + h), P.tinta, { w: .7 }); D.forEach(function (d, i) { var bh = d[1] / max * h, x = x0 + (i + .5) * w / n - bw / 2; s += K.r(x, y0 + h - bh, bw, bh, 1, d[2] || CO[i % CO.length], { w: .6 }) + K.t(x + bw / 2, y0 + h + 7, d[0], { s: ajusta(d[0], w / n - 1, o.s || 4.8) }) + K.t(x + bw / 2, y0 + h - bh - 2.5, d[3] || nf(d[1]), { s: o.sv || 4.8, b: 1 }); }); return s; }
  window.EU_EMPRE_K = { P: P, CO: CO, FAM: FAM, nf: nf, ajusta: ajusta, G: G, caja: caja, per: per, barras: barras, rejilla: rejilla };

  var L = [
    /* ─────────── IDEAS Y OPORTUNIDADES ─────────── */
    { id: 'em_problema', fam: 'idea', n: 'Problema, solución y cliente',
      d: function (K) { var s = K.suelo(100, 104, 94) + caja(K, 10, 40, 52, 40, P.rojo, 'PROBLEMA', 'algo que molesta') + K.flecha(64, 60, 74, 60, P.tinta, { w: 1.2, p: 3 }) + caja(K, 76, 40, 52, 40, P.verde, 'SOLUCIÓN', 'lo que yo ofrezco') + K.flecha(130, 60, 140, 60, P.tinta, { w: 1.2, p: 3 }) + caja(K, 142, 40, 48, 40, P.amarillo, 'CLIENTE', 'quien paga'); return s + K.t(36, 30, '«No hay pan', { s: 5, a: 'middle' }) + K.t(36, 36, 'caliente a las 7»', { s: 5 }) + K.t(102, 30, 'reparto de pan', { s: 5 }) + K.t(102, 36, 'a domicilio', { s: 5 }) + K.t(166, 30, 'familias que', { s: 5 }) + K.t(166, 36, 'trabajan temprano', { s: 5 }) + K.t(100, 116, 'Un negocio empieza por un problema real de personas reales', { s: 5.4, b: 1 }) + K.t(100, 126, 'Si nadie tiene el problema, nadie pagará la solución', { s: 5.2 }); },
      intro: 'Toda idea de negocio responde a tres preguntas: qué problema resuelve, cómo lo resuelve y quién pagará por ello.',
      q: [['¿Qué problema resuelve una lavandería de barrio?', 'La falta de tiempo o de lavadora en casa.'], ['¿Por qué empezar por el problema y no por el producto?', 'Porque un producto sin problema detrás no tiene clientes.'], ['Escribe un problema de tu barrio y una solución.', 'Respuesta abierta.']],
      porque: 'Las personas no compran productos: compran soluciones a sus problemas.' },
    G('em_fuentes_ideas', 'idea', 'De dónde salen las ideas', [['Lo que me molesta', 'quejas propias y ajenas'], ['Lo que sé hacer', 'oficio, estudio, afición'], ['Lo que cambia', 'tendencias y nuevas leyes'], ['Lo que falta aquí', 'algo que no hay en el barrio'], ['Copiar y mejorar', 'lo que funciona en otro lugar'], ['Unir dos cosas', 'café + libros, taller + curso']], 2, 20, 28, 'Anota cada idea: casi todas salen de observar', 'Las ideas de negocio no caen del cielo: salen de mirar con atención lo que pasa alrededor.', [['¿Qué idea saldría de «en mi barrio no hay dónde arreglar bicis»?', 'Un taller de reparación de bicicletas.'], ['Da un ejemplo de unir dos cosas.', 'Una peluquería con barbería y café.'], ['¿Por qué conviene llevar una libreta de ideas?', 'Porque las buenas ideas se olvidan si no se anotan.']], 'Observar es la primera herramienta de quien emprende.', { s: 7, s2: 5.2 }),
    { id: 'em_ikigai', fam: 'idea', n: 'El punto de encuentro: ikigai',
      d: function (K) { var s = K.suelo(100, 140, 96), C = [[80, 50, P.rosa, 'lo que me gusta', 50, 20], [120, 50, P.azul, 'lo que sé hacer', 150, 20], [80, 86, P.verde, 'lo que la gente', 44, 120], [120, 86, P.amarillo, 'por lo que pagarían', 156, 120]]; C.forEach(function (c) { s += K.c(c[0], c[1], 30, c[2], { w: .9, op: .55 }); }); C.forEach(function (c, i) { s += K.t(c[4], c[5], c[3], { s: 5.4, b: 1 }) + (i === 2 ? K.t(c[4], c[5] + 7, 'necesita', { s: 5.4, b: 1 }) : ''); }); return s + K.c(100, 68, 9, P.blanco, { w: .8 }) + K.t(100, 70, 'idea', { s: 5.6, b: 1 }) + K.t(100, 143, 'Un buen negocio está donde se cruzan los cuatro círculos', { s: 5, b: 1 }); },
      intro: 'El ikigai ayuda a buscar una idea que una lo que te gusta, lo que sabes hacer, lo que se necesita y por lo que pagarían.',
      q: [['¿Qué pasa si solo une «me gusta» y «sé hacerlo»?', 'Es una afición: falta que alguien lo necesite y pague.'], ['Escribe algo en cada círculo.', 'Respuesta personal.'], ['¿Por qué importa «por lo que pagarían»?', 'Porque sin ingresos el negocio no se sostiene.']],
      porque: 'Cuando el trabajo une gusto, habilidad y necesidad, se sostiene mejor en el tiempo.' },
    G('em_scamper', 'idea', 'SCAMPER: mejorar una idea', [['S Sustituir', 'otro material o ingrediente'], ['C Combinar', 'juntar dos productos'], ['A Adaptar', 'traer algo de otro sector'], ['M Modificar', 'tamaño, forma, color'], ['P Poner otro uso', 'nuevo cliente o uso'], ['E Eliminar', 'quitar lo que sobra'], ['R Reordenar', 'cambiar el orden o al revés']], 2, 14, 22, 'Ejemplo: helado + café = afogato (combinar)', 'SCAMPER es una lista de siete preguntas para transformar un producto que ya existe en algo nuevo.', [['¿Qué letra usa la maleta con ruedas?', 'C: combinar maleta y ruedas.'], ['Aplica «eliminar» a un restaurante.', 'Quitar las mesas: solo comida para llevar.'], ['¿Qué significa «poner otro uso»?', 'Usar el producto para algo distinto o para otro cliente.']], 'Muchas innovaciones son pequeños cambios sobre algo que ya existía.', { s: 7, s2: 5.2 }),
    { id: 'em_validar', fam: 'idea', n: 'Validar la idea antes de invertir',
      d: function (K) { var E = [['idea', 'en la cabeza', 176], ['20 entrevistas', '¿tienen el problema?', 148], ['prototipo', 'algo sencillo para probar', 120], ['primeras ventas', '¿pagan de verdad?', 92]], s = K.suelo(100, 140, 96); E.forEach(function (e, i) { var y = 14 + i * 26, w = e[2]; s += K.p('M' + (100 - w / 2) + ' ' + y + ' L' + (100 + w / 2) + ' ' + y + ' L' + (100 + w / 2 - 14) + ' ' + (y + 22) + ' L' + (100 - w / 2 + 14) + ' ' + (y + 22) + ' Z', CO[i], { w: .8 }) + K.t(100, y + 10, e[0], { s: 6, b: 1 }) + K.t(100, y + 18, e[1], { s: 4.8 }); }); return s + K.t(100, 128, 'Cada paso cuesta poco y evita perder mucho', { s: 5.8, b: 1 }) + K.t(100, 137, 'Si falla un paso, se cambia la idea, no se insiste a ciegas', { s: 4.8 }); },
      intro: 'Validar es comprobar con personas reales, paso a paso, que la idea interesa y que pagarán por ella.',
      q: [['¿Por qué hablar con clientes antes de comprar maquinaria?', 'Para no gastar en algo que quizá nadie quiere.'], ['¿Qué es un prototipo?', 'Una primera versión sencilla para probar la idea.'], ['¿Cuál es la mejor prueba de que una idea funciona?', 'Que alguien pague por ella.']],
      porque: 'Equivocarse barato al principio es mucho mejor que equivocarse caro al final.' },
    { id: 'em_pmv', fam: 'idea', n: 'Producto mínimo viable',
      d: function (K) { var s = K.suelo(100, 92, 94), E = [['patinete', 'ya sirve para moverse'], ['bicicleta', 'más rápido'], ['moto', 'motor'], ['coche', 'el producto completo']], X = [26, 74, 124, 172]; s += K.r(16, 76, 20, 3, 1, P.madera, { w: .6 }) + K.c(19, 82, 3.4, P.gris, { w: .6 }) + K.c(33, 82, 3.4, P.gris, { w: .6 }) + K.l('M34 76 L34 56 L28 56', P.grisO, { w: 1.4 }); s += K.c(62, 80, 7, 'none', { w: .1 }) + K.l('M62 80 m-7 0 a7 7 0 1 0 14 0 a7 7 0 1 0 -14 0 M86 80 m-7 0 a7 7 0 1 0 14 0 a7 7 0 1 0 -14 0 M62 80 L72 66 L86 80 M72 66 L82 66 L86 80 M70 62 L76 62', P.azulO, { w: 1.2 }); s += K.c(112, 80, 6, P.gris, { w: .7 }) + K.c(136, 80, 6, P.gris, { w: .7 }) + K.p('M112 74 L120 64 L132 64 L138 74 Z', P.rojo, { w: .8 }) + K.r(118, 70, 12, 6, 2, P.grisO, { w: .5 }); s += K.c(158, 82, 6, P.gris, { w: .7 }) + K.c(186, 82, 6, P.gris, { w: .7 }) + K.p('M150 80 L150 70 L160 70 L166 60 L180 60 L186 70 L194 70 L194 80 Z', P.verde, { w: .8 }); E.forEach(function (e, i) { s += K.t(X[i], 100, e[0], { s: 6, b: 1 }) + K.t(X[i], 108, e[1], { s: ajusta(e[1], 46, 4.8) }); if (i < 3) s += K.flecha(X[i] + 18, 40, X[i + 1] - 18, 40, P.tinta, { w: .8, p: 2.5 }); }); return s + K.t(100, 28, 'Cada versión ya se puede usar y vender', { s: 5.6, b: 1 }) + K.t(100, 126, 'PMV: lo más simple que el cliente pueda usar y pagar', { s: 5.6, b: 1 }) + K.t(100, 136, 'Mejorar con lo que dicen los clientes de cada versión', { s: 5 }); },
      intro: 'El producto mínimo viable es la versión más sencilla que ya resuelve el problema y se puede vender.',
      q: [['¿Por qué no empezar fabricando el coche?', 'Porque se tarda mucho y no se sabe si lo quieren.'], ['¿Cuál sería el PMV de una pastelería?', 'Vender por encargo desde casa a vecinos y amigos.'], ['¿Qué se gana con cada versión?', 'Ingresos y opiniones para mejorar.']],
      porque: 'Lanzar pronto algo sencillo enseña más que planear mucho tiempo algo perfecto.' },
    G('em_tipos', 'idea', 'Tipos de negocio', [['Producto', 'fabrico y vendo: jabones, pan'], ['Servicio', 'hago algo por ti: clases, reparación'], ['Comercio', 'compro y revendo: tienda'], ['En línea', 'vendo por internet'], ['Franquicia', 'uso una marca que ya existe'], ['Social', 'gano dinero y resuelvo un problema social']], 2, 20, 28, 'Cada tipo necesita recursos y habilidades distintas', 'Los negocios se diferencian por lo que ofrecen y por cómo lo hacen llegar al cliente.', [['¿Qué tipo es una academia de idiomas?', 'De servicio.'], ['¿Qué ventaja tiene una franquicia?', 'La marca y el método ya están probados.'], ['¿Qué es una empresa social?', 'Una que busca ganancias y además un impacto positivo en la sociedad.']], 'Elegir el tipo de negocio ayuda a calcular cuánto hace falta para empezar.', { s: 7.4, s2: 5.2 }),
    /* ─────────── CLIENTE Y MERCADO ─────────── */
    { id: 'em_cliente_ideal', fam: 'cli', n: 'Mi cliente ideal',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(10, 14, 180, 110, 6, P.blanco, { w: .9 }) + K.c(46, 54, 28, P.azul, { w: .8, op: .5 }) + per(K, 46, 46, P.amarillo, 1.5, P.piel2) + K.t(46, 98, 'Carmen, 34 años', { s: 6, b: 1 }) + K.t(46, 106, 'madre de dos niños', { s: 4.8 }); [['Qué hace', 'trabaja de 8 a 17 h'], ['Qué le preocupa', 'no tiene tiempo para cocinar'], ['Qué quiere', 'comida sana y rápida'], ['Dónde está', 'redes sociales, colegio, mercado'], ['Cuánto paga', 'hasta 6 por almuerzo']].forEach(function (f, i) { var y = 28 + i * 18; s += K.t(88, y, f[0], { s: 5, b: 1, a: 'start' }) + K.t(88, y + 7.5, f[1], { s: ajusta(f[1], 96, 5.2), a: 'start' }); }); return s + K.t(100, 136, 'Personaje inventado con datos de clientes reales', { s: 5.4, b: 1 }); },
      intro: 'El cliente ideal es un personaje que resume cómo es, qué necesita y dónde encontrar a quien más compraría.',
      q: [['¿Para qué sirve imaginar a Carmen?', 'Para decidir producto, precio y dónde anunciarse pensando en alguien concreto.'], ['¿De dónde salen sus datos?', 'De entrevistas y observación de clientes reales.'], ['Describe el cliente ideal de una tienda de bicis.', 'Respuesta abierta.']],
      porque: 'Quien intenta venderle a todo el mundo no le habla bien a nadie.' },
    { id: 'em_mercado', fam: 'cli', n: 'El tamaño del mercado',
      d: function (K) { var s = K.suelo(70, 132, 60) + K.c(70, 70, 58, P.azul, { w: .9, op: .6 }) + K.c(70, 88, 38, P.verde, { w: .9, op: .8 }) + K.c(70, 106, 18, P.amarillo, { w: .9 }); s += K.t(70, 24, 'TOTAL', { s: 6, b: 1 }) + K.t(70, 32, '20 000 hogares', { s: 4.8 }) + K.t(70, 64, 'ALCANZABLE', { s: 6, b: 1 }) + K.t(70, 72, '4 000 en mi zona', { s: 4.8 }) + K.t(70, 104, 'MI META', { s: 5.4, b: 1 }) + K.t(70, 111, '200', { s: 4.8, b: 1 }); return s + K.t(134, 32, 'Total: todos los que', { s: 5, a: 'start' }) + K.t(134, 40, 'podrían comprar', { s: 5, a: 'start' }) + K.t(134, 60, 'Alcanzable: los que', { s: 5, a: 'start' }) + K.t(134, 68, 'puedo atender', { s: 5, a: 'start' }) + K.t(134, 88, 'Meta: los que espero', { s: 5, a: 'start' }) + K.t(134, 96, 'ganar el primer año', { s: 5, a: 'start' }) + K.t(134, 112, '200 / 4 000 = 5 %', { s: 5.4, b: 1, a: 'start' }) + K.t(100, 142, 'Ser realista con la meta evita comprar de más', { s: 5, b: 1 }); },
      intro: 'Antes de empezar conviene estimar cuántos clientes hay en total, cuántos se pueden atender y cuántos se pueden ganar.',
      q: [['¿Qué porcentaje del mercado alcanzable es la meta?', '200 / 4000 = 5 %.'], ['Si cada hogar gasta 10 al mes, ¿cuánto vende la meta?', '200 · 10 = 2 000 al mes.'], ['¿Por qué no contar con los 20 000 hogares?', 'Porque no se puede llegar a todos ni todos comprarán.']],
      porque: 'Un número de clientes realista es la base de todas las demás cuentas.' },
    { id: 'em_entrevista', fam: 'cli', n: 'Preguntar bien al cliente',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(10, 14, 86, 104, 6, P.rojo, { w: .9, op: .7 }) + K.r(104, 14, 86, 104, 6, P.verde, { w: .9, op: .7 }) + K.t(53, 28, 'EVITAR', { s: 7, b: 1, c: P.rojoO }) + K.t(147, 28, 'MEJOR', { s: 7, b: 1, c: P.verdeO }); ['¿Te gusta mi idea?', '¿Comprarías esto?', '¿Verdad que es útil?', '¿Cuánto pagarías?'].forEach(function (t, i) { s += K.t(53, 46 + i * 18, t, { s: 5.4 }); }); ['¿Cuándo te pasó por última vez?', '¿Cómo lo resuelves hoy?', '¿Cuánto te cuesta ahora?', '¿Qué es lo más molesto?'].forEach(function (t, i) { s += K.t(147, 46 + i * 18, t, { s: ajusta(t, 80, 5.4) }); }); return s + K.t(100, 130, 'Preguntar por hechos pasados, no por opiniones futuras', { s: 5.4, b: 1 }); },
      intro: 'En una entrevista de cliente se pregunta por lo que la persona hace y gasta hoy, no por si le gusta la idea.',
      q: [['¿Por qué «¿te gusta mi idea?» es mala pregunta?', 'Porque por cortesía casi todos dicen que sí.'], ['¿Qué revela «¿cómo lo resuelves hoy?»?', 'La competencia real y cuánto le importa el problema.'], ['¿Cuántas entrevistas conviene hacer?', 'Al menos 15 o 20 para ver patrones.']],
      porque: 'Lo que la gente hace dice más que lo que dice que haría.' },
    { id: 'em_competencia', fam: 'cli', n: 'Comparar con la competencia',
      d: function (K) { var Cc = ['', 'Precio', 'Calidad', 'Cercanía', 'Horario', 'Atención'], F = [['Yo', 2, 3, 3, 3, 3], ['Panadería A', 3, 2, 1, 2, 2], ['Súper B', 3, 1, 2, 3, 1]], s = K.suelo(100, 140, 96); Cc.forEach(function (c, j) { if (j) s += K.t(54 + j * 23, 22, c, { s: 5, b: 1 }); }); F.forEach(function (f, i) { var y = 32 + i * 26; s += K.r(10, y, 180, 22, 3, i ? P.blanco : P.amarillo, { w: .6 }) + K.t(14, y + 13.5, f[0], { s: 5.6, b: 1, a: 'start' }); for (var j = 1; j <= 5; j++) for (var k = 0; k < 3; k++) s += estrella(K, 47 + j * 23 + k * 7, y + 11, 2.8, k < f[j] ? P.oro : P.gris); }); return s + K.t(100, 122, 'Buscar en qué puedo ser claramente mejor', { s: 5.8, b: 1 }) + K.t(100, 132, '3 estrellas = muy bien · 1 = flojo', { s: 5 }); },
      intro: 'Una tabla comparativa muestra en qué destaca cada competidor y dónde está la oportunidad propia.',
      q: [['¿En qué gana «Yo» a los dos competidores?', 'En calidad, cercanía y atención.'], ['¿En qué pierde?', 'En precio.'], ['¿Qué haría con esa información?', 'Destacar la calidad y la atención, no competir por precio.']],
      porque: 'Competir en todo es imposible; hay que elegir en qué ser el mejor.' },
    { id: 'em_encuesta', fam: 'cli', n: 'Leer una encuesta',
      d: function (K) { var D = [['diario', 12, P.verde], ['semanal', 28, P.verde], ['mensual', 34, P.amarillo], ['casi nunca', 18, P.gris], ['nunca', 8, P.rojo]], s = K.suelo(100, 140, 96) + K.t(100, 16, '¿Cada cuánto comprarías pan artesanal? (100 personas)', { s: 5.4, b: 1 }) + barras(K, D.map(function (d) { return [d[0], d[1], d[2], d[1] + ' %']; }), 20, 26, 160, 74, 40, { s: 5, sv: 5.4 }); return s + K.t(100, 122, 'Diario + semanal = 40 %: 40 de cada 100 serían clientes frecuentes', { s: 4.8, b: 1 }) + K.t(100, 132, 'Una encuesta da pistas; las ventas reales lo confirman', { s: 5 }); },
      intro: 'Una encuesta con muchas personas ayuda a estimar cuántas comprarían y con qué frecuencia.',
      q: [['¿Cuántos comprarían al menos cada semana?', '12 + 28 = 40 de 100.'], ['¿Qué porcentaje no compraría nunca?', '8 %.'], ['En un barrio de 2 000 personas, ¿cuántos clientes semanales se esperan?', '40 % de 2000 = 800, como máximo.']],
      porque: 'Los porcentajes convierten opiniones sueltas en números para planificar.' },
    { id: 'em_propuesta', fam: 'cli', n: 'Propuesta de valor',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(12, 22, 80, 80, 4, P.azul, { w: .9, op: .6 }) + K.c(150, 62, 40, P.amarillo, { w: .9, op: .6 }) + K.l('M52 22 L52 102 M12 62 L52 62', P.blanco, { w: 1.6 }) + K.l('M150 22 L150 102', P.blanco, { w: 1.6 }); return s + K.t(52, 16, 'MI PRODUCTO', { s: 6, b: 1 }) + K.t(150, 16, 'MI CLIENTE', { s: 6, b: 1 }) + K.t(32, 40, 'alivia', { s: 5.2, b: 1 }) + K.t(32, 48, 'dolores', { s: 5.2, b: 1 }) + K.t(32, 82, 'crea', { s: 5.2, b: 1 }) + K.t(32, 90, 'alegrías', { s: 5.2, b: 1 }) + K.t(72, 64, 'producto', { s: 5.2, b: 1 }) + K.t(131, 56, 'dolores', { s: 5.2, b: 1 }) + K.t(131, 64, 'lo que le', { s: 4.6 }) + K.t(131, 71, 'molesta', { s: 4.6 }) + K.t(169, 56, 'alegrías', { s: 5.2, b: 1 }) + K.t(169, 64, 'lo que', { s: 4.6 }) + K.t(169, 71, 'desea', { s: 4.6 }) + K.flecha(94, 62, 108, 62, P.tinta, { w: 1.2, p: 3 }) + K.t(100, 118, 'Encajan cuando el producto quita lo que molesta', { s: 5.6, b: 1 }) + K.t(100, 128, 'y da lo que el cliente desea', { s: 5.6, b: 1 }); },
      intro: 'La propuesta de valor explica por qué un cliente elegiría tu producto: qué dolor le quita y qué alegría le da.',
      q: [['¿Qué dolor alivia una guardería con horario largo?', 'No tener con quién dejar a los niños mientras se trabaja.'], ['¿Qué alegría puede crear una heladería artesanal?', 'Sabores únicos y un rato agradable en familia.'], ['Escribe tu propuesta en una frase.', 'Respuesta abierta: «Ayudo a… a… gracias a…».']],
      porque: 'Si no sabes decir por qué te elegirían, el cliente tampoco lo sabrá.' },
    /* ─────────── LA PERSONA EMPRENDEDORA ─────────── */
    G('em_habilidades', 'per', 'Habilidades de quien emprende', [['Iniciativa', 'empezar sin que te lo pidan'], ['Constancia', 'seguir cuando cuesta'], ['Organización', 'tiempo, dinero, tareas'], ['Comunicación', 'explicar y escuchar'], ['Aprender del error', 'probar, fallar, mejorar'], ['Pedir ayuda', 'mentores, redes, familia'], ['Responsabilidad', 'cumplir con clientes y pagos'], ['Creatividad', 'buscar otras soluciones']], 2, 14, 23, 'Todas se aprenden con práctica', 'Emprender exige habilidades personales que se pueden entrenar como cualquier otra.', [['¿Qué habilidad muestra quien prueba otra receta tras un fracaso?', 'Aprender del error y constancia.'], ['¿Por qué es importante pedir ayuda?', 'Porque nadie sabe de todo y otros ya pasaron por lo mismo.'], ['¿Cuál quieres mejorar tú?', 'Respuesta personal.']], 'El negocio crece al ritmo de la persona que lo lleva.', { s: 7, s2: 5.2 }),
    { id: 'em_ciclo', fam: 'per', n: 'Crear, medir y aprender',
      d: function (K) { var s = K.suelo(100, 140, 96), N = [['CREAR', 'algo pequeño', 100, 26, P.azul], ['MEDIR', 'ventas, opiniones', 160, 92, P.amarillo], ['APRENDER', 'qué cambiar', 40, 92, P.verde]]; s += K.flecha(124, 36, 158, 72, P.tinta, { w: 1.4, p: 3.5, curva: [150, 44] }) + K.flecha(138, 104, 62, 104, P.tinta, { w: 1.4, p: 3.5, curva: [100, 122] }) + K.flecha(42, 72, 76, 36, P.tinta, { w: 1.4, p: 3.5, curva: [50, 44] }); N.forEach(function (n) { s += K.c(n[2], n[3], 18, n[4], { w: .9 }) + K.t(n[2], n[3], n[0], { s: ajusta(n[0], 32, 6.4), b: 1 }) + K.t(n[2], n[3] + 8, n[1], { s: ajusta(n[1], 34, 4.6) }); }); return s + K.t(100, 70, 'cuanto más rápido', { s: 5.2, b: 1 }) + K.t(100, 78, 'gira, más se aprende', { s: 5.2, b: 1 }) + K.t(100, 140, 'Ejemplo: probar 3 sabores, ver cuál se vende, quedarse con el mejor', { s: 4.6 }); },
      intro: 'Emprender es repetir un ciclo: crear algo pequeño, medir cómo responde el cliente y aprender qué cambiar.',
      q: [['¿Qué se mide en una feria de comida?', 'Cuántas unidades de cada producto se venden y qué dicen los clientes.'], ['¿Qué hacer con un producto que no se vende?', 'Mejorarlo o sustituirlo por otro.'], ['¿Por qué empezar en pequeño?', 'Para aprender rápido y gastar poco.']],
      porque: 'Los errores pequeños y rápidos son la forma más barata de aprender.' },
    { id: 'em_semana', fam: 'per', n: 'Organizar la semana del negocio',
      d: function (K) { var D = ['L', 'M', 'X', 'J', 'V', 'S'], T = [['producir', P.azul], ['vender', P.verde], ['administrar', P.amarillo], ['descanso', P.gris]], Pl = [[0, 0, 1, 2], [0, 0, 1, 1], [0, 0, 1, 2], [0, 0, 1, 1], [0, 1, 1, 2], [1, 1, 1, 3]], s = K.suelo(100, 140, 96); D.forEach(function (d, i) { var x = 18 + i * 22; s += K.t(x + 9, 18, d, { s: 6, b: 1 }); Pl[i].forEach(function (t, j) { s += K.r(x, 24 + j * 22, 18, 20, 2, T[t][1], { w: .5 }); }); }); s += K.t(10, 37, 'mañana', { s: 4.4, a: 'start' }); T.forEach(function (t, i) { s += K.r(156, 30 + i * 16, 9, 9, 2, t[1], { w: .5 }) + K.t(168, 37 + i * 16, t[0], { s: 5, a: 'start' }); }); return s + K.t(100, 124, 'Bloques fijos para cada tarea: el papeleo también es trabajo', { s: 5, b: 1 }) + K.t(100, 134, 'y el descanso evita quemarse', { s: 5 }); },
      intro: 'Quien emprende hace de todo; repartir la semana en bloques ayuda a no descuidar ninguna tarea.',
      q: [['¿Qué día dedica más tiempo a vender?', 'El sábado.'], ['¿Por qué reservar tiempo para administrar?', 'Para llevar cuentas, pagar y cobrar a tiempo.'], ['Haz el plan de una semana de tu negocio.', 'Respuesta abierta.']],
      porque: 'Lo que no tiene un hueco en la agenda, acaba sin hacerse.' },
    G('em_errores', 'per', 'Errores frecuentes al empezar', [['Gastar antes de vender', 'local y máquinas sin clientes'], ['Mezclar dinero', 'cuenta personal y del negocio'], ['Precio bajo', 'que no cubre los costes'], ['No llevar cuentas', 'no saber si se gana'], ['Hacerlo todo solo', 'sin pedir consejo'], ['Rendirse pronto', 'antes de aprender del cliente']], 2, 20, 28, 'Conocerlos es la mejor forma de evitarlos', 'Muchos negocios cierran por errores conocidos que se pueden prevenir.', [['¿Por qué es un error alquilar local antes de tener clientes?', 'Porque genera un coste fijo sin ingresos asegurados.'], ['¿Qué pasa si el precio no cubre los costes?', 'Cada venta hace perder dinero.'], ['¿Cómo evitar mezclar dinero?', 'Con una cuenta o una caja solo para el negocio.']], 'Aprender de los errores de otros sale más barato que de los propios.', { s: 7, s2: 5.2 })
  ];
  function estrella(K, cx, cy, r, col) { var pt = []; for (var i = 0; i < 10; i++) { var a = -Math.PI / 2 + i * Math.PI / 5, rr = i % 2 ? r * .45 : r; pt.push([cx + Math.cos(a) * rr, cy + Math.sin(a) * rr]); } return K.pl(pt, col, { w: .4 }); }
  window.EU_EMPRE_K.estrella = estrella;
  MO.agregar('empre', L, { nombre: 'Emprendimiento', familias: FAM, materias: /^(empre)$/ });
})();
