/* b6_lib_peluqueria2.js — Peluquería (2/3): cortes, técnicas, color y química. 33 modelos para EU_MODELOS.
   Cargar después de b6_lib_peluqueria.js. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('pe_secciones')) return;
  var M = MO.M;
  var C = { pelo: '#6A4A32', peloC: '#B8864A', rubio: '#E6C27A', piel: '#F0C8A8', pielO: '#C8906A', cromo: '#D5DADF', guia: '#C8323A', tinte: '#6A2A4A', oxid: '#F2F2EA', ok: '#4E9A3A', mal: '#C8323A' };
  function cabeza(K, cx, cy, r, pelo) { var s = K.e(cx, cy + r * .1, r * .78, r * .95, C.piel) + K.e(cx - r * .76, cy + r * .12, r * .1, r * .18, C.pielO); if (pelo !== false) s += K.p('M' + (cx - r * .82) + ' ' + (cy + r * .1) + ' Q' + (cx - r * .9) + ' ' + (cy - r * 1.05) + ' ' + cx + ' ' + (cy - r * 1.02) + ' Q' + (cx + r * .9) + ' ' + (cy - r * 1.05) + ' ' + (cx + r * .82) + ' ' + (cy + r * .1) + ' Q' + (cx + r * .6) + ' ' + (cy - r * .5) + ' ' + cx + ' ' + (cy - r * .55) + ' Q' + (cx - r * .6) + ' ' + (cy - r * .5) + ' ' + (cx - r * .82) + ' ' + (cy + r * .1) + ' Z', pelo || C.pelo); return s; }
  function perfil(K, cx, cy, r, c) { return K.p('M' + (cx + r * .7) + ' ' + (cy - r * .2) + ' Q' + (cx + r * .8) + ' ' + (cy + r * .4) + ' ' + (cx + r * .55) + ' ' + (cy + r * .8) + ' L' + (cx + r * .1) + ' ' + (cy + r * .95) + ' L' + (cx - r * .2) + ' ' + (cy + r * 1.4) + ' L' + (cx - r * .6) + ' ' + (cy + r * 1.4) + ' Q' + (cx - r * .9) + ' ' + (cy + r * .4) + ' ' + (cx - r * .8) + ' ' + (cy - r * .3) + ' Q' + (cx - r * .5) + ' ' + (cy - r) + ' ' + cx + ' ' + (cy - r) + ' Q' + (cx + r * .6) + ' ' + (cy - r * .9) + ' ' + (cx + r * .7) + ' ' + (cy - r * .2) + ' Z', c || C.piel); }

  var L = [
    /* ─────────── CORTES Y TÉCNICAS ─────────── */
    { id: 'pe_secciones', fam: 'cor', n: 'Las cuatro secciones básicas',
      d: function (K) { return K.suelo(100, 140, 60) + K.e(100, 74, 50, 60, C.pelo) + K.l('M100 14 L100 134', '#fff', { w: 2, d: '4 3' }) + K.l('M50 70 Q100 60 150 70', '#fff', { w: 2, d: '4 3' }) + K.t(78, 44, '1', { s: 14, b: 1, c: '#fff' }) + K.t(122, 44, '2', { s: 14, b: 1, c: '#fff' }) + K.t(78, 104, '3', { s: 14, b: 1, c: '#fff' }) + K.t(122, 104, '4', { s: 14, b: 1, c: '#fff' }); },
      rot: [['Raya central', 100, 24, 150, 16], ['De oreja a oreja', 150, 70, 184, 90]],
      intro: 'Una raya central y otra de oreja a oreja dividen la cabeza en cuatro partes de trabajo.',
      q: [['¿Por dónde se empieza a cortar?', 'Normalmente por la nuca, en las secciones 3 y 4.'], ['¿Por qué dividir?', 'Para trabajar con orden y no dejar zonas sin cortar.'], ['¿Qué sujeta cada sección?', 'Una pinza.']],
      porque: 'Trabajar de abajo arriba deja siempre a la vista la guía del mechón anterior.' },
    { id: 'pe_mecha_guia', fam: 'cor', n: 'La mecha guía',
      d: function (K) { var s = K.suelo(100, 132, 80); for (var i = 0; i < 7; i++) s += K.l('M' + (40 + i * 18) + ' 20 L' + (40 + i * 18) + ' ' + (i === 3 ? 90 : 110), i === 3 ? C.guia : C.pelo, { w: i === 3 ? 3.6 : 2.4 }); return s + K.l('M30 90 L170 90', '#555', { w: 1, d: '3 3' }) + K.p('M130 86 L180 80 L180 84 L132 92 Z', C.cromo) + K.t(94, 124, 'Mecha guía', { s: 7.4, b: 1, c: C.guia }); },
      rot: [['Línea de corte', 50, 90, 16, 70]],
      intro: 'El primer mechón cortado marca el largo; los demás se igualan a él.',
      q: [['¿Qué pasa si la guía está mal?', 'Todo el corte sale con el mismo error.'], ['¿Guía fija o móvil?', 'Fija: todo va a un punto; móvil: cada mechón toma parte del anterior.'], ['¿Cómo se ve la guía?', 'Se toma un poco del mechón anterior junto al nuevo.']],
      porque: 'Copiar siempre el mismo largo de referencia da un corte simétrico.' },
    { id: 'pe_elevacion', fam: 'cor', n: 'Elevación: 0°, 45° y 90°',
      d: function (K) { var t = [[0, '0° · Recto', 'Peso'], [45, '45° · Graduado', 'Volumen'], [90, '90° · Capas', 'Ligereza']], s = K.suelo(100, 132, 90); t.forEach(function (q, i) { var x = 36 + i * 64, a = q[0] * Math.PI / 180, ex = x + Math.sin(a) * 36, ey = 100 - Math.cos(a) * 36; s += K.c(x, 60, 18, C.piel) + K.l('M' + x + ' 76 L' + ex + ' ' + (ey + 36 - (i === 0 ? 0 : 36)), C.pelo, { w: 3 }) + K.l('M' + (x - 22) + ' 100 L' + (x + 22) + ' 100', '#888', { d: '2 2' }) + K.t(x, 116, q[1], { s: 6.6, b: 1 }) + K.t(x, 126, q[2], { s: 6 }); }); return s; },
      intro: 'El ángulo al que se levanta el mechón antes de cortar decide el peso o la ligereza.',
      q: [['¿Qué elevación da un bob recto?', '0°.'], ['¿Cuál crea capas?', '90° o más.'], ['¿Qué pasa en 45°?', 'Se crea volumen en la zona de la nuca: corte graduado.']],
      porque: 'Cuanto más se eleva el mechón, más corto queda el pelo de abajo respecto al de arriba.' },
    { id: 'pe_bob', fam: 'cor', n: 'Corte bob',
      d: function (K) { return K.suelo(100, 136, 60) + cabeza(K, 100, 64, 40, false) + K.p('M58 70 Q56 18 100 20 Q144 18 142 70 L144 104 L56 104 Z', C.pelo) + K.e(100, 70, 28, 36, C.piel) + K.l('M56 104 L144 104', C.guia, { w: 1.6, d: '3 2' }); },
      rot: [['Línea recta a la mandíbula', 144, 104, 184, 118]],
      intro: 'Corte recto a la altura de la mandíbula, con todo el pelo al mismo largo por fuera.',
      q: [['¿A qué elevación se corta?', 'A 0°, sin levantar el pelo.'], ['¿Con qué tipo de pelo funciona mejor?', 'Con liso o poco ondulado.'], ['¿Qué variación tiene la nuca más corta?', 'El bob en A o invertido.']],
      porque: 'Cortar sin elevar deja todo el peso en la línea de abajo.' },
    { id: 'pe_capas', fam: 'cor', n: 'Corte en capas',
      d: function (K) { var s = K.suelo(100, 140, 60) + cabeza(K, 100, 60, 40, false); for (var i = 0; i < 4; i++) s += K.p('M' + (58 - i * 2) + ' ' + (40 + i * 18) + ' Q' + (60 - i * 4) + ' ' + (60 + i * 18) + ' ' + (54 - i * 4) + ' ' + (72 + i * 18) + ' L' + (70 - i * 2) + ' ' + (66 + i * 18) + ' Z', i % 2 ? C.pelo : C.peloC) + K.p('M' + (142 + i * 2) + ' ' + (40 + i * 18) + ' Q' + (140 + i * 4) + ' ' + (60 + i * 18) + ' ' + (146 + i * 4) + ' ' + (72 + i * 18) + ' L' + (130 + i * 2) + ' ' + (66 + i * 18) + ' Z', i % 2 ? C.pelo : C.peloC); return s + K.p('M60 44 Q60 16 100 16 Q140 16 140 44 Q120 30 100 30 Q80 30 60 44 Z', C.pelo); },
      intro: 'Mechones de distintos largos que dan movimiento y quitan peso.',
      q: [['¿Qué elevación se usa?', '90° o más.'], ['¿Para qué pelo es bueno?', 'Para pelo grueso o con mucho volumen.'], ['¿Qué pasa en pelo muy fino?', 'Puede quedar sin cuerpo en las puntas.']],
      porque: 'Al subir el mechón para cortar, el pelo de arriba queda más corto que el de abajo.' },
    { id: 'pe_degradado', fam: 'cor', n: 'Degradado (fade)',
      d: function (K) { var s = K.suelo(100, 140, 60) + perfil(K, 100, 66, 44); for (var i = 0; i < 6; i++) s += K.r(60, 30 + i * 10, 60 - i * 4, 10, 0, C.pelo, { op: 1 - i * .16, sin: 1 }); return s + K.t(160, 34, 'n.º 4', { s: 6.6, b: 1 }) + K.t(160, 54, 'n.º 2', { s: 6.6, b: 1 }) + K.t(160, 74, 'n.º 1', { s: 6.6, b: 1 }) + K.t(160, 90, 'Piel', { s: 6.6, b: 1 }) + K.l('M130 30 L150 30 M130 50 L150 50 M126 70 L150 70 M124 86 L150 86', '#888', { d: '2 2' }); },
      intro: 'El pelo pasa de más largo arriba a casi piel en la nuca de forma gradual.',
      q: [['¿Con qué herramienta?', 'Con máquina y distintos peines guía.'], ['¿Cómo se difumina la línea?', 'Cambiando el peine y moviendo la palanca de la máquina.'], ['¿Cada cuánto se repasa?', 'Cada 2-3 semanas.']],
      porque: 'Cambiar poco a poco la altura de corte crea una transición sin saltos.' },
    { id: 'pe_flequillo', fam: 'cor', n: 'Tipos de flequillo',
      d: function (K) { var t = ['Recto', 'Lateral', 'Abierto', 'Micro'], s = K.suelo(100, 134, 90); t.forEach(function (q, i) { var x = 30 + i * 46; s += K.e(x, 70, 18, 24, C.piel) + K.p('M' + (x - 20) + ' 64 Q' + (x - 20) + ' 38 ' + x + ' 38 Q' + (x + 20) + ' 38 ' + (x + 20) + ' 64 Z', C.pelo); if (i === 0) s += K.r(x - 16, 50, 32, 12, 0, C.pelo); if (i === 1) s += K.p('M' + (x - 16) + ' 50 L' + (x + 16) + ' 50 L' + (x + 16) + ' 56 L' + (x - 16) + ' 66 Z', C.pelo); if (i === 2) s += K.p('M' + (x - 16) + ' 50 L' + (x - 4) + ' 62 L' + x + ' 50 L' + (x + 4) + ' 62 L' + (x + 16) + ' 50 Z', C.pelo); if (i === 3) s += K.r(x - 16, 50, 32, 5, 0, C.pelo); s += K.t(x, 112, q, { s: 7, b: 1 }); }); return s; },
      intro: 'El flequillo enmarca la cara; su forma cambia la expresión del corte.',
      q: [['¿Por qué se corta en seco?', 'Al secar sube y puede quedar demasiado corto.'], ['¿Qué flequillo suaviza una frente ancha?', 'El lateral o el abierto.'], ['¿Qué se tiene en cuenta antes de cortarlo?', 'Los remolinos de la zona.']],
      porque: 'Un remolino hace que el pelo salga en otra dirección: el flequillo se levanta.' },
    { id: 'pe_puntas', fam: 'cor', n: 'Sanear las puntas',
      d: function (K) { var s = K.suelo(100, 124, 90); for (var i = 0; i < 6; i++) { var x = 40 + i * 22; s += K.l('M' + x + ' 20 L' + x + ' 96', C.peloC, { w: 2.4 }) + K.l('M' + x + ' 96 l-4 10 M' + x + ' 96 l0 12 M' + x + ' 96 l4 10', C.peloC, { w: 1 }); } return s + K.l('M30 94 L170 94', C.guia, { w: 1.6, d: '4 3' }) + K.t(100, 124, 'Cortar 1-2 cm por encima de la punta abierta', { s: 6.6, b: 1 }); },
      rot: [['Puntas abiertas', 62, 104, 20, 120]],
      intro: 'Las puntas abiertas no se reparan: se cortan antes de que la rotura suba.',
      q: [['¿Cada cuánto se sanean?', 'Cada 8 a 12 semanas.'], ['¿Qué abre las puntas?', 'El calor, el tinte, el cepillado brusco y el roce.'], ['¿Los productos las sellan?', 'Las disimulan un tiempo, pero no las unen.']],
      porque: 'Una punta abierta se sigue abriendo hacia arriba como una cremallera.' },
    { id: 'pe_formas_cara', fam: 'cor', n: 'Formas de la cara',
      d: function (K) { var t = [['Ovalada', 'M0 -26 Q18 -26 18 0 Q18 26 0 28 Q-18 26 -18 0 Q-18 -26 0 -26 Z'], ['Redonda', 'M0 -22 Q22 -22 22 0 Q22 22 0 22 Q-22 22 -22 0 Q-22 -22 0 -22 Z'], ['Cuadrada', 'M-18 -22 L18 -22 L20 18 L-20 18 Z'], ['Alargada', 'M0 -30 Q14 -30 14 0 Q14 30 0 30 Q-14 30 -14 0 Q-14 -30 0 -30 Z'], ['Corazón', 'M-20 -20 L20 -20 Q20 10 0 28 Q-20 10 -20 -20 Z']], s = K.suelo(100, 132, 90); t.forEach(function (q, i) { var x = 22 + i * 39; s += '<g transform="translate(' + x + ' 64)">' + K.p(q[1], C.piel) + '</g>' + K.t(x, 112, q[0], { s: 6.4, b: 1 }); }); return s; },
      intro: 'El corte busca equilibrar la cara: dar altura, anchura o suavizar ángulos.',
      q: [['¿Qué corte alarga una cara redonda?', 'Uno con volumen arriba y largos a los lados.'], ['¿Qué suaviza una cara cuadrada?', 'Ondas y capas alrededor de la mandíbula.'], ['¿Por qué la ovalada admite casi todo?', 'Sus proporciones ya están equilibradas.']],
      porque: 'El volumen del pelo crea una silueta nueva que compensa la forma de la cara.' },
    { id: 'pe_lavado', fam: 'cor', n: 'Lavado en cuatro pasos',
      d: function (K) { var t = ['Mojar', 'Champú', 'Masaje', 'Aclarar'], s = K.suelo(100, 128, 90); t.forEach(function (q, i) { var x = 30 + i * 46; s += K.c(x, 64, 18, C.piel) + K.p('M' + (x - 18) + ' 60 Q' + x + ' 40 ' + (x + 18) + ' 60', C.pelo); if (i === 0 || i === 3) s += K.l('M' + (x - 8) + ' 30 L' + (x - 8) + ' 44 M' + x + ' 28 L' + x + ' 44 M' + (x + 8) + ' 30 L' + (x + 8) + ' 44', '#9CCBE6', { w: 1.6, d: '3 2' }); if (i === 1) s += K.c(x - 6, 46, 4, '#fff') + K.c(x + 4, 44, 5, '#fff') + K.c(x + 10, 50, 3, '#fff'); if (i === 2) s += K.l('M' + (x - 14) + ' 44 q6 -6 12 0 q6 -6 12 0', C.pielO, { w: 1.6 }); s += K.t(x, 100, (i + 1) + ' · ' + q, { s: 6.8, b: 1 }); }); return s; },
      intro: 'Agua templada, champú en la palma, masaje con las yemas y aclarado a fondo.',
      q: [['¿Cuánto champú se usa?', 'Una cantidad del tamaño de una moneda.'], ['¿Por qué se aclara tanto?', 'Los restos de champú apagan el brillo e irritan.'], ['¿Dónde se aplica el acondicionador?', 'De medios a puntas, no en la raíz.']],
      porque: 'El champú une la grasa y la suciedad al agua; el aclarado las arrastra.' },
    /* ─────────── COLOR Y QUÍMICA ─────────── */
    { id: 'pe_rueda_color', fam: 'col', n: 'Rueda de colores y neutralización',
      d: function (K) { var col = ['#E0302E', '#E8702E', '#F0B02E', '#E8D83E', '#8AB83E', '#3E9A5E', '#3E7AB8', '#6A4AA8'], s = K.suelo(100, 138, 70); col.forEach(function (c, i) { var a1 = i * Math.PI / 4 - Math.PI / 2, a2 = a1 + Math.PI / 4; s += K.p('M100 72 L' + (100 + Math.cos(a1) * 56) + ' ' + (72 + Math.sin(a1) * 56) + ' A56 56 0 0 1 ' + (100 + Math.cos(a2) * 56) + ' ' + (72 + Math.sin(a2) * 56) + ' Z', c, { w: .8 }); }); return s + K.c(100, 72, 18, '#FFFFFF') + K.flecha(122, 42, 88, 104, '#222', { w: 1.4 }) + K.t(100, 76, 'Opuestos', { s: 6, b: 1 }); },
      intro: 'Los colores opuestos de la rueda se anulan: el violeta quita el amarillo y el verde quita el rojo.',
      q: [['¿Qué color neutraliza el naranja?', 'El azul.'], ['¿Por qué los champús «matizadores» son violetas?', 'Quitan el tono amarillo del rubio.'], ['¿Qué se usa para un castaño muy rojizo?', 'Un tinte con reflejo verde o ceniza.']],
      porque: 'Dos colores complementarios juntos absorben casi toda la luz y se ven neutros.' },
    { id: 'pe_niveles', fam: 'col', n: 'Niveles de tono del 1 al 10',
      d: function (K) { var col = ['#141010', '#241A14', '#3A281C', '#4E3422', '#6A4A2E', '#8A6440', '#A8804E', '#C8A060', '#DCBE82', '#EEDCB0'], n = ['Negro', 'Castaño muy oscuro', '', 'Castaño', '', 'Rubio oscuro', '', 'Rubio claro', '', 'Rubio platino'], s = K.suelo(100, 132, 90); col.forEach(function (c, i) { s += K.r(12 + i * 18, 40, 16, 60, 0, c) + K.t(20 + i * 18, 110, String(i + 1), { s: 8, b: 1 }); }); return s + K.t(20, 30, '1 Negro', { s: 6.4, b: 1, a: 'start' }) + K.t(186, 30, '10 Rubio platino', { s: 6.4, b: 1, a: 'end' }) + K.t(100, 128, 'Nivel = lo claro u oscuro, sin reflejo', { s: 6.6, b: 1 }); },
      intro: 'El nivel mide lo claro u oscuro que es el pelo, del 1 negro al 10 rubio muy claro.',
      q: [['¿Qué significa el primer número de un tinte 7.3?', 'El nivel: rubio medio.'], ['¿Y el número tras el punto?', 'El reflejo: 3 es dorado.'], ['¿Un tinte aclara un tinte?', 'No: color sobre color no aclara; hace falta decolorar.']],
      porque: 'El nivel depende de cuánta melanina queda en el córtex.' },
    { id: 'pe_reflejos', fam: 'col', n: 'Reflejos del tinte',
      d: function (K) { var t = [['.1 Ceniza', '#8A8E94'], ['.2 Irisado', '#9A7A9A'], ['.3 Dorado', '#C8A050'], ['.4 Cobrizo', '#B8602E'], ['.5 Caoba', '#8A2E3A'], ['.6 Rojo', '#A81E2E']], s = K.suelo(100, 128, 90); t.forEach(function (q, i) { var x = 22 + i * 31; s += K.r(x - 12, 36, 24, 60, 12, q[1]) + K.t(x, 108, q[0].split(' ')[0], { s: 7.4, b: 1 }) + K.t(x, 118, q[0].split(' ')[1], { s: 6 }); }); return s; },
      intro: 'El reflejo es el matiz que acompaña al nivel: frío (ceniza, irisado) o cálido (dorado, cobrizo, rojo).',
      q: [['¿Qué reflejo corrige un rubio amarillento?', 'El ceniza o el irisado.'], ['¿Qué significa 6.43?', 'Rubio oscuro cobrizo dorado.'], ['¿Qué reflejo dura menos?', 'El rojo, porque sus pigmentos son más grandes y salen antes.']],
      porque: 'Cada reflejo añade un pigmento de color que se suma al tono de base.' },
    { id: 'pe_oxidante', fam: 'col', n: 'Oxidante: volúmenes',
      d: function (K) { var t = [['10 vol · 3 %', 'Depositar color', 30], ['20 vol · 6 %', 'Cubrir canas, aclarar 1', 55], ['30 vol · 9 %', 'Aclarar 2-3 tonos', 80], ['40 vol · 12 %', 'Aclarar 3-4 tonos', 100]], s = K.suelo(100, 132, 90); t.forEach(function (q, i) { var x = 30 + i * 46; s += K.cil(x, 40, 14, 70, C.oxid) + K.r(x - 13, 110 - q[2] * .6, 26, q[2] * .6, 0, '#9CCBE6', { op: .6 }) + K.t(x, 122, q[0], { s: 5.8, b: 1 }) + K.t(x, 132, q[1], { s: 5 }); }); return s; },
      intro: 'El agua oxigenada abre la cutícula y aclara el pigmento natural: más volumen, más aclarado.',
      q: [['¿Qué volumen para cubrir canas?', '20 volúmenes.'], ['¿Por qué 40 vol puede irritar?', 'Es muy fuerte y la reacción da calor.'], ['¿Qué proporción suele llevar un tinte?', '1 parte de tinte por 1 o 1,5 de oxidante.']],
      porque: 'El peróxido libera oxígeno que rompe la melanina y ayuda a formar el nuevo color.' },
    { id: 'pe_como_tine', fam: 'col', n: 'Cómo actúa un tinte permanente',
      d: function (K) { var t = [['1 · El amoníaco abre la cutícula', 0], ['2 · Entran los precursores', 1], ['3 · El oxígeno los une y crecen', 2]], s = K.suelo(100, 132, 90); t.forEach(function (q, i) { var x = 36 + i * 64; s += K.r(x - 18, 30, 36, 70, 0, '#C8905A'); for (var j = 0; j < 5; j++) s += K.p('M' + (x - 18) + ' ' + (34 + j * 13) + ' l' + (i ? 12 : 4) + ' -4 l0 6 Z', '#E8C890'); if (i >= 1) for (var k = 0; k < 6; k++) s += K.c(x - 8 + (k % 3) * 8, 50 + Math.floor(k / 3) * 22, i === 2 ? 4.4 : 2, C.tinte); s += K.t(x, 114, q[0].split(' · ')[0], { s: 8, b: 1 }) + K.t(x, 124, q[0].split(' · ')[1], { s: 5.4 }); }); return s; },
      intro: 'Moléculas pequeñas entran en el córtex y se unen dentro: quedan atrapadas y el color dura.',
      q: [['¿Por qué no sale con el lavado?', 'Las moléculas unidas son más grandes que la abertura de la cutícula.'], ['¿Qué hace el amoníaco?', 'Hincha el pelo y abre la cutícula.'], ['¿Cuánto tiempo de exposición?', 'Normalmente entre 30 y 45 minutos.']],
      porque: 'Los precursores entran pequeños y, al oxidarse, se unen en moléculas grandes que no salen.' },
    { id: 'pe_decoloracion', fam: 'col', n: 'Fases de la decoloración',
      d: function (K) { var col = [['#3A281C', 'Castaño'], ['#7A3A1E', 'Rojo'], ['#B8602E', 'Naranja'], ['#D89040', 'Naranja claro'], ['#E8C050', 'Amarillo'], ['#F0DC90', 'Amarillo pálido'], ['#F6ECC8', 'Platino']], s = K.suelo(100, 128, 90); col.forEach(function (c, i) { var x = 20 + i * 27; s += K.r(x - 11, 40, 22, 60, 11, c[0]); }); s += K.flecha(20, 30, 182, 30, '#555') + K.t(100, 24, 'Tiempo y fuerza del decolorante', { s: 6.6, b: 1 }); return s + K.t(20, 114, 'Castaño', { s: 6.4, b: 1 }) + K.t(74, 114, 'Naranja', { s: 6.4, b: 1 }) + K.t(128, 114, 'Amarillo', { s: 6.4, b: 1 }) + K.t(182, 114, 'Platino', { s: 6.4, b: 1 }); },
      intro: 'Al decolorar, el pelo oscuro pasa por rojo, naranja y amarillo antes de llegar a platino.',
      q: [['¿Por qué sale naranja?', 'El pigmento rojo-naranja es el más difícil de romper.'], ['¿Qué se hace con el amarillo final?', 'Se matiza con un tono violeta.'], ['¿Se puede decolorar en una sola sesión un pelo negro a platino?', 'Suele necesitar varias sesiones para no romperlo.']],
      porque: 'La melanina oscura se rompe primero; los pigmentos cálidos resisten más.' },
    { id: 'pe_prueba_alergia', fam: 'col', n: 'Prueba de alergia',
      d: function (K) { return K.suelo(100, 130, 80) + K.p('M20 60 Q60 50 120 60 Q150 66 160 90 L150 110 Q110 96 20 100 Z', C.piel) + K.e(136, 76, 10, 7, C.tinte) + K.t(136, 64, 'Tinte', { s: 6.6, b: 1 }) + K.t(90, 124, 'Detrás de la oreja o en el codo · esperar 48 h', { s: 6.6, b: 1 }) + K.r(20, 14, 160, 30, 3, '#FFF4E0') + K.t(100, 26, 'Si aparece picor, rojez o hinchazón:', { s: 6.6, b: 1, c: C.mal }) + K.t(100, 37, 'NO se aplica el tinte', { s: 7, b: 1, c: C.mal }); },
      intro: 'Se aplica un poco de tinte en la piel 48 horas antes para comprobar que no hay reacción.',
      q: [['¿Por qué 48 horas?', 'Las reacciones alérgicas al tinte pueden tardar en aparecer.'], ['¿Qué ingrediente causa más alergias?', 'La parafenilendiamina (PPD).'], ['¿Se repite cada vez?', 'Sí, antes de cada coloración.']],
      porque: 'Una alergia puede aparecer aunque antes no la hubiera: el sistema inmune se sensibiliza.' },
    { id: 'pe_ph', fam: 'col', n: 'pH del pelo y de los productos',
      d: function (K) { var col = ['#C8323A', '#E0602E', '#E9A02E', '#E9C92E', '#B8C82E', '#6EAA3A', '#3A9A5A', '#2E8A8A', '#2E6AAA', '#3A4AAA', '#5A3A9A', '#6A2A8A'], s = K.suelo(100, 128, 90); col.forEach(function (c, i) { s += K.r(10 + i * 15, 50, 15, 16, 0, c) + K.t(17.5 + i * 15, 76, String(i + 2), { s: 6 }); }); return s + K.l('M40 46 L40 34', '#333') + K.t(40, 30, 'Pelo 4,5-5,5', { s: 6.4, b: 1 }) + K.l('M100 46 L100 34', '#333') + K.t(100, 30, 'Champú 5-7', { s: 6.4, b: 1 }) + K.l('M152 46 L152 34', '#333') + K.t(152, 30, 'Tinte 9-11', { s: 6.4, b: 1 }) + K.t(100, 100, 'Ácido cierra la cutícula · alcalino la abre', { s: 7, b: 1 }); },
      intro: 'El pelo es ligeramente ácido; los productos alcalinos lo abren y los ácidos lo cierran.',
      q: [['¿Por qué se usa acondicionador ácido tras el tinte?', 'Cierra la cutícula y fija el color.'], ['¿Qué pH tiene el pelo sano?', 'Entre 4,5 y 5,5.'], ['¿Qué producto es más alcalino?', 'El tinte o el alisado químico.']],
      porque: 'Un pH alto hincha la fibra y separa las escamas; un pH bajo las vuelve a asentar.' },
    { id: 'pe_mechas', fam: 'col', n: 'Mechas con papel',
      d: function (K) { var s = K.suelo(100, 132, 80) + K.e(100, 74, 50, 56, C.pelo); for (var i = 0; i < 5; i++) s += K.r(56 + i * 18, 38 + (i % 2) * 8, 16, 40, 1, '#D8DCE0'); for (var j = 0; j < 5; j++) s += K.l('M' + (64 + j * 18) + ' ' + (78 + (j % 2) * 8) + ' L' + (64 + j * 18) + ' 120', C.rubio, { w: 2.4 }); return s; },
      rot: [['Papel de aluminio', 74, 50, 30, 30], ['Mecha aclarada', 82, 110, 30, 130]],
      intro: 'Se aclaran mechones finos envueltos en papel: el resto del pelo no se toca.',
      q: [['¿Para qué sirve el papel?', 'Separa la mecha y mantiene el calor y la humedad del producto.'], ['¿Qué es el balayage?', 'Mechas pintadas a mano alzada, sin papel.'], ['¿Qué ventaja tienen las mechas?', 'El crecimiento se nota menos que en un tinte completo.']],
      porque: 'Aislar el mechón concentra el aclarado solo donde se quiere.' },
    { id: 'pe_permanente', fam: 'col', n: 'Permanente: enlaces del pelo',
      d: function (K) { var t = [['Pelo liso', 0], ['Reductor rompe', 1], ['Neutralizante une', 2]], s = K.suelo(100, 132, 90); t.forEach(function (q, i) { var x = 36 + i * 64; s += K.l('M' + (x - 12) + ' 30 ' + (i === 2 ? 'q12 10 0 20 q-12 10 0 20 q12 10 0 20' : 'L' + (x - 12) + ' 90'), C.peloC, { w: 3 }) + K.l('M' + (x + 12) + ' 30 ' + (i === 2 ? 'q12 10 0 20 q-12 10 0 20 q12 10 0 20' : 'L' + (x + 12) + ' 90'), C.peloC, { w: 3 }); for (var j = 0; j < 4; j++) s += i === 1 ? K.l('M' + (x - 10) + ' ' + (40 + j * 14) + ' l6 0 M' + (x + 4) + ' ' + (40 + j * 14) + ' l6 0', '#C8A020', { w: 2 }) : K.l('M' + (x - 10 + (i === 2 ? (j % 2 ? 6 : -2) : 0)) + ' ' + (40 + j * 14) + ' l20 0', '#C8A020', { w: 2 }); s += K.t(x, 110, q[0], { s: 6.6, b: 1 }); }); return s + K.t(100, 128, 'Puentes de azufre (disulfuro)', { s: 6.6, b: 1 }); },
      intro: 'Un producto rompe los puentes de azufre del pelo; en el rulo se vuelven a unir en la nueva forma.',
      q: [['¿Qué hace el líquido reductor?', 'Rompe los enlaces de azufre.'], ['¿Y el neutralizante?', 'Los vuelve a unir con la forma del rulo.'], ['¿Por qué no se lava el pelo en 48 horas?', 'Los enlaces terminan de estabilizarse.']],
      porque: 'Los puentes de disulfuro dan la forma permanente al pelo; al rehacerlos, cambia la forma.' },
    { id: 'pe_alisado', fam: 'col', n: 'Alisado con keratina',
      d: function (K) { var s = K.suelo(100, 128, 90), d = 'M40 30'; for (var i = 0; i < 6; i++) d += ' q10 5 0 10 q-10 5 0 10'; s += K.l(d, C.pelo, { w: 2.4 }) + K.l(d.replace('M40', 'M50'), C.pelo, { w: 2.4 }) + K.t(45, 150 - 16, 'Antes', { s: 6.8, b: 1 }) + K.flecha(76, 80, 104, 80, '#555'); s += K.p('M110 50 L180 44 L182 50 L112 56 Z', '#2E2E32') + K.p('M110 62 L180 68 L182 62 L112 56 Z', '#2E2E32') + K.l('M130 30 L130 120 M140 30 L140 120 M150 30 L150 120', C.pelo, { w: 2.4 }); return s + K.t(146, 134, 'Plancha a 200-230 °C', { s: 6.8, b: 1 }); },
      intro: 'Producto con proteína que se sella con plancha: reduce el encrespado durante meses.',
      q: [['¿Qué se revisa en la etiqueta?', 'Que no contenga formol ni libere formaldehído.'], ['¿Por qué se ventila el local?', 'El calor desprende vapores irritantes.'], ['¿Cuánto dura?', 'Entre 3 y 5 meses.']],
      porque: 'El calor fija una capa de proteína que rellena la cutícula y la mantiene lisa.' },
    { id: 'pe_canas', fam: 'col', n: 'Cubrir canas',
      d: function (K) { var s = K.suelo(100, 128, 90); for (var i = 0; i < 10; i++) s += K.l('M' + (20 + i * 7) + ' 30 L' + (20 + i * 7) + ' 100', i % 3 ? C.pelo : '#E8E4DC', { w: 2.4 }); s += K.t(52, 116, 'Con 30 % de canas', { s: 6.6, b: 1 }) + K.flecha(96, 64, 114, 64, '#555'); for (var j = 0; j < 10; j++) s += K.l('M' + (120 + j * 7) + ' 30 L' + (120 + j * 7) + ' 100', '#5A3A24', { w: 2.4 }); return s + K.t(152, 116, 'Tinte + 20 vol', { s: 6.6, b: 1 }); },
      intro: 'La cana no tiene pigmento y es más resistente: necesita tinte con más base natural.',
      q: [['¿Qué oxidante se usa para canas?', '20 volúmenes.'], ['¿Por qué se mezcla con un tono natural?', 'Las canas necesitan una base de pigmento neutro.'], ['¿Cada cuánto se retoca la raíz?', 'Cada 4 a 6 semanas.']],
      porque: 'Sin melanina de fondo, el reflejo del tinte se vería demasiado intenso sin una base natural.' },
    { id: 'pe_temporal', fam: 'col', n: 'Color temporal, semi y permanente',
      d: function (K) { var t = [['Temporal', 1, 'Sale en 1 lavado'], ['Semipermanente', 2, '6-8 lavados'], ['Permanente', 3, 'Crece, no sale']], s = K.suelo(100, 132, 90); t.forEach(function (q, i) { var x = 36 + i * 64; s += K.r(x - 18, 30, 36, 70, 0, '#C8905A') + K.r(x - 18, 30, 6, 70, 0, '#E8C890'); if (q[1] === 1) s += K.r(x - 24, 30, 6, 70, 0, C.tinte, { op: .8 }); if (q[1] >= 2) for (var j = 0; j < 5; j++) s += K.c(x - 6 + (q[1] === 3 ? (j % 2) * 10 : 0), 40 + j * 12, q[1] === 3 ? 3.4 : 2.4, C.tinte); s += K.t(x, 114, q[0], { s: 6.8, b: 1 }) + K.t(x, 124, q[2], { s: 5.8 }); }); return s; },
      intro: 'Cuanto más profundo entra el pigmento, más dura el color.',
      q: [['¿Cuál no lleva oxidante?', 'El temporal y la mayoría de los semipermanentes.'], ['¿Cuál aclara?', 'Solo el permanente, con oxidante.'], ['¿Cuál es más suave con el pelo?', 'El temporal.']],
      porque: 'El temporal se queda fuera de la cutícula; el permanente se forma dentro del córtex.' },
    { id: 'pe_tiempo_exposicion', fam: 'col', n: 'Tiempo de exposición',
      d: function (K) { var s = K.suelo(100, 132, 90) + K.c(70, 70, 40, '#FFFFFF') + K.c(70, 70, 36, '#F4F0E8'); for (var i = 0; i < 12; i++) { var a = i * Math.PI / 6; s += K.l('M' + (70 + Math.cos(a) * 30) + ' ' + (70 + Math.sin(a) * 30) + ' L' + (70 + Math.cos(a) * 34) + ' ' + (70 + Math.sin(a) * 34), '#333', { w: 1.4 }); } s += K.p('M70 70 L70 34 A36 36 0 1 1 42 92 Z', C.tinte, { op: .35 }) + K.l('M70 70 L70 40 M70 70 L46 86', '#222', { w: 2 }); return s + K.t(150, 50, 'Tinte: 30-45 min', { s: 7, b: 1 }) + K.t(150, 66, 'Decoloración: vigilar', { s: 7, b: 1 }) + K.t(150, 82, 'cada 10 min', { s: 7, b: 1 }) + K.t(150, 98, 'Desde el último mechón', { s: 6.4 }); },
      intro: 'El tiempo se cuenta desde que se aplica el producto en el último mechón.',
      q: [['¿Qué pasa si se retira antes?', 'El color queda claro o no cubre.'], ['¿Y si se deja de más?', 'El pelo se daña; el color permanente apenas cambia.'], ['¿Por qué se vigila la decoloración?', 'Actúa rápido y puede romper el pelo.']],
      porque: 'La reacción química necesita tiempo para completarse; después solo daña.' },
    { id: 'pe_raiz_medios', fam: 'col', n: 'Aplicar: raíz, medios y puntas',
      d: function (K) { return K.suelo(100, 132, 80) + K.r(84, 16, 32, 110, 2, C.peloC) + K.r(84, 16, 32, 20, 0, '#C8505A', { op: .6 }) + K.r(84, 36, 32, 50, 0, '#E0A04A', { op: .5 }) + K.r(84, 86, 32, 40, 0, '#E8D080', { op: .5 }) + K.t(124, 28, 'Raíz: calor de la cabeza, sube rápido', { s: 6.2, a: 'start' }) + K.t(124, 62, 'Medios', { s: 6.6, b: 1, a: 'start' }) + K.t(124, 106, 'Puntas: más porosas', { s: 6.6, b: 1, a: 'start' }) + K.t(76, 28, '3.º', { s: 8, b: 1, a: 'end' }) + K.t(76, 62, '1.º', { s: 8, b: 1, a: 'end' }) + K.t(76, 106, '2.º', { s: 8, b: 1, a: 'end' }); },
      intro: 'En un primer tinte se empieza por medios y puntas y se termina en la raíz.',
      q: [['¿Por qué la raíz va al final?', 'El calor de la cabeza acelera el color y quedaría más clara.'], ['¿Y en un retoque de raíz?', 'Solo la raíz, y los últimos minutos se emulsiona hacia puntas.'], ['¿Por qué las puntas cogen más color?', 'Son más porosas.']],
      porque: 'El calor del cuero cabelludo acelera la reacción: la raíz necesita menos tiempo.' }
  ];
  MO.agregar('pelu', L);
})();
