/* b6_lib_batidos3.js — Batidos (3/3): batidos por objetivo, nutrición y ciencia, medida, costes y conservación. 34 modelos.
   Cargar después de b6_lib_batidos2.js. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('bt_hidratante')) return;
  var M = MO.M;
  var C = { verde: '#7FB548', rosa: '#E86A8A', naranja: '#F29A3A', amarillo: '#F2C94B', dorado: '#E6A92A', choco: '#6A3E26', rojo: '#D2453E', morado: '#6A3A7A', azul: '#4F8FC0', ok: '#4E9A3A', mal: '#C8323A', papel: '#FFFDF4', sandia: '#E8586A' };
  function vaso(K, x, y, w, h, c, o) {
    o = o || {}; var s = K.suelo(x, y + h + 2, w * .7) + K.p('M' + (x - w / 2) + ' ' + y + ' L' + (x - w * .38) + ' ' + (y + h) + ' L' + (x + w * .38) + ' ' + (y + h) + ' L' + (x + w / 2) + ' ' + y + ' Z', M.vidrio, { op: .7 });
    s += K.p('M' + (x - w * .47) + ' ' + (y + h * .1) + ' L' + (x - w * .38) + ' ' + (y + h - 2) + ' L' + (x + w * .38) + ' ' + (y + h - 2) + ' L' + (x + w * .47) + ' ' + (y + h * .1) + ' Z', c) + K.e(x, y + h * .1, w * .47, 3, K.claro(c, .2));
    if (o.pajita !== false) s += K.l('M' + (x + w * .1) + ' ' + (y + h * .5) + ' L' + (x + w * .32) + ' ' + (y - 22), o.pc || '#E8E0D0', { w: 3.4 });
    return s + K.brillo(x - w * .3, y + h * .5, 2, h * .3);
  }
  function tabla(K, x, y, filas, w) { var s = ''; filas.forEach(function (f, i) { s += K.t(x, y + i * 11, f[0], { s: 6.6, a: 'start' }) + K.t(x + w, y + i * 11, f[1], { s: 6.6, b: 1, a: 'end' }); }); return s; }
  function barras(K, datos, x0, y0, w, h, max, uni) { y0 -= 16; h -= 14; var s = '', bw = w / datos.length; datos.forEach(function (d, i) { var hh = d[1] / max * h, x = x0 + i * bw, cx = x + bw / 2; s += K.r(x + bw * .15, y0 - hh, bw * .7, hh, 1, d[2]) + K.t(cx, y0 - hh - 3, d[1] + (uni || ''), { s: 5.8, b: 1 }) + '<g transform="rotate(-38 ' + cx + ' ' + (y0 + 5) + ')">' + K.t(cx + 2, y0 + 7, d[0], { s: 5.8, b: 1, a: 'end' }) + '</g>'; }); return s + K.l('M' + x0 + ' ' + y0 + ' L' + (x0 + w) + ' ' + y0, '#555'); }

  var L = [
    /* ─────────── BATIDOS POR OBJETIVO ─────────── */
    { id: 'bt_hidratante', fam: 'rec', n: 'Batido hidratante',
      d: function (K) { return vaso(K, 60, 44, 56, 80, C.sandia) + tabla(K, 104, 42, [['Sandía', '250 g'], ['Pepino', '½'], ['Lima', '½'], ['Menta', '6 hojas'], ['Hielo', 'al gusto']], 84) + K.t(146, 110, '≈ 90 % agua', { s: 7, b: 1 }); },
      intro: 'Frutas y verduras con mucha agua para los días de calor o después de sudar.',
      q: [['¿Por qué no lleva líquido añadido?', 'La sandía y el pepino ya son casi todo agua.'], ['¿Qué aporta la lima?', 'Acidez que refresca y vitamina C.'], ['¿Cuándo conviene?', 'En verano y tras hacer ejercicio suave.']],
      porque: 'Beber alimentos con agua y algo de sales hidrata tanto como un vaso de agua.' },
    { id: 'bt_chocolate', fam: 'rec', n: 'Batido de chocolate sin azúcar',
      d: function (K) { return vaso(K, 60, 44, 56, 80, C.choco) + tabla(K, 104, 42, [['Plátano congelado', '1'], ['Cacao puro', '1 cda'], ['Leche o bebida', '250 ml'], ['Dátil', '1'], ['Canela', 'pizca']], 84); },
      intro: 'Sabor a chocolate con el dulzor del plátano y el dátil, sin azúcar añadido.',
      q: [['¿Qué endulza?', 'El plátano maduro y el dátil.'], ['¿Qué diferencia hay con un batido de cacao soluble?', 'El soluble puede llevar 15 g de azúcar por vaso.'], ['¿Qué le da textura de helado?', 'El plátano congelado.']],
      porque: 'El cacao puro aporta sabor sin azúcar; el plátano congelado, cremosidad y dulzor.' },
    { id: 'bt_dorado', fam: 'rec', n: 'Batido dorado de cúrcuma',
      d: function (K) { return vaso(K, 60, 44, 56, 80, C.dorado) + tabla(K, 104, 42, [['Mango', '100 g'], ['Zanahoria', '½'], ['Cúrcuma', '½ cdta'], ['Pimienta negra', 'pizca'], ['Bebida de coco', '200 ml']], 84); },
      intro: 'Mango, zanahoria y cúrcuma con pimienta y un poco de grasa para absorberla.',
      q: [['¿Por qué lleva pimienta?', 'La piperina ayuda a absorber la curcumina.'], ['¿Qué aporta la bebida de coco?', 'Grasa que disuelve la curcumina y el betacaroteno.'], ['¿Por qué mancha tanto?', 'La cúrcuma es un pigmento muy intenso.']],
      porque: 'Tres ingredientes naranjas o amarillos comparten pigmentos solubles en grasa.' },
    { id: 'bt_vitamina_c', fam: 'rec', n: 'Batido rico en vitamina C',
      d: function (K) { return vaso(K, 60, 44, 56, 80, '#F2B84A') + tabla(K, 104, 36, [['Naranja entera', '1'], ['Kiwi', '1'], ['Guayaba', '½'], ['Fresas', '5'], ['Agua', '100 ml']], 84) + K.r(104, 96, 84, 22, 2, '#FFF4DC') + K.t(146, 110, '≈ 250 mg vitamina C', { s: 6.8, b: 1 }); },
      intro: 'Cuatro frutas con mucha vitamina C en un vaso: más del triple de lo que se necesita al día.',
      q: [['¿Cuánta vitamina C necesita un adulto al día?', 'Entre 75 y 90 mg.'], ['¿Por qué se toma recién hecho?', 'La vitamina C se pierde con el aire y la luz.'], ['¿El exceso se acumula?', 'No: se elimina por la orina.']],
      porque: 'La vitamina C es soluble en agua: el cuerpo no la almacena y hay que tomarla cada día.' },
    { id: 'bt_otono', fam: 'rec', n: 'Batido de otoño',
      d: function (K) { return vaso(K, 60, 44, 56, 80, '#C8783E') + tabla(K, 104, 42, [['Pera', '1'], ['Calabaza asada', '80 g'], ['Avena', '20 g'], ['Leche', '200 ml'], ['Canela y nuez moscada', 'pizca']], 84); },
      intro: 'Fruta y verdura de temporada con especias cálidas: sabe a postre sin azúcar.',
      q: [['¿Por qué la calabaza asada?', 'Asada es más dulce y se tritura sin grumos.'], ['¿Qué fruta de otoño se puede cambiar por la pera?', 'Manzana, caqui o granada.'], ['¿Por qué usar fruta de temporada?', 'Es más barata, sabrosa y cercana.']],
      porque: 'Al asar, el almidón de la calabaza se convierte en azúcares y se carameliza.' },
    /* ─────────── NUTRICIÓN Y CIENCIA ─────────── */
    { id: 'bt_estructura', fam: 'nut', n: 'Estructura de un batido equilibrado',
      d: function (K) { var cap = [['Extra: especias, semillas', '#C8A070', 10], ['Grasa buena', '#6E9A4E', 12], ['Proteína', '#E9D8C0', 16], ['Verdura', '#4E8A3A', 18], ['Fruta', '#F29A3A', 24], ['Líquido', '#9CCBE6', 28]], s = K.suelo(70, 132, 40), y = 22; s += K.p('M40 20 L50 130 L90 130 L100 20 Z', M.vidrio, { op: .5 }); cap.forEach(function (c) { var t = (y - 20) / 110, t2 = (y + c[2] - 20) / 110; s += K.pl([[40 + 10 * t, y], [100 - 10 * t, y], [100 - 10 * t2, y + c[2]], [40 + 10 * t2, y + c[2]]], c[1]) + K.t(108, y + c[2] / 2 + 2.4, c[0], { s: 7, b: 1, a: 'start' }); y += c[2]; }); return s; },
      intro: 'Un batido completo se construye por capas: líquido, fruta, verdura, proteína, grasa y un extra.',
      q: [['¿Qué capa sacia más?', 'La proteína, junto con la grasa y la fibra.'], ['¿Cuánta fruta se pone?', 'Una o dos raciones, unos 150-250 g.'], ['¿Qué se consigue al añadir verdura?', 'Más fibra y vitaminas sin casi azúcar.']],
      porque: 'Combinar grupos de alimentos equilibra energía, saciedad y nutrientes en un solo vaso.' },
    { id: 'bt_fibra_glucosa', fam: 'nut', n: 'La fibra frena el azúcar',
      d: function (K) { return K.suelo(100, 128, 88) + K.l('M24 118 L184 118 M24 118 L24 20', '#555', { w: 1.2 }) + K.l('M24 110 Q50 110 60 40 Q70 20 86 70 Q100 104 184 108', C.mal, { w: 2.4 }) + K.l('M24 110 Q60 106 80 76 Q104 60 130 80 Q154 98 184 104', C.ok, { w: 2.4 }) + K.t(64, 30, 'Zumo', { s: 7.4, b: 1, c: C.mal }) + K.t(120, 58, 'Batido con fibra', { s: 7.4, b: 1, c: C.ok }) + K.t(104, 132, 'Tiempo después de beber (min)', { s: 6.4 }) + K.t(28, 16, 'Glucosa en sangre', { s: 6.4, a: 'start' }); },
      intro: 'Con la misma fruta, el zumo sube la glucosa en pico y el batido la sube de forma suave.',
      q: [['¿Por qué el zumo sube tanto?', 'Sin fibra, el azúcar llega de golpe al intestino.'], ['¿Qué pasa después del pico?', 'La glucosa baja rápido y vuelve el hambre.'], ['¿Qué añade más fibra a un batido?', 'Verdura, semillas, avena y fruta con piel.']],
      porque: 'La fibra forma un gel en el intestino que retrasa la absorción del azúcar.' },
    { id: 'bt_azucares_libres', fam: 'nut', n: 'Azúcares libres: el límite de la OMS',
      d: function (K) { var s = K.suelo(100, 128, 88); for (var i = 0; i < 6; i++) s += K.caja(20 + i * 18, 96, 12, 12, 6, '#FFFFFF'); s += K.t(70, 124, '25 g ≈ 6 cucharaditas', { s: 7, b: 1 }) + K.t(70, 84, 'Límite ideal al día (adulto)', { s: 6.8, b: 1 }) + K.cil(160, 50, 18, 60, '#F29A3A', { abierto: 1 }) + K.t(160, 124, 'Zumo 250 ml', { s: 6.8, b: 1 }) + K.t(160, 134, '≈ 22 g', { s: 6.8, b: 1, c: C.mal }); return s + K.t(100, 30, 'Cuentan: azúcar, miel, siropes y zumos', { s: 7, b: 1 }); },
      intro: 'La OMS recomienda que los azúcares libres sean menos del 10 % de la energía, e idealmente menos del 5 %, unos 25 g al día.',
      q: [['¿Qué cuenta como azúcar libre?', 'El azúcar añadido, la miel, los siropes y el azúcar de los zumos.'], ['¿La fruta entera cuenta?', 'No: su azúcar está dentro de la fibra.'], ['¿Y la fruta triturada en batido?', 'Se considera en parte libre: por eso conviene no pasar de un vaso.']],
      porque: 'Al romper las células de la fruta, parte del azúcar queda libre y se absorbe más rápido.' },
    { id: 'bt_indice_glucemico', fam: 'nut', n: 'Índice glucémico de las frutas',
      d: function (K) { return K.suelo(100, 128, 88) + barras(K, [['Cereza', 22, '#A81E2E'], ['Manzana', 36, '#C8332E'], ['Fresa', 40, '#E0413A'], ['Naranja', 43, '#F28C28'], ['Mango', 51, '#F2A43A'], ['Plátano', 51, '#F2D04B'], ['Piña', 59, '#E9C24A'], ['Sandía', 72, '#E8483E']], 34, 132, 156, 96, 80) + K.t(100, 16, 'Índice glucémico aproximado (glucosa = 100)', { s: 6.6, b: 1 }); },
      intro: 'El índice glucémico mide la rapidez con que un alimento sube la glucosa.',
      q: [['¿Qué frutas tienen índice bajo?', 'Cereza, manzana, fresa, naranja.'], ['¿Significa que la sandía es mala?', 'No: tiene poco azúcar por ración, su carga glucémica es baja.'], ['¿Qué baja el índice de un batido?', 'Añadir proteína, grasa y fibra.']],
      porque: 'Fibra, acidez y tipo de azúcar hacen que cada fruta se digiera a distinta velocidad.' },
    { id: 'bt_vitc_frutas', fam: 'nut', n: 'Vitamina C por fruta',
      d: function (K) { return K.suelo(100, 128, 88) + barras(K, [['Guayaba', 228, '#F0A0A8'], ['Kiwi', 93, '#8FB23E'], ['Fresa', 59, '#E0413A'], ['Naranja', 53, '#F28C28'], ['Papaya', 61, '#F07E4A'], ['Mango', 36, '#F2A43A'], ['Piña', 48, '#E9C24A'], ['Plátano', 9, '#F2D04B']], 34, 132, 156, 96, 230) + K.t(100, 16, 'mg de vitamina C por 100 g', { s: 6.6, b: 1 }); },
      intro: 'La guayaba y el kiwi superan a la naranja; el plátano apenas tiene.',
      q: [['¿Qué fruta tiene más vitamina C?', 'La guayaba.'], ['¿Cuánto kiwi cubre lo que se necesita al día?', 'Uno grande.'], ['¿Qué destruye la vitamina C?', 'El calor, el aire y el paso del tiempo.']],
      porque: 'La vitamina C protege a la fruta del daño del sol y del oxígeno; por eso abunda en la piel y la pulpa fresca.' },
    { id: 'bt_proteina_ingr', fam: 'nut', n: 'Proteína por ingrediente',
      d: function (K) { return K.suelo(100, 128, 88) + barras(K, [['Suero', 20, '#EFE8DA'], ['Yogur gr.', 12, '#FFFDF6'], ['Leche', 8, '#FBFBF6'], ['Tofu', 5, '#F2EEE0'], ['Avena', 5, '#E8D6A8'], ['Cacahuete', 4, '#C8904A'], ['Chía', 2, '#8A8480'], ['Plátano', 1, '#F2D04B']], 34, 132, 156, 96, 22, ' g') + K.t(100, 12, 'Gramos de proteína por ración', { s: 6.8, b: 1 }) + K.t(100, 21, 'suero 1 cacito · yogur 125 g · leche 250 ml · tofu 100 g', { s: 5.6 }) + K.t(100, 28, 'avena 40 g · cacahuete y chía 1 cda', { s: 5.6 }); },
      intro: 'Los lácteos y el suero son los que más proteína aportan; la fruta casi nada.',
      q: [['¿Cómo llego a 20 g de proteína sin suplementos?', 'Yogur griego + leche = unos 20 g.'], ['¿Qué opción vegetal hay?', 'Tofu sedoso, bebida de soja, crema de cacahuete.'], ['¿Por qué importa la proteína en el batido?', 'Da saciedad y mantiene el músculo.']],
      porque: 'Las proteínas se digieren despacio y envían señales de saciedad al cerebro.' },
    { id: 'bt_calorias', fam: 'nut', n: 'Calorías por ingrediente',
      d: function (K) { return K.suelo(100, 128, 88) + barras(K, [['Leche', 150, '#FBFBF6'], ['Avena', 150, '#E8D6A8'], ['Plátano', 105, '#F2D04B'], ['Cacahuete', 95, '#C8904A'], ['Aguacate', 80, '#6E9A4E'], ['Miel', 64, '#E0A02A'], ['Fresas', 32, '#E0413A'], ['Espinaca', 7, '#3E7A34']], 34, 132, 156, 96, 160, ' ') + K.t(100, 12, 'kcal aproximadas por ración', { s: 6.8, b: 1 }) + K.t(100, 21, 'leche 250 ml · avena 40 g · 1 plátano · cacahuete 1 cda', { s: 5.6 }) + K.t(100, 28, '¼ aguacate · miel 1 cda · fresas 100 g · espinaca 30 g', { s: 5.6 }); },
      intro: 'Un batido puede tener 150 o 600 kcal según lo que se añada: conviene sumar.',
      q: [['¿Qué ingredientes suman más calorías?', 'Frutos secos, cremas, avena, leche entera y endulzantes.'], ['¿Cuál casi no suma?', 'Las verduras de hoja.'], ['Si sumo plátano, leche y avena, ¿cuánto sale?', 'Unas 405 kcal.']],
      porque: 'Las grasas dan 9 kcal por gramo; las proteínas y los hidratos, 4.' },
    { id: 'bt_colores', fam: 'nut', n: 'Los colores de la fruta',
      d: function (K) { var t = [['Rojo', 'Licopeno', '#D2453E'], ['Naranja', 'Betacaroteno', '#F29A3A'], ['Amarillo', 'Flavonoides', '#F2C94B'], ['Verde', 'Clorofila', '#5E9A3A'], ['Morado', 'Antocianinas', '#6A3A7A'], ['Blanco', 'Alicina', '#EFE8DA']], s = K.suelo(100, 132, 90); t.forEach(function (q, i) { var x = 36 + (i % 3) * 64, y = 48 + Math.floor(i / 3) * 50; s += K.c(x, y, 12, q[2]) + K.t(x, y + 22, q[0], { s: 7, b: 1 }) + K.t(x, y + 31, q[1], { s: 6.2 }); }); return s + K.t(100, 16, 'Un color distinto, un pigmento distinto', { s: 7, b: 1 }); },
      intro: 'Cada color de fruta o verdura es un pigmento diferente con su propia función.',
      q: [['¿Qué pigmento tiene la zanahoria?', 'Betacaroteno.'], ['¿Por qué se recomienda «comer el arcoíris»?', 'Cada color aporta compuestos distintos.'], ['¿Qué pasa si se mezclan morado y verde?', 'El batido sale marrón, aunque sigue siendo nutritivo.']],
      porque: 'Los pigmentos protegen a la planta del sol; en el cuerpo muchos actúan como antioxidantes.' },
    { id: 'bt_textura', fam: 'nut', n: 'Orden de carga de la batidora',
      d: function (K) { var cap = [['5 · Hielo o congelado', '#DDF1F8'], ['4 · Fruta dura y semillas', '#F29A3A'], ['3 · Hojas verdes', '#5E9A3A'], ['2 · Fruta blanda y yogur', '#F4E6C8'], ['1 · Líquido', '#9CCBE6']], s = K.suelo(64, 136, 40) + K.p('M34 16 L40 128 L88 128 L94 16 Z', M.vidrio, { op: .5 }); cap.forEach(function (c, i) { var y = 22 + i * 21; s += K.r(38 + i * .6, y, 52 - i * 1.2, 20, 0, c[1]) + K.t(100, y + 13, c[0], { s: 7.2, b: 1, a: 'start' }); }); return s + K.p('M52 126 L64 120 L76 126', M.acero, { w: 1.6 }); },
      intro: 'Cargar el vaso en este orden ayuda a que la cuchilla forme el remolino desde el principio.',
      q: [['¿Por qué el líquido va primero?', 'Cubre la cuchilla y la deja girar libre.'], ['¿Y el hielo al final?', 'Su peso empuja todo hacia abajo.'], ['¿Qué hacer si se atasca?', 'Parar, añadir un poco de líquido y remover.']],
      porque: 'Con líquido abajo, la cuchilla gira rápido y arrastra lo de arriba hacia el centro.' },
    { id: 'bt_oxidacion', fam: 'nut', n: 'El batido cambia con el tiempo',
      d: function (K) { var t = [['Recién hecho', '#7FB548'], ['1 hora', '#9AA848'], ['4 horas', '#A89A4A'], ['12 horas', '#9A8450']], s = K.suelo(100, 128, 90); t.forEach(function (q, i) { var x = 34 + i * 44; s += K.p('M' + (x - 14) + ' 60 L' + (x - 11) + ' 112 L' + (x + 11) + ' 112 L' + (x + 14) + ' 60 Z', q[1]); if (i > 1) s += K.r(x - 13, 60, 26, 10, 0, '#D8D0B0', { op: .8 }); s += K.t(x, 126, q[0], { s: 6.6, b: 1 }); }); return s + K.t(100, 40, 'Color, espuma y vitamina C bajan', { s: 7, b: 1 }); },
      intro: 'Con el aire, el batido se oscurece, se separa y pierde vitamina C.',
      q: [['¿Cuánto aguanta en la nevera?', 'Hasta 24 horas, en un recipiente lleno y cerrado.'], ['¿Qué frena la oxidación?', 'Unas gotas de limón y dejar poco aire en el recipiente.'], ['¿Por qué se separa en capas?', 'La pulpa pesa más y baja.']],
      porque: 'Las enzimas de la fruta reaccionan con el oxígeno y oscurecen los pigmentos.' },
    { id: 'bt_enzimas', fam: 'nut', n: 'Piña, kiwi y lácteos',
      d: function (K) { var s = K.suelo(100, 124, 90) + K.c(40, 80, 20, '#E9C24A') + K.t(40, 116, 'Piña o kiwi', { s: 7, b: 1 }) + K.t(40, 126, '(enzimas)', { s: 6.4 }) + K.t(76, 84, '+', { s: 14, b: 1 }) + K.cil(110, 60, 18, 40, M.blanco) + K.t(110, 116, 'Lácteo', { s: 7, b: 1 }) + K.flecha(134, 80, 150, 80, '#555'); s += K.p('M156 104 L158 56 L186 56 L184 104 Z', M.vidrio, { op: .6 }) + K.r(158, 76, 26, 28, 0, '#F4E6B8') + K.r(158, 60, 26, 16, 0, '#F8F2E0', { op: .8 }); return s + K.t(172, 116, 'Amarga', { s: 7, b: 1, c: C.mal }) + K.t(172, 126, 'si reposa', { s: 6.4 }); },
      intro: 'La piña y el kiwi crudos tienen enzimas que rompen las proteínas de la leche.',
      q: [['¿Qué pasa si el batido reposa?', 'Se vuelve amargo y la textura se corta.'], ['¿Cómo se evita?', 'Tomándolo enseguida o usando bebida vegetal o fruta cocida.'], ['¿Qué enzima tiene la piña?', 'La bromelina.']],
      porque: 'Las enzimas cortan las proteínas de la leche en trozos pequeños que saben amargos.' },
    { id: 'bt_agua_fruta', fam: 'nut', n: 'Agua en frutas y verduras',
      d: function (K) { return K.suelo(100, 128, 88) + barras(K, [['Pepino', 95, '#5E9A48'], ['Lechuga', 95, '#8CC05A'], ['Sandía', 92, '#E8483E'], ['Fresa', 91, '#E0413A'], ['Melón', 90, '#E9C98A'], ['Naranja', 87, '#F28C28'], ['Manzana', 86, '#C8332E'], ['Plátano', 75, '#F2D04B']], 34, 132, 156, 96, 100, ' %') + K.t(100, 16, 'Porcentaje de agua', { s: 6.6, b: 1 }); },
      intro: 'Muchas frutas y verduras son más del 85 % agua: también hidratan.',
      q: [['¿Qué fruta tiene menos agua de esta lista?', 'El plátano.'], ['¿Por qué el plátano espesa y la sandía aclara?', 'El plátano tiene menos agua y más almidón y pectina.'], ['¿Cuánta agua hay en 200 g de sandía?', 'Unos 184 ml.']],
      porque: 'Las células de la fruta son pequeñas bolsas de agua que se liberan al triturar.' },
    { id: 'bt_liposolubles', fam: 'nut', n: 'Vitaminas que necesitan grasa',
      d: function (K) { var s = K.suelo(100, 124, 90); ['A', 'D', 'E', 'K'].forEach(function (v, i) { s += K.c(30 + i * 30, 60, 12, '#F2C94B') + K.t(30 + i * 30, 64, v, { s: 10, b: 1 }); }); s += K.t(75, 90, 'Se disuelven en grasa', { s: 7, b: 1 }) + K.p('M140 100 Q140 60 160 58 Q180 60 180 100 Q180 120 160 120 Q140 120 140 100 Z', '#4F7A2E') + K.c(160, 100, 9, '#8A5A2E'); return s + K.t(156, 136, 'Aguacate y semillas', { s: 6.2, b: 1 }) + K.t(75, 110, 'Añade 1 fuente de grasa', { s: 6.8 }); },
      intro: 'Las vitaminas A, D, E y K solo se absorben bien si hay algo de grasa en el batido.',
      q: [['¿Qué vitamina de la zanahoria necesita grasa?', 'La A (betacaroteno).'], ['¿Qué ingredientes aportan esa grasa?', 'Aguacate, semillas, frutos secos, yogur entero.'], ['¿Cuánta hace falta?', 'Poca: una cucharada de semillas o un cuarto de aguacate.']],
      porque: 'Estas vitaminas viajan en pequeñas gotas de grasa que el intestino absorbe.' },
    /* ─────────── MEDIDA, COSTES Y CONSERVACIÓN ─────────── */
    { id: 'bt_proporcion', fam: 'med', n: 'Proporción líquido y sólido',
      d: function (K) { var s = K.suelo(100, 128, 90); [['Líquido 1 : 1 sólido', 'Bebible', 50, 60], ['1 : 1,5', 'Cremoso', 50, 75], ['1 : 2', 'Bol para cuchara', 50, 90]].forEach(function (q, i) { var x = 36 + i * 64; s += K.r(x - 16, 110 - q[2] * .6, 12, q[2] * .6, 1, '#9CCBE6') + K.r(x + 2, 110 - q[3] * .6, 12, q[3] * .6, 1, '#F29A3A') + K.t(x, 122, q[0], { s: 6, b: 1 }) + K.t(x, 132, q[1], { s: 6.4 }); }); return s + K.r(20, 20, 8, 8, 1, '#9CCBE6') + K.t(30, 27, 'Líquido', { s: 6.4, a: 'start' }) + K.r(80, 20, 8, 8, 1, '#F29A3A') + K.t(90, 27, 'Fruta y sólidos', { s: 6.4, a: 'start' }); },
      intro: 'Cambiar la relación entre líquido y sólido cambia la textura: de bebida a bol de cuchara.',
      q: [['¿Qué proporción para un batido de vaso?', 'Una parte de líquido por una de sólido.'], ['¿Cómo se hace un bol de batido?', 'Con el doble de fruta congelada que de líquido.'], ['Si tengo 300 g de fruta, ¿cuánto líquido para un batido bebible?', '300 ml.']],
      porque: 'Menos líquido deja las partículas de pulpa más juntas y el batido fluye menos.' },
    { id: 'bt_escalar', fam: 'med', n: 'Escalar la receta',
      d: function (K) { var f = [['Plátano', 1, 'ud'], ['Fresas', 100, 'g'], ['Leche', 250, 'ml'], ['Avena', 20, 'g']], s = K.suelo(100, 136, 90) + K.r(16, 14, 168, 116, 3, C.papel) + K.t(24, 28, 'Ingrediente', { s: 7, b: 1, a: 'start' }) + K.t(110, 28, '1 vaso', { s: 7, b: 1 }) + K.t(160, 28, '× 4 vasos', { s: 7, b: 1 }); f.forEach(function (q, i) { var y = 46 + i * 16; s += K.t(24, y, q[0], { s: 7, a: 'start' }) + K.t(110, y, q[1] + ' ' + q[2], { s: 7 }) + K.t(160, y, (q[1] * 4) + ' ' + q[2], { s: 7, b: 1, c: C.azul }) + K.l('M24 ' + (y + 5) + ' L176 ' + (y + 5), '#E4E0D0'); }); return s + K.t(100, 122, 'Factor = raciones nuevas ÷ raciones originales', { s: 6.6, b: 1 }); },
      intro: 'Para hacer más batido se multiplica cada ingrediente por el mismo factor.',
      q: [['¿Cuál es el factor para pasar de 1 a 4 vasos?', '4.'], ['¿Y para pasar de 4 a 2?', '0,5: se divide a la mitad.'], ['¿Cabe todo en la batidora?', 'Se mira la capacidad; si no, se hace en dos tandas.']],
      porque: 'Si todo se multiplica por el mismo número, las proporciones y el sabor no cambian.' },
    { id: 'bt_coste', fam: 'med', n: 'Coste de un batido',
      d: function (K) { var f = [['Plátano (1)', '0,25'], ['Fresas 100 g', '0,60'], ['Leche 250 ml', '0,25'], ['Avena 20 g', '0,05'], ['Vaso y pajita', '0,15']], s = K.suelo(100, 136, 90) + K.r(24, 14, 152, 118, 3, C.papel) + K.t(32, 28, 'Batido de fresa y plátano', { s: 7.4, b: 1, a: 'start' }); f.forEach(function (q, i) { var y = 44 + i * 13; s += K.t(32, y, q[0], { s: 7, a: 'start' }) + K.t(168, y, q[1], { s: 7, a: 'end' }); }); return s + K.l('M32 110 L168 110', '#555') + K.t(32, 122, 'Coste total', { s: 7.4, b: 1, a: 'start' }) + K.t(168, 122, '1,30', { s: 7.4, b: 1, a: 'end' }); },
      intro: 'Sumar lo que cuesta cada ingrediente, más el envase, da el coste real de un vaso.',
      q: [['¿Por qué se incluye el vaso?', 'Es un coste que se repite en cada venta.'], ['¿Cómo se calcula el coste de 100 g de fresas si 500 g cuestan 3,00?', '3,00 ÷ 5 = 0,60.'], ['¿Qué ingrediente pesa más en el coste?', 'La fruta fuera de temporada.']],
      porque: 'Conocer el coste unitario permite fijar un precio que no pierda dinero.' },
    { id: 'bt_margen', fam: 'med', n: 'Precio de venta y margen',
      d: function (K) { return K.suelo(100, 128, 90) + K.r(24, 40, 44, 70, 0, '#E8D8C0') + K.t(46, 78, 'Coste', { s: 7, b: 1 }) + K.t(46, 88, '1,30', { s: 7 }) + K.r(24, 20, 44, 20, 0, C.ok) + K.t(46, 33, 'Margen', { s: 6.6, b: 1, c: '#fff' }) + K.t(46, 124, 'Precio 3,50', { s: 7.4, b: 1 }) + K.t(90, 48, 'Coste ÷ precio × 100 = % de coste', { s: 6.6, a: 'start' }) + K.t(90, 62, '1,30 ÷ 3,50 × 100 ≈ 37 %', { s: 6.6, b: 1, a: 'start' }) + K.t(90, 84, 'Margen = precio − coste', { s: 6.6, a: 'start' }) + K.t(90, 98, '3,50 − 1,30 = 2,20', { s: 6.6, b: 1, a: 'start' }); },
      intro: 'El margen es lo que queda para pagar alquiler, sueldos y ganancia.',
      q: [['Si quiero un coste del 30 %, ¿a cuánto vendo un batido de 1,30?', 'A 1,30 ÷ 0,30 ≈ 4,35.'], ['¿Qué es el margen?', 'La diferencia entre precio y coste.'], ['¿El margen es ganancia limpia?', 'No: de ahí salen los gastos fijos.']],
      porque: 'Si el porcentaje de coste es alto, el margen no cubre los gastos del negocio.' },
    { id: 'bt_etiqueta', fam: 'med', n: 'Etiqueta nutricional de un batido',
      d: function (K) { var f = [['Energía', '280 kcal'], ['Grasas', '6 g'], ['Hidratos', '46 g'], ['· de los cuales azúcares', '30 g'], ['Fibra', '6 g'], ['Proteínas', '12 g'], ['Sal', '0,2 g']], s = K.suelo(100, 140, 70) + K.r(40, 10, 120, 126, 2, '#FFFFFF') + K.t(48, 24, 'Información nutricional', { s: 7.4, b: 1, a: 'start' }) + K.t(48, 34, 'Por vaso (350 ml)', { s: 6.4, a: 'start' }); f.forEach(function (q, i) { var y = 50 + i * 12; s += K.t(48, y, q[0], { s: 6.6, a: 'start', b: i === 0 }) + K.t(152, y, q[1], { s: 6.6, a: 'end', b: 1 }) + K.l('M48 ' + (y + 4) + ' L152 ' + (y + 4), '#DDD'); }); return s; },
      intro: 'Una etiqueta clara dice lo que hay en un vaso: energía, azúcares, fibra y proteína.',
      q: [['¿Qué dato se mira para el azúcar?', '«De los cuales azúcares».'], ['¿Por qué se indica la ración?', 'Para comparar productos con la misma cantidad.'], ['¿Qué alérgenos se destacan?', 'Leche, frutos secos, cacahuete, soja y otros de la lista legal.']],
      porque: 'Los valores por ración permiten sumar lo que se come en el día.' },
    { id: 'bt_azucar_calc', fam: 'med', n: '¿Cuánto azúcar tiene mi batido?',
      d: function (K) { var f = [['Plátano 120 g', '14 g'], ['Mango 100 g', '14 g'], ['Leche 250 ml', '12 g'], ['Miel 1 cdta', '6 g']], s = K.suelo(100, 136, 90) + K.r(20, 14, 160, 114, 3, C.papel); f.forEach(function (q, i) { var y = 32 + i * 16; s += K.t(28, y, q[0], { s: 7.2, a: 'start' }) + K.t(172, y, q[1], { s: 7.2, a: 'end', b: 1 }); }); return s + K.l('M28 96 L172 96', '#555') + K.t(28, 110, 'Total', { s: 7.4, b: 1, a: 'start' }) + K.t(172, 110, '46 g ≈ 11 cdtas', { s: 7.4, b: 1, a: 'end', c: C.mal }) + K.t(100, 124, 'Cambiar mango por fresas: −9 g', { s: 6.6, b: 1, c: C.ok }); },
      intro: 'Sumar el azúcar de cada ingrediente muestra cuánto dulce hay en un vaso.',
      q: [['¿Cuántos gramos tiene una cucharadita de azúcar?', 'Unos 4 g.'], ['¿Qué cambio reduce más el azúcar?', 'Quitar la miel y usar frutos rojos.'], ['¿El azúcar de la leche es añadido?', 'No, es lactosa natural.']],
      porque: 'Dividir los gramos entre 4 traduce el azúcar a cucharaditas fáciles de imaginar.' },
    { id: 'bt_conservacion', fam: 'med', n: 'Conservar un batido',
      d: function (K) { var t = [['Ambiente', '≤ 2 h', C.mal], ['Nevera', '≤ 24 h', '#E9A02E'], ['Congelador', '≤ 3 meses', C.ok]], s = K.suelo(100, 128, 90); t.forEach(function (q, i) { var x = 36 + i * 64; s += K.cil(x, 50, 16, 56, M.vidrio, { abierto: 1 }) + K.r(x - 15, 60, 30, 46, 0, '#F29A3A', { op: .85 }) + K.cil(x, 44, 16, 6, M.acero) + K.t(x, 122, q[0], { s: 7, b: 1 }) + K.t(x, 132, q[1], { s: 7, b: 1, c: q[2] }); }); return s; },
      intro: 'Sin conservantes, el batido dura poco: frío, cerrado y lleno hasta arriba.',
      q: [['¿Por qué lleno hasta arriba?', 'Queda menos aire y se oxida menos.'], ['¿Cómo se congela?', 'En moldes de polo o bolsas planas.'], ['¿Qué batido no se conserva bien?', 'El que lleva piña o kiwi con lácteo.']],
      porque: 'El frío frena bacterias y enzimas; la falta de aire frena la oxidación.' },
    { id: 'bt_packs', fam: 'med', n: 'Packs congelados listos',
      d: function (K) { var s = K.suelo(100, 130, 90); [['Lunes', '#E0413A'], ['Martes', '#7FB548'], ['Miérc.', '#F29A3A'], ['Jueves', '#6A3A7A']].forEach(function (q, i) { var x = 30 + i * 46; s += K.r(x - 18, 50, 36, 64, 4, '#E8F2F6', { op: .9 }) + K.r(x - 18, 50, 36, 8, 2, '#B8C8D0'); for (var j = 0; j < 5; j++) s += K.c(x - 8 + (j % 2) * 14, 72 + Math.floor(j / 2) * 12, 6, j === 4 ? '#5E9A3A' : q[1]); s += K.t(x, 124, q[0], { s: 6.8, b: 1 }); }); return s + K.t(100, 34, 'Fruta y verdura ya pesadas: solo añadir líquido', { s: 6.8, b: 1 }); },
      intro: 'Preparar bolsas con la fruta ya pesada para la semana ahorra tiempo y evita desperdicio.',
      q: [['¿Qué se pone en cada bolsa?', 'Toda la fruta, verdura y semillas de un batido.'], ['¿Qué se añade en el momento?', 'El líquido.'], ['¿Qué se escribe en la bolsa?', 'El contenido y la fecha.']],
      porque: 'Congelar en raciones evita descongelar de más y mantiene la fruta en su punto.' },
    { id: 'bt_temporada', fam: 'med', n: 'Frutas de temporada',
      d: function (K) { var e = [['Primavera', ['Fresa', 'Cereza', 'Níspero'], '#8CC05A'], ['Verano', ['Sandía', 'Melón', 'Melocotón'], '#F2C94B'], ['Otoño', ['Uva', 'Granada', 'Caqui'], '#C8783E'], ['Invierno', ['Naranja', 'Kiwi', 'Mandarina'], '#8AB0D8']], s = K.suelo(100, 136, 90); e.forEach(function (q, i) { var x = 12 + i * 46; s += K.r(x, 20, 42, 110, 3, K.claro(q[2], .55)) + K.r(x, 20, 42, 16, 3, q[2]) + K.t(x + 21, 31, q[0], { s: 6.4, b: 1 }); q[1].forEach(function (f, j) { s += K.c(x + 21, 54 + j * 26, 8, q[2]) + K.t(x + 21, 70 + j * 26, f, { s: 6, b: 1 }); }); }); return s; },
      intro: 'Hemisferio norte. En el sur las estaciones se invierten; en el trópico hay fruta todo el año.',
      q: [['¿Por qué la fruta de temporada es más barata?', 'Hay más oferta y viaja menos.'], ['¿Por qué sabe mejor?', 'Madura en la planta.'], ['¿Qué fruta hay en tu país en este mes?', 'Respuesta propia: consulta un calendario local.']],
      porque: 'La fruta madurada en la planta acumula más azúcar y aroma que la cosechada verde.' },
    { id: 'bt_aprovechar', fam: 'med', n: 'Aprovechar la fruta madura',
      d: function (K) { return K.suelo(100, 124, 90) + K.p('M16 80 Q30 116 90 100 Q104 94 106 82 Q100 88 90 90 Q40 100 26 74 Z', '#E8C050') + K.puntos([[40, 90], [56, 94], [72, 92], [84, 88], [48, 84]], 3, '#6A4A2A') + K.t(60, 124, 'Plátano muy maduro', { s: 6.8, b: 1 }) + K.flecha(112, 88, 130, 88, '#555') + K.r(136, 60, 48, 50, 4, '#E8F2F6', { op: .9 }) + K.c(150, 80, 7, '#F2D04B') + K.c(166, 80, 7, '#F2D04B') + K.c(158, 94, 7, '#F2D04B') + K.t(160, 124, 'Al congelador', { s: 6.8, b: 1 }); },
      intro: 'La fruta demasiado madura es perfecta para batir: más dulce y fácil de triturar.',
      q: [['¿Qué se hace con los plátanos con manchas?', 'Pelarlos, trocearlos y congelarlos.'], ['¿Qué fruta no se aprovecha?', 'La que tiene moho o huele a fermentado.'], ['¿Cuánto se desperdicia de fruta en casa?', 'Una parte importante del desperdicio de alimentos es fruta y verdura.']],
      porque: 'Al madurar, el almidón se transforma en azúcar: sin añadir nada, el batido es más dulce.' },
    { id: 'bt_lavar', fam: 'med', n: 'Lavar fruta y verdura',
      d: function (K) { var s = K.suelo(100, 126, 90) + K.p('M24 72 Q28 120 80 120 Q132 120 136 72 Z', M.metal) + K.e(80, 72, 56, 12, '#BFE3F2'); [[60, 70, '#E0413A'], [80, 74, '#5E9A3A'], [100, 70, '#F29A3A']].forEach(function (q) { s += K.c(q[0], q[1], 8, q[2]); }); return s + K.l('M80 20 L80 56', '#9CCBE6', { w: 3, d: '4 3' }) + K.r(70, 12, 20, 10, 2, M.acero) + K.t(166, 60, '1 · Agua corriente', { s: 6.6, b: 1 }) + K.t(166, 74, '2 · Frotar', { s: 6.6, b: 1 }) + K.t(166, 88, '3 · Hojas: remojo', { s: 6.6, b: 1 }) + K.t(166, 102, '4 · Secar', { s: 6.6, b: 1 }); },
      intro: 'Lavar con agua corriente y frotar quita tierra, restos y parte de los microbios.',
      q: [['¿Se lava la fruta que se pela?', 'Sí: el cuchillo arrastra lo de la piel a la pulpa.'], ['¿Se usa jabón?', 'No: puede quedar en la piel.'], ['¿Cuándo se lavan las fresas?', 'Justo antes de usarlas.']],
      porque: 'El agua en movimiento y el frotado arrastran la suciedad mejor que el remojo solo.' },
    { id: 'bt_alergenos', fam: 'med', n: 'Alérgenos frecuentes en batidos',
      d: function (K) { var t = [['Leche', '#FBFBF6'], ['Frutos secos', '#A8743E'], ['Cacahuete', '#C8904A'], ['Soja', '#E8D8A0'], ['Sésamo', '#E8D0A0'], ['Gluten (avena)', '#E8D6A8']], s = K.suelo(100, 128, 90); t.forEach(function (q, i) { var x = 34 + (i % 3) * 66, y = 46 + Math.floor(i / 3) * 44; s += K.c(x, y, 14, q[1]) + K.l('M' + (x - 10) + ' ' + (y - 10) + ' L' + (x + 10) + ' ' + (y + 10), C.mal, { w: 2 }) + K.t(x, y + 26, q[0], { s: 6.8, b: 1 }); }); return s + K.t(100, 16, 'Preguntar siempre antes de servir', { s: 7, b: 1 }); },
      intro: 'Varios ingredientes comunes de los batidos están en la lista de alérgenos obligatorios.',
      q: [['¿Por qué la avena puede tener gluten?', 'Por contaminación con trigo al procesarla.'], ['¿Cómo se evita el contacto cruzado?', 'Lavando el vaso y la cuchilla entre batidos.'], ['¿Dónde se informa al cliente?', 'En la carta o de forma oral y registrada.']],
      porque: 'Una cantidad mínima puede provocar una reacción en una persona alérgica.' },
    { id: 'bt_pizarra', fam: 'med', n: 'Carta de batidos',
      d: function (K) { var f = [['Verde', '3,50', '#7FB548'], ['Tropical', '3,80', '#F29A3A'], ['Frutos rojos', '3,90', '#A8325A'], ['Desayuno', '4,20', '#D8B07A'], ['Chocolate', '3,90', '#6A3E26']], s = K.suelo(100, 140, 80) + K.r(28, 10, 144, 124, 3, '#2E3A34') + K.r(32, 14, 136, 116, 2, '#3A4A42') + K.t(100, 30, 'BATIDOS', { s: 10, b: 1, c: '#F4F0E0' }); f.forEach(function (q, i) { var y = 50 + i * 16; s += K.c(44, y - 3, 4, q[2]) + K.t(54, y, q[0], { s: 7.4, a: 'start', c: '#F4F0E0' }) + K.t(160, y, q[1], { s: 7.4, b: 1, a: 'end', c: '#F4F0E0' }); }); return s; },
      intro: 'Una carta corta y clara ayuda a elegir; cada precio sale del coste y el margen.',
      q: [['¿Por qué pocas opciones?', 'Se decide antes y hay menos desperdicio de ingredientes.'], ['¿Qué información extra ayuda?', 'Objetivo del batido, alérgenos y tamaño del vaso.'], ['¿Qué batido tiene el precio más alto y por qué?', 'El de desayuno: lleva más ingredientes.']],
      porque: 'Con menos productos se compra mejor y se repite la calidad en cada vaso.' },
    { id: 'bt_pajitas', fam: 'equ', n: 'Pajitas reutilizables',
      d: function (K) { var s = K.suelo(100, 124, 90); [['Acero', M.metal], ['Vidrio', M.vidrio], ['Bambú', '#C8A060'], ['Silicona', '#E86A8A']].forEach(function (q, i) { var x = 40 + i * 36; s += '<g transform="rotate(' + (-10 + i * 6) + ' ' + x + ' 110)">' + K.r(x - 4, 26, 8, 86, 4, q[1]) + K.e(x, 26, 4, 1.6, K.oscuro(q[1], .3)) + '</g>' + K.t(x, 124, q[0], { s: 7, b: 1 }); }); return s + K.l('M160 30 L184 110', '#555', { w: 1.2 }) + K.c(184, 110, 3, '#888') + K.t(172, 136, 'Cepillo', { s: 6.6, b: 1 }); },
      intro: 'Sustituyen a las de plástico de un solo uso; se limpian con un cepillo fino.',
      q: [['¿Por qué ancha para batidos?', 'El batido es espeso y no pasa por una pajita fina.'], ['¿Cómo se limpian?', 'Con agua caliente, jabón y cepillo.'], ['¿Cuál es mejor para niños?', 'La de silicona, blanda y sin bordes.']],
      porque: 'Un diámetro mayor reduce la resistencia al paso del líquido espeso.' },
    { id: 'bt_saciedad', fam: 'nut', n: 'Qué hace que un batido sacie',
      d: function (K) { var t = [['Zumo', 1, '#F29A3A'], ['Batido de fruta', 2, '#F2C94B'], ['+ yogur', 3, '#EFE8DA'], ['+ avena y semillas', 4, '#D8B07A'], ['Bol espeso con cuchara', 5, '#7FB548']], s = K.suelo(100, 132, 90); t.forEach(function (q, i) { var y = 24 + i * 20; s += K.t(78, y + 9, q[0], { s: 6.8, b: 1, a: 'end' }) + K.r(84, y, q[1] * 20, 13, 2, q[2]); }); return s + K.t(134, 136, 'Menos saciante → más saciante', { s: 6.6, b: 1 }); },
      intro: 'Proteína, fibra, grasa y textura espesa alargan la sensación de estar lleno.',
      q: [['¿Por qué el zumo sacia poco?', 'Es líquido, sin fibra ni proteína, y pasa rápido por el estómago.'], ['¿Qué efecto tiene comer con cuchara?', 'Se come más despacio y el cerebro registra la saciedad.'], ['¿Qué ingrediente convierte un batido en comida?', 'Una fuente de proteína.']],
      porque: 'Los alimentos espesos y con proteína tardan más en salir del estómago.' },
    { id: 'bt_raciones', fam: 'med', n: 'Tamaños de vaso',
      d: function (K) { var t = [['250 ml', 'Niños o tentempié', 40, 50], ['350 ml', 'Adulto', 60, 100], ['500 ml', 'Sustituye comida', 80, 150]], s = K.suelo(100, 128, 90); t.forEach(function (q, i) { var x = 36 + i * 64, h = q[2]; s += K.p('M' + (x - 14 - i * 3) + ' ' + (112 - h) + ' L' + (x - 11 - i * 2) + ' 112 L' + (x + 11 + i * 2) + ' 112 L' + (x + 14 + i * 3) + ' ' + (112 - h) + ' Z', '#F29A3A', { op: .85 }) + K.t(x, 122, q[0], { s: 7, b: 1 }) + K.t(x, 132, q[1], { s: 6.2 }); }); return s; },
      intro: 'El tamaño del vaso cambia las calorías: elegir el tamaño según el momento del día.',
      q: [['Si 250 ml tienen 180 kcal, ¿cuántas tienen 500 ml?', '360 kcal.'], ['¿Qué tamaño para un niño?', 'Entre 150 y 250 ml.'], ['¿Cuándo tiene sentido el vaso grande?', 'Cuando sustituye una comida y lleva proteína.']],
      porque: 'Las calorías son proporcionales al volumen: el doble de vaso, el doble de energía.' }
  ];
  MO.agregar('batidos', L, { materias: /^(batidos|cocina)$/ });
})();
