/* b6_lib_religion.js — Religión y cultura religiosa: modelos 1–25 de 50 (primera entrega). Materia `religion`. Prefijo `re_`.
   Cargar después de b6_modelos.js. No repite rel_fiestas, rel_planta, rel_templos, val_emociones, his_feudal, linea_pais, geo_poligono ni geo_simetria.
   Familias: grandes religiones, libros sagrados, relatos bíblicos (este archivo); calendario y ritos, símbolos y arte, convivencia y diálogo, cosmovisiones (b6_lib_religion2.js). */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('re_creencias')) return;
  var P = { azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', oro: '#E8C060', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', agua: '#9CCBE6', madera: '#C89A62', arena: '#EAD9B0', pergamino: '#F4E8C8' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { gr: 'Grandes religiones', lib: 'Libros sagrados', bib: 'Relatos bíblicos', cal: 'Calendario y ritos', sim: 'Símbolos y arte', dia: 'Convivencia y diálogo', cos: 'Cosmovisiones' };
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + f1 * .35, q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  function ajusta(t, ancho, max) { return +Math.min(max, ancho / (t.length * .54)).toFixed(2); }
  function estrella(K, cx, cy, r, col, o) { var pt = []; for (var i = 0; i < 10; i++) { var a = -Math.PI / 2 + i * Math.PI / 5, rr = i % 2 ? r * .45 : r; pt.push([+(cx + Math.cos(a) * rr).toFixed(1), +(cy + Math.sin(a) * rr).toFixed(1)]); } return K.pl(pt, col, o || { w: .6 }); }
  function david(K, cx, cy, r, col) { var a = [], b = []; for (var i = 0; i < 3; i++) { var t = -Math.PI / 2 + i * 2 * Math.PI / 3; a.push([+(cx + Math.cos(t) * r).toFixed(1), +(cy + Math.sin(t) * r).toFixed(1)]); b.push([+(cx + Math.cos(t + Math.PI) * r).toFixed(1), +(cy + Math.sin(t + Math.PI) * r).toFixed(1)]); } var tri = function (q) { return 'M' + q[0][0] + ' ' + q[0][1] + ' L' + q[1][0] + ' ' + q[1][1] + ' L' + q[2][0] + ' ' + q[2][1] + ' Z'; }; return K.l(tri(a) + ' ' + tri(b), col, { w: 2.4 }); }
  function cruz(K, cx, cy, e, col) { return K.r(cx - 3 * e, cy - 16 * e, 6 * e, 34 * e, 1, col, { w: .8 }) + K.r(cx - 12 * e, cy - 8 * e, 24 * e, 6 * e, 1, col, { w: .8 }); }
  function loto(K, cx, cy, e, col) { var s = ''; [-50, -25, 0, 25, 50].forEach(function (g) { s += K.p('M' + cx + ' ' + cy + ' Q' + (cx + Math.sin(g * Math.PI / 180) * 26 * e - 8 * e) + ' ' + (cy - Math.cos(g * Math.PI / 180) * 18 * e) + ' ' + (cx + Math.sin(g * Math.PI / 180) * 22 * e) + ' ' + (cy - Math.cos(g * Math.PI / 180) * 22 * e) + ' Q' + (cx + Math.sin(g * Math.PI / 180) * 26 * e + 8 * e) + ' ' + (cy - Math.cos(g * Math.PI / 180) * 18 * e) + ' ' + cx + ' ' + cy + ' Z', col, { w: .7 }); }); return s + K.e(cx, cy + 2, 18 * e, 4 * e, P.verde, { w: .6 }); }
  function rueda(K, cx, cy, r, col) { var s = K.l('M' + (cx - r) + ' ' + cy + ' A' + r + ' ' + r + ' 0 1 1 ' + (cx + r) + ' ' + cy + ' A' + r + ' ' + r + ' 0 1 1 ' + (cx - r) + ' ' + cy, col, { w: 3 }) + K.c(cx, cy, r * .22, col, { w: .6 }); for (var i = 0; i < 8; i++) { var a = i * Math.PI / 4; s += K.l('M' + (cx + Math.cos(a) * r * .22).toFixed(1) + ' ' + (cy + Math.sin(a) * r * .22).toFixed(1) + ' L' + (cx + Math.cos(a) * r).toFixed(1) + ' ' + (cy + Math.sin(a) * r).toFixed(1), col, { w: 1.6 }) + K.c(cx + Math.cos(a) * (r + 3), cy + Math.sin(a) * (r + 3), 2.2, col, { w: .4 }); } return s; }
  /* ficha de una religión: icono a la izquierda y filas [rótulo, valor] */
  function ficha(K, icono, filas, pie, col) { var s = K.suelo(100, 140, 96) + K.r(8, 12, 184, 112, 6, P.blanco, { w: .8 }) + K.c(42, 60, 26, col, { w: .8, op: .55 }) + icono; filas.forEach(function (f, i) { var y = 26 + i * 16; s += K.t(80, y, f[0], { s: 5, b: 1, a: 'start' }) + K.t(116, y, f[1], { s: ajusta(f[1], 72, 5.4), a: 'start' }); if (i) s += K.l('M80 ' + (y - 10) + ' L186 ' + (y - 10), P.gris, { w: .4 }); }); return s + (pie ? K.t(100, 136, pie, { s: 5.8, b: 1 }) : ''); }
  function per(K, x, y, col, e) { e = e || 1; return K.p('M' + (x - 11 * e) + ' ' + (y + 34 * e) + ' Q' + (x - 11 * e) + ' ' + (y + 12 * e) + ' ' + x + ' ' + (y + 12 * e) + ' Q' + (x + 11 * e) + ' ' + (y + 12 * e) + ' ' + (x + 11 * e) + ' ' + (y + 34 * e) + ' Z', col, { w: .8 }) + K.c(x, y, 8 * e, P.piel, { w: .8 }); }

  var L = [
    /* ─────────── GRANDES RELIGIONES ─────────── */
    { id: 're_creencias', fam: 'gr', n: 'Las creencias en el mundo',
      d: function (K) { var D = [['Cristianismo', 28.8, P.azul], ['Islam', 25.6, P.verde], ['Sin religión', 24.2, P.gris], ['Hinduismo', 14.9, P.naranja], ['Budismo', 4.1, P.amarillo], ['Otras', 2.2, P.morado], ['Judaísmo', 0.2, P.rosa]], s = K.suelo(100, 140, 96); D.forEach(function (d, i) { var y = 14 + i * 15, w = Math.max(1.5, d[1] * 3.4); s += K.t(64, y + 8, d[0], { s: 5.4, b: 1, a: 'end' }) + K.r(68, y, w, 11, 2, d[2], { w: .6 }) + K.t(72 + w, y + 8, String(d[1]).replace('.', ',') + ' %', { s: 5.2, b: 1, a: 'start' }); }); return s + K.t(100, 128, 'Población mundial en 2020 · Pew Research Center', { s: 5.4, b: 1 }) + K.t(100, 136, 'unos 7 900 millones de personas', { s: 5 }); },
      intro: 'En el mundo conviven muchas creencias; casi tres de cada cuatro personas se identifican con una religión.',
      q: [['¿Qué religión tiene más seguidores?', 'El cristianismo, con casi el 29 %.'], ['¿Qué porcentaje no tiene religión?', 'Alrededor del 24 %.'], ['¿Cuánto suman cristianismo e islam?', '28,8 + 25,6 = 54,4 %: más de la mitad.']],
      porque: 'Conocer las creencias de otros ayuda a entender sus costumbres y a convivir con respeto.' },
    { id: 're_abrahamicas', fam: 'gr', n: 'Las religiones abrahámicas',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(64, 12, 72, 20, 8, P.arena, { w: .9 }) + K.t(100, 25, 'Abraham', { s: 7, b: 1 }); [['Judaísmo', 'Moisés · Torá', 38, P.azul], ['Cristianismo', 'Jesús · Biblia', 100, P.amarillo], ['Islam', 'Mahoma · Corán', 162, P.verde]].forEach(function (q) { s += K.flecha(100, 32, q[2], 64, P.grisO, { w: .9, p: 3 }) + K.r(q[2] - 30, 66, 60, 30, 5, q[3], { w: .8 }) + K.t(q[2], 79, q[0], { s: 6.4, b: 1 }) + K.t(q[2], 89, q[1], { s: 5 }); }); return s + K.t(100, 116, 'Las tres creen en un solo Dios (monoteísmo)', { s: 5.8, b: 1 }) + K.t(100, 126, 'y reconocen a Abraham como padre en la fe', { s: 5.4 }); },
      intro: 'Judaísmo, cristianismo e islam se llaman religiones abrahámicas porque las tres miran a Abraham como origen.',
      q: [['¿Qué tienen en común las tres?', 'Creen en un solo Dios y reconocen a Abraham.'], ['¿Qué es el monoteísmo?', 'La creencia en un único Dios.'], ['¿Cuál es la más antigua de las tres?', 'El judaísmo.']],
      porque: 'Saber que comparten raíces ayuda a ver lo que une a creyentes de distintas religiones.' },
    { id: 're_judaismo', fam: 'gr', n: 'El judaísmo',
      d: function (K) { return ficha(K, david(K, 42, 60, 17, P.azulO), [['Dios', 'uno solo, Yahvé'], ['Figuras', 'Abraham y Moisés'], ['Libro', 'Tanaj; la Torá es su centro'], ['Templo', 'sinagoga'], ['Día santo', 'sábado (shabat)'], ['Guía', 'rabino']], 'Unos 15 millones de personas en el mundo', P.azul); },
      intro: 'El judaísmo es la religión del pueblo judío; nació en Oriente Próximo hace más de 3 000 años.',
      q: [['¿Cómo se llama el día santo judío?', 'Shabat, el sábado.'], ['¿Qué símbolo lo representa?', 'La estrella de David.'], ['¿Quién guía a la comunidad?', 'El rabino, maestro de la Torá.']],
      porque: 'El judaísmo es la raíz de la que nacieron el cristianismo y, en parte, el islam.' },
    { id: 're_cristianismo', fam: 'gr', n: 'El cristianismo',
      d: function (K) { return ficha(K, cruz(K, 42, 58, 1.1, P.oro), [['Dios', 'Padre, Hijo y Espíritu Santo'], ['Figura', 'Jesús de Nazaret'], ['Libro', 'Biblia'], ['Templo', 'iglesia'], ['Día santo', 'domingo'], ['Guía', 'sacerdote o pastor']], 'La más extendida: unos 2 300 millones de personas', P.amarillo); },
      intro: 'El cristianismo se basa en la vida y las enseñanzas de Jesús de Nazaret, a quien considera Hijo de Dios.',
      q: [['¿Por qué el día santo es el domingo?', 'Porque recuerda la resurrección de Jesús.'], ['¿Qué es la Trinidad?', 'Un solo Dios en tres personas: Padre, Hijo y Espíritu Santo.'], ['¿Dónde nació Jesús según los evangelios?', 'En Belén.']],
      porque: 'El cristianismo ha marcado la historia, el arte y el calendario de América y Europa.' },
    { id: 're_pilares_islam', fam: 'gr', n: 'Los cinco pilares del islam',
      d: function (K) { var Pi = [['Shahada', 'fe en un Dios'], ['Salat', 'orar 5 veces'], ['Zakat', 'limosna'], ['Sawm', 'ayuno'], ['Hach', 'ir a La Meca']], s = K.suelo(100, 140, 96) + K.pl([[10, 34], [100, 12], [190, 34]], P.verde, { w: 1 }) + K.r(10, 34, 180, 6, 0, P.arena, { w: .8 }) + K.r(10, 104, 180, 6, 0, P.arena, { w: .8 }); Pi.forEach(function (q, i) { var x = 18 + i * 34; s += K.r(x + 4, 40, 18, 64, 1, P.blanco, { w: .8 }) + K.t(x + 13, 120, q[0], { s: 6, b: 1 }) + K.t(x + 13, 128, q[1], { s: ajusta(q[1], 32, 4.8) }); }); return s + estrella(K, 100, 25, 5, P.amarillo) + K.t(100, 140, 'Mahoma, La Meca, siglo VII · libro: Corán · templo: mezquita', { s: 4.8, b: 1 }); },
      intro: 'El islam se apoya en cinco prácticas básicas que todo musulmán procura cumplir.',
      q: [['¿Cuántas veces al día rezan los musulmanes?', 'Cinco.'], ['¿En qué mes ayunan?', 'En el mes de Ramadán, desde el alba hasta la puesta del sol.'], ['¿Qué es el hach?', 'La peregrinación a La Meca, al menos una vez en la vida si se puede.']],
      porque: 'Los pilares muestran cómo la fe del islam se vive en la oración, la ayuda y el ayuno.' },
    { id: 're_hinduismo', fam: 'gr', n: 'El hinduismo',
      d: function (K) { return ficha(K, loto(K, 42, 70, 1, P.rosa), [['Lo divino', 'Brahman, con muchas formas'], ['Trimurti', 'Brahma, Visnú y Shiva'], ['Libros', 'Vedas, Bhagavad Gita'], ['Templo', 'mandir'], ['Ideas', 'karma y reencarnación'], ['Dónde', 'sobre todo India y Nepal']], 'Unos 1 200 millones de personas', P.naranja); },
      intro: 'El hinduismo es una de las religiones más antiguas; reúne muchas tradiciones nacidas en la India.',
      q: [['¿Qué es el karma?', 'La idea de que cada acto tiene consecuencias, en esta vida o en otra.'], ['¿Qué dioses forman la Trimurti?', 'Brahma (crea), Visnú (conserva) y Shiva (transforma).'], ['¿Qué flor es un símbolo de pureza?', 'El loto.']],
      porque: 'El hinduismo muestra otra forma de pensar el tiempo: como un ciclo que se repite.' },
    { id: 're_octuple', fam: 'gr', n: 'El budismo: el noble óctuple sendero',
      d: function (K) { var S = ['comprensión correcta', 'intención correcta', 'palabra correcta', 'acción correcta', 'modo de vida correcto', 'esfuerzo correcto', 'atención correcta', 'concentración correcta'], s = K.suelo(100, 140, 96) + rueda(K, 52, 64, 36, P.oro); S.forEach(function (t, i) { s += K.c(108, 18 + i * 13, 4, CO[i], { w: .5 }) + K.t(108, 20 + i * 13, String(i + 1), { s: 4.6, b: 1 }) + K.t(116, 20 + i * 13, t, { s: 5.2, a: 'start' }); }); return s + K.t(100, 126, 'Buda (Siddhartha Gautama) · hace unos 2 500 años', { s: 5.4, b: 1 }) + K.t(100, 135, 'templo budista y estupa · libros: Tripitaka', { s: 5 }); },
      intro: 'El budismo enseña un camino de ocho pasos para liberarse del sufrimiento; la rueda del dharma lo representa.',
      q: [['¿Cuántos radios tiene la rueda del dharma?', 'Ocho, uno por cada paso del sendero.'], ['¿Quién fue Buda?', 'Siddhartha Gautama, un príncipe de la India que buscó el fin del sufrimiento.'], ['¿Qué es la atención correcta?', 'Estar atento a lo que se piensa, se siente y se hace.']],
      porque: 'El budismo propone cambiar la propia mente para vivir con más calma y compasión.' },
    { id: 're_asia', fam: 'gr', n: 'Taoísmo, confucianismo y sintoísmo',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.c(46, 62, 30, P.blanco, { w: 1 }) + K.p('M46 32 A30 30 0 0 1 46 92 A15 15 0 0 1 46 62 A15 15 0 0 0 46 32 Z', P.tinta, { w: .6, negro: 1 }) + K.c(46, 47, 4, P.tinta, { w: .4, negro: 1 }) + K.c(46, 77, 4, P.blanco, { w: .4 }); [['Taoísmo', 'Lao Tse · armonía del yin y el yang', P.gris], ['Confucianismo', 'Confucio · familia, respeto, estudio', P.amarillo], ['Sintoísmo', 'Japón · los kami y el torii', P.rojo]].forEach(function (q, i) { var y = 16 + i * 36; s += K.r(90, y, 98, 30, 4, q[2], { w: .7 }) + K.t(139, y + 12, q[0], { s: 6.4, b: 1 }) + K.t(139, y + 23, q[1], { s: ajusta(q[1], 92, 5) }); }); return s + K.t(46, 108, 'yin y yang', { s: 5.6, b: 1 }) + K.t(100, 132, 'Tres tradiciones de China y Japón que se mezclan en la vida diaria', { s: 5, b: 1 }); },
      intro: 'En China y Japón muchas personas combinan varias tradiciones a la vez: el taoísmo, el confucianismo, el budismo y el sintoísmo.',
      q: [['¿Qué representa el yin y el yang?', 'Dos fuerzas opuestas y complementarias que se equilibran.'], ['¿Qué valora el confucianismo?', 'El respeto a la familia, a los mayores y el estudio.'], ['¿Qué son los kami?', 'Espíritus de la naturaleza y de los antepasados en el sintoísmo.']],
      porque: 'No todas las culturas viven la religión como algo exclusivo: a veces se suman tradiciones.' },
    { id: 're_ramas', fam: 'gr', n: 'Las ramas del cristianismo',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.l('M100 112 L100 90 Q100 80 56 66 M100 90 Q100 78 128 64 M128 64 Q140 52 162 36', P.madera, { w: 4 }) + K.r(56, 112, 88, 16, 6, P.arena, { w: .8 }) + K.t(100, 122.5, 'Jesús y los apóstoles · siglo I', { s: 5.2, b: 1 }); [[42, 56, 'Ortodoxos', 'Grecia, Rusia, Europa del Este', P.azul], [122, 54, 'Católicos', 'Roma · el papa', P.amarillo], [162, 26, 'Protestantes', 'luteranos, evangélicos…', P.verde]].forEach(function (q) { s += K.r(q[0] - 30, q[1] - 10, 60, 22, 6, q[4], { w: .7 }) + K.t(q[0], q[1], q[2], { s: 6, b: 1 }) + K.t(q[0], q[1] + 8, q[3], { s: ajusta(q[3], 56, 4.6) }); }); return s + K.t(64, 90, '1054 Gran Cisma', { s: 5.2, b: 1, a: 'end' }) + K.t(150, 76, '1517 Reforma', { s: 5.2, b: 1, a: 'start' }) + K.t(150, 84, 'de Lutero', { s: 5, a: 'start' }); },
      intro: 'El cristianismo se dividió en grandes ramas a lo largo de la historia, aunque todas siguen a Jesús.',
      q: [['¿Qué pasó en 1054?', 'Se separaron la Iglesia de Oriente (ortodoxa) y la de Occidente (católica).'], ['¿Quién inició la Reforma protestante?', 'Martín Lutero, en 1517.'], ['¿Qué tienen en común todas las ramas?', 'La fe en Jesucristo y la Biblia.']],
      porque: 'Las divisiones explican por qué hoy hay iglesias distintas en un mismo barrio.' },
    { id: 're_comparada', fam: 'gr', n: 'Cinco religiones en una tabla',
      d: function (K) { var C = ['Religión', 'Libro', 'Templo', 'Día'], F = [['Judaísmo', 'Tanaj', 'sinagoga', 'sábado'], ['Cristianismo', 'Biblia', 'iglesia', 'domingo'], ['Islam', 'Corán', 'mezquita', 'viernes'], ['Hinduismo', 'Vedas', 'mandir', 'varía'], ['Budismo', 'Tripitaka', 'templo', 'luna llena']], X = [12, 62, 104, 146], W = [50, 42, 42, 42], s = K.suelo(100, 140, 96); C.forEach(function (c, j) { s += K.r(X[j], 14, W[j], 16, 0, P.azulO, { w: .5, op: .8 }) + K.t(X[j] + W[j] / 2, 25, c, { s: 6, b: 1, c: P.blanco }); }); F.forEach(function (f, i) { var y = 30 + i * 18; f.forEach(function (v, j) { s += K.r(X[j], y, W[j], 18, 0, i % 2 ? P.blanco : P.gris, { w: .4 }) + K.t(X[j] + W[j] / 2, y + 11.5, v, { s: ajusta(v, W[j] - 4, 5.6), b: j === 0 ? 1 : 0 }); }); }); return s + K.t(100, 136, 'Busca una más: el sijismo (libro, templo, día)', { s: 5.4, b: 1 }); },
      intro: 'Comparar las religiones en una tabla ayuda a ver en qué se parecen y en qué se diferencian.',
      q: [['¿Qué día es especial para los musulmanes?', 'El viernes, día de la oración en comunidad.'], ['¿Cómo se llama el templo judío?', 'Sinagoga.'], ['¿Qué tres religiones tienen un día fijo a la semana?', 'Judaísmo, cristianismo e islam.']],
      porque: 'Ordenar la información en una tabla permite comparar de un vistazo.' },
    /* ─────────── LIBROS SAGRADOS ─────────── */
    { id: 're_biblia', fam: 'lib', n: 'La biblioteca de la Biblia',
      d: function (K) { var s = K.suelo(100, 140, 96), est = function (y, grupos, x0) { var r = K.r(10, y + 30, 180, 4, 0, P.madera, { w: .7 }), x = x0; grupos.forEach(function (g, j) { var a = g[1] * 3.4; for (var k = 0; k < g[1]; k++) r += K.r(x + k * 3.4, y + 4 + (k % 3), 3, 26 - (k % 3), .5, g[2], { w: .3 }); r += K.t(x + a / 2, y + 42 + (j % 2) * 8, g[0] + ' ' + g[1], { s: ajusta(g[0] + ' 00', Math.max(a, 26), 5), b: 1 }); x += a + 3; }); return r; }; s += K.t(12, 16, 'Antiguo Testamento · 46', { s: 6, b: 1, a: 'start' }) + est(16, [['Pentateuco', 5, P.rojo], ['Históricos', 16, P.amarillo], ['Sapienciales', 7, P.verde], ['Proféticos', 18, P.azul]], 14); s += K.t(12, 76, 'Nuevo Testamento · 27', { s: 6, b: 1, a: 'start' }) + est(76, [['Evangelios', 4, P.oro], ['Hechos', 1, P.naranja], ['Cartas', 21, P.morado], ['Apoc.', 1, P.rosa]], 14); return s + K.t(100, 138, 'Biblia católica: 73 libros · Biblia protestante: 66', { s: 5.4, b: 1 }); },
      intro: '«Biblia» significa «los libros»: es una biblioteca escrita durante siglos, dividida en Antiguo y Nuevo Testamento.',
      q: [['¿Cuántos libros tiene el Nuevo Testamento?', '27.'], ['¿Por qué la Biblia protestante tiene 66?', 'Porque su Antiguo Testamento tiene 39 libros en lugar de 46.'], ['¿Qué cuentan los evangelios?', 'La vida y las enseñanzas de Jesús.']],
      porque: 'Ver la Biblia como una biblioteca ayuda a entender que tiene libros de géneros distintos.' },
    { id: 're_cita', fam: 'lib', n: 'Cómo se lee una cita bíblica',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(40, 34, 120, 36, 6, P.pergamino, { w: 1 }) + K.t(100, 60, 'Jn 3, 16', { s: 20, b: 1 }); [[66, 'libro', 'Evangelio de Juan', 34, 20], [118, 'capítulo', '3', 100, 92], [146, 'versículo', '16', 166, 20]].forEach(function (q) { var arriba = q[4] < 34; s += K.l('M' + q[0] + ' ' + (arriba ? 36 : 68) + ' L' + q[3] + ' ' + (arriba ? q[4] + 4 : q[4] - 8), P.grisO, { w: .6 }) + K.t(q[3], arriba ? q[4] - 2 : q[4], q[1], { s: 5.6, b: 1 }) + K.t(q[3], arriba ? q[4] + 6 : q[4] + 8, q[2], { s: 5 }); }); return s + K.t(100, 122, 'Gn 1, 1-5 = Génesis, capítulo 1, versículos del 1 al 5', { s: 5.4, b: 1 }) + K.t(100, 132, 'la coma separa capítulo y versículo · el guion, un tramo', { s: 5 }); },
      intro: 'Las citas bíblicas indican el libro abreviado, el capítulo y el versículo para encontrar un texto.',
      q: [['¿Qué significa «Mt 5, 3-10»?', 'Evangelio de Mateo, capítulo 5, versículos del 3 al 10.'], ['¿Qué separa la coma?', 'El capítulo del versículo.'], ['Busca en el índice la abreviatura de Lucas.', 'Lc.']],
      porque: 'Este sistema permite que cualquiera encuentre el mismo texto en cualquier edición.' },
    { id: 're_coran', fam: 'lib', n: 'El Corán',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.l('M64 118 L136 76 M136 118 L64 76', P.madera, { w: 4 }) + K.p('M100 80 L56 70 L56 36 L100 46 Z', P.pergamino, { w: .9 }) + K.p('M100 80 L144 70 L144 36 L100 46 Z', P.pergamino, { w: .9 }); for (var i = 0; i < 4; i++) s += K.l('M' + (62) + ' ' + (46 + i * 7) + ' L94 ' + (54 + i * 7) + ' M106 ' + (54 + i * 7) + ' L138 ' + (46 + i * 7), P.verdeO, { w: .8 }); return s + K.t(30, 30, '114 suras', { s: 6, b: 1 }) + K.t(30, 38, '(capítulos)', { s: 5 }) + K.t(170, 30, 'en árabe', { s: 6, b: 1 }) + K.t(170, 38, 'siglo VII', { s: 5 }) + K.t(30, 98, 'se lee de', { s: 5.4, b: 1 }) + K.t(30, 106, 'derecha a', { s: 5.4, b: 1 }) + K.t(30, 114, 'izquierda', { s: 5.4, b: 1 }) + K.t(170, 98, 'atril', { s: 5.4, b: 1 }) + K.t(170, 106, '(rehal)', { s: 5 }) + K.t(100, 136, 'Para los musulmanes, palabra de Dios revelada a Mahoma', { s: 5.2, b: 1 }); },
      intro: 'El Corán es el libro sagrado del islam; se divide en 114 suras y se escribió en árabe.',
      q: [['¿Cuántas suras tiene el Corán?', '114.'], ['¿En qué lengua se escribió?', 'En árabe.'], ['¿Para qué sirve el atril?', 'Para sostener el libro con respeto, sin dejarlo en el suelo.']],
      porque: 'El cuidado con que se trata el libro muestra el valor que tiene para quienes creen.' },
    { id: 're_tora', fam: 'lib', n: 'El rollo de la Torá',
      d: function (K) { var B = ['Génesis', 'Éxodo', 'Levítico', 'Números', 'Deuteronomio'], s = K.suelo(100, 140, 96) + K.r(36, 26, 128, 84, 0, P.pergamino, { w: .9 }); [30, 170].forEach(function (x) { s += K.r(x - 6, 26, 12, 84, 6, P.madera, { w: .8 }) + K.r(x - 2, 14, 4, 12, 1, P.oro, { w: .6 }) + K.r(x - 2, 110, 4, 12, 1, P.oro, { w: .6 }) + K.c(x, 14, 4, P.oro, { w: .6 }); }); B.forEach(function (b, i) { s += K.t(100, 42 + i * 14, (i + 1) + '. ' + b, { s: 6.4, b: 1 }); }); return s + K.t(100, 132, 'Escrita a mano en hebreo · se lee de derecha a izquierda', { s: 5.2, b: 1 }); },
      intro: 'La Torá son los cinco primeros libros de la Biblia hebrea; en la sinagoga se lee de un rollo escrito a mano.',
      q: [['¿Qué libros forman la Torá?', 'Génesis, Éxodo, Levítico, Números y Deuteronomio.'], ['¿Cómo se llaman en el cristianismo?', 'Pentateuco.'], ['¿Por qué se escribe a mano?', 'Por respeto: un escriba la copia letra a letra con mucho cuidado.']],
      porque: 'Los mismos cinco libros son sagrados para judíos y cristianos.' },
    G('re_libros_mundo', 'lib', 'Libros sagrados del mundo', [['Tanaj', 'judaísmo'], ['Biblia', 'cristianismo'], ['Corán', 'islam'], ['Vedas', 'hinduismo'], ['Tripitaka', 'budismo'], ['Tao Te Ching', 'taoísmo'], ['Gurú Granth Sahib', 'sijismo'], ['Popol Vuh', 'pueblo maya k’iche’']], 2, 14, 24, 'Cada libro es un tesoro de su cultura', 'Muchas religiones guardan sus enseñanzas en libros que consideran sagrados.', [['¿Qué libro sagrado es de América?', 'El Popol Vuh, del pueblo maya k’iche’.'], ['¿Cuál es el libro del budismo?', 'El Tripitaka, «las tres cestas».'], ['¿Qué libro comparten en parte judíos y cristianos?', 'El Tanaj, que coincide con el Antiguo Testamento.']], 'Los libros sagrados también son literatura, historia y arte.', { s: 7.4, s2: 5.4 }),
    G('re_evangelistas', 'lib', 'Los cuatro evangelistas y sus símbolos', [['Mateo', 'un hombre alado'], ['Marcos', 'un león'], ['Lucas', 'un toro'], ['Juan', 'un águila']], 2, 18, 44, 'Aparecen así en pórticos, vitrales y retablos', 'Los cuatro evangelios llevan el nombre de sus autores; el arte los representa con un símbolo.', [['¿Qué símbolo tiene Juan?', 'Un águila.'], ['¿Cuántos evangelios hay?', 'Cuatro: Mateo, Marcos, Lucas y Juan.'], ['¿Dónde se pueden ver estos símbolos?', 'En fachadas de iglesias, vitrales y libros antiguos.']], 'Conocer los símbolos permite «leer» el arte de iglesias y museos.', { s: 9, s2: 6 }),
    /* ─────────── RELATOS BÍBLICOS ─────────── */
    G('re_creacion', 'bib', 'La creación en siete días', [['Día 1', 'la luz'], ['Día 2', 'el cielo'], ['Día 3', 'tierra y plantas'], ['Día 4', 'sol, luna, estrellas'], ['Día 5', 'peces y aves'], ['Día 6', 'animales y personas'], ['Día 7', 'descanso']], 4, 20, 40, 'Génesis 1 · un relato que habla del sentido, no de ciencia', 'El primer capítulo del Génesis cuenta la creación del mundo como una semana de trabajo y descanso.', [['¿Qué se crea el cuarto día?', 'El sol, la luna y las estrellas.'], ['¿Qué día se descansa?', 'El séptimo.'], ['¿Contradice este relato a la ciencia?', 'Es un relato religioso sobre el sentido del mundo, no una explicación científica.']], 'El relato inspira la semana de siete días con un día de descanso.', { s: 7, s2: 5 }),
    { id: 're_arca', fam: 'bib', n: 'El arca de Noé',
      d: function (K) { var s = K.r(0, 110, 200, 30, 0, P.agua, { w: 0 }); [[P.rojo, 70], [P.naranja, 64], [P.amarillo, 58], [P.verde, 52], [P.azul, 46], [P.morado, 40]].forEach(function (a) { s += K.l('M' + (100 - a[1] - 20) + ' 106 A' + (a[1] + 20) + ' ' + (a[1] + 20) + ' 0 0 1 ' + (100 + a[1] + 20) + ' 106', a[0], { w: 4 }); }); s += K.p('M40 92 L160 92 L148 116 L52 116 Z', P.madera, { w: 1 }) + K.r(74, 70, 52, 22, 2, P.arena, { w: .9 }) + K.pl([[70, 70], [100, 56], [130, 70]], P.madera, { w: .9 }) + K.r(96, 78, 8, 14, 1, P.tinta, { w: .4, negro: 1 }); [[60, 86, P.gris], [66, 86, P.gris], [134, 86, P.naranja], [140, 86, P.naranja]].forEach(function (a) { s += K.c(a[0], a[1], 3, a[2], { w: .5 }); }); s += K.l('M30 30 q4 -4 8 0 q4 -4 8 0', P.tinta, { w: .8 }); return s + K.t(100, 130, 'Génesis 6-9 · el arcoíris, señal de una alianza', { s: 5.6, b: 1, c: P.tinta }); },
      intro: 'El relato del diluvio cuenta cómo Noé construyó un arca para salvar a su familia y a una pareja de cada animal.',
      q: [['¿Qué significa el arcoíris en el relato?', 'La promesa de Dios de no volver a destruir la tierra.'], ['¿Qué ave trajo una rama de olivo?', 'Una paloma.'], ['¿En qué otras culturas hay relatos de un diluvio?', 'En Mesopotamia (Gilgamesh) y en relatos indígenas de América, entre otros.']],
      porque: 'Muchos pueblos antiguos contaron historias de grandes inundaciones.' },
    { id: 're_exodo', fam: 'bib', n: 'El éxodo: de Egipto a Canaán',
      d: function (K) { var s = K.r(0, 0, 200, 150, 0, P.arena, { w: 0, op: .5 }) + K.p('M72 150 C70 120 86 100 80 70 C78 56 90 50 96 60 C100 80 88 110 92 150 Z', P.agua, { w: .6 }) + K.r(14, 96, 44, 30, 3, P.amarillo, { w: .8 }) + K.pl([[24, 96], [36, 80], [48, 96]], P.oro, { w: .6 }) + K.pl([[112, 104], [130, 74], [148, 104]], P.grisO, { w: .8 }) + K.r(150, 20, 42, 26, 4, P.verde, { w: .8 }); s += K.l('M50 100 C64 96 74 92 86 88 C100 86 110 96 124 96 C140 92 140 70 150 52 C156 44 160 42 168 40', P.rojoO, { w: 1.2, d: '3 2' }); return s + K.t(36, 120, 'Egipto', { s: 6.4, b: 1 }) + K.t(84, 140, 'mar Rojo', { s: 5.4, b: 1 }) + K.t(130, 114, 'monte Sinaí', { s: 5.4, b: 1 }) + K.t(171, 32, 'Canaán', { s: 5.8, b: 1 }) + K.t(171, 40, 'tierra prometida', { s: 4.6 }) + K.t(100, 16, 'Moisés guía al pueblo: 40 años en el desierto', { s: 6, b: 1 }) + K.t(100, 24, 'esquema, no a escala', { s: 4.6 }); },
      intro: 'El libro del Éxodo narra cómo Moisés sacó de Egipto al pueblo de Israel hacia la tierra prometida.',
      q: [['¿Qué mar cruzaron según el relato?', 'El mar Rojo.'], ['¿Qué recibió Moisés en el monte Sinaí?', 'Las tablas de la Ley, los Diez Mandamientos.'], ['¿Qué fiesta judía recuerda la salida de Egipto?', 'La Pascua judía (Pésaj).']],
      porque: 'El éxodo es un relato de liberación que ha inspirado a muchos pueblos oprimidos.' },
    { id: 're_decalogo', fam: 'bib', n: 'Los Diez Mandamientos',
      d: function (K) { var A = ['Amar a Dios', 'No usar su nombre en vano', 'Santificar las fiestas', 'Honrar a los padres', 'No matar'], B = ['No cometer actos impuros', 'No robar', 'No mentir', 'No desear impuramente', 'No codiciar lo ajeno'], s = K.suelo(100, 140, 96), tabla = function (x, L, n0) { var r = K.p('M' + x + ' 116 L' + x + ' 34 A38 22 0 0 1 ' + (x + 76) + ' 34 L' + (x + 76) + ' 116 Z', P.gris, { w: 1 }); L.forEach(function (t, i) { var tx = (n0 + i) + ' ' + t; r += K.t(x + 38, 42 + i * 15, tx, { s: ajusta(tx, 70, 5.4), b: 1 }); }); return r; }; return s + tabla(18, A, 1) + tabla(106, B, 6) + K.t(100, 132, 'Éxodo 20 · Deuteronomio 5 · numeración católica', { s: 5.2, b: 1 }); },
      intro: 'Los Diez Mandamientos son normas que, según el Éxodo, Dios entregó a Moisés en el monte Sinaí.',
      q: [['¿Qué mandamientos tratan de la relación con los demás?', 'Del 4 al 10.'], ['¿Qué mandamientos coinciden con leyes actuales?', 'No matar, no robar y, en parte, no mentir (falso testimonio).'], ['¿Por qué se dibujan en dos tablas?', 'Por el relato: Moisés bajó del monte con dos tablas de piedra.']],
      porque: 'Muchas normas de convivencia actuales tienen raíces en códigos morales antiguos.' },
    { id: 're_tierra_jesus', fam: 'bib', n: 'La tierra de Jesús',
      d: function (K) { var s = K.r(0, 0, 30, 150, 0, P.agua, { w: .1 }) + K.r(30, 0, 170, 150, 0, P.arena, { w: .1, op: .45 }) + K.e(140, 36, 9, 12, P.agua, { w: .6 }) + K.l('M140 48 C136 64 146 80 140 96 C136 104 142 108 140 112', P.azulO, { w: 1.4 }) + K.e(140, 122, 7, 14, P.agua, { w: .6 }); [[86, 36, 'GALILEA'], [86, 72, 'SAMARIA'], [86, 108, 'JUDEA']].forEach(function (q) { s += K.t(q[0], q[1], q[2], { s: 6.4, b: 1, c: P.grisO }); }); [[110, 44, 'Nazaret', 'end'], [132, 28, 'Cafarnaún', 'end'], [124, 112, 'Jerusalén', 'end'], [118, 124, 'Belén', 'end']].forEach(function (q) { s += K.c(q[0] + 4, q[1] - 2, 2, P.rojoO, { w: .4 }) + K.t(q[0], q[1], q[2], { s: 5.2, b: 1, a: q[3] }); }); return s + K.t(156, 38, 'mar de Galilea', { s: 4.8, a: 'start' }) + K.t(150, 80, 'río Jordán', { s: 4.8, a: 'start' }) + K.t(152, 124, 'mar Muerto', { s: 4.8, a: 'start' }) + K.t(15, 66, 'mar', { s: 3.8, b: 1, c: P.azulO }) + K.t(15, 72, 'Mediterráneo', { s: 3.8, b: 1, c: P.azulO }) + K.t(100, 144, 'esquema, no a escala', { s: 4.6 }); },
      intro: 'Jesús vivió en Palestina, en el siglo I, una región dividida en Galilea, Samaria y Judea.',
      q: [['¿En qué ciudad nació Jesús?', 'En Belén, en Judea.'], ['¿Dónde creció?', 'En Nazaret, en Galilea.'], ['¿Qué río une el mar de Galilea con el mar Muerto?', 'El río Jordán.']],
      porque: 'Situar los relatos en un mapa ayuda a entenderlos como hechos de un tiempo y un lugar.' },
    { id: 're_vida_jesus', fam: 'bib', n: 'Momentos de la vida de Jesús',
      d: function (K) { var M = [['nace', 'Belén'], ['crece', 'Nazaret'], ['bautismo', 'río Jordán'], ['predica', 'Galilea'], ['muerte y resurrección', 'Jerusalén']], s = K.suelo(100, 140, 96) + K.l('M14 70 L186 70', P.grisO, { w: 2 }); M.forEach(function (m, i) { var x = 22 + i * 39, up = i % 2 === 0; s += K.c(x, 70, 5, CO[i], { w: .8 }) + K.l('M' + x + ' ' + (up ? 64 : 76) + ' L' + x + ' ' + (up ? 50 : 90), P.grisO, { w: .5 }) + K.t(x, up ? 38 : 100, m[0], { s: ajusta(m[0], 44, 6), b: 1 }) + K.t(x, up ? 46 : 108, m[1], { s: 5 }); }); return s + K.t(100, 20, 'Siglo I, en tiempos del Imperio romano', { s: 5.8, b: 1 }) + K.t(100, 132, 'Lo cuentan los cuatro evangelios', { s: 5.6, b: 1 }); },
      intro: 'Los evangelios cuentan la vida de Jesús desde su nacimiento en Belén hasta su muerte y resurrección en Jerusalén.',
      q: [['¿Dónde fue bautizado Jesús?', 'En el río Jordán, por Juan el Bautista.'], ['¿Qué imperio gobernaba entonces?', 'El Imperio romano.'], ['¿Qué celebra la Pascua cristiana?', 'La resurrección de Jesús.']],
      porque: 'Una línea del tiempo ordena los relatos y muestra cómo se suceden.' },
    G('re_parabolas', 'bib', 'Las parábolas de Jesús', [['El buen samaritano', 'ayudar a quien lo necesita'], ['El hijo pródigo', 'el perdón del padre'], ['El sembrador', 'acoger la palabra'], ['La oveja perdida', 'nadie sobra'], ['Los talentos', 'hacer crecer los dones'], ['El grano de mostaza', 'lo pequeño crece']], 2, 20, 28, 'Una parábola enseña con una historia sencilla', 'Jesús enseñaba con parábolas: relatos breves de la vida diaria con un mensaje.', [['¿Qué enseña el buen samaritano?', 'Que el prójimo es cualquiera que necesita ayuda.'], ['¿Qué hace el padre del hijo pródigo?', 'Lo recibe con una fiesta y lo perdona.'], ['Inventa una parábola sobre la amistad.', 'Respuesta abierta.']], 'Las historias se recuerdan mejor que las normas.', { s: 7.4, s2: 5.4 }),
    { id: 're_bienaventuranzas', fam: 'bib', n: 'Las bienaventuranzas',
      d: function (K) { var B = ['los pobres de espíritu', 'los que lloran', 'los mansos', 'los que tienen hambre y sed de justicia', 'los misericordiosos', 'los limpios de corazón', 'los que trabajan por la paz', 'los perseguidos por la justicia'], s = K.suelo(50, 124, 46) + K.pl([[8, 124], [50, 52], [92, 124]], P.verde, { w: 1 }) + per(K, 50, 40, P.blanco, .6); B.forEach(function (b, i) { s += K.t(98, 22 + i * 12.5, (i + 1) + ' ' + b, { s: ajusta(b + '00', 96, 5.4), a: 'start' }); }); return s + K.t(144, 12, 'Felices…', { s: 6.4, b: 1 }) + K.t(100, 136, 'Sermón del monte · Mateo 5, 3-10', { s: 5.6, b: 1 }); },
      intro: 'En el sermón del monte, Jesús llama felices a quienes viven valores que el mundo no suele premiar.',
      q: [['¿Cuántas bienaventuranzas hay en Mateo?', 'Ocho.'], ['¿Qué significa «misericordioso»?', 'Que se compadece y ayuda a quien sufre.'], ['¿Cuál se relaciona con la cultura de paz?', '«Felices los que trabajan por la paz».']],
      porque: 'Las bienaventuranzas resumen el estilo de vida que propone el cristianismo.' },
    G('re_apostoles', 'bib', 'Los doce apóstoles', [['Pedro', ''], ['Andrés', ''], ['Santiago el Mayor', ''], ['Juan', ''], ['Felipe', ''], ['Bartolomé', ''], ['Tomás', ''], ['Mateo', ''], ['Santiago el Menor', ''], ['Judas Tadeo', ''], ['Simón', ''], ['Judas Iscariote', 'luego, Matías']], 3, 16, 20, 'Pedro y Andrés, Santiago y Juan eran pescadores', 'Jesús eligió a doce discípulos, los apóstoles, para que continuaran su misión.', [['¿Quiénes eran hermanos?', 'Pedro y Andrés; Santiago el Mayor y Juan.'], ['¿Quién sustituyó a Judas Iscariote?', 'Matías.'], ['¿Qué apóstol dudó de la resurrección?', 'Tomás.']], 'El número doce recuerda las doce tribus de Israel.', { s: 6.4, s2: 4.8, gy: 4 })
  ];
  MO.agregar('religion', L, { nombre: 'Religión y cultura religiosa', familias: FAM, materias: /^(religion)$/ });
})();
