/* b6_lib_calculo.js — Cálculo: modelos 1–25 de 50 (primera entrega). Materia `calculo`. Prefijo `ca_`.
   Cargar después de b6_modelos.js. No repite geo_mira, geo_paso, fis_mru, mat_*, geo_*, gm_*, recipientes, qui_dilucion, bloques ni tec_iso.
   Familias: funciones, límites y continuidad, derivadas, aplicaciones de la derivada (este archivo y el 2); integrales, sucesiones y series, modelos y ecuaciones diferenciales (b6_lib_calculo2.js).
   Helpers de gráficas: Gr (ejes y rejilla), curva, area, seg, punto, hueco — expuestos en window.EU_CALC_K para el archivo 2. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('ca_dominio')) return;
  var P = { azul: '#A8C8E8', azulO: '#2F5F92', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', moradoO: '#6A4A96', naranja: '#F4C090', naranjaO: '#B8661E', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', tinta: '#2A2420', blanco: '#FFFFFF', madera: '#C89A62', cesped: '#9CCB7A' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { fun: 'Funciones', lim: 'Límites y continuidad', der: 'Derivadas', apl: 'Aplicaciones de la derivada', int: 'Integrales', ser: 'Sucesiones y series', edo: 'Modelos y ecuaciones diferenciales' };
  function nf(v, d) { var s = d == null ? String(+(+v).toFixed(4)) : (+v).toFixed(d); return s.replace('.', ',').replace('-', '−'); }
  function miles(n) { return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ' '); }
  function ajusta(t, ancho, max) { return +Math.min(max, ancho / (String(t).length * .54)).toFixed(2); }
  function f1(v) { return (+v).toFixed(1); }
  function Gr(K, o) {
    var b = o.b, xr = o.x, yr = o.y;
    var X = function (v) { return b[0] + (v - xr[0]) / (xr[1] - xr[0]) * b[2]; }, Y = function (v) { return b[1] + b[3] - (v - yr[0]) / (yr[1] - yr[0]) * b[3]; };
    var s = K.r(b[0], b[1], b[2], b[3], 0, P.blanco, { w: .4 }), i, v;
    var X0 = X(Math.min(Math.max(0, xr[0]), xr[1])), Y0 = Y(Math.min(Math.max(0, yr[0]), yr[1]));
    if (o.dx) for (i = Math.ceil(xr[0] / o.dx - 1e-9); (v = i * o.dx) <= xr[1] + 1e-9; i++) s += K.l('M' + f1(X(v)) + ' ' + b[1] + ' L' + f1(X(v)) + ' ' + (b[1] + b[3]), P.gris, { w: .3 });
    if (o.dy) for (i = Math.ceil(yr[0] / o.dy - 1e-9); (v = i * o.dy) <= yr[1] + 1e-9; i++) s += K.l('M' + b[0] + ' ' + f1(Y(v)) + ' L' + (b[0] + b[2]) + ' ' + f1(Y(v)), P.gris, { w: .3 });
    s += K.l('M' + b[0] + ' ' + f1(Y0) + ' L' + (b[0] + b[2]) + ' ' + f1(Y0), P.tinta, { w: .7 }) + K.l('M' + f1(X0) + ' ' + b[1] + ' L' + f1(X0) + ' ' + (b[1] + b[3]), P.tinta, { w: .7 });
    (o.ex || []).forEach(function (e) { var val = Array.isArray(e) ? e[0] : e, tx = Array.isArray(e) ? e[1] : nf(e); s += K.l('M' + f1(X(val)) + ' ' + f1(Y0 - 1.5) + ' L' + f1(X(val)) + ' ' + f1(Y0 + 1.5), P.tinta, { w: .6 }) + K.t(X(val), Y0 + 6.5, tx, { s: 4.2 }); });
    (o.ey || []).forEach(function (e) { var val = Array.isArray(e) ? e[0] : e, tx = Array.isArray(e) ? e[1] : nf(e); s += K.l('M' + f1(X0 - 1.5) + ' ' + f1(Y(val)) + ' L' + f1(X0 + 1.5) + ' ' + f1(Y(val)), P.tinta, { w: .6 }) + K.t(X0 - 2.5, Y(val) + 1.5, tx, { s: 4.2, a: 'end' }); });
    return { s: s, X: X, Y: Y, xr: xr, yr: yr, b: b, X0: X0, Y0: Y0 };
  }
  function curva(K, G, f, a, b, col, o) { o = o || {}; var n = o.n || 100, d = '', on = false, m = (G.yr[1] - G.yr[0]) * .002, lo = G.yr[0] - m, hi = G.yr[1] + m; for (var i = 0; i <= n; i++) { var x = a + (b - a) * i / n, y = f(x); if (!isFinite(y) || y < lo || y > hi) { on = false; continue; } d += (on ? ' L' : ' M') + f1(G.X(x)) + ' ' + f1(G.Y(y)); on = true; } return d ? K.l(d.trim(), col, { w: o.w || 1.4, d: o.d }) : ''; }
  function area(K, G, f, a, b, col, g) { g = g || function () { return 0; }; var n = 60, d = 'M' + f1(G.X(a)) + ' ' + f1(G.Y(g(a))), i, x; for (i = 0; i <= n; i++) { x = a + (b - a) * i / n; d += ' L' + f1(G.X(x)) + ' ' + f1(G.Y(f(x))); } for (i = n; i >= 0; i--) { x = a + (b - a) * i / n; d += ' L' + f1(G.X(x)) + ' ' + f1(G.Y(g(x))); } return K.p(d + ' Z', col, { w: .3, op: .7 }); }
  function seg(K, G, x1, y1, x2, y2, col, o) { return K.l('M' + f1(G.X(x1)) + ' ' + f1(G.Y(y1)) + ' L' + f1(G.X(x2)) + ' ' + f1(G.Y(y2)), col, o || { w: .8 }); }
  function punto(K, G, x, y, col) { return K.c(G.X(x), G.Y(y), 1.9, col || P.tinta, { w: .5, negro: 1 }); }
  function hueco(K, G, x, y) { return K.c(G.X(x), G.Y(y), 1.9, P.blanco, { w: .8 }); }
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var a1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), a2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + a1 * .35, q[0], { s: +a1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +a2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  window.EU_CALC_K = { P: P, CO: CO, FAM: FAM, nf: nf, miles: miles, ajusta: ajusta, f1: f1, Gr: Gr, curva: curva, area: area, seg: seg, punto: punto, hueco: hueco, G: G };
  var PI = Math.PI;

  var L = [
    /* ─────────── FUNCIONES ─────────── */
    { id: 'ca_dominio', fam: 'fun', n: 'Dominio y recorrido',
      d: function (K) { var g = Gr(K, { b: [20, 14, 170, 96], x: [-1, 6], y: [-1, 3], dx: 1, dy: 1, ex: [1, 2, 3, 4, 5, 6], ey: [1, 2, 3] }), s = g.s; s += K.r(g.X(1), g.Y0 - 1.6, g.X(6) - g.X(1), 3.2, 0, P.verde, { w: .3 }) + K.r(g.X0 - 1.6, g.b[1], 3.2, g.Y0 - g.b[1], 0, P.naranja, { w: .3 }) + curva(K, g, function (x) { return Math.sqrt(x - 1); }, 1, 6, P.azulO, { w: 1.6 }) + punto(K, g, 1, 0, P.azulO); return s + K.t(g.X(4.6), g.Y(2.6), 'f(x) = √(x − 1)', { s: 6, b: 1 }) + K.t(g.X(3.5), g.Y0 + 15, 'dominio: x ≥ 1', { s: 5.4, b: 1, c: P.verdeO }) + K.t(g.X0 + 4, g.b[1] + 7, 'recorrido: y ≥ 0', { s: 5.4, b: 1, a: 'start', c: P.naranjaO }) + K.t(100, 128, 'Dentro de la raíz no puede haber un número negativo', { s: 5.4, b: 1 }); },
      intro: 'El dominio son los valores de x que se pueden usar; el recorrido, los valores que toma y.',
      q: [['¿Cuál es el dominio de f(x) = √(x − 1)?', 'x ≥ 1.'], ['¿Cuánto vale f(5)?', '√4 = 2.'], ['¿Qué dominio tiene g(x) = 1/x?', 'Todos los números menos el 0.']],
      porque: 'Antes de calcular hay que saber dónde tiene sentido la fórmula.' },
    { id: 'ca_familias', fam: 'fun', n: 'Familias de funciones',
      d: function (K) { var F = [['Lineal', 'y = x/2 + 1', function (x) { return x / 2 + 1; }], ['Cuadrática', 'y = x² − 2', function (x) { return x * x - 2; }], ['Cúbica', 'y = x³ − 3x', function (x) { return x * x * x - 3 * x; }], ['Exponencial', 'y = 2ˣ', function (x) { return Math.pow(2, x); }], ['Logarítmica', 'y = ln x', function (x) { return Math.log(x); }], ['Racional', 'y = 1/x', function (x) { return 1 / x; }]], s = ''; F.forEach(function (f, i) { var x0 = 12 + (i % 3) * 62, y0 = 12 + Math.floor(i / 3) * 62, g = Gr(K, { b: [x0, y0, 54, 40], x: [-3, 3], y: [-3, 3] }); s += g.s + curva(K, g, f[2], -3, 3, P.azulO, { w: 1.5, n: 120 }) + K.t(x0 + 27, y0 + 48, f[0], { s: 6, b: 1 }) + K.t(x0 + 27, y0 + 55, f[1], { s: 5 }); }); return s + K.t(100, 141, 'Cada familia tiene una forma que se reconoce', { s: 5.4, b: 1 }); },
      intro: 'Las funciones más usadas se agrupan en familias, cada una con una gráfica característica.',
      q: [['¿Qué familia da una recta?', 'La lineal.'], ['¿Qué gráfica tiene forma de U?', 'La cuadrática (parábola).'], ['¿Cuál crece cada vez más deprisa?', 'La exponencial.']],
      porque: 'Reconocer la forma ayuda a elegir el modelo adecuado para cada problema.' },
    { id: 'ca_composicion', fam: 'fun', n: 'Composición de funciones',
      d: function (K) { var bola = function (x, t) { return K.c(x, 60, 9, P.amarillo, { w: .8 }) + K.t(x, 62.2, t, { s: 6.4, b: 1 }); }, s = K.suelo(100, 78, 92) + bola(20, '2') + K.flecha(29, 60, 44, 60, P.tinta, { w: 1, p: 3 }) + K.caja(46, 46, 36, 28, 6, P.azul, { w: .8 }) + K.t(64, 62, 'g(x) = x + 3', { s: 4.8, b: 1 }) + K.flecha(88, 60, 97, 60, P.tinta, { w: 1, p: 3 }) + bola(108, '5') + K.flecha(118, 60, 124, 60, P.tinta, { w: 1, p: 3 }) + K.caja(126, 46, 36, 28, 6, P.verde, { w: .8 }) + K.t(144, 62, 'f(x) = x²', { s: 5.2, b: 1 }) + K.flecha(168, 60, 172, 60, P.tinta, { w: 1, p: 3 }) + bola(182, '25'); return s + K.t(64, 28, 'g', { s: 7, b: 1 }) + K.t(64, 37, 'suma 3', { s: 5.2 }) + K.t(144, 28, 'f', { s: 7, b: 1 }) + K.t(144, 37, 'eleva al cuadrado', { s: 5 }) + K.t(100, 98, '(f ∘ g)(2) = f(g(2)) = f(5) = 25', { s: 6.4, b: 1 }) + K.t(100, 110, 'Al revés: (g ∘ f)(2) = g(4) = 7', { s: 5.6 }) + K.t(100, 130, 'Primero actúa la función de la derecha', { s: 5.6, b: 1 }); },
      intro: 'Componer funciones es aplicar una y, al resultado, aplicar otra, como dos máquinas en cadena.',
      q: [['Calcula (f ∘ g)(1).', 'g(1) = 4; f(4) = 16.'], ['¿Da lo mismo (g ∘ f)(1)?', 'No: f(1) = 1; g(1) = 4.'], ['Escribe la fórmula de (f ∘ g)(x).', '(x + 3)².']],
      porque: 'Muchos procesos reales son una cadena de pasos: la composición los describe.' },
    { id: 'ca_inversa', fam: 'fun', n: 'Función inversa',
      d: function (K) { var g = Gr(K, { b: [40, 10, 120, 120], x: [-3, 5], y: [-3, 5], dx: 1, dy: 1 }), s = g.s; s += seg(K, g, -3, -3, 5, 5, P.grisO, { w: .8, d: '3 2' }) + curva(K, g, Math.exp, -3, 1.7, P.azulO, { w: 1.6 }) + curva(K, g, Math.log, .01, 5, P.rojoO, { w: 1.6, n: 160 }) + seg(K, g, 0, 1, 1, 0, P.grisO, { w: .6, d: '1.5 1.5' }) + punto(K, g, 0, 1, P.azulO) + punto(K, g, 1, 0, P.rojoO); return s + K.t(g.X(1.2) - 4, g.Y(3.3), 'y = eˣ', { s: 5.8, b: 1, a: 'end', c: P.azulO }) + K.t(g.X(4), g.Y(1.39) + 9, 'y = ln x', { s: 5.8, b: 1, c: P.rojoO }) + K.t(148, 22, 'y = x', { s: 5.4, b: 1, a: 'end' }) + K.t(g.X(0) - 3, g.Y(1) - 2, '(0, 1)', { s: 4.8, a: 'end' }) + K.t(g.X(1) + 2, g.Y(0) + 8, '(1, 0)', { s: 4.8, a: 'start' }) + K.t(100, 141, 'f⁻¹ deshace lo que hace f: ln(eˣ) = x · simétricas respecto a y = x', { s: 4.6, b: 1 }); },
      intro: 'La función inversa deshace lo que hace la original; sus gráficas son simétricas respecto a la recta y = x.',
      q: [['¿Cuál es la inversa de eˣ?', 'ln x.'], ['Si f(0) = 1, ¿cuánto vale f⁻¹(1)?', '0.'], ['¿Cuál es la inversa de f(x) = 2x?', 'f⁻¹(x) = x/2.']],
      porque: 'Con la inversa se despeja: si conozco el resultado, encuentro el dato de partida.' },
    { id: 'ca_trasladar', fam: 'fun', n: 'Mover una gráfica',
      d: function (K) { var g = Gr(K, { b: [14, 12, 120, 110], x: [-3, 5], y: [-4, 6], dx: 1, dy: 1 }), s = g.s, C = [[function (x) { return x * x; }, P.tinta, 'y = x²', 'original', '3 2'], [function (x) { return (x - 2) * (x - 2); }, P.azulO, 'y = (x − 2)²', '2 a la derecha', ''], [function (x) { return x * x + 1; }, P.verdeO, 'y = x² + 1', '1 hacia arriba', '5 1.5'], [function (x) { return -x * x; }, P.rojoO, 'y = −x²', 'reflejo en el eje x', '1 1.5']]; C.forEach(function (c, i) { var y = 22 + i * 26; s += curva(K, g, c[0], -3, 5, c[1], { w: 1.4, d: c[4] }) + K.l('M140 ' + y + ' L150 ' + y, c[1], { w: 1.6, d: c[4] }) + K.t(153, y + 2, c[2], { s: 5.2, b: 1, a: 'start' }) + K.t(153, y + 10, c[3], { s: ajusta(c[3], 42, 4.6), a: 'start' }); }); return s + K.t(100, 136, 'Cambiar la fórmula mueve la gráfica sin deformarla', { s: 5.6, b: 1 }); },
      intro: 'Sumar o restar dentro o fuera de la función traslada su gráfica; el signo menos la refleja.',
      q: [['¿Hacia dónde se mueve y = (x + 3)²?', '3 unidades a la izquierda.'], ['¿Y y = x² − 4?', '4 unidades hacia abajo.'], ['¿Dónde está el vértice de y = (x − 2)² + 1?', 'En (2, 1).']],
      porque: 'Basta con conocer una gráfica base para dibujar toda su familia.' },
    { id: 'ca_par_impar', fam: 'fun', n: 'Funciones pares e impares',
      d: function (K) { var s = '', A = [[12, 'PAR', function (x) { return x * x - 1; }, 1.5, 'f(−x) = f(x)', 'simétrica respecto al eje y'], [104, 'IMPAR', function (x) { return x * x * x / 2; }, 1, 'f(−x) = −f(x)', 'simétrica respecto al origen']]; A.forEach(function (a, i) { var g = Gr(K, { b: [a[0], 18, 84, 84], x: [-2, 2], y: [-2, 2], dx: 1, dy: 1 }), v = a[3], fv = a[2](v); s += g.s + curva(K, g, a[2], -2, 2, P.azulO, { w: 1.6 }) + seg(K, g, -v, i ? -fv : fv, v, fv, P.rojoO, { w: .7, d: '2 1.5' }) + punto(K, g, v, fv, P.rojoO) + punto(K, g, -v, i ? -fv : fv, P.rojoO) + K.t(a[0] + 42, 13, a[1], { s: 6.6, b: 1 }) + K.t(a[0] + 42, 110, a[4], { s: 6, b: 1 }) + K.t(a[0] + 42, 119, a[5], { s: ajusta(a[5], 82, 5) }); }); return s + K.t(100, 134, 'Pares: x², cos x · impares: x³, sen x', { s: 5.6, b: 1 }); },
      intro: 'Una función es par si es simétrica respecto al eje y, e impar si lo es respecto al origen.',
      q: [['¿Es par f(x) = x⁴?', 'Sí: f(−x) = x⁴ = f(x).'], ['¿Es impar f(x) = x³ + x?', 'Sí: f(−x) = −x³ − x = −f(x).'], ['¿Puede no ser ni par ni impar?', 'Sí, por ejemplo f(x) = x + 1.']],
      porque: 'La simetría ahorra trabajo: basta estudiar la mitad de la gráfica.' },
    { id: 'ca_trozos', fam: 'fun', n: 'Función definida a trozos',
      d: function (K) { var g = Gr(K, { b: [26, 14, 146, 96], x: [0, 6], y: [0, 10], dx: 1, dy: 1, ex: [1, 3, 5], ey: [4, 6, 9] }), s = g.s; [[0, 1, 4], [1, 3, 6], [3, 5, 9]].forEach(function (t) { s += seg(K, g, t[0], t[2], t[1], t[2], P.azulO, { w: 2 }) + hueco(K, g, t[0], t[2]) + punto(K, g, t[1], t[2], P.azulO); }); return s + K.t(g.X(6) + 3, g.Y0 + 2, 'kg', { s: 5.2, b: 1, a: 'start' }) + K.t(g.X0 + 3, g.b[1] + 7, 'precio', { s: 5.2, b: 1, a: 'start' }) + K.t(100, 122, '● incluye el extremo · ○ no lo incluye', { s: 5.4, b: 1 }) + K.t(100, 132, 'Envío de 3 kg: 6 · envío de 3,1 kg: 9', { s: 5.4 }) + K.t(100, 141, 'Tarifa de envío según el peso: una función a trozos', { s: 5, b: 1 }); },
      intro: 'Una función a trozos usa una fórmula distinta en cada intervalo, como las tarifas por tramos.',
      q: [['¿Cuánto cuesta enviar 2 kg?', '6.'], ['¿Y 1 kg exacto?', '4: el punto lleno indica que 1 kg está en el primer tramo.'], ['¿Es continua esta función?', 'No: da saltos en x = 1 y x = 3.']],
      porque: 'Muchas tarifas, impuestos y multas funcionan por tramos.' },
    { id: 'ca_seno_coseno', fam: 'fun', n: 'Gráficas de seno y coseno',
      d: function (K) { var g = Gr(K, { b: [20, 14, 170, 88], x: [0, 6.6], y: [-1.4, 1.4], ex: [[PI / 2, 'π/2'], [PI, 'π'], [3 * PI / 2, '3π/2'], [2 * PI, '2π']], ey: [1, -1] }), s = g.s; [PI / 2, PI, 3 * PI / 2, 2 * PI].forEach(function (v) { s += K.l('M' + f1(g.X(v)) + ' 14 L' + f1(g.X(v)) + ' 102', P.gris, { w: .3 }); }); s += curva(K, g, Math.sin, 0, 6.6, P.azulO, { w: 1.6 }) + curva(K, g, Math.cos, 0, 6.6, P.rojoO, { w: 1.6, d: '4 2' }); return s + K.l('M56 118 L68 118', P.azulO, { w: 1.6 }) + K.t(71, 120, 'y = sen x', { s: 5.6, b: 1, a: 'start' }) + K.l('M118 118 L130 118', P.rojoO, { w: 1.6, d: '4 2' }) + K.t(133, 120, 'y = cos x', { s: 5.6, b: 1, a: 'start' }) + K.t(100, 133, 'Se repiten cada 2π ≈ 6,28 · valores entre −1 y 1', { s: 5.4, b: 1 }); },
      intro: 'Seno y coseno son funciones periódicas: su gráfica se repite cada 2π.',
      q: [['¿Cuánto vale sen(π/2)?', '1.'], ['¿Dónde corta cos x al eje x entre 0 y 2π?', 'En π/2 y en 3π/2.'], ['¿Qué fenómenos se modelan con ondas así?', 'El sonido, las mareas, la corriente alterna.']],
      porque: 'Todo lo que se repite en el tiempo se puede describir con senos y cosenos.' },
    /* ─────────── LÍMITES Y CONTINUIDAD ─────────── */
    { id: 'ca_limite_tabla', fam: 'lim', n: 'Acercarse a un límite',
      d: function (K) { var R = [['1,9', '3,9'], ['1,99', '3,99'], ['1,999', '3,999'], ['2', '¿?'], ['2,001', '4,001'], ['2,01', '4,01'], ['2,1', '4,1']], s = K.r(12, 12, 74, 12, 0, P.azul, { w: .5 }) + K.t(30.5, 20.5, 'x', { s: 6, b: 1 }) + K.t(67.5, 20.5, 'f(x)', { s: 6, b: 1 }); R.forEach(function (r, i) { var y = 24 + i * 12, c = i === 3 ? P.amarillo : i % 2 ? P.blanco : P.gris; s += K.r(12, y, 37, 12, 0, c, { w: .4 }) + K.r(49, y, 37, 12, 0, c, { w: .4 }) + K.t(30.5, y + 8.5, r[0], { s: 5.6, b: i === 3 ? 1 : 0 }) + K.t(67.5, y + 8.5, r[1], { s: 5.6, b: i === 3 ? 1 : 0 }); }); var g = Gr(K, { b: [100, 14, 88, 92], x: [0, 4], y: [0, 7], dx: 1, dy: 1, ex: [2], ey: [4] }); s += g.s + curva(K, g, function (x) { return x + 2; }, 0, 4, P.azulO, { w: 1.6 }) + seg(K, g, 2, 0, 2, 4, P.rojoO, { w: .6, d: '2 1.5' }) + seg(K, g, 0, 4, 2, 4, P.rojoO, { w: .6, d: '2 1.5' }) + hueco(K, g, 2, 4); return s + K.t(49, 114, 'x → 2 por los dos lados', { s: 4.6 }) + K.t(100, 124, 'lím de (x² − 4)/(x − 2) cuando x → 2 = 4', { s: 5.8, b: 1 }) + K.t(100, 134, 'En x = 2 no existe la función, pero se acerca a 4', { s: 5.2 }); },
      intro: 'El límite es el valor al que se acerca una función cuando x se acerca a un número, aunque allí no exista.',
      q: [['¿Qué pasa si se sustituye x = 2?', 'Sale 0/0, que no está definido.'], ['¿Por qué la gráfica es la recta y = x + 2?', 'Porque x² − 4 = (x − 2)(x + 2) y se simplifica.'], ['¿Cuánto vale el límite?', '4.']],
      porque: 'El límite permite hablar de lo que pasa cerca de un punto sin necesitar el punto.' },
    { id: 'ca_laterales', fam: 'lim', n: 'Límites laterales',
      d: function (K) { var g = Gr(K, { b: [20, 14, 116, 100], x: [0, 4], y: [0, 5], dx: 1, dy: 1, ex: [2], ey: [1, 3] }), s = g.s; s += curva(K, g, function (x) { return x + 1; }, 0, 2, P.azulO, { w: 1.8 }) + curva(K, g, function (x) { return x - 1; }, 2, 4, P.rojoO, { w: 1.8 }) + hueco(K, g, 2, 3) + punto(K, g, 2, 1, P.rojoO) + K.flecha(g.X(1), g.Y(2) - 5, g.X(1.8), g.Y(2.8) - 5, P.azulO, { w: .8, p: 2.5 }) + K.flecha(g.X(3.4), g.Y(2.4) + 5, g.X(2.3), g.Y(1.3) + 5, P.rojoO, { w: .8, p: 2.5 }); return s + K.t(166, 30, 'por la izquierda', { s: 5.2, b: 1, c: P.azulO }) + K.t(166, 39, 'el límite es 3', { s: 5.2 }) + K.t(166, 58, 'por la derecha', { s: 5.2, b: 1, c: P.rojoO }) + K.t(166, 67, 'el límite es 1', { s: 5.2 }) + K.t(166, 88, '3 ≠ 1:', { s: 5.6, b: 1 }) + K.t(166, 97, 'no hay límite', { s: 5.6, b: 1 }) + K.t(166, 105, 'en x = 2', { s: 5.2 }) + K.t(100, 132, 'Solo hay límite si los dos laterales coinciden', { s: 5.6, b: 1 }); },
      intro: 'Los límites laterales miran a qué valor se acerca la función por la izquierda y por la derecha.',
      q: [['¿A qué se acerca por la izquierda de 2?', 'A 3.'], ['¿Y por la derecha?', 'A 1.'], ['¿Cuánto vale f(2)?', '1 (el punto lleno).']],
      porque: 'Un salto en la gráfica se detecta porque los laterales no coinciden.' },
    { id: 'ca_asintotas', fam: 'lim', n: 'Asíntotas',
      d: function (K) { var g = Gr(K, { b: [20, 12, 150, 110], x: [-3, 5], y: [-3, 5], dx: 1, dy: 1 }), s = g.s, f = function (x) { return 1 / (x - 1) + 1; }; s += seg(K, g, 1, -3, 1, 5, P.rojoO, { w: .9, d: '3 2' }) + seg(K, g, -3, 1, 5, 1, P.rojoO, { w: .9, d: '3 2' }) + curva(K, g, f, -3, .999, P.azulO, { w: 1.6, n: 220 }) + curva(K, g, f, 1.001, 5, P.azulO, { w: 1.6, n: 220 }); return s + K.t(g.X(1) - 3, 20, 'asíntota vertical: x = 1', { s: 5, b: 1, a: 'end' }) + K.t(g.X(5) - 2, g.Y(1) + 8, 'asíntota horizontal: y = 1', { s: 5, b: 1, a: 'end' }) + K.t(24, 116, 'f(x) = 1/(x − 1) + 1', { s: 5.6, b: 1, a: 'start' }) + K.t(100, 136, 'La gráfica se acerca a las asíntotas sin llegar a tocarlas', { s: 5.2, b: 1 }); },
      intro: 'Una asíntota es una recta a la que la gráfica se acerca cada vez más sin llegar a alcanzarla.',
      q: [['¿Por qué hay asíntota vertical en x = 1?', 'Porque el denominador se anula y la función se dispara.'], ['¿A qué valor se acerca f cuando x → ∞?', 'A 1, porque 1/(x − 1) → 0.'], ['¿Cuánto vale f(2)?', '1/1 + 1 = 2.']],
      porque: 'Las asíntotas describen cómo se comporta una función en los extremos.' },
    { id: 'ca_continuidad', fam: 'lim', n: 'Tipos de discontinuidad',
      d: function (K) { var s = '', D = [['evitable', 'un hueco que se puede tapar'], ['de salto', 'los laterales no coinciden'], ['infinita', 'la función se dispara']], h = function (x) { return .4 / ((x - 2) * (x - 2)); }; D.forEach(function (d, i) { var g = Gr(K, { b: [12 + i * 62, 14, 54, 70], x: [0, 4], y: [0, 4] }); s += g.s; if (i === 0) s += curva(K, g, function (x) { return .5 * x + 1; }, 0, 4, P.azulO, { w: 1.6 }) + hueco(K, g, 2, 2) + punto(K, g, 2, 3.3, P.azulO); if (i === 1) s += seg(K, g, 0, 1, 2, 1, P.azulO, { w: 1.6 }) + seg(K, g, 2, 3, 4, 3, P.azulO, { w: 1.6 }) + hueco(K, g, 2, 1) + punto(K, g, 2, 3, P.azulO); if (i === 2) s += seg(K, g, 2, 0, 2, 4, P.rojoO, { w: .7, d: '2 1.5' }) + curva(K, g, h, 0, 1.98, P.azulO, { w: 1.6 }) + curva(K, g, h, 2.02, 4, P.azulO, { w: 1.6 }); s += K.t(39 + i * 62, 96, d[0], { s: 6.2, b: 1 }) + K.t(39 + i * 62, 104, d[1], { s: ajusta(d[1], 56, 4.8) }); }); return s + K.t(100, 122, 'Continua: se dibuja sin levantar el lápiz', { s: 6, b: 1 }) + K.t(100, 132, 'f(a) existe, el límite existe y los dos coinciden', { s: 5.2 }); },
      intro: 'Una función es continua en un punto si existe, tiene límite y ambos coinciden; si no, hay una discontinuidad.',
      q: [['¿Qué tipo de discontinuidad tiene un hueco aislado?', 'Evitable: se tapa redefiniendo un solo punto.'], ['¿Qué pasa en una de salto?', 'Los límites laterales son distintos.'], ['¿Es continua f(x) = 1/x en x = 0?', 'No: tiene una discontinuidad infinita.']],
      porque: 'Saber dónde se rompe una función evita errores al calcular con ella.' },
    { id: 'ca_infinito', fam: 'lim', n: 'Quién crece más rápido',
      d: function (K) { var g = Gr(K, { b: [22, 12, 120, 100], x: [0, 10], y: [0, 40], dx: 2, dy: 10, ex: [2, 4, 6, 8, 10], ey: [10, 20, 30, 40] }), s = g.s, C = [[Math.log, P.verdeO, 'ln x', 'logarítmica', '1 1.5'], [function (x) { return x; }, P.azulO, 'x', 'lineal', '4 2'], [function (x) { return x * x; }, P.naranjaO, 'x²', 'cuadrática', '6 1.5'], [function (x) { return Math.pow(2, x); }, P.rojoO, '2ˣ', 'exponencial', '']]; C.forEach(function (c, i) { var y = 22 + i * 22; s += curva(K, g, c[0], .05, 10, c[1], { w: 1.5, d: c[4], n: 160 }) + K.l('M150 ' + y + ' L160 ' + y, c[1], { w: 1.6, d: c[4] }) + K.t(163, y + 2, c[2], { s: 6, b: 1, a: 'start' }) + K.t(163, y + 10, c[3], { s: 4.8, a: 'start' }); }); return s + K.t(100, 128, 'Cuando x → ∞: ln x crece menos que x, x menos que x², x² menos que 2ˣ', { s: 4.6, b: 1 }) + K.t(100, 137, 'Por eso x² / 2ˣ → 0', { s: 5.4, b: 1 }); },
      intro: 'Cuando x se hace muy grande, unas funciones crecen mucho más deprisa que otras.',
      q: [['¿Quién es mayor en x = 10, x² o 2ˣ?', '2ˣ: 1024 frente a 100.'], ['¿Cuánto vale lím x/2ˣ cuando x → ∞?', '0.'], ['¿Cuál crece más despacio?', 'ln x.']],
      porque: 'Comparar crecimientos permite calcular límites en el infinito sin hacer cuentas.' },
    { id: 'ca_numero_e', fam: 'lim', n: 'El número e',
      d: function (K) { var E = Math.E, xe = 50 + E * 40, s = K.l('M' + f1(xe) + ' 14 L' + f1(xe) + ' 112', P.rojoO, { w: .8, d: '3 2' }) + K.t(xe, 10, 'e = 2,71828…', { s: 5.4, b: 1, c: P.rojoO }); [1, 2, 10, 100, 1000, 1000000].forEach(function (n, i) { var v = Math.pow(1 + 1 / n, n), y = 18 + i * 16; s += K.t(46, y + 8, 'n = ' + miles(n), { s: 5, b: 1, a: 'end' }) + K.r(50, y, v * 40, 11, 2, CO[i], { w: .6 }) + K.t(53 + v * 40, y + 8, nf(v, 4), { s: 5, b: 1, a: 'start' }); }); return s + K.t(100, 126, '(1 + 1/n)ⁿ: un 100 % de interés repartido en n partes', { s: 5.2, b: 1 }) + K.t(100, 136, 'Cuando n → ∞, el resultado se acerca a e y nunca lo pasa', { s: 5 }); },
      intro: 'El número e aparece como límite de (1 + 1/n)ⁿ cuando n crece sin fin.',
      q: [['¿Cuánto vale (1 + 1/2)²?', '2,25.'], ['¿Qué interés da 1 € al 100 % con capitalización continua en un año?', 'e ≈ 2,72 €.'], ['¿Es e un número racional?', 'No: tiene infinitas cifras sin periodo.']],
      porque: 'e es la base natural del crecimiento continuo: aparece en finanzas, biología y física.' },
    { id: 'ca_bolzano', fam: 'lim', n: 'Teorema de Bolzano',
      d: function (K) { var f = function (x) { return x * x * x - x - 1; }, r = 1.3247, g = Gr(K, { b: [20, 12, 150, 104], x: [0, 2.5], y: [-2, 6], dx: .5, dy: 1, ex: [1, 2], ey: [5, -1] }), s = g.s; if (!K.linea) s += K.r(g.X(1), g.b[1], g.X(2) - g.X(1), g.b[3], 0, P.amarillo, { w: .2, op: .35 }); s += curva(K, g, f, .8, 2.15, P.azulO, { w: 1.6 }) + punto(K, g, 1, -1, P.rojoO) + punto(K, g, 2, 5, P.verdeO) + punto(K, g, r, 0, P.tinta); return s + K.t(g.X(1) - 6, 112, 'f(1) = −1 < 0', { s: 5, b: 1, a: 'end', c: P.rojoO }) + K.t(g.X(2) - 4, g.Y(5) - 3, 'f(2) = 5 > 0', { s: 5, b: 1, a: 'end', c: P.verdeO }) + K.t(g.X(r) - 3, g.Y0 - 6, 'raíz ≈ 1,32', { s: 5, b: 1, a: 'end' }) + K.t(100, 128, 'Si f es continua y cambia de signo, cruza el eje', { s: 5.6, b: 1 }) + K.t(100, 137, 'Teorema de Bolzano · f(x) = x³ − x − 1 en [1, 2]', { s: 5 }); },
      intro: 'Si una función continua es negativa en un extremo y positiva en el otro, tiene al menos una raíz entre ambos.',
      q: [['¿Cuánto vale f(1)? ¿Y f(2)?', 'f(1) = −1 y f(2) = 5.'], ['¿Qué asegura el teorema?', 'Que hay un c entre 1 y 2 con f(c) = 0.'], ['¿Sirve si la función no es continua?', 'No: podría saltar de negativo a positivo sin cruzar.']],
      porque: 'Bolzano garantiza que una solución existe antes de buscarla.' },
    /* ─────────── DERIVADAS ─────────── */
    { id: 'ca_secante_tangente', fam: 'der', n: 'De la secante a la tangente',
      d: function (K) { var f = function (x) { return .25 * x * x + .5; }, g = Gr(K, { b: [16, 12, 120, 108], x: [0, 6], y: [0, 10], dx: 1, dy: 1, ex: [2] }), s = g.s + curva(K, g, f, 0, 6, P.tinta, { w: 1.6 }); [[5, P.moradoO, '5 2'], [4, P.naranjaO, '3 1.5'], [3, P.verdeO, '1.5 1.5']].forEach(function (q, i) { var m = (f(q[0]) - f(2)) / (q[0] - 2), y = 24 + i * 18; s += curva(K, g, function (x) { return f(2) + m * (x - 2); }, 0, 6, q[1], { w: 1, d: q[2], n: 60 }) + punto(K, g, q[0], f(q[0]), q[1]) + K.l('M142 ' + y + ' L152 ' + y, q[1], { w: 1.2, d: q[2] }) + K.t(155, y + 2, 'Q en x = ' + q[0], { s: 5, b: 1, a: 'start' }) + K.t(155, y + 9, 'm = ' + nf(m, 2), { s: 5, a: 'start' }); }); s += curva(K, g, function (x) { return f(2) + (x - 2); }, 0, 6, P.rojoO, { w: 1.6, n: 60 }) + punto(K, g, 2, f(2), P.rojoO) + K.l('M142 84 L152 84', P.rojoO, { w: 1.6 }) + K.t(155, 86, 'tangente', { s: 5, b: 1, a: 'start' }) + K.t(155, 93, 'm = 1', { s: 5, a: 'start' }) + K.t(g.X(2) - 3, g.Y(f(2)) - 4, 'P', { s: 6, b: 1, a: 'end' }); return s + K.t(100, 134, 'Al acercar Q a P, la secante se convierte en la tangente', { s: 5.2, b: 1 }) + K.t(100, 142, 'f(x) = x²/4 + 1/2 · P = (2; 1,5)', { s: 4.8 }); },
      intro: 'La recta tangente es la posición final de las secantes PQ cuando Q se acerca cada vez más a P.',
      q: [['¿Qué pendiente tiene la secante con Q en x = 4?', '(4,5 − 1,5)/(4 − 2) = 1,5.'], ['¿A qué valor se acercan las pendientes?', 'A 1.'], ['¿Qué nombre recibe ese valor?', 'La derivada de f en x = 2.']],
      porque: 'Así nace la derivada: una pendiente calculada en un único punto.' },
    { id: 'ca_derivada_def', fam: 'der', n: 'Definición de derivada',
      d: function (K) { var f = function (x) { return .3 * x * x + 1; }, a = 1.5, b = 4, g = Gr(K, { b: [16, 10, 110, 96], x: [0, 5], y: [0, 8], dx: 1, dy: 1 }), s = g.s; s += curva(K, g, f, 0, 4.9, P.azulO, { w: 1.6 }) + curva(K, g, function (x) { return f(a) + (f(b) - f(a)) / (b - a) * (x - a); }, 0, 5, P.naranjaO, { w: 1, d: '3 2', n: 60 }) + seg(K, g, a, f(a), b, f(a), P.tinta, { w: .9 }) + seg(K, g, b, f(a), b, f(b), P.tinta, { w: .9 }) + punto(K, g, a, f(a), P.rojoO) + punto(K, g, b, f(b), P.rojoO); s += K.t(g.X(a) - 3, g.Y(f(a)) - 4, 'P', { s: 6, b: 1, a: 'end' }) + K.t(g.X(b) - 3, g.Y(f(b)) - 3, 'Q', { s: 6, b: 1, a: 'end' }) + K.t((g.X(a) + g.X(b)) / 2, g.Y(f(a)) + 8, 'h', { s: 6, b: 1 }) + K.t(g.X(b) + 3, (g.Y(f(a)) + g.Y(f(b))) / 2, 'Δy', { s: 6, b: 1, a: 'start' }); return s + K.t(162, 30, 'pendiente de PQ', { s: 5.4, b: 1 }) + K.t(162, 39, 'Δy / h', { s: 5.4 }) + K.t(162, 56, 'si h → 0,', { s: 5.4, b: 1 }) + K.t(162, 65, 'Q se acerca a P', { s: 5 }) + K.t(162, 74, 'y la secante se', { s: 5 }) + K.t(162, 82, 'vuelve tangente', { s: 5 }) + K.t(100, 118, 'f′(x) = lím (f(x + h) − f(x)) / h', { s: 6, b: 1 }) + K.t(100, 127, 'cuando h → 0', { s: 5 }) + K.t(100, 137, 'La derivada es la pendiente de la curva en un punto', { s: 5.4 }); },
      intro: 'La derivada se define como el límite del cociente entre lo que sube la función y lo que avanza x.',
      q: [['¿Qué representa h?', 'El avance horizontal entre P y Q.'], ['Calcula la derivada de f(x) = x² con la definición.', '((x + h)² − x²)/h = 2x + h → 2x.'], ['¿Qué significa que la derivada sea negativa?', 'Que la función baja en ese punto.']],
      porque: 'La definición convierte una idea geométrica en un cálculo exacto.' },
    G('ca_tabla_derivadas', 'der', 'Tabla de derivadas', [['f(x) = k', 'f′(x) = 0'], ['f(x) = xⁿ', 'f′(x) = n · xⁿ⁻¹'], ['f(x) = eˣ', 'f′(x) = eˣ'], ['f(x) = ln x', 'f′(x) = 1/x'], ['f(x) = sen x', 'f′(x) = cos x'], ['f(x) = cos x', 'f′(x) = −sen x'], ['f(x) = aˣ', 'f′(x) = aˣ · ln a'], ['f(x) = √x', 'f′(x) = 1/(2√x)']], 2, 14, 23, 'Ejemplo: (x⁵)′ = 5x⁴', 'Las derivadas de las funciones básicas se aprenden una vez y se usan siempre.', [['Deriva f(x) = x⁷.', '7x⁶.'], ['¿Qué función es igual a su derivada?', 'eˣ.'], ['Deriva f(x) = 3.', '0: una constante no cambia.']], 'Con pocas reglas se pueden derivar casi todas las funciones.', { s: 7, s2: 6 }),
    G('ca_reglas', 'der', 'Reglas de derivación', [['Suma', '(f + g)′ = f′ + g′'], ['Por una constante', '(k · f)′ = k · f′'], ['Producto', '(f · g)′ = f′ · g + f · g′'], ['Cociente', '(f / g)′ = (f′g − fg′) / g²'], ['Regla de la cadena', '[f(g(x))]′ = f′(g(x)) · g′(x)'], ['Ejemplo de cadena', '[(x² + 1)³]′ = 3(x² + 1)² · 2x']], 2, 20, 28, 'Con estas reglas se deriva cualquier combinación', 'Las reglas de derivación indican cómo derivar sumas, productos, cocientes y funciones compuestas.', [['Deriva x² · sen x.', '2x · sen x + x² · cos x.'], ['Deriva (3x + 1)⁴.', '4(3x + 1)³ · 3 = 12(3x + 1)³.'], ['¿Es (f · g)′ = f′ · g′?', 'No: hay que usar la regla del producto.']], 'Derivar una función complicada es aplicar reglas sencillas en orden.', { s: 7.4, s2: 5.4 }),
    { id: 'ca_f_y_fprima', fam: 'der', n: 'Una función y su derivada',
      d: function (K) { var f = function (x) { return x * x * x - 3 * x; }, d = function (x) { return 3 * x * x - 3; }, A = Gr(K, { b: [26, 8, 160, 58], x: [-2.5, 2.5], y: [-4, 4], dx: 1, dy: 2, ex: [-1, 1] }), B = Gr(K, { b: [26, 72, 160, 50], x: [-2.5, 2.5], y: [-4, 10], dx: 1, dy: 2 }), s = A.s + B.s; [-1, 1].forEach(function (v) { s += K.l('M' + f1(A.X(v)) + ' 8 L' + f1(A.X(v)) + ' 122', P.rojoO, { w: .6, d: '2 1.5' }); }); s += curva(K, A, f, -2.5, 2.5, P.azulO, { w: 1.6 }) + curva(K, B, d, -2.5, 2.5, P.verdeO, { w: 1.6 }) + punto(K, A, -1, 2, P.rojoO) + punto(K, A, 1, -2, P.rojoO) + punto(K, B, -1, 0, P.rojoO) + punto(K, B, 1, 0, P.rojoO); return s + K.t(18, 40, 'f', { s: 7, b: 1, a: 'end' }) + K.t(18, 100, 'f′', { s: 7, b: 1, a: 'end' }) + K.t(A.X(-1), A.Y(2) - 4, 'máx', { s: 5, b: 1 }) + K.t(A.X(1), A.Y(-2) + 8, 'mín', { s: 5, b: 1 }) + K.t(100, 132, 'Donde f′ = 0, f tiene un máximo o un mínimo', { s: 5.6, b: 1 }) + K.t(100, 141, 'f′ > 0: f sube · f′ < 0: f baja', { s: 5 }); },
      intro: 'La gráfica de la derivada indica cómo cambia la función: positiva donde sube y negativa donde baja.',
      q: [['¿Dónde se anula f′(x) = 3x² − 3?', 'En x = −1 y x = 1.'], ['¿Qué hace f entre −1 y 1?', 'Baja, porque f′ es negativa.'], ['¿Cuánto vale el máximo de f?', 'f(−1) = 2.']],
      porque: 'Mirar la derivada es mirar la velocidad a la que cambia la función.' },
    { id: 'ca_velocidad', fam: 'der', n: 'La derivada como velocidad',
      d: function (K) { var g = Gr(K, { b: [24, 12, 140, 100], x: [0, 3], y: [0, 45], dx: .5, dy: 5, ex: [1, 2, 3], ey: [5, 20, 45] }), s = g.s; s += curva(K, g, function (t) { return 5 * t * t; }, 0, 3, P.azulO, { w: 1.6 }) + curva(K, g, function (t) { return 20 * t - 20; }, 1, 3, P.rojoO, { w: 1.1, d: '3 2', n: 20 }) + seg(K, g, 2, 20, 3, 20, P.grisO, { w: .6 }) + seg(K, g, 3, 20, 3, 40, P.grisO, { w: .6 }) + punto(K, g, 2, 20, P.rojoO); return s + K.t(g.X(.1), g.Y(40), 's(t) = 5t²', { s: 6, b: 1, a: 'start' }) + K.t(g.X(.1), g.Y(40) + 9, 'tangente en t = 2:', { s: 5, a: 'start' }) + K.t(g.X(.1), g.Y(40) + 17, 'v = 20/1 = 20 m/s', { s: 5, b: 1, a: 'start', c: P.rojoO }) + K.t(170, g.Y0 + 2, 't (s)', { s: 5, b: 1, a: 'start' }) + K.t(g.X0 + 3, 16, 's (m)', { s: 5, b: 1, a: 'start' }) + K.t(100, 127, 'La velocidad es la derivada de la posición: v(t) = s′(t) = 10t', { s: 4.8, b: 1 }) + K.t(100, 136, 'y la aceleración, la derivada de la velocidad: a = 10 m/s²', { s: 4.8 }); },
      intro: 'En un movimiento, la derivada de la posición respecto al tiempo es la velocidad en cada instante.',
      q: [['¿Qué velocidad lleva en t = 1 s?', 'v(1) = 10 m/s.'], ['¿Qué distancia recorre en 3 s?', 's(3) = 45 m.'], ['¿Por qué la gráfica se curva hacia arriba?', 'Porque la velocidad aumenta: el objeto acelera.']],
      porque: 'Newton inventó la derivada, entre otras cosas, para estudiar el movimiento.' },
    { id: 'ca_leer_pendiente', fam: 'der', n: 'Leer pendientes en una gráfica',
      d: function (K) { var g = Gr(K, { b: [16, 12, 170, 80], x: [-.3, 6.6], y: [-1.5, 1.5] }), s = g.s, A = [[0, 'm = 1', 'ai'], [PI / 2, 'm = 0', 'ar'], [PI, 'm = −1', 'ab'], [3 * PI / 2, 'm = 0', 'de'], [2 * PI, 'm = 1', 'ai']]; s += curva(K, g, Math.sin, -.3, 6.6, P.azulO, { w: 1.6 }); A.forEach(function (a) { var m = Math.cos(a[0]), y = Math.sin(a[0]), X = g.X(a[0]), Y = g.Y(y); s += seg(K, g, a[0] - .55, y - .55 * m, a[0] + .55, y + .55 * m, P.rojoO, { w: 1.2 }) + punto(K, g, a[0], y, P.rojoO); s += a[2] === 'ai' ? K.t(X - 6, Y - 6, a[1], { s: 5, b: 1, a: 'end' }) : a[2] === 'ab' ? K.t(X - 6, Y + 10, a[1], { s: 5, b: 1, a: 'end' }) : a[2] === 'ar' ? K.t(X, Y - 6, a[1], { s: 5, b: 1 }) : K.t(X, Y + 9, a[1], { s: 5, b: 1 }); }); var B = Gr(K, { b: [16, 100, 170, 26], x: [-.3, 6.6], y: [-1.3, 1.3] }); s += B.s + curva(K, B, Math.cos, -.3, 6.6, P.verdeO, { w: 1.4 }); A.forEach(function (a) { s += punto(K, B, a[0], Math.cos(a[0]), P.rojoO); }); return s + K.t(101, 20, 'f(x) = sen x', { s: 5, b: 1 }) + K.t(101, 106, 'f′(x) = cos x', { s: 4.6, b: 1 }) + K.t(100, 138, 'Las pendientes de sen x dibujan la curva cos x', { s: 5.6, b: 1 }); },
      intro: 'Midiendo la pendiente de la tangente en varios puntos se puede dibujar la gráfica de la derivada.',
      q: [['¿Qué pendiente hay en una cima?', '0: la tangente es horizontal.'], ['¿Dónde es más negativa la pendiente de sen x?', 'En x = π, donde vale −1.'], ['¿Qué función forman las pendientes?', 'cos x.']],
      porque: 'Leer pendientes a ojo entrena la intuición antes de calcular.' },
    { id: 'ca_recta_tangente', fam: 'der', n: 'Ecuación de la recta tangente',
      d: function (K) { var g = Gr(K, { b: [12, 12, 92, 104], x: [-1, 3], y: [-2, 6], dx: 1, dy: 1, ex: [1], ey: [1] }), s = g.s, T = ['f(1) = 1 → punto (1, 1)', 'f′(x) = 2x → f′(1) = 2', 'y − 1 = 2(x − 1)', 'y = 2x − 1']; s += curva(K, g, function (x) { return x * x; }, -1, 3, P.azulO, { w: 1.6 }) + curva(K, g, function (x) { return 2 * x - 1; }, -1, 3, P.rojoO, { w: 1.2, n: 40 }) + punto(K, g, 1, 1, P.tinta) + K.t(g.X(1.6), g.Y(4.6), 'y = x²', { s: 5.6, b: 1, a: 'end', c: P.azulO }); T.forEach(function (t, i) { var y = 28 + i * 20; s += K.c(116, y - 2, 5, CO[i], { w: .6 }) + K.t(116, y, String(i + 1), { s: 5.4, b: 1 }) + K.t(124, y, t, { s: ajusta(t, 70, 5.4), b: i === 3 ? 1 : 0, a: 'start' }); }); return s + K.t(100, 134, 'Tangente en x = a: y − f(a) = f′(a) · (x − a)', { s: 5.6, b: 1 }); },
      intro: 'Para escribir la tangente se necesita el punto de contacto y la pendiente, que da la derivada.',
      q: [['Halla la tangente a y = x² en x = 2.', 'Punto (2, 4), pendiente 4: y = 4x − 4.'], ['¿Dónde es horizontal la tangente a y = x²?', 'En x = 0.'], ['¿Para qué sirve la tangente?', 'Para aproximar la función cerca del punto.']],
      porque: 'Cerca del punto, la curva y su tangente casi coinciden.' },
    /* ─────────── APLICACIONES DE LA DERIVADA ─────────── */
    { id: 'ca_monotonia', fam: 'apl', n: 'Crecimiento y decrecimiento',
      d: function (K) { var f = function (x) { return x * x * x - 6 * x * x + 9 * x + 1; }, g = Gr(K, { b: [22, 8, 168, 72], x: [-.5, 4.5], y: [-2, 8], dx: 1, dy: 2, ex: [1, 3], ey: [1, 5] }), s = g.s, x1 = g.X(1), x3 = g.X(3), c = [(22 + x1) / 2, (x1 + x3) / 2, (x3 + 190) / 2]; s += curva(K, g, f, -.5, 4.5, P.azulO, { w: 1.6 }) + punto(K, g, 1, 5, P.rojoO) + punto(K, g, 3, 1, P.verdeO); [x1, x3].forEach(function (x) { s += K.l('M' + f1(x) + ' 84 L' + f1(x) + ' 124', P.grisO, { w: .5, d: '2 1.5' }); }); s += K.l('M22 96 L190 96 M22 110 L190 110', P.gris, { w: .5 }) + K.t(18, 92, 'x', { s: 5.4, b: 1, a: 'end' }) + K.t(18, 105, 'f′(x)', { s: 5.4, b: 1, a: 'end' }) + K.t(18, 120, 'f(x)', { s: 5.4, b: 1, a: 'end' }) + K.t(x1, 92, '1', { s: 5.6, b: 1 }) + K.t(x3, 92, '3', { s: 5.6, b: 1 }) + K.t(c[0], 106, '+', { s: 7, b: 1 }) + K.t(x1, 105, '0', { s: 5.6 }) + K.t(c[1], 106, '−', { s: 7, b: 1 }) + K.t(x3, 105, '0', { s: 5.6 }) + K.t(c[2], 106, '+', { s: 7, b: 1 }) + K.flecha(c[0] - 8, 122, c[0] + 8, 112, P.verdeO, { w: 1, p: 3 }) + K.flecha(c[1] - 8, 112, c[1] + 8, 122, P.rojoO, { w: 1, p: 3 }) + K.flecha(c[2] - 8, 122, c[2] + 8, 112, P.verdeO, { w: 1, p: 3 }) + K.t(x1, 120, 'máx', { s: 5, b: 1 }) + K.t(x3, 120, 'mín', { s: 5, b: 1 }); return s + K.t(100, 134, 'f′ > 0: crece · f′ < 0: decrece · f′ = 0: posible máximo o mínimo', { s: 5, b: 1 }) + K.t(100, 142, 'f(x) = x³ − 6x² + 9x + 1 · f′(x) = 3(x − 1)(x − 3)', { s: 4.6 }); },
      intro: 'El signo de la derivada indica en qué intervalos la función crece y en cuáles decrece.',
      q: [['¿En qué intervalo decrece f?', 'Entre x = 1 y x = 3.'], ['¿Cuánto vale el máximo relativo?', 'f(1) = 5.'], ['¿Y el mínimo relativo?', 'f(3) = 1.']],
      porque: 'Una tabla de signos resume todo el comportamiento de la función.' },
    { id: 'ca_extremos', fam: 'apl', n: 'Máximos y mínimos',
      d: function (K) { var f = function (x) { return .1 * x * x * x - .9 * x * x + 2.1 * x + 1; }, a = 3 - Math.SQRT2, b = 3 + Math.SQRT2, g = Gr(K, { b: [20, 12, 170, 100], x: [0, 6.5], y: [0, 3.4], dx: 1, dy: .5, ex: [6] }), s = g.s; s += curva(K, g, f, 0, 6, P.azulO, { w: 1.6 }) + seg(K, g, a - .6, f(a), a + .6, f(a), P.rojoO, { w: .8, d: '2 1.5' }) + seg(K, g, b - .6, f(b), b + .6, f(b), P.rojoO, { w: .8, d: '2 1.5' }) + punto(K, g, a, f(a), P.rojoO) + punto(K, g, b, f(b), P.rojoO) + punto(K, g, 0, f(0), P.verdeO) + punto(K, g, 6, f(6), P.verdeO); return s + K.t(g.X(a), g.Y(f(a)) - 7, 'máximo relativo', { s: 5, b: 1 }) + K.t(g.X(b), g.Y(f(b)) + 10, 'mínimo relativo', { s: 5, b: 1 }) + K.t(g.X(6) - 4, g.Y(f(6)) - 6, 'máximo absoluto', { s: 5, b: 1, a: 'end', c: P.verdeO }) + K.t(g.X(0) + 4, g.Y(f(0)) + 10, 'mínimo absoluto', { s: 5, b: 1, a: 'start', c: P.verdeO }) + K.t(100, 127, 'En un extremo relativo la tangente es horizontal: f′ = 0', { s: 5.2, b: 1 }) + K.t(100, 136, 'Los absolutos pueden estar en los bordes del intervalo [0, 6]', { s: 5 }); },
      intro: 'Los extremos relativos están donde la derivada vale cero; los absolutos pueden estar también en los bordes.',
      q: [['¿Qué condición cumple un extremo relativo?', 'f′(x) = 0.'], ['¿Dónde está el máximo absoluto en [0, 6]?', 'En x = 6, en el borde.'], ['¿Basta f′ = 0 para que haya extremo?', 'No: en x³ la derivada se anula en 0 y no hay extremo.']],
      porque: 'Buscar extremos es buscar lo mejor o lo peor posible: base de toda optimización.' }
  ];
  MO.agregar('calculo', L, { nombre: 'Cálculo', familias: FAM, materias: /^(calculo)$/ });
})();
