/* b6_lib_religion2.js — Religión y cultura religiosa: modelos 26–50 de 50. Materia `religion`. Prefijo `re_`.
   Cargar después de b6_lib_religion.js. Familias: calendario y ritos, símbolos y arte, convivencia y diálogo, cosmovisiones. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('re_ano_liturgico')) return;
  var P = { azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', oro: '#E8C060', morado: '#D0B8E8', moradoO: '#7A5AA0', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', piel2: '#C89670', tinta: '#2A2420', blanco: '#FFFFFF', agua: '#9CCBE6', madera: '#C89A62', arena: '#EAD9B0', pergamino: '#F4E8C8', cesped: '#9CCB7A' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { gr: 'Grandes religiones', lib: 'Libros sagrados', bib: 'Relatos bíblicos', cal: 'Calendario y ritos', sim: 'Símbolos y arte', dia: 'Convivencia y diálogo', cos: 'Cosmovisiones' };
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + f1 * .35, q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  function ajusta(t, ancho, max) { return +Math.min(max, ancho / (t.length * .54)).toFixed(2); }
  function estrella(K, cx, cy, r, col) { var pt = []; for (var i = 0; i < 10; i++) { var a = -Math.PI / 2 + i * Math.PI / 5, rr = i % 2 ? r * .45 : r; pt.push([cx + Math.cos(a) * rr, cy + Math.sin(a) * rr]); } return K.pl(pt, col, { w: .6 }); }
  function per(K, x, y, col, e, piel) { e = e || 1; return K.p('M' + (x - 11 * e) + ' ' + (y + 34 * e) + ' Q' + (x - 11 * e) + ' ' + (y + 12 * e) + ' ' + x + ' ' + (y + 12 * e) + ' Q' + (x + 11 * e) + ' ' + (y + 12 * e) + ' ' + (x + 11 * e) + ' ' + (y + 34 * e) + ' Z', col, { w: .8 }) + K.c(x, y, 8 * e, piel || P.piel, { w: .8 }); }
  function luna(K, cx, cy, r, col, fondo) { return K.c(cx, cy, r, col, { w: .8 }) + K.c(cx + r * .38, cy - r * .2, r * .82, fondo || P.blanco, { w: .1, sin: 1 }); }
  function arco(K, x, y, w, h, col, apuntado) { var m = x + w / 2, d = apuntado ? 'M' + x + ' ' + (y + h) + ' L' + x + ' ' + (y + w * .55) + ' Q' + x + ' ' + y + ' ' + m + ' ' + (y - w * .1) + ' Q' + (x + w) + ' ' + y + ' ' + (x + w) + ' ' + (y + w * .55) + ' L' + (x + w) + ' ' + (y + h) + ' Z' : 'M' + x + ' ' + (y + h) + ' L' + x + ' ' + (y + w / 2) + ' A' + (w / 2) + ' ' + (w / 2) + ' 0 0 1 ' + (x + w) + ' ' + (y + w / 2) + ' L' + (x + w) + ' ' + (y + h) + ' Z'; return K.p(d, col, { w: .8 }); }

  var L = [
    /* ─────────── CALENDARIO Y RITOS ─────────── */
    { id: 're_ano_liturgico', fam: 'cal', n: 'El año litúrgico cristiano',
      d: function (K) { var cx = 60, cy = 68, r = 46, D = [['Adviento', 4, P.morado], ['Navidad', 2, P.oro], ['Tiempo ordinario', 6, P.verde], ['Cuaresma', 6, P.morado], ['Pascua', 7, P.blanco], ['Tiempo ordinario', 27, P.verde]], a = 0, s = K.suelo(cx, 124, 50); D.forEach(function (d, i) { var a2 = a + d[1] / 52 * 2 * Math.PI, x1 = cx + Math.sin(a) * r, y1 = cy - Math.cos(a) * r, x2 = cx + Math.sin(a2) * r, y2 = cy - Math.cos(a2) * r; s += K.p('M' + cx + ' ' + cy + ' L' + x1.toFixed(1) + ' ' + y1.toFixed(1) + ' A' + r + ' ' + r + ' 0 ' + (a2 - a > Math.PI ? 1 : 0) + ' 1 ' + x2.toFixed(1) + ' ' + y2.toFixed(1) + ' Z', d[2], { w: .8 }) + K.r(112, 18 + i * 15, 9, 9, 2, d[2], { w: .5 }) + K.t(124, 25 + i * 15, d[0] + ' · ' + d[1] + ' sem.', { s: 4.8, a: 'start' }); a = a2; }); return s + K.c(cx, cy, 12, P.blanco, { w: .6 }) + K.t(cx, cy + 2, '52 sem.', { s: 5, b: 1 }) + K.t(100, 132, 'Empieza en Adviento · Pentecostés cierra la Pascua (rojo)', { s: 5, b: 1 }); },
      intro: 'El año litúrgico ordena las celebraciones cristianas en tiempos con un color propio.',
      q: [['¿Con qué tiempo empieza el año litúrgico?', 'Con el Adviento, cuatro semanas antes de Navidad.'], ['¿Qué color se usa en Cuaresma?', 'El morado.'], ['¿Qué tiempo es el más largo?', 'El tiempo ordinario, de color verde.']],
      porque: 'Los colores ayudan a reconocer de un vistazo qué tiempo se celebra.' },
    G('re_sacramentos', 'cal', 'Los siete sacramentos', [['Bautismo', 'iniciación', P.azul], ['Confirmación', 'iniciación', P.azul], ['Eucaristía', 'iniciación', P.azul], ['Reconciliación', 'curación', P.verde], ['Unción de enfermos', 'curación', P.verde], ['Orden sacerdotal', 'servicio', P.amarillo], ['Matrimonio', 'servicio', P.amarillo]], 2, 14, 22, 'Iglesia católica y ortodoxa · los protestantes reconocen dos', 'Los sacramentos son signos que, para los cristianos, acompañan los momentos importantes de la vida.', [['¿Qué sacramentos son de iniciación?', 'Bautismo, confirmación y eucaristía.'], ['¿Cuáles reconocen la mayoría de iglesias protestantes?', 'El bautismo y la cena del Señor (eucaristía).'], ['¿Qué sacramento se da a los enfermos?', 'La unción de enfermos.']], 'Los sacramentos unen gestos sencillos —agua, pan, aceite— con un sentido profundo.', { s: 7, s2: 5.2 }),
    { id: 're_calendarios', fam: 'cal', n: 'Calendarios solares y lunares',
      d: function (K) { var D = [['Gregoriano', 'solar', 365, 'año 2026', P.amarillo], ['Islámico', 'lunar', 354, 'años 1447-1448 de la Hégira', P.verde], ['Judío', 'lunisolar', 385, '12 o 13 meses · años 5786-5787', P.azul]], s = K.suelo(100, 140, 96); D.forEach(function (d, i) { var y = 22 + i * 34, w = d[2] * .3; s += K.t(12, y - 3, d[0] + ' · ' + d[1], { s: 6, b: 1, a: 'start' }) + K.r(12, y, w, 12, 3, d[4], { w: .7 }) + K.t(16 + w, y + 8.5, (i === 2 ? '353-' : '') + d[2] + ' días', { s: 5.4, b: 1, a: 'start' }) + K.t(12, y + 20, d[3], { s: 5, a: 'start' }); }); return s + luna(K, 176, 30, 10, P.amarillo) + K.c(176, 64, 9, P.oro, { w: .7 }) + K.t(100, 132, 'Por eso el Ramadán y la Pascua cambian de fecha cada año', { s: 5.4, b: 1 }); },
      intro: 'Las religiones usan calendarios distintos: unos siguen al sol, otros a la luna y otros a los dos.',
      q: [['¿Cuántos días tiene el año lunar islámico?', 'Unos 354: once menos que el solar.'], ['¿Por qué el Ramadán se adelanta cada año?', 'Porque el año lunar es más corto que el solar.'], ['¿Cómo ajusta el calendario judío la diferencia?', 'Añadiendo un mes extra en algunos años.']],
      porque: 'Los calendarios muestran cómo cada cultura midió el tiempo mirando el cielo.' },
    G('re_ritos_paso', 'cal', 'Ritos de paso', [['Bautismo', 'cristianismo · entrar en la comunidad'], ['Bar y bat mitzvá', 'judaísmo · 13 y 12 años'], ['Confirmación', 'cristianismo · reafirmar la fe'], ['Upanayana', 'hinduismo · el cordón sagrado'], ['Matrimonio', 'en casi todas las religiones'], ['Funeral', 'despedida y memoria']], 2, 20, 28, 'Marcan el paso de una etapa de la vida a otra', 'Los ritos de paso celebran momentos clave: nacer, hacerse adulto, casarse y morir.', [['¿A qué edad es el bar mitzvá?', 'A los 13 años (el bat mitzvá de las chicas, a los 12).'], ['¿Qué etapa marca la confirmación?', 'La reafirmación personal de la fe, normalmente en la adolescencia.'], ['¿Hay ritos de paso no religiosos?', 'Sí: graduaciones, quinceañeras, mayoría de edad…']], 'Todas las culturas necesitan señalar los grandes cambios de la vida.', { s: 7, s2: 5 }),
    G('re_oracion', 'cal', 'Formas de orar', [['De pie', 'judaísmo, cristianismo ortodoxo'], ['De rodillas', 'cristianismo'], ['Postración', 'islam (salat)'], ['Sentado en silencio', 'budismo (meditación)'], ['Manos juntas', 'muchas tradiciones'], ['Cantando', 'salmos, mantras, góspel']], 2, 20, 28, 'El cuerpo también expresa la oración', 'Cada tradición tiene gestos y posturas propias para orar o meditar.', [['¿Hacia dónde se orientan los musulmanes al orar?', 'Hacia La Meca.'], ['¿Qué es meditar en el budismo?', 'Sentarse en silencio y atender a la respiración y la mente.'], ['¿Qué tienen en común todas las posturas?', 'Expresan respeto, atención y recogimiento.']], 'Los gestos del cuerpo ayudan a la mente a concentrarse.', { s: 7.2, s2: 5.2 }),
    G('re_peregrinaciones', 'cal', 'Lugares de peregrinación', [['La Meca', 'Arabia Saudí · islam'], ['Jerusalén', 'judíos, cristianos y musulmanes'], ['Santiago de Compostela', 'España · cristianismo'], ['Basílica de Guadalupe', 'México · cristianismo'], ['Varanasi', 'India · hinduismo, río Ganges'], ['Bodh Gaya', 'India · budismo']], 2, 20, 28, 'Peregrinar: viajar a un lugar sagrado por motivos de fe', 'Muchas religiones tienen lugares sagrados a los que los creyentes viajan.', [['¿Qué ciudad es sagrada para tres religiones?', 'Jerusalén.'], ['¿Qué pasó en Bodh Gaya según la tradición?', 'Buda alcanzó allí la iluminación.'], ['¿Cómo se llama el camino a Santiago?', 'El Camino de Santiago.']], 'Las peregrinaciones han creado rutas, ciudades y encuentros entre culturas.', { s: 7, s2: 5 }),
    { id: 're_ayunos', fam: 'cal', n: 'El ayuno en tres religiones',
      d: function (K) { var s = K.suelo(100, 140, 96); [['Ramadán', 'islam', 'un mes', 'del alba a la puesta del sol', P.verde], ['Cuaresma', 'cristianismo', '40 días', 'ayuno y abstinencia algunos días', P.morado], ['Yom Kipur', 'judaísmo', 'un día', 'unas 25 horas sin comer ni beber', P.azul]].forEach(function (q, i) { var x = 12 + i * 60; s += K.r(x, 20, 56, 96, 6, q[4], { w: .8, op: .75 }) + K.t(x + 28, 70, q[0], { s: ajusta(q[0], 50, 7), b: 1 }) + K.t(x + 28, 79, q[1], { s: 5 }) + K.t(x + 28, 94, q[2], { s: 6, b: 1 }) + K.t(x + 28, 104, q[3], { s: ajusta(q[3], 52, 5) }); }); s += luna(K, 40, 42, 12, P.amarillo, P.verde) + K.r(97, 28, 6, 26, 1, P.oro, { w: .7 }) + K.r(90, 34, 20, 6, 1, P.oro, { w: .7 }); [150, 160, 170].forEach(function (x) { s += K.r(x - 2, 38, 4, 16, 1, P.blanco, { w: .6 }) + K.e(x, 34, 1.8, 3.4, P.naranja, { w: .4 }); }); return s + K.t(100, 132, 'Ayunar: privarse para reflexionar, compartir y empezar de nuevo', { s: 5, b: 1 }); },
      intro: 'El ayuno es una práctica de varias religiones para reflexionar, purificarse y ser solidario.',
      q: [['¿Cuánto dura el Ramadán?', 'Un mes lunar, 29 o 30 días.'], ['¿Quiénes no están obligados a ayunar?', 'En general, niños, enfermos, embarazadas y personas mayores.'], ['¿Qué se busca con el ayuno además de no comer?', 'Reflexionar, pedir perdón y ayudar a quien pasa hambre.']],
      porque: 'Sentir hambre por voluntad propia ayuda a comprender a quien la pasa sin elegirlo.' },
    /* ─────────── SÍMBOLOS Y ARTE ─────────── */
    { id: 're_simbolos', fam: 'sim', n: 'Símbolos religiosos',
      d: function (K) { var s = K.suelo(100, 140, 96), C = [[38, 42, 'cruz', 'cristianismo'], [100, 42, 'estrella de David', 'judaísmo'], [162, 42, 'media luna', 'islam'], [38, 102, 'rueda del dharma', 'budismo'], [100, 102, 'yin y yang', 'taoísmo'], [162, 102, 'flor de loto', 'hinduismo y budismo']]; C.forEach(function (c) { s += K.t(c[0], c[1] + 22, c[2], { s: ajusta(c[2], 56, 5.6), b: 1 }) + K.t(c[0], c[1] + 30, c[3], { s: ajusta(c[3], 56, 4.8) }); }); s += K.r(35, 24, 6, 32, 1, P.oro, { w: .7 }) + K.r(26, 32, 24, 6, 1, P.oro, { w: .7 }); var tri = function (cx, cy, r, g) { var p = []; for (var i = 0; i < 3; i++) { var t = g + i * 2 * Math.PI / 3; p.push((i ? ' L' : 'M') + (cx + Math.cos(t) * r).toFixed(1) + ' ' + (cy + Math.sin(t) * r).toFixed(1)); } return p.join('') + ' Z'; }; s += K.l(tri(100, 40, 14, -Math.PI / 2) + ' ' + tri(100, 40, 14, Math.PI / 2), P.azulO, { w: 2 }) + luna(K, 160, 40, 13, P.verde) + estrella(K, 172, 36, 4, P.verde); s += K.l('M24 100 A14 14 0 1 1 52 100 A14 14 0 1 1 24 100', P.oro, { w: 2.4 }); for (var i = 0; i < 8; i++) { var a = i * Math.PI / 4; s += K.l('M38 100 L' + (38 + Math.cos(a) * 14).toFixed(1) + ' ' + (100 + Math.sin(a) * 14).toFixed(1), P.oro, { w: 1.2 }); } s += K.c(100, 100, 15, P.blanco, { w: .8 }) + K.p('M100 85 A15 15 0 0 1 100 115 A7.5 7.5 0 0 1 100 100 A7.5 7.5 0 0 0 100 85 Z', P.tinta, { w: .4, negro: 1 }); [-40, -20, 0, 20, 40].forEach(function (g) { s += K.e(162 + Math.sin(g * Math.PI / 180) * 8, 98 - Math.cos(g * Math.PI / 180) * 5, 4, 9, P.rosa, { w: .6 }); }); return s; },
      intro: 'Los símbolos resumen en una imagen las ideas centrales de cada religión.',
      q: [['¿Qué religión usa la estrella de David?', 'El judaísmo.'], ['¿Qué representan el yin y el yang?', 'El equilibrio entre fuerzas opuestas.'], ['¿Por qué el loto es símbolo de pureza?', 'Porque nace en el barro y florece limpio sobre el agua.']],
      porque: 'Un símbolo comunica sin palabras y une a quienes lo comparten.' },
    { id: 're_vitral', fam: 'sim', n: 'El vitral',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.p('M70 128 L70 50 Q70 14 100 10 Q130 14 130 50 L130 128 Z', P.gris, { w: 1.4 }), C = [P.azul, P.rojo, P.amarillo, P.verde, P.morado]; for (var f = 0; f < 6; f++) for (var c = 0; c < 3; c++) s += K.r(74 + c * 18, 44 + f * 14, 16, 12, 0, C[(f * 3 + c) % 5], { w: .9 }); s += K.c(100, 30, 10, P.amarillo, { w: .9 }) + K.l('M100 20 L100 40 M90 30 L110 30', P.tinta, { w: .8 }); return s + K.l('M130 60 L150 60', P.grisO, { w: .5 }) + K.t(152, 58, 'varillas de', { s: 5.4, b: 1, a: 'start' }) + K.t(152, 66, 'plomo', { s: 5.4, b: 1, a: 'start' }) + K.l('M70 86 L52 86', P.grisO, { w: .5 }) + K.t(48, 84, 'vidrios de', { s: 5.4, b: 1, a: 'end' }) + K.t(48, 92, 'colores', { s: 5.4, b: 1, a: 'end' }) + K.t(36, 30, 'arco apuntado', { s: 5.2 }) + K.t(36, 38, '(gótico)', { s: 5 }) + K.t(100, 140, 'La luz entra coloreada y cuenta historias sin palabras', { s: 5.2, b: 1 }); },
      intro: 'El vitral es una ventana de vidrios de colores unidos con plomo; en el gótico llenaba las iglesias de luz.',
      q: [['¿Con qué se unen los vidrios?', 'Con varillas de plomo.'], ['¿Para qué servían los vitrales en la Edad Media?', 'Para enseñar relatos religiosos a quienes no sabían leer.'], ['Diseña un vitral con un tema de tu elección.', 'Respuesta abierta.']],
      porque: 'El vitral convierte la luz del sol en un elemento del edificio.' },
    { id: 're_romanico_gotico', fam: 'sim', n: 'Románico y gótico',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(14, 56, 70, 70, 0, P.arena, { w: 1.2 }) + K.pl([[10, 56], [49, 34], [88, 56]], P.madera, { w: 1 }) + arco(K, 38, 92, 22, 34, P.madera) + arco(K, 22, 66, 8, 14, P.tinta) + arco(K, 68, 66, 8, 14, P.tinta); s += K.r(116, 40, 60, 86, 0, P.gris, { w: 1 }) + K.pl([[112, 40], [146, 6], [180, 40]], P.grisO, { w: 1 }) + arco(K, 136, 90, 20, 36, P.madera, 1) + arco(K, 122, 52, 10, 30, P.azul, 1) + arco(K, 160, 52, 10, 30, P.azul, 1) + K.l('M116 70 L100 90 L100 126 M176 70 L192 90 L192 126', P.grisO, { w: 1.4 }); return s + K.t(49, 26, 'ROMÁNICO', { s: 6.4, b: 1 }) + K.t(49, 134, 'muros gruesos · arco de medio punto', { s: 4.6 }) + K.t(146, 134, 'altura · arco apuntado · arbotantes', { s: 4.6 }) + K.t(186, 18, 'GÓTICO', { s: 6.4, b: 1, a: 'end' }) + K.t(49, 142, 'siglos XI-XII · poca luz', { s: 4.6 }) + K.t(146, 142, 'siglos XII-XV · mucha luz', { s: 4.6 }); },
      intro: 'El románico y el gótico son dos estilos de las iglesias medievales de Europa; el gótico buscó altura y luz.',
      q: [['¿Qué arco usa el románico?', 'El arco de medio punto (redondo).'], ['¿Para qué sirven los arbotantes?', 'Para sostener los muros desde fuera y poder abrir grandes ventanas.'], ['¿Qué estilo tiene más luz y por qué?', 'El gótico, porque sus muros tienen grandes vitrales.']],
      porque: 'La técnica constructiva cambió la experiencia de entrar en un templo.' },
    { id: 're_icono', fam: 'sim', n: 'Cómo leer un icono',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(66, 14, 68, 104, 2, P.madera, { w: 1 }) + K.r(72, 20, 56, 92, 1, P.oro, { w: .7 }) + K.c(100, 44, 16, P.amarillo, { w: 1 }) + per(K, 100, 46, P.rojo, 1.6) + K.c(88, 86, 3, P.piel, { w: .6 }) + K.l('M88 83 L88 76', P.tinta, { w: .9 }); [['fondo dorado', 'la luz de Dios', 40, 28, 74, 26], ['aureola', 'santidad', 160, 40, 116, 40], ['mirada de frente', 'habla al que mira', 160, 70, 108, 48], ['mano que bendice', 'gesto de saludo', 40, 88, 86, 84], ['pintado sobre madera', 'con temple', 40, 118, 66, 110]].forEach(function (q) { var izq = q[2] < 100; s += K.l('M' + (izq ? q[2] + 22 : q[2] - 22) + ' ' + (q[3] - 2) + ' L' + q[4] + ' ' + q[5], P.grisO, { w: .5 }) + K.t(q[2], q[3] - 3, q[0], { s: ajusta(q[0], 50, 5.4), b: 1 }) + K.t(q[2], q[3] + 5, q[1], { s: ajusta(q[1], 50, 4.8) }); }); return s + K.t(100, 140, 'Arte cristiano de Bizancio y de las iglesias ortodoxas', { s: 5, b: 1 }); },
      intro: 'Un icono es una imagen sagrada pintada sobre madera, con reglas fijas para cada elemento.',
      q: [['¿Qué significa el fondo dorado?', 'La luz divina, un espacio fuera del tiempo.'], ['¿Por qué la figura mira de frente?', 'Para dialogar con quien contempla el icono.'], ['¿En qué iglesias son más importantes los iconos?', 'En las ortodoxas.']],
      porque: 'Cada detalle de un icono es un símbolo que se puede leer.' },
    { id: 're_retablo', fam: 'sim', n: 'El retablo barroco americano',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(26, 14, 148, 112, 2, P.oro, { w: 1 }); for (var f = 0; f < 2; f++) for (var c = 0; c < 3; c++) { var x = 40 + c * 44, y = 22 + f * 52; s += arco(K, x, y, 32, 44, P.madera) + per(K, x + 16, y + 20, CO[f * 3 + c], .6); } [32, 76, 120, 164].forEach(function (x) { var d = 'M' + x + ' 18'; for (var k = 0; k < 13; k++) d += ' L' + (x + (k % 2 ? 4 : -2)) + ' ' + (22 + k * 8); s += K.l(d, P.madera, { w: 1.6 }); }); return s + K.t(100, 134, 'Pan de oro · columnas salomónicas · siglos XVII-XVIII', { s: 5.2, b: 1 }) + K.t(100, 142, 'artistas indígenas y mestizos añadieron flores y frutos de América', { s: 4.4 }); },
      intro: 'El retablo es la gran estructura dorada detrás del altar; en la América colonial alcanzó gran riqueza.',
      q: [['¿Qué es el pan de oro?', 'Una lámina finísima de oro que se pega sobre la madera tallada.'], ['¿Cómo son las columnas salomónicas?', 'Retorcidas en espiral.'], ['¿Qué aportaron los artistas americanos?', 'Motivos de su tierra: frutas, flores, aves y rostros locales.']],
      porque: 'El barroco americano mezcla tradición europea y mirada indígena.' },
    { id: 're_belen', fam: 'sim', n: 'El belén o nacimiento',
      d: function (K) { var s = K.suelo(100, 132, 90) + K.pl([[40, 50], [100, 22], [160, 50]], P.madera, { w: 1 }) + K.r(48, 50, 4, 80, 0, P.madera, { w: .8 }) + K.r(148, 50, 4, 80, 0, P.madera, { w: .8 }) + estrella(K, 100, 10, 7, P.oro); s += per(K, 74, 84, P.azul, 1) + per(K, 128, 82, P.naranja, 1, P.piel2) + K.r(88, 112, 24, 12, 2, P.madera, { w: .8 }) + K.e(100, 110, 10, 4, P.amarillo, { w: .6 }) + K.c(100, 108, 3.4, P.piel, { w: .5 }) + K.e(62, 120, 9, 6, P.gris, { w: .6 }) + K.e(140, 120, 9, 6, P.grisO, { w: .6 }); return s + K.t(74, 70, 'María', { s: 5.4, b: 1 }) + K.t(128, 68, 'José', { s: 5.4, b: 1 }) + K.t(100, 140, 'Tradición iniciada por san Francisco de Asís en 1223', { s: 5, b: 1 }) + K.t(28, 112, 'buey', { s: 5 }) + K.t(172, 112, 'mula', { s: 5 }) + K.t(122, 16, 'estrella', { s: 5, a: 'start' }); },
      intro: 'El belén representa el nacimiento de Jesús en un establo de Belén; es una costumbre muy viva en América y España.',
      q: [['¿Quién montó el primer belén?', 'San Francisco de Asís, en Greccio (Italia), en 1223.'], ['¿Qué personajes llegan guiados por la estrella?', 'Los Reyes Magos.'], ['¿Qué figuras típicas añaden en tu país?', 'Respuesta según el país.']],
      porque: 'El belén convierte un relato en una escena que se puede tocar y montar en familia.' },
    G('re_musica_sacra', 'sim', 'Música religiosa', [['Canto gregoriano', 'monasterios medievales'], ['Salmos', 'canto judío y cristiano'], ['Góspel', 'iglesias afroamericanas'], ['Villancico', 'Navidad en España y América'], ['Mantras', 'hinduismo y budismo'], ['Llamada a la oración', 'islam (adhan)']], 2, 20, 28, 'La música fue la primera forma de oración compartida', 'Las religiones han creado músicas propias para orar, celebrar y enseñar.', [['¿Qué es el canto gregoriano?', 'Un canto a una sola voz, en latín y sin instrumentos.'], ['¿Dónde nació el góspel?', 'En las iglesias afroamericanas de Estados Unidos.'], ['¿Qué es un mantra?', 'Una palabra o frase que se repite para meditar u orar.']], 'Mucha música que hoy escuchamos tiene raíces en el canto religioso.', { s: 7, s2: 5.2 }),
    /* ─────────── CONVIVENCIA Y DIÁLOGO ─────────── */
    { id: 're_libertad', fam: 'dia', n: 'La libertad religiosa',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.e(100, 80, 46, 16, P.madera, { w: 1 }); [[64, 56, P.azul, P.piel], [88, 50, P.verde, P.piel2], [112, 50, P.amarillo, P.piel], [136, 56, P.morado, P.piel2]].forEach(function (q) { s += per(K, q[0], q[1], q[2], .7, q[3]); }); return s + K.r(20, 104, 160, 24, 6, P.blanco, { w: .8 }) + K.t(100, 114, 'Toda persona tiene derecho a la libertad de pensamiento,', { s: 5, b: 1 }) + K.t(100, 122, 'de conciencia y de religión · DUDH, artículo 18', { s: 5, b: 1 }) + K.t(100, 20, 'Creer, no creer o cambiar de creencia', { s: 6, b: 1 }) + K.t(100, 30, 'sin ser perseguido ni discriminado', { s: 5.4 }); },
      intro: 'La libertad religiosa es el derecho a tener, no tener o cambiar de religión, y a practicarla en paz.',
      q: [['¿Qué artículo de la DUDH la reconoce?', 'El artículo 18.'], ['¿Incluye el derecho a no creer?', 'Sí: protege también a quien no tiene religión.'], ['¿Tiene límites?', 'Sí: no se puede dañar a otros ni violar sus derechos en nombre de una creencia.']],
      porque: 'La libertad religiosa protege a todos, también a las minorías.' },
    G('re_dialogo', 'dia', 'Dialogar entre creencias', [['Escuchar', 'sin juzgar'], ['Preguntar', 'con curiosidad y respeto'], ['Buscar lo común', 'valores compartidos'], ['Respetar', 'lo que es diferente'], ['No imponer', 'cada persona decide'], ['Colaborar', 'en causas comunes']], 2, 20, 28, 'Dialogar no es renunciar a lo propio', 'El diálogo interreligioso busca conocerse y convivir entre personas de distintas creencias.', [['¿Qué valores comparten muchas religiones?', 'La regla de oro, la ayuda al necesitado, la paz y la justicia.'], ['¿Qué pregunta respetuosa harías a un compañero de otra religión?', 'Por ejemplo: «¿Qué fiesta es la más importante para tu familia?».'], ['¿Por qué no hay que imponer la propia fe?', 'Porque la fe, para ser auténtica, debe ser libre.']], 'Conocer al otro desactiva el miedo a lo desconocido.', { s: 7.6, s2: 5.4 }),
    { id: 're_laicidad', fam: 'dia', n: 'Estado laico y Estado confesional',
      d: function (K) { var s = K.suelo(100, 140, 96), ed = function (x) { return K.r(x, 50, 56, 40, 0, P.gris, { w: .9 }) + K.pl([[x - 4, 50], [x + 28, 32], [x + 60, 50]], P.grisO, { w: .9 }) + [8, 22, 36, 48].map(function (d) { return K.r(x + d, 56, 4, 30, 0, P.blanco, { w: .5 }); }).join(''); }; s += ed(22) + ed(122); s += K.r(36, 98, 28, 12, 2, P.amarillo, { w: .7 }) + K.t(50, 106, 'una religión', { s: 4.4, b: 1 }) + K.l('M50 90 L50 98', P.tinta, { w: 1.2 }); [124, 140, 156, 172].forEach(function (x, i) { s += K.r(x - 7, 98, 14, 12, 2, CO[i], { w: .6 }); }); return s + K.t(50, 24, 'CONFESIONAL', { s: 6.4, b: 1 }) + K.t(150, 24, 'LAICO', { s: 6.4, b: 1 }) + K.t(50, 122, 'tiene una religión oficial', { s: 5 }) + K.t(150, 122, 'separado de todas; trata igual', { s: 5 }) + K.t(150, 130, 'a creyentes y no creyentes', { s: 5 }) + K.t(100, 142, 'Busca qué dice la Constitución de tu país', { s: 5.4, b: 1 }); },
      intro: 'Un Estado laico no tiene religión oficial y garantiza la libertad de todas; uno confesional reconoce una religión oficial.',
      q: [['¿Qué es un Estado laico?', 'Uno separado de las religiones, que no favorece a ninguna.'], ['¿Prohíbe un Estado laico la religión?', 'No: protege la libertad de practicarla.'], ['¿Es laico tu país?', 'Respuesta según la Constitución de cada país.']],
      porque: 'La separación entre Estado y religión protege a la vez la libertad y la igualdad.' },
    G('re_misericordia', 'dia', 'Las obras de misericordia corporales', [['Dar de comer', 'al hambriento'], ['Dar de beber', 'al sediento'], ['Vestir', 'al desnudo'], ['Dar posada', 'al peregrino'], ['Visitar', 'a los enfermos'], ['Visitar', 'a los presos'], ['Enterrar', 'a los muertos']], 2, 14, 22, 'Hoy: bancos de alimentos, voluntariado, acogida', 'Las obras de misericordia son siete acciones concretas de ayuda que propone la tradición cristiana.', [['¿Cuántas obras de misericordia corporales hay?', 'Siete.'], ['¿Qué obra se practica en un banco de alimentos?', 'Dar de comer al hambriento.'], ['¿Qué sería hoy «dar posada al peregrino»?', 'Acoger a migrantes o a personas sin hogar.']], 'Las obras de misericordia convierten la fe en acciones visibles.', { s: 7.4, s2: 5.4 }),
    G('re_solidaridad', 'dia', 'La ayuda al necesitado en cuatro religiones', [['Zakat', 'islam · 2,5 % del ahorro anual'], ['Diezmo', 'cristianismo · tradicionalmente el 10 %'], ['Tsedaká', 'judaísmo · ayudar es hacer justicia'], ['Dana', 'budismo · la generosidad']], 2, 20, 44, 'Compartir lo que se tiene aparece en todas las tradiciones', 'Muchas religiones piden a sus creyentes que compartan parte de sus bienes con quien lo necesita.', [['Si alguien ahorró 2 000 al año, ¿cuánto es el zakat?', '2,5 % de 2 000 = 50.'], ['¿Qué significa «diezmo»?', 'La décima parte: el 10 %.'], ['¿Por qué tsedaká significa también justicia?', 'Porque ayudar se ve como un deber, no como un favor.']], 'La solidaridad es un punto de encuentro entre religiones distintas.', { s: 9, s2: 5.6 }),
    { id: 're_preguntas', fam: 'dia', n: 'Las grandes preguntas',
      d: function (K) { var Q = [['¿De dónde venimos?', 50, 24], ['¿Qué sentido tiene la vida?', 150, 24], ['¿Qué está bien y qué está mal?', 48, 64], ['¿Qué pasa al morir?', 152, 64], ['¿Existe Dios?', 100, 110]], s = K.suelo(100, 136, 60) + per(K, 100, 62, P.amarillo, 1); Q.forEach(function (q) { var w = Math.min(84, q[0].length * 3.3 + 8); s += K.r(q[1] - w / 2, q[2] - 8, w, 14, 7, P.blanco, { w: .8 }) + K.t(q[1], q[2] + 1.6, q[0], { s: ajusta(q[0], w - 4, 5.4), b: 1 }); }); return s + K.t(100, 140, 'Religiones, filosofía y ciencia responden de formas distintas', { s: 4.8, b: 1 }); },
      intro: 'Todas las culturas se han hecho preguntas sobre el origen, el sentido de la vida y la muerte.',
      q: [['¿Qué pregunta intenta responder la ciencia?', 'Sobre todo, de dónde venimos y cómo funciona el mundo.'], ['¿Qué preguntas tratan las religiones?', 'El sentido de la vida, la muerte y Dios.'], ['¿Qué pregunta te haces tú?', 'Respuesta personal.']],
      porque: 'Hacerse preguntas profundas es una de las cosas que nos hacen humanos.' },
    { id: 're_ciencia_fe', fam: 'dia', n: 'Ciencia y fe: preguntas distintas',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(12, 16, 80, 84, 6, P.azul, { w: .9, op: .7 }) + K.r(108, 16, 80, 84, 6, P.amarillo, { w: .9, op: .7 }); s += K.t(52, 30, 'CIENCIA', { s: 7, b: 1 }) + K.t(52, 42, '¿cómo funciona?', { s: 5.6, b: 1 }) + K.t(52, 58, 'observación', { s: 5.2 }) + K.t(52, 68, 'experimento', { s: 5.2 }) + K.t(52, 78, 'datos y pruebas', { s: 5.2 }) + K.t(148, 30, 'FE', { s: 7, b: 1 }) + K.t(148, 42, '¿qué sentido tiene?', { s: 5.6, b: 1 }) + K.t(148, 58, 'confianza', { s: 5.2 }) + K.t(148, 68, 'tradición', { s: 5.2 }) + K.t(148, 78, 'textos sagrados', { s: 5.2 }) + K.flecha(92, 58, 106, 58, P.tinta, { w: 1, p: 3 }) + K.flecha(108, 66, 94, 66, P.tinta, { w: 1, p: 3 }); return s + K.t(100, 116, 'Georges Lemaître, sacerdote y físico, propuso en 1927', { s: 5, b: 1 }) + K.t(100, 124, 'que el universo se expande: la base de la teoría del Big Bang', { s: 5 }); },
      intro: 'La ciencia y la religión responden a preguntas distintas y pueden dialogar sin confundirse.',
      q: [['¿Qué tipo de pregunta responde la ciencia?', '¿Cómo funciona? Con observación y experimentos.'], ['¿Quién fue Georges Lemaître?', 'Un sacerdote belga y físico que propuso la expansión del universo.'], ['¿Puede un científico tener fe?', 'Sí: muchos científicos son creyentes y otros no.']],
      porque: 'Distinguir el tipo de pregunta evita conflictos innecesarios entre ciencia y fe.' },
    /* ─────────── COSMOVISIONES ─────────── */
    { id: 're_tres_pachas', fam: 'cos', n: 'Los tres mundos andinos',
      d: function (K) { var s = K.r(14, 10, 172, 38, 4, P.azul, { w: .8 }) + K.r(14, 52, 172, 38, 4, P.cesped, { w: .8 }) + K.r(14, 94, 172, 38, 4, P.madera, { w: .8 }); s += K.p('M140 30 L120 22 L134 28 L128 34 Z M140 30 L160 22 L146 28 L152 34 Z', P.tinta, { w: .5, negro: 1 }) + K.c(140, 28, 3, P.blanco, { w: .4 }); s += K.e(146, 72, 14, 6, P.oro, { w: .7 }) + K.c(162, 66, 5, P.oro, { w: .7 }) + K.l('M134 76 L132 84 M140 77 L140 84 M152 77 L152 84 M158 76 L160 84 M132 70 Q124 64 126 58', P.oro, { w: 1.6 }); s += K.l('M124 112 Q132 104 140 112 T156 112 T172 112', P.verdeO, { w: 2.4 }) + K.c(172, 112, 2, P.verdeO, { w: .4 }); return s + K.t(66, 26, 'Hanan Pacha', { s: 6.4, b: 1 }) + K.t(66, 36, 'mundo de arriba · cóndor', { s: 5 }) + K.t(66, 68, 'Kay Pacha', { s: 6.4, b: 1 }) + K.t(66, 78, 'este mundo · puma', { s: 5 }) + K.t(66, 110, 'Uku Pacha', { s: 6.4, b: 1 }) + K.t(66, 120, 'mundo de abajo · serpiente', { s: 5 }) + K.t(100, 144, 'Cosmovisión andina (quechua y aimara) · la Pachamama es la madre tierra', { s: 4.6, b: 1 }); },
      intro: 'Para los pueblos andinos el cosmos tiene tres mundos unidos, cada uno con un animal que lo representa.',
      q: [['¿Qué animal representa el mundo de arriba?', 'El cóndor.'], ['¿Qué es la Pachamama?', 'La madre tierra, a la que se agradece y se ofrenda.'], ['¿En qué países vive esta tradición?', 'Sobre todo en Perú, Bolivia, Ecuador y el norte de Chile y Argentina.']],
      porque: 'Las cosmovisiones indígenas enseñan a ver la naturaleza como algo sagrado y vivo.' },
    { id: 're_popol_vuh', fam: 'cos', n: 'Popol Vuh: los hombres de maíz',
      d: function (K) { var s = K.suelo(100, 132, 90); [['de barro', 'se deshacían con el agua', P.madera, 38], ['de madera', 'no tenían corazón ni memoria', P.arena, 100], ['de maíz', 'pudieron hablar y agradecer', P.amarillo, 162]].forEach(function (q, i) { s += per(K, q[3], 62, q[2], 1.1) + K.t(q[3], 30, (i + 1) + '.º intento', { s: 5.6, b: 1 }) + K.t(q[3], 112, q[0], { s: 6.4, b: 1 }) + K.t(q[3], 121, q[1], { s: ajusta(q[1], 56, 4.8) }); if (i < 2) s += K.flecha(q[3] + 18, 74, q[3] + 44, 74, P.grisO, { w: 1, p: 3 }); }); [[156, 56], [168, 56], [162, 50]].forEach(function (p) { s += K.e(p[0], p[1] + 20, 2.4, 3.4, P.oro, { w: .4 }); }); return s + K.t(100, 16, 'Libro sagrado del pueblo maya k’iche’ · Guatemala', { s: 5.4, b: 1 }) + K.t(100, 140, 'El maíz, alimento de Mesoamérica, se vuelve carne humana', { s: 5, b: 1 }); },
      intro: 'El Popol Vuh cuenta que los dioses intentaron crear a los seres humanos tres veces hasta lograrlo con maíz.',
      q: [['¿De qué materiales se intentó crear al ser humano?', 'Barro, madera y, por fin, maíz.'], ['¿Qué les faltaba a los hombres de madera?', 'Corazón y memoria: no recordaban a sus creadores.'], ['¿Por qué el maíz?', 'Porque era el alimento básico de los pueblos mayas.']],
      porque: 'Los relatos de origen muestran lo que cada pueblo considera más valioso.' },
    G('re_mitos_creacion', 'cos', 'Relatos de creación del mundo', [['Génesis', 'Dios crea con su palabra'], ['Popol Vuh', 'los dioses forman al ser humano de maíz'], ['Pangu · China', 'un gigante separa el cielo y la tierra'], ['Brahma · India', 'nace de un loto y crea el mundo']], 2, 20, 44, 'Cada pueblo contó su origen con sus propias imágenes', 'Casi todas las culturas tienen un relato que explica cómo empezó el mundo.', [['¿Qué relato habla de un gigante?', 'El de Pangu, de China.'], ['¿Qué tienen en común todos?', 'Explican el origen del mundo y del ser humano y su lugar en él.'], ['¿Son relatos científicos?', 'No: son relatos simbólicos sobre el sentido del mundo.']], 'Comparar relatos de origen muestra lo que une a la humanidad.', { s: 9, s2: 5.4 }),
    { id: 're_sincretismo', fam: 'cos', n: 'El sincretismo en América',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.c(76, 50, 36, P.verde, { w: 1, op: .7 }) + K.c(124, 50, 36, P.amarillo, { w: 1, op: .7 }); s += K.t(56, 46, 'tradiciones', { s: 5.6, b: 1 }) + K.t(56, 54, 'indígenas y', { s: 5.6, b: 1 }) + K.t(56, 62, 'africanas', { s: 5.6, b: 1 }) + K.t(146, 50, 'cristianismo', { s: 5.6, b: 1 }) + K.t(100, 48, 'mezcla', { s: 6, b: 1 }); [['Guadalupe y el cerro del Tepeyac', 'México'], ['Inti Raymi y San Juan, 24 de junio', 'Perú'], ['Santería: orishas y santos', 'Cuba']].forEach(function (q, i) { var y = 100 + i * 13; s += K.r(16, y - 8, 168, 11, 5, CO[i], { w: .5 }) + K.t(22, y, q[0], { s: 5.2, b: 1, a: 'start' }) + K.t(178, y, q[1], { s: 5, a: 'end' }); }); return s; },
      intro: 'El sincretismo es la mezcla de creencias de culturas distintas; en América unió tradiciones indígenas, africanas y cristianas.',
      q: [['¿Qué es el sincretismo?', 'La fusión de elementos de religiones o culturas diferentes.'], ['¿Qué fiesta andina coincide con San Juan?', 'El Inti Raymi, la fiesta del sol, el 24 de junio.'], ['Busca un ejemplo de sincretismo en tu país.', 'Respuesta según el país.']],
      porque: 'Las culturas no se reemplazan sin más: se mezclan y crean algo nuevo.' }
  ];
  MO.agregar('religion', L, { nombre: 'Religión y cultura religiosa', familias: FAM, materias: /^(religion)$/ });
})();
