/* b6_lib_efisica2.js — Educación física (2/2): atletismo, gimnasia y expresión, deportes colectivos, juegos, seguridad. 29 modelos.
   Materia `efisica`. Prefijo `ef_`. Cargar después de b6_lib_efisica.js. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('ef_pista')) return;
  var P = { azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', cesped: '#9CCB7A', pista: '#D9866A', agua: '#9CCBE6', madera: '#D8B080', arena: '#EAD7A0' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { cal: 'Calentamiento y estiramiento', cap: 'Capacidades físicas', sal: 'Salud y hábitos', ent: 'Entrenamiento', atl: 'Atletismo', gim: 'Gimnasia y expresión', dep: 'Deportes colectivos', jue: 'Juegos y recreación', seg: 'Seguridad y primeros auxilios' };
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + f1 * .35, q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  function fig(K, x, y, o) {
    o = o || {}; var e = o.e || 1, col = o.col || P.azul, rad = Math.PI / 180, tor = (o.tronco || 0) * rad, L1 = 13 * e, L2 = 12 * e, T = 18 * e;
    var hx = x + Math.sin(tor) * T, hy = y - Math.cos(tor) * T, s = '';
    function seg(x0, y0, a1, a2, l1, l2, c) { var x1 = x0 + Math.sin(a1 * rad) * l1, y1 = y0 + Math.cos(a1 * rad) * l1, x2 = x1 + Math.sin(a2 * rad) * l2, y2 = y1 + Math.cos(a2 * rad) * l2; return K.l('M' + x0.toFixed(1) + ' ' + y0.toFixed(1) + ' L' + x1.toFixed(1) + ' ' + y1.toFixed(1) + ' L' + x2.toFixed(1) + ' ' + y2.toFixed(1), c, { w: 3.4 * e }); }
    var b = o.b || [20, 20, -20, -20], p = o.p || [8, 8, -8, -8];
    s += seg(x, y, p[0], p[1], L1, L2, K.oscuro(col, .35)) + seg(x, y, p[2], p[3], L1, L2, K.oscuro(col, .35));
    s += K.l('M' + x + ' ' + y + ' L' + hx.toFixed(1) + ' ' + hy.toFixed(1), col, { w: 5 * e });
    var sx = x + Math.sin(tor) * T * .85, sy = y - Math.cos(tor) * T * .85;
    s += seg(sx, sy, b[0], b[1], 10 * e, 9 * e, col) + seg(sx, sy, b[2], b[3], 10 * e, 9 * e, col);
    return s + K.c(hx + Math.sin(tor) * 5 * e, hy - Math.cos(tor) * 5 * e, 4.6 * e, P.piel, { w: .7 });
  }
  var CORRE = { tronco: 12, b: [-50, -100, 70, 120], p: [55, -20, -40, -60] };
  function jug(K, x, y, col, n) { return K.c(x, y, 5, col, { w: .8 }) + (n ? K.t(x, y + 2, String(n), { s: 4.8, b: 1 }) : ''); }
  function campo(K, x, y, w, h, col) { return K.r(x, y, w, h, 1, col || P.cesped, { w: 1 }) + K.l('M' + (x + w / 2) + ' ' + y + ' L' + (x + w / 2) + ' ' + (y + h), P.blanco, { w: .9 }) + K.c(x + w / 2, y + h / 2, h * .16, 'none', { w: .9, c: P.blanco }); }
  function balon(K, x, y, r, col) { return K.c(x, y, r, col || P.blanco, { w: .8 }) + K.l('M' + (x - r) + ' ' + y + ' Q' + x + ' ' + (y - r * .5) + ' ' + (x + r) + ' ' + y, P.grisO, { w: .5 }); }

  var L = [
    /* ─────────── ATLETISMO ─────────── */
    { id: 'ef_pista', fam: 'atl', n: 'La pista de atletismo',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.p('M50 20 L150 20 A46 46 0 0 1 150 112 L50 112 A46 46 0 0 1 50 20 Z', P.pista, { w: 1 }) + K.p('M50 44 L150 44 A22 22 0 0 1 150 88 L50 88 A22 22 0 0 1 50 44 Z', P.cesped, { w: .9 }); for (var i = 1; i < 8; i++) { var r = 22 + i * 3; s += K.p('M50 ' + (66 - r) + ' L150 ' + (66 - r) + ' A' + r + ' ' + r + ' 0 0 1 150 ' + (66 + r) + ' L50 ' + (66 + r) + ' A' + r + ' ' + r + ' 0 0 1 50 ' + (66 - r) + ' Z', 'none', { w: .3 }); } s += K.l('M150 88 L150 112', P.blanco, { w: 1.6 }); return s + K.t(100, 70, 'zona de lanzamientos y saltos', { s: 5, b: 1 }) + K.t(162, 104, 'meta', { s: 5.6, b: 1, a: 'start' }) + K.t(100, 128, '400 m por la calle 1 · 8 calles', { s: 6.2, b: 1 }) + K.t(100, 138, 'En las curvas, las calles exteriores salen adelantadas', { s: 5 }); },
      intro: 'La pista oficial mide 400 metros en la calle interior y tiene ocho calles separadas por líneas.',
      q: [['¿Cuántas vueltas son 1 500 m?', '3 vueltas y tres cuartos.'], ['¿Por qué las salidas de las calles exteriores están escalonadas?', 'Porque su curva es más larga; así todos corren la misma distancia.'], ['¿Qué pruebas se hacen en el centro?', 'Saltos y lanzamientos.']],
      porque: 'Una curva de radio mayor es más larga: escalonar la salida compensa la diferencia.' },
    { id: 'ef_salida', fam: 'atl', n: 'La salida de velocidad',
      d: function (K) { var s = K.suelo(100, 136, 96) + K.l('M10 120 L190 120', P.blanco, { w: 1.4 }); [['«A sus puestos»', { tronco: 80, b: [0, 0, 5, 0], p: [-70, 30, -110, 10] }, 36], ['«Listos»', { tronco: 65, b: [5, 0, 10, 0], p: [-60, 20, -95, 0] }, 100], ['¡Pum!', { tronco: 45, b: [-70, -110, 60, 100], p: [-30, 30, -80, -40] }, 164]].forEach(function (q) { s += fig(K, q[2], 104, q[1]) + K.t(q[2], 132, q[0], { s: 6, b: 1 }); }); return s + K.t(100, 20, 'Tacos de salida, manos detrás de la línea', { s: 5.8, b: 1 }) + K.t(100, 30, 'Cadera arriba en «listos» · empuje fuerte con las dos piernas', { s: 5 }); },
      intro: 'La salida baja se hace en tres tiempos que preparan el cuerpo para empujar con fuerza.',
      q: [['¿Qué se levanta en la orden «listos»?', 'La cadera, por encima de los hombros.'], ['¿Qué pasa si se sale antes del disparo?', 'Es salida falsa y se descalifica al atleta.'], ['¿Por qué se mantiene el cuerpo inclinado al salir?', 'Para empujar hacia delante y acelerar.']],
      porque: 'Inclinarse al salir dirige toda la fuerza de las piernas hacia delante.' },
    { id: 'ef_relevos', fam: 'atl', n: 'Los relevos 4 × 100',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(10, 56, 180, 30, 1, P.pista, { w: .9 }) + K.r(80, 56, 40, 30, 0, P.amarillo, { w: .5, op: .5 }) + fig(K, 70, 84, Object.assign({ e: .8, col: P.azul }, CORRE)) + fig(K, 110, 84, Object.assign({ e: .8, col: P.rojo }, { tronco: 10, b: [-40, -90, 120, 100], p: [50, -20, -30, -50] })) + K.r(86, 66, 10, 3, 1, P.amarillo, { w: .7 }); return s + K.t(100, 50, 'zona de transferencia: 30 m', { s: 5.6, b: 1 }) + K.t(100, 100, 'el testigo se pasa dentro de la zona', { s: 5.4, b: 1 }) + K.t(100, 22, '4 atletas × 100 m', { s: 7, b: 1 }) + K.t(100, 32, 'El que recibe ya va corriendo', { s: 5.4 }) + K.t(100, 124, 'Mano abajo, palma arriba: «¡ya!» y entrega', { s: 5.6, b: 1 }); },
      intro: 'En los relevos, cuatro atletas corren 100 m cada uno y se pasan un testigo dentro de una zona marcada.',
      q: [['¿Qué pasa si el testigo se entrega fuera de la zona?', 'El equipo queda descalificado.'], ['¿Por qué el que recibe empieza a correr antes?', 'Para recibir el testigo ya a gran velocidad.'], ['¿Quién lleva el testigo al final?', 'El cuarto relevista, hasta la meta.']],
      porque: 'Un buen relevo no depende solo de correr rápido: la entrega puede ganar o perder la carrera.' },
    { id: 'ef_longitud', fam: 'atl', n: 'Las fases del salto de longitud',
      d: function (K) { var s = K.suelo(100, 136, 96) + K.r(8, 116, 110, 6, 0, P.pista, { w: .7 }) + K.r(118, 116, 74, 8, 0, P.arena, { w: .8 }) + K.r(110, 115, 8, 3, 0, P.blanco, { w: .6 }); [['carrera', CORRE, 22, 104], ['batida', { tronco: 0, b: [-150, -160, 40, 30], p: [-10, 0, 60, 80] }, 90, 100], ['vuelo', { tronco: -10, b: [-160, -170, 160, 170], p: [-70, 0, -80, 10] }, 132, 72], ['caída', { tronco: 40, b: [-100, -110, -90, -100], p: [-90, 0, -80, 0] }, 170, 108]].forEach(function (q) { s += fig(K, q[2], q[3], Object.assign({ e: .75 }, q[1])) + K.t(q[2], 132, q[0], { s: 5.8, b: 1 }); }); return s + K.l('M90 110 Q130 50 172 106', P.grisO, { w: .6 }) + K.t(100, 22, 'Se mide desde la tabla hasta la marca más cercana', { s: 5.6, b: 1 }); },
      intro: 'El salto de longitud se divide en carrera, batida en la tabla, vuelo y caída en la arena.',
      q: [['¿Desde dónde se mide el salto?', 'Desde el borde de la tabla de batida.'], ['¿Qué marca se toma si el atleta cae hacia atrás?', 'La más cercana a la tabla, aunque sea la mano.'], ['¿Qué pasa si se pisa más allá de la tabla?', 'Es salto nulo.']],
      porque: 'La velocidad de la carrera se convierte en distancia: por eso los saltadores son velocistas.' },
    { id: 'ef_lanzamientos', fam: 'atl', n: 'Los lanzamientos',
      d: function (K) { var s = K.suelo(100, 140, 96); [['peso', 'bola de metal', 34, function (x, y) { return K.c(x, y, 5, '#8A8E94', { w: .7 }); }], ['disco', 'giro y suelta', 100, function (x, y) { return K.e(x, y, 7, 2.6, '#8A8E94', { w: .7 }); }], ['jabalina', 'carrera y lanzamiento', 166, function (x, y) { return K.l('M' + (x - 18) + ' ' + (y + 6) + ' L' + (x + 18) + ' ' + (y - 6), P.grisO, { w: 1.4 }); }]].forEach(function (q) { s += fig(K, q[2], 96, { b: [-150, -170, 50, 30], p: [10, 10, -25, -20] }) + q[3](q[2] + 12, 54) + K.t(q[2], 118, q[0], { s: 6.4, b: 1 }) + K.t(q[2], 126, q[1], { s: 5 }); }); return s + K.t(100, 22, 'Siempre de uno en uno y con la zona despejada', { s: 6, b: 1, c: P.rojoO }) + K.t(100, 32, 'Se recoge el implemento cuando todos han lanzado', { s: 5.2 }); },
      intro: 'En los lanzamientos se impulsa un objeto lo más lejos posible con una técnica propia de cada prueba.',
      q: [['¿Qué lanzamiento se hace empujando desde el hombro?', 'El de peso.'], ['¿Por qué es tan importante la seguridad?', 'Porque un implemento puede causar lesiones graves.'], ['¿Qué ángulo de salida da más distancia en teoría?', 'Cerca de 45°, aunque en la práctica algo menos.']],
      porque: 'Las reglas de seguridad en los lanzamientos no tienen excepciones.' },
    G('ef_atletismo', 'atl', 'Las pruebas del atletismo', [['Velocidad', '100, 200, 400 m'], ['Medio fondo', '800, 1 500 m'], ['Fondo', '5 000, 10 000 m, maratón'], ['Vallas', '100/110 y 400 m'], ['Relevos', '4 × 100, 4 × 400'], ['Saltos', 'longitud, triple, altura, pértiga'], ['Lanzamientos', 'peso, disco, jabalina, martillo'], ['Pruebas combinadas', 'heptatlón, decatlón']], 2, 16, 23, 'La maratón mide 42,195 km', 'El atletismo agrupa carreras, saltos y lanzamientos.', [['¿Cuántas pruebas tiene el decatlón?', 'Diez.'], ['¿Qué prueba de salto usa una vara?', 'El salto con pértiga.'], ['¿Cuántas vueltas a la pista son 10 000 m?', '25.']], 'Es el deporte olímpico más antiguo: correr, saltar y lanzar.', { s: 7.4, s2: 5.2 }),
    /* ─────────── GIMNASIA Y EXPRESIÓN ─────────── */
    { id: 'ef_voltereta', fam: 'gim', n: 'La voltereta hacia delante',
      d: function (K) { var s = K.suelo(100, 132, 96) + K.r(8, 118, 184, 8, 3, P.azul, { w: .8 }); [[24, { tronco: 10, b: [160, 170, -160, -170], p: [-10, 0, 10, 0] }, '1 de pie'], [62, { tronco: 110, b: [-170, -180, -170, -180], p: [-40, 20, -40, 20] }, '2 manos y barbilla'], [108, { tronco: 170, b: [90, 60, 80, 60], p: [-150, -40, -150, -40] }, '3 rodar'], [152, { tronco: 40, b: [80, 100, 70, 90], p: [-90, 0, -90, 0] }, '4 agrupado'], [180, { b: [-80, -80, 80, 80] }, '5 arriba']].forEach(function (q, i) { s += fig(K, q[0], i === 2 ? 104 : 110, Object.assign({ e: .7 }, q[1])) + K.t(q[0], 30 + (i % 2) * 8, q[2], { s: 5, b: 1 }); }); return s + K.t(100, 140, 'Barbilla al pecho: rueda la espalda, no la cabeza', { s: 5.6, b: 1 }); },
      intro: 'La voltereta hacia delante es un giro sobre la espalda con el cuerpo agrupado.',
      q: [['¿Por qué se mete la barbilla?', 'Para que la nuca y la espalda rueden y no se apoye la cabeza.'], ['¿Dónde se apoyan las manos?', 'En la colchoneta, a la anchura de los hombros.'], ['¿Cómo se termina?', 'Agrupado, levantándose sin apoyar las manos.']],
      porque: 'Una espalda redonda rueda como una pelota; una espalda recta golpea.' },
    { id: 'ef_equilibrios', fam: 'gim', n: 'Equilibrios individuales y en pareja',
      d: function (K) { var s = K.suelo(100, 136, 96); s += fig(K, 30, 100, { b: [-90, -90, 90, 90], p: [0, 0, -100, -95] }) + K.t(30, 124, 'avión', { s: 6, b: 1 }); s += fig(K, 80, 100, { b: [-160, -175, 160, 175], p: [0, 0, -60, 40] }) + K.t(80, 124, 'flamenco', { s: 6, b: 1 }); s += fig(K, 130, 100, { tronco: -20, b: [-60, -60, 0, 0], col: P.rojo }) + fig(K, 160, 100, { tronco: 20, b: [60, 60, 0, 0], col: P.verde }) + K.t(145, 124, 'contrapeso en pareja', { s: 6, b: 1 }); return s + K.t(100, 22, 'Mirada fija en un punto · abdomen firme', { s: 6, b: 1 }) + K.t(100, 32, 'Aguantar 5 segundos sin moverse', { s: 5.4 }); },
      intro: 'En los equilibrios se mantiene una postura quieta controlando el centro de gravedad.',
      q: [['¿Por qué ayuda mirar un punto fijo?', 'Porque la vista ayuda al oído interno a mantener el equilibrio.'], ['¿Qué pasa en el contrapeso si uno suelta?', 'Los dos pierden el equilibrio: dependen el uno del otro.'], ['¿Por qué abrir los brazos en el avión?', 'Para equilibrar el peso de la pierna levantada.']],
      porque: 'Mantenerse en equilibrio es mantener el centro de gravedad sobre la base de apoyo.' },
    { id: 'ef_acrosport', fam: 'gim', n: 'Pirámides de acrosport',
      d: function (K) { var s = K.suelo(100, 136, 96); s += fig(K, 60, 112, { tronco: 90, b: [0, 0, 0, 0], p: [0, 0, 0, 0], col: P.azul, e: .8 }) + fig(K, 90, 112, { tronco: 90, b: [0, 0, 0, 0], p: [0, 0, 0, 0], col: P.azul, e: .8 }); s = K.suelo(100, 136, 96); [[64, P.azul], [100, P.azul], [136, P.azul]].forEach(function (q) { s += K.r(q[0] - 14, 98, 28, 12, 4, q[1], { w: .8 }) + K.c(q[0] + 16, 102, 4, P.piel, { w: .6 }) + K.l('M' + (q[0] - 12) + ' 110 L' + (q[0] - 12) + ' 120 M' + (q[0] + 12) + ' 110 L' + (q[0] + 12) + ' 120', K.oscuro(q[1], .3), { w: 3 }); }); [[82, P.verde], [118, P.verde]].forEach(function (q) { s += K.r(q[0] - 14, 76, 28, 12, 4, q[1], { w: .8 }) + K.c(q[0] + 16, 80, 4, P.piel, { w: .6 }) + K.l('M' + (q[0] - 12) + ' 88 L' + (q[0] - 12) + ' 98 M' + (q[0] + 12) + ' 88 L' + (q[0] + 12) + ' 98', K.oscuro(q[1], .3), { w: 3 }); }); s += fig(K, 100, 76, { b: [-150, -170, 150, 170], col: P.amarillo, e: .8 }); return s + K.t(100, 22, 'Bases abajo, ágiles arriba, un ayudante al lado', { s: 5.8, b: 1 }) + K.t(100, 32, 'Apoyos sobre hombros y caderas, nunca en la mitad de la espalda', { s: 5 }) + K.t(100, 132, 'Se sube y se baja en orden inverso', { s: 5.8, b: 1 }); },
      intro: 'En el acrosport un grupo forma figuras humanas con bases, ágiles y ayudantes.',
      q: [['¿Dónde se apoya el ágil sobre la base?', 'En hombros y caderas, nunca en el centro de la espalda.'], ['¿Qué hace el ayudante?', 'Vigila y sujeta para que nadie caiga.'], ['¿En qué orden se deshace la figura?', 'Al revés de como se montó: primero baja el de arriba.']],
      porque: 'Hombros y caderas soportan peso; la mitad de la espalda no.' },
    { id: 'ef_coreografia', fam: 'gim', n: 'Contar una coreografía en ochos',
      d: function (K) { var s = K.suelo(100, 140, 96); for (var i = 0; i < 8; i++) { var x = 18 + i * 22; s += K.c(x, 26, 8, i % 4 === 0 ? P.rosa : P.gris, { w: .7 }) + K.t(x, 28.5, String(i + 1), { s: 7, b: 1 }); } [[18, { b: [160, 170, -20, -20] }], [62, { b: [20, 20, -160, -170] }], [106, { b: [-90, -90, 90, 90], p: [40, 0, -8, -8] }], [150, { b: [160, 170, -160, -170], p: [8, 8, -8, -8] }]].forEach(function (q, i) { s += fig(K, q[0] + 11, 96, Object.assign({ e: .8 }, q[1])) + K.t(q[0] + 11, 120, ['1-2', '3-4', '5-6', '7-8'][i], { s: 6, b: 1 }); }); return s + K.t(100, 50, '«cinco, seis, siete, ocho» antes de empezar', { s: 5.6, b: 1 }) + K.t(100, 134, 'Un movimiento cada dos tiempos', { s: 5.8 }); },
      intro: 'Las coreografías se cuentan en bloques de ocho tiempos que coinciden con las frases de la música.',
      q: [['¿Qué se cuenta antes de empezar a bailar?', '«Cinco, seis, siete, ocho».'], ['¿Cuántos movimientos hay en este ocho?', 'Cuatro, uno cada dos tiempos.'], ['¿Por qué contar en ochos?', 'Porque casi toda la música popular agrupa los tiempos así.']],
      porque: 'Contar en ochos permite a un grupo moverse junto aunque no oiga bien la música.' },
    G('ef_expresion', 'gim', 'Expresión corporal', [['Mímica', 'contar sin palabras'], ['Estatuas', 'quedarse quieto expresando'], ['Espejo', 'imitar a la pareja'], ['Ritmo', 'moverse al compás'], ['Danza tradicional', 'bailes del país'], ['Dramatización', 'representar una historia']], 2, 22, 28, 'El cuerpo también comunica: gestos, postura, mirada', 'La expresión corporal usa el movimiento para comunicar ideas y emociones.', [['¿Qué se trabaja en el juego del espejo?', 'La atención, la coordinación y la cooperación.'], ['Representa «tengo frío» sin hablar.', 'Encogerse, frotarse los brazos y tiritar.'], ['Nombra una danza tradicional de tu país.', 'Respuesta abierta: por ejemplo cumbia, joropo, marinera o cueca.']], 'Los gestos dicen tanto como las palabras.', { s: 7.4, s2: 5.6 }),
    /* ─────────── DEPORTES COLECTIVOS ─────────── */
    { id: 'ef_futbol', fam: 'dep', n: 'El campo de fútbol y las posiciones',
      d: function (K) { var s = K.suelo(100, 140, 96) + campo(K, 10, 18, 180, 104); s += K.r(10, 46, 26, 48, 0, 'none', { w: .8 }) + K.r(164, 46, 26, 48, 0, 'none', { w: .8 }) + K.r(6, 60, 4, 20, 0, P.blanco, { w: .6 }) + K.r(190, 60, 4, 20, 0, P.blanco, { w: .6 }); [[18, 70, 1], [44, 36, 2], [44, 58, 3], [44, 82, 4], [44, 104, 5], [70, 46, 6], [70, 70, 8], [70, 94, 10], [92, 34, 7], [92, 70, 9], [92, 106, 11]].forEach(function (q) { s += jug(K, q[0], q[1], P.azul, q[2]); }); return s + K.t(18, 132, 'portero', { s: 5, b: 1 }) + K.t(44, 132, 'defensas', { s: 5, b: 1 }) + K.t(70, 132, 'medios', { s: 5, b: 1 }) + K.t(94, 132, 'delanteros', { s: 5, b: 1 }) + K.t(156, 132, '11 · sistema 1-4-3-3', { s: 5.4, b: 1 }); },
      intro: 'Un equipo de fútbol tiene once jugadores repartidos en portero, defensas, centrocampistas y delanteros.',
      q: [['¿Cuántos defensas tiene el sistema 4-3-3?', 'Cuatro.'], ['¿Quién puede tocar el balón con las manos?', 'Solo el portero, dentro de su área.'], ['¿Cuánto dura un partido oficial?', 'Dos tiempos de 45 minutos.']],
      porque: 'Ocupar bien el campo es tan importante como tener buena técnica.' },
    { id: 'ef_baloncesto', fam: 'dep', n: 'La cancha de baloncesto',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(10, 18, 180, 104, 1, P.madera, { w: 1 }) + K.l('M100 18 L100 122', P.tinta, { w: .8 }) + K.c(100, 70, 12, 'none', { w: .8 }); [[10, 1], [190, -1]].forEach(function (q) { var x = q[0], d = q[1]; s += K.r(Math.min(x, x + d * 38), 54, 38, 32, 0, P.naranja, { w: .8, op: .6 }) + K.p('M' + x + ' 26 L' + (x + d * 30) + ' 26 A48 48 0 0 ' + (d > 0 ? 1 : 0) + ' ' + (x + d * 30) + ' 114 L' + x + ' 114', 'none', { w: .8 }) + K.c(x + d * 8, 70, 3, 'none', { w: 1.2, c: P.rojoO }); }); return s + K.t(100, 14, '5 jugadores por equipo · 4 cuartos de 10 min', { s: 5.6, b: 1 }) + K.t(38, 50, 'zona', { s: 5, b: 1 }) + K.t(62, 108, 'triple', { s: 5, b: 1 }) + K.t(100, 132, 'Dentro: 2 puntos · desde fuera de la línea: 3 · tiro libre: 1', { s: 5.2, b: 1 }); },
      intro: 'En baloncesto cada canasta vale 1, 2 o 3 puntos según desde dónde se lance.',
      q: [['¿Cuántos puntos vale una canasta desde fuera de la línea de 6,75 m?', 'Tres.'], ['¿Se puede caminar con el balón en las manos?', 'No: hay que botar; si no, es pasos.'], ['¿Cuántos jugadores hay en la cancha por equipo?', 'Cinco.']],
      porque: 'Lanzar de lejos da más puntos pero es más difícil: el equipo elige el riesgo.' },
    { id: 'ef_voleibol', fam: 'dep', n: 'La cancha de voleibol y la rotación',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(20, 30, 160, 80, 1, P.naranja, { w: 1 }) + K.l('M100 22 L100 118', P.tinta, { w: 1.6 }) + K.l('M74 30 L74 110 M126 30 L126 110', P.blanco, { w: .7 }); var pos = [[90, 96, 2], [90, 70, 3], [90, 44, 4], [44, 44, 5], [44, 70, 6], [44, 96, 1]]; pos.forEach(function (q) { s += jug(K, q[0] - 6, q[1], P.amarillo, q[2]); }); s += K.flecha(36, 102, 36, 50, P.azulO, { w: .9, p: 3 }) + K.flecha(50, 38, 80, 38, P.azulO, { w: .9, p: 3 }); return s + K.t(100, 16, 'red', { s: 5.4, b: 1 }) + K.t(100, 126, '6 jugadores · al ganar el saque se rota en sentido horario', { s: 5.4, b: 1 }) + K.t(100, 136, 'El 1 saca desde detrás de la línea de fondo', { s: 5 }) + K.t(150, 70, 'campo rival', { s: 5.4 }); },
      intro: 'En voleibol juegan seis por equipo, y cada vez que se recupera el saque se rota una posición.',
      q: [['¿Cuántos toques puede dar un equipo antes de pasar el balón?', 'Tres.'], ['¿Quién saca?', 'El jugador que ocupa la posición 1.'], ['¿Para qué sirve rotar?', 'Para que todos pasen por todas las posiciones.']],
      porque: 'La rotación obliga a que todos ataquen, defiendan y saquen.' },
    { id: 'ef_pase', fam: 'dep', n: 'Tipos de pase',
      d: function (K) { var s = K.suelo(100, 140, 96); [['de pecho', 'directo y tenso', 30, 'M42 60 L80 60'], ['picado', 'bota antes de llegar', 30, 'M42 98 L62 116 L80 98'], ['bombeado', 'por encima de un rival', 120, 'M132 60 Q150 20 170 60'], ['de pie', 'interior del pie, raso', 120, 'M132 108 L170 108']].forEach(function (q, i) { var y = i % 2 ? 98 : 60; s += fig(K, q[2], y + 20, { e: .7, b: [-100, -80, 100, 80] }) + fig(K, q[2] + 54, y + 20, { e: .7, b: [-100, -80, 100, 80], col: P.verde }) + K.l(q[3], P.rojoO, { w: 1 }) + K.t(q[2] + 27, y - 12 + (i === 2 ? -6 : 0) + (i % 2 ? 0 : 0), q[0], { s: 5.8, b: 1 }) + K.t(q[2] + 27, y + 34, q[1], { s: 4.8 }); }); return s; },
      intro: 'El tipo de pase depende de la distancia, de los rivales y del deporte.',
      q: [['¿Qué pase supera a un rival que está en medio?', 'El bombeado o el picado.'], ['¿Cuál es el más rápido?', 'El de pecho, directo y tenso.'], ['¿Con qué parte del pie se da el pase más preciso?', 'Con el interior.']],
      porque: 'Un buen pase llega a donde el compañero va, no a donde está.' },
    G('ef_reglas', 'dep', 'Comparar deportes colectivos', [['Fútbol', '11 · pies · 2 × 45 min'], ['Baloncesto', '5 · manos · 4 × 10 min'], ['Voleibol', '6 · golpeo · sets a 25'], ['Balonmano', '7 · manos · 2 × 30 min'], ['Fútbol sala', '5 · pies · 2 × 20 min'], ['Béisbol', '9 · bate · 9 entradas']], 2, 22, 28, 'Jugadores en el campo · cómo se juega · duración', 'Cada deporte colectivo tiene su número de jugadores, su forma de tocar el balón y su duración.', [['¿En qué deporte no hay tiempo fijo?', 'En voleibol y béisbol: se juega por puntos o entradas.'], ['¿Cuántos jugadores tiene un equipo de balonmano en la pista?', 'Siete.'], ['¿Qué deporte se juega con más jugadores?', 'El fútbol, con once.']], 'Comparar las reglas ayuda a entender la lógica de cada juego.', { s: 7.6, s2: 5.6 }),
    { id: 'ef_ataque_def', fam: 'dep', n: 'Atacar y defender',
      d: function (K) { var s = K.suelo(100, 140, 96) + campo(K, 10, 18, 180, 100); [[120, 40], [130, 70], [120, 100], [150, 56], [150, 86]].forEach(function (p) { s += jug(K, p[0], p[1], P.rojo); }); [[60, 30], [80, 60], [70, 100], [100, 46], [104, 90]].forEach(function (p) { s += jug(K, p[0], p[1], P.azul); }); s += K.flecha(80, 60, 100, 46, P.azulO, { w: 1, p: 3 }) + K.flecha(100, 46, 140, 30, P.azulO, { w: .9, p: 3 }) + balon(K, 86, 58, 2.6); return s + K.t(56, 130, 'atacar: abrir espacios', { s: 5.2, b: 1, c: P.azulO }) + K.t(150, 130, 'defender: cerrar espacios', { s: 5.2, b: 1, c: P.rojoO }); },
      intro: 'Cuando el equipo tiene el balón ataca y ocupa espacios amplios; cuando no lo tiene, defiende juntando líneas.',
      q: [['¿Qué hace el equipo azul al atacar?', 'Se abre y busca pases hacia delante.'], ['¿Qué hace el rojo al defender?', 'Se junta y cierra los espacios cerca de su portería.'], ['¿Qué es un contraataque?', 'Atacar muy rápido justo después de recuperar el balón.']],
      porque: 'Abrir el campo con el balón y cerrarlo sin él es la idea común a casi todos los deportes colectivos.' },
    { id: 'ef_juego_limpio', fam: 'dep', n: 'Juego limpio',
      d: function (K) { var s = K.suelo(100, 136, 96) + fig(K, 70, 100, { b: [-60, -40, 40, 20], col: P.azul }) + fig(K, 130, 100, { b: [60, 40, -40, -20], col: P.rojo }) + K.c(100, 66, 4, P.piel, { w: .6 }); return s + K.t(100, 24, 'Saludar al rival · aceptar al árbitro · ayudar al caído', { s: 5.6, b: 1 }) + K.t(100, 34, 'Ganar con respeto · perder con dignidad', { s: 5.4 }) + K.t(100, 128, 'Se compite contra el rival, no contra la persona', { s: 6, b: 1 }); },
      intro: 'El juego limpio es respetar las reglas, a los rivales, a los compañeros y a los árbitros.',
      q: [['¿Qué haces si un rival se cae y se lastima?', 'Detener el juego o echar el balón fuera para que lo atiendan.'], ['¿Cómo se debe reaccionar ante una decisión arbitral injusta?', 'Con calma: el capitán puede preguntar, sin insultos.'], ['¿Por qué saludar al final del partido?', 'Para reconocer al rival como compañero de juego.']],
      porque: 'Sin rival no hay partido: respetarlo es respetar el juego.' },
    /* ─────────── JUEGOS Y RECREACIÓN ─────────── */
    G('ef_juegos', 'jue', 'Juegos tradicionales', [['Rayuela', 'saltar a la pata coja'], ['Cuerda', 'saltar al ritmo'], ['Escondite', 'buscar y esconderse'], ['Pañuelo', 'velocidad y reacción'], ['Trompo', 'lanzar y hacer girar'], ['Canicas', 'puntería'], ['Carrera de sacos', 'saltar con las piernas juntas'], ['Gallina ciega', 'orientarse sin ver']], 2, 16, 23, 'Pregunta a tus mayores a qué jugaban', 'Los juegos tradicionales se transmiten de generación en generación y trabajan muchas capacidades.', [['¿Qué capacidad trabaja el pañuelo?', 'La velocidad de reacción.'], ['¿Y la rayuela?', 'El equilibrio y la coordinación.'], ['¿Qué juego de tu región no está en la lista?', 'Respuesta abierta.']], 'Jugar como se jugaba antes es también conocer la cultura propia.', { s: 7.6, s2: 5.4 }),
    { id: 'ef_rayuela', fam: 'jue', n: 'La rayuela',
      d: function (K) { var s = K.suelo(100, 140, 96), C = [[88, 112, '1'], [88, 96, '2'], [80, 80, '3'], [96, 80, '4'], [88, 64, '5'], [80, 48, '6'], [96, 48, '7']]; C.forEach(function (q) { s += K.r(q[0] - 8 + (q[2] === '3' || q[2] === '6' ? 0 : q[2] === '4' || q[2] === '7' ? 0 : 0), q[1], 16, 16, 0, P.blanco, { w: 1 }) + K.t(q[0], q[1] + 10.5, q[2], { s: 7, b: 1 }); }); s += K.p('M80 32 Q88 18 96 32 Z', P.blanco, { w: 1 }) + K.t(88, 30, 'cielo', { s: 4.6, b: 1 }) + K.c(88, 72, 3, P.rojo, { w: .6 }) + fig(K, 40, 110, { e: .8, p: [0, 0, -60, 50], b: [-90, -90, 90, 90] }); return s + K.t(122, 40, '1 lanzar la piedra', { s: 5.4, b: 1, a: 'start' }) + K.t(122, 50, '2 saltar sin pisarla', { s: 5.4, b: 1, a: 'start' }) + K.t(122, 60, '3 pata coja en una,', { s: 5.4, b: 1, a: 'start' }) + K.t(122, 68, 'dos pies en las dobles', { s: 5.4, a: 'start' }) + K.t(122, 78, '4 recogerla al volver', { s: 5.4, b: 1, a: 'start' }); },
      intro: 'En la rayuela se salta de casilla en casilla sin pisar la que tiene la piedra ni las líneas.',
      q: [['¿Qué pasa si se pisa una línea?', 'Se pierde el turno.'], ['¿Cuándo se apoyan los dos pies?', 'En las casillas dobles, una con cada pie.'], ['¿Qué capacidades trabaja?', 'Equilibrio, coordinación y puntería.']],
      porque: 'Un juego sencillo con piedra y tiza trabaja casi todas las capacidades coordinativas.' },
    { id: 'ef_orientacion', fam: 'jue', n: 'Carrera de orientación',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(14, 14, 120, 112, 2, P.verde, { w: .9 }) + K.p('M40 30 C60 20 80 40 70 60 C60 80 90 90 110 70', 'none', { w: 4, c: P.agua }) + K.r(90, 90, 30, 20, 1, P.gris, { w: .7 }) + K.t(105, 103, 'edificio', { s: 4.6 }); var C = [[30, 110, '▲'], [46, 50, '1'], [94, 36, '2'], [118, 62, '3'], [60, 96, '4']]; C.forEach(function (q, i) { s += (i ? K.c(q[0], q[1], 5, 'none', { w: 1, c: P.morado }) : K.pl([[q[0], q[1] - 6], [q[0] + 6, q[1] + 4], [q[0] - 6, q[1] + 4]], 'none', { w: 1, c: P.morado })) + (i ? K.t(q[0] + 8, q[1] - 4, q[2], { s: 5.6, b: 1, a: 'start', c: P.morado }) : ''); if (i < 4) s += K.l('M' + q[0] + ' ' + q[1] + ' L' + C[i + 1][0] + ' ' + C[i + 1][1], P.morado, { w: .7 }); }); s += K.l('M124 22 L124 34', P.tinta, { w: 1 }) + K.p('M121 26 L124 20 L127 26 Z', P.tinta, { w: .4 }) + K.t(124, 40, 'N', { s: 5, b: 1 }); return s + K.t(162, 34, 'Orientar el mapa', { s: 5.4, b: 1 }) + K.t(162, 42, 'con la brújula', { s: 5 }) + K.t(162, 60, 'Pasar las balizas', { s: 5.4, b: 1 }) + K.t(162, 68, 'en orden: 1, 2, 3, 4', { s: 5 }) + K.t(162, 86, '▲ salida', { s: 5.2, b: 1 }) + K.t(162, 104, 'Gana quien tarda', { s: 5.2 }) + K.t(162, 112, 'menos, sin saltarse', { s: 5.2 }) + K.t(162, 120, 'ninguna baliza', { s: 5.2 }); },
      intro: 'En la carrera de orientación se encuentran puntos de control con un mapa y una brújula.',
      q: [['¿Qué indica el triángulo?', 'La salida.'], ['¿Qué significa orientar el mapa?', 'Girarlo para que su norte coincida con el norte real.'], ['¿Qué capacidades combina?', 'Resistencia, orientación espacial y toma de decisiones.']],
      porque: 'El camino más corto en el mapa no siempre es el más rápido en el terreno.' },
    { id: 'ef_cooperativo', fam: 'jue', n: 'Juegos cooperativos',
      d: function (K) { var s = K.suelo(100, 136, 96) + K.c(100, 76, 38, P.amarillo, { w: 1, op: .7 }); for (var i = 0; i < 8; i++) { var a = i * Math.PI / 4, x = 100 + Math.cos(a) * 46, y = 76 + Math.sin(a) * 34; s += K.c(x, y, 5, CO[i], { w: .7 }); } s += K.c(100, 76, 6, P.blanco, { w: .7 }); return s + K.t(100, 20, 'Paracaídas: todos juntos lanzan la pelota arriba', { s: 5.8, b: 1 }) + K.t(100, 128, 'No hay perdedores: el grupo gana o pierde junto', { s: 5.8, b: 1 }); },
      intro: 'En los juegos cooperativos el grupo entero persigue un mismo objetivo y nadie queda eliminado.',
      q: [['¿Qué diferencia hay con un juego competitivo?', 'Aquí no se juega contra nadie: el reto es del grupo.'], ['¿Qué se aprende en estos juegos?', 'A comunicarse, escuchar y ayudarse.'], ['Propón un juego cooperativo.', 'Por ejemplo, cruzar el aula entre todos sin pisar el «río».']],
      porque: 'Cuando todos ganan juntos, nadie juega con miedo a perder.' },
    /* ─────────── SEGURIDAD Y PRIMEROS AUXILIOS ─────────── */
    { id: 'ef_rice', fam: 'seg', n: 'Una torcedura: protocolo PRICE',
      d: function (K) { var s = K.suelo(100, 140, 96); [['P', 'proteger', 'parar la actividad'], ['R', 'reposo', 'no apoyar'], ['I', 'hielo', '15–20 min, envuelto'], ['C', 'compresión', 'venda sin apretar'], ['E', 'elevación', 'por encima del corazón']].forEach(function (q, i) { var x = 12 + i * 36; s += K.r(x, 30, 32, 64, 4, CO[i], { w: .8 }) + K.t(x + 16, 50, q[0], { s: 14, b: 1 }) + K.t(x + 16, 70, q[1], { s: 5.4, b: 1 }) + K.t(x + 16, 84, q[2], { s: Math.min(4.2, 30 / (q[2].length * .52)) }); }); return s + K.t(100, 18, 'Esguince de tobillo', { s: 7, b: 1 }) + K.t(100, 112, 'Nunca hielo directo sobre la piel', { s: 6, b: 1, c: P.rojoO }) + K.t(100, 124, 'Si duele mucho o no se puede apoyar: al médico', { s: 5.6 }); },
      intro: 'Ante una torcedura se aplica PRICE: proteger, reposo, hielo, compresión y elevación.',
      q: [['¿Por qué se envuelve el hielo en un paño?', 'Para no quemar la piel con el frío.'], ['¿Para qué se eleva el pie?', 'Para reducir la hinchazón.'], ['¿Cuándo hay que ir al médico?', 'Si hay mucho dolor, deformidad o no se puede apoyar.']],
      porque: 'El frío y la elevación reducen la inflamación de las primeras horas.' },
    { id: 'ef_pas', fam: 'seg', n: 'Proteger, avisar, socorrer',
      d: function (K) { var s = K.suelo(100, 140, 96); [['P', 'PROTEGER', 'que no haya más peligro', P.amarillo], ['A', 'AVISAR', 'llamar a emergencias', P.rojo], ['S', 'SOCORRER', 'ayudar sin hacer daño', P.verde]].forEach(function (q, i) { var x = 14 + i * 60; s += K.c(x + 26, 46, 20, q[3], { w: 1 }) + K.t(x + 26, 52, q[0], { s: 16, b: 1 }) + K.t(x + 26, 80, q[1], { s: 6.6, b: 1 }) + K.t(x + 26, 90, q[2], { s: 5 }); }); return s + K.t(100, 112, 'Al llamar: qué pasó, dónde, cuántos heridos', { s: 5.8, b: 1 }) + K.t(100, 124, 'No colgar hasta que lo indiquen', { s: 5.6 }) + K.t(100, 136, 'Aprende el número de emergencias de tu país', { s: 5.4, b: 1 }); },
      intro: 'Ante un accidente se actúa en tres pasos: proteger, avisar y socorrer.',
      q: [['¿Por qué proteger primero?', 'Para que no haya más heridos, incluido quien ayuda.'], ['¿Qué datos se dan al llamar?', 'Qué pasó, dónde y cuántas personas están heridas.'], ['¿Se debe mover a un herido grave?', 'No, salvo peligro inmediato.']],
      porque: 'Un aviso rápido y bien dado es la ayuda más útil que puede dar cualquier persona.' },
    { id: 'ef_lateral', fam: 'seg', n: 'La posición lateral de seguridad',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(10, 104, 180, 10, 2, P.verde, { w: .6 }) + fig(K, 100, 96, { tronco: 90, b: [-150, -100, 0, 40], p: [-60, -20, -90, -90], e: 1.1 }); return s + K.t(100, 22, 'Persona inconsciente que respira', { s: 6.4, b: 1 }) + K.t(100, 32, 'De lado, cabeza hacia atrás, boca hacia el suelo', { s: 5.4 }) + K.t(52, 84, 'mano bajo la mejilla', { s: 5, b: 1 }) + K.t(150, 84, 'rodilla doblada: no rueda', { s: 5, b: 1 }) + K.t(100, 128, 'Así la lengua no tapa la vía aérea y puede salir el vómito', { s: 5.4, b: 1 }) + K.t(100, 138, 'Vigilar la respiración hasta que llegue la ayuda', { s: 5 }); },
      intro: 'La posición lateral de seguridad mantiene abierta la vía aérea de una persona inconsciente que respira.',
      q: [['¿Para qué se dobla la rodilla de arriba?', 'Para que el cuerpo no ruede.'], ['¿Por qué la boca hacia el suelo?', 'Para que un vómito salga y no vaya a los pulmones.'], ['¿Qué hacer si deja de respirar?', 'Avisar a emergencias y empezar la reanimación si se sabe.']],
      porque: 'La lengua de una persona inconsciente boca arriba puede cerrar el paso del aire.' },
    G('ef_seguridad', 'seg', 'Normas de seguridad en la clase', [['Ropa y calzado deportivo', 'cordones atados'], ['Sin joyas ni relojes', 'evitan cortes y golpes'], ['Material en su sitio', 'nada suelto por el suelo'], ['Calentar siempre', 'antes de esfuerzos intensos'], ['Avisar si duele algo', 'parar a tiempo'], ['Agua a mano', 'beber en las pausas']], 2, 22, 28, 'La mayoría de las lesiones se evitan con estas normas', 'Unas pocas normas sencillas previenen casi todas las lesiones en la clase de educación física.', [['¿Por qué quitarse los anillos?', 'Pueden engancharse y cortar el dedo.'], ['¿Qué hacer si duele una rodilla durante el ejercicio?', 'Parar y avisar al docente.'], ['¿Por qué recoger el material?', 'Para que nadie tropiece con conos o pelotas.']], 'Prevenir lleva un minuto; una lesión, semanas.', { s: 7, s2: 5.6 }),
    { id: 'ef_calor', fam: 'seg', n: 'Ejercicio con calor',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.c(32, 30, 12, P.amarillo, { w: .8 }); for (var i = 0; i < 8; i++) { var a = i * Math.PI / 4; s += K.l('M' + (32 + Math.cos(a) * 15).toFixed(1) + ' ' + (30 + Math.sin(a) * 15).toFixed(1) + ' L' + (32 + Math.cos(a) * 20).toFixed(1) + ' ' + (30 + Math.sin(a) * 20).toFixed(1), P.naranja, { w: 1 }); } s += K.r(150, 18, 10, 60, 5, P.blanco, { w: .8 }) + K.c(155, 82, 8, P.rojo, { w: .8 }) + K.r(152, 34, 6, 46, 3, P.rojo, { w: 0 }); return s + K.t(100, 30, 'Golpe de calor: piel caliente,', { s: 5.6, b: 1 }) + K.t(100, 38, 'mareo, dolor de cabeza', { s: 5.6, b: 1 }) + K.t(100, 64, 'Prevenir:', { s: 6, b: 1 }) + K.t(100, 74, 'gorra, agua, sombra', { s: 5.4 }) + K.t(100, 82, 'evitar las horas centrales', { s: 5.4 }) + K.t(100, 110, 'Actuar: sombra, aflojar ropa,', { s: 5.8, b: 1, c: P.rojoO }) + K.t(100, 118, 'enfriar con agua y avisar', { s: 5.8, b: 1, c: P.rojoO }); },
      intro: 'Con calor el cuerpo suda mucho para enfriarse; si no puede, aparece el golpe de calor, que es una emergencia.',
      q: [['¿Qué horas conviene evitar?', 'Las del mediodía, de 12 a 16 h aproximadamente.'], ['¿Qué hacer ante alguien con golpe de calor?', 'Llevarlo a la sombra, enfriarlo con agua y avisar a emergencias.'], ['¿Por qué usar ropa clara?', 'Porque absorbe menos calor del sol.']],
      porque: 'El sudor solo enfría si se evapora: con mucha humedad y sin agua, el cuerpo no se refresca.' },
    { id: 'ef_raqueta', fam: 'dep', n: 'Deportes de raqueta: el golpe de derecha',
      d: function (K) { var s = K.suelo(100, 136, 96) + K.l('M10 120 L190 120', P.blanco, { w: 1 }); [['1 preparar', { tronco: -15, b: [120, 100, -40, -30] }, 40], ['2 golpear', { b: [-80, -80, 40, 30] }, 100], ['3 acompañar', { tronco: 15, b: [-150, -140, 30, 20] }, 160]].forEach(function (q, i) { s += fig(K, q[2], 100, q[1]); var hx = q[2] + [16, -20, -14][i], hy = [78, 76, 64][i]; s += K.e(hx + [10, -8, -2][i], hy - [2, 0, 10][i], 6, 8, P.rojo, { w: .8 }) + K.t(q[2], 132, q[0], { s: 6, b: 1 }); }); s += K.c(84, 80, 2.8, '#D8F060', { w: .6 }); return s + K.t(100, 20, 'Pies de lado, mirar la pelota, golpear delante del cuerpo', { s: 5.4, b: 1 }) + K.t(100, 30, 'Tenis, pádel, bádminton y tenis de mesa', { s: 5 }); },
      intro: 'El golpe de derecha se hace en tres tiempos: preparar la raqueta, golpear delante del cuerpo y acompañar.',
      q: [['¿Dónde debe estar la pelota al golpearla?', 'Delante del cuerpo, a un lado.'], ['¿Por qué acompañar el golpe?', 'Para dar dirección y no frenar el brazo de golpe.'], ['¿Qué deporte de raqueta se juega con volante?', 'El bádminton.']],
      porque: 'Golpear delante del cuerpo deja usar el giro de la cadera, no solo la fuerza del brazo.' },
    { id: 'ef_bici_segura', fam: 'seg', n: 'Montar en bicicleta con seguridad',
      d: function (K) { var s = K.suelo(100, 136, 96) + K.c(60, 108, 18, 'none', { w: 1.8 }) + K.c(140, 108, 18, 'none', { w: 1.8 }) + K.l('M60 108 L86 80 L126 80 L140 108 M86 80 L100 108 L126 80 M100 108 L60 108 M82 72 L92 72 M126 80 L130 70 L138 70', P.azulO, { w: 1.8 }); s += fig(K, 98, 78, { tronco: 30, b: [120, 70, 110, 70], p: [40, -10, 60, 10], e: .9, col: P.naranja }) + K.p('M' + 104 + ' 40 Q' + 114 + ' 30 ' + 124 + ' 40 Z', P.rojo, { w: .8 }) + K.c(146, 80, 2.6, P.blanco, { w: .6 }) + K.c(50, 92, 2.6, P.rojo, { w: .6 }); return s + K.t(116, 26, 'casco bien abrochado', { s: 5.4, b: 1 }) + K.t(162, 72, 'luz blanca', { s: 5, b: 1, a: 'start' }) + K.t(40, 84, 'luz roja', { s: 5, b: 1, a: 'end' }) + K.t(100, 14, 'Revisar frenos y ruedas antes de salir', { s: 5.8, b: 1 }) + K.t(100, 136, 'Circular por la derecha y señalar los giros con el brazo', { s: 5.4, b: 1 }); },
      intro: 'Para ir en bicicleta con seguridad se revisa la bici, se usa casco y se respetan las normas de tráfico.',
      q: [['¿Qué protección es obligatoria en muchos países para menores?', 'El casco.'], ['¿Cómo se indica un giro a la izquierda?', 'Extendiendo el brazo izquierdo.'], ['¿Para qué sirven las luces de día?', 'Para que los conductores te vean antes.']],
      porque: 'Ver y ser visto es la regla principal de la seguridad vial.' }
  ];
  MO.agregar('efisica', L, { nombre: 'Educación física', familias: FAM, materias: /^(efisica)$/ });
})();
