/* b6_lib_musica.js — Música (1/2): lenguaje musical, el sonido, la voz y el cuerpo. 25 modelos.
   Materia `musica`. Prefijo `mu_`. Cargar después de b6_modelos.js.
   No repite los dibujos que el Editorial ya tiene para música (mus_penta, mus_teclado, mus_familias,
   mus_orquesta, ritmo, geo_compas). Primera entrega de 50; se ampliará a 100. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('mu_figuras')) return;
  var P = { papel: '#FBF7EE', azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', grisO: '#8A8478', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', madera: '#B8946A', metal: '#C8CED4', oro: '#E8C04A' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { len: 'Lenguaje musical', son: 'El sonido', voz: 'La voz y el cuerpo', ins: 'Instrumentos', his: 'Historia, formas y estilos', tec: 'Tecnología musical' };
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .55)) : 0; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, y + (q[1] ? h * .44 : h / 2) + f1 * .35, q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, y + h * .82, q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + (o && o.tit ? K.t(100, 14, o.tit, { s: 7, b: 1 }) : '') + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: 6, b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  /* pentagrama: y = línea superior; separación 5 */
  function penta(K, x, y, w) { var s = ''; for (var i = 0; i < 5; i++) s += K.l('M' + x + ' ' + (y + i * 5) + ' L' + (x + w) + ' ' + (y + i * 5), P.tinta, { w: .6 }); return s; }
  function yN(y, n) { return y + 20 - n * 2.5; } /* n = 0: 1.ª línea (mi) en clave de sol */
  function nota(K, x, y, fig, o) {
    o = o || {}; var llena = fig !== 'r' && fig !== 'b', s = K.e(x, y, 3.4, 2.5, llena ? P.tinta : P.blanco, { w: .9, negro: llena });
    if (fig !== 'r') { var ab = o.abajo, sx = ab ? x - 3.2 : x + 3.2, sy = ab ? y + 15 : y - 15; s += K.l('M' + sx + ' ' + y + ' L' + sx + ' ' + sy, P.tinta, { w: .9 }); if (fig === 'c' || fig === 's') s += K.l('M' + sx + ' ' + sy + ' q5 4 4 10', P.tinta, { w: .9 }); if (fig === 's') s += K.l('M' + sx + ' ' + (sy + 4) + ' q5 4 4 10', P.tinta, { w: .9 }); }
    if (o.punto) s += K.c(x + 6, y - 1, .9, P.tinta, { negro: 1, w: .3 });
    if (o.ad) o.ad.forEach(function (ly) { s += K.l('M' + (x - 5.5) + ' ' + ly + ' L' + (x + 5.5) + ' ' + ly, P.tinta, { w: .6 }); });
    return s;
  }
  function claveSol(K, x, y) { return K.l('M' + (x + 5) + ' ' + (y + 27) + ' C' + (x + 1) + ' ' + (y + 28) + ' ' + (x + 1) + ' ' + (y + 23) + ' ' + (x + 4) + ' ' + (y + 23) + ' L' + (x + 6) + ' ' + (y - 6) + ' C' + (x + 10) + ' ' + (y - 2) + ' ' + (x + 10) + ' ' + (y + 4) + ' ' + (x + 2) + ' ' + (y + 11) + ' C' + (x - 3) + ' ' + (y + 17) + ' ' + (x + 2) + ' ' + (y + 23) + ' ' + (x + 8) + ' ' + (y + 19) + ' C' + (x + 12) + ' ' + (y + 15) + ' ' + (x + 7) + ' ' + (y + 9) + ' ' + (x + 4) + ' ' + (y + 13), P.tinta, { w: 1.2 }); }
  function claveFa(K, x, y) { return K.c(x + 2, y + 5, 1.8, P.tinta, { negro: 1, w: .4 }) + K.l('M' + (x + 1) + ' ' + (y + 5) + ' C' + (x + 1) + ' ' + y + ' ' + (x + 11) + ' ' + (y - 1) + ' ' + (x + 11) + ' ' + (y + 6) + ' C' + (x + 11) + ' ' + (y + 12) + ' ' + (x + 6) + ' ' + (y + 17) + ' ' + x + ' ' + (y + 20), P.tinta, { w: 1.2 }) + K.c(x + 14, y + 2.5, .9, P.tinta, { negro: 1, w: .3 }) + K.c(x + 14, y + 7.5, .9, P.tinta, { negro: 1, w: .3 }); }
  function claveDo(K, x, y) { return K.r(x, y, 2.4, 20, 0, P.tinta, { negro: 1, w: .3 }) + K.l('M' + (x + 4) + ' ' + y + ' L' + (x + 4) + ' ' + (y + 20), P.tinta, { w: .9 }) + K.l('M' + (x + 4) + ' ' + (y + 10) + ' L' + (x + 7) + ' ' + (y + 7) + ' C' + (x + 14) + ' ' + (y - 2) + ' ' + (x + 14) + ' ' + (y + 6) + ' ' + (x + 8) + ' ' + (y + 6) + ' M' + (x + 4) + ' ' + (y + 10) + ' L' + (x + 7) + ' ' + (y + 13) + ' C' + (x + 14) + ' ' + (y + 22) + ' ' + (x + 14) + ' ' + (y + 14) + ' ' + (x + 8) + ' ' + (y + 14), P.tinta, { w: 1 }); }
  function barra(K, x, y, dbl) { return K.l('M' + x + ' ' + y + ' L' + x + ' ' + (y + 20), P.tinta, { w: dbl ? .6 : .8 }) + (dbl ? K.r(x + 2, y, 2, 20, 0, P.tinta, { negro: 1, w: .2 }) : ''); }
  function persona(K, x, y, col) { return K.c(x, y, 6, P.piel, { w: .8 }) + K.p('M' + (x - 9) + ' ' + (y + 26) + ' Q' + (x - 9) + ' ' + (y + 8) + ' ' + x + ' ' + (y + 8) + ' Q' + (x + 9) + ' ' + (y + 8) + ' ' + (x + 9) + ' ' + (y + 26) + ' Z', col, { w: .8 }); }
  function onda(K, x, y, w, amp, ciclos, col, gr) { var d = 'M' + x + ' ' + y, n = ciclos * 16; for (var i = 1; i <= n; i++) { var t = i / n; d += ' L' + (x + t * w).toFixed(1) + ' ' + (y - Math.sin(t * ciclos * 2 * Math.PI) * amp).toFixed(1); } return K.l(d, col || P.azulO, { w: gr || 1.4 }); }
  function ejes(K, x, y, w, h, ex, ey) { return K.flecha(x, y + h, x + w, y + h, P.tinta, { w: 1 }) + K.flecha(x, y + h, x, y, P.tinta, { w: 1 }) + K.t(x + w, y + h + 9, ex, { s: 5.4, a: 'end' }) + K.t(x + 4, y + 3, ey, { s: 5.4, a: 'start' }); }

  var L = [
    /* ─────────── LENGUAJE MUSICAL ─────────── */
    { id: 'mu_figuras', fam: 'len', n: 'Las figuras y su duración',
      d: function (K) { var F = [['r', 'redonda', '4'], ['b', 'blanca', '2'], ['n', 'negra', '1'], ['c', 'corchea', '½'], ['s', 'semicorchea', '¼']], s = K.suelo(100, 140, 96); F.forEach(function (q, i) { var x = 26 + i * 37; s += K.r(x - 16, 22, 32, 62, 3, CO[i], { w: .7 }) + nota(K, x - 2, 60, q[0]) + K.t(x, 96, q[1], { s: 5.8, b: 1 }) + K.t(x, 108, q[2] + (q[2] === '1' ? ' tiempo' : ' tiempos'), { s: 5.6 }); }); return s + K.t(100, 128, 'Cada figura dura la mitad que la anterior', { s: 6.4, b: 1 }); },
      intro: 'Las figuras indican cuánto dura un sonido; tomando la negra como un tiempo, cada figura vale la mitad de la anterior.',
      q: [['¿Cuántas negras caben en una redonda?', 'Cuatro.'], ['¿Cuántas corcheas suman una blanca?', 'Cuatro: cada corchea dura medio tiempo.'], ['¿Qué tiene la corchea que no tiene la negra?', 'Un corchete en la plica.']],
      porque: 'Como cada figura es la mitad de la anterior, los ritmos se pueden sumar como fracciones.' },
    { id: 'mu_silencios', fam: 'len', n: 'Los silencios',
      d: function (K) { var s = K.suelo(100, 140, 96) + penta(K, 14, 36, 172), y = 36; s += K.r(30, y + 5, 10, 2.6, 0, P.tinta, { negro: 1, w: .3 }) + K.r(64, y + 7.4, 10, 2.6, 0, P.tinta, { negro: 1, w: .3 }) + K.l('M98 ' + (y + 3) + ' l4 5 -4 4 4 5 q-6 -2 -2 5', P.tinta, { w: 1.4 }) + K.l('M134 ' + (y + 16) + ' L139 ' + (y + 5), P.tinta, { w: 1 }) + K.c(135, y + 7, 1.6, P.tinta, { negro: 1, w: .3 }) + K.l('M164 ' + (y + 18) + ' L171 ' + (y + 3), P.tinta, { w: 1 }) + K.c(166, y + 5, 1.6, P.tinta, { negro: 1, w: .3 }) + K.c(164, y + 10, 1.6, P.tinta, { negro: 1, w: .3 }); [['de redonda', '4', 35], ['de blanca', '2', 69], ['de negra', '1', 101], ['de corchea', '½', 136], ['de semicor.', '¼', 167]].forEach(function (q) { s += K.t(q[2], 74, 'silencio', { s: 4.6 }) + K.t(q[2], 81, q[0], { s: 4.6, b: 1 }) + K.t(q[2], 91, q[1], { s: 6.4, b: 1 }); }); return s + K.t(100, 108, 'Colgado de la 4.ª línea: redonda · sentado en la 3.ª: blanca', { s: 5.6 }) + K.t(100, 124, 'Un silencio dura lo mismo que su figura', { s: 6.4, b: 1 }); },
      intro: 'Cada figura tiene un silencio que dura lo mismo; en ese tiempo no se toca, pero se sigue contando.',
      q: [['¿Cómo se distingue el silencio de redonda del de blanca?', 'El de redonda cuelga de la 4.ª línea; el de blanca se apoya en la 3.ª.'], ['¿Cuánto dura el silencio de negra?', 'Un tiempo.'], ['¿Por qué se cuentan los silencios?', 'Para volver a entrar justo a tiempo con el resto del grupo.']],
      porque: 'El silencio también es música: sin él no habría ritmo ni respiración.' },
    { id: 'mu_claves', fam: 'len', n: 'Las tres claves',
      d: function (K) { var s = K.suelo(100, 140, 96); [[12, 'clave de sol', '2.ª línea = sol', claveSol], [72, 'clave de fa', '4.ª línea = fa', claveFa], [132, 'clave de do', '3.ª línea = do', claveDo]].forEach(function (q, i) { var y = 40; s += penta(K, q[0], y, 56) + q[3](K, q[0] + 4, i === 1 ? y : y) + K.t(q[0] + 28, 84, q[1], { s: 6.4, b: 1 }) + K.t(q[0] + 28, 94, q[2], { s: 5.4 }); }); s += K.c(36, yN(40, 2), 2.6, P.rojo, { w: .6 }) + K.c(96, 45, 2.6, P.rojo, { w: .6 }) + K.c(158, 50, 2.6, P.rojo, { w: .6 }); return s + K.t(100, 114, 'La clave dice qué nota corresponde a cada línea', { s: 6.2, b: 1 }) + K.t(100, 126, 'Sol: violín, flauta, voz aguda · Fa: contrabajo, tuba, voz grave', { s: 5.2 }); },
      intro: 'La clave, al comienzo del pentagrama, fija el nombre de una línea y con ella el de todas las demás.',
      q: [['¿En qué línea está el sol en clave de sol?', 'En la 2.ª línea.'], ['¿Qué instrumentos leen en clave de fa?', 'Los graves: contrabajo, violonchelo, fagot, tuba y la mano izquierda del piano.'], ['¿Qué instrumento usa la clave de do en 3.ª?', 'La viola.']],
      porque: 'Cada clave centra el pentagrama en el registro del instrumento, para no llenar la partitura de líneas adicionales.' },
    { id: 'mu_adicionales', fam: 'len', n: 'Líneas adicionales: el do central',
      d: function (K) { var y = 30, s = K.suelo(100, 140, 96) + penta(K, 14, y, 172) + claveSol(K, 18, y), N = [[-2, 'do', [yN(y, -2)]], [-1, 're', []], [9, 'sol', []], [10, 'la', [yN(y, 10)]], [11, 'si', [yN(y, 10)]], [12, 'do', [yN(y, 10), yN(y, 12)]]]; N.forEach(function (q, i) { var x = 46 + i * 24; s += nota(K, x, yN(y, q[0]), 'n', { ad: q[2], abajo: q[0] > 4 }) + K.t(x, 92, q[1], { s: 6, b: 1 }); }); return s + K.r(34, 98, 46, 14, 3, P.amarillo, { w: .7 }) + K.t(57, 107, 'do central', { s: 5.8, b: 1 }) + K.t(100, 124, 'Las notas que no caben en el pentagrama usan líneas cortas', { s: 5.8, b: 1 }) + K.t(100, 134, 'encima o debajo, una por cada dos notas', { s: 5.4 }); },
      intro: 'Las líneas adicionales amplían el pentagrama hacia arriba o hacia abajo para escribir notas más agudas o más graves.',
      q: [['¿Dónde se escribe el do central en clave de sol?', 'En la primera línea adicional por debajo.'], ['¿Qué nota hay justo debajo de la 1.ª línea?', 'Re, en el espacio.'], ['¿Por qué se llama «central»?', 'Porque está cerca del centro del teclado y une las claves de sol y de fa.']],
      porque: 'Con líneas adicionales, un mismo pentagrama sirve para notas que se salen de sus cinco líneas.' },
    { id: 'mu_alteraciones', fam: 'len', n: 'Sostenido, bemol y becuadro',
      d: function (K) { var s = K.suelo(100, 140, 96), y = 30; s += penta(K, 14, y, 172); var sos = function (x, yy) { return K.l('M' + (x - 1.5) + ' ' + (yy - 6) + ' L' + (x - 1.5) + ' ' + (yy + 6) + ' M' + (x + 1.5) + ' ' + (yy - 6.5) + ' L' + (x + 1.5) + ' ' + (yy + 5.5) + ' M' + (x - 3.5) + ' ' + (yy - 1) + ' L' + (x + 3.5) + ' ' + (yy - 2.5) + ' M' + (x - 3.5) + ' ' + (yy + 2.5) + ' L' + (x + 3.5) + ' ' + (yy + 1), P.tinta, { w: .8 }); }, bem = function (x, yy) { return K.l('M' + (x - 2) + ' ' + (yy - 9) + ' L' + (x - 2) + ' ' + (yy + 3) + ' C' + (x + 4) + ' ' + yy + ' ' + (x + 3) + ' ' + (yy - 4) + ' ' + (x - 2) + ' ' + (yy - 1), P.tinta, { w: .9 }); }, bec = function (x, yy) { return K.l('M' + (x - 2) + ' ' + (yy - 7) + ' L' + (x - 2) + ' ' + (yy + 2.5) + ' L' + (x + 2) + ' ' + (yy + 1.5) + ' M' + (x + 2) + ' ' + (yy + 7) + ' L' + (x + 2) + ' ' + (yy - 2.5) + ' L' + (x - 2) + ' ' + (yy - 1.5), P.tinta, { w: .8 }); }; var yf = yN(y, 1); s += sos(36, yf) + nota(K, 46, yf, 'n') + bem(90, yN(y, 4)) + nota(K, 100, yN(y, 4), 'n', { abajo: 0 }) + bec(144, yf) + nota(K, 154, yf, 'n'); return s + K.t(42, 74, 'sostenido ♯', { s: 6, b: 1 }) + K.t(42, 84, 'sube medio tono', { s: 5.2 }) + K.t(42, 92, 'fa → fa♯', { s: 5.2 }) + K.t(96, 74, 'bemol ♭', { s: 6, b: 1 }) + K.t(96, 84, 'baja medio tono', { s: 5.2 }) + K.t(96, 92, 'si → si♭', { s: 5.2 }) + K.t(150, 74, 'becuadro ♮', { s: 6, b: 1 }) + K.t(150, 84, 'anula la alteración', { s: 5.2 }) + K.t(150, 92, 'fa♯ → fa', { s: 5.2 }) + K.t(100, 116, 'La alteración vale hasta el final del compás', { s: 6.2, b: 1 }) + K.t(100, 128, 'En el piano, fa♯ es la tecla negra a la derecha de fa', { s: 5.4 }); },
      intro: 'Las alteraciones suben o bajan una nota medio tono, o le devuelven su sonido natural.',
      q: [['¿Qué hace el sostenido?', 'Sube la nota medio tono.'], ['¿Cuánto dura el efecto de una alteración escrita junto a la nota?', 'Hasta el final del compás.'], ['¿Qué otra nota suena igual que do♯ en el piano?', 're♭: es la misma tecla negra.']],
      porque: 'Entre las siete notas naturales hay cinco sonidos más: las alteraciones les dan nombre.' },
    { id: 'mu_puntillo', fam: 'len', n: 'El puntillo y la ligadura',
      d: function (K) { var y = 30, s = K.suelo(100, 140, 96) + penta(K, 14, y, 172); s += nota(K, 34, yN(y, 3), 'b', { punto: 1 }) + K.t(56, yN(y, 3) + 2, '=', { s: 9, b: 1 }) + nota(K, 70, yN(y, 3), 'b') + K.t(80, yN(y, 3) + 2, '+', { s: 8, b: 1 }) + nota(K, 90, yN(y, 3), 'n') + barra(K, 104, y) + nota(K, 124, yN(y, 3), 'n') + nota(K, 156, yN(y, 3), 'n') + K.l('M124 ' + (yN(y, 3) + 4) + ' Q140 ' + (yN(y, 3) + 12) + ' 156 ' + (yN(y, 3) + 4), P.tinta, { w: 1 }); return s + K.t(62, 70, 'Puntillo', { s: 6.6, b: 1 }) + K.t(62, 80, 'suma la mitad de su valor', { s: 5.4 }) + K.t(62, 90, 'blanca con puntillo = 3 tiempos', { s: 5.4, b: 1 }) + K.t(146, 70, 'Ligadura', { s: 6.6, b: 1 }) + K.t(146, 80, 'une dos notas iguales', { s: 5.4 }) + K.t(146, 90, '1 + 1 = 2 tiempos, un solo golpe', { s: 5.4, b: 1 }) + K.t(100, 116, 'Negra con puntillo = 1 + ½ = 1 ½ tiempos', { s: 6.2, b: 1 }) + K.t(100, 128, 'La ligadura permite que un sonido cruce la barra de compás', { s: 5.4 }); },
      intro: 'El puntillo alarga una figura la mitad de su valor; la ligadura une dos notas de la misma altura en un solo sonido.',
      q: [['¿Cuánto dura una negra con puntillo?', 'Un tiempo y medio.'], ['¿Cuánto dura una redonda con puntillo?', '4 + 2 = 6 tiempos.'], ['¿Se toca dos veces la nota ligada?', 'No: se toca una vez y se mantiene la suma de las dos.']],
      porque: 'Con puntillos y ligaduras se escriben duraciones que ninguna figura sola puede expresar.' },
    { id: 'mu_escala', fam: 'len', n: 'La escala de do mayor',
      d: function (K) { var y = 26, s = K.suelo(100, 140, 96) + penta(K, 14, y, 172) + claveSol(K, 18, y), nom = ['do', 're', 'mi', 'fa', 'sol', 'la', 'si', 'do'], tt = ['T', 'T', 'S', 'T', 'T', 'T', 'S']; for (var i = 0; i < 8; i++) { var x = 44 + i * 19, n = i - 2; s += nota(K, x, yN(y, n), 'n', { ad: i === 0 ? [yN(y, -2)] : [], abajo: n > 4 }) + K.t(x, 70, nom[i], { s: 6, b: 1 }); if (i < 7) s += K.r(x + 3, 78, 13, 12, 3, tt[i] === 'T' ? P.azul : P.rosa, { w: .6 }) + K.t(x + 9.5, 86.5, tt[i], { s: 6, b: 1 }); } return s + K.t(100, 106, 'T = tono · S = semitono', { s: 6.4, b: 1 }) + K.t(100, 118, 'Patrón de la escala mayor: T T S T T T S', { s: 6, b: 1 }) + K.t(100, 130, 'Los semitonos caen entre mi-fa y si-do', { s: 5.6 }); },
      intro: 'La escala mayor sube por tonos y semitonos siguiendo siempre el mismo patrón.',
      q: [['¿Entre qué notas hay semitono en la escala de do?', 'Entre mi y fa, y entre si y do.'], ['¿Cuántos tonos hay en total?', '5 tonos y 2 semitonos, es decir, 6 tonos.'], ['Para empezar la escala mayor en sol, ¿qué nota hay que alterar?', 'Fa, que pasa a fa♯.']],
      porque: 'Con el mismo patrón T T S T T T S se forma la escala mayor desde cualquier nota.' },
    { id: 'mu_armadura', fam: 'len', n: 'La armadura',
      d: function (K) { var y = 32, s = K.suelo(100, 140, 96); s += penta(K, 12, y, 84) + claveSol(K, 16, y) + penta(K, 104, y, 84) + claveSol(K, 108, y); var sx = 34, sy = yN(y, 8); s += K.l('M' + (sx - 1.5) + ' ' + (sy - 6) + ' L' + (sx - 1.5) + ' ' + (sy + 6) + ' M' + (sx + 1.5) + ' ' + (sy - 6.5) + ' L' + (sx + 1.5) + ' ' + (sy + 5.5) + ' M' + (sx - 3.5) + ' ' + (sy - 1) + ' L' + (sx + 3.5) + ' ' + (sy - 2.5) + ' M' + (sx - 3.5) + ' ' + (sy + 2.5) + ' L' + (sx + 3.5) + ' ' + (sy + 1), P.tinta, { w: .8 }); var bx = 126, by = yN(y, 4); s += K.l('M' + (bx - 2) + ' ' + (by - 9) + ' L' + (bx - 2) + ' ' + (by + 3) + ' C' + (bx + 4) + ' ' + by + ' ' + (bx + 3) + ' ' + (by - 4) + ' ' + (bx - 2) + ' ' + (by - 1), P.tinta, { w: .9 }); s += K.l('M42 ' + y + ' L42 ' + (y + 20) + ' M134 ' + y + ' L134 ' + (y + 20), P.grisO, { w: .4 }); return s + K.t(54, 72, 'Sol mayor', { s: 6.6, b: 1 }) + K.t(54, 82, '1 sostenido: fa♯', { s: 5.6 }) + K.t(146, 72, 'Fa mayor', { s: 6.6, b: 1 }) + K.t(146, 82, '1 bemol: si♭', { s: 5.6 }) + K.t(100, 104, 'Las alteraciones de la armadura valen para toda la pieza', { s: 5.8, b: 1 }) + K.t(100, 114, 'y en todas las octavas', { s: 5.6 }) + K.t(100, 130, 'Orden de los sostenidos: fa, do, sol, re, la, mi, si', { s: 5.4 }); },
      intro: 'La armadura agrupa al principio del pentagrama las alteraciones fijas de una tonalidad.',
      q: [['¿Qué tonalidad mayor no lleva alteraciones?', 'Do mayor.'], ['Una pieza en sol mayor tiene un fa en el compás 10. ¿Cómo se toca?', 'Como fa♯, por la armadura.'], ['¿Cuál es el orden de los bemoles?', 'Si, mi, la, re, sol, do, fa: el de los sostenidos al revés.']],
      porque: 'Escribir la alteración una sola vez al principio evita repetirla en cada nota.' },
    { id: 'mu_intervalos', fam: 'len', n: 'Los intervalos',
      d: function (K) { var y = 24, s = K.suelo(100, 140, 96) + penta(K, 10, y, 180), nom = ['2.ª', '3.ª', '4.ª', '5.ª', '6.ª', '7.ª', '8.ª']; for (var i = 0; i < 7; i++) { var x = 26 + i * 25; s += nota(K, x, yN(y, -2), 'r', { ad: [yN(y, -2)] }) + nota(K, x, yN(y, -1 + i), 'r') + K.t(x, 66, nom[i], { s: 6.4, b: 1 }) + K.t(x, 76, 'do-' + ['re', 'mi', 'fa', 'sol', 'la', 'si', 'do'][i], { s: 4.8 }); } return s + K.t(100, 98, 'Se cuentan las dos notas y todas las de en medio', { s: 6, b: 1 }) + K.t(100, 110, 'do-mi: do, re, mi = 3 notas → tercera', { s: 5.6 }) + K.t(100, 128, 'La 8.ª (octava) repite el nombre de la nota', { s: 5.8 }); },
      intro: 'Un intervalo es la distancia entre dos notas, contada por el número de notas que abarca.',
      q: [['¿Qué intervalo hay de re a la?', 'Una quinta: re, mi, fa, sol, la.'], ['¿Qué intervalo hay entre do y el do siguiente?', 'Una octava.'], ['¿Por qué do-re es segunda y no primera?', 'Porque se cuentan las dos notas: do y re.']],
      porque: 'Reconocer intervalos permite cantar o tocar una melodía en cualquier altura.' },
    { id: 'mu_acorde', fam: 'len', n: 'El acorde',
      d: function (K) { var y = 26, s = K.suelo(100, 140, 96) + penta(K, 14, y, 172) + claveSol(K, 18, y); [[48, -2, 0, 2, 'do mayor', 'do-mi-sol'], [92, 1, 3, 5, 'fa mayor', 'fa-la-do'], [136, 2, 4, 6, 'sol mayor', 'sol-si-re']].forEach(function (q) { s += nota(K, q[0], yN(y, q[1]), 'r', { ad: q[1] < 0 ? [yN(y, -2)] : [] }) + nota(K, q[0], yN(y, q[2]), 'r') + nota(K, q[0], yN(y, q[3]), 'r') + K.t(q[0], 68, q[4], { s: 6.2, b: 1 }) + K.t(q[0], 78, q[5], { s: 5.4 }); }); return s + K.t(100, 100, 'Tres notas a distancia de tercera, a la vez', { s: 6.4, b: 1 }) + K.t(100, 112, 'Con estos tres acordes se acompañan muchas canciones', { s: 5.6 }) + K.t(100, 128, 'Do: grado I · Fa: grado IV · Sol: grado V', { s: 5.8, b: 1 }); },
      intro: 'Un acorde son tres o más notas que suenan a la vez; el más básico se forma apilando terceras.',
      q: [['¿Qué notas forman el acorde de sol mayor?', 'Sol, si y re.'], ['¿Qué diferencia hay entre acorde y melodía?', 'En el acorde las notas suenan juntas; en la melodía, una tras otra.'], ['¿Qué tres acordes acompañan muchas canciones en do?', 'Do (I), fa (IV) y sol (V).']],
      porque: 'Los acordes I, IV y V contienen todas las notas de la escala, por eso acompañan casi cualquier melodía sencilla.' },
    G('mu_dinamica', 'len', 'La dinámica: del suave al fuerte', [['pp', 'pianissimo · muy suave'], ['p', 'piano · suave'], ['mp', 'mezzo piano · medio suave'], ['mf', 'mezzo forte · medio fuerte'], ['f', 'forte · fuerte'], ['ff', 'fortissimo · muy fuerte']], 3, 18, 34, 'Crescendo < aumenta poco a poco · Decrescendo > disminuye', 'Los signos de dinámica indican con qué intensidad se toca cada pasaje.', [['¿Qué significa mf?', 'Mezzo forte: medio fuerte.'], ['¿Qué indica el signo <?', 'Un crescendo: subir la intensidad poco a poco.'], ['¿De qué idioma vienen estas palabras?', 'Del italiano.']], 'Tocar siempre igual de fuerte aburre: la dinámica da expresión a la música.', { s: 9, s2: 5.4 }),
    G('mu_tempo', 'len', 'El tempo: la velocidad del pulso', [['Largo', '40–60 pulsos por minuto'], ['Adagio', '66–76 · lento'], ['Andante', '76–108 · al paso'], ['Moderato', '108–120 · moderado'], ['Allegro', '120–168 · rápido'], ['Presto', '168–200 · muy rápido']], 2, 18, 26, 'El metrónomo marca los pulsos por minuto (ppm)', 'El tempo indica a qué velocidad va el pulso de la música; se mide en pulsos por minuto.', [['¿Qué tempo se parece al de caminar?', 'Andante.'], ['¿Cuántos pulsos hay en 30 segundos a 120 ppm?', '60.'], ['¿Qué significa accelerando?', 'Ir acelerando poco a poco.']], 'El mismo ritmo cambia de carácter según el tempo: una nana lenta, una marcha más rápida.', { s: 7.4, s2: 5.4 }),
    { id: 'mu_repeticion', fam: 'len', n: 'Signos de repetición',
      d: function (K) { var y = 24, s = K.suelo(100, 140, 96) + penta(K, 14, y, 172); s += K.r(40, y, 2, 20, 0, P.tinta, { negro: 1, w: .2 }) + K.l('M44 ' + y + ' L44 ' + (y + 20), P.tinta, { w: .6 }) + K.c(47, y + 7.5, .9, P.tinta, { negro: 1, w: .3 }) + K.c(47, y + 12.5, .9, P.tinta, { negro: 1, w: .3 }); for (var i = 0; i < 4; i++) s += nota(K, 58 + i * 10, yN(y, 2 + i), 'n'); s += K.l('M100 ' + y + ' L100 ' + (y + 20), P.tinta, { w: .6 }) + K.r(102, y, 2, 20, 0, P.tinta, { negro: 1, w: .2 }) + K.c(97, y + 7.5, .9, P.tinta, { negro: 1, w: .3 }) + K.c(97, y + 12.5, .9, P.tinta, { negro: 1, w: .3 }); s += K.l('M116 ' + (y - 6) + ' L116 ' + (y - 12) + ' L150 ' + (y - 12), P.tinta, { w: .6 }) + K.t(120, y - 7, '1.', { s: 5, b: 1, a: 'start' }) + K.l('M152 ' + (y - 6) + ' L152 ' + (y - 12) + ' L184 ' + (y - 12), P.tinta, { w: .6 }) + K.t(156, y - 7, '2.', { s: 5, b: 1, a: 'start' }); return s + K.t(72, 62, 'se repite lo que está entre :|| ||:', { s: 5.4, b: 1 }) + K.t(150, 62, 'casillas 1.ª y 2.ª', { s: 5.4, b: 1 }) + K.r(14, 76, 54, 34, 3, P.amarillo, { w: .7 }) + K.t(41, 89, 'D.C.', { s: 7, b: 1 }) + K.t(41, 99, 'da capo: desde el principio', { s: 4.6 }) + K.r(73, 76, 54, 34, 3, P.verde, { w: .7 }) + K.t(100, 89, 'D.S.', { s: 7, b: 1 }) + K.t(100, 99, 'dal segno: desde el signo', { s: 4.6 }) + K.r(132, 76, 54, 34, 3, P.rosa, { w: .7 }) + K.t(159, 89, 'Fine', { s: 7, b: 1 }) + K.t(159, 99, 'aquí termina la pieza', { s: 4.6 }) + K.t(100, 128, 'Sirven para no escribir dos veces lo mismo', { s: 6, b: 1 }); },
      intro: 'Los signos de repetición indican qué fragmento se vuelve a tocar y por dónde se sigue.',
      q: [['¿Qué se toca la segunda vez cuando hay casillas?', 'Se salta la 1.ª casilla y se toca la 2.ª.'], ['¿Qué significa D.C. al Fine?', 'Volver al principio y terminar donde dice Fine.'], ['¿Por qué se usan estos signos?', 'Para ahorrar páginas y que la estructura se vea de un golpe.']],
      porque: 'Muchas canciones repiten estrofas y estribillos: los signos muestran esa forma en la partitura.' },
    /* ─────────── EL SONIDO ─────────── */
    G('mu_cualidades', 'son', 'Las cualidades del sonido', [['Altura', 'agudo o grave · frecuencia'], ['Duración', 'largo o corto · tiempo'], ['Intensidad', 'fuerte o suave · amplitud'], ['Timbre', 'quién suena · forma de la onda']], 2, 24, 40, 'Con el timbre se reconoce una voz sin verla', 'Todo sonido se describe con cuatro cualidades: altura, duración, intensidad y timbre.', [['¿Qué cualidad distingue una flauta de un violín tocando la misma nota?', 'El timbre.'], ['¿Qué cualidad cambia al subir el volumen?', 'La intensidad.'], ['¿Qué indica la figura musical?', 'La duración.']], 'La partitura escribe tres de las cuatro cualidades; el timbre lo pone el instrumento.', { s: 9, s2: 5.8 }),
    { id: 'mu_altura', fam: 'son', n: 'Agudo y grave: la frecuencia',
      d: function (K) { var s = K.suelo(100, 140, 96) + onda(K, 20, 40, 160, 12, 2, P.azulO) + onda(K, 20, 92, 160, 12, 8, P.rojoO); return s + K.t(20, 22, 'Grave: pocas vibraciones por segundo', { s: 5.8, b: 1, a: 'start', c: P.azulO }) + K.t(20, 74, 'Agudo: muchas vibraciones por segundo', { s: 5.8, b: 1, a: 'start', c: P.rojoO }) + K.t(100, 120, 'La4 (diapasón) = 440 Hz · La5 = 880 Hz · La3 = 220 Hz', { s: 5.6, b: 1 }) + K.t(100, 132, 'Una octava más aguda = el doble de frecuencia', { s: 6, b: 1 }); },
      intro: 'La altura depende de la frecuencia: cuántas veces vibra el aire por segundo, medida en hercios (Hz).',
      q: [['¿Qué frecuencia tiene el la una octava por debajo de 440 Hz?', '220 Hz.'], ['¿Qué suena más agudo, 300 Hz o 1 000 Hz?', '1 000 Hz.'], ['¿Qué rango de frecuencias oye una persona joven?', 'Aproximadamente de 20 Hz a 20 000 Hz.']],
      porque: 'Duplicar la frecuencia da la misma nota más aguda: por eso las notas se repiten cada octava.' },
    { id: 'mu_intensidad', fam: 'son', n: 'Intensidad: los decibelios',
      d: function (K) { var D = [[30, 'susurro', P.verde], [60, 'conversación', P.verde], [80, 'tráfico', P.amarillo], [95, 'moto', P.naranja], [110, 'concierto', P.rojo], [130, 'avión', P.rojo]], s = K.suelo(100, 140, 96) + K.l('M20 116 L186 116', P.tinta, { w: .9 }); D.forEach(function (q, i) { var x = 26 + i * 27, h = q[0] * .72; s += K.caja(x, 116 - h, 18, h, 4, q[2], { w: .7 }) + K.t(x + 9, 116 - h - 3, q[0] + ' dB', { s: 5, b: 1 }) + K.t(x + 9, 125, q[1], { s: Math.min(5, 26 / (q[1].length * .55)) }); }); return s + K.l('M20 ' + (116 - 85 * .72) + ' L186 ' + (116 - 85 * .72), P.rojoO, { w: .8 }) + K.t(22, 116 - 85 * .72 - 3, '85 dB: riesgo si dura horas', { s: 5, b: 1, a: 'start', c: P.rojoO }) + K.t(100, 140, 'Cada 10 dB más, el oído percibe el doble de fuerte', { s: 5.4, b: 1 }); },
      intro: 'La intensidad del sonido se mide en decibelios (dB); a partir de unos 85 dB mantenidos, el oído puede dañarse.',
      q: [['¿Qué es más fuerte, el tráfico o una conversación?', 'El tráfico: 80 dB frente a 60 dB.'], ['¿Por qué se usan protectores en los conciertos?', 'Porque 110 dB durante horas pueden dañar el oído para siempre.'], ['¿Cómo cuidar el oído con auriculares?', 'Bajar el volumen y descansar cada cierto tiempo.']],
      porque: 'El daño por ruido no duele y no se cura: se previene bajando el volumen y el tiempo de exposición.' },
    { id: 'mu_timbre', fam: 'son', n: 'El timbre: la forma de la onda',
      d: function (K) { var s = K.suelo(100, 140, 96), d1 = 'M20 34', d2 = 'M20 72', d3 = 'M20 110'; for (var i = 0; i <= 96; i++) { var t = i / 96, x = (20 + t * 160).toFixed(1), a = t * 3 * 2 * Math.PI; d1 += ' L' + x + ' ' + (34 - Math.sin(a) * 10).toFixed(1); d2 += ' L' + x + ' ' + (72 - (Math.sin(a) * 7 + Math.sin(2 * a) * 4 + Math.sin(3 * a) * 2)).toFixed(1); d3 += ' L' + x + ' ' + (110 - (((a / (2 * Math.PI)) % 1) * 20 - 10)).toFixed(1); } s += K.l(d1, P.azulO, { w: 1.3 }) + K.l(d2, P.verdeO, { w: 1.3 }) + K.l(d3, P.rojoO, { w: 1.3 }); return s + K.t(186, 20, 'diapasón: onda pura', { s: 5.6, b: 1, a: 'end', c: P.azulO }) + K.t(186, 56, 'flauta: pocos armónicos', { s: 5.6, b: 1, a: 'end', c: P.verdeO }) + K.t(186, 94, 'violín: muchos armónicos', { s: 5.6, b: 1, a: 'end', c: P.rojoO }) + K.t(100, 134, 'Misma nota, misma frecuencia · distinta forma = distinto timbre', { s: 5.4, b: 1 }); },
      intro: 'Dos instrumentos que tocan la misma nota producen ondas de igual frecuencia pero de forma distinta: eso es el timbre.',
      q: [['¿Qué tienen igual las tres ondas?', 'La frecuencia: repiten su forma el mismo número de veces.'], ['¿Qué son los armónicos?', 'Sonidos más agudos que acompañan a la nota principal.'], ['¿Por qué se reconoce la voz de un amigo por teléfono?', 'Por su timbre.']],
      porque: 'Cada instrumento mezcla sus armónicos de una forma propia, como una huella digital del sonido.' },
    { id: 'mu_cuerda', fam: 'son', n: 'Cuerda más corta, nota más aguda',
      d: function (K) { var s = K.suelo(100, 140, 96); [[20, 180, 'cuerda entera: do', 30], [20, 100, 'la mitad: do una octava más aguda', 62], [20, 126.7, 'pisada a dos tercios: sol (quinta)', 94]].forEach(function (q, i) { var y = q[3]; s += K.r(14, y - 4, 6, 8, 1, P.madera, { w: .6 }) + K.r(180, y - 4, 6, 8, 1, P.madera, { w: .6 }) + K.l('M20 ' + y + ' L180 ' + y, P.grisO, { w: .5 }) + K.l('M20 ' + y + ' Q' + ((q[0] + q[1]) / 2) + ' ' + (y - 8) + ' ' + q[1] + ' ' + y + ' Q' + ((q[0] + q[1]) / 2) + ' ' + (y + 8) + ' 20 ' + y, i === 0 ? P.azulO : i === 1 ? P.rojoO : P.verdeO, { w: 1.2 }) + (i ? K.p('M' + q[1] + ' ' + (y - 6) + ' l-3 6 l6 0 z', P.tinta, { w: .4 }) : '') + K.t(100, y + 17, q[2], { s: 5.4, b: 1 }); }); return s + K.t(100, 136, 'Así funcionan los trastes de la guitarra', { s: 6, b: 1 }); },
      intro: 'Al acortar la cuerda que vibra, la frecuencia aumenta y la nota suena más aguda.',
      q: [['¿Qué nota suena al pisar la cuerda justo en su mitad?', 'La misma nota, una octava más aguda.'], ['¿Qué más hace sonar agudo a una cuerda?', 'Tensarla más o que sea más fina.'], ['¿Por qué las cuerdas graves del piano son más largas y gruesas?', 'Porque vibran más despacio y dan frecuencias bajas.']],
      porque: 'Pitágoras ya observó que las longitudes 1, ½ y ⅔ suenan bien juntas: son la octava y la quinta.' },
    { id: 'mu_eco', fam: 'son', n: 'La velocidad del sonido y el eco',
      d: function (K) { var s = K.suelo(100, 140, 96) + persona(K, 26, 60, P.azul) + K.r(176, 20, 14, 100, 1, P.gris, { w: .9 }); for (var i = 0; i < 6; i++) s += K.l('M' + (172 - i * 2) + ' 30 L' + (172 - i * 2) + ' 112', P.grisO, { w: .2 }); for (var j = 1; j <= 4; j++) s += K.l('M' + (40 + j * 26) + ' ' + (58 - j * 4) + ' Q' + (46 + j * 26) + ' 70 ' + (40 + j * 26) + ' ' + (82 + j * 4), P.azulO, { w: 1 }); return s + K.flecha(40, 98, 172, 98, P.azulO, { w: 1.2 }) + K.flecha(172, 108, 40, 108, P.rojoO, { w: 1.2 }) + K.t(106, 94, 'ida', { s: 5.4, c: P.azulO }) + K.t(106, 118, 'vuelta', { s: 5.4, c: P.rojoO }) + K.t(106, 22, 'En el aire el sonido viaja a unos 343 m/s', { s: 6, b: 1 }) + K.t(106, 32, 'Pared a 170 m: el eco vuelve en 1 s', { s: 5.6 }) + K.t(100, 136, 'Distancia = velocidad × tiempo ÷ 2', { s: 6.2, b: 1 }); },
      intro: 'El eco es el sonido que rebota en una superficie lejana y vuelve al oído con un retraso.',
      q: [['Gritas y el eco tarda 2 s. ¿A qué distancia está la pared?', '343 × 2 ÷ 2 ≈ 343 m.'], ['¿Por qué se divide entre 2?', 'Porque el sonido va y vuelve.'], ['¿Por qué las salas de concierto tienen paredes con relieve?', 'Para repartir los rebotes y evitar ecos molestos.']],
      porque: 'El oído separa dos sonidos si llegan con más de una décima de segundo: por eso en una habitación pequeña no hay eco.' },
    { id: 'mu_oido', fam: 'son', n: 'El viaje del sonido por el oído',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.p('M20 40 C10 50 10 90 24 104 C30 96 30 84 26 78 C34 74 36 62 30 52 Z', P.piel, { w: 1 }) + K.r(30, 62, 46, 10, 4, P.rosa, { w: .8 }) + K.e(78, 67, 2.2, 10, P.gris, { w: .8 }) + K.l('M80 64 L90 60 L98 66 L106 62', P.oro, { w: 2.4 }) + K.c(98, 66, 2.4, P.oro, { w: .6 }) + K.l('M110 66 C118 56 132 56 132 66 C132 76 118 76 120 66 C122 60 128 62 126 66', P.naranja, { w: 3 }) + K.l('M132 66 L166 54', P.amarillo, { w: 2 }) + K.r(166, 46, 22, 14, 4, P.morado, { w: .8 }); for (var j = 0; j < 3; j++) s += K.l('M' + (2 + j * 4) + ' 58 q4 9 0 18', P.azulO, { w: .9 }); var E = [[58, 86, '1 pabellón y conducto'], [78, 48, '2 tímpano'], [98, 82, '3 huesecillos'], [124, 48, '4 cóclea'], [170, 76, '5 nervio → cerebro']]; E.forEach(function (q) { s += K.t(q[0], q[1], q[2], { s: 5.2, b: 1 }); }); return s + K.t(100, 112, 'El tímpano vibra, los huesecillos amplifican', { s: 6, b: 1 }) + K.t(100, 124, 'y la cóclea convierte la vibración en señales nerviosas', { s: 5.6 }); },
      intro: 'El oído recoge la vibración del aire, la amplifica y la convierte en una señal que el cerebro interpreta.',
      q: [['¿Qué parte vibra primero dentro del oído?', 'El tímpano.'], ['¿Cómo se llaman los tres huesecillos?', 'Martillo, yunque y estribo.'], ['¿Dónde se convierten las vibraciones en señal nerviosa?', 'En la cóclea, en el oído interno.']],
      porque: 'Las células de la cóclea no se regeneran: por eso el ruido fuerte deja daños permanentes.' },
    /* ─────────── LA VOZ Y EL CUERPO ─────────── */
    { id: 'mu_voces', fam: 'voz', n: 'Los tipos de voz',
      d: function (K) { var V = [['soprano', 112, 170, P.rosa], ['mezzosoprano', 98, 156, P.rosa], ['contralto', 84, 142, P.rosa], ['tenor', 70, 128, P.azul], ['barítono', 56, 114, P.azul], ['bajo', 42, 100, P.azul]], s = K.suelo(100, 140, 96) + K.flecha(20, 124, 190, 124, P.tinta, { w: .9 }); V.forEach(function (q, i) { var y = 22 + i * 16; s += K.caja(q[1], y, q[2] - q[1], 11, 4, q[3], { w: .7 }) + K.t(q[1] - 3, y + 8, q[0], { s: 5.6, b: 1, a: 'end' }); }); return s + K.t(30, 134, 'grave', { s: 5.4, b: 1 }) + K.t(180, 134, 'agudo', { s: 5.4, b: 1 }) + K.t(150, 140, 'rosa: voces femeninas · azul: masculinas', { s: 4.8 }); },
      intro: 'Las voces se clasifican por su tesitura: el tramo de notas que cantan con comodidad.',
      q: [['¿Cuál es la voz masculina más aguda?', 'El tenor.'], ['¿Qué voz femenina es la más grave?', 'La contralto.'], ['¿Por qué cambia la voz de los chicos en la adolescencia?', 'Porque crecen la laringe y las cuerdas vocales, y la voz baja casi una octava.']],
      porque: 'Cantar en la propia tesitura protege la voz: forzar notas fuera de ella la cansa.' },
    { id: 'mu_fonador', fam: 'voz', n: 'Cómo se produce la voz',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.p('M60 20 C40 22 36 48 46 62 C50 70 58 72 62 70 L62 96 L84 96 L84 62 C96 56 96 26 80 20 Z', P.piel, { w: 1 }) + K.r(66, 70, 14, 46, 6, P.rosa, { w: .8 }) + K.e(58, 128, 20, 14, P.rojo, { w: .8 }) + K.e(88, 128, 20, 14, P.rojo, { w: .8 }) + K.r(68, 78, 10, 6, 2, P.morado, { w: .6 }) ; s += K.flecha(73, 118, 73, 88, P.azulO, { w: 1.3 }) + K.flecha(73, 76, 64, 46, P.azulO, { w: 1.3 }); var E = [[116, 34, '3 resonadores', 'boca, nariz, garganta: dan el timbre', P.verde], [116, 64, '2 cuerdas vocales', 'en la laringe: vibran', P.morado], [116, 100, '1 pulmones', 'empujan el aire', P.rojo]]; E.forEach(function (q) { s += K.r(q[0], q[1], 72, 22, 3, q[4], { w: .7 }) + K.t(q[0] + 36, q[1] + 9, q[2], { s: 5.8, b: 1 }) + K.t(q[0] + 36, q[1] + 17, q[3], { s: 4.6 }); }); return s; },
      intro: 'La voz nace del aire de los pulmones, que hace vibrar las cuerdas vocales; la boca y la nariz le dan el timbre.',
      q: [['¿Dónde están las cuerdas vocales?', 'En la laringe, en el cuello.'], ['¿Qué pasa al tensar las cuerdas vocales?', 'Vibran más rápido y la voz sube.'], ['¿Por qué cambia la voz con la nariz tapada?', 'Porque se pierde un resonador.']],
      porque: 'La voz es un instrumento de viento: necesita aire (pulmones), algo que vibre (cuerdas) y una caja de resonancia.' },
    { id: 'mu_respirar', fam: 'voz', n: 'Respirar para cantar',
      d: function (K) { var s = K.suelo(100, 140, 96); [[50, 'inspirar', 1], [150, 'espirar al cantar', 0]].forEach(function (q) { var x = q[0], g = q[2]; s += K.c(x, 26, 9, P.piel, { w: .8 }) + K.p('M' + (x - 20) + ' 110 L' + (x - 22) + ' 50 Q' + x + ' 36 ' + (x + 22) + ' 50 L' + (x + 20) + ' 110 Z', P.azul, { w: .8 }) + K.e(x - 8, 66, g ? 9 : 7, g ? 16 : 12, P.rosa, { w: .7 }) + K.e(x + 8, 66, g ? 9 : 7, g ? 16 : 12, P.rosa, { w: .7 }) + K.l('M' + (x - 18) + ' ' + (g ? 90 : 82) + ' Q' + x + ' ' + (g ? 94 : 74) + ' ' + (x + 18) + ' ' + (g ? 90 : 82), P.rojoO, { w: 1.6 }) + K.t(x, 124, q[1], { s: 6.2, b: 1 }); }); s += K.flecha(32, 16, 42, 24, P.azulO, { w: 1 }) + K.flecha(158, 24, 172, 16, P.verdeO, { w: 1 }); return s + K.t(50, 133, 'el diafragma baja', { s: 5, b: 1, c: P.rojoO }) + K.t(150, 133, 'el diafragma sube despacio', { s: 5, b: 1, c: P.rojoO }) + K.t(100, 145, 'Se ensancha el abdomen, no se suben los hombros', { s: 5.6, b: 1 }); },
      intro: 'Para cantar se respira con el diafragma: el aire entra hasta abajo y sale despacio y controlado.',
      q: [['¿Qué músculo controla la respiración del cantante?', 'El diafragma.'], ['¿Por qué no conviene subir los hombros al inspirar?', 'Porque se toma menos aire y se tensa el cuello.'], ['Un ejercicio para controlar el aire:', 'Soltar el aire con una «s» larga contando los segundos.']],
      porque: 'Con aire suficiente y bien dosificado, la voz suena firme sin forzar la garganta.' },
    { id: 'mu_coro', fam: 'voz', n: 'Cómo se coloca un coro',
      d: function (K) { var s = K.suelo(100, 136, 96), C = [[P.rosa, 'sopranos'], [P.morado, 'contraltos'], [P.azul, 'tenores'], [P.verde, 'bajos']]; for (var f = 0; f < 2; f++) for (var i = 0; i < 8; i++) { var col = C[f === 0 ? (i < 4 ? 0 : 1) : (i < 4 ? 2 : 3)][0], x = 30 + i * 20, y = 44 + f * 26; s += K.c(x, y, 5, P.piel, { w: .6 }) + K.p('M' + (x - 7) + ' ' + (y + 18) + ' Q' + (x - 7) + ' ' + (y + 6) + ' ' + x + ' ' + (y + 6) + ' Q' + (x + 7) + ' ' + (y + 6) + ' ' + (x + 7) + ' ' + (y + 18) + ' Z', col, { w: .6 }); } s += persona(K, 100, 104, P.amarillo) + K.l('M110 110 L120 98', P.tinta, { w: 1 }); C.forEach(function (q, i) { s += K.r(14 + i * 45, 14, 8, 8, 2, q[0], { w: .5 }) + K.t(25 + i * 45, 20.5, q[1], { s: 5.4, a: 'start' }); }); return s + K.t(100, 144, 'director', { s: 5.4, b: 1 }); },
      intro: 'En un coro a cuatro voces, cada cuerda se agrupa para oírse entre sí y mezclarse con las demás.',
      q: [['¿Cuáles son las cuatro voces de un coro mixto?', 'Soprano, contralto, tenor y bajo.'], ['¿Por qué se agrupan las voces iguales?', 'Para afinar juntas y apoyarse.'], ['¿Qué hace el director?', 'Marca el pulso, las entradas, la dinámica y une a todos.']],
      porque: 'La disposición del coro cambia cómo se mezcla el sonido para el público.' },
    G('mu_corporal', 'voz', 'Percusión corporal', [['Palmas', 'agudo y seco'], ['Chasquidos', 'muy agudo, suave'], ['Pecho', 'grave y apagado'], ['Muslos', 'medio'], ['Pies', 'el más grave'], ['Lengua', 'clic, para el pulso']], 3, 22, 32, 'Ritmo: pies · muslos · palmas · chasquido (4 tiempos)', 'El cuerpo es un instrumento de percusión con sonidos de distinta altura y timbre.', [['¿Qué sonido corporal es el más grave?', 'El de los pies.'], ['Inventa un ritmo de 4 tiempos.', 'Por ejemplo: pie, palma, pie, palma.'], ['¿Por qué ayuda a aprender ritmo?', 'Porque se siente el pulso en el propio cuerpo, sin instrumentos.']], 'Antes que cualquier instrumento, el cuerpo ya sabe llevar el ritmo.', { s: 8, s2: 5.6 })
  ];
  MO.agregar('musica', L, { nombre: 'Música', familias: FAM, materias: /^(musica)$/ });
})();
