/* b6_lib_ingles3.js — Inglés (3/3): verbos irregulares, preposiciones y vocabulario temático (escuela, trabajo, viaje, deporte). 33 modelos.
   Cargar después de b6_lib_ingles2.js. Con los tres archivos, Inglés tiene 100 modelos. */
(function () {
  'use strict';
  var MO = window.EU_MODELOS; if (!MO || MO.modelo('in_irr_be')) return;
  var P = { papel: '#FBF7EE', azul: '#A8C8E8', azulO: '#3A6A9A', rojo: '#F0A8A0', rojoO: '#B83A30', verde: '#B8D8A0', verdeO: '#3E7A3A', amarillo: '#F4DC90', morado: '#D0B8E8', naranja: '#F4C090', rosa: '#F4C0D0', gris: '#E0DCD4', piel: '#F0C8A8', tinta: '#2A2420', blanco: '#FFFFFF', madera: '#B8946A' };
  var CO = [P.azul, P.amarillo, P.verde, P.rosa, P.naranja, P.morado, P.gris, P.rojo];
  var FAM = { irr: 'Verbos irregulares', pre: 'Preposiciones', tem: 'Escuela, trabajo, viaje y deporte' };
  function persona(K, x, y, col) { return K.c(x, y, 7, P.piel, { w: .8 }) + K.p('M' + (x - 11) + ' ' + (y + 30) + ' Q' + (x - 11) + ' ' + (y + 10) + ' ' + x + ' ' + (y + 10) + ' Q' + (x + 11) + ' ' + (y + 10) + ' ' + (x + 11) + ' ' + (y + 30) + ' Z', col, { w: .8 }); }
  function rejilla(K, L, cols, y0, h, o) { o = o || {}; var g = 4, w = (176 - (cols - 1) * g) / cols, s = ''; L.forEach(function (q, i) { var x = 12 + (i % cols) * (w + g), y = y0 + Math.floor(i / cols) * (h + (o.gy || 5)); var f1 = Math.min(o.s || 7, (w - 4) / (q[0].length * .6)), f2 = q[1] ? Math.min(o.s2 || 5.2, (w - 4) / (q[1].length * .58)) : 0; if (q[1]) { var k = Math.min(1, (h - 3) / (f1 + f2 + 1.6)); f1 *= k; f2 *= k; } var b1 = q[1] ? y + (h - f1 - f2 - 1.6) / 2 + f1 * .8 : y + h / 2 + f1 * .35, b2 = b1 + f1 * .2 + 1.6 + f2 * .8; s += K.r(x, y, w, h, 3, q[2] || CO[i % CO.length], { w: .8 }) + K.t(x + w / 2, +b1.toFixed(2), q[0], { s: +f1.toFixed(2), b: 1 }); if (q[1]) s += K.t(x + w / 2, +b2.toFixed(2), q[1], { s: +f2.toFixed(2) }); }); return s; }
  function G(id, fam, n, pares, cols, y0, h, pie, intro, q, porque, o) { return { id: id, fam: fam, n: n, d: function (K) { return K.suelo(100, 140, 96) + (o && o.tit ? K.t(100, 14, o.tit, { s: 7, b: 1 }) : '') + rejilla(K, pares, cols, y0, h, o) + (pie ? K.t(100, 136, pie, { s: +Math.min(6, 180 / (pie.length * .58)).toFixed(2), b: 1 }) : ''); }, intro: intro, q: q, porque: porque }; }
  /* tabla de verbos: base · pasado · participio · significado */
  function tablaV(K, V, pie) { var s = K.suelo(100, 140, 96), X = [12, 56, 100, 144], H = ['base', 'past', 'participle', 'español'], C = [P.azul, P.verde, P.naranja, P.gris]; H.forEach(function (h, j) { s += K.r(X[j], 14, 42, 14, 2, C[j], { w: .8 }) + K.t(X[j] + 21, 24, h, { s: 6, b: 1 }); }); V.forEach(function (v, i) { var y = 32 + i * 17; v.forEach(function (c, j) { s += K.r(X[j], y, 42, 14, 2, j === 3 ? P.blanco : P.papel, { w: .5 }) + K.t(X[j] + 21, y + 10, c, { s: +Math.min(j === 3 ? 5.4 : 7, 39 / (c.length * .58)).toFixed(2), b: j < 3 ? 1 : 0 }); }); }); return s + (pie ? K.t(100, 136, pie, { s: +Math.min(6, 180 / (pie.length * .58)).toFixed(2), b: 1 }) : ''); }
  function V(id, n, verbos, pie, intro, q, porque) { return { id: id, fam: 'irr', n: n, d: function (K) { return tablaV(K, verbos, pie); }, intro: intro, q: q, porque: porque }; }
  /* caja con pelota para las preposiciones de lugar */
  function caja(K, x, y) { return K.p('M' + x + ' ' + y + ' l26 0 l8 -6 l-26 0 Z', '#D8B888', { w: .8 }) + K.r(x, y, 26, 20, 0, P.madera, { w: .8 }) + K.p('M' + (x + 26) + ' ' + y + ' l8 -6 l0 20 l-8 6 Z', '#9A7650', { w: .8 }); }
  function pelota(K, x, y) { return K.c(x, y, 5, '#E0483C', { w: .8 }); }

  var L = [
    /* ─────────── VERBOS IRREGULARES ─────────── */
    V('in_irr_be', 'Be, have, do', [['be', 'was / were', 'been', 'ser, estar'], ['have', 'had', 'had', 'tener'], ['do', 'did', 'done', 'hacer'], ['make', 'made', 'made', 'fabricar, hacer']], '«do» = actividad · «make» = crear algo', 'Los tres verbos más usados del inglés son irregulares y además sirven de auxiliares.', [['Pasado de «have»:', '«Had».'], ['¿«do» o «make» con «homework»?', '«Do homework».'], ['¿«do» o «make» con «a cake»?', '«Make a cake».']], 'Los verbos más frecuentes son los más irregulares: se usan tanto que nunca se regularizaron.'),
    V('in_irr_go', 'Go, come, leave', [['go', 'went', 'gone', 'ir'], ['come', 'came', 'come', 'venir'], ['leave', 'left', 'left', 'salir, dejar'], ['run', 'ran', 'run', 'correr'], ['fly', 'flew', 'flown', 'volar']], 'I went to school · She has gone home', 'Verbos de movimiento con formas irregulares.', [['Pasado de «go»:', '«Went».'], ['Participio de «come»:', '«Come», igual que la base.'], ['Completa: The plane ___ (fly) to Madrid.', '«Flew».']], '«Went» venía de otro verbo antiguo, «wend»: por eso no se parece a «go».'),
    V('in_irr_eat', 'Eat, drink, sleep', [['eat', 'ate', 'eaten', 'comer'], ['drink', 'drank', 'drunk', 'beber'], ['sleep', 'slept', 'slept', 'dormir'], ['cook', 'cooked', 'cooked', 'cocinar (regular)'], ['feed', 'fed', 'fed', 'alimentar']], 'i → a → u: drink, drank, drunk', 'Verbos de comida y descanso; «cook» aparece para comparar con uno regular.', [['Pasado de «eat»:', '«Ate».'], ['¿Es irregular «cook»?', 'No: cooked.'], ['Completa: I have ___ (drink) two glasses.', '«Drunk».']], 'Algunos verbos cambian solo la vocal: drink, drank, drunk, como sing, sang, sung.'),
    V('in_irr_see', 'See, hear, feel', [['see', 'saw', 'seen', 'ver'], ['hear', 'heard', 'heard', 'oír'], ['feel', 'felt', 'felt', 'sentir'], ['smell', 'smelt', 'smelt', 'oler'], ['find', 'found', 'found', 'encontrar']], 'smell: smelt (UK) o smelled (US)', 'Verbos de los sentidos y de percibir.', [['Pasado de «see»:', '«Saw».'], ['Participio de «feel»:', '«Felt».'], ['¿Cómo suena «heard»?', '«Jerd», con la e de «her».']], 'En EE. UU. algunos de estos verbos se usan ya como regulares: smelled, learned.'),
    V('in_irr_say', 'Say, tell, speak', [['say', 'said', 'said', 'decir'], ['tell', 'told', 'told', 'contar, decir a'], ['speak', 'spoke', 'spoken', 'hablar'], ['write', 'wrote', 'written', 'escribir'], ['read', 'read', 'read', 'leer']], 'tell + persona: She told me · say + algo: She said hi', 'Verbos de comunicación; «read» se escribe igual pero cambia de sonido.', [['¿«said me» o «told me»?', '«Told me»: «tell» lleva la persona detrás.'], ['¿Cómo suena el pasado de «read»?', '«Red».'], ['Participio de «write»:', '«Written».']], '«Say» se centra en las palabras; «tell», en la persona que las recibe.'),
    V('in_irr_buy', 'Buy, bring, think', [['buy', 'bought', 'bought', 'comprar'], ['bring', 'brought', 'brought', 'traer'], ['think', 'thought', 'thought', 'pensar'], ['catch', 'caught', 'caught', 'atrapar'], ['teach', 'taught', 'taught', 'enseñar']], 'Todos terminan en «-ought» o «-aught»: suenan «ot»', 'Un grupo de verbos que comparte la misma terminación en pasado.', [['Pasado de «buy»:', '«Bought».'], ['¿Cómo suena «thought»?', '«Zot», con la th sin voz.'], ['Completa: My teacher ___ (teach) me a lot.', '«Taught».']], 'Aprender los verbos por grupos que riman es más fácil que en orden alfabético.'),
    V('in_irr_take', 'Take, give, get', [['take', 'took', 'taken', 'tomar, llevar'], ['give', 'gave', 'given', 'dar'], ['get', 'got', 'got / gotten', 'conseguir, llegar'], ['forget', 'forgot', 'forgotten', 'olvidar'], ['break', 'broke', 'broken', 'romper']], 'Muchos participios terminan en -en', 'Verbos muy frecuentes con participio en -en.', [['Participio de «give»:', '«Given».'], ['¿«got» o «gotten» en EE. UU.?', '«Gotten»; en el Reino Unido, «got».'], ['Completa: I have ___ (forget) my keys.', '«Forgotten».']], 'El participio en -en es una huella del inglés antiguo.'),
    V('in_irr_know', 'Know, grow, throw', [['know', 'knew', 'known', 'saber, conocer'], ['grow', 'grew', 'grown', 'crecer'], ['throw', 'threw', 'thrown', 'lanzar'], ['blow', 'blew', 'blown', 'soplar'], ['draw', 'drew', 'drawn', 'dibujar']], 'ow → ew → own', 'Verbos que siguen el patrón -ow, -ew, -own.', [['Pasado de «know»:', '«Knew», con la k muda.'], ['Participio de «grow»:', '«Grown».'], ['Completa: She ___ (draw) a cat.', '«Drew».']], 'Un mismo patrón sirve para varios verbos: si sabes uno, sabes el grupo.'),
    V('in_irr_begin', 'Begin, swim, sing', [['begin', 'began', 'begun', 'empezar'], ['swim', 'swam', 'swum', 'nadar'], ['sing', 'sang', 'sung', 'cantar'], ['ring', 'rang', 'rung', 'sonar, llamar'], ['sit', 'sat', 'sat', 'sentarse']], 'i → a → u', 'Verbos que cambian la vocal i por a en pasado y por u en participio.', [['Pasado de «swim»:', '«Swam».'], ['Participio de «sing»:', '«Sung».'], ['Completa: The class has ___ (begin).', '«Begun».']], 'La vocal marca el tiempo: a para el pasado, u para el participio.'),
    V('in_irr_put', 'Put, cut, let (AAA)', [['put', 'put', 'put', 'poner'], ['cut', 'cut', 'cut', 'cortar'], ['let', 'let', 'let', 'dejar'], ['hit', 'hit', 'hit', 'golpear'], ['cost', 'cost', 'cost', 'costar']], 'Las tres formas iguales: el contexto dice el tiempo', 'Verbos que no cambian en ninguna de sus formas.', [['Pasado de «put»:', '«Put».'], ['¿Cómo sabes si «I cut» es pasado?', 'Por el contexto: yesterday, last week…'], ['Completa: It ___ ten dollars yesterday.', '«Cost».']], 'Son verbos cortos que ya terminan en t o d, como si llevaran el pasado incorporado.'),
    V('in_irr_lose', 'Lose, win, pay', [['lose', 'lost', 'lost', 'perder'], ['win', 'won', 'won', 'ganar'], ['pay', 'paid', 'paid', 'pagar'], ['spend', 'spent', 'spent', 'gastar'], ['sell', 'sold', 'sold', 'vender']], '«won» suena como «one»', 'Verbos de juego y de dinero.', [['Pasado de «win»:', '«Won».'], ['¿Se escribe «payed»?', 'No: «paid».'], ['Completa: We ___ (lose) the match.', '«Lost».']], 'Con estos verbos se cuentan resultados y compras en pasado.'),
    { id: 'in_irr_patterns', fam: 'irr', n: 'Irregular patterns · Patrones',
      d: function (K) { var R = [['AAA', 'cut · cut · cut', 'las tres iguales', P.verde], ['ABB', 'buy · bought · bought', 'pasado = participio', P.azul], ['ABA', 'come · came · come', 'base = participio', P.amarillo], ['ABC', 'go · went · gone', 'las tres distintas', P.rojo]], s = K.suelo(100, 140, 96); R.forEach(function (q, i) { var y = 16 + i * 26; s += K.r(12, y, 36, 22, 3, q[3], { w: .8 }) + K.t(30, y + 15, q[0], { s: 10, b: 1 }) + K.r(52, y, 136, 22, 3, P.papel, { w: .6 }) + K.t(58, y + 10, q[1], { s: 7, b: 1, a: 'start' }) + K.t(58, y + 18, q[2], { s: 5.2, a: 'start' }); }); return s + K.t(100, 134, 'Clasificar los verbos por patrón ayuda a memorizarlos', { s: 6, b: 1 }); },
      intro: 'Los verbos irregulares se pueden agrupar en cuatro patrones según qué formas coinciden.',
      q: [['¿Qué patrón sigue «sleep, slept, slept»?', 'ABB.'], ['¿Y «run, ran, run»?', 'ABA.'], ['¿Y «see, saw, seen»?', 'ABC.']],
      porque: 'El grupo ABB es el más numeroso: si dudas, a menudo pasado y participio coinciden.' },
    /* ─────────── PREPOSICIONES ─────────── */
    { id: 'in_prep_place', fam: 'pre', n: 'In, on, under · Preposiciones de lugar',
      d: function (K) { var s = K.suelo(100, 140, 96), X = [16, 78, 140]; X.forEach(function (x) { s += caja(K, x, 50); }); s += pelota(K, 29, 62) + pelota(K, 98, 39) + pelota(K, 158, 79); return s + K.t(33, 98, 'in', { s: 9, b: 1 }) + K.t(33, 108, 'dentro', { s: 5.4 }) + K.t(95, 98, 'on', { s: 9, b: 1 }) + K.t(95, 108, 'encima', { s: 5.4 }) + K.t(157, 98, 'under', { s: 9, b: 1 }) + K.t(157, 108, 'debajo', { s: 5.4 }) + K.t(100, 128, 'The ball is in the box.', { s: 7, b: 1 }); },
      intro: 'Tres preposiciones básicas de lugar, con una pelota y una caja.',
      q: [['Where is the cat? It’s ___ the bed. (debajo)', '«Under».'], ['¿«in» u «on» con «the table»?', '«On the table».'], ['¿«in» u «on» con «the fridge» (dentro)?', '«In the fridge».']],
      porque: '«On» exige contacto con la superficie; «in», estar dentro de un espacio.' },
    { id: 'in_prep_place2', fam: 'pre', n: 'Next to, between, behind · Más lugar',
      d: function (K) { var s = K.suelo(100, 140, 96); s += caja(K, 14, 44) + pelota(K, 54, 59) + K.t(32, 86, 'next to', { s: 7, b: 1 }) + K.t(32, 94, 'al lado de', { s: 5 }); s += caja(K, 66, 44) + pelota(K, 108, 59) + caja(K, 114, 44); s += K.t(108, 86, 'between', { s: 7, b: 1 }) + K.t(108, 94, 'entre', { s: 5 }); s += pelota(K, 172, 42) + caja(K, 156, 46) + K.t(170, 86, 'behind', { s: 7, b: 1 }) + K.t(170, 94, 'detrás', { s: 5 }); return s + K.r(12, 106, 176, 22, 3, P.papel, { w: .6 }) + K.t(100, 116, 'behind = detrás de · in front of = delante de', { s: 6.2, b: 1 }) + K.t(100, 124, 'opposite = enfrente · near = cerca de', { s: 5.4 }); },
      intro: 'Preposiciones para situar una cosa respecto a otras.',
      q: [['The bank is ___ the café and the shop.', '«Between».'], ['¿Qué significa «opposite»?', 'Enfrente, al otro lado.'], ['¿Cómo se dice «delante de»?', '«In front of».']],
      porque: 'Estas preposiciones permiten dar indicaciones y describir una habitación.' },
    { id: 'in_prep_time', fam: 'pre', n: 'At, on, in · Preposiciones de tiempo',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.p('M100 14 L178 112 L22 112 Z', P.papel, { w: 1 }) + K.l('M74 46 L126 46 M48 80 L152 80', P.tinta, { w: .8 }); s += K.t(100, 36, 'at', { s: 9, b: 1, c: P.rojoO }) + K.t(100, 44, '7 o’clock · night', { s: 4.6 }) + K.t(100, 64, 'on', { s: 9, b: 1, c: P.azulO }) + K.t(100, 74, 'Monday · 5th May · my birthday', { s: 5 }) + K.t(100, 96, 'in', { s: 9, b: 1, c: P.verdeO }) + K.t(100, 106, 'May · 2026 · summer · the morning', { s: 5.4 }); return s + K.t(100, 128, 'De lo más concreto (arriba) a lo más amplio (abajo)', { s: 6, b: 1 }); },
      intro: '«At» para horas, «on» para días y fechas, «in» para meses, años y estaciones.',
      q: [['¿«at», «on» o «in» con «Friday»?', '«On Friday».'], ['¿Y con «2010»?', '«In 2010».'], ['¿«in the night» o «at night»?', '«At night», pero «in the morning».']],
      porque: 'Cuanto más amplio es el periodo, más se baja en la pirámide: at, on, in.' },
    { id: 'in_prep_move', fam: 'pre', n: 'Prepositions of movement · Movimiento',
      d: function (K) { var M = [['into', 'hacia dentro'], ['out of', 'hacia fuera'], ['across', 'de un lado a otro'], ['through', 'a través de'], ['up', 'hacia arriba'], ['down', 'hacia abajo'], ['along', 'a lo largo de'], ['around', 'alrededor de']], s = K.suelo(100, 140, 96); M.forEach(function (q, i) { var x = 12 + (i % 4) * 45, y = 16 + Math.floor(i / 4) * 56, cx = x + 20; s += K.r(x, y, 41, 50, 3, CO[i], { w: .6 }); var a = [[cx - 14, y + 18, cx + 2, y + 18], [cx - 2, y + 18, cx + 14, y + 18], [x + 4, y + 18, x + 37, y + 18], [x + 4, y + 18, x + 37, y + 18], [cx, y + 28, cx, y + 6], [cx, y + 6, cx, y + 28], [x + 4, y + 22, x + 37, y + 22], [cx + 10, y + 10, cx + 9, y + 26]][i]; if (i < 2) s += K.r(cx - 2, y + 8, 14, 20, 0, P.blanco, { w: .6 }); if (i === 3) s += K.r(cx - 6, y + 6, 12, 24, 6, P.blanco, { w: .6 }); if (i === 7) s += K.c(cx, y + 18, 6, P.blanco, { w: .6 }); s += K.flecha(a[0], a[1], a[2], a[3], P.tinta, { w: 1.2 }) + K.t(cx, y + 40, q[0], { s: 6.6, b: 1 }) + K.t(cx, y + 47, q[1], { s: 4.2 }); }); return s; },
      intro: 'Preposiciones que indican hacia dónde se mueve algo.',
      q: [['The cat jumped ___ the box. (hacia dentro)', '«Into».'], ['¿Qué significa «walk across the street»?', 'Cruzar la calle.'], ['We drove ___ the tunnel.', '«Through».']],
      porque: 'Con verbos de movimiento la preposición indica la dirección, no solo el lugar.' },
    { id: 'in_directions', fam: 'pre', n: 'Giving directions · Indicar el camino',
      d: function (K) { var s = K.suelo(100, 140, 96) + K.r(12, 14, 176, 104, 3, '#E8ECDE', { w: .8 }) + K.r(12, 58, 176, 16, 0, P.gris, { w: .4 }) + K.r(92, 14, 16, 104, 0, P.gris, { w: .4 }); s += K.r(20, 22, 30, 28, 2, P.azul, { w: .6 }) + K.t(35, 39, 'bank', { s: 6, b: 1 }) + K.r(116, 22, 34, 28, 2, P.rosa, { w: .6 }) + K.t(133, 39, 'café', { s: 6, b: 1 }) + K.r(116, 82, 40, 28, 2, P.verde, { w: .6 }) + K.t(136, 99, 'park', { s: 6, b: 1 }) + K.r(20, 82, 30, 28, 2, P.amarillo, { w: .6 }) + K.t(35, 99, 'school', { s: 6, b: 1 }); s += K.c(100, 112, 3.4, P.rojoO) + K.t(108, 114, 'you', { s: 5, b: 1, a: 'start' }) + K.flecha(100, 108, 100, 70, P.rojoO, { w: 1.4 }) + K.flecha(100, 66, 130, 66, P.rojoO, { w: 1.4 }); return s + K.t(100, 132, 'Go straight on, turn right. The café is on your left.', { s: 5.6, b: 1 }); },
      intro: 'Las frases para indicar un camino sobre un plano sencillo.',
      q: [['¿Qué significa «go straight on»?', 'Sigue recto.'], ['¿Cómo se dice «gira a la izquierda»?', '«Turn left».'], ['Excuse me, where is the park?', 'Go straight on, turn right; it’s on your right.']],
      porque: 'Las indicaciones usan el imperativo y la posición respecto a quien camina.' },
    G('in_transport', 'pre', 'By bus, on foot · Medios de transporte', [['by bus', 'en autobús'], ['by car', 'en coche'], ['by train', 'en tren'], ['by plane', 'en avión'], ['by bike', 'en bici'], ['on foot', 'a pie', P.rosa], ['get on the bus', 'subir al autobús'], ['get off the bus', 'bajar del autobús']], 4, 22, 36, '«by» sin artículo: by bus, no «by the bus»', 'Para el medio de transporte se usa «by», salvo «on foot».', [['¿Cómo se dice «voy andando»?', '«I go on foot» o «I walk».'], ['¿«by the train» o «by train»?', '«By train».'], ['How do you get to school?', 'Respuesta libre: I go by bus.']], '«On foot» es la excepción porque no es un vehículo.', { s: 7.4, s2: 5.4 }),
    G('in_prep_adj', 'pre', 'Adjectives + prepositions · Adjetivo y preposición', [['good at', 'bueno en'], ['afraid of', 'miedo de'], ['interested in', 'interesado en'], ['proud of', 'orgulloso de'], ['different from', 'distinto de'], ['angry with', 'enfadado con'], ['tired of', 'cansado de'], ['keen on', 'aficionado a']], 2, 14, 22, 'Se aprenden en bloque: no se traducen palabra a palabra', 'Muchos adjetivos van siempre con la misma preposición.', [['I’m good ___ maths.', '«At».'], ['She’s afraid ___ spiders.', '«Of».'], ['Are you interested ___ music?', '«In».']], 'La preposición inglesa no siempre coincide con la española: «good at», no «good in».', { s: 7.6, s2: 5.4 }),
    G('in_phrasal', 'pre', 'Phrasal verbs · Verbos con partícula', [['get up', 'levantarse'], ['turn on', 'encender'], ['turn off', 'apagar'], ['look for', 'buscar'], ['give up', 'rendirse, dejar'], ['put on', 'ponerse'], ['find out', 'averiguar'], ['look after', 'cuidar']], 2, 14, 22, 'La partícula cambia el significado: look ≠ look for', 'Un verbo y una partícula forman un significado nuevo.', [['¿Qué significa «turn off the light»?', 'Apagar la luz.'], ['I’m looking ___ my keys.', '«For».'], ['¿Qué significa «give up»?', 'Rendirse o dejar de hacer algo.']], 'Los phrasal verbs son muy frecuentes al hablar y conviene aprenderlos con un ejemplo.', { s: 7.6, s2: 5.4 }),
    G('in_prep_common', 'pre', 'Common mistakes · Errores frecuentes', [['married to (no with)', 'casado con', P.rojo], ['depend on (no of)', 'depender de', P.rojo], ['arrive in / at (no to)', 'llegar a', P.rojo], ['listen to music', 'escuchar música', P.verde], ['wait for the bus', 'esperar el autobús', P.verde], ['on TV · on the radio', 'en la tele', P.verde]], 2, 14, 30, 'arrive in + ciudad/país · arrive at + edificio', 'Preposiciones que se traducen mal del español.', [['¿«arrive to London» o «arrive in London»?', '«Arrive in London».'], ['I’m waiting ___ my friend.', '«For».'], ['It depends ___ the weather.', '«On».']], 'Copiar la preposición del español es la causa de estos errores.', { s: 7.4, s2: 5.4 }),
    G('in_prep_places', 'pre', 'At home, in town · Lugares', [['at home', 'en casa', P.amarillo], ['at school', 'en el colegio', P.azul], ['at work', 'en el trabajo', P.naranja], ['in the city', 'en la ciudad', P.verde], ['in Mexico', 'en México', P.verde], ['in the kitchen', 'en la cocina', P.verde], ['on the street', 'en la calle', P.morado], ['on the bus', 'en el autobús', P.morado], ['on the first floor', 'en la primera planta', P.morado]], 3, 14, 28, 'at = un punto · in = un espacio · on = una superficie o línea', 'Las tres maneras de decir «en» según el tipo de lugar.', [['¿«in home» o «at home»?', '«At home».'], ['¿«in» u «on» con «the bus»?', '«On the bus»; en coche se dice «in the car».'], ['I live ___ Lima.', '«In».']], 'El español usa «en» para todo; el inglés distingue punto, espacio y superficie.', { s: 7.6, s2: 5.4 }),
    /* ─────────── ESCUELA, TRABAJO, VIAJE Y DEPORTE ─────────── */
    G('in_subjects', 'tem', 'School subjects · Asignaturas', [['Maths', 'Matemáticas'], ['Science', 'Ciencias'], ['History', 'Historia'], ['Geography', 'Geografía'], ['Art', 'Arte'], ['Music', 'Música'], ['P.E.', 'Educación física'], ['Spanish', 'Lengua'], ['English', 'Inglés'], ['I.T.', 'Informática'], ['Biology', 'Biología'], ['Chemistry', 'Química']], 4, 14, 24, 'Con mayúscula · What’s your favourite subject?', 'Las asignaturas escolares en inglés.', [['¿Qué es «P.E.»?', 'Physical Education: Educación física.'], ['¿Se dice «the Maths»?', 'No: «I like Maths», sin artículo.'], ['What’s your favourite subject?', 'Respuesta libre: My favourite subject is Art.']], 'Las asignaturas se escriben con mayúscula y sin artículo.', { s: 8, s2: 5.2 }),
    { id: 'in_timetable', fam: 'tem', n: 'School timetable · El horario',
      d: function (K) { var D = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], H = ['9:00', '10:00', '11:00', '12:00'], A = [['Maths', 'English', 'Maths', 'Science', 'Art'], ['Science', 'Maths', 'History', 'English', 'Maths'], ['break', 'break', 'break', 'break', 'break'], ['P.E.', 'Music', 'English', 'P.E.', 'I.T.']], CM = { Maths: P.azul, English: P.rosa, Science: P.verde, Art: P.naranja, History: P.amarillo, 'P.E.': P.morado, Music: P.amarillo, 'I.T.': P.gris, 'break': P.blanco }, s = K.suelo(100, 140, 96); D.forEach(function (d, j) { s += K.r(40 + j * 30, 14, 28, 14, 2, P.tinta) + K.t(54 + j * 30, 24, d, { s: 6, b: 1, c: P.blanco }); }); H.forEach(function (h, i) { var y = 32 + i * 22; s += K.t(36, y + 12, h, { s: 5.6, b: 1, a: 'end' }); A[i].forEach(function (a, j) { s += K.r(40 + j * 30, y, 28, 18, 2, CM[a], { w: .5 }) + K.t(54 + j * 30, y + 12, a, { s: 5.2, b: 1 }); }); }); return s + K.t(100, 132, 'On Mondays I have Maths at nine o’clock.', { s: 6, b: 1 }); },
      intro: 'Un horario semanal para practicar días, horas y asignaturas.',
      q: [['What do you have on Tuesday at nine?', 'English.'], ['When do you have P.E.?', 'On Monday and Thursday at twelve.'], ['¿Qué es «break»?', 'El recreo.']],
      porque: 'El horario combina vocabulario de días, horas y asignaturas en frases reales.' },
    G('in_office', 'tem', 'At work · En el trabajo', [['meeting', 'reunión'], ['email', 'correo'], ['boss', 'jefe/a'], ['colleague', 'compañero/a'], ['salary', 'sueldo'], ['schedule', 'horario'], ['deadline', 'fecha límite'], ['report', 'informe'], ['customer', 'cliente'], ['office', 'oficina'], ['shift', 'turno'], ['day off', 'día libre']], 4, 14, 24, 'I work from 9 to 5 · I work part-time / full-time', 'Vocabulario básico del entorno de trabajo.', [['¿Qué es un «deadline»?', 'La fecha límite para entregar algo.'], ['¿Cómo se dice «compañero de trabajo»?', '«Colleague» o «co-worker».'], ['What are your working hours?', 'Respuesta libre: I work from nine to five.']], 'Estas palabras aparecen en correos, entrevistas y conversaciones de trabajo.', { s: 7.8, s2: 5.2 }),
    { id: 'in_cv', fam: 'tem', n: 'A CV · El currículum',
      d: function (K) { var s = K.suelo(100, 140, 60) + K.r(52, 10, 96, 124, 2, P.blanco, { w: 1 }) + K.c(70, 28, 9, P.piel, { w: .6 }) + K.t(84, 26, 'Ana López', { s: 7, b: 1, a: 'start' }) + K.t(84, 34, 'ana@mail.com', { s: 4.6, a: 'start' }); [['Personal profile', 46], ['Work experience', 66], ['Education', 86], ['Skills', 104], ['Languages', 120]].forEach(function (q, i) { s += K.r(58, q[1], 84, 7, 1, CO[i], { w: .4 }) + K.t(60, q[1] + 5.4, q[0], { s: 5, b: 1, a: 'start' }) + K.l('M60 ' + (q[1] + 11) + ' L132 ' + (q[1] + 11), '#C8C0B0', { w: .6 }); }); return s; },
      rot: [['Datos de contacto', 84, 34, 22, 26], ['Experiencia', 100, 70, 178, 70], ['Formación', 100, 90, 22, 90], ['Idiomas', 100, 124, 178, 124]],
      intro: 'Las secciones de un currículum en inglés.',
      q: [['¿Qué va en «Work experience»?', 'Los trabajos anteriores, del más reciente al más antiguo.'], ['¿En qué tiempo se describe un trabajo pasado?', 'En pasado simple: I worked as a waiter.'], ['¿Qué es el «personal profile»?', 'Un resumen breve de quién eres y qué ofreces.']],
      porque: 'En muchos países de habla inglesa el CV no lleva foto ni edad.' },
    { id: 'in_airport', fam: 'tem', n: 'At the airport · En el aeropuerto',
      d: function (K) { var S = [['check-in', 'facturar', P.azul], ['security', 'control', P.amarillo], ['passport control', 'pasaportes', P.verde], ['gate', 'puerta', P.naranja], ['boarding', 'embarque', P.rosa]], s = K.suelo(100, 140, 96); S.forEach(function (q, i) { var x = 12 + i * 36; s += K.r(x, 30, 32, 40, 3, q[2], { w: .8 }) + K.t(x + 16, 48, q[0].split(' ')[0], { s: 5.6, b: 1 }) + (q[0].split(' ')[1] ? K.t(x + 16, 55, q[0].split(' ')[1], { s: 5.6, b: 1 }) : '') + K.t(x + 16, 64, q[1], { s: 4.4 }) + (i < 4 ? K.flecha(x + 32, 50, x + 36, 50, P.tinta, { w: .8, p: 3 }) : ''); }); return s + K.p('M60 100 L130 96 L140 92 L146 94 L138 100 L146 104 L140 106 L130 102 L60 104 Z', P.blanco, { w: .8 }) + K.p('M96 98 L82 84 L90 84 L110 97 Z', P.gris, { w: .6 }) + K.t(100, 18, 'Departures · Salidas', { s: 7, b: 1 }) + K.t(100, 128, 'boarding pass = tarjeta de embarque · luggage = equipaje', { s: 5.6 }); },
      intro: 'Los pasos de un aeropuerto, de la facturación al embarque.',
      q: [['¿Qué es la «gate»?', 'La puerta de embarque.'], ['¿Cómo se dice «facturar la maleta»?', '«Check in your luggage».'], ['Can I see your boarding pass?', 'Te piden la tarjeta de embarque.']],
      porque: 'Los carteles de los aeropuertos internacionales están en inglés.' },
    G('in_hotel', 'tem', 'At the hotel · En el hotel', [['I have a reservation.', 'tengo una reserva', P.azul], ['a single / double room', 'individual / doble', P.verde], ['What time is breakfast?', '¿a qué hora es el desayuno?', P.amarillo], ['The key, please.', 'la llave, por favor', P.naranja], ['The shower doesn’t work.', 'la ducha no funciona', P.rojo], ['What time is check-out?', '¿a qué hora hay que dejar la habitación?', P.morado]], 1, 14, 16, 'reception = recepción · lift (UK) / elevator (US)', 'Frases útiles para alojarse en un hotel.', [['¿Cómo se dice «habitación doble»?', '«A double room».'], ['¿Qué es el «check-out»?', 'La salida del hotel y la hora límite para dejar la habitación.'], ['¿«Lift» o «elevator»?', 'Los dos: «lift» en el Reino Unido, «elevator» en EE. UU.']], 'Conocer estas frases resuelve casi todas las situaciones de un viaje.', { s: 7, s2: 5, gy: 3 }),
    { id: 'in_tickets', fam: 'tem', n: 'Buying a ticket · Comprar un billete',
      d: function (K) { return K.suelo(100, 140, 96) + K.r(24, 22, 152, 56, 4, P.amarillo, { w: 1 }) + K.l('M140 22 L140 78', P.tinta, { w: .8, d: '3 2' }) + K.t(30, 36, 'TRAIN TICKET', { s: 7, b: 1, a: 'start' }) + K.t(30, 50, 'From: London', { s: 6.4, a: 'start' }) + K.t(30, 60, 'To: Oxford', { s: 6.4, a: 'start' }) + K.t(30, 72, 'Return · Platform 4', { s: 6, b: 1, a: 'start' }) + K.t(158, 46, '£25', { s: 10, b: 1 }) + K.t(158, 62, '10:15', { s: 7, b: 1 }) + K.t(100, 96, 'A return ticket to Oxford, please.', { s: 7, b: 1 }) + K.t(100, 110, 'single = solo ida · return = ida y vuelta', { s: 6 }) + K.t(100, 124, 'platform = andén · delayed = con retraso', { s: 6 }); },
      intro: 'Los datos de un billete de tren y la frase para comprarlo.',
      q: [['¿Qué es un «return ticket»?', 'Un billete de ida y vuelta.'], ['¿Qué significa «platform 4»?', 'Andén 4.'], ['¿Cómo se dice «solo ida»?', '«Single» (UK) o «one-way» (US).']],
      porque: 'En el Reino Unido y en EE. UU. se usan palabras distintas para el mismo billete.' },
    G('in_sports', 'tem', 'Sports · Deportes', [['football', 'fútbol'], ['basketball', 'baloncesto'], ['tennis', 'tenis'], ['volleyball', 'voleibol'], ['swimming', 'natación'], ['cycling', 'ciclismo'], ['athletics', 'atletismo'], ['baseball', 'béisbol'], ['karate', 'kárate'], ['gymnastics', 'gimnasia'], ['skating', 'patinaje'], ['running', 'correr']], 4, 14, 24, 'football (UK) = soccer (US)', 'Doce deportes; en EE. UU. el fútbol se llama «soccer».', [['¿Qué es «American football»?', 'El fútbol americano, distinto del «soccer».'], ['¿Cómo se dice «natación»?', '«Swimming».'], ['What sports do you like?', 'Respuesta libre: I like basketball.']], 'Una misma palabra puede nombrar deportes distintos según el país.', { s: 7.6, s2: 5.2 }),
    G('in_play_go_do', 'tem', 'Play, go or do? · ¿Play, go o do?', [['play', 'football, tennis, chess', P.azul], ['go', 'swimming, cycling, running', P.verde], ['do', 'karate, yoga, gymnastics', P.naranja]], 3, 24, 60, 'play: con pelota · go: en -ing · do: artes y ejercicios', 'Cada deporte va con uno de estos tres verbos.', [['¿«play» o «go» con «skiing»?', '«Go skiing».'], ['¿«do» o «play» con «judo»?', '«Do judo».'], ['¿«play» con «basketball»?', 'Sí: play basketball.']], 'La regla funciona casi siempre: pelota con play, -ing con go y el resto con do.', { s: 11, s2: 5 }),
    G('in_comparatives', 'tem', 'Comparatives · Comparativos', [['tall → taller', 'corto: + er', P.azul], ['big → bigger', 'dobla la consonante', P.verde], ['happy → happier', 'y → ier', P.amarillo], ['expensive → more expensive', 'largo: more', P.naranja], ['good → better', 'irregular', P.rosa], ['bad → worse', 'irregular', P.rojo]], 2, 14, 30, 'A train is faster than a bike: «than» = que', 'Para comparar dos cosas se añade -er o se usa «more», y después «than».', [['Comparativo de «hot»:', '«Hotter».'], ['¿«more easy» o «easier»?', '«Easier».'], ['Completa: Spain is ___ (big) than Portugal.', '«Bigger».']], 'La longitud del adjetivo decide entre -er y «more».', { s: 7.4, s2: 5.4 }),
    G('in_superlatives', 'tem', 'Superlatives · Superlativos', [['tall → the tallest', 'el más alto', P.azul], ['big → the biggest', 'el más grande', P.verde], ['happy → the happiest', 'el más feliz', P.amarillo], ['expensive → the most expensive', 'el más caro', P.naranja], ['good → the best', 'el mejor', P.rosa], ['bad → the worst', 'el peor', P.rojo]], 2, 14, 30, 'Everest is the highest mountain in the world', 'El superlativo destaca uno sobre todos los demás y lleva «the».', [['Superlativo de «good»:', '«The best».'], ['Completa: It’s the ___ (cold) month.', '«Coldest».'], ['¿Se dice «the most big»?', 'No: «the biggest».']], 'Superlativo y comparativo siguen la misma regla: -est o «most» según la longitud.', { s: 7, s2: 5.4 })
  ];
  MO.agregar('ingles', L, { nombre: 'Inglés', familias: FAM, materias: /^(ingles)$/ });
})();
