/* b6_marketing_ia.js — materias «Marketing digital» (mkt) e «IA desde cero» (ia).
   · 13 + 12 unidades con ideas, palabras clave, V/F, preguntas, figura (flujo/mapa/ciclo) y gancho.
   · Generadores con respuesta y proceso: CTR, CPC, CPM, conversión, ROAS, CAC, LTV, email,
     ingresos de un freelance (marketing) y tiempo ahorrado, rentabilidad de una suscripción,
     precisión y costo por tarea (IA). Importes en la moneda del país con EU_EMPRE.FX.
   · SABER con datos históricos verificables para «Para saber más» (EU_LIBRO).
   · Usan los productos generales (libro, cuaderno, examen, curso/vídeo de los conectores).
   Cargar después de b6_emprendimiento_2026.js. */
(function () {
  'use strict';
  var ED = window.EU_EDITORIAL, LB = window.EU_LIBRO;
  if (!ED || window.EU_MKT_IA) return;
  var H = ED.H, it = H.it, E = H.ent, FX = (window.EU_EMPRE && EU_EMPRE.FX) || { es: 1 };
  function bon(v) { if (v <= 0) return 0; if (v < 10) return Math.round(v * 10) / 10; var p = Math.pow(10, Math.max(0, Math.floor(Math.log10(v)) - 1)); return Math.round(v / p) * p; }
  function m(eur, C) { return bon(eur * (FX[C.pk] || 1)); }
  function $(v, C) { return H.din(v, C); }
  function pc(a, b) { return Math.round(a / b * 1000) / 10; }
  function n(x, C) { return H.num(x, C); }
  var P = H.pick;

  var U = [];
  function un(mat, id, b, t, g, i, k, vf, q, f, h) { U.push({ m: mat, id: id, b: b.split(' '), t: t, g: g, i: i, k: k, vf: vf.split('|').map(function (s) { return [s.slice(2), s.charAt(0) === 'V']; }), q: q, f: f, h: h, plus: true }); }
  var B = 'sec bach fp adu';

  /* ─────────── Marketing digital ─────────── */
  un('mkt', 'mkt_que', B, 'Qué es el marketing', 'mkt_conv', ['El marketing es el trabajo de entender qué necesita un grupo de personas y ofrecerle algo de valor de forma rentable.', 'No es solo publicidad: incluye el producto, el precio, dónde se vende y cómo se comunica.', 'El marketing digital hace lo mismo con internet: buscadores, redes, correo, tiendas en línea y anuncios.', 'Todo se puede medir: cuántas personas ven, cuántas hacen clic y cuántas compran.'], ['marketing', 'valor', 'necesidad', 'mercado', 'medición'], 'V:El marketing empieza por entender al cliente.|F:Marketing es lo mismo que publicidad.|V:En digital casi todo se puede medir.', ['Explica con tus palabras qué es el marketing.', 'Pon un ejemplo de marketing que hayas visto hoy.'], { t: 'ciclo', p: ['entender', 'crear valor', 'comunicar', 'vender', 'medir'] }, '¿Por qué compras una marca y no otra?');
  un('mkt', 'mkt_cliente', B, 'El cliente ideal y los segmentos', 'mkt_conv', ['Un segmento es un grupo de clientes con necesidades parecidas.', 'El cliente ideal (buyer persona) se describe con edad, lugar, hábitos, problemas y dónde se informa.', 'Hablar a todos es hablar a nadie: un mensaje concreto convence más.', 'Las entrevistas y las encuestas cortas son la forma más barata de conocer al cliente.'], ['segmento', 'buyer persona', 'necesidad', 'encuesta', 'nicho'], 'V:Un nicho es un segmento pequeño y concreto.|F:Conviene dirigirse a todo el mundo.|V:Entrevistar clientes es barato y útil.', ['Describe al cliente ideal de un negocio de tu barrio.', 'Escribe cinco preguntas para entrevistar a un cliente.'], { t: 'mapa', c: 'Cliente ideal', r: ['edad y lugar', 'hábitos', 'problema', 'dónde se informa', 'qué le frena'] }, '¿Quién es exactamente la persona que te compraría?');
  un('mkt', 'mkt_4p', B, 'Las 4 P: producto, precio, plaza y promoción', 'mkt_cpm', ['Producto: lo que ofreces y el problema que resuelve.', 'Precio: lo que cobras, que debe cubrir costos y ser coherente con el valor percibido.', 'Plaza: dónde y cómo llega el producto al cliente.', 'Promoción: cómo lo das a conocer.'], ['producto', 'precio', 'plaza', 'promoción', 'mezcla de marketing'], 'V:Las 4 P forman la mezcla de marketing.|F:La plaza es solo la tienda física.|V:El precio también comunica calidad.', ['Analiza las 4 P de un producto que uses a diario.', '¿Qué P cambiarías para vender más?'], { t: 'mapa', c: 'Mezcla de marketing', r: ['producto', 'precio', 'plaza', 'promoción'] }, '¿Qué cambia si subes el precio de un producto?');
  un('mkt', 'mkt_marca', B, 'Marca y propuesta de valor', 'mkt_ltv', ['La marca es la idea que la gente tiene de ti: nombre, logotipo, colores, tono y experiencia.', 'La propuesta de valor dice en una frase qué ofreces, a quién y por qué eres distinto.', 'La coherencia construye confianza: mismo tono y misma calidad en todos los canales.', 'Una marca fuerte permite cobrar más que la competencia.'], ['marca', 'identidad visual', 'tono', 'propuesta de valor', 'confianza'], 'V:La marca incluye la experiencia del cliente.|F:La marca es solo el logotipo.|V:La coherencia genera confianza.', ['Escribe la propuesta de valor de tu proyecto en una frase.', 'Elige tres palabras que describan el tono de tu marca.'], { t: 'flujo', p: ['nombre', 'propuesta', 'identidad', 'tono', 'experiencia'] }, '¿Qué recuerda la gente de ti cuando cierra el móvil?');
  un('mkt', 'mkt_redes', B, 'Redes sociales', 'mkt_ctr', ['Cada red tiene un público y un formato: vídeo corto, fotos, textos profesionales o comunidades.', 'El alcance es cuántas personas ven una publicación; la interacción, cuántas reaccionan.', 'Publicar con constancia importa más que publicar mucho un día.', 'Las redes atraen, pero la venta se cierra con buena atención por mensaje.'], ['alcance', 'interacción', 'seguidores', 'formato', 'calendario editorial'], 'V:Cada red tiene su formato.|F:Muchos seguidores garantizan ventas.|V:La constancia mejora el alcance.', ['Haz un calendario de publicaciones para dos semanas.', 'Calcula la tasa de interacción de una publicación.'], { t: 'ciclo', p: ['planificar', 'crear', 'publicar', 'responder', 'medir'] }, '¿Por qué un vídeo de 15 segundos puede llegar a miles de personas?');
  un('mkt', 'mkt_contenido', B, 'Marketing de contenidos', 'mkt_conv', ['El contenido útil (guías, trucos, vídeos) atrae a clientes que buscan resolver un problema.', 'Se trata de enseñar antes de vender.', 'Un buen contenido responde a una pregunta real del cliente.', 'Un mismo contenido se puede reutilizar en formatos distintos: artículo, vídeo corto, carrusel y correo.'], ['contenido', 'valor', 'formato', 'reutilizar', 'autoridad'], 'V:El contenido útil atrae clientes.|F:Todo el contenido debe ser un anuncio.|V:Un contenido se puede reutilizar.', ['Escribe cinco preguntas que se hacen tus clientes.', 'Convierte una de ellas en un guion de vídeo de 30 segundos.'], { t: 'flujo', p: ['pregunta del cliente', 'respuesta útil', 'formato', 'publicación', 'contacto'] }, '¿Qué pregunta de tus clientes podrías responder hoy?');
  un('mkt', 'mkt_seo', B, 'Buscadores (SEO)', 'mkt_ctr', ['El SEO son las técnicas para aparecer en los primeros resultados de los buscadores sin pagar.', 'Se empieza por las palabras que escribe el cliente cuando busca.', 'Cuentan el contenido útil, la velocidad de la web y los enlaces de otras páginas.', 'Una ficha de negocio en los mapas ayuda mucho a los comercios locales.'], ['SEO', 'palabra clave', 'posicionamiento', 'enlace', 'ficha local'], 'V:El SEO no se paga por clic.|F:Basta con repetir mucho una palabra.|V:La ficha local ayuda a los comercios.', ['Lista diez búsquedas que haría tu cliente.', 'Revisa la ficha de un comercio en un mapa en línea.'], { t: 'flujo', p: ['palabras clave', 'contenido', 'técnica', 'enlaces', 'posición'] }, '¿Qué escribirías en el buscador para encontrar tu negocio?');
  un('mkt', 'mkt_anuncios', B, 'Publicidad pagada', 'mkt_cpc', ['Los anuncios digitales se pagan por mil impresiones (CPM), por clic (CPC) o por resultado.', 'El CTR es el porcentaje de personas que hacen clic tras ver el anuncio.', 'Se segmenta por edad, lugar e intereses para no pagar por quien no comprará.', 'Se prueban dos versiones del anuncio y se deja la que funciona mejor (prueba A/B).'], ['CPM', 'CPC', 'CTR', 'segmentación', 'prueba A/B'], 'V:CTR = clics ÷ impresiones.|F:Un anuncio caro siempre funciona mejor.|V:La prueba A/B compara dos versiones.', ['Calcula el CPC de una campaña.', 'Diseña dos versiones de un anuncio para compararlas.'], { t: 'flujo', p: ['objetivo', 'público', 'anuncio', 'presupuesto', 'resultado'] }, '¿Cuánto cuesta que una persona haga clic en tu anuncio?');
  un('mkt', 'mkt_email', B, 'Correo y mensajería', 'mkt_email', ['Una lista de contactos propia no depende de ninguna red social.', 'Se pide permiso antes de enviar: la ley de protección de datos lo exige.', 'La tasa de apertura mide cuántos abren el correo; la de clics, cuántos pulsan el enlace.', 'La mensajería sirve para atención y avisos, no para enviar publicidad sin permiso.'], ['lista', 'permiso', 'tasa de apertura', 'boletín', 'automatización'], 'V:Hay que pedir permiso para enviar correos.|F:Comprar listas de correos es buena idea.|V:La lista propia no depende de una red.', ['Escribe el asunto de un correo para tus clientes.', 'Calcula la tasa de apertura de un envío.'], { t: 'ciclo', p: ['captar', 'dar la bienvenida', 'enviar valor', 'ofrecer', 'medir'] }, '¿Qué pasaría si mañana cerrara tu red social favorita?');
  un('mkt', 'mkt_embudo', B, 'El embudo de ventas', 'mkt_conv', ['El embudo muestra cómo una persona pasa de conocerte a comprar.', 'En cada paso se pierde gente: de mil que ven, pocos compran.', 'La tasa de conversión es el porcentaje que pasa al siguiente paso.', 'Mejorar un paso del embudo multiplica las ventas finales.'], ['embudo', 'conversión', 'atracción', 'consideración', 'cierre'], 'V:En cada paso del embudo se pierde gente.|F:La conversión se mide en euros.|V:Mejorar un paso sube las ventas.', ['Dibuja el embudo de una tienda en línea.', 'Calcula la conversión de visitas a ventas.'], { t: 'flujo', p: ['ven', 'visitan', 'se interesan', 'compran', 'repiten'] }, '¿Cuántas personas tienen que ver tu producto para que una lo compre?');
  un('mkt', 'mkt_metricas', B, 'Métricas y rentabilidad', 'mkt_roas', ['El ROAS divide los ingresos entre lo gastado en anuncios.', 'El CAC es lo que cuesta conseguir un cliente nuevo.', 'El valor del cliente (LTV) suma lo que gasta durante toda la relación.', 'Una campaña es rentable cuando el LTV supera claramente al CAC.'], ['ROAS', 'CAC', 'LTV', 'rentabilidad', 'panel de datos'], 'V:ROAS = ingresos ÷ gasto.|F:El CAC incluye lo que gasta el cliente.|V:Conviene que el LTV supere al CAC.', ['Calcula el ROAS de una campaña.', 'Compara el CAC con el LTV de un negocio.'], { t: 'mapa', c: 'Métricas', r: ['alcance', 'CTR', 'conversión', 'CAC', 'LTV', 'ROAS'] }, '¿Cómo sabes si un anuncio te hizo ganar o perder dinero?');
  un('mkt', 'mkt_ingresos', B, 'Cómo se generan ingresos con el marketing', 'mkt_freelance', ['Se puede trabajar en una empresa o por cuenta propia (freelance).', 'Servicios habituales: gestión de redes, anuncios, diseño de contenido, correo y tiendas en línea.', 'Otras vías: afiliación (comisión por venta), cursos y productos digitales propios.', 'Los ingresos dependen de cuántos clientes atiendes, la tarifa y las horas que te lleva cada uno.'], ['freelance', 'tarifa', 'afiliación', 'cliente mensual', 'portafolio'], 'V:La afiliación paga una comisión por venta.|F:Para empezar hace falta una agencia grande.|V:El portafolio demuestra lo que sabes hacer.', ['Calcula tus ingresos con tres clientes al mes.', '¿Qué servicio ofrecerías primero y por qué?'], { t: 'flujo', p: ['aprender', 'practicar', 'portafolio', 'primer cliente', 'crecer'] }, '¿Cuántos clientes necesitarías para vivir del marketing?');
  un('mkt', 'mkt_ruta', B, 'Aprender marketing desde cero', 'mkt_freelance', ['Se empieza por lo básico: cliente, mensaje y un solo canal.', 'Practicar con un negocio real (familia, barrio, un proyecto propio) enseña más que la teoría.', 'Hay cursos gratuitos de las propias plataformas de anuncios y buscadores.', 'En 90 días se puede tener un portafolio con tres casos medidos.'], ['ruta de aprendizaje', 'práctica', 'caso', 'certificado', 'portafolio'], 'V:Practicar con un negocio real enseña mucho.|F:Hay que dominar todos los canales a la vez.|V:Un portafolio con resultados convence.', ['Diseña tu plan de aprendizaje de 90 días.', 'Elige el negocio con el que vas a practicar.'], { t: 'flujo', p: ['semana 1–4: bases', 'semana 5–8: un canal', 'semana 9–12: caso real', 'portafolio'] }, '¿Qué podrías aprender en 90 días empezando hoy?');

  /* ─────────── IA desde cero ─────────── */
  un('ia', 'ia_que', B, 'Qué es la inteligencia artificial', 'ia_precision', ['La inteligencia artificial son programas que aprenden patrones de los datos para reconocer, predecir o generar.', 'No piensa como una persona: calcula lo más probable a partir de lo que ha visto.', 'Está en el móvil, los buscadores, los mapas, el correo y los traductores.', 'Puede equivocarse: siempre hay que revisar lo que produce.'], ['inteligencia artificial', 'datos', 'patrón', 'predicción', 'modelo'], 'V:La IA aprende patrones de los datos.|F:La IA nunca se equivoca.|V:Usamos IA cada día sin darnos cuenta.', ['Escribe tres usos de la IA que veas en tu día a día.', '¿Por qué hay que revisar lo que hace una IA?'], { t: 'flujo', p: ['datos', 'entrenamiento', 'modelo', 'respuesta', 'revisión'] }, '¿Cuántas veces has usado IA hoy sin saberlo?');
  un('ia', 'ia_historia', B, 'Breve historia de la IA', 'ia_precision', ['En 1950 Alan Turing propuso una prueba para saber si una máquina parece inteligente.', 'El nombre «inteligencia artificial» se usó por primera vez en 1956.', 'En 2012 las redes neuronales profundas dieron un salto en el reconocimiento de imágenes.', 'Desde 2022 las IA que conversan y generan texto e imágenes llegaron al gran público.'], ['prueba de Turing', 'red neuronal', 'aprendizaje profundo', 'IA generativa', 'línea del tiempo'], 'V:El término se acuñó en 1956.|F:La IA se inventó en 2022.|V:Turing propuso su prueba en 1950.', ['Haz una línea del tiempo con cinco momentos de la IA.', '¿Qué cambió en 2022?'], { t: 'flujo', p: ['1950 Turing', '1956 nombre', '1997 ajedrez', '2012 imágenes', '2022 chat'] }, '¿Qué tienen en común una partida de ajedrez de 1997 y tu móvil?');
  un('ia', 'ia_aprende', B, 'Cómo aprende una máquina', 'ia_precision', ['Se le muestran muchos ejemplos con la respuesta correcta y ajusta sus cálculos para acertar más.', 'Una parte de los datos se guarda para comprobar si aprendió o solo memorizó.', 'La precisión es el porcentaje de aciertos en esos datos de prueba.', 'Si los datos tienen errores o sesgos, el modelo los aprende.'], ['entrenamiento', 'datos de prueba', 'precisión', 'sesgo', 'red neuronal'], 'V:Los sesgos de los datos pasan al modelo.|F:Con pocos ejemplos siempre aprende bien.|V:Los datos de prueba no se usan para entrenar.', ['Calcula la precisión de un modelo.', '¿Qué pasaría si solo le enseñas fotos de gatos negros?'], { t: 'ciclo', p: ['ejemplos', 'predice', 'compara', 'ajusta', 'prueba'] }, '¿Cómo aprende una máquina a distinguir un perro de un gato?');
  un('ia', 'ia_generativa', B, 'IA generativa: texto, imagen y voz', 'ia_tiempo', ['La IA generativa crea contenido nuevo: textos, imágenes, música, voz o código.', 'Los modelos de lenguaje predicen la siguiente palabra a partir de muchísimos textos.', 'Puede inventar datos con total seguridad: se llama alucinación.', 'Sirve de borrador y ayuda; la decisión y la revisión son tuyas.'], ['IA generativa', 'modelo de lenguaje', 'alucinación', 'borrador', 'multimodal'], 'V:Puede inventar datos falsos.|F:Todo lo que genera es verdad.|V:Sirve como borrador.', ['Pide a una IA un texto y marca qué corregirías.', '¿Qué es una alucinación?'], { t: 'flujo', p: ['instrucción', 'modelo', 'borrador', 'revisión', 'versión final'] }, '¿Puede una máquina escribir un poema?');
  un('ia', 'ia_prompts', B, 'Escribir buenas instrucciones (prompts)', 'ia_tiempo', ['Una buena instrucción dice el papel, la tarea, el contexto y el formato de la respuesta.', 'Cuanto más concreto es lo que pides, mejor es el resultado.', 'Se mejora conversando: se pide que corrija, amplíe o cambie el tono.', 'Dar un ejemplo de lo que quieres ayuda mucho.'], ['prompt', 'rol', 'contexto', 'formato', 'iteración'], 'V:Dar un ejemplo mejora la respuesta.|F:Cuanto más corta la instrucción, mejor.|V:Se puede pedir que corrija.', ['Reescribe «hazme un texto» como una buena instrucción.', 'Compara dos respuestas a dos instrucciones distintas.'], { t: 'flujo', p: ['rol', 'tarea', 'contexto', 'formato', 'ejemplo'] }, '¿Por qué la misma pregunta da respuestas tan distintas?');
  un('ia', 'ia_texto', B, 'IA para escribir, resumir y estudiar', 'ia_tiempo', ['Resume textos largos, propone esquemas y corrige ortografía y estilo.', 'Explica un tema de otra forma o con un ejemplo más sencillo.', 'Puede hacerte preguntas para repasar antes de un examen.', 'Copiar sin entender no enseña: úsala para aprender, no para evitar aprender.'], ['resumen', 'esquema', 'corrección', 'repaso', 'autoría'], 'V:Puede generar preguntas de repaso.|F:Entregar lo que escribe la IA como propio es correcto.|V:Explica un tema de varias formas.', ['Pide un resumen de un tema y compáralo con tus apuntes.', 'Pide cinco preguntas de repaso y contéstalas.'], { t: 'ciclo', p: ['leo', 'pregunto', 'resumo', 'me examino', 'repaso'] }, '¿Te puede ayudar una IA a estudiar sin copiar?');
  un('ia', 'ia_imagen', B, 'IA para imágenes y diseño', 'ia_costo', ['Genera imágenes a partir de una descripción en texto.', 'Conviene describir estilo, colores, encuadre y luz.', 'Hay que revisar manos, textos y detalles, donde suele fallar.', 'Revisa las condiciones de uso antes de usar una imagen en un negocio.'], ['imagen generada', 'estilo', 'encuadre', 'derechos', 'retoque'], 'V:Conviene describir el estilo.|F:Toda imagen generada se puede usar sin condiciones.|V:Suele fallar en los detalles.', ['Describe con detalle la imagen de un producto.', '¿Qué revisarías antes de publicarla?'], { t: 'flujo', p: ['idea', 'descripción', 'generar', 'elegir', 'retocar'] }, '¿Cómo describirías con palabras una foto perfecta de tu producto?');
  un('ia', 'ia_datos', B, 'IA con hojas de cálculo y datos', 'ia_precision', ['Ayuda a escribir fórmulas, limpiar datos y hacer gráficos.', 'Encuentra patrones en ventas, gastos o notas.', 'Hay que comprobar los cálculos con un ejemplo sencillo.', 'No se deben subir datos personales de otras personas sin permiso.'], ['hoja de cálculo', 'fórmula', 'gráfico', 'patrón', 'datos personales'], 'V:Hay que comprobar sus cálculos.|F:Se pueden subir datos de clientes sin permiso.|V:Ayuda a escribir fórmulas.', ['Pide una fórmula para sumar las ventas de un mes y compruébala.', '¿Qué datos no subirías nunca a una IA?'], { t: 'flujo', p: ['datos', 'pregunta', 'fórmula', 'gráfico', 'conclusión'] }, '¿Qué te contarían tus gastos del mes si pudieran hablar?');
  un('ia', 'ia_automatiza', B, 'Automatizar tareas', 'ia_tiempo', ['Automatizar es dejar que una herramienta haga sola una tarea repetitiva.', 'Ejemplos: responder preguntas frecuentes, ordenar correos, crear informes semanales.', 'Se empieza por la tarea que más tiempo quita y siempre se hace igual.', 'Hay que medir el tiempo antes y después para saber si compensa.'], ['automatización', 'tarea repetitiva', 'flujo de trabajo', 'tiempo ahorrado', 'regla'], 'V:Conviene medir el tiempo ahorrado.|F:Todo se debe automatizar.|V:Las tareas repetitivas son las mejores candidatas.', ['Lista tres tareas repetitivas de tu semana.', 'Calcula las horas que ahorrarías al mes.'], { t: 'flujo', p: ['tarea', 'medir', 'automatizar', 'revisar', 'ahorro'] }, '¿Qué tarea repites cada semana que podría hacerse sola?');
  un('ia', 'ia_etica', B, 'Uso responsable: sesgos, privacidad y verdad', 'ia_precision', ['Los sesgos de los datos pueden producir decisiones injustas.', 'No se comparten datos personales ni secretos en herramientas públicas.', 'Se verifica en fuentes fiables antes de dar algo por cierto.', 'Se indica cuándo un texto o imagen se ha hecho con IA; varias leyes ya lo exigen.'], ['sesgo', 'privacidad', 'verificación', 'transparencia', 'ley de IA'], 'V:Los sesgos pueden causar injusticias.|F:Se pueden compartir contraseñas con una IA.|V:Hay que verificar en fuentes fiables.', ['Busca un ejemplo de sesgo en una IA.', 'Escribe tres normas de uso responsable para tu clase.'], { t: 'mapa', c: 'Uso responsable', r: ['verificar', 'proteger datos', 'evitar sesgos', 'decir que es IA', 'decidir tú'] }, '¿Te fiarías de una noticia escrita por una máquina?');
  un('ia', 'ia_trabajo', B, 'La IA en el trabajo y cómo ganar dinero con ella', 'ia_costo', ['La IA cambia tareas dentro de muchos empleos más que eliminar empleos enteros.', 'Quien sabe usarla hace en menos tiempo el mismo trabajo.', 'Se pueden ofrecer servicios: contenido para comercios, atención automatizada, análisis de datos o formación.', 'Una herramienta de pago compensa si el tiempo ahorrado vale más que la suscripción.'], ['productividad', 'servicio', 'suscripción', 'valor de la hora', 'nuevo empleo'], 'V:Compensa si el tiempo ahorrado vale más que su precio.|F:La IA elimina todos los empleos.|V:Se pueden ofrecer servicios con IA.', ['Calcula si una suscripción te compensa.', '¿Qué servicio con IA ofrecerías a un comercio?'], { t: 'flujo', p: ['aprender', 'probar', 'medir ahorro', 'ofrecer', 'cobrar'] }, '¿Cuánto vale una hora de tu tiempo?');
  un('ia', 'ia_ruta', B, 'Aprender a trabajar con IA desde cero', 'ia_tiempo', ['Semana 1: probar una IA conversacional con tareas reales.', 'Semana 2: aprender a escribir instrucciones y a revisar respuestas.', 'Semana 3: usarla con documentos, hojas de cálculo e imágenes.', 'Semana 4: automatizar una tarea y medir el tiempo ahorrado.'], ['plan de 30 días', 'práctica diaria', 'portafolio', 'herramienta', 'hábito'], 'V:Practicar a diario crea el hábito.|F:Hace falta saber programar para empezar.|V:Medir el ahorro demuestra el valor.', ['Escribe tu plan de 30 días.', 'Elige la primera tarea real que harás con IA.'], { t: 'flujo', p: ['semana 1: probar', 'semana 2: instrucciones', 'semana 3: documentos', 'semana 4: automatizar'] }, '¿Qué sabrías hacer dentro de 30 días si empiezas hoy?');

  /* ─────────── generadores ─────────── */
  var MARCAS = ['una tienda de ropa', 'una cafetería', 'una academia', 'un taller de velas', 'una peluquería', 'una tienda en línea de jabones', 'un gimnasio', 'una pastelería'];
  var TAREAS = [['redactar correos a clientes', 90], ['preparar publicaciones para redes', 120], ['resumir informes', 60], ['responder preguntas frecuentes', 150], ['ordenar datos de ventas', 80], ['preparar presentaciones', 100]];
  var GEN = {
    mkt_ctr: function (u, C, r) { var imp = P(r, [2000, 4000, 5000, 8000, 12000]), cl = Math.round(imp * P(r, [.8, 1.2, 1.5, 2, 3]) / 100); return it('corta', 'Un anuncio de ' + P(r, MARCAS) + ' se mostró ' + n(imp, C) + ' veces y recibió ' + cl + ' clics. ¿Cuál es su CTR?', n(pc(cl, imp), C) + ' %', { ac: [pc(cl, imp)], x: 'CTR = clics ÷ impresiones × 100 = ' + cl + ' ÷ ' + n(imp, C) + ' × 100 = ' + n(pc(cl, imp), C) + ' %.' }); },
    mkt_cpc: function (u, C, r) { var g = m(P(r, [50, 80, 120, 200]), C), cl = P(r, [100, 160, 250, 400]), v = Math.round(g / cl * 100) / 100; return it('corta', 'Una campaña gastó ' + $(g, C) + ' y consiguió ' + cl + ' clics. ¿Cuánto costó cada clic (CPC)?', $(v, C), { ac: [v, n(v, C)], x: 'CPC = gasto ÷ clics = ' + $(g, C) + ' ÷ ' + cl + ' = ' + $(v, C) + '.' }); },
    mkt_cpm: function (u, C, r) { var imp = P(r, [10000, 20000, 25000, 40000]), g = m(P(r, [30, 60, 90, 150]), C), v = Math.round(g / imp * 1000 * 100) / 100; return it('corta', 'Mostrar un anuncio ' + n(imp, C) + ' veces costó ' + $(g, C) + '. ¿Cuál es el costo por mil impresiones (CPM)?', $(v, C), { ac: [v, n(v, C)], x: 'CPM = gasto ÷ impresiones × 1000 = ' + $(g, C) + ' ÷ ' + n(imp, C) + ' × 1000 = ' + $(v, C) + '.' }); },
    mkt_conv: function (u, C, r) { var vis = P(r, [500, 800, 1200, 2000, 3000]), ven = Math.round(vis * P(r, [1, 1.5, 2, 2.5, 4]) / 100); return it('corta', 'La web de ' + P(r, MARCAS) + ' recibió ' + n(vis, C) + ' visitas y ' + ven + ' compras. ¿Cuál es la tasa de conversión?', n(pc(ven, vis), C) + ' %', { ac: [pc(ven, vis)], x: 'Conversión = compras ÷ visitas × 100 = ' + ven + ' ÷ ' + n(vis, C) + ' × 100 = ' + n(pc(ven, vis), C) + ' %.' }); },
    mkt_roas: function (u, C, r) { var g = m(P(r, [100, 150, 250, 400]), C), k = P(r, [2, 2.5, 3, 4, 5]), ing = Math.round(g * k); return it('corta', 'Se invirtieron ' + $(g, C) + ' en anuncios y generaron ' + $(ing, C) + ' en ventas. ¿Cuál es el ROAS?', n(k, C), { ac: [k], x: 'ROAS = ingresos ÷ gasto = ' + $(ing, C) + ' ÷ ' + $(g, C) + ' = ' + n(k, C) + '. Por cada unidad invertida vuelven ' + n(k, C) + '.' }); },
    mkt_cac: function (u, C, r) { var g = m(P(r, [200, 300, 500, 800]), C), c = P(r, [10, 20, 25, 40]), v = Math.round(g / c * 100) / 100; return it('corta', 'En un mes ' + P(r, MARCAS) + ' gastó ' + $(g, C) + ' en marketing y consiguió ' + c + ' clientes nuevos. ¿Cuál es su CAC?', $(v, C), { ac: [v, n(v, C)], x: 'CAC = gasto ÷ clientes nuevos = ' + $(g, C) + ' ÷ ' + c + ' = ' + $(v, C) + '.' }); },
    mkt_ltv: function (u, C, r) { var t = m(P(r, [15, 20, 30, 45]), C), f = P(r, [1, 2, 3]), me = P(r, [6, 12, 18, 24]), v = t * f * me; return it('corta', 'Un cliente gasta de media ' + $(t, C) + ' por compra, compra ' + f + ' ' + (f === 1 ? 'vez' : 'veces') + ' al mes y sigue ' + me + ' meses. ¿Cuál es su valor (LTV)?', $(v, C), { ac: [v, n(v, C)], x: 'LTV = ticket × compras al mes × meses = ' + $(t, C) + ' × ' + f + ' × ' + me + ' = ' + $(v, C) + '.' }); },
    mkt_email: function (u, C, r) { var e = P(r, [400, 800, 1000, 1500]), a = Math.round(e * P(r, [18, 22, 25, 30, 35]) / 100); return it('corta', 'Se envió un boletín a ' + n(e, C) + ' contactos y lo abrieron ' + a + '. ¿Cuál es la tasa de apertura?', n(pc(a, e), C) + ' %', { ac: [pc(a, e)], x: 'Apertura = abiertos ÷ enviados × 100 = ' + a + ' ÷ ' + n(e, C) + ' × 100 = ' + n(pc(a, e), C) + ' %.' }); },
    mkt_freelance: function (u, C, r) { var k = P(r, [2, 3, 4, 5]), t = m(P(r, [250, 300, 400]), C), h = m(P(r, [40, 60, 80]), C), g = k * t - h; return it('corta', 'Gestionas las redes de ' + k + ' comercios y cobras ' + $(t, C) + ' al mes a cada uno. Tus herramientas cuestan ' + $(h, C) + ' al mes. ¿Cuánto ganas al mes?', $(g, C), { ac: [g, n(g, C)], x: 'Ganancia = clientes × tarifa − herramientas = ' + k + ' × ' + $(t, C) + ' − ' + $(h, C) + ' = ' + $(g, C) + '.' }); },
    ia_tiempo: function (u, C, r) { var T = P(r, TAREAS), red = P(r, [30, 40, 50, 60]), s = P(r, [4, 4, 5]), ah = Math.round(T[1] * red / 100 * s * 4 / 60 * 10) / 10; return it('corta', 'Dedicas ' + T[1] + ' minutos ' + s + ' días a la semana a ' + T[0] + '. Con IA tardas un ' + red + ' % menos. ¿Cuántas horas ahorras en 4 semanas?', n(ah, C) + ' h', { ac: [ah], x: T[1] + ' min × ' + red + '/100 × ' + s + ' días × 4 semanas = ' + Math.round(T[1] * red / 100 * s * 4) + ' min ≈ ' + n(ah, C) + ' h.' }); },
    ia_costo: function (u, C, r) { var s = m(20, C), hv = m(P(r, [8, 10, 12, 15]), C), hr = P(r, [2, 3, 5, 8]), val = hv * hr, ok = val > s; return it('corta', 'Una herramienta de IA cuesta ' + $(s, C) + ' al mes y te ahorra ' + hr + ' horas. Si tu hora vale ' + $(hv, C) + ', ¿cuánto ganas o pierdes al mes al pagarla?', $(val - s, C), { ac: [val - s, n(val - s, C)], x: 'Valor ahorrado = ' + hr + ' × ' + $(hv, C) + ' = ' + $(val, C) + '; menos la suscripción: ' + $(val, C) + ' − ' + $(s, C) + ' = ' + $(val - s, C) + (ok ? '. Compensa.' : '. No compensa.') }); },
    ia_precision: function (u, C, r) { var t = P(r, [200, 400, 500, 800, 1000]), a = Math.round(t * P(r, [82, 88, 91, 94, 97]) / 100); return it('corta', 'Un modelo clasificó ' + t + ' fotos de prueba y acertó ' + a + '. ¿Cuál es su precisión? ¿Cuántas falló?', n(pc(a, t), C) + ' %; ' + (t - a), { ac: [pc(a, t)], x: 'Precisión = aciertos ÷ total × 100 = ' + a + ' ÷ ' + t + ' × 100 = ' + n(pc(a, t), C) + ' %. Falló ' + t + ' − ' + a + ' = ' + (t - a) + '.' }); }
  };

  var SABER = {
    mkt: [['Las 4 P', 'E. Jerome McCarthy propuso en 1960 agrupar el marketing en producto, precio, plaza y promoción.'], ['Mezcla de marketing', 'Neil Borden popularizó la expresión «marketing mix» en la década de 1950.'], ['El manual de Kotler', 'Philip Kotler publicó «Marketing Management» en 1967; sigue siendo un manual de referencia en muchas universidades.'], ['El modelo AIDA', 'A finales del siglo XIX se atribuyó a E. St. Elmo Lewis la secuencia atención, interés, deseo y acción.'], ['El primer banner', 'En 1994 la revista HotWired publicó uno de los primeros anuncios en forma de banner en internet.'], ['El primer correo masivo', 'En 1978 Gary Thuerk envió el que se considera el primer correo publicitario masivo, a unos 400 usuarios de ARPANET.'], ['Anuncios en el buscador', 'Google lanzó su sistema de anuncios AdWords en el año 2000; hoy se llama Google Ads.'], ['PageRank', 'Larry Page y Sergey Brin describieron en 1998 PageRank, que ordenaba las páginas según los enlaces que recibían.'], ['Net Promoter Score', 'Fred Reichheld presentó en 2003 el NPS: preguntar cuánto recomendaría un cliente la marca, del 0 al 10.'], ['Retener cuesta menos', 'Según un artículo de Harvard Business Review de 2014, conseguir un cliente nuevo cuesta entre 5 y 25 veces más que retener uno.'], ['El logotipo de Coca-Cola', 'Frank Robinson escribió en 1886 el nombre de Coca-Cola en la letra caligráfica que la marca aún usa.'], ['Comercio en línea en América Latina', 'En 2025 el comercio electrónico equivalía al 15,9 % de las ventas minoristas en América Latina, por encima del 8,4 % mundial (AMVO 2026).']],
    ia: [['La prueba de Turing', 'Alan Turing propuso en 1950, en «Computing Machinery and Intelligence», un juego para saber si una máquina parece pensar.'], ['El nombre', 'La expresión «inteligencia artificial» se usó en la propuesta de la conferencia de Dartmouth de 1956, organizada por John McCarthy y otros.'], ['El perceptrón', 'Frank Rosenblatt presentó en 1958 el perceptrón, una de las primeras redes neuronales artificiales.'], ['ELIZA', 'Joseph Weizenbaum creó en 1966 ELIZA, un programa que conversaba imitando a un terapeuta.'], ['Deep Blue', 'En 1997 el ordenador Deep Blue de IBM ganó un encuentro de ajedrez al campeón mundial Garri Kaspárov.'], ['El salto de 2012', 'En 2012 la red AlexNet redujo mucho los errores en el concurso ImageNet de reconocimiento de imágenes.'], ['AlphaGo', 'En 2016 AlphaGo, de DeepMind, venció 4 a 1 al campeón de go Lee Sedol.'], ['El transformer', 'En 2017 investigadores de Google publicaron «Attention Is All You Need», la arquitectura en la que se basan los modelos de lenguaje actuales.'], ['ChatGPT', 'ChatGPT se abrió al público el 30 de noviembre de 2022 y llevó la IA conversacional a millones de personas.'], ['Nobel para la IA', 'En 2024 el Nobel de Física premió a John Hopfield y Geoffrey Hinton por sus trabajos en redes neuronales, y el de Química a Demis Hassabis y John Jumper (AlphaFold) junto a David Baker.'], ['La ley europea', 'El Reglamento de Inteligencia Artificial de la Unión Europea entró en vigor el 1 de agosto de 2024 y se aplica por fases.'], ['IA en España', 'El 29 % de quienes emprenden en fase inicial en España ya usa la IA en su negocio (Informe GEM España 2025-2026).']]
  };
  if (LB && LB.SABER) { LB.SABER.mkt = SABER.mkt; LB.SABER.ia = SABER.ia; }

  ED.registrar({
    materias: [{ id: 'mkt', n: 'Marketing digital', ico: '📣', prodDef: 'libro' }, { id: 'ia', n: 'IA desde cero', ico: '🤖', prodDef: 'libro' }],
    unidades: U, generadores: GEN
  });
  function sinRepetir(res) {
    var C = res.C, visto = {}, keys = Object.keys(GEN).filter(function (k) { return k.indexOf(C.mat + '_') === 0; });
    res.pages.forEach(function (p, i) {
      if (!p.items || !p.items.length) return;
      var nuevos = [];
      p.items.forEach(function (x, j) {
        var k = x && x.e; if (!k || !visto[k]) { if (k) visto[k] = 1; nuevos.push(x); return; }
        var r = H.rng(H.hash(C.mat + ':' + i + ':' + j + ':' + (C.semilla || 1)));
        for (var t = 0; t < 40; t++) { var gk = t < 10 && p.u && GEN[p.u.g] ? p.u.g : keys[Math.floor(r() * keys.length)], y = null; try { y = GEN[gk](p.u, C, r); } catch (e) {} if (y && y.e && !visto[y.e]) { visto[y.e] = 1; nuevos.push(y); return; } }
      });
      p.items.length = 0; Array.prototype.push.apply(p.items, nuevos);
    });
  }
  var ens = ED.ensamblar;
  ED.ensamblar = function (cfg) { var res = ens(cfg); if (cfg && /^(mkt|ia)$/.test(cfg.materia)) try { sinRepetir(res); } catch (e) { console.warn('EU_MKT_IA', e); } return res; };
  window.EU_MKT_IA = { U: U, GEN: GEN, SABER: SABER };
})();
