/* b6_redes_sociales.js — materia «Redes sociales» (redes): ganar dinero con las redes paso a paso.
   · 14 unidades: qué son, nicho, estrategia, formatos, Facebook, Instagram, TikTok, Telegram/WhatsApp,
     anuncios y programas de creadores, afiliación, marcas/UGC, productos propios, métricas, legal.
   · Generadores con respuesta y proceso: tasa de interacción (por seguidores y por alcance), RPM/CPM,
     reparto de YouTube (55 %), anuncios de Telegram (50 %), comisión de afiliado, UGC, suscripciones,
     crecimiento, conversión del enlace, valor de la hora y reserva para impuestos.
   · Páginas propias: rs_modelos, rs_plataformas (requisitos reales de cada programa), rs_pasos (capturas
     esquemáticas paso a paso), rs_ingresos (tres escenarios con salario mínimo del país), rs_calc,
     rs_calendario, rs_kit, rs_legal (por país) y rs_plan90. Se insertan tras «Aprende» de cada unidad
     sustituyendo páginas de relleno, sin cambiar el número de páginas.
   · Visuales para páginas «vis» (EU_SVG.visual): embudo 3D, vistas por día, reparto de ingresos y pantalla.
   · Ideas para «Mi plan de negocio» (grupo 'redes') y SABER con fuente para «Para saber más».
   Expone EU_REDES.K (utilidades de maqueta) que reutiliza b6_comercio_electronico.js.
   Cargar después de b6_ideas_2026.js. */
(function () {
  'use strict';
  var ED = window.EU_EDITORIAL, LB = window.EU_LIBRO, SV = window.EU_SVG, EM = window.EU_EMPRE;
  if (!ED || window.EU_REDES) return;
  var H = ED.H, it = H.it, esc = H.esc, FX = (EM && EM.FX) || { es: 1, mx: 20, co: 4300, ar: 1300, cl: 1000, ve: 150, do: 65, us: 1.1 }, P = H.pick;
  function bon(v) { if (v <= 0) return 0; if (v < 10) return Math.round(v * 10) / 10; var p = Math.pow(10, Math.max(0, Math.floor(Math.log10(v)) - 1)); return Math.round(v / p) * p; }
  function m(eur, C) { return bon(eur * (FX[C.pk] || 1)); }
  function $(v, C) { return H.din(v, C); }
  function n(x, C) { return H.num(x, C); }
  function pc(a, b) { return Math.round(a / b * 1000) / 10; }
  function r2(x) { return Math.round(x * 100) / 100; }
  var NS = 'xmlns="http://www.w3.org/2000/svg"';

  /* ─────────── utilidades de maqueta (compartidas) ─────────── */
  var K = {
    tabla: function (C, cab, filas, o) {
      var T = C.T; o = o || {};
      return '<table style="width:100%;border-collapse:collapse;font-size:' + (o.fs || '.86em') + ';margin:0 0 4mm;break-inside:avoid"><tr>' + cab.map(function (c) { return '<th style="text-align:left;padding:1.6mm 2mm;border-bottom:0.5mm solid ' + T.acc + ';font-weight:700;color:' + T.acc + '">' + esc(c) + '</th>'; }).join('') + '</tr>' +
        filas.map(function (f, i) { return '<tr>' + f.map(function (c, j) { return '<td style="padding:1.6mm 2mm;border-bottom:1px solid ' + T.soft + ';vertical-align:top;' + (j === 0 ? 'font-weight:600;' : '') + (o.num && j > 0 ? 'font-variant-numeric:tabular-nums;' : '') + '">' + (String(c).charAt(0) === '<' ? c : esc(c)) + '</td>'; }).join('') + '</tr>'; }).join('') + (o.total ? '<tr>' + o.total.map(function (c) { return '<td style="padding:1.8mm 2mm;font-weight:700;border-top:0.5mm solid ' + T.ink + '">' + esc(c) + '</td>'; }).join('') + '</tr>' : '') + '</table>';
    },
    caja: function (C, t, html, alt) { var T = C.T; return '<div style="border:0.4mm solid ' + (alt ? T.acc2 : T.soft) + ';border-radius:' + (T.r || 0) + 'px;padding:3mm 4mm;margin:0 0 4mm;break-inside:avoid"><div style="font-weight:700;color:' + (alt ? T.acc2 : T.acc) + ';margin:0 0 1.5mm">' + esc(t) + '</div><div style="font-size:.93em;line-height:1.45">' + html + '</div></div>'; },
    p: function (s, st) { return '<p style="margin:0 0 3mm;text-wrap:pretty;line-height:1.5;' + (st || '') + '">' + esc(s) + '</p>'; },
    fuente: function (C, s) { return '<div style="font-size:.74em;opacity:.75;margin:-2mm 0 4mm">Fuente: ' + esc(s) + '</div>'; },
    lineas: function (C, k) { return H.lineas(k, C); },
    items: function (pg, C, modo, max) { return (pg.items || []).slice(0, max == null ? 9 : max).map(function (x, i) { return H.itemHTML(x, i, C, modo, 'x' + pg.num); }).join(''); },
    num: function (C, i) { var T = C.T; return '<span style="flex:none;width:6.5mm;height:6.5mm;border-radius:50%;background:' + T.acc2 + ';color:#fff;display:inline-flex;align-items:center;justify-content:center;font-weight:700;font-size:.85em">' + i + '</span>'; },
    pasos: function (C, a) { return '<div style="display:flex;flex-direction:column;gap:2.4mm;margin:0 0 4mm">' + a.map(function (s, i) { return '<div style="display:flex;gap:3mm;align-items:flex-start">' + K.num(C, i + 1) + '<div style="line-height:1.45">' + esc(s) + '</div></div>'; }).join('') + '</div>'; },
    grid: function (cols, html, gap) { return '<div style="display:grid;grid-template-columns:repeat(' + cols + ',minmax(0,1fr));gap:' + (gap || '4mm') + ';margin:0 0 4mm">' + html + '</div>'; },
    svg: function (w, h, body, max) { return '<svg ' + NS + ' viewBox="0 0 ' + w + ' ' + h + '" style="width:100%;max-width:' + (max || w) + 'px;height:auto;display:block;margin:0 auto">' + body + '</svg>'; },
    tx: function (x, y, s, o) { o = o || {}; return '<text x="' + x + '" y="' + y + '" text-anchor="' + (o.a || 'middle') + '" font-size="' + (o.s || 12) + '" font-family="' + esc(o.f || 'sans-serif') + '" font-weight="' + (o.w || 400) + '" fill="' + (o.c || '#222') + '">' + esc(s) + '</text>'; },
    d3: function (C) { return C.prem ? C.prem.dibujo === '3d' : (((C.cfg && C.cfg.acab) || {}).dibujo || '3d') === '3d'; },
    /* Pantalla de móvil esquemática (no reproduce ninguna app): filas [tipo, texto, marca] */
    movil: function (C, S) {
      var T = C.T, F = T.cuerpo, W = 170, Hh = 330, y = 58, out = '', ink = T.ink || '#222', marcas = [];
      out += '<rect x="3" y="3" width="164" height="324" rx="20" fill="#fff" stroke="' + ink + '" stroke-width="3"/><rect x="62" y="10" width="46" height="6" rx="3" fill="' + ink + '" opacity=".5"/>';
      out += '<rect x="12" y="24" width="146" height="26" rx="6" fill="' + T.soft + '"/>' + K.tx(85, 41, S.tit, { f: F, s: 11, w: 700, c: ink });
      (S.filas || []).forEach(function (f) {
        var t = f[0], s = f[1] || '', h = { img: 62, btn: 24, campo: 24, lin: 16, dato: 40, lista: 50, tab: 22 }[t] || 18;
        if (t === 'img') out += '<rect x="16" y="' + y + '" width="138" height="' + (h - 6) + '" rx="6" fill="' + T.soft + '" opacity=".6"/><path d="M16 ' + (y + h - 16) + ' l38 -24 l26 18 l22 -14 l52 20" fill="none" stroke="' + ink + '" stroke-width="1.5" opacity=".45"/>' + K.tx(85, y + 18, s, { f: F, s: 9.5, c: ink });
        else if (t === 'btn') out += '<rect x="16" y="' + y + '" width="138" height="' + (h - 4) + '" rx="' + (T.r ? 10 : 3) + '" fill="' + T.acc + '"/>' + K.tx(85, y + 14, s, { f: F, s: 10, w: 700, c: '#fff' });
        else if (t === 'campo') out += K.tx(18, y + 7, s, { f: F, s: 8, a: 'start', c: ink }) + '<rect x="16" y="' + (y + 9) + '" width="138" height="12" rx="3" fill="none" stroke="' + ink + '" stroke-width="1" opacity=".6"/>';
        else if (t === 'dato') out += '<rect x="16" y="' + y + '" width="138" height="' + (h - 4) + '" rx="6" fill="none" stroke="' + T.acc + '" stroke-width="1.5"/>' + K.tx(85, y + 22, s, { f: F, s: 15, w: 700, c: T.acc }) + K.tx(85, y + 33, f[3] || '', { f: F, s: 8, c: ink });
        else if (t === 'lista') { for (var q = 0; q < 3; q++) out += '<circle cx="24" cy="' + (y + 8 + q * 15) + '" r="5" fill="' + T.soft + '"/><rect x="34" y="' + (y + 5 + q * 15) + '" width="' + (110 - q * 18) + '" height="6" rx="3" fill="' + ink + '" opacity=".25"/>'; if (s) out += K.tx(154, y + 11, s, { f: F, s: 8, a: 'end', c: ink }); }
        else if (t === 'tab') { out += '<line x1="12" y1="' + y + '" x2="158" y2="' + y + '" stroke="' + ink + '" opacity=".25"/>'; for (var z = 0; z < 5; z++) out += '<rect x="' + (22 + z * 28) + '" y="' + (y + 6) + '" width="12" height="10" rx="2" fill="' + (z === 4 ? T.acc : ink) + '" opacity="' + (z === 4 ? 1 : .35) + '"/>'; }
        else out += K.tx(18, y + 11, s, { f: F, s: 9, a: 'start', c: ink });
        if (f[2]) marcas.push([y + h / 2 - 2, f[2]]);
        y += h;
      });
      marcas.forEach(function (mk) { out += '<circle cx="158" cy="' + mk[0] + '" r="9" fill="' + T.acc2 + '" stroke="#fff" stroke-width="2"/>' + K.tx(158, mk[0] + 4, String(mk[1]), { f: F, s: 10, w: 700, c: '#fff' }); });
      return '<svg ' + NS + ' viewBox="0 0 ' + W + ' ' + Hh + '" style="width:100%;height:auto;display:block">' + out + '</svg>';
    },
    /* Embudo en 3D (o plano): etapas [[etiqueta, valor]] */
    embudo: function (C, E) {
      var T = C.T, F = T.cuerpo, d3 = K.d3(C), pal = SV && SV.paleta ? SV.paleta(C) : [T.acc, T.acc2], W = 560, fila = 48, Hh = E.length * fila + 24, out = '', max = E[0][1];
      E.forEach(function (e, i) {
        var w0 = 380 * (1 - i * .15), w1 = 380 * (1 - (i + 1) * .15), x0 = 200 - w0 / 2, y = 10 + i * fila, col = pal[i % pal.length];
        if (d3) out += '<ellipse cx="200" cy="' + (y + fila - 4) + '" rx="' + (w1 / 2) + '" ry="7" fill="' + (SV && SV.osc ? SV.osc(col, .3) : col) + '"/>';
        out += '<path d="M' + x0 + ' ' + y + ' L' + (x0 + w0) + ' ' + y + ' L' + (200 + w1 / 2) + ' ' + (y + fila - 4) + ' L' + (200 - w1 / 2) + ' ' + (y + fila - 4) + ' Z" fill="' + col + '" opacity="' + (d3 ? 1 : .85) + '"/>';
        if (d3) out += '<ellipse cx="200" cy="' + y + '" rx="' + (w0 / 2) + '" ry="7" fill="#fff" opacity=".35"/>';
        out += K.tx(200, y + 28, H.num(e[1], C), { f: F, s: 15, w: 700, c: '#fff' }) + K.tx(410, y + 22, e[0], { f: F, s: 13, w: 700, a: 'start', c: T.ink }) + (i ? K.tx(410, y + 38, H.num(pc(e[1], E[i - 1][1]), C) + ' % del paso anterior', { f: F, s: 10.5, a: 'start', c: T.ink }) : '');
      });
      return K.svg(W, Hh, out, 540);
    },
    /* Barras horizontales [[etiqueta, valor, texto]] */
    barrasH: function (C, R, o) {
      o = o || {}; var T = C.T, F = T.cuerpo, W = 560, fila = 30, Hh = R.length * fila + 10, max = Math.max.apply(null, R.map(function (x) { return x[1]; })) || 1, out = '', d3 = K.d3(C);
      R.forEach(function (x, i) { var w = Math.max(4, 300 * x[1] / max), y = 6 + i * fila; out += K.tx(150, y + 15, x[0], { f: F, s: 11.5, a: 'end', c: T.ink }) + (d3 ? '<polygon points="' + (160 + w) + ',' + y + ' ' + (168 + w) + ',' + (y - 5) + ' ' + (168 + w) + ',' + (y + 15) + ' ' + (160 + w) + ',' + (y + 20) + '" fill="' + (SV && SV.osc ? SV.osc(i % 2 ? T.acc2 : T.acc, .3) : T.acc) + '"/><polygon points="160,' + y + ' ' + (160 + w) + ',' + y + ' ' + (168 + w) + ',' + (y - 5) + ' 168,' + (y - 5) + '" fill="#fff" opacity=".5"/>' : '') + '<rect x="160" y="' + y + '" width="' + w + '" height="20" fill="' + (i % 2 ? T.acc2 : T.acc) + '"/>' + K.tx(176 + w, y + 15, x[2] || H.num(x[1], C), { f: F, s: 11, a: 'start', w: 700, c: T.ink }); });
      return K.svg(W, Hh, out, o.max || 540);
    },
    /* Página de pasos con capturas esquemáticas */
    paginaPasos: function (pg, C, modo, F) {
      var T = C.T, cols = F.pant.length;
      return H.cabecera(C, pg) + H.h1(C, esc(F.t)) + K.p(F.intro) +
        '<div style="display:grid;grid-template-columns:repeat(' + cols + ',minmax(0,1fr));gap:4mm;margin:0 0 4mm;max-width:' + (cols * 37) + 'mm">' + F.pant.map(function (S, i) { return '<div style="display:flex;flex-direction:column;gap:1.5mm"><div style="font-size:.78em;font-weight:700;color:' + T.acc + '">Pantalla ' + (i + 1) + '</div>' + K.movil(C, S) + '</div>'; }).join('') + '</div>' +
        H.h2(C, 'Paso a paso') + K.pasos(C, F.pasos) + K.caja(C, 'Ojo', esc(F.ojo), true) + K.items(pg, C, modo, 1) + H.folio(C, pg);
    }
  };

  /* ─────────── unidades ─────────── */
  var U = [];
  function un(id, t, g, i, k, vf, q, f, h, pz) { U.push({ m: 'redes', id: id, b: 'sec bach fp adu'.split(' '), t: t, g: g, i: i, k: k, vf: vf.split('|').map(function (s) { return [s.slice(2), s.charAt(0) === 'V']; }), q: q, f: f, h: h, pz: pz, plus: true }); }
  un('rs_que', 'Qué son las redes sociales y cómo se gana dinero', 'redes_hora', ['Una red social es una plataforma donde las personas publican, comparten y conversan; su negocio es vender publicidad a partir del tiempo que pasamos en ella.', 'Quien crea contenido puede ganar dinero de seis formas: anuncios, afiliación, acuerdos con marcas, productos propios, servicios y aportaciones del público.', 'Según Goldman Sachs (2023) hay unos 50 millones de creadores en el mundo, pero solo cerca del 4 % gana más de 100.000 dólares al año.', 'Los acuerdos con marcas son la mayor fuente: alrededor del 70 % de los ingresos de los creadores en las encuestas que cita ese informe.', 'Las redes son terreno alquilado: si cambia el algoritmo o cierra la cuenta, se pierde el canal. Por eso conviene tener una lista de contactos propia.'], ['red social', 'creador', 'monetización', 'audiencia', 'algoritmo'], 'V:Las redes viven de la publicidad.|F:La mayoría de creadores gana más de 100.000 dólares al año.|V:Conviene tener una lista de contactos propia.', ['¿Qué seis formas de ganar dinero con las redes conoces?', '¿Por qué se dice que las redes son terreno alquilado?'], { t: 'flujo', p: ['crear', 'atraer', 'ganar confianza', 'monetizar', 'medir'] }, '¿Cuánto vale una hora de tu tiempo delante del móvil?', ['rs_modelos']);
  un('rs_nicho', 'Nicho y público objetivo', 'redes_crec', ['Un nicho es un tema concreto para un público concreto: «recetas de 15 minutos para quien trabaja» funciona mejor que «cocina».', 'El público objetivo se describe con edad, lugar, problema, lo que ya sabe y en qué red pasa su tiempo.', 'Un perfil claro dice en la primera línea a quién ayudas y cómo; así quien llega decide en segundos si te sigue.', 'Conviene elegir un nicho que puedas sostener un año: algo que te interese y en lo que puedas aportar.', 'Antes de lanzarte, revisa diez cuentas del nicho: qué publican, qué comentarios reciben y qué falta.'], ['nicho', 'público objetivo', 'perfil', 'propuesta de valor', 'competencia'], 'V:Un nicho concreto se entiende mejor.|F:Conviene hablar de todo para llegar a más gente.|V:La biografía debe decir a quién ayudas.', ['Escribe tu nicho en una frase: tema + público + resultado.', 'Analiza tres cuentas de tu nicho: ¿qué les falta?'], { t: 'mapa', c: 'Mi público', r: ['edad y lugar', 'problema', 'qué sabe', 'dónde está', 'qué le frena'] }, '¿Quién exactamente se detendría a ver tu vídeo?', ['rs_pasos:perfil']);
  un('rs_contenido', 'Estrategia de contenido', 'redes_eng', ['Una estrategia reparte el contenido en pilares: enseñar, inspirar, mostrar el detrás de escena y vender.', 'Una proporción habitual es publicar mucho más contenido útil que promocional, para que el público no sienta que solo se le vende.', 'El calendario editorial fija qué se publica cada día; la constancia importa más que la cantidad.', 'Cada pieza debe tener un objetivo: alcance, interacción, seguidores o clics en el enlace.', 'Reutilizar multiplica: un vídeo largo da varios cortos, un carrusel y un correo.'], ['pilar de contenido', 'calendario editorial', 'objetivo', 'constancia', 'reutilizar'], 'V:Cada publicación debe tener un objetivo.|F:Hay que vender en todas las publicaciones.|V:Un contenido se puede reutilizar en varios formatos.', ['Define cuatro pilares de contenido para tu nicho.', 'Planifica una semana de publicaciones.'], { t: 'ciclo', p: ['planificar', 'crear', 'publicar', 'responder', 'medir'] }, '¿Qué publicarías si solo pudieras subir tres cosas a la semana?', ['rs_calendario']);
  un('rs_formatos', 'Formatos: vídeo corto, carrusel, directo y texto', 'redes_engalc', ['El vídeo corto vertical es el formato de mayor alcance en TikTok, Reels y Shorts.', 'Los primeros tres segundos deciden si alguien se queda: se empieza por el resultado o por la pregunta.', 'El carrusel de imágenes enseña paso a paso y se guarda mucho, lo que indica que el contenido es útil.', 'Los directos crean cercanía y permiten responder preguntas y vender en el momento.', 'Un guion de 30 segundos tiene cuatro partes: gancho, problema, solución y llamada a la acción.'], ['gancho', 'guion', 'carrusel', 'directo', 'llamada a la acción'], 'V:Los primeros segundos deciden si alguien se queda.|F:Un carrusel no se puede guardar.|V:El guion corto tiene gancho, problema, solución y llamada.', ['Escribe el guion de un vídeo de 30 segundos.', 'Convierte ese guion en un carrusel de cinco imágenes.'], { t: 'flujo', p: ['gancho 0–3 s', 'problema', 'solución', 'prueba', 'llamada'] }, '¿Qué te hace dejar de deslizar el dedo?', ['rs_pasos:guion']);
  un('rs_facebook', 'Facebook: páginas, grupos y Marketplace', 'redes_conv', ['Una página de Facebook es la cara pública de un negocio o creador; un perfil personal no debe usarse para vender.', 'Los grupos reúnen comunidades por tema o barrio: aportar primero da confianza para ofrecer después.', 'Marketplace permite vender artículos a gente cercana; conviene publicar fotos claras, precio y zona de entrega.', 'Meta ofrece programas de monetización de contenido que dependen del país y de la cuenta; se consultan en su panel profesional.', 'Facebook sigue siendo la red con más usuarios adultos en muchos países de habla hispana.'], ['página', 'grupo', 'Marketplace', 'panel profesional', 'comunidad'], 'V:Un grupo aporta primero y vende después.|F:Conviene vender desde el perfil personal.|V:Marketplace sirve para ventas cercanas.', ['Diseña la página de un negocio: nombre, foto, botón y primeras tres publicaciones.', '¿Qué grupo de tu ciudad sería útil para tu nicho?'], { t: 'flujo', p: ['crear página', 'completar datos', 'publicar', 'unirse a grupos', 'vender'] }, '¿Dónde busca tu vecina algo de segunda mano?', ['rs_pasos:fb']);
  un('rs_instagram', 'Instagram: Reels, carruseles e historias', 'redes_eng', ['La cuenta profesional (de creador o de empresa) da acceso a estadísticas, botones de contacto y herramientas de venta.', 'Los Reels buscan alcance, los carruseles enseñan y las historias mantienen la relación diaria con quien ya te sigue.', 'Los destacados del perfil funcionan como un menú: precios, opiniones, preguntas frecuentes.', 'Instagram no reparte de forma general ingresos por anuncios: se gana con marcas, afiliación, suscripciones y ventas propias.', 'Las colaboraciones pagadas deben llevar la etiqueta de colaboración pagada o un aviso claro.'], ['cuenta profesional', 'Reels', 'historias', 'destacados', 'colaboración pagada'], 'V:La cuenta profesional da estadísticas.|F:Instagram paga a todos los creadores por sus vistas.|V:Las colaboraciones pagadas deben indicarse.', ['Organiza los destacados de un perfil de negocio.', 'Calcula la tasa de interacción de tres publicaciones.'], { t: 'mapa', c: 'Instagram', r: ['Reels: alcance', 'carrusel: enseñar', 'historias: relación', 'destacados: menú', 'mensajes: venta'] }, '¿Qué miras primero cuando entras en un perfil?', ['rs_pasos:ig']);
  un('rs_tiktok', 'TikTok: vídeo corto y Creator Rewards', 'redes_cpm', ['TikTok muestra los vídeos a personas que no te siguen: una cuenta nueva puede llegar a miles de personas con un solo vídeo.', 'El Programa Creator Rewards exige 18 años, cuenta personal, 10.000 seguidores y 100.000 visualizaciones en los últimos 30 días.', 'Solo pagan los vídeos originales de más de un minuto, y el programa está disponible en algunos países, entre ellos México y Estados Unidos.', 'La inscripción se hace desde el perfil: menú, TikTok Studio y Programa Creator Rewards; la respuesta llega en unos tres días.', 'TikTok no publica una tarifa fija por vista: el pago depende de la calidad, la originalidad y la región.'], ['Para ti', 'Creator Rewards', 'TikTok Studio', 'visualización cualificada', 'retención'], 'V:TikTok muestra vídeos a quien no te sigue.|F:Todos los vídeos cortos cobran en Creator Rewards.|V:Hacen falta 10.000 seguidores.', ['¿Cuáles son los requisitos del programa Creator Rewards?', 'Calcula lo que se ganaría con 200.000 vistas a un RPM de ejemplo.'], { t: 'flujo', p: ['publicar', 'retener', 'Para ti', 'seguidores', 'monetizar'] }, '¿Por qué un vídeo de alguien desconocido te aparece en TikTok?', ['rs_pasos:tiktok', 'rs_plataformas']);
  un('rs_telegram', 'Telegram y WhatsApp: canales y comunidades', 'redes_tg', ['Un canal envía mensajes a muchas personas a la vez; un grupo permite que todos conversen.', 'En Telegram los canales públicos con 1.000 suscriptores o más pueden recibir el 50 % de lo que Telegram ingresa por los anuncios que muestra en ellos (desde 2024).', 'Los canales de WhatsApp también permiten difundir novedades; los mensajes llegan a quien se une voluntariamente.', 'Las comunidades de pago dan contenido exclusivo por una cuota mensual.', 'Nunca se añade a nadie sin permiso ni se comparten sus datos: además de molesto, lo prohíben las leyes de protección de datos.'], ['canal', 'grupo', 'suscriptor', 'comunidad de pago', 'permiso'], 'V:Un canal difunde a muchas personas a la vez.|F:Se puede añadir a cualquiera sin permiso.|V:Telegram reparte el 50 % de los anuncios en canales grandes.', ['Crea el plan de un canal: nombre, tema y frecuencia.', 'Calcula los ingresos de una comunidad de pago.'], { t: 'flujo', p: ['crear canal', 'describir', 'invitar', 'publicar', 'monetizar'] }, '¿Por qué un canal propio es más seguro que depender del algoritmo?', ['rs_pasos:tg']);
  un('rs_anuncios', 'Ingresos por anuncios y programas de creadores', 'redes_yt', ['El CPM es lo que paga el anunciante por mil impresiones; el RPM, lo que recibe el creador por cada mil vistas.', 'YouTube entrega a los creadores el 55 % de los ingresos por anuncios en vídeos largos y el 45 % en Shorts.', 'Para entrar en su Programa de Socios hacen falta 1.000 suscriptores y 4.000 horas de visualización en 12 meses, o 10 millones de vistas de Shorts en 90 días.', 'El RPM cambia mucho según el país del público, el tema y la época del año: finanzas paga más que humor, y diciembre más que enero.', 'Con anuncios hacen falta muchas vistas para ingresos modestos; por eso casi nadie vive solo de ellos.'], ['CPM', 'RPM', 'Programa de Socios', 'reparto', 'visualizaciones'], 'V:El RPM es lo que recibe el creador por mil vistas.|F:YouTube entrega el 100 % de los anuncios.|V:El RPM depende del país y del tema.', ['¿Qué diferencia hay entre CPM y RPM?', 'Calcula cuántas vistas harían falta para ganar el salario mínimo.'], { t: 'flujo', p: ['anunciante paga', 'plataforma cobra', 'reparto', 'creador recibe', 'impuestos'] }, '¿Cuántas vistas necesitarías para pagar el alquiler?', ['rs_calc']);
  un('rs_afiliados', 'Afiliación: comisiones por venta', 'redes_com', ['En la afiliación recomiendas un producto con un enlace propio y cobras una comisión cuando alguien compra.', 'Las comisiones dependen de la tienda y la categoría: en las grandes tiendas en línea suelen ir de un pequeño porcentaje a alrededor del 10 %.', 'Lo que se gana es clics × tasa de conversión × precio × comisión: pocas ventas en un nicho caro pueden valer más que muchas baratas.', 'Solo se recomienda lo que se ha probado o investigado: la confianza es el capital del creador.', 'La ley obliga a avisar de que el enlace es de afiliado.'], ['enlace de afiliado', 'comisión', 'conversión', 'cookie', 'aviso'], 'V:Hay que avisar de que el enlace es de afiliado.|F:La comisión es igual en todas las categorías.|V:Se cobra cuando alguien compra.', ['Calcula la comisión de un mes con tus propios datos.', '¿Qué producto de tu nicho recomendarías y por qué?'], { t: 'flujo', p: ['elegir producto', 'crear enlace', 'publicar con aviso', 'clic', 'comisión'] }, '¿Cuántas cosas has comprado por la recomendación de alguien?', ['rs_pasos:afiliado']);
  un('rs_marcas', 'Colaboraciones con marcas y contenido UGC', 'redes_ugc', ['Una marca paga por publicar su producto en tu cuenta (patrocinio) o por vídeos que ella publicará en la suya (UGC).', 'Para el UGC no hacen falta muchos seguidores: la marca paga por la calidad del vídeo, no por tu audiencia.', 'El kit de medios resume quién eres, tu público, tus números y tus tarifas.', 'Una propuesta clara incluye entregables, fechas, derechos de uso, número de cambios y forma de pago.', 'Todo acuerdo se firma por escrito y se cobra, al menos en parte, por adelantado.'], ['patrocinio', 'UGC', 'kit de medios', 'derechos de uso', 'tarifa'], 'V:El UGC no exige muchos seguidores.|F:Los acuerdos con marcas no necesitan contrato.|V:El kit de medios resume tus números.', ['Prepara tu kit de medios.', 'Calcula tus ingresos con UGC en un mes.'], { t: 'flujo', p: ['kit de medios', 'propuesta', 'contrato', 'entrega', 'cobro'] }, '¿Por qué una marca pagaría por un vídeo que no se publica en tu cuenta?', ['rs_kit']);
  un('rs_productos', 'Vender productos y servicios propios', 'redes_sus', ['Con un producto propio te quedas con casi todo el margen: guías, plantillas, cursos, recetarios o productos físicos.', 'Los servicios (clases, asesorías, gestión de redes) se pueden vender desde el primer día y validan qué necesita el público.', 'Las suscripciones dan un ingreso mensual previsible; la plataforma suele quedarse una comisión.', 'La escalera de valor ofrece algo gratis, algo barato y algo completo, para que cada persona elija su paso.', 'Con pocos seguidores fieles se puede ganar más que con muchos que solo miran.'], ['producto digital', 'servicio', 'suscripción', 'escalera de valor', 'margen'], 'V:Un servicio se puede vender desde el primer día.|F:Hacen falta millones de seguidores para vender.|V:La suscripción da ingresos previsibles.', ['Diseña tu escalera de valor con tres escalones.', 'Calcula los ingresos netos de una suscripción.'], { t: 'flujo', p: ['gratis', 'barato', 'completo', 'suscripción', 'recomendación'] }, '¿Qué sabes hacer por lo que alguien te pagaría hoy?', ['rs_ingresos']);
  un('rs_metricas', 'Métricas que importan', 'redes_engalc', ['El alcance es cuántas personas distintas vieron la publicación; las impresiones, cuántas veces se mostró.', 'La tasa de interacción suma me gusta, comentarios, compartidos y guardados, y la divide entre seguidores o entre alcance.', 'La retención dice qué parte del vídeo se ve: si la gente se va en el segundo 2, falla el gancho.', 'Los clics en el enlace y las ventas son las métricas que pagan las facturas.', 'Se revisan una vez por semana y se cambia una sola cosa cada vez para saber qué funcionó.'], ['alcance', 'impresiones', 'tasa de interacción', 'retención', 'clic en el enlace'], 'V:El alcance cuenta personas distintas.|F:Las impresiones y el alcance son lo mismo.|V:Se cambia una cosa cada vez.', ['Calcula la tasa de interacción por alcance de tres publicaciones.', 'Diseña tu hoja semanal de métricas.'], { t: 'ciclo', p: ['medir', 'comparar', 'decidir', 'cambiar una cosa', 'medir'] }, '¿Cómo sabrías qué vídeo te trajo más clientes?', ['rs_pasos:metricas']);
  un('rs_legal', 'Aspectos legales, impuestos y plan de 90 días', 'redes_imp', ['La publicidad debe identificarse siempre: «publicidad», «colaboración pagada» o la etiqueta de la plataforma.', 'Los ingresos de las redes son ingresos gravables: hay que declararlos y, según el país, darse de alta como autónomo o en un régimen simplificado.', 'Las imágenes, músicas y textos de otros tienen derechos de autor: se usan las bibliotecas autorizadas de cada plataforma.', 'Los datos de seguidores y clientes se tratan con permiso y se guardan con cuidado.', 'Un plan de 90 días con metas medibles convierte la teoría en ingresos reales.'], ['publicidad identificada', 'impuestos', 'derechos de autor', 'protección de datos', 'plan de 90 días'], 'V:La publicidad debe identificarse.|F:Lo que se gana en redes no paga impuestos.|V:La música de otros tiene derechos.', ['Escribe cómo avisarías de una colaboración pagada.', 'Diseña tu plan de 90 días.'], { t: 'flujo', p: ['avisar publicidad', 'declarar ingresos', 'respetar derechos', 'proteger datos', 'plan'] }, '¿Qué pasa si una marca te paga y no lo dices?', ['rs_legal', 'rs_plan90']);

  /* ─────────── generadores ─────────── */
  var NICHOS = ['recetas rápidas', 'finanzas personales', 'manualidades', 'viajes baratos', 'ejercicio en casa', 'tecnología', 'maquillaje', 'jardinería', 'idiomas', 'mascotas'];
  var GEN = {
    redes_eng: function (u, C, r) { var s = P(r, [1200, 2500, 4000, 8000, 15000]), mg = Math.round(s * P(r, [2, 3, 4, 5]) / 100), co = Math.round(mg * P(r, [.05, .08, .1])), cp = Math.round(mg * P(r, [.03, .05])), gu = Math.round(mg * P(r, [.06, .1])), t = mg + co + cp + gu; return it('corta', 'Una cuenta de ' + P(r, NICHOS) + ' tiene ' + n(s, C) + ' seguidores. Una publicación recibió ' + mg + ' me gusta, ' + co + ' comentarios, ' + cp + ' compartidos y ' + gu + ' guardados. ¿Cuál es su tasa de interacción por seguidores?', n(pc(t, s), C) + ' %', { ac: [pc(t, s)], x: 'Interacciones = ' + mg + ' + ' + co + ' + ' + cp + ' + ' + gu + ' = ' + t + '. Tasa = ' + t + ' ÷ ' + n(s, C) + ' × 100 = ' + n(pc(t, s), C) + ' %.' }); },
    redes_engalc: function (u, C, r) { var a = P(r, [3000, 6000, 9000, 20000]), t = Math.round(a * P(r, [3, 4.5, 6, 8]) / 100); return it('corta', 'Un vídeo llegó a ' + n(a, C) + ' personas (alcance) y sumó ' + n(t, C) + ' interacciones. ¿Cuál es la tasa de interacción por alcance?', n(pc(t, a), C) + ' %', { ac: [pc(t, a)], x: 'Tasa por alcance = interacciones ÷ alcance × 100 = ' + n(t, C) + ' ÷ ' + n(a, C) + ' × 100 = ' + n(pc(t, a), C) + ' %.' }); },
    redes_cpm: function (u, C, r) { var v = P(r, [50000, 120000, 200000, 400000]), rpm = r2(m(P(r, [.3, .5, .8, 1.2]), C)), g = r2(v / 1000 * rpm); return it('corta', 'Un vídeo largo tuvo ' + n(v, C) + ' visualizaciones cualificadas. Si el RPM de ejemplo es ' + $(rpm, C) + ' por mil vistas, ¿cuánto se gana?', $(g, C), { ac: [g, n(g, C)], x: 'Ingreso = vistas ÷ 1000 × RPM = ' + n(v, C) + ' ÷ 1000 × ' + $(rpm, C) + ' = ' + $(g, C) + '. Es un RPM de ejemplo: la plataforma no publica una tarifa fija.' }); },
    redes_yt: function (u, C, r) { var a = m(P(r, [200, 400, 600, 1000]), C), sh = r() < .35, k = sh ? 45 : 55, g = r2(a * k / 100); return it('corta', 'Los anuncios de tus ' + (sh ? 'Shorts' : 'vídeos largos') + ' generaron ' + $(a, C) + ' en un mes. YouTube entrega al creador el ' + k + ' %. ¿Cuánto recibes?', $(g, C), { ac: [g, n(g, C)], x: 'Parte del creador = ' + $(a, C) + ' × ' + k + ' ÷ 100 = ' + $(g, C) + ' (YouTube: 55 % en vídeos largos, 45 % en Shorts).' }); },
    redes_tg: function (u, C, r) { var a = m(P(r, [40, 80, 150, 300]), C), g = r2(a / 2); return it('corta', 'Telegram ingresó ' + $(a, C) + ' por los anuncios que mostró en tu canal este mes. Si reparte el 50 % con el propietario, ¿cuánto te corresponde?', $(g, C), { ac: [g, n(g, C)], x: '50 % de ' + $(a, C) + ' = ' + $(a, C) + ' ÷ 2 = ' + $(g, C) + '. Solo aplica a canales públicos con al menos 1.000 suscriptores.' }); },
    redes_com: function (u, C, r) { var cl = P(r, [800, 1500, 3000, 5000]), cv = P(r, [1, 1.5, 2, 3]), pr = m(P(r, [25, 40, 60, 120]), C), k = P(r, [3, 4, 6, 8, 10]), vt = Math.round(cl * cv / 100), g = r2(vt * pr * k / 100); return it('corta', 'Tu enlace de afiliado recibió ' + n(cl, C) + ' clics; el ' + n(cv, C) + ' % compró un producto de ' + $(pr, C) + ' con una comisión del ' + k + ' %. ¿Cuánto ganas?', $(g, C), { ac: [g, n(g, C)], x: 'Ventas = ' + n(cl, C) + ' × ' + n(cv, C) + ' % = ' + vt + '. Comisión = ' + vt + ' × ' + $(pr, C) + ' × ' + k + ' % = ' + $(g, C) + '.' }); },
    redes_ugc: function (u, C, r) { var v = P(r, [4, 6, 8, 10, 12]), t = m(P(r, [60, 90, 120, 150]), C), h = m(P(r, [20, 30, 50]), C), g = v * t - h; return it('corta', 'Este mes entregas ' + v + ' vídeos UGC a ' + $(t, C) + ' cada uno. Tus gastos (atrezo, apps, internet) son ' + $(h, C) + '. ¿Cuánto ganas?', $(g, C), { ac: [g, n(g, C)], x: 'Ganancia = vídeos × tarifa − gastos = ' + v + ' × ' + $(t, C) + ' − ' + $(h, C) + ' = ' + $(g, C) + '.' }); },
    redes_sus: function (u, C, r) { var s = P(r, [40, 80, 120, 200]), p = m(P(r, [3, 5, 8]), C), k = P(r, [10, 20, 30]), g = r2(s * p * (100 - k) / 100); return it('corta', 'Tienes ' + s + ' suscriptores que pagan ' + $(p, C) + ' al mes. La plataforma se queda el ' + k + ' %. ¿Cuánto ingresas neto al mes?', $(g, C), { ac: [g, n(g, C)], x: 'Neto = ' + s + ' × ' + $(p, C) + ' × (100 − ' + k + ') ÷ 100 = ' + $(g, C) + '.' }); },
    redes_crec: function (u, C, r) { var s = P(r, [500, 1000, 2000, 3000]), g = P(r, [10, 15, 20]), me = 3, f = Math.round(s * Math.pow(1 + g / 100, me)); return it('corta', 'Una cuenta empieza con ' + n(s, C) + ' seguidores y crece un ' + g + ' % cada mes. ¿Cuántos tendrá dentro de ' + me + ' meses?', n(f, C), { ac: [f], x: n(s, C) + ' × ' + n(1 + g / 100, C) + '³ = ' + n(f, C) + ' (el crecimiento se acumula mes a mes).' }); },
    redes_conv: function (u, C, r) { var v = P(r, [2000, 5000, 8000]), cl = Math.round(v * P(r, [1, 2, 3]) / 100), ve = Math.max(1, Math.round(cl * P(r, [3, 5, 8]) / 100)); return it('corta', 'Tu publicación en Marketplace tuvo ' + n(v, C) + ' vistas, ' + cl + ' mensajes y ' + ve + ' ventas. ¿Qué porcentaje de los mensajes terminó en venta?', n(pc(ve, cl), C) + ' %', { ac: [pc(ve, cl)], x: 'Conversión = ventas ÷ mensajes × 100 = ' + ve + ' ÷ ' + cl + ' × 100 = ' + n(pc(ve, cl), C) + ' %.' }); },
    redes_hora: function (u, C, r) { var g = m(P(r, [300, 450, 600, 900]), C), h = P(r, [30, 40, 60, 80]), v = r2(g / h); return it('corta', 'En un mes ganaste ' + $(g, C) + ' con tus redes y dedicaste ' + h + ' horas a grabar, editar y responder. ¿Cuánto ganaste por hora?', $(v, C), { ac: [v, n(v, C)], x: 'Valor de la hora = ingresos ÷ horas = ' + $(g, C) + ' ÷ ' + h + ' = ' + $(v, C) + '. Compáralo con el salario mínimo por hora de tu país.' }); },
    redes_imp: function (u, C, r) { var g = m(P(r, [400, 800, 1200, 2000]), C), k = P(r, [15, 20, 25]), v = r2(g * k / 100); return it('corta', 'Este mes ingresaste ' + $(g, C) + ' por redes. Si apartas un ' + k + ' % para impuestos, ¿cuánto guardas?', $(v, C), { ac: [v, n(v, C)], x: g + ' × ' + k + ' ÷ 100 = ' + $(v, C) + '. El porcentaje real depende del país y de tu régimen: consulta la administración tributaria.' }); }
  };

  /* ─────────── datos por país (legal) ─────────── */
  var LEG = {
    es: ['España', 'Desde 2024, el Real Decreto 444/2024 trata como «usuarios de especial relevancia» a quienes ingresan 300.000 € o más al año con su actividad, superan 1 millón de seguidores en una plataforma (o 2 millones en total) y publican al menos 24 vídeos al año: deben inscribirse en un registro estatal y cumplir las normas de publicidad y protección de menores.', 'Agencia Tributaria (alta censal y, en su caso, autónomo en la Seguridad Social)'],
    mx: ['México', 'La publicidad debe ser veraz y distinguible (Ley Federal de Protección al Consumidor, vigilada por Profeco). Las plataformas digitales pueden retener ISR e IVA a quienes venden o prestan servicios a través de ellas.', 'SAT (régimen de plataformas tecnológicas o RESICO según el caso)'],
    co: ['Colombia', 'La Superintendencia de Industria y Comercio publicó una guía de buenas prácticas para la publicidad a través de influenciadores: la relación con la marca debe ser clara (#publicidad).', 'DIAN (RUT y régimen correspondiente)'],
    ar: ['Argentina', 'La Ley 24.240 de Defensa del Consumidor exige información clara y veraz; la publicidad encubierta puede considerarse engañosa.', 'ARCA (monotributo o régimen general)'],
    cl: ['Chile', 'La Ley 19.496 del consumidor prohíbe la publicidad engañosa; el SERNAC ha orientado que las colaboraciones pagadas se identifiquen.', 'SII (inicio de actividades y boletas de honorarios o boletas electrónicas)'],
    ve: ['Venezuela', 'La publicidad debe ser veraz. Revisa la normativa vigente de la SUNDDE y de CONATEL para contenidos y anuncios.', 'SENIAT (RIF y declaración de ingresos)'],
    do: ['República Dominicana', 'La Ley 358-05 de Protección al Consumidor (Pro Consumidor) exige publicidad veraz e identificable.', 'DGII (RNC y facturación electrónica según la Ley 32-23)'],
    us: ['Estados Unidos', 'Las guías de la FTC sobre recomendaciones y testimonios (actualizadas en 2023) exigen revelar de forma clara cualquier relación material con una marca: pago, producto gratis o comisión.', 'IRS (impuesto sobre el trabajo por cuenta propia; formulario 1099 de las plataformas)']
  };

  /* ─────────── flujos paso a paso ─────────── */
  var FLUJOS = {
    perfil: { t: 'Paso a paso: un perfil que se entiende en tres segundos', intro: 'Pantallas esquemáticas (no reproducen ninguna aplicación concreta). Sirven para cualquier red con perfil público.', pant: [{ tit: 'Perfil', filas: [['img', 'foto de cara o logotipo', 1], ['lin', 'Nombre + palabra clave', 2], ['lin', 'A quién ayudo y cómo', 3], ['lin', 'Prueba: resultado o dato'], ['btn', 'Enlace / Contacto', 4], ['lista', 'destacados']] }, { tit: 'Editar perfil', filas: [['campo', 'Nombre', 2], ['campo', 'Biografía', 3], ['campo', 'Enlace', 4], ['campo', 'Categoría'], ['btn', 'Guardar']] }, { tit: 'Destacados', filas: [['lista', 'Precios', 5], ['lista', 'Opiniones'], ['lista', 'Preguntas']] }], pasos: ['Usa una foto donde se vea tu cara o el logotipo, sin texto pequeño.', 'Pon en el nombre una palabra que la gente busca: «Ana | Recetas rápidas».', 'Escribe en la biografía a quién ayudas y cómo, en una línea.', 'Añade un único enlace a tu tienda, lista de correo o página de contacto.', 'Crea destacados que respondan a las preguntas que más te hacen.'], ojo: 'Si en tres segundos no se entiende de qué va tu cuenta, la persona se va. Pide a alguien que no te conozca que lea tu perfil y te diga qué ofreces.' },
    guion: { t: 'Paso a paso: guion de un vídeo de 30 segundos', intro: 'Cuatro fotogramas de un guion gráfico (storyboard). Cada pantalla es un tramo del vídeo.', pant: [{ tit: '0–3 s · gancho', filas: [['img', 'plano del resultado', 1], ['lin', 'Texto: «Cena en 10 minutos»'], ['lin', 'Voz: pregunta directa']] }, { tit: '3–15 s · problema', filas: [['img', 'plano de la situación', 2], ['lin', 'Texto: «Llegas cansada…»']] }, { tit: '15–25 s · solución', filas: [['img', 'pasos rápidos', 3], ['lista', '3 pasos']] }, { tit: '25–30 s · llamada', filas: [['img', 'plato final', 4], ['btn', 'Guárdalo y sígueme']] }], pasos: ['Empieza por el resultado o por una pregunta que tu público se hace.', 'Muestra el problema en pocas palabras y con una imagen que se reconozca.', 'Enseña la solución en tres pasos claros; corta todo lo que sobre.', 'Termina con una sola acción: guardar, seguir, comentar o ir al enlace.', 'Añade subtítulos: mucha gente ve los vídeos sin sonido.'], ojo: 'Mira la retención: si la mayoría se va antes del segundo 3, cambia el gancho antes que nada.' },
    fb: { t: 'Paso a paso: crear una página y publicar en Marketplace', intro: 'Pantallas esquemáticas. Los nombres de los menús pueden cambiar según la versión de la aplicación.', pant: [{ tit: 'Menú', filas: [['lista', ''], ['btn', 'Páginas', 1], ['lin', 'Marketplace', 4]] }, { tit: 'Crear página', filas: [['campo', 'Nombre de la página', 2], ['campo', 'Categoría', 2], ['campo', 'Biografía'], ['btn', 'Crear']] }, { tit: 'Tu página', filas: [['img', 'portada', 3], ['btn', 'Enviar mensaje', 3], ['lista', 'publicaciones']] }, { tit: 'Vender artículo', filas: [['img', 'fotos del artículo', 5], ['campo', 'Precio', 5], ['campo', 'Ubicación'], ['btn', 'Publicar', 6]] }], pasos: ['Abre el menú y entra en «Páginas».', 'Escribe el nombre del negocio y elige la categoría más precisa.', 'Añade foto, portada y un botón de acción (mensaje, llamar o comprar).', 'Para vender un artículo, entra en Marketplace y elige «Vender».', 'Sube varias fotos con buena luz, precio y zona de entrega.', 'Publica y responde rápido: la velocidad de respuesta decide muchas ventas.'], ojo: 'No vendas desde el perfil personal ni publiques el mismo anuncio en veinte grupos a la vez: la plataforma puede limitar tu cuenta.' },
    ig: { t: 'Paso a paso: pasar a cuenta profesional', intro: 'Pantallas esquemáticas. La cuenta profesional permite ver estadísticas y añadir botones de contacto.', pant: [{ tit: 'Perfil', filas: [['img', 'tu perfil'], ['btn', '☰ Menú', 1]] }, { tit: 'Configuración', filas: [['lista', ''], ['btn', 'Tipo de cuenta', 2]] }, { tit: 'Tipo de cuenta', filas: [['btn', 'Cambiar a profesional', 3], ['campo', 'Creador / Empresa', 4], ['campo', 'Categoría', 5]] }, { tit: 'Panel profesional', filas: [['dato', '12.480', 6, 'cuentas alcanzadas'], ['lista', 'estadísticas']] }], pasos: ['En tu perfil pulsa el menú (☰).', 'Entra en la opción del tipo de cuenta y herramientas.', 'Elige «Cambiar a cuenta profesional».', 'Selecciona «Creador» si eres una persona o «Empresa» si vendes productos o servicios.', 'Elige la categoría y decide si se muestra en el perfil.', 'A partir de ahí tendrás el panel profesional con alcance, interacciones y seguidores.'], ojo: 'Las estadísticas solo cuentan desde que la cuenta es profesional: cámbiala antes de empezar a medir.' },
    tiktok: { t: 'Paso a paso: solicitar el Programa Creator Rewards', intro: 'Ruta indicada por TikTok en su Creator Academy. Requisitos: 18 años, cuenta personal, 10.000 seguidores y 100.000 visualizaciones en 30 días.', pant: [{ tit: 'Perfil', filas: [['img', 'tu perfil'], ['btn', '☰ Menú', 1]] }, { tit: 'Menú', filas: [['lista', ''], ['btn', 'TikTok Studio', 2]] }, { tit: 'TikTok Studio', filas: [['dato', '100.000', 0, 'vistas en 30 días'], ['btn', 'Creator Rewards', 3]] }, { tit: 'Creator Rewards', filas: [['lista', 'requisitos'], ['btn', 'Solicitar', 4], ['lin', 'Respuesta en ~3 días', 5]] }], pasos: ['Ve a tu perfil y pulsa el botón Menú (☰).', 'Selecciona TikTok Studio.', 'Entra en «Programa Creator Rewards».', 'Presenta la solicitud si cumples los requisitos.', 'Espera la respuesta (unos tres días) y publica vídeos originales de más de un minuto.'], ojo: 'El programa solo está disponible en algunos países (entre ellos México y Estados Unidos). Duetos, uniones y vídeos de menos de un minuto no cobran.' },
    tg: { t: 'Paso a paso: crear un canal de Telegram', intro: 'Pantallas esquemáticas. Un canal difunde mensajes; los suscriptores no escriben en él.', pant: [{ tit: 'Chats', filas: [['lista', ''], ['btn', '✎ Nuevo mensaje', 1]] }, { tit: 'Nuevo', filas: [['lin', 'Nuevo grupo'], ['btn', 'Nuevo canal', 2]] }, { tit: 'Datos del canal', filas: [['img', 'foto del canal', 3], ['campo', 'Nombre', 3], ['campo', 'Descripción', 3]] }, { tit: 'Tipo de canal', filas: [['campo', 'Público / Privado', 4], ['campo', 't.me/tu_canal', 5], ['btn', 'Invitar', 6]] }], pasos: ['Pulsa el botón de nuevo mensaje.', 'Elige «Nuevo canal».', 'Pon foto, nombre y una descripción que diga qué recibirá quien se una.', 'Decide si es público (cualquiera lo encuentra) o privado (solo con enlace).', 'Elige un enlace corto y fácil: t.me/tu_canal.', 'Comparte el enlace en tus redes; nunca añadas a nadie sin su permiso.'], ojo: 'Los anuncios de Telegram solo reparten el 50 % en canales públicos con al menos 1.000 suscriptores, y el pago llega en la criptomoneda Toncoin.' },
    afiliado: { t: 'Paso a paso: tu primer enlace de afiliado', intro: 'Pantallas esquemáticas de un programa de afiliados cualquiera. Cada tienda tiene su propio panel.', pant: [{ tit: 'Programa de afiliados', filas: [['lin', 'Registro'], ['campo', 'Tus redes', 1], ['campo', 'Datos fiscales', 1], ['btn', 'Solicitar']] }, { tit: 'Buscar producto', filas: [['campo', 'Buscar…', 2], ['img', 'producto'], ['btn', 'Obtener enlace', 3]] }, { tit: 'Tu enlace', filas: [['campo', 'tienda.com/…?tag=tu_id', 3], ['btn', 'Copiar']] }, { tit: 'Panel', filas: [['dato', '1.240', 5, 'clics'], ['dato', '31', 5, 'ventas'], ['lista', 'comisiones']] }], pasos: ['Regístrate en el programa de afiliados de la tienda, con tus redes y datos fiscales.', 'Busca un producto que hayas probado o investigado.', 'Genera el enlace: incluye tu identificador para que la venta cuente como tuya.', 'Publícalo con el aviso «enlace de afiliado» o «#publicidad».', 'Revisa cada semana clics, ventas y comisiones en el panel.'], ojo: 'Muchas tiendas cierran la cuenta si no hay ventas en un plazo o si el enlace se usa sin aviso: lee las condiciones antes de empezar.' },
    metricas: { t: 'Paso a paso: tu revisión semanal de métricas', intro: 'Pantallas esquemáticas de un panel de estadísticas. Anota los datos en una hoja cada lunes.', pant: [{ tit: 'Estadísticas', filas: [['dato', '18.300', 1, 'cuentas alcanzadas'], ['dato', '1.090', 2, 'interacciones']] }, { tit: 'Contenido', filas: [['lista', 'mejor'], ['img', 'vídeo con más retención', 3]] }, { tit: 'Público', filas: [['dato', '62 %', 4, 'mujeres 25–34'], ['lista', 'ciudades']] }, { tit: 'Mi hoja', filas: [['campo', 'Semana'], ['campo', 'Alcance · Interacción'], ['campo', 'Clics · Ventas', 5], ['btn', 'Una mejora', 6]] }], pasos: ['Apunta el alcance de la semana.', 'Suma interacciones y calcula la tasa por alcance.', 'Busca el contenido con más retención y el que menos.', 'Mira quién te ve: edad, lugar y horas.', 'Anota clics en el enlace y ventas: son lo que paga.', 'Decide una sola mejora para la semana siguiente.'], ojo: 'Cambiar muchas cosas a la vez impide saber cuál funcionó. Una mejora por semana.' }
  };

  /* ─────────── páginas ─────────── */
  function smiTxt(C) { try { var s = EM && EM.smi ? EM.smi(C) : null; return s && isFinite(s.v) ? s : null; } catch (e) { return null; } }
  var PAG = {
    rs_modelos: function (pg, C, modo) {
      var T = C.T, a = m(500, C);
      return H.cabecera(C, pg) + H.h1(C, 'Seis formas de ganar dinero con las redes') + K.p('Cada modelo tiene quién paga, qué requisito pide y cuánto tarda en dar dinero. Lo habitual es combinar dos o tres.') +
        K.tabla(C, ['Modelo', 'Quién paga', 'Requisito', 'Ejemplo de cálculo'], [['Anuncios', 'La plataforma', 'Programa de creadores', 'vistas ÷ 1000 × RPM'], ['Afiliación', 'La tienda', 'Aviso de enlace', 'ventas × precio × comisión'], ['Marcas', 'La empresa', 'Kit de medios y contrato', 'publicaciones × tarifa'], ['UGC', 'La empresa', 'Portafolio de vídeos', 'vídeos × tarifa'], ['Productos propios', 'Tu público', 'Producto y forma de cobro', 'ventas × margen'], ['Servicios', 'Tu cliente', 'Saber hacer algo', 'horas × tarifa'], ['Suscripciones', 'Tu público', 'Contenido exclusivo', 'suscriptores × cuota − comisión']]) +
        K.grid(2, '<div>' + (SV && SV.sectores ? SV.sectores(C, { vals: [70, 30], cats: ['Acuerdos con marcas', 'Anuncios, suscripciones y otros'] }) : '') + K.fuente(C, 'Goldman Sachs Research, 2023 (encuestas a creadores).') + '</div><div>' + K.caja(C, 'Cuántos viven de esto', 'De unos 50 millones de creadores, solo cerca del 4 % gana más de 100.000 dólares al año (Goldman Sachs, 2023). Empieza con la meta de unos primeros ' + esc($(a, C)) + ' al mes, no con la de hacerte famoso.') + K.caja(C, 'Por qué funciona combinar', 'Si un mes baja el alcance, los servicios y productos propios siguen facturando: diversificar protege el ingreso.', true) + '</div>') + K.items(pg, C, modo) + H.folio(C, pg);
    },
    rs_plataformas: function (pg, C, modo) {
      var rpm = m(.8, C), meta = m(100, C), vis = Math.round(meta / rpm * 1000);
      return H.cabecera(C, pg) + H.h1(C, 'Qué paga cada plataforma') + K.p('Requisitos publicados por cada plataforma. Cambian a menudo: compruébalos en su página oficial antes de hacer planes.') +
        K.tabla(C, ['Plataforma', 'Programa', 'Requisitos', 'Qué reparte'], [['YouTube', 'Programa de Socios', '1.000 suscriptores y 4.000 horas en 12 meses, o 10 millones de vistas de Shorts en 90 días', '55 % de los anuncios en vídeos largos; 45 % en Shorts'], ['TikTok', 'Creator Rewards', '18 años, 10.000 seguidores, 100.000 vistas en 30 días; vídeos de más de 1 minuto; solo algunos países', 'Pago por vistas cualificadas; sin tarifa fija'], ['Facebook', 'Monetización de contenido', 'Según país y cuenta; se consulta en el panel profesional', 'Pagos por rendimiento de Reels, historias y publicaciones'], ['Instagram', 'Suscripciones, regalos, marcas', 'Cuenta profesional; requisitos por función y país', 'No reparte anuncios de forma general'], ['Telegram', 'Anuncios en canales', 'Canal público con 1.000 suscriptores o más', '50 % de los anuncios del canal, en Toncoin']], { fs: '.8em' }) +
        H.h2(C, '¿Cuántas vistas hacen falta para ganar ' + $(meta, C) + '?') + K.barrasH(C, [['RPM ' + $(r2(rpm / 2), C), Math.round(meta / (rpm / 2) * 1000)], ['RPM ' + $(rpm, C), vis], ['RPM ' + $(r2(rpm * 2), C), Math.round(meta / (rpm * 2) * 1000)]].map(function (x) { return [x[0], x[1], H.num(x[1], C) + ' vistas']; })) +
        K.caja(C, 'Cómo se lee', 'Con un RPM de ejemplo de ' + esc($(rpm, C)) + ' hacen falta ' + esc(H.num(vis, C)) + ' vistas para ganar ' + esc($(meta, C)) + '. Si el RPM se duplica, las vistas necesarias se reducen a la mitad.') + K.items(pg, C, modo) + H.folio(C, pg);
    },
    rs_pasos: function (pg, C, modo) { return K.paginaPasos(pg, C, modo, FLUJOS[pg.fl] || FLUJOS.perfil); },
    rs_ingresos: function (pg, C, modo) {
      var T = C.T, rpm = m(.8, C), s = smiTxt(C), E = [['Pequeña', 5000, 60000, 2, m(60, C), 1, 30], ['Mediana', 50000, 400000, 3, m(250, C), 3, 60], ['Grande', 500000, 3000000, 4, m(1500, C), 6, 110]];
      var filas = E.map(function (e) { var an = Math.round(e[2] / 1000 * rpm), af = Math.round(e[2] * .004 * e[3] / 100 * m(40, C) * .06), ma = e[4] * e[5], tot = an + af + ma; return [e[0] + ' (' + H.num(e[1], C) + ')', $(an, C), $(af, C), $(ma, C), $(tot, C), $(r2(tot / e[6]), C)]; });
      var tops = E.map(function (e) { var an = Math.round(e[2] / 1000 * rpm), af = Math.round(e[2] * .004 * e[3] / 100 * m(40, C) * .06); return an + af + e[4] * e[5]; });
      return H.cabecera(C, pg) + H.h1(C, '¿Cuánto se gana de verdad?') + K.p('Tres cuentas de ejemplo en ' + C.P.n + ', un mes cualquiera. Supuestos: RPM de ejemplo de ' + $(rpm, C) + ', el 0,4 % de las vistas hace clic en el enlace de afiliado, compra entre el 2 % y el 4 %, producto de ' + $(m(40, C), C) + ' con un 6 % de comisión, y tarifas de marca orientativas.') +
        K.tabla(C, ['Cuenta (seguidores)', 'Anuncios', 'Afiliación', 'Marcas', 'Total', 'Por hora'], filas, { fs: '.8em', num: true }) +
        K.barrasH(C, E.map(function (e, i) { return [e[0], tops[i], $(tops[i], C)]; }).concat(s ? [['Salario mínimo', s.v, $(s.v, C)]] : [])) + (s ? K.fuente(C, s.t) : '') +
        K.caja(C, 'Lo que dicen los números', 'Una cuenta pequeña rara vez vive de anuncios: su primer ingreso suele llegar de servicios, UGC o un producto propio. Por eso esta unidad empieza por lo que puedes vender hoy.') + K.items(pg, C, modo) + H.folio(C, pg);
    },
    rs_calc: function (pg, C, modo) {
      var rpm = m(.8, C), pr = m(40, C), fila = function (t, f, ej) { return K.caja(C, t, '<div style="font-family:' + C.T.tit + ';font-size:1.1em;margin:0 0 1.5mm">' + esc(f) + '</div><div>' + esc(ej) + '</div><div style="margin-top:2mm">Tu cuenta: ____________________________________________</div>'); };
      return H.cabecera(C, pg) + H.h1(C, 'Tres calculadoras que debes dominar') + K.p('Cópialas en una hoja de cálculo y rellénalas cada semana con tus datos reales.') +
        fila('Tasa de interacción', '(me gusta + comentarios + compartidos + guardados) ÷ seguidores × 100', 'Ejemplo: (240 + 18 + 12 + 30) ÷ 6.000 × 100 = 5 %. Por alcance: divide entre las personas alcanzadas.') +
        fila('Ingresos por anuncios', 'vistas ÷ 1000 × RPM', 'Ejemplo: 150.000 ÷ 1000 × ' + $(rpm, C) + ' = ' + $(r2(150 * rpm), C) + '. En YouTube el RPM ya descuenta la parte de la plataforma.') +
        fila('Comisión de afiliado', 'clics × conversión × precio × comisión', 'Ejemplo: 2.000 × 2 % × ' + $(pr, C) + ' × 6 % = ' + $(r2(40 * pr * .06), C) + '.') +
        fila('Valor de tu hora', 'ingresos del mes ÷ horas dedicadas', 'Si el resultado queda por debajo del salario mínimo por hora, revisa qué tareas no generan ingresos.') + K.items(pg, C, modo) + H.folio(C, pg);
    },
    rs_calendario: function (pg, C, modo) {
      var T = C.T, D = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'], ej = [['Enseñar', 'Vídeo corto', 'Alcance'], ['Detrás de escena', 'Historias', 'Relación'], ['Enseñar', 'Carrusel', 'Guardados'], ['Opinión de cliente', 'Reel', 'Confianza'], ['Oferta', 'Publicación + enlace', 'Clics'], ['Directo', 'Directo 20 min', 'Preguntas'], ['Descanso', 'Responder mensajes', 'Relación']];
      var celda = function (s, b) { return '<td style="padding:1.6mm;border:1px solid ' + T.soft + ';vertical-align:top;font-size:.8em;height:' + (b ? '13mm' : 'auto') + '">' + esc(s) + '</td>'; };
      return H.cabecera(C, pg) + H.h1(C, 'Calendario editorial de una semana') + K.p('Arriba, una semana de ejemplo; abajo, la tuya. Cada día tiene un pilar, un formato y un objetivo.') +
        '<table style="width:100%;border-collapse:collapse;margin:0 0 4mm"><tr><th></th>' + D.map(function (d) { return '<th style="font-size:.82em;color:' + T.acc + ';padding:1mm">' + d + '</th>'; }).join('') + '</tr>' + ['Pilar', 'Formato', 'Objetivo'].map(function (f, k) { return '<tr><th style="text-align:left;font-size:.8em;padding:1mm">' + f + '</th>' + ej.map(function (e) { return celda(e[k]); }).join('') + '</tr>'; }).join('') + '</table>' +
        H.h2(C, 'Mi semana') + '<table style="width:100%;border-collapse:collapse;margin:0 0 4mm"><tr><th></th>' + D.map(function (d) { return '<th style="font-size:.82em;color:' + T.acc + ';padding:1mm">' + d + '</th>'; }).join('') + '</tr>' + ['Pilar', 'Formato', 'Objetivo', 'Resultado'].map(function (f) { return '<tr><th style="text-align:left;font-size:.8em;padding:1mm">' + f + '</th>' + D.map(function () { return celda('', 1); }).join('') + '</tr>'; }).join('') + '</table>' +
        K.caja(C, 'Por qué funciona', 'Decidir el lunes qué se publica cada día evita improvisar y mantiene la constancia, que es lo que más valoran los algoritmos y el público.') + K.items(pg, C, modo) + H.folio(C, pg);
    },
    rs_kit: function (pg, C, modo) {
      var T = C.T, seg = 12000, al = 30000, ta = 4.6, base = m(90, C), tar = bon(seg / 1000 * base / 12 * (ta / 3)), ugc = m(120, C);
      return H.cabecera(C, pg) + H.h1(C, 'Tu kit de medios, paso a paso') + K.p('Una sola página que una marca pueda leer en un minuto. Ejemplo de una cuenta de ' + H.num(seg, C) + ' seguidores en ' + C.P.ciudades[0] + '.') +
        K.grid(2, '<div style="border:0.5mm solid ' + T.acc + ';border-radius:' + (T.r || 0) + 'px;padding:4mm"><div style="font-family:' + T.tit + ';font-size:1.4em;color:' + T.acc + '">Lucía · Recetas en 15 minutos</div><div style="font-size:.85em;margin:1mm 0 3mm">Cocina rápida para gente que trabaja · ' + esc(C.P.ciudades[0]) + '</div>' +
          K.tabla(C, ['Dato', 'Valor'], [['Seguidores', H.num(seg, C)], ['Alcance medio mensual', H.num(al, C)], ['Tasa de interacción', H.num(ta, C) + ' %'], ['Público', '72 % mujeres, 25–44 años'], ['Reel patrocinado', $(tar, C)], ['Vídeo UGC (sin publicar)', $(ugc, C)]], { fs: '.82em' }) + '</div>' +
          '<div>' + K.pasos(C, ['Quién eres y a quién hablas, en una línea.', 'Tres números: seguidores, alcance e interacción.', 'Quién te ve: edad, lugar, intereses.', 'Tres trabajos anteriores con resultados.', 'Tarifas por formato y qué incluyen.', 'Condiciones: plazos, cambios, derechos de uso y pago.']) + '</div>') +
        K.caja(C, 'Cómo se calculó la tarifa del ejemplo', 'Se parte de ' + esc($(base, C)) + ' por cada mil seguidores al año, repartidos en 12 meses, y se ajusta por la interacción frente a una media del 3 %: ' + esc(H.num(seg / 1000, C)) + ' × ' + esc($(base, C)) + ' ÷ 12 × (' + esc(H.num(ta, C)) + ' ÷ 3) ≈ ' + esc($(tar, C)) + '. Es un punto de partida: compara con cuentas de tu país y tu nicho.') +
        K.caja(C, 'Correo de propuesta', '«Hola, soy Lucía, creo recetas de 15 minutos para gente que trabaja. Mi público coincide con el vuestro. Os propongo un Reel y tres historias con vuestra salsa. Adjunto mi kit de medios.»', true) + K.items(pg, C, modo) + H.folio(C, pg);
    },
    rs_legal: function (pg, C, modo) {
      var L = LEG[C.pk] || LEG.es;
      return H.cabecera(C, pg) + H.h1(C, 'Lo legal en ' + L[0]) + K.caja(C, 'Publicidad', esc(L[1])) + K.caja(C, 'Impuestos', 'Los ingresos por redes se declaran. Organismo: ' + esc(L[2]) + '. Aparta cada mes una parte para impuestos y guarda todas las facturas y justificantes.') +
        H.h2(C, 'Lista de comprobación antes de publicar') + K.pasos(C, ['¿Hay pago, regalo o comisión? Indícalo: «publicidad», «colaboración pagada» o la etiqueta de la plataforma.', '¿Usas música, imágenes o textos de otros? Solo de bibliotecas autorizadas o con permiso.', '¿Aparecen menores u otras personas? Pide permiso por escrito.', '¿Prometes resultados de salud o dinero? Evítalo si no puedes demostrarlo.', '¿Recoges datos (sorteos, listas)? Explica para qué y pide consentimiento.']) +
        K.caja(C, 'Contrato con una marca', 'Incluye entregables, fechas, número de cambios, derechos de uso (dónde y cuánto tiempo), exclusividad, precio, forma de pago y qué pasa si se cancela.', true) + K.items(pg, C, modo) + H.folio(C, pg);
    },
    rs_plan90: function (pg, C, modo) {
      var s = smiTxt(C), meta = s ? bon(s.v * .25) : m(300, C);
      var W = [['1–2', 'Elegir nicho, perfil y 20 ideas', 'Perfil terminado'], ['3–4', 'Publicar 3 veces por semana', '12 publicaciones'], ['5–6', 'Analizar métricas y ajustar el gancho', 'Tasa de interacción medida'], ['7–8', 'Ofrecer un servicio o UGC a 10 negocios', '1.er cliente'], ['9–10', 'Crear un producto sencillo o elegir 3 afiliados', 'Primera venta'], ['11–12', 'Lista de contactos y revisión del plan', 'Ingreso de ' + $(meta, C)]];
      return H.cabecera(C, pg) + H.h1(C, 'Mi plan de 90 días') + K.p('Una meta realista para el primer trimestre: ' + $(meta, C) + ' al mes' + (s ? ', una cuarta parte del salario mínimo de ' + C.P.n : '') + '. Marca cada tarea al terminarla.') +
        K.tabla(C, ['Semanas', 'Tarea', 'Meta medible', 'Hecho'], W.map(function (w) { return w.concat(['☐']); })) + H.h2(C, 'Mis números al día 90') + K.tabla(C, ['Dato', 'Meta', 'Real'], [['Seguidores', '', ''], ['Tasa de interacción', '', ''], ['Clics en el enlace', '', ''], ['Clientes o ventas', '', ''], ['Ingresos del mes', $(meta, C), '']]) + K.items(pg, C, modo) + H.folio(C, pg);
    }
  };
  var ITEMS = { rs_modelos: 'redes_hora', rs_plataformas: 'redes_cpm', rs_ingresos: 'redes_hora', rs_calc: 'redes_com', rs_calendario: 'redes_eng', rs_kit: 'redes_ugc', rs_legal: 'redes_imp', rs_plan90: 'redes_crec' };

  /* ─────────── visuales para páginas «vis» ─────────── */
  function visEmbudo(u, C, r) {
    var a = P(r, [8000, 12000, 20000, 30000]), i = Math.round(a * P(r, [4, 5, 6]) / 100), c = Math.round(i * P(r, [15, 20, 25]) / 100), v = Math.max(2, Math.round(c * P(r, [5, 8, 10]) / 100)), E = [['Alcance', a], ['Interacciones', i], ['Clics en el enlace', c], ['Ventas', v]];
    return { t: 'El embudo de una publicación', intro: 'Datos de una publicación de ' + P(r, NICHOS) + '. Cada franja muestra cuántas personas pasaron al paso siguiente.', fig: K.embudo(C, E), items: [it('corta', '¿Qué porcentaje del alcance interactuó?', n(pc(i, a), C) + ' %', { ac: [pc(i, a)] }), it('corta', '¿Qué porcentaje de los clics terminó en venta?', n(pc(v, c), C) + ' %', { ac: [pc(v, c)] }), it('abierta', '¿Qué paso del embudo mejorarías primero y cómo?', '', { lin: 2 })] };
  }
  function visDias(u, C, r) {
    var d = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'], v = d.map(function () { return H.ent(r, 2, 12) * 100; }), mx = v.indexOf(Math.max.apply(null, v)), mn = v.indexOf(Math.min.apply(null, v)), tot = v.reduce(function (s, x) { return s + x; }, 0);
    return { t: 'Vistas por día de la semana', intro: 'Vistas de los vídeos publicados cada día durante un mes en una cuenta de ' + P(r, NICHOS) + '.', fig: SV.barras(C, { cats: d, vals: v, unidad: 'vistas', valores: true }), items: [it('corta', '¿Qué día conviene publicar?', d[mx]), it('corta', '¿Cuántas vistas hubo en total?', n(tot, C), { ac: [tot] }), it('corta', '¿Cuántas vistas más tuvo el mejor día que el peor?', n(v[mx] - v[mn], C), { ac: [v[mx] - v[mn]] })] };
  }
  function visReparto(u, C, r) {
    var ma = H.ent(r, 40, 60), af = H.ent(r, 10, 20), an = H.ent(r, 5, 15), pr = 100 - ma - af - an, tot = m(P(r, [800, 1200, 2000]), C);
    return { t: 'De dónde viene el dinero de una creadora', intro: 'Reparto de los ingresos de un mes (' + $(tot, C) + ' en total) de una creadora de ' + P(r, NICHOS) + '.', fig: SV.sectores(C, { vals: [ma, af, an, pr], cats: ['Marcas', 'Afiliación', 'Anuncios', 'Productos propios'] }), items: [it('corta', '¿Cuánto ganó con marcas?', $(r2(tot * ma / 100), C), { ac: [r2(tot * ma / 100)] }), it('corta', '¿Qué fuente aporta menos?', ['Marcas', 'Afiliación', 'Anuncios', 'Productos propios'][[ma, af, an, pr].indexOf(Math.min(ma, af, an, pr))]), it('abierta', 'Si una marca deja de contratarla, ¿qué porcentaje de ingresos pierde? ¿Cómo lo evitarías?', '', { lin: 2 })] };
  }
  function visPantalla(u, C, r) {
    var ks = Object.keys(FLUJOS), F = FLUJOS[P(r, ks)], k = H.ent(r, 0, F.pant.length - 1), S = F.pant[k];
    return { t: 'Lee la pantalla', intro: F.t.replace(/^Paso a paso: /, '') + '. Observa la pantalla ' + (k + 1) + ' y responde.', fig: '<div style="display:grid;grid-template-columns:52mm 1fr;gap:6mm;align-items:start"><div>' + K.movil(C, S) + '</div><div>' + K.pasos(C, F.pasos) + '</div></div>', items: [it('abierta', '¿Qué hace el botón o campo marcado en la pantalla? Relaciónalo con uno de los pasos.', '', { lin: 2 }), it('abierta', F.ojo.split(':')[0] + '. ¿Por qué es importante?', '', { lin: 2 })] };
  }
  if (SV && SV.visual) { var MR = /^redes$/; SV.visual('rs_embudo', visEmbudo, { materias: MR, max: 2 }); SV.visual('rs_dias', visDias, { materias: MR, max: 1 }); SV.visual('rs_reparto', visReparto, { materias: MR, max: 1 }); SV.visual('rs_pantalla', visPantalla, { materias: MR, max: 2 }); }

  /* ─────────── Para saber más ─────────── */
  var SABER = [['50 millones de creadores', 'Goldman Sachs Research calculó en 2023 unos 50 millones de creadores en el mundo; solo cerca del 4 % gana más de 100.000 dólares al año.'], ['Las marcas pagan más', 'Según las encuestas que cita Goldman Sachs (2023), los acuerdos con marcas son alrededor del 70 % de los ingresos de los creadores.'], ['Un mercado que se duplica', 'Goldman Sachs estimó que la economía de los creadores podría pasar de 250.000 a 480.000 millones de dólares entre 2023 y 2027.'], ['El reparto de YouTube', 'YouTube entrega a los creadores el 55 % de los ingresos por anuncios en vídeos largos y el 45 % en Shorts.'], ['Requisitos de TikTok', 'El Programa Creator Rewards pide 10.000 seguidores y 100.000 visualizaciones en 30 días, y paga solo vídeos originales de más de un minuto (TikTok Creator Academy).'], ['TikTok llega a México', 'TikTok abrió su Programa de Recompensas para Creadores a residentes en México; se solicita desde TikTok Studio.'], ['Telegram reparte anuncios', 'Desde 2024 Telegram entrega el 50 % de los ingresos por anuncios a los canales públicos con al menos 1.000 suscriptores.'], ['Nace la almohadilla', 'Chris Messina propuso en 2007 usar el símbolo # en Twitter para agrupar conversaciones: así nació el hashtag.'], ['Influencers con registro', 'En España, el Real Decreto 444/2024 obliga a inscribirse en un registro estatal a los creadores con más de 300.000 € de ingresos y más de un millón de seguidores.'], ['Publicidad visible', 'La FTC de Estados Unidos actualizó en 2023 sus guías: cualquier pago, regalo o comisión de una marca debe revelarse de forma clara.'], ['Facebook paga a creadores', 'Según datos de Meta, Facebook pagó casi 3.000 millones de dólares a creadores en 2025, un 35 % más que el año anterior.']];
  if (LB && LB.SABER) LB.SABER.redes = SABER;

  /* ─────────── ideas para «Mi plan de negocio» ─────────── */
  var T26 = 'Importes de ejemplo: compáralos con tarifas reales de tu zona. ';
  var IDEAS = [
    { id: 'ugc_creador', g: 'redes', n: 'Creación de vídeos UGC para marcas', u: 'vídeo', ico: 'movil', d: T26 + 'Las marcas pagan por vídeos que publican en sus propias cuentas; no hacen falta muchos seguidores (Goldman Sachs 2023: las marcas son el 70 % del ingreso de los creadores).', inv: [['Móvil con buena cámara (si no tienes)', 350], ['Luz, micrófono y trípode', 90], ['App de edición (año)', 60]], mat: [['Atrezo y producto', 8], ['Apps y música por vídeo', 3]], p: 110, h: 3, q: 10, fijos: [['Internet y teléfono', 35], ['Portafolio en línea', 10]], pasos: ['Graba 5 vídeos de muestra con productos que ya tienes', 'Publica el portafolio con precio por vídeo', 'Escribe a 20 marcas pequeñas por semana', 'Firma entregables, cambios y derechos de uso', 'Cobra el 50 % por adelantado'], vender: ['Marcas pequeñas y tiendas en línea', 'Agencias de marketing', 'Plataformas de UGC'], riesgo: 'Ingresos irregulares: busca clientes con encargo mensual.' },
    { id: 'comunidad_pago', g: 'redes', n: 'Comunidad de pago en Telegram o WhatsApp', u: 'suscriptor', ico: 'movil', d: T26 + 'Contenido exclusivo por una cuota mensual; Telegram reparte además el 50 % de sus anuncios en canales públicos de 1.000 suscriptores o más.', inv: [['Contenido inicial (guías, plantillas)', 150], ['Diseño de la marca', 60]], mat: [['Comisión de cobro por suscriptor', .5]], p: 6, h: .05, q: 150, fijos: [['Herramientas de cobro y bots', 20], ['Publicidad', 60]], pasos: ['Elige un tema con valor práctico', 'Abre un canal gratuito como escaparate', 'Crea la comunidad de pago con 3 ventajas claras', 'Publica con calendario fijo', 'Mide bajas y pregunta por qué se van'], vender: ['Tus redes sociales', 'Canal gratuito', 'Recomendaciones de miembros'], riesgo: 'Si el contenido decae, las bajas suben: revisa cada mes qué valoran los miembros.' },
    { id: 'afiliados_nicho', g: 'redes', n: 'Contenido de afiliación en un nicho', u: 'venta', ico: 'bolsa', d: T26 + 'Recomiendas productos con enlace propio y cobras una comisión por compra; la ley obliga a avisar de que el enlace es de afiliado.', inv: [['Productos para probar', 200], ['Web sencilla con dominio', 80]], mat: [], p: 3.5, h: .02, q: 200, fijos: [['Web y herramientas', 15], ['Publicidad', 30]], pasos: ['Elige un nicho con productos de precio medio', 'Prueba lo que vas a recomendar', 'Publica comparativas y guías con aviso de afiliado', 'Reúne los enlaces en una página propia', 'Revisa cada semana clics y comisiones'], vender: ['Vídeos cortos', 'Web y buscadores', 'Lista de correo'], riesgo: 'Las tiendas pueden bajar comisiones: no dependas de un solo programa.' },
    { id: 'editor_video', g: 'redes', n: 'Edición de vídeos cortos para creadores y negocios', u: 'vídeo', ico: 'movil', d: T26 + 'Muchos creadores y comercios graban pero no tienen tiempo de editar: subtítulos, cortes y ganchos.', inv: [['Portátil (si no tienes)', 600], ['Programa de edición (año)', 150]], mat: [['Música y recursos por vídeo', 1]], p: 30, h: 1, q: 40, fijos: [['Internet', 30], ['Almacenamiento en la nube', 10]], pasos: ['Edita 5 vídeos de muestra', 'Ofrece un paquete de 12 vídeos al mes', 'Entrega en 48 horas con dos cambios incluidos', 'Mide la retención de los vídeos del cliente', 'Sube la tarifa con resultados'], vender: ['Creadores pequeños', 'Comercios con redes', 'Plataformas de trabajo freelance'], riesgo: 'Precios a la baja en las plataformas: diferénciate con ganchos y resultados medidos.' }
  ];
  if (EM && EM.IDEAS) IDEAS.forEach(function (I) { if (!EM.IDEAS.some(function (x) { return x.id === I.id; })) EM.IDEAS.push(I); });

  ED.registrar({ materias: [{ id: 'redes', n: 'Redes sociales', ico: '📱', prodDef: 'libro' }], unidades: U, generadores: GEN, paginas: PAG });

  /* ─────────── motor común: páginas propias, sin repetir, plan de negocio, cabecera ─────────── */
  function insertar(res, TIPOS, ITEMS, GENS) {
    var C = res.C, pages = res.pages, N = pages.length; if (N < 20) return;
    var usados = {}, cambio = false;
    res.unidades && res.unidades.forEach(function (u) {
      if (!u.pz) return;
      var anc = -1; pages.forEach(function (p, i) { if (p.u === u && p.tipo === 'explica' && anc < 0) anc = i; }); if (anc < 0) return;
      var libres = []; pages.forEach(function (p, i) { if (p.u === u && p.relleno && /^(actividad|apuntes|vis)$/.test(p.tipo) && i > anc && !(p.tipo === 'vis' && p.gen && window.EU_MODELOS && EU_MODELOS.modelo(p.gen))) libres.push(i); });
      libres.sort(function (a, b) { var pa = pages[a].tipo === 'vis' ? 1 : 0, pb = pages[b].tipo === 'vis' ? 1 : 0; return pa - pb || a - b; });
      libres.reverse();
      u.pz.forEach(function (z, k) {
        var j = libres[libres.length - 1 - k]; if (j == null) return;
        var sp = z.split(':'), tipo = sp[0]; if (!TIPOS[tipo]) return;
        var r = H.rng(H.hash(u.id + ':' + z) + (C.semilla || 1) * 131), g = ITEMS[tipo] || u.g, items = [];
        for (var q = 0; q < 2; q++) { try { var x = GENS[g](u, C, r); if (x) items.push(x); } catch (e) { } }
        usados[j] = { tipo: tipo, fl: sp[1], u: u, n: pages[anc].n, items: items, cab: pages[anc].cab, propia: true };
        cambio = true;
      });
    });
    if (!cambio) return;
    var out = [], ins = {};
    Object.keys(usados).forEach(function (j) { var p = usados[j], anc = -1; pages.forEach(function (x, i) { if (x.u === p.u && x.tipo === 'explica' && anc < 0) anc = i; }); (ins[anc] = ins[anc] || []).push(p); });
    pages.forEach(function (p, i) { if (!usados[i]) out.push(p); if (ins[i]) out.push.apply(out, ins[i]); });
    out.forEach(function (p, i) { p.num = i + 1; });
    res.pages = out; resol(res);
  }
  function resol(res) {
    var out = res.pages, sols = out.filter(function (p) { return p.tipo === 'solucion'; }); if (!sols.length) return;
    var e = [];
    out.forEach(function (p) { if (p.tipo === 'vis' && p.v && p.v.sopa) e.push({ p: p.num, items: [{ s: p.v.sol }], u: p.u }); else if (p.items && p.items.length && (p.tipo === 'actividad' || p.tipo === 'ficha' || p.tipo === 'vis' || p.lec || p.propia)) e.push({ p: p.num, items: p.items, u: p.u }); });
    var per = Math.ceil(e.length / sols.length); sols.forEach(function (p, i) { p.entradas = e.slice(i * per, (i + 1) * per); });
  }
  function sinRepetir(res, GENS, pref) {
    var C = res.C, visto = {}, keys = Object.keys(GENS).filter(function (k) { return k.indexOf(pref) === 0; });
    res.pages.forEach(function (p, i) {
      if (!p.items || !p.items.length) return;
      var nuevos = [];
      p.items.forEach(function (x, j) {
        var k = x && x.e; if (!k || !visto[k]) { if (k) visto[k] = 1; nuevos.push(x); return; }
        var r = H.rng(H.hash(C.mat + ':' + i + ':' + j + ':' + (C.semilla || 1)));
        for (var t = 0; t < 40; t++) { var gk = t < 10 && p.u && GENS[p.u.g] ? p.u.g : keys[Math.floor(r() * keys.length)], y = null; try { y = GENS[gk](p.u, C, r); } catch (e) { } if (y && y.e && !visto[y.e]) { visto[y.e] = 1; nuevos.push(y); return; } }
      });
      p.items.length = 0; Array.prototype.push.apply(p.items, nuevos);
    });
  }
  /* «Mi plan de negocio» y «Pitch» también para redes y comercio: solo las ideas de ese grupo */
  var GRUPO = { redes: ['redes', 'redes_comercios', 'contenido_ia'], ecom: ['ecom', 'tienda_online', 'comida_online'] };
  (ED.PRODUCTOS || []).forEach(function (p) { if ((p.id === 'plan_negocio' || p.id === 'pitch') && p.solo) ['redes', 'ecom'].forEach(function (m) { if (p.solo.indexOf(m) < 0) p.solo.push(m); }); });
  var ens = ED.ensamblar;
  ED.ensamblar = function (cfg) {
    if (cfg && GRUPO[cfg.materia] && /^(plan_negocio|pitch)$/.test(cfg.prod) && EM) {
      var g = GRUPO[cfg.materia], op = Object.assign({}, cfg.op || {});
      if (!op.ideas || !op.ideas.length) op.ideas = EM.IDEAS.filter(function (I) { return I.g === g[0] || g.indexOf(I.id) >= 0; }).map(function (I) { return I.id; });
      cfg = Object.assign({}, cfg, { op: op });
    }
    var res = ens(cfg);
    try {
      if (cfg && cfg.materia === 'redes' && res && res.pages) { insertar(res, PAG, ITEMS, GEN); sinRepetir(res, GEN, 'redes_'); }
      if (cfg && cfg.nivel === 'adu' && /^(redes|ecom)$/.test(cfg.materia) && res && res.C) res.C.cursoN = 'Personas adultas';
    } catch (e) { console.warn('EU_REDES', e); }
    return res;
  };
  window.EU_REDES = { U: U, GEN: GEN, SABER: SABER, IDEAS: IDEAS, FLUJOS: FLUJOS, LEG: LEG, K: K, insertar: insertar, sinRepetir: sinRepetir, resol: resol, m: m, bon: bon };
})();
