/* b6_unidades_plus.js — unidades nuevas para las materias con menos temas por nivel
   (Religión, Valores, Música, Educación física, Lengua e Inglés). Con dos o tres unidades por nivel,
   un libro de 300 páginas repetía las mismas frases decenas de veces; ahora cada nivel de secundaria
   tiene al menos ocho. Formato de EU_CURRICULO.UNIDADES; b6_mates_plus les asigna 'proc_orden', que
   hace los ejercicios de ordenar el proceso, V/F justificado y completar.
   Cargar después de b6_mates_plus.js. */
(function () {
  'use strict';
  var ED = window.EU_EDITORIAL; if (!ED) return;
  var B = ['pri3', 'sec', 'bach', 'adu'], BS = ['sec', 'bach', 'adu'];
  function u(m, id, t, i, k, vf, q, f, b) { var x = { m: m, id: id, t: t, i: i, k: k, vf: vf, q: q, b: b || B, plus: true }; if (f) x.f = f; return x; }
  function mapa(c, r) { return { t: 'mapa', c: c, r: r }; }
  function flujo(p) { return { t: 'flujo', p: p }; }

  var U = [
    /* ───── Religión (enfoque cultural y comparado) ───── */
    u('religion', 'rel_libros', 'Los libros sagrados', ['La Biblia reúne el Antiguo y el Nuevo Testamento.', 'La Torá son los cinco primeros libros de la Biblia hebrea.', 'El Corán es el libro sagrado del islam, escrito en árabe.', 'Los Vedas son los textos más antiguos del hinduismo.'], ['Biblia', 'Torá', 'Corán', 'Vedas', 'escritura'], [['El Corán está escrito en árabe.', true], ['La Torá forma parte del Nuevo Testamento.', false], ['Los Vedas son textos del hinduismo.', true]], ['¿Por qué crees que las religiones pusieron sus enseñanzas por escrito?', 'Compara dos libros sagrados: idioma, época y contenido.'], mapa('Libros sagrados', ['Biblia', 'Torá', 'Corán', 'Vedas'])),
    u('religion', 'rel_calendario', 'Calendarios y fiestas', ['Cada tradición organiza el año con sus propias fiestas.', 'La Pascua cristiana cambia de fecha porque depende de la luna llena de primavera.', 'El calendario islámico es lunar: el Ramadán se adelanta unos once días cada año.', 'Muchas fiestas coinciden con cosechas o cambios de estación.'], ['calendario', 'Pascua', 'Ramadán', 'calendario lunar', 'estación'], [['El Ramadán cae siempre en la misma fecha del calendario civil.', false], ['La Pascua depende de la luna.', true], ['Algunas fiestas coinciden con cosechas.', true]], ['Haz un calendario con cinco fiestas religiosas de tu país.', '¿Por qué un calendario lunar se desplaza respecto al solar?'], mapa('Fiestas del año', ['Navidad', 'Pascua', 'Ramadán', 'Janucá', 'Diwali'])),
    u('religion', 'rel_templos', 'Templos del mundo', ['La iglesia cristiana suele tener planta de cruz latina, con nave y altar.', 'La mezquita tiene un mihrab que señala la dirección de La Meca.', 'La sinagoga guarda los rollos de la Torá en el arca.', 'Los templos budistas suelen tener una estupa que guarda reliquias.'], ['iglesia', 'mezquita', 'sinagoga', 'estupa', 'mihrab'], [['El mihrab señala la dirección de La Meca.', true], ['La sinagoga guarda el Corán.', false], ['La estupa es propia del budismo.', true]], ['Describe un templo de tu ciudad: forma, materiales y uso.', '¿Qué tienen en común los espacios de culto de distintas religiones?'], mapa('Templos', ['iglesia', 'mezquita', 'sinagoga', 'templo hindú', 'estupa'])),
    u('religion', 'rel_etica', 'Las normas morales', ['Todas las grandes tradiciones tienen normas para convivir.', 'La «regla de oro» —trata a los demás como quieres que te traten— aparece en muchas de ellas.', 'Los diez mandamientos son la base moral del judaísmo y del cristianismo.', 'El budismo propone el noble camino óctuple.'], ['regla de oro', 'mandamientos', 'camino óctuple', 'moral'], [['La regla de oro aparece solo en una religión.', false], ['Los diez mandamientos son comunes al judaísmo y al cristianismo.', true], ['El camino óctuple es budista.', true]], ['Escribe la regla de oro con tus palabras y pon un ejemplo de clase.', '¿Qué norma común encuentras entre dos tradiciones?'], flujo(['Norma', 'Conducta', 'Convivencia', 'Comunidad'])),
    u('religion', 'rel_historia', 'Religión e historia', ['El cristianismo se extendió por el Imperio romano desde el siglo I.', 'El islam nació en Arabia en el siglo VII.', 'En América, la llegada europea trajo el cristianismo y se mezcló con creencias indígenas.', 'Ese mestizaje se ve hoy en fiestas y santuarios.'], ['expansión', 'Imperio romano', 'sincretismo', 'santuario'], [['El islam nació en el siglo VII.', true], ['El cristianismo llegó a América antes que a Roma.', false], ['En América se mezclaron creencias.', true]], ['Busca una fiesta de tu país que mezcle tradiciones distintas.', 'Ordena en una línea del tiempo el nacimiento de tres religiones.'], flujo(['Siglo I', 'Siglo VII', 'Siglo XV', 'Hoy'])),
    u('religion', 'rel_simbolos2', 'Leer los símbolos', ['La cruz es el símbolo principal del cristianismo.', 'La estrella de David identifica al judaísmo.', 'La media luna se asocia al islam.', 'La rueda del dharma representa las enseñanzas de Buda.'], ['cruz', 'estrella de David', 'media luna', 'rueda del dharma'], [['La rueda del dharma es un símbolo budista.', true], ['La estrella de David identifica al islam.', false], ['La cruz es cristiana.', true]], ['Dibuja tres símbolos y escribe qué tradición representa cada uno.', '¿Por qué los símbolos se entienden sin palabras?'], mapa('Símbolos', ['cruz', 'estrella de David', 'media luna', 'rueda del dharma', 'om']), BS),
    u('religion', 'rel_libertad', 'Libertad religiosa', ['La Declaración Universal de Derechos Humanos (1948) recoge la libertad de pensamiento, conciencia y religión.', 'Incluye el derecho a cambiar de creencia o a no tener ninguna.', 'Los Estados laicos no tienen una religión oficial.', 'Respetar las creencias ajenas es parte de la convivencia democrática.'], ['libertad religiosa', 'laicidad', 'derechos humanos', 'respeto'], [['La libertad religiosa incluye no tener religión.', true], ['Un Estado laico tiene una religión oficial.', false], ['La Declaración Universal es de 1948.', true]], ['Explica qué significa que un Estado sea laico.', 'Escribe una norma de clase que proteja la libertad de creencias.'], mapa('Libertad', ['conciencia', 'culto', 'laicidad', 'respeto']), BS),
    u('religion', 'rel_dialogo', 'Diálogo entre culturas', ['Dialogar no es pensar igual: es escuchar para entender.', 'Muchas ciudades tienen consejos interreligiosos que organizan actividades comunes.', 'Las religiones colaboran en tareas solidarias como bancos de alimentos.', 'Conocer al otro reduce prejuicios.'], ['diálogo', 'prejuicio', 'solidaridad', 'convivencia'], [['Dialogar exige pensar igual.', false], ['Conocer al otro reduce prejuicios.', true], ['Hay proyectos solidarios compartidos.', true]], ['Prepara tres preguntas respetuosas para conocer la fiesta de un compañero.', '¿Qué es un prejuicio? Pon un ejemplo y cómo se supera.'], flujo(['Escuchar', 'Preguntar', 'Comprender', 'Colaborar'])),

    /* ───── Valores y ética ───── */
    u('valores', 'val_dilema', 'Dilemas morales', ['Un dilema es una situación con dos opciones y razones para las dos.', 'Pensar bien un dilema exige ver las consecuencias para todos.', 'También hay que preguntarse qué norma o principio se respeta.', 'Dos personas pueden decidir distinto y ambas razonar bien.'], ['dilema', 'consecuencia', 'principio', 'argumento'], [['En un dilema solo hay una opción razonable.', false], ['Conviene pensar en las consecuencias.', true], ['Dos personas pueden razonar bien y decidir distinto.', true]], ['Inventa un dilema de tu vida diaria y da un argumento para cada opción.', '¿Qué principio usarías para decidir?'], flujo(['Situación', 'Opciones', 'Consecuencias', 'Decisión'])),
    u('valores', 'val_empatia', 'La empatía', ['La empatía es ponerse en el lugar de otra persona.', 'Se practica escuchando sin interrumpir.', 'Nombrar lo que siente el otro ayuda: «parece que estás preocupado».', 'La empatía no obliga a estar de acuerdo.'], ['empatía', 'escucha activa', 'emoción', 'respeto'], [['Empatía significa estar siempre de acuerdo.', false], ['Escuchar sin interrumpir es parte de la empatía.', true], ['Nombrar emociones ayuda a comprender.', true]], ['Describe una vez en que alguien te escuchó de verdad.', 'Escribe tres frases empáticas para un compañero triste.'], mapa('Empatía', ['escuchar', 'observar', 'nombrar', 'ayudar'])),
    u('valores', 'val_conflicto', 'Resolver conflictos', ['Los conflictos son normales cuando convivimos.', 'Primero se calma la situación; después se habla.', 'Cada parte explica qué pasó y cómo se sintió, sin insultos.', 'Se buscan soluciones en las que ganen las dos partes.'], ['conflicto', 'mediación', 'acuerdo', 'calma'], [['Un conflicto se resuelve mejor en caliente.', false], ['Cada parte debe poder explicarse.', true], ['Se buscan soluciones en las que ganen todos.', true]], ['Ordena los pasos para resolver una discusión en el recreo.', '¿Qué hace una persona mediadora?'], flujo(['Calmarse', 'Escuchar', 'Proponer', 'Acordar'])),
    u('valores', 'val_derechos', 'Los derechos humanos', ['La Declaración Universal de Derechos Humanos se aprobó en la ONU en 1948.', 'Tiene 30 artículos.', 'Los derechos son universales: valen para todas las personas.', 'La Convención sobre los Derechos del Niño es de 1989.'], ['derechos humanos', 'ONU', 'universal', 'Convención del Niño'], [['La Declaración tiene 30 artículos.', true], ['Los derechos solo valen para adultos.', false], ['La Convención del Niño es de 1989.', true]], ['Elige un artículo de la Declaración y explica un ejemplo en tu barrio.', '¿Qué derecho de la infancia te parece más importante y por qué?'], mapa('Derechos', ['vida', 'educación', 'salud', 'libertad', 'igualdad'])),
    u('valores', 'val_digital', 'Convivencia en internet', ['Lo que se publica en internet puede quedar para siempre.', 'El ciberacoso es acoso repetido por medios digitales.', 'Antes de compartir una foto de alguien hay que pedir permiso.', 'Si ves acoso, guarda pruebas y cuéntaselo a un adulto de confianza.'], ['huella digital', 'ciberacoso', 'privacidad', 'permiso'], [['Lo que se publica se borra del todo.', false], ['Hay que pedir permiso para compartir fotos ajenas.', true], ['Ante el acoso conviene guardar pruebas.', true]], ['Escribe tres normas para un grupo de mensajería de clase.', '¿Qué harías si ves que se burlan de alguien en línea?'], flujo(['Pienso', 'Pido permiso', 'Publico', 'Respeto'])),
    u('valores', 'val_medio', 'Cuidar el planeta', ['Reducir, reutilizar y reciclar, en ese orden, ahorra más recursos.', 'Separar la basura permite recuperar materiales.', 'El agua y la energía que no se gastan no contaminan.', 'Las decisiones de cada día suman: transporte, compra y comida.'], ['reducir', 'reutilizar', 'reciclar', 'consumo responsable'], [['Reciclar es lo primero de las tres erres.', false], ['Separar la basura permite recuperar materiales.', true], ['Los hábitos diarios influyen en el planeta.', true]], ['Haz un plan de una semana para gastar menos agua en casa.', '¿Qué objeto podrías reutilizar en lugar de tirar?'], mapa('Tres erres', ['reducir', 'reutilizar', 'reciclar'])),
    u('valores', 'val_igualdad', 'Igualdad y no discriminación', ['Discriminar es tratar peor a alguien por lo que es.', 'Nadie debe ser excluido por su origen, sexo, religión o discapacidad.', 'La igualdad de oportunidades da a cada persona lo que necesita para participar.', 'Los estereotipos son ideas fijas que no se ajustan a cada persona.'], ['discriminación', 'estereotipo', 'inclusión', 'igualdad de oportunidades'], [['Un estereotipo describe bien a cada persona.', false], ['Nadie debe ser excluido por su origen.', true], ['La inclusión busca que todos participen.', true]], ['Escribe un estereotipo común y un ejemplo que lo desmienta.', 'Propón un cambio para que tu escuela sea más inclusiva.'], mapa('Inclusión', ['origen', 'sexo', 'religión', 'discapacidad'])),
    u('valores', 'val_responsable', 'Responsabilidad', ['Ser responsable es cumplir lo que te toca y asumir las consecuencias.', 'Pedir perdón y reparar el daño forma parte de la responsabilidad.', 'Planificar evita dejar tareas para el último momento.', 'La responsabilidad crece con la edad y con la confianza de los demás.'], ['responsabilidad', 'compromiso', 'reparar', 'planificar'], [['Ser responsable incluye reparar el daño.', true], ['Planificar no influye en cumplir tareas.', false], ['La confianza se gana cumpliendo.', true]], ['Haz una lista de tus responsabilidades en casa y en clase.', 'Cuenta una vez en que reparaste un error.'], flujo(['Compromiso', 'Plan', 'Cumplo', 'Reviso'])),
    u('valores', 'val_participar', 'Participar en la comunidad', ['En una democracia las decisiones se toman escuchando a todos.', 'El consejo de clase o de estudiantes es una forma de participar.', 'Votar exige informarse antes.', 'El voluntariado es dar tiempo a una causa sin cobrar.'], ['democracia', 'voto', 'voluntariado', 'consejo escolar'], [['Votar sin informarse es lo recomendable.', false], ['El voluntariado no se cobra.', true], ['Un consejo de estudiantes es participación.', true]], ['Propón una mejora para tu escuela y cómo la votaríais.', '¿Qué voluntariado conoces en tu ciudad?'], flujo(['Propuesta', 'Debate', 'Voto', 'Acción']), BS),

    /* ───── Música ───── */
    u('musica', 'mus_pentagrama', 'El pentagrama y las notas', ['El pentagrama tiene cinco líneas y cuatro espacios.', 'La clave de sol fija la nota sol en la segunda línea.', 'Las notas son do, re, mi, fa, sol, la y si.', 'Cuanto más arriba en el pentagrama, más aguda es la nota.'], ['pentagrama', 'clave de sol', 'nota', 'agudo'], [['El pentagrama tiene cinco líneas.', true], ['La clave de sol fija el sol en la cuarta línea.', false], ['Más arriba significa más agudo.', true]], ['Escribe las siete notas en orden ascendente y descendente.', '¿Por qué hace falta una clave al principio del pentagrama?'], flujo(['do', 're', 'mi', 'fa', 'sol', 'la', 'si'])),
    u('musica', 'mus_figuras', 'Figuras y duración', ['La redonda dura 4 tiempos; la blanca, 2; la negra, 1; la corchea, medio.', 'Cada figura dura la mitad que la anterior.', 'Los silencios tienen las mismas duraciones que las figuras.', 'El puntillo alarga la figura la mitad de su valor.'], ['redonda', 'blanca', 'negra', 'corchea', 'puntillo'], [['La blanca dura 2 tiempos.', true], ['La corchea dura más que la negra.', false], ['El puntillo añade la mitad del valor.', true]], ['¿Cuánto dura una blanca con puntillo?', 'Escribe un compás de 4/4 con cuatro figuras distintas.'], flujo(['Redonda 4', 'Blanca 2', 'Negra 1', 'Corchea ½'])),
    u('musica', 'mus_instrumentos', 'Familias de instrumentos', ['Los instrumentos de cuerda suenan al vibrar una cuerda: violín, guitarra, arpa.', 'Los de viento suenan al vibrar una columna de aire: flauta, trompeta.', 'Los de percusión suenan al ser golpeados: tambor, xilófono.', 'Los electrófonos producen el sonido con electricidad: sintetizador.'], ['cuerda', 'viento', 'percusión', 'electrófono'], [['La trompeta es de viento.', true], ['El xilófono es de cuerda.', false], ['El sintetizador es un electrófono.', true]], ['Clasifica diez instrumentos de tu país en sus familias.', '¿Qué vibra en una flauta?'], mapa('Instrumentos', ['cuerda', 'viento-madera', 'viento-metal', 'percusión', 'electrófonos'])),
    u('musica', 'mus_orquesta', 'La orquesta sinfónica', ['Una orquesta sinfónica puede reunir entre 60 y 100 músicos.', 'Las cuerdas se sitúan delante, cerca del director.', 'Detrás van las maderas, después los metales y al fondo la percusión.', 'El director marca el tempo y da entrada a cada sección.'], ['orquesta', 'director', 'sección', 'tempo'], [['La percusión va delante.', false], ['El director marca el tempo.', true], ['Las cuerdas están cerca del director.', true]], ['Dibuja la colocación de una orquesta.', '¿Por qué crees que las cuerdas van delante?'], mapa('Orquesta', ['cuerdas', 'maderas', 'metales', 'percusión', 'director'])),
    u('musica', 'mus_forma', 'La forma musical', ['Las canciones se organizan en partes que se repiten.', 'La forma estrofa-estribillo alterna una parte que cambia con otra que vuelve.', 'La forma A-B-A presenta una idea, un contraste y vuelve a la primera.', 'Reconocer la forma ayuda a escuchar y a memorizar.'], ['estrofa', 'estribillo', 'forma ABA', 'repetición'], [['El estribillo cambia cada vez.', false], ['La forma ABA vuelve a la primera idea.', true], ['Reconocer la forma ayuda a memorizar.', true]], ['Escucha una canción y escribe su forma con letras.', 'Inventa un estribillo de cuatro versos.'], flujo(['A', 'B', 'A'])),
    u('musica', 'mus_folclor', 'Música de mi país', ['Cada país tiene géneros propios que nacen de su historia.', 'En {pais} es muy conocida {musica}.', 'La música tradicional se transmitía de oído, de generación en generación.', 'Muchos géneros actuales mezclan ritmos tradicionales y modernos.'], ['folclore', 'tradición oral', 'género', 'fusión'], [['La música tradicional se aprendía de oído.', true], ['Los géneros actuales nunca mezclan estilos.', false], ['Cada país tiene géneros propios.', true]], ['Pregunta en casa por una canción tradicional y escribe su letra.', '¿Qué instrumentos se usan en la música típica de tu país?'], mapa('Folclore', ['ritmo', 'instrumentos', 'baile', 'letra'])),
    u('musica', 'mus_tempo', 'Tempo y dinámica', ['El tempo es la velocidad de la música y se mide en pulsos por minuto.', 'Adagio es lento; allegro, rápido.', 'La dinámica indica la intensidad: piano es suave, forte es fuerte.', 'El crescendo aumenta poco a poco la intensidad.'], ['tempo', 'allegro', 'adagio', 'piano', 'forte'], [['Allegro es lento.', false], ['Forte indica fuerte.', true], ['El tempo se mide en pulsos por minuto.', true]], ['Canta una canción en tempo adagio y luego en allegro. ¿Qué cambia?', 'Dibuja el símbolo de crescendo.'], flujo(['pp', 'p', 'mf', 'f', 'ff']), BS),

    /* ───── Educación física ───── */
    u('efisica', 'ef_calentar', 'El calentamiento', ['Calentar prepara el cuerpo: sube la temperatura del músculo y el pulso.', 'Empieza con movilidad articular y carrera suave.', 'Después, ejercicios parecidos a la actividad que vas a hacer.', 'Un buen calentamiento dura entre 10 y 15 minutos.'], ['calentamiento', 'movilidad', 'pulso', 'lesión'], [['El calentamiento dura unos 10–15 minutos.', true], ['Calentar aumenta el riesgo de lesión.', false], ['Se empieza por movilidad articular.', true]], ['Diseña un calentamiento de 10 minutos para fútbol.', '¿Por qué los ejercicios deben parecerse a la actividad principal?'], flujo(['Movilidad', 'Carrera suave', 'Estiramiento dinámico', 'Ejercicios específicos'])),
    u('efisica', 'ef_capacidades', 'Capacidades físicas', ['Las capacidades físicas básicas son resistencia, fuerza, velocidad y flexibilidad.', 'La resistencia permite mantener un esfuerzo durante mucho tiempo.', 'La fuerza es vencer una resistencia con los músculos.', 'Todas mejoran con entrenamiento regular.'], ['resistencia', 'fuerza', 'velocidad', 'flexibilidad'], [['La flexibilidad es una capacidad física básica.', true], ['Las capacidades no mejoran entrenando.', false], ['La resistencia sostiene un esfuerzo largo.', true]], ['Pon un ejercicio para cada capacidad física.', '¿Qué capacidad es más importante en tu deporte favorito?'], mapa('Capacidades', ['resistencia', 'fuerza', 'velocidad', 'flexibilidad'])),
    u('efisica', 'ef_pulso', 'Pulso y frecuencia cardiaca', ['La frecuencia cardiaca son los latidos del corazón por minuto.', 'Se toma en la muñeca o en el cuello durante 15 segundos y se multiplica por 4.', 'Una estimación sencilla de la máxima es 220 menos la edad.', 'En reposo, un adolescente suele tener entre 60 y 100 pulsaciones.'], ['frecuencia cardiaca', 'pulso', 'frecuencia máxima', 'reposo'], [['Se cuenta 15 segundos y se multiplica por 4.', true], ['La frecuencia máxima estimada es 200 más la edad.', false], ['El pulso se toma en la muñeca o el cuello.', true]], ['Toma tu pulso en reposo y después de 30 saltos. Compara.', 'Calcula tu frecuencia máxima estimada.'], flujo(['Reposo', 'Calentamiento', 'Esfuerzo', 'Recuperación'])),
    u('efisica', 'ef_juego', 'Juego limpio', ['El juego limpio es respetar las reglas, a los rivales y al árbitro.', 'Saludar al terminar forma parte del deporte.', 'Ganar sin trampas vale más que ganar a cualquier precio.', 'Ayudar a un rival lesionado es un gesto de juego limpio.'], ['juego limpio', 'reglas', 'árbitro', 'respeto'], [['El juego limpio incluye respetar al árbitro.', true], ['Hacer trampa está bien si ganas.', false], ['Saludar al final forma parte del deporte.', true]], ['Escribe tres normas de juego limpio para tu clase.', 'Cuenta un gesto de juego limpio que hayas visto.'], mapa('Juego limpio', ['reglas', 'rival', 'árbitro', 'compañeros'])),
    u('efisica', 'ef_postura', 'Postura e higiene', ['Una buena postura reparte el peso y evita dolores de espalda.', 'La mochila se lleva con las dos asas y pegada a la espalda.', 'Después del ejercicio conviene ducharse y cambiarse de ropa.', 'Beber agua antes, durante y después evita la deshidratación.'], ['postura', 'espalda', 'hidratación', 'higiene'], [['La mochila se lleva en un solo hombro.', false], ['Beber agua evita la deshidratación.', true], ['La ducha tras el ejercicio es higiene.', true]], ['Observa cómo te sientas al estudiar y propón una mejora.', '¿Cuánta agua bebes un día de deporte?'], flujo(['Antes', 'Durante', 'Después'])),
    u('efisica', 'ef_orienta', 'Orientación', ['La orientación es encontrar un camino con mapa y brújula.', 'El norte del mapa se alinea con el norte de la brújula.', 'La escala del mapa permite calcular distancias.', 'Las carreras de orientación combinan correr y pensar.'], ['orientación', 'brújula', 'mapa', 'escala'], [['La aguja de la brújula señala el norte.', true], ['La escala no sirve para medir distancias.', false], ['La orientación combina correr y pensar.', true]], ['Dibuja un plano de tu escuela con cinco balizas.', 'En un mapa 1:10 000, ¿cuántos metros son 3 cm?'], flujo(['Orientar el mapa', 'Elegir ruta', 'Avanzar', 'Baliza'])),

    /* ───── Lengua ───── */
    u('lengua', 'len_textos', 'Tipos de texto', ['El texto narrativo cuenta hechos: cuentos, noticias.', 'El descriptivo muestra cómo es algo o alguien.', 'El expositivo explica un tema con datos.', 'El argumentativo defiende una opinión con razones.'], ['narrativo', 'descriptivo', 'expositivo', 'argumentativo'], [['El texto argumentativo defiende una opinión.', true], ['Una noticia es un texto descriptivo.', false], ['El expositivo explica con datos.', true]], ['Busca en un periódico un ejemplo de cada tipo de texto.', 'Escribe un párrafo argumentativo sobre el uso del móvil en clase.'], mapa('Textos', ['narrar', 'describir', 'exponer', 'argumentar'])),
    u('lengua', 'len_acento', 'La tilde', ['Las palabras agudas llevan tilde si terminan en vocal, n o s: canción.', 'Las llanas la llevan si no terminan en vocal, n o s: árbol.', 'Las esdrújulas siempre llevan tilde: música.', 'Los monosílabos, en general, no llevan tilde, salvo la tilde diacrítica: tú / tu.'], ['aguda', 'llana', 'esdrújula', 'tilde diacrítica'], [['Todas las esdrújulas llevan tilde.', true], ['«Árbol» es aguda.', false], ['«Tú» lleva tilde diacrítica.', true]], ['Clasifica diez palabras de tu nombre y tu calle por su acento.', '¿Por qué «camión» lleva tilde y «camiones» no?'], flujo(['Separo sílabas', 'Busco la tónica', 'Clasifico', 'Aplico la regla'])),
    u('lengua', 'len_categorias', 'Las clases de palabras', ['El sustantivo nombra personas, animales, cosas o ideas.', 'El adjetivo dice cómo es el sustantivo.', 'El verbo expresa acciones o estados y se conjuga.', 'Adverbios, preposiciones y conjunciones completan la oración.'], ['sustantivo', 'adjetivo', 'verbo', 'adverbio', 'preposición'], [['El adjetivo acompaña al sustantivo.', true], ['El adverbio se conjuga.', false], ['El verbo expresa acciones o estados.', true]], ['Subraya en un párrafo los sustantivos de un color y los verbos de otro.', 'Escribe una oración con un sustantivo, un adjetivo, un verbo y un adverbio.'], mapa('Palabras', ['sustantivo', 'adjetivo', 'verbo', 'adverbio', 'preposición'])),
    u('lengua', 'len_resumen', 'El resumen', ['Resumir es contar lo esencial de un texto con palabras propias.', 'Primero se lee entero y se subrayan las ideas principales.', 'Después se ordenan y se unen con conectores.', 'Un buen resumen ocupa más o menos una cuarta parte del original.'], ['resumen', 'idea principal', 'conector', 'subrayar'], [['El resumen copia frases del texto.', false], ['Se subrayan las ideas principales.', true], ['Ocupa aproximadamente un cuarto del original.', true]], ['Resume en cinco líneas la última noticia que hayas leído.', '¿Qué conectores usarías para unir tres ideas?'], flujo(['Leer', 'Subrayar', 'Ordenar', 'Redactar'])),
    u('lengua', 'len_poesia', 'La poesía', ['El poema se organiza en versos y estrofas.', 'La rima puede ser consonante (coinciden vocales y consonantes) o asonante (solo vocales).', 'La medida se cuenta en sílabas métricas.', 'Las figuras literarias, como la metáfora, dan fuerza a las imágenes.'], ['verso', 'estrofa', 'rima', 'metáfora'], [['En la rima asonante coinciden solo las vocales.', true], ['Una estrofa es una sola palabra.', false], ['La metáfora es una figura literaria.', true]], ['Escribe una estrofa de cuatro versos con rima asonante.', 'Busca una metáfora en una canción conocida.'], mapa('Poesía', ['verso', 'estrofa', 'rima', 'medida', 'figura'])),
    u('lengua', 'len_medios', 'Los medios de comunicación', ['La noticia responde a qué, quién, cuándo, dónde, cómo y por qué.', 'El titular resume la noticia en pocas palabras.', 'Distinguir información de opinión es clave para leer bien.', 'Contrastar varias fuentes ayuda a detectar noticias falsas.'], ['noticia', 'titular', 'opinión', 'fuente', 'bulo'], [['El titular resume la noticia.', true], ['Información y opinión son lo mismo.', false], ['Contrastar fuentes ayuda a detectar bulos.', true]], ['Escribe una noticia breve sobre algo que pasó en tu escuela.', '¿Cómo comprobarías si una noticia es verdadera?'], flujo(['Qué', 'Quién', 'Cuándo', 'Dónde', 'Por qué']), BS),

    /* ───── Inglés ───── */
    u('ingles', 'ing_rutina', 'Daily routine', ['We use the present simple for routines: I get up at seven.', 'With he, she and it the verb takes -s: she gets up.', 'Adverbs of frequency go before the main verb: I always walk to school.', 'Common verbs: wake up, have breakfast, go to school, do homework.'], ['present simple', 'always', 'usually', 'never', 'routine'], [['«She get up» is correct.', false], ['Adverbs of frequency go before the main verb.', true], ['We use the present simple for routines.', true]], ['Write your daily routine with five sentences.', 'Ask a partner three questions about his or her day.'], flujo(['wake up', 'breakfast', 'school', 'homework', 'bed'])),
    u('ingles', 'ing_pasado', 'Past simple', ['Regular verbs add -ed in the past: played, watched.', 'Many common verbs are irregular: go → went, eat → ate.', 'Questions use did: Did you see the film?', 'Negatives use didn’t + base verb: I didn’t go.'], ['past simple', 'regular', 'irregular', 'did'], [['«Go» becomes «went» in the past.', true], ['Negatives use «didn’t» + past form.', false], ['Questions use «did».', true]], ['Write five things you did last weekend.', 'Make a list of ten irregular verbs.'], flujo(['base', 'past', 'question', 'negative'])),
    u('ingles', 'ing_futuro', 'Plans and predictions', ['«Going to» is for plans: I’m going to visit my grandma.', '«Will» is for predictions and quick decisions: It will rain.', 'Time expressions: tomorrow, next week, in 2030.', 'The present continuous also talks about fixed plans: I’m meeting Ana at five.'], ['going to', 'will', 'plan', 'prediction'], [['«Will» is used for predictions.', true], ['«Going to» never talks about plans.', false], ['«Tomorrow» is a time expression.', true]], ['Write three plans for the summer with «going to».', 'Make three predictions about the future with «will».'], mapa('Future', ['going to', 'will', 'present continuous'])),
    u('ingles', 'ing_compara', 'Comparing things', ['Short adjectives add -er: taller, faster.', 'Long adjectives use more: more expensive.', 'Superlatives: the tallest, the most expensive.', 'Irregular forms: good → better → the best; bad → worse → the worst.'], ['comparative', 'superlative', 'than', 'irregular'], [['«Good» becomes «better».', true], ['«Expensiver» is correct.', false], ['Superlatives use «the».', true]], ['Compare three cities of your country.', 'Write the superlative of five adjectives.'], flujo(['tall', 'taller', 'the tallest'])),
    u('ingles', 'ing_viaje', 'Travelling', ['At the airport: check-in, boarding pass, gate, luggage.', 'Asking for directions: Excuse me, where is the station?', 'Directions: turn left, go straight on, it’s next to the bank.', 'Polite requests: Could you help me, please?'], ['boarding pass', 'directions', 'turn left', 'polite request'], [['«Turn left» gives directions.', true], ['«Could you help me?» is rude.', false], ['A boarding pass is used at the airport.', true]], ['Write a dialogue asking for directions to a museum.', 'Make a checklist for an international trip.'], flujo(['check-in', 'security', 'gate', 'boarding']), BS)
  ];
  ED.registrar({ unidades: U });
  window.EU_UNIDADES_PLUS = { U: U };
})();
