/* b6_unidades_adultos.js — unidades nuevas para las materias de personas adultas (Emprendimiento,
   Marketing digital, IA desde cero, Redes sociales y Comercio electrónico). Con 12–14 unidades, un libro
   de 300 páginas repetía casi la mitad de sus frases. Cada unidad trae ideas, palabras clave, V/F,
   preguntas, figura, gancho y un generador propio con varias redacciones.
   Redes sociales incluye un bloque «Ingresos desde cero» (rs2_cero1…3): cómo pasar de 0 seguidores
   a los primeros ingresos sin esperar a la monetización de la plataforma.
   Cargar después de b6_comercio_electronico.js. */
(function () {
  'use strict';
  var ED = window.EU_EDITORIAL; if (!ED || window.EU_UNIDADES_ADULTOS) return;
  var H = ED.H, it = H.it, P = H.pick, FX = (window.EU_EMPRE && EU_EMPRE.FX) || { es: 1 };
  function E(r, a, b) { return a + Math.floor(r() * (b - a + 1)); }
  function bon(v) { if (v <= 0) return 0; if (v < 10) return Math.round(v * 10) / 10; var p = Math.pow(10, Math.max(0, Math.floor(Math.log10(v)) - 1)); return Math.round(v / p) * p; }
  function m(eur, C) { return bon(eur * (FX[C.pk] || 1)); }
  function $(v, C) { return H.din(v, C); }
  function n(x, C) { return H.num(x, C); }
  function r1(x) { return Math.round(x * 10) / 10; }

  var G = {
    emp2_valida: function (u, C, r) {
      var t = P(r, [20, 25, 30, 40, 50]), s = E(r, 3, Math.round(t * 0.6)), p = r1(s / t * 100);
      var q = P(r, ['Entrevistas a ' + t + ' posibles clientes y ' + s + ' dicen que pagarían por tu producto. ¿Qué porcentaje es?', 'En una prueba de mercado, ' + s + ' de ' + t + ' personas dejan su contacto para comprar. ¿Qué porcentaje de interés hay?', 'Muestras el prototipo a ' + t + ' personas; ' + s + ' hacen un pedido anticipado. ¿Cuál es la tasa de validación?']);
      return it('corta', q, n(p, C) + ' %', { ac: [p, n(p, C)], x: s + ' ÷ ' + t + ' × 100 = ' + n(p, C) + ' %' });
    },
    emp2_presu: function (u, C, r) {
      var a = m(P(r, [300, 500, 800, 1200]), C), b = m(P(r, [150, 250, 400]), C), g = m(P(r, [200, 350, 500, 700]), C), mes = P(r, [3, 4, 6]), t = a + b + g * mes;
      var q = P(r, ['Para empezar necesitas ' + $(a, C) + ' en equipo y ' + $(b, C) + ' en material. Quieres un colchón de ' + mes + ' meses de gastos fijos (' + $(g, C) + ' al mes). ¿Cuánto dinero reúnes?', 'Presupuesto inicial: equipo ' + $(a, C) + ', primer material ' + $(b, C) + ' y reserva para ' + mes + ' meses de gastos fijos de ' + $(g, C) + '. ¿Cuál es el total?']);
      return it('corta', q, $(t, C), { ac: [t], x: $(a, C) + ' + ' + $(b, C) + ' + ' + $(g, C) + ' × ' + mes + ' = ' + $(t, C) });
    },
    emp2_crece: function (u, C, r) {
      var v = P(r, [20, 30, 40, 50, 80]), p = P(r, [5, 10, 15, 20]), k = P(r, [3, 4, 6]), f = Math.round(v * Math.pow(1 + p / 100, k));
      var q = P(r, ['Vendes ' + v + ' unidades este mes y las ventas crecen un ' + p + ' % cada mes. ¿Cuántas venderás dentro de ' + k + ' meses? (redondea)', 'Un negocio atiende a ' + v + ' clientes al mes y crece un ' + p + ' % mensual. ¿Cuántos clientes tendrá en ' + k + ' meses?']);
      return it('corta', q, String(f), { ac: [f], x: v + ' × (1 + ' + p + ' ÷ 100) elevado a ' + k + ' ≈ ' + f });
    },
    mkt2_seo: function (u, C, r) {
      var b = P(r, [800, 1500, 2400, 5000, 12000]), pos = P(r, [[1, 28], [2, 15], [3, 11], [5, 6]]), v = Math.round(b * pos[1] / 100);
      var q = P(r, ['Una búsqueda tiene ' + n(b, C) + ' consultas al mes. En la posición ' + pos[0] + ' se recibe cerca del ' + pos[1] + ' % de los clics. ¿Cuántas visitas llegarían?', 'Si tu página aparece en el puesto ' + pos[0] + ' (CTR aproximado del ' + pos[1] + ' %) para una palabra con ' + n(b, C) + ' búsquedas mensuales, ¿cuántas visitas esperas?']);
      return it('corta', q, n(v, C), { ac: [v], x: n(b, C) + ' × ' + pos[1] + ' ÷ 100 = ' + n(v, C) });
    },
    mkt2_retar: function (u, C, r) {
      var v = P(r, [1000, 2000, 4000, 6000]), ab = P(r, [60, 70, 75, 80]), rc = P(r, [3, 5, 8]), c = Math.round(v * ab / 100 * rc / 100);
      var q = P(r, [n(v, C) + ' personas visitan la tienda y el ' + ab + ' % abandona el carrito. Un anuncio de retargeting recupera al ' + rc + ' % de ellas. ¿Cuántas compras recuperas?', 'De ' + n(v, C) + ' visitas, el ' + ab + ' % se va sin comprar. Si el recordatorio convierte al ' + rc + ' % de esas personas, ¿cuántas ventas más consigues?']);
      return it('corta', q, n(c, C), { ac: [c], x: n(v, C) + ' × ' + ab + ' % × ' + rc + ' % = ' + n(c, C) });
    },
    mkt2_reparto: function (u, C, r) {
      var t = m(P(r, [500, 800, 1000, 2000]), C), c = P(r, [['buscadores', 40], ['redes', 35], ['correo', 10], ['vídeo', 25], ['retargeting', 15]]), v = bon(t * c[1] / 100);
      var q = P(r, ['Tienes ' + $(t, C) + ' al mes para publicidad y decides dedicar el ' + c[1] + ' % a ' + c[0] + '. ¿Cuánto es?', 'En el plan de medios, ' + c[0] + ' recibe el ' + c[1] + ' % de un presupuesto de ' + $(t, C) + '. ¿Qué importe le asignas?']);
      return it('corta', q, $(v, C), { ac: [v], x: $(t, C) + ' × ' + c[1] + ' ÷ 100 = ' + $(v, C) });
    },
    ia2_split: function (u, C, r) {
      var t = P(r, [500, 1000, 2400, 5000, 12000]), p = P(r, [70, 75, 80, 90]), e = Math.round(t * p / 100), pr = t - e;
      var q = P(r, ['Tienes ' + n(t, C) + ' ejemplos etiquetados. Usas el ' + p + ' % para entrenar y el resto para probar. ¿Cuántos quedan para la prueba?', 'Un conjunto de datos tiene ' + n(t, C) + ' filas. Si separas un ' + (100 - p) + ' % para validar el modelo, ¿cuántas filas son?']);
      return it('corta', q, n(pr, C), { ac: [pr], x: n(t, C) + ' × ' + (100 - p) + ' ÷ 100 = ' + n(pr, C) });
    },
    ia2_sesgo: function (u, C, r) {
      var na = P(r, [200, 400, 500]), ea = E(r, 6, 20), nb = P(r, [100, 200, 250]), eb = E(r, 12, 40), pa = r1(ea / na * 100), pb = r1(eb / nb * 100), d = r1(Math.abs(pb - pa));
      var q = P(r, ['Un modelo se equivoca en ' + ea + ' de ' + na + ' casos del grupo A y en ' + eb + ' de ' + nb + ' del grupo B. ¿Cuántos puntos porcentuales de diferencia hay en la tasa de error?', 'Auditoría de sesgo: grupo A, ' + ea + ' errores en ' + na + ' casos; grupo B, ' + eb + ' errores en ' + nb + '. ¿Qué diferencia de error hay entre grupos, en puntos?']);
      return it('corta', q, n(d, C) + ' puntos', { ac: [d, n(d, C)], x: 'A: ' + n(pa, C) + ' %; B: ' + n(pb, C) + ' %; diferencia ' + n(d, C) });
    },
    ia2_tokens: function (u, C, r) {
      var c = P(r, [0.5, 1, 2, 3]), k = P(r, [40, 120, 300, 800]), t = r1(c * k);
      var q = P(r, ['Un servicio de IA cobra ' + n(c, C) + ' céntimos por cada mil unidades de texto (tokens). Si tu tarea usa ' + k + ' mil tokens, ¿cuántos céntimos cuesta?', 'Procesar mil tokens cuesta ' + n(c, C) + ' céntimos. ¿Cuánto cuestan ' + k + ' mil tokens?']);
      return it('corta', q, n(t, C) + ' céntimos', { ac: [t, n(t, C)], x: n(c, C) + ' × ' + k + ' = ' + n(t, C) });
    },
    rs2_publica: function (u, C, r) {
      var p = P(r, [3, 4, 5, 7]), s = P(r, [4, 8, 12, 13]), t = p * s;
      var q = P(r, ['Empiezas desde cero y publicas ' + p + ' veces por semana durante ' + s + ' semanas. ¿Cuántas publicaciones tendrás?', 'Tu plan es subir ' + p + ' vídeos cortos a la semana. ¿Cuántos habrás publicado en ' + s + ' semanas?']);
      return it('corta', q, String(t), { ac: [t], x: p + ' × ' + s + ' = ' + t });
    },
    rs2_ugc: function (u, C, r) {
      var pr = m(P(r, [60, 80, 100, 150]), C), k = E(r, 2, 8), t = pr * k;
      var q = P(r, ['Sin seguidores puedes vender vídeos UGC a marcas. Si cobras ' + $(pr, C) + ' por vídeo y haces ' + k + ' al mes, ¿cuánto ingresas?', 'Gestionas las redes de un comercio del barrio y creas ' + k + ' piezas al mes a ' + $(pr, C) + ' cada una. ¿Cuál es tu ingreso mensual?']);
      return it('corta', q, $(t, C), { ac: [t], x: $(pr, C) + ' × ' + k + ' = ' + $(t, C) });
    },
    rs2_seg: function (u, C, r) {
      var s = P(r, [0, 50, 120, 300]), w = P(r, [40, 60, 80, 120]), k = P(r, [8, 12, 16, 26]), t = s + w * k;
      var q = P(r, ['Tienes ' + s + ' seguidores y ganas unos ' + w + ' por semana. ¿Cuántos tendrás en ' + k + ' semanas?', 'Una cuenta nueva arranca con ' + s + ' seguidores y suma ' + w + ' cada semana. ¿Cuántos habrá tras ' + k + ' semanas?']);
      return it('corta', q, n(t, C), { ac: [t], x: s + ' + ' + w + ' × ' + k + ' = ' + n(t, C) });
    },
    ec2_pedido: function (u, C, r) {
      var a = m(P(r, [0.5, 0.8, 1.2]), C), b = m(P(r, [0.4, 0.6, 1]), C), c = m(P(r, [3.5, 4.5, 6]), C), t = r1(a + b + c);
      var q = P(r, ['Preparar un pedido cuesta ' + $(a, C) + ' de mano de obra, ' + $(b, C) + ' de embalaje y ' + $(c, C) + ' de envío. ¿Cuánto cuesta cada pedido?', 'Coste logístico por pedido: preparación ' + $(a, C) + ', caja y relleno ' + $(b, C) + ', transportista ' + $(c, C) + '. ¿Total?']);
      return it('corta', q, $(t, C), { ac: [t], x: $(a, C) + ' + ' + $(b, C) + ' + ' + $(c, C) + ' = ' + $(t, C) });
    },
    ec2_rota: function (u, C, r) {
      var inv = m(P(r, [2000, 3000, 5000]), C), k = P(r, [4, 6, 8, 12]), cv = inv * k, d = Math.round(365 / k);
      var q = P(r, ['El costo de lo vendido en un año es ' + $(cv, C) + ' y el inventario medio vale ' + $(inv, C) + '. ¿Cuántas veces rota el inventario al año?', 'Vendes al año mercancía que te costó ' + $(cv, C) + ' y mantienes de media ' + $(inv, C) + ' en stock. ¿Cuál es la rotación?']);
      return it('corta', q, k + ' veces', { ac: [k], x: $(cv, C) + ' ÷ ' + $(inv, C) + ' = ' + k + ' (unos ' + d + ' días por rotación)' });
    },
    ec2_roi: function (u, C, r) {
      var i = m(P(r, [500, 1000, 2000, 4000]), C), p = P(r, [20, 35, 50, 80, 120]), g = bon(i * (1 + p / 100));
      var q = P(r, ['Inviertes ' + $(i, C) + ' en la tienda y en un año obtienes ' + $(g, C) + ' de beneficio bruto. ¿Cuál es el ROI?', 'Una campaña de ' + $(i, C) + ' deja ' + $(g, C) + ' de margen. ¿Qué retorno sobre la inversión tiene?']);
      var roi = Math.round((g - i) / i * 100);
      return it('corta', q, roi + ' %', { ac: [roi], x: '(' + $(g, C) + ' − ' + $(i, C) + ') ÷ ' + $(i, C) + ' × 100 ≈ ' + roi + ' %' });
    }
  };

  var U = [], B = 'sec bach fp adu'.split(' ');
  function un(mat, id, t, g, i, k, vf, q, f, h) { U.push({ m: mat, id: id, b: B, t: t, g: g, i: i, k: k, vf: vf.split('|').map(function (s) { return [s.slice(2), s.charAt(0) === 'V']; }), q: q, f: f, h: h, plus: true }); }
  function fl(p) { return { t: 'flujo', p: p }; }
  function ma(c, r) { return { t: 'mapa', c: c, r: r }; }
  function ci(p) { return { t: 'ciclo', p: p }; }

  /* ───── Emprendimiento ───── */
  un('empre', 'emp2_validar', 'Validar la idea antes de invertir', 'emp2_valida', ['Validar es conseguir pruebas de que alguien pagará, antes de gastar en equipo o local.', 'La prueba más fuerte no es un «me gusta», es un pago o una reserva con señal.', 'Las entrevistas funcionan mejor si preguntas por lo que la persona hizo, no por lo que haría.', 'Si tras veinte entrevistas nadie tiene el problema, la idea necesita cambiar.'], ['validación', 'hipótesis', 'entrevista', 'preventa', 'señal'], 'V:Una preventa es una prueba más fuerte que una opinión.|F:Si a tu familia le gusta, la idea está validada.|V:Conviene preguntar por hechos pasados.', ['Escribe la hipótesis principal de tu negocio en una frase.', 'Prepara cinco preguntas de entrevista sobre hechos, no opiniones.'], fl(['hipótesis', 'entrevistas', 'prototipo', 'preventa', 'decisión']), '¿Alguien te ha pagado ya por tu idea?');
  un('empre', 'emp2_test', 'El producto mínimo', 'emp2_valida', ['El producto mínimo viable es la versión más sencilla que resuelve el problema principal.', 'Puede ser una muestra hecha a mano, una página con formulario o un servicio prestado en persona.', 'Sirve para aprender rápido y barato qué quiere de verdad el cliente.', 'Cada prueba se mide: cuántos ven, cuántos preguntan y cuántos compran.'], ['producto mínimo viable', 'prototipo', 'iteración', 'aprendizaje', 'medición'], 'V:El producto mínimo puede hacerse a mano.|F:El producto mínimo debe estar terminado y perfecto.|V:Cada prueba debe medirse.', ['Describe la versión más sencilla de tu producto.', '¿Qué medirías en la primera semana de prueba?'], ci(['construir', 'mostrar', 'medir', 'aprender', 'mejorar']), '¿Qué es lo mínimo que podrías vender mañana?');
  un('empre', 'emp2_presupuesto', 'El presupuesto inicial', 'emp2_presu', ['El presupuesto inicial suma todo lo necesario para abrir: equipo, material, trámites y promoción.', 'A esa suma se añade un colchón para varios meses de gastos fijos.', 'Muchos negocios cierran por falta de caja, no por falta de clientes.', 'Separar gastos imprescindibles de deseables ayuda a empezar con menos.'], ['inversión inicial', 'colchón', 'gasto fijo', 'caja', 'prioridad'], 'V:El colchón cubre gastos fijos mientras llegan ventas.|F:El presupuesto solo incluye el equipo.|V:Falta de caja es causa frecuente de cierre.', ['Haz una lista de gastos imprescindibles y deseables.', 'Calcula tu colchón de tres meses.'], ma('Presupuesto', ['equipo', 'material', 'trámites', 'promoción', 'colchón']), '¿Cuántos meses aguantaría tu negocio sin vender?');
  un('empre', 'emp2_legal', 'Elegir la forma legal', 'emp_iva', ['La forma legal decide quién responde de las deudas, qué impuestos se pagan y qué trámites hay.', 'Como persona física se empieza rápido, pero se responde con el patrimonio propio.', 'Una sociedad separa el patrimonio, aunque exige más trámites y contabilidad.', 'Muchos países tienen regímenes simplificados para ingresos pequeños.'], ['persona física', 'sociedad', 'responsabilidad', 'régimen simplificado', 'alta'], 'V:La forma legal influye en los impuestos.|F:Una sociedad no tiene trámites.|V:Hay regímenes para ingresos pequeños.', ['Compara dos formas legales de tu país.', '¿Qué forma elegirías para empezar y por qué?'], fl(['actividad', 'ingresos previstos', 'riesgo', 'forma legal', 'alta']), '¿Responderías de las deudas con tu casa?');
  un('empre', 'emp2_financia', 'Pedir financiación', 'emp_roi', ['Las fuentes habituales son ahorro propio, familia, microcréditos, bancos y ayudas públicas.', 'Quien presta quiere saber cuánto necesitas, para qué y cuándo lo devolverás.', 'Una carta de financiación resume el negocio, la cantidad, el uso del dinero y el plan de pago.', 'Pedir menos y crecer con las ventas reduce el riesgo.'], ['microcrédito', 'aval', 'plan de pago', 'ayuda pública', 'interés'], 'V:Quien presta quiere ver el plan de pago.|F:Pedir más dinero siempre es mejor.|V:Existen ayudas públicas para emprender.', ['Redacta una carta breve pidiendo un microcrédito.', 'Explica en qué gastarías cada parte del préstamo.'], fl(['cantidad', 'uso', 'plan de pago', 'garantías', 'solicitud']), '¿Cómo convencerías a alguien de prestarte dinero?');
  un('empre', 'emp2_pitch', 'Presentar el negocio en dos minutos', 'emp_ganancia', ['Un pitch es una presentación corta del negocio para clientes, socios o inversores.', 'Sigue un orden: problema, solución, cliente, cómo ganas dinero y qué pides.', 'Un dato propio (ventas, pedidos, encuestas) convence más que muchos adjetivos.', 'Se ensaya en voz alta y se cronometra.'], ['pitch', 'problema', 'solución', 'tracción', 'petición'], 'V:El pitch termina con una petición clara.|F:Cuantos más adjetivos, mejor.|V:Hay que ensayarlo cronometrado.', ['Escribe el guion de tu pitch en cinco frases.', '¿Qué dato propio mostrarías?'], fl(['problema', 'solución', 'cliente', 'modelo', 'petición']), '¿Puedes explicar tu negocio antes de que se enfríe un café?');
  un('empre', 'emp2_escala', 'Crecer y escalar', 'emp2_crece', ['Crecer es vender más; escalar es vender más sin que los costos crezcan al mismo ritmo.', 'Documentar los procesos permite delegar sin perder calidad.', 'Antes de contratar conviene automatizar o externalizar tareas repetitivas.', 'Crecer demasiado rápido puede dejar el negocio sin caja.'], ['escalar', 'proceso', 'delegar', 'automatizar', 'crecimiento'], 'V:Escalar es crecer sin que los costos suban igual.|F:Crecer rápido nunca tiene riesgos.|V:Documentar procesos ayuda a delegar.', ['Escribe paso a paso una tarea que repites cada día.', '¿Qué tarea delegarías primero?'], ci(['vender', 'documentar', 'delegar', 'medir', 'crecer']), '¿Qué pasaría si mañana tuvieras el doble de pedidos?');

  /* ───── Marketing digital ───── */
  un('mkt', 'mkt2_auditseo', 'Auditoría SEO paso a paso', 'mkt2_seo', ['Una auditoría SEO revisa si los buscadores pueden encontrar, leer y valorar una web.', 'Se comprueba la velocidad, que funcione bien en el móvil y que cada página tenga título y descripción.', 'Después se revisan las palabras clave y si el contenido responde a lo que se busca.', 'El resultado es una lista de tareas ordenadas por impacto y esfuerzo.'], ['auditoría', 'velocidad', 'título', 'metadescripción', 'indexación'], 'V:La auditoría revisa también la versión móvil.|F:Basta con revisar el logotipo.|V:Las tareas se ordenan por impacto.', ['Revisa el título y la descripción de tres páginas de un comercio.', 'Ordena cinco tareas por impacto y esfuerzo.'], fl(['rastreo', 'velocidad', 'móvil', 'contenido', 'enlaces']), '¿Tu web aparece cuando buscas tu propio servicio?');
  un('mkt', 'mkt2_canales', 'Contenido para cada canal', 'mkt_conv', ['Cada canal pide un formato: vídeo vertical, carrusel, artículo o correo.', 'Una idea central se adapta a varios canales sin copiarla igual.', 'El calendario editorial reparte temas y formatos a lo largo del mes.', 'Se mide qué canal trae contactos, no solo cuál tiene más visitas.'], ['canal', 'formato', 'calendario editorial', 'adaptar', 'contacto'], 'V:Una idea se puede adaptar a varios canales.|F:Todos los canales usan el mismo formato.|V:Importa qué canal trae contactos.', ['Adapta una misma idea a tres canales.', 'Diseña un calendario de cuatro semanas.'], ma('Una idea', ['vídeo corto', 'carrusel', 'artículo', 'correo']), '¿Dónde está tu cliente cuando tiene el problema?');
  un('mkt', 'mkt2_compe', 'Analizar a la competencia', 'mkt_cpc', ['Analizar a la competencia es ver qué ofrecen, a qué precio y cómo comunican.', 'Las reseñas de sus clientes muestran lo que valoran y lo que les molesta.', 'Las bibliotecas públicas de anuncios dejan ver qué campañas tienen activas.', 'El objetivo es encontrar un hueco, no copiar.'], ['competencia', 'reseñas', 'biblioteca de anuncios', 'diferenciación', 'hueco'], 'V:Las reseñas ajenas dan información útil.|F:Analizar la competencia es copiarla.|V:Se buscan huecos sin cubrir.', ['Compara tres competidores en precio, mensaje y canal.', 'Lee diez reseñas y anota tres quejas repetidas.'], ma('Competencia', ['oferta', 'precio', 'mensaje', 'canal', 'reseñas']), '¿Qué no hace bien tu competencia?');
  un('mkt', 'mkt2_medios', 'El plan de medios pagados', 'mkt2_reparto', ['Un plan de medios dice cuánto se gasta, en qué canal, cuándo y con qué objetivo.', 'Se empieza con poco presupuesto y se sube en lo que funciona.', 'Cada canal tiene un objetivo distinto: dar a conocer, atraer visitas o vender.', 'Se fija de antemano cuánto se puede pagar por cliente.'], ['plan de medios', 'presupuesto', 'objetivo', 'CPA máximo', 'reparto'], 'V:Se sube el gasto en lo que funciona.|F:Todo el presupuesto va a un solo anuncio desde el primer día.|V:Conviene fijar un costo máximo por cliente.', ['Reparte un presupuesto mensual entre tres canales.', '¿Cuánto puedes pagar como máximo por un cliente?'], fl(['objetivo', 'canales', 'reparto', 'prueba', 'ajuste']), '¿Cuánto vale para ti un cliente nuevo?');
  un('mkt', 'mkt2_retarget', 'Retargeting', 'mkt2_retar', ['El retargeting muestra anuncios a quien ya visitó tu web o tu perfil.', 'Funciona porque la mayoría no compra en la primera visita.', 'Se segmenta por lo que hizo: vio un producto, añadió al carrito o empezó a pagar.', 'Hay que limitar la frecuencia para no cansar y respetar el consentimiento de cookies.'], ['retargeting', 'píxel', 'carrito abandonado', 'frecuencia', 'consentimiento'], 'V:La mayoría no compra en la primera visita.|F:El retargeting no necesita consentimiento.|V:Conviene limitar la frecuencia.', ['Diseña tres anuncios para tres tipos de visitante.', 'Calcula las compras recuperadas de una campaña.'], fl(['visita', 'abandono', 'recordatorio', 'vuelta', 'compra']), '¿Por qué ves el anuncio de algo que miraste ayer?');
  un('mkt', 'mkt2_auto', 'Automatizar el marketing', 'mkt_email', ['Automatizar es dejar preparados mensajes que se envían solos cuando pasa algo.', 'Ejemplos: bienvenida al suscribirse, recordatorio de carrito y felicitación de cumpleaños.', 'Cada secuencia tiene un disparador, una espera y un mensaje.', 'Se revisa cada mes: qué se abre, qué se pulsa y qué se deja de leer.'], ['automatización', 'disparador', 'secuencia', 'bienvenida', 'segmento'], 'V:Una secuencia empieza con un disparador.|F:Automatizar significa no revisar nunca.|V:La bienvenida es una secuencia habitual.', ['Escribe una secuencia de bienvenida de tres correos.', '¿Qué disparador usarías en tu negocio?'], fl(['disparador', 'espera', 'mensaje', 'espera', 'oferta']), '¿Qué mensaje repites a mano todas las semanas?');

  /* ───── IA desde cero ───── */
  un('ia', 'ia2_tipos', 'Tipos de inteligencia artificial', 'ia_precision', ['La IA de clasificación decide a qué grupo pertenece algo: correo deseado o no deseado.', 'La de predicción estima un número: ventas del mes o tiempo de entrega.', 'La generativa crea texto, imágenes, audio o código nuevos.', 'La mayoría de herramientas combinan varias de estas capacidades.'], ['clasificación', 'predicción', 'generativa', 'recomendación', 'modelo'], 'V:Un filtro de correo no deseado clasifica.|F:Toda la IA genera imágenes.|V:Predecir ventas es una tarea de predicción.', ['Clasifica cinco herramientas que uses según su tipo de IA.', 'Pon un ejemplo de predicción en un negocio.'], ma('Tipos de IA', ['clasificar', 'predecir', 'recomendar', 'generar']), '¿Qué IA has usado hoy sin darte cuenta?');
  un('ia', 'ia2_datos', 'Los datos que alimentan la IA', 'ia2_split', ['Un modelo aprende de ejemplos: cuantos más y mejores, mejor funciona.', 'Los datos se limpian: se quitan duplicados, errores y huecos.', 'Se separan en datos de entrenamiento y de prueba para no hacerse trampas.', 'Si los datos no representan a todos, el modelo tampoco lo hará.'], ['conjunto de datos', 'etiqueta', 'limpieza', 'entrenamiento', 'prueba'], 'V:Los datos de prueba no se usan para entrenar.|F:Los datos con errores no afectan al modelo.|V:Los datos deben representar a todos.', ['Describe qué datos harían falta para predecir las ventas de una tienda.', '¿Por qué se separan datos de prueba?'], fl(['recoger', 'limpiar', 'etiquetar', 'separar', 'entrenar']), '¿Qué pasa si enseñas con ejemplos equivocados?');
  un('ia', 'ia2_validar', 'Comprobar si un modelo funciona', 'ia_precision', ['La precisión dice qué parte de las respuestas son correctas.', 'Un modelo puede acertar mucho de media y fallar en los casos importantes.', 'La matriz de confusión separa aciertos, falsos positivos y falsos negativos.', 'Siempre se prueba con datos que el modelo no vio al entrenar.'], ['precisión', 'falso positivo', 'falso negativo', 'matriz de confusión', 'validación'], 'V:Se prueba con datos no vistos.|F:Alta precisión media garantiza acertar en todo.|V:La matriz de confusión separa tipos de error.', ['Explica con un ejemplo un falso positivo y un falso negativo.', '¿Qué error sería más grave en un detector de fraude?'], ma('Resultados', ['verdadero positivo', 'falso positivo', 'falso negativo', 'verdadero negativo']), '¿Qué error es peor: una falsa alarma o no detectar nada?');
  un('ia', 'ia2_sesgos', 'Sesgos en la IA', 'ia2_sesgo', ['Un sesgo aparece cuando el modelo trata peor a un grupo de personas.', 'Suele venir de datos desequilibrados o de decisiones pasadas injustas.', 'Se detecta comparando el error entre grupos.', 'Se corrige equilibrando datos, revisando variables y con supervisión humana.'], ['sesgo', 'equidad', 'datos desequilibrados', 'auditoría', 'supervisión humana'], 'V:El sesgo puede venir de los datos.|F:Una máquina nunca puede ser injusta.|V:Se compara el error entre grupos.', ['Busca un caso conocido de sesgo en un sistema automático.', 'Propón dos formas de reducir un sesgo.'], fl(['datos', 'modelo', 'comparar grupos', 'corregir', 'revisar']), '¿Puede una máquina aprender nuestros prejuicios?');
  un('ia', 'ia2_casos', 'Casos de uso en pequeños negocios', 'ia_tiempo', ['Atención al cliente: respuestas rápidas a preguntas frecuentes, revisadas por una persona.', 'Contenido: borradores de descripciones, publicaciones y correos.', 'Gestión: resumir facturas, ordenar pedidos o preparar informes.', 'El valor se mide en horas ahorradas y en errores evitados.'], ['caso de uso', 'preguntas frecuentes', 'borrador', 'informe', 'horas ahorradas'], 'V:Las respuestas automáticas deben revisarse.|F:La IA sustituye toda la atención al cliente.|V:El ahorro se mide en horas.', ['Elige tres tareas de un negocio que podría apoyar la IA.', 'Calcula las horas que ahorraría al mes.'], ma('Pequeño negocio', ['atención', 'contenido', 'gestión', 'análisis']), '¿Qué tarea te quita más tiempo cada semana?');
  un('ia', 'ia2_ley', 'La IA y la ley', 'ia2_tokens', ['La Unión Europea aprobó en 2024 el Reglamento de Inteligencia Artificial, que clasifica los usos por nivel de riesgo.', 'Algunos usos están prohibidos, otros exigen controles y otros solo transparencia.', 'Las leyes de protección de datos también se aplican: no se suben datos personales sin permiso.', 'En América Latina varios países preparan normas propias; conviene revisar la de tu país.'], ['reglamento', 'nivel de riesgo', 'transparencia', 'datos personales', 'consentimiento'], 'V:El reglamento europeo clasifica por riesgo.|F:Se pueden subir datos de clientes sin permiso.|V:Algunos usos exigen transparencia.', ['Explica los niveles de riesgo con un ejemplo cada uno.', '¿Qué datos no subirías nunca a una herramienta de IA?'], fl(['uso', 'riesgo', 'obligaciones', 'control', 'revisión']), '¿Quién responde si una IA se equivoca?');
  un('ia', 'ia2_etica', 'Decidir con ética', 'ia_costo', ['Usar IA con ética es preguntarse a quién beneficia y a quién puede perjudicar.', 'Hay que decir cuándo un texto o una imagen se ha hecho con IA.', 'Las decisiones importantes sobre personas deben tener revisión humana.', 'Respetar derechos de autor y privacidad es parte del trabajo.'], ['ética', 'transparencia', 'revisión humana', 'derechos de autor', 'privacidad'], 'V:Conviene avisar cuando se usa IA.|F:Las decisiones sobre personas pueden ser 100 % automáticas sin revisión.|V:La privacidad forma parte de la ética.', ['Escribe tres normas éticas para usar IA en tu trabajo.', 'Analiza un caso: ¿quién gana y quién pierde?'], ma('Ética', ['beneficio', 'daño', 'transparencia', 'revisión', 'derechos']), '¿Firmarías un trabajo hecho por una IA?');
  un('ia', 'ia2_futuro', 'Trabajo y futuro', 'ia_tiempo', ['La IA cambia tareas más que empleos completos: automatiza partes del trabajo.', 'Ganan valor las habilidades de criterio, trato con personas y revisión.', 'Aprender a combinar IA con un oficio concreto es una ventaja.', 'La formación continua es la mejor protección ante los cambios.'], ['automatización', 'tarea', 'habilidad', 'formación continua', 'criterio'], 'V:La IA suele automatizar tareas concretas.|F:El criterio humano ya no hace falta.|V:Combinar IA con un oficio es una ventaja.', ['Divide tu trabajo en tareas y marca cuáles podría apoyar la IA.', 'Diseña un plan de formación de tres meses.'], fl(['tareas', 'automatizables', 'nuevas habilidades', 'práctica', 'oficio mejorado']), '¿Qué parte de tu trabajo nunca haría una máquina?');

  /* ───── Redes sociales ───── */
  un('redes', 'rs2_cero1', 'Ingresos desde cero (1): la cuenta que vende', 'rs2_publica', ['Con cero seguidores se empieza eligiendo un tema, un público y un problema que sabes resolver.', 'El perfil dice en una línea qué haces, para quién y cómo contactarte.', 'Durante las primeras 12 semanas importa más publicar con constancia que acertar a la primera.', 'Cada publicación responde a una pregunta real de tu público.'], ['perfil', 'biografía', 'constancia', 'tema', 'público'], 'V:El perfil debe decir qué haces y para quién.|F:Hay que esperar a tener seguidores para empezar.|V:La constancia pesa más al principio.', ['Escribe la biografía de tu perfil en una línea.', 'Anota diez preguntas de tu público para diez publicaciones.'], fl(['tema', 'perfil', '30 ideas', 'publicar', 'revisar']), '¿Qué sabes hacer que otras personas buscan?');
  un('redes', 'rs2_cero2', 'Ingresos desde cero (2): cobrar sin seguidores', 'rs2_ugc', ['No hace falta una audiencia grande para cobrar: se puede vender un servicio.', 'Vídeos UGC para marcas, gestión de redes de comercios locales, edición de vídeo o diseño de publicaciones.', 'El portafolio se hace con tres piezas de muestra para negocios reales o inventados.', 'Se contacta a diez negocios por semana con una propuesta concreta y un precio.'], ['UGC', 'servicio', 'portafolio', 'propuesta', 'tarifa'], 'V:Se puede cobrar por servicios sin tener muchos seguidores.|F:Los vídeos UGC se publican en la cuenta del creador.|V:Tres piezas de muestra bastan para empezar.', ['Crea tres piezas de muestra para un comercio de tu barrio.', 'Redacta un mensaje de propuesta con precio.'], fl(['servicio', 'muestras', 'propuesta', 'primer cliente', 'reseña']), '¿Qué negocio cercano necesita mejores publicaciones?');
  un('redes', 'rs2_cero3', 'Ingresos desde cero (3): del primer cobro al ingreso fijo', 'rs2_seg', ['El primer cliente se convierte en ingreso fijo con un paquete mensual.', 'Con la audiencia llegan la afiliación y los productos digitales propios.', 'La monetización de la plataforma llega después: YouTube pide 1 000 suscriptores y 4 000 horas vistas o 10 millones de vistas de Shorts, y TikTok Creator Rewards 10 000 seguidores.', 'Se lleva un registro de ingresos por fuente para ver qué conviene reforzar; los requisitos cambian y hay que revisarlos.'], ['paquete mensual', 'afiliación', 'producto digital', 'monetización', 'registro de ingresos'], 'V:Un paquete mensual da ingresos estables.|F:La monetización de la plataforma llega el primer día.|V:Conviene registrar ingresos por fuente.', ['Diseña un paquete mensual con precio.', 'Haz una tabla de ingresos por fuente para seis meses.'], fl(['servicio', 'paquete mensual', 'afiliación', 'producto propio', 'monetización']), '¿Cuánto tardarías en tener tu primer ingreso fijo?');
  un('redes', 'rs2_audiencia', 'Conocer a tu audiencia', 'redes_eng', ['Las estadísticas de la cuenta muestran edad, país, horas de conexión y qué contenido retiene.', 'La retención dice en qué segundo se va la gente de un vídeo.', 'Los comentarios y mensajes revelan qué preguntas se repiten.', 'Con esos datos se decide qué repetir y qué dejar.'], ['estadísticas', 'retención', 'demografía', 'hora de conexión', 'comentarios'], 'V:La retención muestra dónde se va la gente.|F:Las estadísticas solo sirven a grandes cuentas.|V:Los comentarios dan ideas de contenido.', ['Revisa las estadísticas de una cuenta y anota tres datos.', '¿En qué segundo pierde gente tu último vídeo?'], ma('Audiencia', ['edad', 'país', 'horario', 'retención', 'preguntas']), '¿Quién ve realmente lo que publicas?');
  un('redes', 'rs2_viral', 'Por qué un contenido se comparte', 'redes_engalc', ['Se comparte lo que hace quedar bien a quien lo comparte: útil, divertido o sorprendente.', 'Los primeros segundos deciden si alguien sigue mirando.', 'Un gancho claro, una promesa y un final que invite a guardar o comentar.', 'Lo viral no se garantiza; lo que se puede controlar es la calidad y la frecuencia.'], ['gancho', 'retención', 'compartir', 'guardar', 'tendencia'], 'V:Los primeros segundos son decisivos.|F:Lo viral se puede garantizar.|V:Se comparte lo útil o sorprendente.', ['Escribe tres ganchos para un mismo vídeo.', 'Analiza por qué se compartió un vídeo que viste.'], fl(['gancho', 'promesa', 'desarrollo', 'final', 'llamada']), '¿Qué fue lo último que reenviaste a alguien?');
  un('redes', 'rs2_comunidad', 'Comunidad frente a seguidores', 'redes_com', ['Un seguidor mira; un miembro de la comunidad participa y vuelve.', 'Responder comentarios y mensajes convierte seguidores en comunidad.', 'Los grupos, canales y transmisiones en directo refuerzan el vínculo.', 'Una comunidad pequeña y activa vende más que una grande y dormida.'], ['comunidad', 'participación', 'directo', 'canal', 'fidelidad'], 'V:Responder comentarios crea comunidad.|F:Más seguidores siempre significa más ventas.|V:Una comunidad pequeña puede vender mucho.', ['Diseña una actividad semanal para tu comunidad.', '¿Qué canal usarías para hablar con tus seguidores más fieles?'], ci(['atraer', 'conversar', 'reunir', 'cuidar', 'volver']), '¿Cuántos de tus seguidores te escribirían si desaparecieras?');
  un('redes', 'rs2_crisis', 'Crisis y reputación', 'redes_imp', ['Una crisis empieza con una queja o un error que se extiende.', 'Se responde pronto, con calma y en público, y se sigue por mensaje privado.', 'Borrar críticas suele empeorar la situación.', 'Tener preparado un protocolo ahorra decisiones en caliente.'], ['crisis', 'reputación', 'protocolo', 'disculpa', 'respuesta'], 'V:Conviene responder pronto y con calma.|F:Borrar las críticas soluciona la crisis.|V:Un protocolo evita decisiones en caliente.', ['Escribe la respuesta a una queja pública.', 'Redacta un protocolo de crisis de cinco pasos.'], fl(['detectar', 'valorar', 'responder', 'resolver', 'aprender']), '¿Qué harías si mañana te critican en público?');
  un('redes', 'rs2_herramientas', 'Herramientas de gestión', 'redes_hora', ['Las herramientas de programación publican a la hora elegida en varias redes.', 'Los editores de vídeo del móvil bastan para empezar.', 'Una hoja de cálculo sirve de calendario y de registro de resultados.', 'Menos herramientas bien usadas rinden más que muchas a medias.'], ['programar', 'editor', 'calendario', 'plantilla', 'registro'], 'V:Se puede programar publicaciones.|F:Hace falta un equipo caro para empezar.|V:Una hoja de cálculo sirve de calendario.', ['Monta tu calendario mensual en una hoja de cálculo.', 'Elige tres herramientas y explica para qué usarías cada una.'], ma('Herramientas', ['grabar', 'editar', 'programar', 'medir', 'responder']), '¿Cuánto tiempo te ahorraría programar una semana de publicaciones?');
  un('redes', 'rs2_local', 'Casos de negocio local', 'redes_conv', ['Un comercio de barrio gana más con clientes cercanos que con miles de vistas lejanas.', 'Mostrar el detrás de escena genera confianza: cómo se hace, quién lo hace.', 'Etiquetar la ubicación y colaborar con otros negocios de la zona amplía el alcance.', 'Se mide cuántas personas llegan diciendo «te vi en redes».'], ['negocio local', 'ubicación', 'detrás de escena', 'colaboración', 'confianza'], 'V:El detrás de escena genera confianza.|F:Un comercio local necesita alcance mundial.|V:Colaborar con vecinos amplía el alcance.', ['Diseña tres publicaciones para una panadería de barrio.', '¿Cómo medirías las visitas que llegan por redes?'], fl(['mostrar', 'etiquetar', 'colaborar', 'invitar', 'medir']), '¿Qué comercio de tu barrio te gustaría ver en redes?');

  /* ───── Comercio electrónico ───── */
  un('ecom', 'ec2_nicho', 'Encontrar un nicho', 'ecom_ticket', ['Un nicho es un grupo concreto de clientes con una necesidad que las tiendas grandes atienden mal.', 'Las búsquedas y las preguntas en foros muestran si hay demanda.', 'Conviene que el producto sea ligero, no frágil y con margen suficiente para el envío.', 'Un nicho pequeño y fiel rinde más que competir con todo el mundo.'], ['nicho', 'demanda', 'margen', 'producto ligero', 'fidelidad'], 'V:Un nicho es un grupo concreto de clientes.|F:Lo mejor es vender de todo a todos.|V:Los productos ligeros abaratan el envío.', ['Propón tres nichos y compáralos.', '¿Qué producto de tu nicho es ligero y con margen?'], ma('Nicho', ['cliente', 'necesidad', 'demanda', 'margen', 'envío']), '¿Qué buscas en internet y no encuentras bien?');
  un('ecom', 'ec2_compe', 'Estudiar la competencia en línea', 'ecom_precio', ['Se revisan precio, gastos de envío, plazos, fotos y reseñas de las tiendas rivales.', 'Las quejas repetidas de sus clientes son oportunidades.', 'No siempre gana el más barato: cuentan la rapidez, la confianza y la atención.', 'Una tabla comparativa ayuda a decidir en qué ser distinto.'], ['competencia', 'precio', 'plazo de entrega', 'reseñas', 'diferenciación'], 'V:Las quejas ajenas son oportunidades.|F:Siempre gana el más barato.|V:La confianza también vende.', ['Haz una tabla con tres tiendas rivales.', 'Elige en qué te diferenciarás.'], ma('Comparar', ['precio', 'envío', 'plazo', 'fotos', 'reseñas']), '¿Por qué compras en una tienda y no en otra?');
  un('ecom', 'ec2_fulfill', 'Preparar y enviar pedidos', 'ec2_pedido', ['El fulfillment es todo lo que pasa desde que entra el pedido hasta que llega: preparar, embalar y enviar.', 'Puede hacerse en casa, en un almacén propio o con un operador logístico.', 'Un embalaje bien pensado evita roturas y reduce el peso volumétrico.', 'Cada pedido tiene un costo que hay que incluir en el precio.'], ['fulfillment', 'preparación', 'embalaje', 'operador logístico', 'costo por pedido'], 'V:El embalaje influye en el costo.|F:El fulfillment solo es el transporte.|V:Se puede externalizar a un operador.', ['Calcula el costo de preparar y enviar un pedido.', 'Diseña el embalaje de tu producto.'], fl(['pedido', 'preparar', 'embalar', 'etiquetar', 'enviar']), '¿Cuánto cuesta de verdad cada paquete que envías?');
  un('ecom', 'ec2_inventario', 'Gestionar el inventario', 'ec2_rota', ['El inventario es dinero parado: comprar de más inmoviliza caja.', 'La rotación indica cuántas veces se vende y repone el stock en un año.', 'El análisis ABC separa los productos que más venden de los que casi no se mueven.', 'Contar el stock cada cierto tiempo evita vender lo que no hay.'], ['inventario', 'rotación', 'análisis ABC', 'stock de seguridad', 'recuento'], 'V:El inventario inmoviliza dinero.|F:Cuanto más stock, mejor.|V:El análisis ABC ordena por ventas.', ['Clasifica diez productos con el método ABC.', 'Calcula la rotación de tu inventario.'], ci(['comprar', 'almacenar', 'vender', 'contar', 'reponer']), '¿Qué producto tienes guardado desde hace meses?');
  un('ecom', 'ec2_atencion', 'Atención que fideliza', 'ecom_devol', ['Responder rápido es lo que más valoran los compradores en línea.', 'Unas respuestas preparadas para las preguntas frecuentes ahorran tiempo.', 'Un problema bien resuelto genera más confianza que un pedido sin incidencias.', 'Pedir una reseña después de la entrega aumenta las valoraciones.'], ['atención al cliente', 'tiempo de respuesta', 'preguntas frecuentes', 'incidencia', 'reseña'], 'V:La rapidez es muy valorada.|F:Las quejas deben ignorarse.|V:Pedir reseñas aumenta las valoraciones.', ['Escribe cinco respuestas a preguntas frecuentes.', 'Redacta el mensaje para pedir una reseña.'], fl(['pregunta', 'respuesta', 'solución', 'seguimiento', 'reseña']), '¿Cuánto tardas en contestar un mensaje de cliente?');
  un('ecom', 'ec2_transporte', 'Elegir transportista', 'ecom_envio', ['Se comparan precio, plazo, cobertura, seguimiento y cómo gestionan las incidencias.', 'Muchos transportistas cobran por el mayor entre peso real y peso volumétrico.', 'Los puntos de recogida suelen ser más baratos que la entrega a domicilio.', 'Negociar tarifas es posible cuando se envían muchos paquetes al mes.'], ['transportista', 'cobertura', 'seguimiento', 'punto de recogida', 'tarifa'], 'V:Se cobra por el mayor entre peso real y volumétrico.|F:Todos los transportistas cuestan lo mismo.|V:Con volumen se pueden negociar tarifas.', ['Compara dos transportistas de tu país.', '¿Ofrecerías punto de recogida? ¿Por qué?'], ma('Transportista', ['precio', 'plazo', 'cobertura', 'seguimiento', 'incidencias']), '¿Qué pasa si el paquete llega tarde?');
  un('ecom', 'ec2_roi', 'El retorno de la inversión', 'ec2_roi', ['El ROI compara lo que ganas con lo que invertiste.', 'Se calcula restando la inversión al beneficio y dividiendo entre la inversión.', 'Sirve para comparar campañas, productos o mejoras de la tienda.', 'Un ROI negativo indica que se perdió dinero y hay que cambiar algo.'], ['ROI', 'inversión', 'beneficio', 'comparar', 'rentabilidad'], 'V:El ROI compara ganancia e inversión.|F:Un ROI negativo es una buena señal.|V:Sirve para comparar campañas.', ['Calcula el ROI de dos campañas y elige una.', '¿Qué mejora de tu tienda tendría mejor ROI?'], fl(['inversión', 'resultado', 'beneficio', 'ROI', 'decisión']), '¿Qué inversión te devolvería más dinero?');

  /* Contexto de sector: cada enunciado se sitúa en un negocio distinto, así el mismo cálculo no se lee
     igual cincuenta veces. Solo toca ítems con enunciado de texto; las páginas que devuelven otros
     objetos pasan intactas. Se aplica también a los generadores de los módulos anteriores. */
  var CTX = {
    empre: ['En un taller de velas', 'Para una panadería de barrio', 'En un salón de belleza', 'En un negocio de piñatas', 'Para una academia de clases particulares', 'En un taller de costura', 'En un puesto de comida', 'Para un servicio de reparaciones', 'En una tienda de bisutería', 'En un taller de cerámica', 'Para una juguería', 'En un estudio de fotografía'],
    mkt: ['Para una cafetería de barrio', 'En la campaña de una floristería', 'Para una academia de idiomas', 'En una tienda de ropa infantil', 'Para una clínica dental', 'En la web de un gimnasio', 'Para una librería', 'En la campaña de una óptica', 'Para un taller mecánico', 'En la tienda en línea de cosmética natural', 'Para una agencia de viajes', 'En una pastelería artesanal'],
    ia: ['En una gestoría', 'En una clínica veterinaria', 'En una tienda de electrónica', 'En una academia en línea', 'En una inmobiliaria', 'En un restaurante', 'En un despacho de abogados', 'En una empresa de transporte', 'En una farmacia', 'En un centro de atención al cliente', 'En una biblioteca', 'En un taller de impresión'],
    redes: ['En la cuenta de una floristería', 'Para el perfil de una academia de baile', 'En el canal de una creadora de recetas', 'En la cuenta de un taller de bicicletas', 'Para el perfil de una tienda de plantas', 'En el canal de un profesor de guitarra', 'En la cuenta de una peluquería', 'Para el perfil de una entrenadora personal', 'En la cuenta de una librería', 'En el canal de un viajero', 'En la cuenta de una repostera', 'Para el perfil de un fotógrafo de bodas'],
    ecom: ['En una tienda en línea de cerámica', 'Para una tienda de café de especialidad', 'En un comercio de ropa deportiva', 'En una tienda de juguetes de madera', 'Para una marca de cosmética natural', 'En una tienda de repuestos', 'En una tienda de libros usados', 'Para una marca de bolsos artesanales', 'En una tienda de productos para mascotas', 'En una tienda de papelería', 'Para una marca de velas aromáticas', 'En una tienda de material de pesca']
  };
  var PROPIO = /^(YouTube|TikTok|Instagram|Facebook|Telegram|WhatsApp|Google|Amazon|Mercado|Shopify|ChatGPT|IA|ROAS|CTR|CPC|CPM|CAC|LTV|ROI|IVA|RPM|UGC|OMS|[A-Z]{2,})\b/;
  /* Une las frases del enunciado con «;» para que el contexto forme parte de toda la oración. */
  function unir(e) { return e.replace(/\. (¿?)(Si|Un|Una|El|La|Los|Las|Cada|Tu|Tus|Con|Para|De|Hay|Tienes|Usas|Vendes|Compras|Cuántos|Cuánto|Cuántas|Qué|Cuál|Calcula|Empiezas|Metes|Necesitas|Quieres|Sin|En|Al|Por|Después|Luego|Cuesta|Cobras|Todo|Todos|Así|Ahora|Y|A|Con)\b/g, function (m0, q, w) { return '; ' + q + w.toLowerCase(); }); }
  function conCtx(fn, mat) {
    if (!fn || fn.__ctx) return fn;
    var w = function (u, C, r) {
      var x = fn.apply(this, arguments);
      if (!x || typeof x.e !== 'string' || !x.tipo || typeof r !== 'function' || x.__c) return x;
      x.__c = 1;
      var L = CTX[mat], c = L[Math.floor(r() * L.length)], e = unir(x.e);
      if (e.charAt(0) === '¿' || e.charAt(0) === '¡') x.e = c + ', ' + e.charAt(0) + e.charAt(1).toLowerCase() + e.slice(2);
      else x.e = c + ', ' + (PROPIO.test(e) ? e : e.charAt(0).toLowerCase() + e.slice(1));
      return x;
    };
    w.__ctx = 1; return w;
  }
  function envolver(src, mat, pref) {
    if (!src) return {}; var o = {};
    Object.keys(src).forEach(function (k) { if (pref && !pref.test(k)) return; src[k] = conCtx(src[k], mat); o[k] = src[k]; });
    return o;
  }
  var MI = window.EU_MKT_IA, EMP = window.EU_EMPRE, RS = window.EU_REDES, EC = window.EU_ECOM, W = {};
  [envolver(EMP && EMP.GEN, 'empre', /^emp_(costos|precio|margen|equilibrio|ganancia|roi|iva|hora|capital|escenario|smi|flujo)$/), envolver(MI && MI.GEN, 'mkt', /^mkt_/), envolver(MI && MI.GEN, 'ia', /^ia_/), envolver(RS && RS.GEN, 'redes', /^redes_/), envolver(EC && EC.GEN, 'ecom', /^ecom_/)].forEach(function (o) { Object.keys(o).forEach(function (k) { W[k] = o[k]; }); });
  Object.keys(G).forEach(function (k) { var mat = /^emp2_/.test(k) ? 'empre' : /^mkt2_/.test(k) ? 'mkt' : /^ia2_/.test(k) ? 'ia' : /^rs2_/.test(k) ? 'redes' : 'ecom'; G[k] = conCtx(G[k], mat); });

  ED.registrar({ unidades: U, generadores: Object.assign(W, G) });
  window.EU_UNIDADES_ADULTOS = { U: U, GEN: G, CTX: CTX };
})();
